### PR TITLE
loar2-hsamanci: Presentation proposal, week 8

### PR DESCRIPTION
**Pull request by Leysannn**
# Assignment Proposal

## Title

Data privacy and DevOps

## Names and KTH ID

  - Ley-Olivia Avila Rojas (loar2@kth.se)
  - Håkan Samanci (hsamanci@kth.se)

## Deadline

- Week 8

## Category

- Presentation

## Description

In this presentation, we will explore the intersection of data privacy regulations, such as the General Data Protection Regulation (GDPR) and the Health Insurance Portability and Accountability Act (HIPAA), and their impact on DevOps practices. 
We will discuss the challenges organizations face in implementing DevOps workflows while ensuring compliance with these regulations. In particular, we will analyze data storage, processing and sharing.

**Relevance**

The importance of discussing data privacy regulations like GDPR and HIPAA within the context of DevOps is due to the increasing emphasis on data privacy and security in today's digital landscape. 
Organizations implementing DevOps must ensure that they comply with these regulations to safeguard their users' data and avoid any legal or financial consequences.
In conclusion, addressing data privacy regulations in DevOps is essential due to the need to protect user data, fulfill legal requirements, and establish a culture of privacy awareness within organizations.
Complying with these regulations can enhance an organization's reputation, improve overall security, and provide a competitive edge in the market.

### CODE REVIEW

**Comment by javierron** [comment]
Hello @Leysannn. There are two problems with this PR.
1. The presentation was already [proposed for week 7](https://github.com/KTH/devops-course/pull/2250)
2. The PR changes 2 different readme files.
 
Did you open this by mistake?

**Comment by Leysannn** [comment]
Hi! 
We were supposed to present it this week, however due to a lot of presentations/demos we changed it for week 8 (discussed with Martin & Benoit).

**Comment by javierron** [comment]
@Leysannn I see. Can you make sure that you remove the file from week 7 then? Thanks!

**Comment by SandZn** [comment]
Hi, I've added your presentation to the week 8 schedule. You will be the first one to give your presentation.

**Comment by SandZn** [comment]
Presentation done.

**Pull request closed without merging**
