### PR TITLE
Video demo submission

### PR DESCRIPTION
**Pull request by m4reko**
Our video demo is available [here](https://youtu.be/DdCsPe-yvXE). We also have a repo containing the sample project which can be found [here](https://github.com/m4reko/laras-app).

The proposal can be found in PR #967.

We are ready for merge @SophieHYe

### CODE REVIEW

**Comment by andnil5** [comment]
**Great job with the demo. This is high-quality stuff! I've added some comments and suggestions below.**
 
**Positive points**

* I liked the introduction. It was fun and caught my attention!
* Nice with voice-over. It makes the demo easy to follow.
* Nice graphics and interactions. It makes the demon very much" alive" and entertaining to watch. 

**Possible improvements**

* The slide at 0:37 flies by quite fast and only the first point of the list is mentioned. Consider increasing the timeframe for this slide and mention the other points of the slide, or simply removing them.
* The console was often filled with output from previous commands, which was a bit disturbing while watching. Also, it was hard to see the commands which were entered since they appeared at the very bottom of the screen.
* It would have been nice to get more information about Google Cloud Functions and how to use them. I know that the timeframe is short, and it is tough to fit much information in 3 minutes. Maybe you could shorten the introduction and the project setup parts to give more space for this?
* Consider adding the pointers you have in the repo in the video description as well.

**Comment by Internet-Person-IP** [comment]
Great Video but can need a small thing.

Pros:
1. Amazing Narrative: The narrative was great and made it so that you wanted to take part in the journey. Because obviously, I want to build a react app and host it as well.
2. Clear Procedure: Really Good step-by-step procedure for understanding how to initialize and build the actual software.
3. Really good presentation of the topic. Makes the new topic a super clear way of learning about serverless functions.

Improvements:
1. I am a little confused because I got the impression that this video will show how the deployment of the frontend would be and from what I saw there was a focus on leveraging firebase functions but not really how it is being deployed. I know that you probably have some time constraints but I think it would be cool just seeing how deployed react app. But maybe that's just me.

**Comment by fwallb** [comment]
Great video, I would definitely continue watching if wanted to learn about Firebase and I clicked on it on Youtube! 

**Strengths**
- The slides are nice and the content is well thought through. 
- The voiceover is clear.
- The speed of the video is great which makes it easy to follow.
- Good text size in the terminal and editor.

**Potential improvements**
- The text written in the terminal is sometimes covered by the text, which could make it harder to follow if you want to watch with subtitles.

**Comment by Atema** [comment]
Great job! The demo's fun to watch and easy to follow the steps. I really liked that you switched between video, information, and demonstration fluently.

I think that the part in the terminal was a bit too fast sometimes, with lots of text on the screen. It seems like you have 6 seconds left, so you could try to add some short pauses between the commands.

**Comment by patricia-naccachian** [comment]
The video is very good! The outline was very well constructed and steps are easy to implement. The voice was clear, the information was nice to learn and the visuals are enjoyable but I think there should be more focus on explaining how it is related to DevOps.

**Comment by dmariel** [comment]
Congratulations to an extremely well made demo, there is not much to improve from what I can see! I really like that you use a persona "Lara" to illustrate the user cases and motivation of using the tool (i.e. scaling), since this made the video more personal and easier to absorb. Moreover, returning to the camera in the end of the video is a nice way of concluding the video! Furthermore, I think that the background information was sufficient, that the video was sublime and that the voice over was very clear. 

Some suggestions for improvement would be to slow down the coding sections slightly (i.e. the terminal output), since I noticed that you have 6 seconds left. I found myself rewinding the video a few times in order to follow what was written in the terminal, so I believe extending the time scope would make it easier for the viewers to follow the video. I also liked that you provided two alternatives for calling cloud funcitons. However, perhaps, you could offer your view on which alternative is to be preferred? Furthermore, you could perhaps divide the video into clickable sections on the YouTube timeline (i.e. I saw this in [this video](https://www.youtube.com/watch?v=GQ9qroAbqr4)).

**Pull request merged**
