### PR TITLE
Feedback

### PR DESCRIPTION
**Pull request by simonebonato**
# Final Submission: Feedback for Executable Tutorial #1942

## Title

Feedback on executable tutorial "Automated email notification for IP change in SSH server"

## Names and KTH ID

- Vishal Nedungadi (vishaln@kth.se)
- Simone Bonato (bonato@kth.se)

## Deadline

Task 5

## Category

Feedback

## Description

We want to give feedback on the executable tutorial [Automated email notification for IP change in SSH server](https://github.com/KTH/devops-course/pull/1844) by Ennio Rampello.

**Link to executable tutorial prooposal PR** (https://github.com/KTH/devops-course/pull/1942)

**Executable Tutorial author**
- Ennio Rampello (ennio@kth.se)

**Final Submission**
Link to Feedback comment: https://github.com/KTH/devops-course/pull/1844

### CODE REVIEW

**Comment by khesoem** [comment]
It seems you have changed the folder name from `vishaln-bonato` to `bonato-vishaln`. You shouldn't change the folder name.

**Comment by khesoem** [comment]
@simonebonato Do you intend to fix the issue with your PR? Without fixing it we cannot grade your work.

**Comment by simonebonato** [comment]
@khaes-kth I'm sorry I did not see I had the error 
Do you have any idea on how to fix it? Because it says I am already registered for an a Feedback but it's my first one...

**Comment by khesoem** [comment]
As I mentioned before:

It seems you have changed the folder name from vishaln-bonato to bonato-vishaln. You shouldn't change the folder name.

**Comment by simonebonato** [comment]
Ok @khaes-kth I made the changes, sorry for the trouble

**Pull request merged**
