### PR TITLE
Presentation proposal, Smart contracts

### PR DESCRIPTION
**Pull request by c-cret**
# Assignment Proposal

## Title

Tokenization of Physical Resources and Services.

## Names and KTH ID
  - Mateo Florez (mateofc@kth.se)
  - Gabriel Acar (gacar@kth.se)

## Deadline

Task 1

## Category

Presentation

## Description

The presentation will cover the Tokenization of Physical Resources and Services in general and how it works, it will also cover why one should Tokenize assets and what the Tokenization process looks like. Some applications in DevOps could be: 

- Controlling code flow automatically by relying on smart contracts as gatekeepers during continuous delivery, with increased transparency of errors.
- Enforcing SLA contracts as a functionality guarantee for software.

We aim to hold the presentation on the 19th of April.

### CODE REVIEW

**Comment by c-cret** [comment]
How long should one wait??

**Comment by vladomit** [comment]
Hi, your README.md shoud be in a group name folder, and you should fetch the upstream

**Review by c-cret — COMMENTED** [review]
@vladomitrovic It is in a group folder, fetched the upstream swell 👍

**Comment by Deee92** [comment]
Hi @c-cret, do you still intend to present tomorrow? If yes, can you add more detail to your description, as well as a brief discussion on how it relates to DevOps?

**Comment by c-cret** [comment]
Hi @Deee92, Well that was the initial plan hehe, but no, we aim to present the next time 👍 . I extend the description shortly.

**Comment by c-cret** [comment]
Hi @Deee92, updated the README :)

**Comment by Deee92** [comment]
Hi @c-cret, thanks for the update!

**Pull request merged**
