### PR TITLE
Essay submission for feedback: Low-code Ops and the art of abstraction

### PR DESCRIPTION
**Pull request by glidfeldt**
Propsal PR #1205

## Members
Gustaf Lidfeldt
Email: lidfeldt@kth.se
Github: @glidfeldt 

Isak Hassbring
Email: isakha@kth.se
Github: @hassbring

### CODE REVIEW

**Comment by glidfeldt** [comment]
Hey @johanmallobakken , this is our first draft. Looking forward to your feedback :)

**Comment by johanmallobakken** [comment]
> Hey @johanmallobakken , this is our first draft. Looking forward to your feedback :)

Great! I will submit your feedback within 24 hours :)

**Comment by johanmallobakken** [comment]
I have submitted the feedback! You can find it at #1403 :) @glidfeldt @hassbring

**Comment by johanmallobakken** [comment]
# Feedback on the essay “Low-code Ops and the art of abstraction” #1205

Adding the feedback as comment here too. 

This is the feedback on [#1205](https://github.com/KTH/devops-course/pull/1205), an essay on Low-code Ops and the art of abstraction. Written by Gustaf Lidfeldt, [glidfeldt](https://github.com/glidfeldt), lidfeldt@kth.se and Isak Hassbring, [hassbring](https://github.com/hassbring), isakha@kth.se.

## Relevant Pull Requests

Original proposal: [#1205](https://github.com/KTH/devops-course/pull/1205)

Essay submission for feedback: [#1396](https://github.com/KTH/devops-course/pull/1396)

## Members
Johan Mallo Bakken (johanmb@kth.se)
Github: [johanmallobakken](https://github.com/johanmallobakken)

## Strengths

First of all, I want to say that you guys have done great work with this essay. It was super interesting to read through and I learned a lot of new and exciting things. Especially learning about Peltarion was a part that I really enjoyed. The reason this article was a pleasant read is because of the joyful and vivid language used in it, but also the structure of the essay is really good and made me want to continue reading to the next sections. The topic of choice is also super interesting. 

The introduction to the essay is very creative and fun. I like the way you smoothly managed to introduce the concept of abstraction by using the very beginning of programming languages as an example, only to then further introduce today's no code / low code platforms. Another part of the text I want to applaud you for is the part where you discuss the limitations of no code / low code, this allows the reader to get the full picture and also to formulate his / her own opinions. 

## Potential Improvements

Although this is a great essay, my task is to give some constructive criticism for you to further improve this essay. I will touch upon some general problems and I will also delve into more smaller issues that can easily be solved like grammatical errors or specific sentences. 

So the first thing I would like to cover is regarding the images in the essay. I noticed quite early on in the process of reading the essay is that some of the images don’t have any captions or text that gives them an explanation. This is something I missed in for example the figure showing RAD (Rapid Application Development), where I would have liked to have a bit more of an explanation on what I’m seeing. Another image that could be improved is the first image on the subsection about Peltarion. This image is messy and contains a lot of text in other fonts. This could maybe have been presented in a more tidy manner. My suggestion here would be to crop the image and keep the bottom half. Then you can maybe cut out the three icons on the top and have them as separate smaller images on the side of the text while explaining their contents as part of the introduction to Peltarion. This would at least make it more visually pleasing to read. If not, the average reader will probably skip the small text on the image. 

In general the section of the Peltarion tutorial could be done more pleasant to read through with some simple restructuring of the text and the images. I’m sure this is something that will not take long to improve. 

Another general point I want to make is that although the article's topic is very interesting it at some points struggles to link to DevOps. There is one subsection regarding the DevOps perspective in all of this, but in some of the other parts I would say there is a bit of a lacking link. In my opinion either the section regarding the DevOps perspective should be reinforced with a more stable link to DevOps or the other parts of the article should be sprinkled with a more DevOps centered viewpoint. Although Peltarion and Figma are very interesting products and I see their relation to MLOps and DevOps respectively, I do also think there are other interesting products that hit right on the spot for this topic. I found them on this [article](https://www.opcito.com/blogs/how-low-code-can-fit-into-the-devops-culture). It would have been interesting to hear about for example [Appian](https://appian.com/) or [Mendix](https://mendix.com/) in your essay.

The sources are a bit unorganized, they should follow the same format in the source list and there are some pieces of text scattered across the essay that could use some sources to back it up. 10 is the minimum amount of sources, an article this length should probably have quite a few more. 


## Summarized actionable improvements
* Sources - restructure, follow Harvard or similar, get/find more sources.
* Fix images, give them text explaining to the reader what they are seeing.
* Restructure the practical examples part. Maybe even look into some of the products mentioned in this [article](https://www.opcito.com/blogs/how-low-code-can-fit-into-the-devops-culture) that might be interesting to cover.
* Link the article even more to DevOps. Maybe by strengthening the link in the DevOps perspective section. 

## Smaller Grammar / Spelling / Structural improvements

This section contains some improvement suggestions, some of them might just be personal preferences.

* “Where” should be replaced with “were” in the second paragraph.
* In the second paragraph, the sentence about Excel could be tethered more smoothly into the text. Maybe something like “One example is the computer program Excel which lets ‘the average Joe’ compute calculations without any programming skills whatsoever.”
* Also the last sentence in this same paragraph is a bit confusing as the fourth generation of programming languages was said to be emerging between the 70’s and 90’s. This sentence says, “The fourth-generation of programming languages has to today emerged...”.
* The paragraph under the RAD image might suit better on the beginning of the subsection “Low code abstraction”, just to make the terminology clear from the beginning. 
* Automate can be changed to automates. 
* Personally I don’t think the quote from  Mike Duensing does not add much value, it could probably be removed if you need to reduce the word count. 
* The introduction to the practical examples page is quite vague, it should elaborate more. practical examples of what?
* It might not be obvious what Wallenberg and EQT are for non-swedish readers. 
* Point 4 in the Peltarion tutorial. There is missing a “to” in between “time” and “define”. 
* Point 6 in the Peltarion tutorial. It should be through and not though.

**Comment by khesoem** [comment]
Final submission: #1462

**Pull request merged**
