### PR TITLE
Feedback submission

### PR DESCRIPTION
**Pull request by Wizkas0**
Feedback given on: #1351

### CODE REVIEW

**Comment by SophieHYe** [comment]
Thanks for the feedback submission. Could you please solve the conflicting file? Thanks.

**Comment by Wizkas0** [comment]
I don't see what the conflict is though, it looks like github thinks I'm replacing a sentence with an identical sentence, so I don't see the conflict.

**Comment by Wizkas0** [comment]
> Thanks for the feedback submission. Could you please solve the conflicting file? Thanks.

@SophieHYe It is now resolved.

**Comment by SophieHYe** [comment]
Thanks, merging it now.

**Pull request merged**
