### PR TITLE
Week 3: Presentation proposal

### PR DESCRIPTION
**Pull request by TobCarl**
# Assignment Proposal

## Title

The importance of containerization 

## Names and KTH ID

- Tobias Carlsson (tocarls@kth.se)
- Siham Shahoud (shahoud@kth.se)

## Deadline

- Week 3

## Category

- Presentation

## Description

In this presentation, we will explore the fundamentals of containerization and its significance in modern DevOps practices. We'll start by discussing Docker, a leading containerization platform, and how it enables developers to package applications with all their dependencies for consistent deployment across various environments. We will then delve into Kubernetes, a powerful orchestration tool that automates the deployment, scaling, and management of containerized applications. This presentation will highlight how containerization accelerates development, reduces infrastructure costs, and enhances collaboration between development and operations teams, making it an essential component of the DevOps toolchain.

**Relevance**

Understanding these technologies is crucial for anyone looking to optimize software delivery pipelines, achieve greater agility, and maintain robust and scalable cloud-native applications.

EDIT: 
We will also compare strengths and weaknesses of Kubernetes and Docker

### CODE REVIEW

**Comment by algomaster99** [comment]
Hi! Thanks for the proposal! Could you also add comparison (strengths and weakness of Kubernetes and docker) also?

**Comment by TobCarl** [comment]
Yes that sounds good!

**Comment by algomaster99** [comment]
Great, merging :tada:

**Comment by algomaster99** [comment]
A piece of advice for your future open source contributions. Always create a branch on your fork before submitting a PR in order to avoid merging issues later.

**Pull request merged**
