### PR TITLE
Open source contribution proposal - Python Discord Bot

### PR DESCRIPTION
**Pull request by Autonymic**
# Assignment Proposal

## Title

Contributing to a python discord bot

## Names and KTH ID

- Tony Le (ttle@kth.se)

## Deadline

Deadline for task 5

## Category

Contribution to open-source

## Description

The discord bot is made for the Python Discord server. It is written in Python and makes use of Docker to run.
I'd like to contribute to this project as I think software bots are useful and I will learn how to set them up through this task.
This is related to DevOps as it falls under software bots.
The project should be fine to choose as it has more than 10 stars, more than 100 commits and a pretty active community on GitHub with the last merged pull request being merely 4 days ago.
I would like to work on two issues that are related:

https://github.com/python-discord/bot/issues/2171

https://github.com/python-discord/bot/issues/2170

The first is a bug that requires adjusting a command that should be able to take multiple users as arguments, but for now it only accepts one.
The second follows up on it by cleaning up the help text for the command, so it should be considered as adding to the documentation.
There is also a decent possibility of the contribution being merged as well.

### CODE REVIEW

**Comment by Autonymic** [comment]
@javierron 
Hi, as discussed in email I'd like to change my proposal as permission has been granted. I am also alone now for this task. I saw that you were active so I am hoping you can check this out as soon as possible.

**Comment by javierron** [comment]
Hello @Autonymic, your task proposal is approved. You can start working on it as usual, The PR will not be merged just yet, but don't worry about it.

**Comment by javierron** [comment]
Hello @vladomitrovic,

The action is failing because this use case (task change) was not considered. Would it be safe to merge?

**Comment by vladomit** [comment]
Hi, you should first manually delete the previous group on canvas. And then merge it.

________________________________

**Pull request merged**
