### PR TITLE
Presentation: Using Ansible

### PR DESCRIPTION
**Pull request by jadlers**
I'm planning on giving a presentation on Ansible and how it can be used to manage configuration in week 4. If someone else is interested in the same topic let me know, we could potentially collaborate.

### CODE REVIEW

**Comment by ashgreyship** [comment]
Since Ansible is a tool related to CD, i'm interested in it. If you still look for a partner, please send me an email, dingli@kth.se

**Comment by jadlers** [comment]
@ashgreyship I sent you an email!

**Comment by SophieHYe** [comment]
Hi, please update your PR with your partner's name and with the suggested information:
in your folder, create a README.md file and put there:
the planned topic, which must be focused enough
a short statement (1-3 sentences) about the relevance and timeliness for testing and devops
bullet outline of the presentation. 

Thanks!

**Comment by jadlers** [comment]
@SophieHYe We'll work on improving the readme this evening!

**Comment by SophieHYe** [comment]
Nice presentation topic, I will merge the PR.

**Pull request merged**
