### PR TITLE
Final submission

### PR DESCRIPTION
**Pull request by Wkkkkk**
This pr includes the final version of the essay proposal. 
The initial [proposal](https://github.com/KTH/devops-course/pull/1031) and a conflicted submission [proposal](https://github.com/KTH/devops-course/pull/1379) can be found in the link.

Feedback from [Ayub Atif](https://github.com/KTH/devops-course/pull/1379#issuecomment-827968781) and [Isac Arvidsson](https://github.com/KTH/devops-course/pull/1379#issuecomment-827652214) has been submitted.

### CODE REVIEW

**Comment by Wkkkkk** [comment]
Sorry for this confusion.

**Comment by khesoem** [comment]
Hi @Wkkkkk 

Can you please explain the difference between this PR and #1379. I remember we discussed something in the lab session, but I don't exactly remember what was the problem.

**Comment by Wkkkkk** [comment]
Hi @khaes-kth 

Sorry for this mess. PR #1379 includes the initial essay and some peers have given their feedback on that version. When I was creating this RP, my feedback on another essay was also committed by mistake, which results in a conflict.  After I read the feedback and polished my essay, I made this new PR to submit the final version of the essay.

**Comment by Wkkkkk** [comment]
The merged essay at this moment is actually the initial one. I really appreciate your help if the final version attached to this PR could be merged.

**Comment by khesoem** [comment]
Hi @Wkkkkk 

Let's do it the simple way. Save your latest changes in your computer. Unfork the repo, fork it again, clone the new forked version, copy the latest changes to the repo, push it and create a new PR. When you have done these, ping me in the new PR.

If you can fix this PR to only change the `essay` folder and resolve the conflict, it is great. If not, do it the simple way.

**Pull request closed without merging**
