### PR TITLE
mrhasa@kth.se new folder

### PR DESCRIPTION
**Pull request by MDRezaulHasan**
Creating a new folder and in this folder, I will present my automation testing materials.

### CODE REVIEW

**Comment by SophieHYe** [comment]
Hi,
Thanks for your PR and for presenting automated testing.
Could you please add a short statement (1-3 sentences) about the relevance and timeliness for testing and devops and bullet outline of the presentation?

**Comment by gluckzhang** [comment]
@MDRezaulHasan , please note that the name of the folder you created should be `mrhasa`. No need to add the `@kth.se` part :)

**Comment by MDRezaulHasan** [comment]
I changed my folder name.

**Comment by MDRezaulHasan** [comment]
I make some bullet point which I am going to describe and a short
description.

**Comment by SophieHYe** [comment]
Hi,
Thanks for your update, I am merging your PR.

**Pull request merged**
