### PR TITLE
Presentation Proposal: AI Code Completion with Tabnine

### PR DESCRIPTION
**Pull request by ChristopherGustafson**
# Presentation Proposal: AI Code Completion with Tabnine

## Members

Axel Pettersson (axp@kth.se)
Github: [Ackuq](https://github.com/Ackuq)

Christopher Gustafson (chrigu@kth.se)
Github: [ChristopherGustafson](https://github.com/ChristopherGustafson)

## Proposal

We would like to hold a presentation about [Tabnine](https://www.tabnine.com/). Tabnine is a code completion tool that uses AI to give accurate predictions about what code the user wants to type. That way Tabnine can save time by speeding up the process of manually typing code as well as having to look up different code constructions. 

The specific topics we would like to cover are:
* What is code completion?
* How the Tabnine tool uses AI to make code predictions
* How you can use the Tabnine tool 
* How Tabnine can improve your workflow

### CODE REVIEW

**Comment by khesoem** [comment]
Hi @ChristopherGustafson 

Your topic is new and interesting. However, I do not see how it is related to DevOps. Can you elaborate on that?

**Comment by Ackuq** [comment]
Hi @khaes-kth,

I would say that it is related to DevOps as the fundamental purpose of it is to make developers more efficient at writing code and boost productivity.

You can relate this to the definition of DevOps presented  by [Atlassian](https://www.atlassian.com/devops/what-is-devops):

> DevOps is a set of practices that works to automate and integrate the processes between software development and IT teams, so they can build, test, and release software faster and more reliably.

Making developers more efficient will (most likely) result in faster integrations of changes, thus being able to release these changes faster.

We could also relate this to the "automation" part of DevOps, as this tool (partially) automates the process of writing code.

Of course, there's a lot of parts of DevOps that is not covered by this technology, but I hope this is sufficient. Otherwise we can always change.

**Comment by khesoem** [comment]
Hi @Ackuq ,

I'm still not sure. It is related to DevOps but it is more related to efficient programming in general.

@cesarsotovalero, @Deee92  What do you think about this presentation proposal? Is it in the scope of DevOps?

**Comment by ChristopherGustafson** [comment]
Hi @khaes-kth , 

Yes we realized that it might be  a bit of a stretch. We will decide on a different topic and redo the PR.

**Comment by khesoem** [comment]
> Yes we realized that it might be a bit of a stretch. We will decide on a different topic and redo the PR.

Good. We are looking forward to your new proposals.

**Pull request closed without merging**
