### PR TITLE
Submission: Pijul (tutorial)

### PR DESCRIPTION
**Pull request by ysndr**
# Submission of the tutorial on pijul.

Follows #1189 

Awaiting review to be incorporated before the deadline.

Self-assessment based on grading guidelines:

|                                             |Yes? + Comment | Remarkable? + Comment |
|-------------------------------------------- | ----|----|
|The TA can successful execute all the commands of the tutorial (mandatory) | ✓ |✓ In the browser |
|If local execution, runs on Linux | ✓ using docker or building from source)  | Easy to setup and run (✓ docker) |
|The tutorial gives enough background | ✓ assuming basic knowledge about git | ✓ concepts of git and pijul explained indetail for each operation|
|The tutorial is easy to follow  | ✓ (content based steps) | ? |
|The tutorial is original, no such tutorial exists on the web | ✓ | ✓ we doubt anyone has heard about it |
|The tutorial contains [easter eggs](https://github.com/OrkoHunter/python-easter-eggs) | Yes (inspect the files produced during the challenge) | ? you decide |
|The tutorial is successful (attracts comments and success) | ? | ? |
|The language is correct | Oui |   |

### CODE REVIEW

**Comment by ysndr** [comment]
@khaes-kth I think you were the assigned TA to this task.
We do not yet have any student to give feedback to our tutorial so we would appreciate TA feedback if applicable

The github URL is https://github.com/ysndr/katacoda-scenarios
The Tutorial is available here: https://www.katacoda.com/ysndr/scenarios/pijul

**Comment by khesoem** [comment]
Hi @ysndr ,

Fine, I'll try to give you some feedback until tomorrow.

**Comment by khesoem** [comment]
Hi @ysndr 

Thank you for the tutorial. Very useful and interesting. Here are my comments;

Very good introduction. The figures look too large on my computer, I do not know if you can fix them.

## Step 1:

> Initializing **an** new project.

Typo.

## Step 2:

You say:

> If you want to skip the add part you can record files directly running e.g.: pijul record ciao.txt

Does this mean `record` also runs `add`? I think this part can be made more clear. Also, I wonder if `record` is somehow similar to `commit` in git.

## Step 3:

> Notably about pijul is that changes, as long as they don't have dependencies, are commutative. That means that unlike git, which tracks edits in a linear log, the order in which the changes are applied does not matter as long as their dependencies are present. This makes pijul far more flexible!

Interesting. What are dependencies? That's the trickiy part I guess.

After continuing the tutorial, I realized you have discussed dependencies. The first time you mention `dependencies`, just note that it will be discussed later.

> Yet, unlike git not only latest changes can be amended:

The sentence can be improved.

> copy it to a to a

Typo.

It is better to tell the reader to choose a specific commit hash when running commands that require a HASH. What happened to me was that I revoked the first ciao commit and when I changed the same file and recoreded it I could not see the dependencies because the first commit was revoked.

## Step 4:

> if you create an account, you should be able to push the changes to the server with

As far as I remember, you did not ask the reader to create an account before. Please explain where I should create an account. You can just mention the registration process in 1-2 sentences (e.g., go to ... and register with your email and ....).

## Step 5:

> there is no clear graph between them -- remember: they commute 

I can guess what you mean, but it makes sense for you to make this sentence a bit more clear with explaining `commute` again.

> The we want to create a new channel bob

Typo.

>  pijul pull . --from-channel bob

It is better to tell the reader what to do when the editor is opened after running this command.

## Step 6:

> if you have used **teh** wrong pijul commands

Typo.

It is good to make the goal of the game clear. What should I expect to happen when I am done with the task?

**Comment by ysndr** [comment]
@khaes-kth thank you for the valuable feedback

**Comment by ysndr** [comment]
@khaes-kth the feedback was taken care of 4 days ago, shouldn't this PR be merged?

**Pull request merged**
