### PR TITLE
Final submission: Essay, DevOps in Finance

### PR DESCRIPTION
**Pull request by Gabriel-Acar**
# Assignment Proposal

## Title

Devops in finance

## Names and KTH ID
  - Gabriel Acar (gacar@kth.se)
  - Lucas Eren (leren@kth.se)

## Deadline

Task 4

## Category

Essay

## Description

We intend to cover the role of devops in the finance industry. Some topics that will be covered are, advantages/disadvantages of devops in finance, and obstacles when using devops in finance.

### CODE REVIEW

**Comment by Gabriel-Acar** [comment]
@c-cret You can start on your feedback now :)

**Comment by sandy-e** [comment]
# Feedback on "DevOps in Finance".
Here is @sandy-e's (sanherib@kth.se) and @c-cret's (mateofc@kth.se) feedback on the "Essay DevOps in Finance" by Gabriel Acar and Lucas Eren.
## High-level strengths and weaknesses of the essay
### Strengths
- The written language level is appropriate, clear, and easy to understand.
- The essay is realistic in applying DevOps to the finance sector; the authors realize that it is not an easy task nor is it free of disadvantages.
- Sources are numerous and properly cited.
- Mostly structurally sound

### Weaknesses
- “Disadvantages” section could benefit from refactoring
- Misses the mark slightly by not mentioning some reasons DevOps is not implemented in finance (discussed in feedback section “Further Thoughts”
- Could benefit from a grammar checker (but does not highly affect quality of the essay)

## Feedback per section
### Introduction
The introduction properly introduces DevOps, its history, why it was needed, and why it has grown in popularity. It then moves on to the finance sector in a smooth way and outlines why it is an important sector. The authors explain why digitalization and competitiveness are important in the sector and how DevOps could aid in those aspects. The introduction could benefit from mentioning more of how the financial sector systems are complex and thus slow to roll out new software releases, but this is done in other sections.
### Advantages
The advantages discussed are in line with DevOps' benefits. The sub-branches of DevOps mentioned are a good way of conveying the fact that DevOps is quite flexible and can be adjusted for individual organizations’ needs. Subsection 2.3 is quite interesting. Stating that digitalization of financial services is mostly limited to translating physical resources to digital ones ties in very nicely with the disadvantages in section 3. 
### Disadvantages
The introductory text is well-motivated on how DevOps can be without its advantages if not implemented properly, or even damaging to organizations. Discussing financial sector culture and how it may clash with DevOps is an important point that may not be immediately obvious. The second paragraph, about how the developer team and operations team may think differently on DevOps could be moved to its own subsection. Structurally, the essay might benefit from removing subsection 3.1 “Obstacles to overcome” and instead having 3.1 be “Culture” and 3.2 be “Complexity”. Right now  there is only one subsection in section 3 which looks a bit strange.
### Conclusion
Concludes the essay and the advantages and disadvantages of DevOps in finance. Not much to improve upon.
### Reflection
The reflection is honest about DevOps in finance. It is not too optimistic but the authors clearly still have hopes about DevOps being implemented where it is advantageous. Thus the section is well balanced around advantages and disadvantages.
## Further thoughts
Financial systems do not implement DevOps because their systems should not be fast-growing and aggressive. It takes time to develop reliable systems that can be used without problems. Financial organizations cannot push out many changes all the time. All changes and updates have to be carefully examined and tested before reaching the end customer. Otherwise, incidents like the one we saw with Swedbank may occur (SVT). 

Furthermore, one cannot just digitalize everything at once. It has to happen periodically for many reasons, including the one stated above. Another reason has to do with inclusivity. By digitalizing everything, the ones without access to the digital world get excluded. 
According to the Internet Foundation's report, Swedes and the Internet 2019, the number of people who do not use the internet daily amounts to just over 1 million. It is also about one in ten who do not use the Internet bank and almost two out of ten who do not use
BankID (Internetstiftelsen).

## Language
Proposal of corrections, actual text (left side), and correction (right side).

Note that these are some of the grammatical errors we found and we reserve us for the possibility of more errors.

### 1 Introduction
“Around the years 2007-2008 was” => The years 2007-2008 were.
 “making it one of the worlds” =>  world’s.
“banks, slow transformation lead to slower and more complex” => lead’s
“Finances are one for the largest industries” => of 
“trillion in the year 2021, growing at about 10% from” => trillion in 2021, growing by
“DevOps and the finance industry can be integrated with each other.” => Remove “with each other”
### 2 Advantages 
“DevOps concepts very versatile to fit the needs of the organization. This is why many different” => DevOps concepts very versatile to fit the **organization's needs**. Many different.
### 2.1 Quick Realization
“Quick realization of software projects are of great importance and can save” => Quick realization of software projects is essential and can save money and time.
“ Thus, it is the Ops that has the responsibility of the quality and they have a lot of impact on the” => Thus, the Ops has the responsibility for the quality, and they have much impact on the time it takes to release the new feature
“If the development team and the operational team works together” => **work**
### 2.2 Security 

“potential security problems, it has helped to tackle threats faster and it has helped to locate issues.” => potential security problems helped to tackle threats faster, and helped to locate issues. As a result.

Architecture and test-automation

“Some benefits that come with microservices architecture is that it helps to simplify” => Some benefits of a microservices architecture are that it helps simplify.

### 3 Disadvantages 

“There are few methods that are without fault, and DevOps is no exception” => Few methods are without fault, and DevOps is no exception.

### 3.1.1 Culture

“DevOps, when a company has those points, will lead to failure and thus a cultural change” => DevOps, when a company has those points, will lead to failure, and thus, a cultural change.

“the operational team is not as positive to DevOps.” => **about** DevOps.

“There needs to be a change in mentality **throughout** the workers, they” => **among**

### 3.1.2 Complexity 

“complexity and that it can affect a bunch of other systems and” => complexity, and it can affect a bunch of other systems and.

### 4 Conclusion

“and finally migrates many” => **migrating**

### 5 Reflection 

“to stay competitive in a fast moving market” => fast-moving
“decreases time from concept to release for products” => the time.

## Additional material
“A DevOps Implementation Framework for Large Agile-Based Financial Organizations” by Nagarajan, A., & Overbeek, S. is an interesting study on how financial based organizations may implement DevOps. They state that agile organizations show an interest in embracing DevOps in addition to working agile. Furthermore they state that while there exists quite a lot of literature on DevOps, they are either not specific to large-scale financial organizations or do not include the agile aspects. We think that this study is quite related to the essay and worth reading

Additionally, [this article](https://www.veritis.com/blog/devops-practices-a-catching-up-trend-in-financial-services-industry/ ) discusses similar issues to the ones brought up in the essay but also brings up trends and statistics for the financial market. 

## Works cited
**Internetstiftelsen. “Svenskarna och internet 2019.” Svenskarna och internet, 15 October 2019, https://svenskarnaochinternet.se/rapporter/svenskarna-och-internet-2019/. Accessed 18 May 2022.**

**SVT. “Swedbank drabbat av problem – konton står på minus.” SVT Nyheter, 29 April 2022, https://www.svt.se/nyheter/inrikes/swedbank-drabbat-av-tekniska-problem-konton-star-pa-minus. Accessed 18 May 2022.**

**Comment by cesarsotovalero** [comment]
Hi @Gabriel-Acar, 
Thanks for submitting your feedback.
Please add your feedback directly in the PR of the essay.
This facilitates the grading.

**Review by cesarsotovalero — DISMISSED** [review]
Please remove the essay's PDF file.

**Comment by Gabriel-Acar** [comment]
Hey @cesarsotovalero,
This is the PR for our essay though.

**Comment by khesoem** [comment]
Hi @Gabriel-Acar 

Your PR is also changing `contributions/feedback/gacar-leren/README.md` (see https://github.com/KTH/devops-course/pull/1996/files). Please remove that change and I'll merge your PR.

**Comment by Gabriel-Acar** [comment]
@khaes-kth Hey! Sorry for that, tried to hand in feedback before this was merged and then had my group member send a PR for that instead. Solved any clashed, should be good now 💯

**Pull request merged**
