### PR TITLE
Added presentation suggestion for Week 6

### PR DESCRIPTION
**Pull request by DokID**

### CODE REVIEW

**Comment by gluckzhang** [comment]
Since fuzzing competition does not require a presentation, extending what students have learned into a presentation needs more effort.

So I would like to approve this proposal. @monperrus @bbaudry What do you think?

**Comment by DokID** [comment]
Note that I have also added a topic suggestion for an essay in a subsequent commit that seems to have been automatically merged into this pull-request.

**Comment by gluckzhang** [comment]
> Note that I have also added a topic suggestion for an essay in a subsequent commit that seems to have been automatically merged into this pull-request.

Yep, after creating the PR, all your commits in this branch will be added into the PR. You could create another branch & PR to register your essay task. You could also wait for this one to be merged. I have checked the essay topic which is a good one :)

**Comment by monperrus** [comment]
OK for me. A short presentation by the leaders of the competition would be fine though, to explain their strategy. We'll tell you in advance over email.

**Comment by gluckzhang** [comment]
@monperrus , great, got that.
@DokID This PR has been merged, you have registed both essay and presentation tasks :)

**Pull request merged**
