### PR TITLE
Course automation grading clarification

### PR DESCRIPTION
**Pull request by khesoem**
This updates it grading description per our discussion.

### CODE REVIEW

**Comment by khesoem** [comment]
@cesarsotovalero, @Deee92, @henry-lp, @bbaudry 
Have a look at this please.

**Comment by Deee92** [comment]
Hi @khaes-kth, these updates are clear. Should we also explicitly mention that the submission should include a link to the fork and the standalone repo?

**Comment by khesoem** [comment]
> Hi @khaes-kth, these updates are clear. Should we also explicitly mention that the submission should include a link to the fork and the standalone repo?

I added this info. Please merge the PR if you feel it is OK.

**Comment by khesoem** [comment]
I just noticed I had mentioned @henry-lp instead of @SophieHYe :D

**Pull request merged**
