### PR TITLE
Demo: Setting up cypress e2e tests in parallel

### PR DESCRIPTION
**Pull request by arxra**

### CODE REVIEW

**Comment by arxra** [comment]
Original PR can be found at #1029

**Comment by arxra** [comment]
Wanted to say so much more but did not have time to talk about the interesting bits without making it into a presentation/essay/tutorial and wanted to stay to the format.
@cesarsotovalero ping

**Comment by Deee92** [comment]
Hi @arxra, the video is unavailable for me (says it's private). Please fix that and let me know.

**Comment by arxra** [comment]
@Deee92 The video is no longer private but unlisted, tried to reach it through incognito and that now works :)

**Comment by sestys** [comment]
Nice video! I like the concept and visuals of the video, but would prefer some more technical/interesting topic, as most of the demo seems like setting few config variables. Few things I think you could improve:
* Introduce what cypress is and what is used for, you jump straight into the project without much introduction.
* Go more in-depth about the topic, show some interesting bits, that you talk about in the PR. The stuff you showed could have be speed up.

What I really liked:
* Showing the different improvements based on the number of machines used.
* The take-home message, that just speeding up testing by 10x does not mean the same speed up for the pipeline.

**Comment by Adamih** [comment]
Things that are good really good: 
* Very brief and concise intro.
* Detailed walkthrough of steps, with a short motivation of why every step is designed this way and important. 
* Detailed and clear commentary that is always appropriate for what is shown on the screen. 
* Really nice sound quality and concise commentary. 

Things that can be improved:
* Intro can have some "here are the video steps intro". 
* Not sure what the minimum required setup is if I already have an app in Gitlab. If the only thing you need is Cypress installed and some tests, that can be mentioned.  
* Should specify in title and intro that this is a GitLab implementation. 
* Some spelling errors in captions.

I really like the voice-over, the pacing, and the clear commentary. Those were definitely the strongest parts. It might be hard to include some of the feedback given the time constraints. Overall, very nice job!

**Comment by IfyUrama** [comment]
**Overall:** Nice video with clear sound!

**Strength:** The takeaway message is clear and the video shows how setting up parallel machines can improve the test time.

**Weakness/Tmprovement:** Would like to see more information in the introduction about the topic and the steps to be presented.

**Pull request merged**
