### PR TITLE
Final submission: Executable tutorial. Automated email notification for IP change in SSH server.

### PR DESCRIPTION
**Pull request by enniorampello**
# Assignment Proposal

## Title

Automated email notification for IP change in SSH server

## Names and KTH ID

- Ennio Rampello (ennio@kth.se)

## Deadline

Deadline for task 4

## Category

Executable tutorial

## Description

It is definitely a struggle when you go live far away from your much loved SSH machine. Especially when your ISP decides to change your public IP address once every two weeks. After the IP address changes, normally you would have no way to know the new one if you don't have a registration to a DNS service. But what if you don't want to use a DNS service? Here I'll show you how to solve the problem in a completely autonomous way.

**Final Submission**: [Tutorial repo](https://github.com/enniorampello/ip-address-email)

### CODE REVIEW

**Comment by enniorampello** [comment]
updated tutorial after feedback @khaes-kth

**Comment by khesoem** [comment]
@enniorampello 
Thanks for the update. You also have to create a revision pull request and add the changes you have made in the readme file.

**Comment by enniorampello** [comment]
@khaes-kth 
I have already tried to create the revision pull request but it stated that I already have a registered task of type "Executable tutorial". Should I do it anyways?

**Comment by enniorampello** [comment]
furthermore, I haven't changed the original readme file but only the content of the linked repo

**Comment by khesoem** [comment]
If you create a pull request that updates the readme file and adds a changelog, it should pass the checks. Please make the PR and mention me to solve possible issues with the PR.

**Pull request merged**
