### PR TITLE
Video demo

### PR DESCRIPTION
**Pull request by bubriks**
Updated the previous video to be exactly 3 minutes long

### CODE REVIEW

**Comment by Deee92** [comment]
Thanks, merging.

**Comment by glidfeldt** [comment]
# Feedback
Good job! My feedback is divided into strengths, weaknesses, and actionable feedback.

## Strengths
* Great audio quality and pace when spoke.
* Good introduction where you explain everything you set out to do. The introduction is complemented with relevant illustrations.
* You're the only one I've seen so far who used timestamps when giving credit. Makes it much easier to follow along and go back if the viewer might have missed something!.
* You demonstrate clearly what you do and the README.md helps if you want to do it yourself.

## Weaknesses
* Poor audio quality in the beginning (I especially had a hard time hearing your opening line). The audio quality improved after your introduction.
* No easter-egg what I could see.
* I thought the video ended rather abruptly.

## Actionable feedback
* Consider adding a take-home message or a proper ending.
* You should add a description to your GitHub repo if someone would like to try to do what you're doing on their own.

**Comment by m4reko** [comment]
Thank you for an interesting demo! Here are my feedback for you:

## Good points
- Nice pace of the voice over and the tutorial as a whole
- Good and clear introduction
- Perfect use of youtube chapters which lets you navigate the sections of the video

## Points of improvement
- The timing of the screen recording and the voice over is not always perfect. Consider rerecording the screen or make a few cuts so that you are always talking about whats happening on the screen.
- I am missing a good summary or wrap up which possibly could include a good take home message.

**Comment by damnePers** [comment]
# Feedback

Nice demo. It seems like a great software that is really useful and would help developers a lot. 

The beginning and background is really good! It gives a good amount of information. You present it in a clear way and even without any previous knowledge the viewer gets a complete understanding of the issue and what is to come. 

It is a really nice feature that you have added time stamps in the video so that the user can easily navigate through it. I would suggest adding one time stamp for when the actual demo starts, ish 0:50s. 

At the start of the demo it would be nice if you mentioned where to turn or add a link to Microsoft Azure in the descriptions. 

It is good that you first go over the set up and then show how to use the software by making an error and how to fix it. One improvement is to fill the silences with explaining your actions, where to click? why? Etc.  

Add an ending. I understand that the time is limited but it would be great if there were some sort of round up at the end or at least a “and now we are done”.

You have a good, slow tempo for the voice over. It is easy to follow and as a viewer you never lose track of what you are doing. To make the captions as clear and easy to follow I suggest adding punctuation and formatting.

**Comment by arxra** [comment]
# Feedback
Very nice demo, if I were looking for the information displayed in the demo I would have been satisfied.

I really liked the showcase of automatic database population for this demo, clearly showing how and why to use it. 
The video was also clearly layed out both in the description of the video and the start.
Also very nice to see the 3-2-1 backup strategy make its first clear appearance!

The audio was okay, but very well synced to what was happening on the screen without stutter or "uhm".
The text size was good, but its resolution was quite poor, making it hard to focus at times in the video. The cluttered interface that is azure pipelines didn't help here either.

Besides that, I have no gripes with the demo. Impressive work! Good background, good content, nice showcase of relevant features, clear audio overlay and great slides!

**Comment by Spycsh** [comment]
# Feedback

Good job! This video clearly show the whole flow of backup SQL databases on Azure platform. I think with this video, I am also able to set up my database backup on Azure. The voice is clear and the speaker makes every sentence to be clear understandable. Good to know 3-2-1 strategy. An improvement maybe a further discussion of where and how 3-2-1 strategy is used in real Azure platform.

**Comment by dmariel** [comment]
This is a very well made demo, I especially liked the extensive background provided (i.e. the 3,2,1 strategy) as well as the overall structure, including the narrative and overview of contents in the beginning of the video and the nice and informative illustrations that goes with it. Moreover, I really liked the fact that the video is divided into clickable sections in the YouTube timeline. However, it seems like the "3-2-1 backup strategy" clickable section should be prolonged (so that "Creating the database" starts when you go to Microsoft Azure). Furthermore, I believe that the voice over was clear and at a suitable pace. However, maybe it would be good to, if possible, edit the video so that your actions matches the voice over [in this part](https://youtu.be/GQ9qroAbqr4?t=99). Another suggestion for improvement would be to display a slide with the some key takeaway notes in the end of the video (i.e. I tried to do this in [my demo](https://youtu.be/mGFS2zUL8mo?t=179)) since this would give the user the impression that the video will end soon.

**Comment by jhammarstedt** [comment]
# Feedback for demo #1246 

## Positive

* Great motivation why this demo is relevant
* Excellent illustrations, visually appealing
* Good pacing and tempo, subtitles also made it easy to follow along

## Suggested improvements

* Just a visual fix would maybe be to set the theme to white as some of the text became harder to read in this dark setting.
* A finishing summary/ conclussion with a takehome would have been nice, the video ended a bit suddenly 


Overall a cool demo of an interesting topic. You had a great intro and it is clear why your demo is relevant.
Just some minor details and maybe summing up the video in the end would be great, but since you only had 3 minutes it's understandable that it didn't fit. But the audio was clear and you did a good job of fitting everything in the short time!
Great job! 😊

**Pull request merged**
