### PR TITLE
Course Automation: Implementation of MPR shell script

### PR DESCRIPTION
**Pull request by luuuk**
# Assignment Submission

## Title

Add a shell script (`mpr`, for "make pull request") which when invoked from CLI creates a new PR for students to the
devops course repository. This script will live in a new directory (`/scripts`) in the root of the devops repo.

## Names and KTH ID
  - Luke LeVasseur (lukel@kth.se)

## Deadline

Task 2

## Category

Course Automation

## Description

mpr simplifies the PR creation flow for students. This shell script incorporates pushing the most recent commit
to its remote branch in the forked repo copy, opens a new PR in the devops repo, and applies the template PR
Description.

Students will be able to run mpr from their command line, which will prompt them for a PR title. After they write the
title and hit enter, the script will run some git commands and open up the "create pull request" web UI with the
template for the title auto-filled based on the CLI input. Students will still need to update the description of the PR
with details from their readme, but this will simplify the PR creation process for students (
currently local commit, remote push, edit PR through git web UI, input title and desc, create pr, will
be local commit, mpr, input desc, create pr)

Demo video below (Sorry about the quality, Github has a 10mb size limit)!

https://user-images.githubusercontent.com/24230237/161754443-accdea42-9710-4d22-8db9-c17dcfb1f9db.mov

Submission:
Shell Script URL in Standalone Repository: https://github.com/luuuk/devops-course/blob/2022/scripts/mpr.sh

### CODE REVIEW

**Comment by luuuk** [comment]
@khaes-kth tagging you here since you reviewed my proposal for this task and have the contextual understanding. A number of the elements in the PR description don't match up well with this deliverable (since it is a submission to the devops repo). Let me know if there's anything else you want to see here, either in terms of documentation of the script functionality or additional implemented functionality!

**Comment by khesoem** [comment]
This is very cool!

You can even improve it further by asking for more info from the user, and put it in the PR format properly. Also, if you can help the user (student) create the README file in the right place, that would be good. For example, you get the team members KTH ID and names as well as the path to the readme file and then put the readme file into the right directory (with the name of team members).

Also, please do not include the script in this PR. Your submission PR can update the README and add a link to your script, which should be saved in a separate repo. In future, if teachers decide we will ask you to create a PR to add the script to KTH/devops-course repo.

**Comment by luuuk** [comment]
Hey Khashayar - I agree that there is potential for a bit more utility with this script, but want to clarify a couple of points before I try to implement your suggestions.

1. I totally agree that your suggestion about collecting info in the script and auto-filling the PR body would be a massive value add. However, one thing to consider is that the way the script currently is implemented (using `open` to load the compare screen) means that all this collected info would have to be formatted locally and appended to the URL's body parameter a _very long_ string. This wouldn't necessarily be hard to implement but would make the URL pretty clunky for students.

2. I envision`mpr` as the second-to-last step in the student workflow for submissions. Thus, I'm not so sure that your suggestion about creating the README in the right location makes sense as a part of this script, since that is work that should have been done well before a student tries to open their PR. However, I think adding this as a local linting step before opening the PR might be a compromise that makes more sense (essentially checking that the README is correctly formatted)?

3. Happy to put the script in my own repo for now, but do want to call out that pretty much all the utility in this script comes from it being included in forked copies of the main DevOps repo. It's not my call to make, but I would strongly suggest that the script is merged to the main repo in the near future so that other students can start using it for their WIP!

**Comment by khesoem** [comment]
Hi @luuuk 

Good points. Regarding 1 and 2: that's your choice. I thought adding some functionalities to this script can make it more helpful for students and also make it more likely that Martin and Benoit will accept this contribution without requiring more changes.

Regarding point 3, I should say that we usually merge the scripts for next year version of the course. So, it is better if you put it in your own repo for now.

**Comment by luuuk** [comment]
Sounds good @khaes-kth - I've implemented the auto-population of the PR body based on README content, but decided against the formatting checks. I'll put it in my own repo and update this PR to reflect the desired submission flow!

**Comment by khesoem** [comment]
Great, this seems good to me.

Is it ready to be merged?

**Comment by luuuk** [comment]
Yep - ready to merge as long as the way I did the submission looks good to you (With the link added to the repo)!

**Comment by khesoem** [comment]
Do you have a readme for your script? If not, can you please add it somewhere in your repo? (ex., it can be here: https://github.com/luuuk/devops-course/tree/2022/scripts)

The readme can tell us how to run it, at least with the most simple config.

**Comment by luuuk** [comment]
The script itself has an optional -h flag, which prints a message for the user with information, but will add a readme as well!

**Comment by luuuk** [comment]
Supporting readme documentation is pushed to standalone repo @khaes-kth

**Review by khesoem — APPROVED** [review]
LGTM!

**Pull request merged**
