### PR TITLE
Week 4: Scientific paper proposal

### PR DESCRIPTION
**Pull request by jackma-00**
# Assignment Proposal

## Title

_CRISP-ML(Q). The End-to-End Machine Learning Workflow_

## Names and KTH ID

  - Jacopo Maragna (jmaragna@kth.se)
  - Siham Shahoud (shahoud@kth.se)

## Deadline

- Week 4

## Category

- Scientific paper

## Description

The purpose of this scientific paper presentation is to guide the audience through the various phases of the machine learning workflow, as outlined in the paper ["Towards CRISP-ML(Q): A Machine Learning Process Model with Quality Assurance Methodology"](https://www.mdpi.com/2504-4990/3/2/20)

**Relevance**

The topics covered are particularly relevant to DevOps, especially MLOps, as they address the state-of-the-art in fully automated pipelines that handle model training, deployment to production, and performance monitoring.

### CODE REVIEW

**Comment by algomaster99** [comment]
Hi! I like the proposal and I approve, but since I am new TA, I would also like @javierron or @Deee92's feedback. :)

**Comment by algomaster99** [comment]
@jackma-00 could you also look for another partner to do this task? Accepting tasks by single students would require much more presentation slots than we already have.

**Comment by jackma-00** [comment]
Hello @algomaster99, thanks for reaching out. Yes, I'll look for a partner.

**Comment by jackma-00** [comment]
Closed due to unsuccessful checks. Reopening as a new PR.

**Pull request closed without merging**
