### PR TITLE
[Submission] Demo: Docker implementation to React native project

### PR DESCRIPTION
**Pull request by George-Bassilious**
This is based on the proposal (#992 )

### CODE REVIEW

**Comment by Ackuq** [comment]
Very well done demo! Calm narrative and easy to follow along. The video editing is very good. I think you you did a great job in explaining the process.

However, I am a little confused, React Native is primarily used for developing native mobile applications, however, here you are building a web application. I see that this is reflected in the description, but maybe good to emphasize this in the video as well.

**Comment by Internet-Person-IP** [comment]
Really Nice Tutorial with some minor things that need to be explained.

Nice:

1. Editing: I really enjoyed the editing and how you highlight certain things that you want to focus on.
2. Informational: Explains the topic discussed really well. I have some familiarity with docker and this made it 100% more clear.
3. Simple to follow along: This video is pretty simple to follow along which makes it easy to grasp and utilize the code.

Work on:
1. I think the fact that it uses React Native makes it a bit confusing. Since I got the impression that React Native is mainly used for Mobile Development. However, I know that React Native also builds a version of the app for the Web as well it just confusing using React Native in this case compared to React. Maybe the purpose is to enable easier testing of mobile apps? in which case I think this should be mentioned in the video


Otherwise, I feel as if this video was great.

**Comment by andnil5** [comment]
**Outstanding job with the demo! I've added some comments and suggestions below.**
 
**Positive points**

* Excellent graphics and slides. It looks professional!
* It is great that you didn't focus on the installation but instead referred to the installation instructions in your repository.
* Good job with the voice-over and the matching subtitles. It makes it easier to follow the video.
* The demo has a nice flow!
* I liked that you have added all the necessary links in the video description.

**Possible improvements**

* It's sweet with background music, but it's a bit loud. Consider lowering it slightly to make it easier to hear the voice-over.
* Consider cutting of a second or so at 2.23 to get rid of "out".
* Consider describing more docker specific things that you have used in the code. Ex" volumes" is mentioned very quickly at 1:45. I know that the timeframe is short, and it could be tough to fit everything in 3 minutes, and if you choose not to do this, it would be helpful if you point to a link from where one could read more.

**Comment by LaraRos** [comment]
# Feedback demo
* Very good speaking speed, you really nailed the 3 min thing
* Great introduction! :)
## Things to work on
* The video quality is very low, I would like you to zoom in on the frames with visual studio because it’s hard to read
* The microphone sound is quite low, so I don’t think it’s good to have music over the demo since it makes it hard to hear.
* As others have said before me, the React Native thing is confusing.

**Comment by Atema** [comment]
Nice job on the demo, it gives a nice overview of the steps that one needs to take to dockerise front- and back-end, and was easy to follow.

You spend quite a lot of time on explaining the basics of Docker, which is nice for beginners, but perhaps a bit unneccessary for the audience of the video (people taking a DevOps course). I'd rather see some more time spent on explaining parts of the configuration you're using (for example, a bit more about the volumes). 

I'm also a bit confused by React Native, especially since there's `android` and `ios` directories in the repository (perhaps these could just be removed to make things clearer).

**Comment by fwallb** [comment]
### Great and proffessional demo, I would definitely continue watching if I clicked on it on YouTube! 

**Strengths**
- Great introduction to the demo and Docker as a tool.
- Good that you have thought about position of the subtitles.
- Nice that you have put some music in the background, the transition between parts using the music is great!

**Potential improvements**
- The music sometimes takes over and it becomes harder to hear the voiceover, this is mainly when the singer sings.
- When you say "pause the video or find the link in the description", you could maybe zoom in quickly on the code to make it easier to read. Or maybe zoom in in the editor throughout the video.

**Pull request merged**
