### PR TITLE
adammel - Essay proposal

### PR DESCRIPTION
**Pull request by Adrelix**
# Assignment Proposal
## Title
Agent testing in video games 

## Names and KTH ID
Adam Melander (adammel@kth.se)

## Deadline
Task 3

## Category
Essay

## Description
As video games become larger and more complex, ensuring thorough testing can be challenging. Relying solely on human testers can slow down development. To speed up the process, autonomous agents using reinforcement learning have shown promise in exploring and testing game scenarios. This goes for both single player environments and multiplayer environments, although the latter would require multiple agents as well. For my essay I want to explore the current techniques being used and discuss how effective they seem to be. So far I have two research papers that I would base this essay upon, one from OpenAI (https://arxiv.org/pdf/1909.07528.pdf) and one from EA (https://arxiv.org/pdf/2103.13798.pdf).

Relevance

As testing is a core component in devops, automated testing could be a massive improvement in terms of thoroughness and efficiency. Tools like Agent testing could potentially save a lot of time in game development pipelines and decrease the risk of letting bugs out in the production environment.

### CODE REVIEW

**Comment by SandZn** [comment]
Hi, thanks for the proposal. Can you add relevance to DevOps in your proposal?

**Comment by Adrelix** [comment]
@SandZn Hi, added relevance now.

**Comment by Deee92** [comment]
Hi @Adrelix, it appears that you've missed the submission deadline (May 8) for this essay.
Note that this means you now submit your essay by the repeat deadline (May 22), and that you do not get the opportunity of revising the essay.
Also, failure to submit by the repeat deadline means that you fail this task.

**Comment by Adrelix** [comment]
Hello @Deee92 , 

I did indeed miss that deadline, many deadlines to keep track of atm, but i submitted my essay now. I hope you guys have some mercy on my submission or have some time to read it relatively soon so i can fix any problems before final submission date. Would be very much appreciated as I have put a lot of effort into this essay.

BR,
Adam

**Pull request merged**
