### PR TITLE
Essay Submission: Cloud & Serverless: Game Changer?

### PR DESCRIPTION
**Pull request by Internet-Person-IP**
# Essay Submission: Cloud & Serverless: Game Changer?
## Members
Taqui - taqui@kth.se
GitHub: [Internet-Person-IP](https://github.com/Internet-Person-IP)

## Initial Proposal: 
#952 

## Feedback
I will receive feedback from @Wkkkkk and @isacarvid

# Submission

Can be found in "essay/taqui/"

## Grading Criteria I am aiming for:

|                                             | Yes | No | Remarkable |
|-------------------------------------------- | ----|----|-------------|
| format: The essay is in PDF | ✅ |  - | - |
| title: The essay has a good title | Yes  | No | Remarkable ✅|
| well-structured: The essay is well structured, the ideas are well presented | Yes ✅| No | Remarkable |
| introduction: The essay contains a good introduction | Yes ✅ | No | Remarkable |
| conclusion: The essay contains a good conclusion | Yes ✅| No | Remarkable |
| self-contained: The essay is self-contained, one can understand it without reading something else (expected knowledge of the reader: a master student in computer science) | Yes | No | Remarkable ✅|
| innovative: The essay contains innovative ideas or material | Yes | No | Remarkable ✅|
| figures: The essay contains good figures or listings | Yes | No ✅| Remarkable |
| sound: The essay is sound, factual, and accurate | Yes ✅| No | Remarkable |
| references: The essay contains references, appropriate in number and quality (10 good refs is a minimum) | Yes ✅| No | Remarkable |
| elegant: The essay presentation is elegant / visually appealing (eg LaTeX, InDesign) | Yes ✅ | No | Remarkable |
| relevant: The essay addresses a topic that is relevant for DevOps | Yes | No | Remarkable ✅|

### CODE REVIEW

**Comment by isacarvid** [comment]
Hi @Internet-Person-IP!  I and @ayubatif will give feedback as soon as possible this week!

**Comment by isacarvid** [comment]
Hi @Internet-Person-IP I believe something went wrong here. I and @ayubatif is actually giving feedback to another essay. As this essay already got feedback we wont be giving feedback here. Hope all goes well, Sorry for the confusion 😁

**Comment by Internet-Person-IP** [comment]
@isacarvid No worries. I just remember you commented on my proposal and therefore I decided to add you. 

Thank you for your time and good luck giving feedback.

**Comment by Wkkkkk** [comment]
Hi, I’m very glad to read this essay. Here are some feedbacks.

Serverless has been a hot topic in recent years, therefore it’s great to read such an essay for those unfamiliar with it. When I see this proposal, I found its title very intriguing and could not wait to read it. The concept of Cloud and Serverless is well introduced in the beginning, so readers could have a glimpse of the essay at once. Later, as different topics are covered, the writer chained these concepts together and explained their utilization to each other. In this way, readers can not only understand each of them but also see the relationships between these concepts clearly. In the next chapters, Serverless computing and storage are introduced in a detailed way, which gives the reader a deeper understanding of Serverless and its possible application scenarios. Some examples are listed in the essay, such as AWS, a Serverless computing vendor and its attached relational database Amazon RDS. The conclusion wraps the content of the essay succinctly and points out the benefits of Serverless as to traditional architecture. Dozens of references are attached in the end.

This essay helps me to figure out several benefits of Serverless and motives me to try it myself if possible. As mentioned, lots of newfangled Serverless applications spring up recently. They tend to show greater availability and elasticity at a lower cost and fit the DevOps perfectly as most operations are automated within the cloud. The provided infrastructure frees developers from tedious management of their application. Examples are some Serverless database services like Auroma and DynamoDB. These services are often leveraged to different Availability Zones and therefore developers don’t need to deal with backups, scaling or possible failures anymore. This helps us to design large-scale applications at ease.

However, it’s worth pointing out that some drawbacks of Serverless architecture are not covered in this essay due to the word limit. One example is the so-called “cold start” issue. As the cost of greater elasticity, it may require a significant amount of time to start up a suspended application, which brings additional latency. Also, diagnosing performance or excessive resource usage problems with serverless code may be more difficult than with traditional server code, because although entire functions can be timed, there is typically no ability to dig into more detail by attaching profilers, debuggers or APM tools. Furthermore, the environment in which the code runs is typically not open source, so its performance characteristics cannot be precisely replicated in a local environment.

In addition, it might be better if some unsuitable computing workloads for Serverless, such as high-performance computing, are mentioned in the essay. Because of the resource limits imposed by cloud providers, and also because it would likely be cheaper to bulk-provision the number of servers believed to be required at any given point in time. When introducing all these concepts, the writer listed lots of facts to illustrate his thoughts but it should be better if some figures are added.

Nevertheless, it’s a great essay to read and I’m really inspired by the introduced benefits of Serverless. Let’s see if Serverless is the real game-changer?

PS: One great essay I'd like to share with Taqui is 《Cloud Programming Simplified: A Berkeley View on Serverless Computing》. It covers lots of interesting perspectives about Serverless Computing.

**Comment by Wkkkkk** [comment]
Hi @cesarsotovalero,
I copied this feedback from the initial essay [pr](https://github.com/KTH/devops-course/pull/952#issuecomment-824708343) and parsed it here. It was within 24 hours after the task submission.

Kun

**Comment by Internet-Person-IP** [comment]
@cesarsotovalero or @khaes-kth (not sure who I should ping) I have added some feedback.

Here is what I added:

- I added a short description of the problems with Serverless
- I mentioned the issue of HPC in a Serverless Context

The word count is 2089 when I ran  `pdftotext Cloud___Serverless__Game_Changer_.pdf - | tr -d '.' | wc -w`

Hopefully, this is sufficient as a final submission.

**Pull request merged**
