### PR TITLE
Essay submission: Types of deployments

### PR DESCRIPTION
**Pull request by bubriks**
# Essay proposal: Types of deployments

## Members

Ralfs Zangis (zangis@kth.se)
GitHub: [Ralfs](https://github.com/bubriks)

## Proposal

Document the reasons for using different forms of deployments (Rolling, blue/green and canary).

- Explain each form of deployment
- Give reasons for their usage
- Explain their drawbacks
- Examples from industry
- Final thoughts on the subject

### CODE REVIEW

**Comment by vladomit** [comment]
# Feedback:  Types of deployments #1239

Feedback on [#1239](https://github.com/KTH/devops-course/pull/1239) essay submission.

## Member
 Vlado Mitrovic (vladom@kth.se)
 Github username: [vladomitrovic](https://github.com/vladomitrovic)
 

## Overall
In general, the essay is interesting and the structure is easy to follow. The topic is self-contained and clearly understandable by someone having minimum knowledge in computer science. You included enough reference from trustworthy sources. Overall you wrote a nice essay and I enjoyed reading it.

However, some points could be improved in order to have a better quality and make it more appealing.

## Strengths

Your **introduction** is very good, you are clearly explaining the problematic and how to solve it. In the same way for the **conclusion**, you summarize what you wrote before and also include the most important goals for the deployment.

The **structure** is good, we can easily understand and follow your explanation. I am just a bit confused by the title of the section 2 (see improvements). You are illustrating the different type of deployments with **figures**.

The topic chosen is really **relevant** for this course as the deployment is clearly a part of the DevOps life-cycle and your explanations are clear.

The essay is clearly **self-contained** and understandable by the target audience defined in the requirements.

You are using a LaTeX template, which makes you essay **elegant** and professional.


## Improvements

From my point of view, I think you could have a better **title**. You should use something catchy to get the attention of the potentials readers.

As said before, the **structure** is good but the title is a bit confusing in the section 2 (Types of deployment) because you have the subsections 2.1 (Deployment strategies) and 2.2 (Testing strategies). Is it normal that the testing is included in the types of deployment ? And what is the difference between 2 and 2.1 ? Not sure if I understood correctly, but I would change the name of the section 2.

Some of your sentences are very long like in the section 2.1.3 (Blue-Green). Half of your paragraph is in one sentence, I would try to simplify it and write shorter sentences to make it easier to follow.

After explaining the different types of deployment, I would summarize what you said. Just highlight the main points so the reader has a clear idea of the different types. Maybe you could add a comparison similar to [this picture](https://storage.googleapis.com/cdn.thenewstack.io/media/2017/11/9e09392d-k8s_deployment_strategies.png).

When you are explaining the examples from the industry and the cost of outage, I would cite the source. You can add something like : According to *XXXX*, the blackout had a cost of ...

I noticed that you only wrote April 2021 for the date, I would add the **full date**.

**Comment by bubriks** [comment]
Hi, thanks for the detailed feedback! I have improved the solution according to it.

**Comment by bubriks** [comment]
# List of changes done based on the feedback
- Improved title to: Software deployment: the art of trade-offs
- Changed section names (hopefully to make it less confusing)
- Reduced the size of sentences across the document
- Summary for the different types of deployments created at the end of the respective sections
- Citing the source for the cost of outage
- Changed date to provide more information
- Using latex format

**Comment by khesoem** [comment]
I'm closing and reopening this PR to test our new GHA for checking essays word count.

**Comment by khesoem** [comment]
> # Feedback: Types of deployments #1239
> Feedback on [#1239](https://github.com/KTH/devops-course/pull/1239) essay submission.
> 
> ## Member
> Vlado Mitrovic ([vladom@kth.se](mailto:vladom@kth.se))
> Github username: [vladomitrovic](https://github.com/vladomitrovic)
> 
> ## Overall
> In general, the essay is interesting and the structure is easy to follow. The topic is self-contained and clearly understandable by someone having minimum knowledge in computer science. You included enough reference from trustworthy sources. Overall you wrote a nice essay and I enjoyed reading it.
> 
> However, some points could be improved in order to have a better quality and make it more appealing.
> 
> ## Strengths
> Your **introduction** is very good, you are clearly explaining the problematic and how to solve it. In the same way for the **conclusion**, you summarize what you wrote before and also include the most important goals for the deployment.
> 
> The **structure** is good, we can easily understand and follow your explanation. I am just a bit confused by the title of the section 2 (see improvements). You are illustrating the different type of deployments with **figures**.
> 
> The topic chosen is really **relevant** for this course as the deployment is clearly a part of the DevOps life-cycle and your explanations are clear.
> 
> The essay is clearly **self-contained** and understandable by the target audience defined in the requirements.
> 
> You are using a LaTeX template, which makes you essay **elegant** and professional.
> 
> ## Improvements
> From my point of view, I think you could have a better **title**. You should use something catchy to get the attention of the potentials readers.
> 
> As said before, the **structure** is good but the title is a bit confusing in the section 2 (Types of deployment) because you have the subsections 2.1 (Deployment strategies) and 2.2 (Testing strategies). Is it normal that the testing is included in the types of deployment ? And what is the difference between 2 and 2.1 ? Not sure if I understood correctly, but I would change the name of the section 2.
> 
> Some of your sentences are very long like in the section 2.1.3 (Blue-Green). Half of your paragraph is in one sentence, I would try to simplify it and write shorter sentences to make it easier to follow.
> 
> After explaining the different types of deployment, I would summarize what you said. Just highlight the main points so the reader has a clear idea of the different types. Maybe you could add a comparison similar to [this picture](https://storage.googleapis.com/cdn.thenewstack.io/media/2017/11/9e09392d-k8s_deployment_strategies.png).
> 
> When you are explaining the examples from the industry and the cost of outage, I would cite the source. You can add something like : According to _XXXX_, the blackout had a cost of ...
> 
> I noticed that you only wrote April 2021 for the date, I would add the **full date**.

Hi @vladomitrovic 

Can you please create a PR and add this feedback text to your [readme ](https://github.com/KTH/devops-course/blob/2021/contributions/feedback/vladom/README.md) as well? Do this ASAP please.

**Pull request merged**
