### PR TITLE
presentation: add presentation link for Week 3

### PR DESCRIPTION
**Pull request by Internet-Person-IP**
This one is related to #954.

I had some merge conflicts I had to deal with. I hope I dealt with them appropriately. 

The main purpose of this is to submit Week 3 presentation and to add the team members that worked with me for making this presentation work.

@cesarsotovalero I think you were the one evaluating my previous pull request which is why I am adding you here.

### CODE REVIEW

**Comment by monperrus** [comment]
@Internet-Person-IP rebase needed, there should not be any essay change in the diff.

**Comment by Internet-Person-IP** [comment]
@monperrus I hope I made the changes correctly.

Best Regards,

Taqui

**Comment by monperrus** [comment]
@Internet-Person-IP  Does not seem so, there is still a change in contributions/essay/taqui/README.md :)

**Comment by Internet-Person-IP** [comment]
@monperrus Hi, I changed the Files Changed Tab in Github and only see the presentation readme being changed. I hope this is correct now.

Best Regards,


Taqui

**Comment by monperrus** [comment]
Thanks.

**Pull request merged**
