### PR TITLE
Presentation: Nix

### PR DESCRIPTION
**Pull request by ysndr**
# Presentation: Nix

## Group

1. yannik: yannik@kth.se
2. none (yet)

## Content

- Nix (the language)
- Nix Derivations (Description of an Artifact)
- Nixpkgs (Central Package Repository)
- Example Applications of Nix 
  - Integrations 
  - NixOS (define a local system)
  - NixOps (deploy remote machines)

Due to timing constraints a subset of these will be presented or some points will mostly be mentioned with pointers to external resources.

### CODE REVIEW

**Comment by cesarsotovalero** [comment]
The topic of your presentation is very suitable for DevOps course.

Can you add more details (bullet points) of what your presentation will cover?

**Comment by ysndr** [comment]
I added some pointers on the content, 7-8 minutes is very short and Nix is a huge topic so I will probably focus mostly on the concepts.

**Comment by cesarsotovalero** [comment]
I'm merging your PR. Good luck @ysndr!

**Comment by monperrus** [comment]
@ysndr Could you add your full name + github id + KTH id to your presentation README? Thanks!

**Pull request merged**
