### PR TITLE
nareaho-hastimz (demo proposal)

### PR DESCRIPTION
**Pull request by Hastimazadeh**
# Assignment Proposal

## Title

A demonstration of GitHub’s new code search engine

## Names and KTH ID

  - Mathias Näreaho (nareaho@kth.se)
  - Hasti Mohebali Zadeh (hastimz@kth.se)

## Deadline

- Week 9

## Category

- Demo

## Description

GitHub have built their own search engine from scratch, specifically for code search, to help traverse over 200 million repositories. 
The new search engine is more advanced and allows for further refinement and exploration of the code. 

This demo aims to showcase some of the features that this new search engine brings, and we will use it to discover and explore some code.

**Relevance**

Code search is an important tool for getting answers about code, through searching, browsing and reading code. The scale of GitHub is very large, so the quality of the search engine is very important.

### CODE REVIEW

**Comment by khesoem** [comment]
It seems Mathias Näreaho is not registered in Canvas.

**Comment by m-nar** [comment]
Student registration is pending, should be done shortly

**Comment by khesoem** [comment]
Good! Please ping me when the registration is done!

**Comment by m-nar** [comment]
Registration is done now on my Ladok :) @khaes-kth

**Comment by khesoem** [comment]
@Hastimazadeh 
Can you try to make it more clear how it is related to Devops? I'm worried that you will present something that the professors will ask about its relevance.

**Comment by Hastimazadeh** [comment]
For the relevance of the topic, we were planning to look at it this way: 

DevOps and code search engines complement each other in the context of software development.

DevOps is a software development approach that focuses on collaboration and communication between development and operations teams in order to improve the efficiency and reliability of software delivery.
Code search engines are tools for helping developers search code among many repositories so that they can reuse code easier. 

This results in saving time and effort in software development, which aligns with the goals of DevOps.

**Comment by khesoem** [comment]
If we consider DevOps as CI/CD, how can we say code search engines contribute to it?

**Comment by Hastimazadeh** [comment]
We suggest that a strong code search software greatly assists in integrating code, as previously written code search can aid in identifying potential conflicts or dependencies with other code repositories. It can also help developers to divide their work into smaller batches that better fit the CI mentality. Code search can also improve collaboration and communication, as developers can easily search and review code repositories, share best practices and coordinate work.
Overall, we deem that a well-implemented code search engine can streamline the CI/CD process, improve code quality and collaboration. 


> If we consider DevOps as CI/CD, how can we say code search engines contribute to it?

**Comment by khesoem** [comment]
Great! Remember to emphasize on the relevance to Devops in your demo

**Pull request merged**
