### PR TITLE
Demo submission for May 5th feedback session

### PR DESCRIPTION
**Pull request by javierron**
Signed-off-by: Javier Ron <javierron90@gmail.com>

### CODE REVIEW

**Comment by s1grun** [comment]
I want to give feedback to this demo.

**Comment by AristotelisKotsias** [comment]
Hi I would like to give feedback to this demo.

**Comment by georgewbar** [comment]
I would like to give feedback

**Comment by rbratfors** [comment]
Hello, I would like to give feedback on this demo.

**Comment by rbratfors** [comment]
It was a good demo with a very interesting and useful topic. The introduction was nice as a quick overview to follow the demo better. The visual representation made it easier to understand what the commands did.

I thought the music was too loud at times, which made it harder to hear the actual narration.

**Comment by AristotelisKotsias** [comment]
Thank you for your demo, it is very interesting, nice edited and explanatory. 

Something that I would like to point out is that you can lower the volume of the music when you talk since it is easier to focus on the actual talking (at least for me). Also, you can keep it under 5mins by maybe not including the "why is autoscaling a convinient feature to have".

**Comment by s1grun** [comment]
Good demo! The screencast is very sublime, the content is interesting and relevant to DevOps. 

Here's my feedback:
- The music is too loud, I ended up muting youtube and only reading the subtitles because I found it hard to focus on the demo.
- Maybe have a prerequisite that you assume that people have set up kubectl 
- Maybe elaborate a bit on the kubectl commands you're running in the terminal 
- When you're explaining the dashboard in Grafana it would be nice if you use the pointer (and make it bigger) to point to the gadgets you're explaining. 
- I felt that the demo was missing a concluded take-home message
- The demo exceeds over the 5 minutes limit which is one of the criteria for the screencast.

**Comment by nagavem** [comment]
Hi,I would like to give feedback to this demo

**Comment by nagavem** [comment]
Really nice and informative demo!! it was well explained and ample reference material was provided to get us started with the topic thereby giving us more context.The voice over is also really good and to the point in terms of explanation.
In terms of possible improvements just to list a few:-
The demo has a few gaps where it could be trimmed as it is exceeding the time limit set forth in the guidelines.
The music for me blended well in the beginning but as @s1grun  pointed out towards the latter half I could not focus on the demo much without muting it so maybe go for a track that has a consistent pitch throughout so as the viewer's attention is unnaffected.
Great demo once again,it taught me something new today :)

**Comment by georgewbar** [comment]
## Feedback overview
* The demo is sublime and has high quality. (with some modifications, see below)
* It is informative and instructive that you clarify the concept at the beginning of the demo. 
* With a quick search on Youtube, I could not find a lot of videos that go through how to combine auto-scaling with visualization using Kube-Prometheus. This is a good point for originality.
* The Katacoda in the description was a very good idea for replication.
* There are good subtitles in general.
* It is also good that you added references at the end.

## Feedback using template
Using the template for `pass` criteria, in my opinion, the following criteria are fulfilled:
* The demonstration screencast is difficult to do. Yes (with some modifications, see below).
* The demonstration screencast is original. Yes.
* The demonstration screencast is sublime (eg visually appealing). Yes (with some modifications, see comments below).

## Some issues that could be fixed
* I know that it maybe obvious, but it is not mentioned at the beginning why auto-scaling and monitoring are relevant to DevOps (this could contribute to the criteria of **The demonstration screencast is clearly motivated (why it matters for Devops?)**).
* Regarding the difficulty of the demo, you only followed what is written in the documentation, even in the demo. This is good, but to achieve the criteria **The demonstration screencast is difficult to do**, this could be made more difficult by creating a new website with an easteregg (for example) that appears if the workload is too high or by e.g. combining more tools into the demo.
* Minikube is used implicitly without mentioning as a prerequisite to install in the demo.
* The time constraint (3-5 minutes) is violated.
* It is a little bit slow in the demo at the beginning. The demo could be made to follow the time-constraint (3-5 minutes) if this bit in the beginning is made a little bit faster.
* At min 1:01, the is an acronym that could be **RC** that I did not understand what is stands for. 
* It could be better to stop the music when the demo starts at minute 2:10.
* There is no good and concise take-home message at the end. **The screencast contains a good and concise take-home message at the end** is a mandatory criterion.
* You could also add the credits for the music.

**Comment by javierron** [comment]
@AristotelisKotsias @rbratfors @s1grun @nagavem @georgewbar

Thank you all! Your feedback is very helpful. We will improve our demo with your suggestions and pointers!

**Pull request merged**
