### PR TITLE
Finished Essay: The Monitoring Process In Video Games

### PR DESCRIPTION
**Pull request by ruwaid4**
# Essay
## Members
Ruwaid Louis (ruwaid@kth.se)
GitHub Username: ruwaid4

Henrik Mellin (hmellin@kth.se)
GitHub Username: hmellin97

## Topic
DevOps monitoring in the video games industry: 
* What tools are used
* What methods are used
* What kind of data is used
* How it is used for: 
  * Anti-Cheat
  * Bug finding
  * Attacks
  * Performance

## Sources
https://medium.com/@helymarleena/devops-vs-gamedev-software-engineering-80b4b73bdc81 </br>
https://dzone.com/articles/monitoring-in-the-gaming-industry </br>
https://dl.acm.org/doi/abs/10.1145/2700529

Co-Author: @hmellin97

### CODE REVIEW

**Comment by gluckzhang** [comment]
Thanks @ruwaid4 , I'll merge the PR first. But the essay will be graded later.

**Comment by ruwaid4** [comment]
Great! Will there be any review process before grading?

**Comment by gluckzhang** [comment]
> Great! Will there be any review process before grading?

Yes, students are given the opportunity to receive specific feedback on their work. You could do a PR according to https://github.com/KTH/devops-course/blob/master/contributions/feedback-planning.md :)

**Comment by monperrus** [comment]
Feedback per #464.

Thanks for the submission, and congrats for finishing the essay so early. Overall, the structure and the writing is good.

Major comments: 

1. one only realizes late in the essay that you're exploring different types of information to be monitored: Solutions: 
    * Announce it in the introduction
    * Add an overview figure with a fat caption
1. We understand well what type of information is being monitored, but not whether there is some common infrastructure or technique across the 4 types. Solution: Add a discussion section
1. The difference between "methods" and "data" is often not clear. In "Data" we would expect things like data formats and data volume. Solutions:
    * Remove confusing subheaders "methods" / "data"
    * Explore whether you can have instead "method" (high level overview) and "example" (a concrete example rooted in reality, from a post/paper, as you have with Super Mario)

See also minor comments in the PDF sent over email.

**Pull request merged**
