### PR TITLE
Updated the readme with the info from the PR

### PR DESCRIPTION
**Pull request by wska**
Hi! Here is the expanded README @khaes-kth

### CODE REVIEW

**Comment by khesoem** [comment]
@wska 

Can you rebase your branch (or follow any other solution) to fix the conflict issues?

**Comment by wska** [comment]
@khaes-kth I will fix it. I could also delete the project files maybe? Since the code is hosted through the other repo?

**Comment by wska** [comment]
@khaes-kth Seems our commit log came in as well. Is this fine or do you want me to try something different?

**Comment by khesoem** [comment]
Your readme has things like `<<<<<<< HEAD` in it. I think the easiest way is just to remove your fork, close this PR, fork again, update the readme, and push it in a new PR.

**Comment by wska** [comment]
Oh you are right. I will make a new fork.

**Pull request closed without merging**
