### PR TITLE
Course automation submission: Hemingway feedback on essays

### PR DESCRIPTION
**Pull request by wska**
# Course automation: Post hemingway editor score, readability and feedback (Proposal #1041)

## Members

William Skagerström (wska@kth.se) (@wska)
Alexander Kruger (alekru@kth.se) (@TheStar19)
## Introduction

This contribution takes the form of a bot that is capable of providing feedback on an essay submission by utilizing the online-hosted hemingway editor (https://hemingwayapp.com/). The hemingway editor will provide some general information about the text that was published, including:
* A approximative grade of the readability of the paper (generated by a heuristic)
* Word count
* Reading time
* Quantity of adverbs utilized
* Uses of a passive voice
* Phrases that could be rewritten in a simpler manner
* Number of difficult to read sentences
* Number of VERY difficult to read sentences

## General functionality
The program performs the following steps when execution initiates:
1. Scans the pull requests available on the designated repo and looks for comments including the "!hemingway" tag.
2. If the pull request contains a pdf file, it will download it and convert it into a raw text file using pdf2txt.py library (https://pypi.org/project/pdf2text/). 
3. The text will then pass into a hemingway function, which utilizes selenium and google chrome to open a web browser and input the raw text (https://selenium-python.readthedocs.io/).
4. It will then fetch the relevant feedback provided by the hemingway editor and create a short summary.
5. This is then returned and posted as a comment to the original pull request using a dedicated bot-account. Git interactions are done using pygithub (https://pygithub.readthedocs.io/en/latest/index.html).

## How to use
The bot will trigger its search upon seeing a pull request conducted to the ./contributions/essay path. In order to obtain hemingway feedback, one needs to either include a comment on the pull request which includes "!hemingway" (with an exclamation mark), or include the phrase in the body of the pull request.

The search can also be manually started by going into Github Actions and scheduling the "hemingway'' job. This might be necessary if one makes a comment after a pull request and wants to obtain feedback.

## Submission details

For this task, we aimed at fulfilling yes for all points except for the point about praise from other students, since this is subjective and unreliable at best. Note that we squashed the commit history into one commit to keeping the history of the main repo clean. The overall work distribution was about equal. 

|                                             | Reasoning | Remarkable |
|-------------------------------------------- |----|-------------|
|The work is done before April 6, 2021 (in order to be useful for the course) | PR done 5th of April | - |
|The automation task produces a PR status or issue / PR comment | Produces a comment on a PR. | - |
|The automation task is reusable | As a github action, it may be applied to any other repository which hemingway feedback may be useful | “In other courses than this one”: If the course is based around github like this one, then yes. |
|The task runs on a standard platform | Yes, runs on Github Actions| - |
|The code for the task is available | Yes, repo: https://github.com/wska/hemingwayAutoFeedback | “Well documented repo”: While subjective, we would say that the repo is well documented |

### CODE REVIEW

**Comment by wska** [comment]
@bbaudry Hi! We have updated the username and all relevant paths as per your request: https://github.com/KTH/devops-course/pull/1041#issuecomment-821214893

**Comment by wska** [comment]
Hi! We added the "current" version of the code for this before the soft deadline of course automation on April 5th, but we were not sure if we were supposed to add the code as part of the pull request or simply point to the repo which hosts it. 

On the dedicated standalone repo (https://github.com/wska/hemingwayAutoFeedback) we have since been doing some minor changes (but nothing that changes the general functionality). 

If you want the submission to be done differently, please let us know.

If you want to merge the code into the devops repo and run it there as a GitHub action, you need to either create an access token with workflow permissions set, or (and I recommend) changing line 52 in the hemingwayfeedback.yml to:
> SUPER_SECRET: ${{ secrets.GITHUB_TOKEN }}

which will then utilize the inherit GitHub token which is created automatically for GitHub actions. 

The code in the pull-request was pre-configured for this particular repo (the KTH/devops-course repo), so the token should be the only thing that needs to be modified.

**Comment by wska** [comment]
@khaes-kth Hi! One question: Should we have included the information in the pull request (such as link to the new repo https://github.com/wska/hemingwayAutoFeedback) in the README on the devops-course repo as well? Or is it fine if it is here on the PR only?

Thanks.

**Comment by khesoem** [comment]
It is much better to add it to the readme as well. Can you do it and create a new PR and mention me?

**Pull request merged**
