### PR TITLE
Presentation Proposal: Continuous testing and its role & application within devops

### PR DESCRIPTION
**Pull request by wska**

### CODE REVIEW

**Comment by wska** [comment]
See latest version of the readme (84159b3)

**Comment by SophieHYe** [comment]
Thanks for your PR, your presentation outline looks good. I am merging it now.

**Comment by monperrus** [comment]
FYI, we have two presentations about continuous testing in week 3, see other one at #984, you may want to contact them to ensure uniqueness.

**Comment by wska** [comment]
@monperrus We have spoken to the other group and have tried to steer our subjects into separate paths. For our PR (#1026) we have decided to focus a bit more on continuous testing versus automated testing, such as key differences, what roles they serve and how they are typically utilized.

**Pull request merged**
