### PR TITLE
move demo to week 7

### PR DESCRIPTION
**Pull request by t-sorger**
# Assignment Proposal

## Title

Infrastructure as Code Using Ansible Playbooks

## Names and KTH ID

- Arber Limani (arberl@kth.se)
- Tom Sorger (sorger@kth.se)

## Deadline

- Week 7

## Category

- Demo

## Description

In this demo, we'll demonstrate how to use `Ansible` to automate the deployment of an application. This approach is useful when setting up multiple instances of the same application for development, testing, and production. The demo will show how `Ansible playbooks` can automatically configure all instances in a consistent manner, ensuring the same setup across every environment.

**Relevance**

This demo is highly relevant to DevOps because it showcases how automation tools like Ansible can streamline the deployment process, ensuring consistency across multiple environments. By automating infrastructure and configuration management, it reduces the risk of human error and allows teams to quickly deploy and scale applications in development, testing, and production environments.

### CODE REVIEW

**Comment by t-sorger** [comment]
As discussed per email @algomaster99

**Comment by algomaster99** [comment]
@Deee92 any idea why the CI is failing?

**Comment by algomaster99** [comment]
@Deee92 @javierron should I disable the essay workflow because we don't have it as a task this year?

**Comment by Deee92** [comment]
Hi @algomaster99, yes please do. Thanks!

**Comment by algomaster99** [comment]
@t-sorger could you please push an empty commit to trigger the workflow?

**Comment by t-sorger** [comment]
@algomaster99 done

**Comment by algomaster99** [comment]
Thanks!

**Comment by DavidCWQ** [comment]
Hi! We'd like to give you some feedback on your Week 7 demo. Hope you're open to it. @t-sorger & @Limph1

**Comment by t-sorger** [comment]
Hi @DavidCWQ, if you want you can give us feedback on our demo. Since this is a sync task, you will need to give the feedback before Wednesday (right?), so we can arrange an online (Zoom) meeting, where we can present the demo to you in a dry run. We are not completely done with the demo yet (in terms of timing/text). We propose tomorrow evening (around 20-21 o'clock); feel free to write me/us an email to agree on a time/further alignments.

**Comment by DavidCWQ** [comment]
Hi @t-sorger, Yes, we will provide the feedback before Wednesday as planned. Apologies for just noticing your reply. The time you’ve proposed works for me, but my partner may not be available at that moment. Would you mind if I record the meeting on Zoom so we can review it later? 20:30-23:30 today works for me on zoom.

**Comment by t-sorger** [comment]
Further communication by mail :)

**Comment by DavidCWQ** [comment]
# Feedback

> Given by Wenqi Cao (wenqic@kth.se) and Katsutoshi Amano (amano@kth.se).

First of all, we want to thank Arber and Tom for allowing us to provide feedback on their demo. Additionally, we also appreciate that you gave us the demo via zoom and allowed us to record. This helps us provide better feedback for the contents presented.

### Code of Conduct

> *We certify that generative AI, incl. ChatGPT has not been used to write this feedback. Using generative AI without permission is considered academic misconduct.*

---

### High-level Strengths & Weaknesses

#### Strengths

- **Good hook**: The question presented on the first slide is very engaging, with impactful sentences and pictures. We can know that you’re addressing an important issue that is worth solving.

- **Clear overview**: The overview of the demo structure is listed, and it is clear and simple. The demo follows the structure of the plan, and the time allocated for each section is appropriate.
- **Nice pictures**: The pictures on page 7 and page 9 are fun and interesting which attracts the attention of the audience very well. These pictures also support the contents that are being presented. 
- **Well-prepared code demo**: The demo code is well-set-up, runs as expected. There are no bugs from start to finish. Also, the demo includes a detailed explanation of code, that makes it easy to understand what is happening.

#### Weaknesses (with improvements)

- **Unnecessary logos/Missing structural diagram**: There are some large logos in your presentation that don’t necessarily help us understand the content. In contrast, there are no structural diagrams that explain how each component (Vagrant, Ansible, nginx etc.) is connected.

  > You can add the diagrams to explain visually. It can include Vagrant, Ansible management node, Playbook, Inventory and two nginx components that represent the development and production environment. Refer to the pictures in [additional links](# Additional Materials & Links), and e.g., replace host 1 and host 2 to two nginx components.

- **Insufficient to solve the hook problem:** Your demo demonstrates how Ansible Playbooks can easily and precisely separate the development and production environments. However, this separation may not fully prevent the hook problem, pushing an error-prone program to the production environment by mistake. 

  > By integrating Ansible with other CI/CD tools, e.g., GitHub actions, you can address the hook problem more effectively.

- **Overlap yaml intro between presenters**: As one of the presenters have already introduced yaml file systematically in page 6, the other presenter doesn’t have to introduce yaml concepts in demo.

  > Include the “role” in page 6 to avoid introducing new concepts in the code demo or moving the introduction of yaml components to code demo.

- **Take-home message being too broad**: The take-home message is aligned with the IaC topic but may not be closely related to the contents in demo.

  > Specify the message to what Ansible can bring or how it solves the initial hook problem you proposed.

### Feedback on specific page/sections

#### Demo - Linux Terminal

In the first of the demo, an important command to run Ansible Playbooks is executed, but it lacks detailed explanation. You can explain in detail what you are doing and what will happen when the command is executed. Besides, you can run `clear` command after the environment has been set up (if necessary) to avoid the terminal display being messy.

#### Reflection - Ansible

As a disadvantage of ansible playbooks, it is mentioned that they become slower on larger scales. However, it is not explained why it occurs. You can identify the reasons and improve the performance by using some techniques. Additionally, comparing to other IaC tools like Terraform can give you further insights.

### Overall Comments/Summary

The presentation starts with a strong and engaging hook about accidentally pushing to production. It is well-connected to the main topic of Infrastructure as Code (IaC). The demo shows how to use Ansible to separate production and development environments, which is relevant to the problem introduced in the hook of the first page. While it’s helpful to separate environments, it may not fully address the problem in hook, especially mistakenly pushing code. The conclusion aligns well with the topic but could be enhanced by integrating with the Ansible contents presented in the demo. The overall flow is solid, and the demo is well-prepared. Be careful with the time limit and good luck in the final demo!

### Additional Materials & Links 

[1] [What is Ansible and How it works](https://www.devopsschool.com/blog/what-is-ansible-and-how-its-works/).

[2] [8 ways to speed up your ansible notebooks](https://www.redhat.com/sysadmin/faster-ansible-playbook-execution).

**Pull request merged**
