### PR TITLE
Tutorial Proposal- Azure DevOps Pipeline

### PR DESCRIPTION
**Pull request by hittesharma**
Describing & implementing features of Azure DevOps and explaining how it provide one stop environment for implementation of CI/CD pipeline with ease.

### CODE REVIEW

**Comment by gluckzhang** [comment]
Hi @hittesharma , I assume you have already read some documents of Azure DevOps. Could you add ref links in your `README` file. You should also mention key features you are going to introduce, which helps to define the scrope of your tutorial.

**Comment by hittesharma** [comment]
Hi @gluckzhang, I have not gone through any documents this time; I have prior experience in DevOps in the IT industry for quite a long time so I understand the implementation. But as far as scope is concerned- I would like to share that my team and I will provide the implementation of Nodejs (or similar) code CI/CD pipeline if it is possible in Azure "free tier" (CI is possible, need to check for CD once I start). I hope that this topic could lead to distinction if done as per your guidelines (let me know if it does not, I will consider changing it). Feel free to ask for any further queries. And I would like to complete it ASAP so looking forward to a quick consensus.

**Comment by gluckzhang** [comment]
> Hi @gluckzhang, I have not gone through any documents this time; I have prior experience in DevOps in the IT industry for quite a long time so I understand the implementation. But as far as scope is concerned- I would like to share that my team and I will provide the implementation of Nodejs (or similar) code CI/CD pipeline if it is possible in Azure "free tier" (CI is possible, need to check for CD once I start). I hope that this topic could lead to distinction if done as per your guidelines (let me know if it does not, I will consider changing it). Feel free to ask for any further queries. And I would like to complete it ASAP so looking forward to a quick consensus.

Hi @hittesharma , "provide the implementation of Nodejs (or similar) code CI/CD pipeline" is still unclear to me. Do you mean using NodeJs to implement pipeline scripts in Azure that supports CI/CD for an application, or implementing a demo application in NodeJs (or similar) and set up a CI/CD pipeline with features provided by Azure on its dashboard?

There are lots of features provided by Azure DevOps, for example (https://docs.microsoft.com/en-us/azure/devops/pipelines/?view=azure-devops)

- build apps: multiple branch, multiple platforms, caching
- test apps: parallel testing, flaky test management
- deploy apps: to Azure, to VMs, to Kubernetes
- ...

You will not cover everything in your tutorial. That's why I asked more about the scrope.

It's definitely possible to get a P+ with this idea. But I could not guarantee it now because the [grading criteria](https://github.com/KTH/devops-course/tree/master/contributions/tutorial#grading-criteria) is not only about the topic itself.

**Comment by hittesharma** [comment]
Hi @gluckzhang 
As far as scope of the tutorial is concerned, I wish to present the basic implementation of Java/ NodeJS code using the features provided by Azure Cloud. Here, this Java or NodeJS are nothing but a random code just used to demonstrate the implementation of Azure CI. **We are using only Azure features and YAML for the implementation of pipelines.**
It also includes, demonstrating the introduction and little implementation (not exhaustive) of Boards, Repos and Artifact- this is done to demonstrate how gracefully Azure DevOps is providing all the DevOps and Agile tools interconnected under one roof. Apart from that, the implementation of the pipeline will be more robust, using some random open-source JAVA project.
It includes creating basic CI pipelines on Azure, providing creating a basic CI pipeline, how the user can customize the CI pipeline, involving approvers intervention in the pipeline for pushing the code to the next higher environment, how the code coverage is checked in Azure DevOps, what are 'tasks' and how we use it in Azure DevOps. It does not cover any specific test cases or test apps but we will try to include basic tests to demonstrate how they are taken care of during CI process in Azure, we will be using Linux VM (if possible in free tier). This all demonstration will be done on actual Azure DevOps environment and the document will carry sufficient screenshots for guiding the steps. 
This will help to understand Azure DevOps in an Agile project implementation of an organisation.

With reference to the document you shared-
Build repository: Azure Repos GIT/ GitHub
Build and deploy: Java

We have started working on this due to our availability on weekend. Let me know if you are looking for any other details.

**Comment by gluckzhang** [comment]
@hittesharma thanks for the answer. Now it's very clear. Please add your response into the `README` (you could update it again when you submit your final work) so that I could merge this PR :)

**Comment by hittesharma** [comment]
Thank you @gluckzhang for the quick response. I appreciate that. README file has been updated you may proceed for merging the PR.

Note:
It might be possible that we may not be able to write simple/ self-explanatory details in the document due to the overwhelming relevant content of CI/CD in Azure DevOps. But I don't want to reduce the scope as we have spent time in gaining the understanding and would like to express it there as much as we can. Hope this will not affect the distinction requirements.

**Comment by gluckzhang** [comment]
> Thank you @gluckzhang for the quick response. I appreciate that. README file has been updated you may proceed for merging the PR.
> 
> Note:
> It might be possible that we may not be able to write simple/ self-explanatory details in the document due to the overwhelming relevant content of CI/CD in Azure DevOps. But I don't want to reduce the scope as we have spent time in gaining the understanding and would like to express it there as much as we can. Hope this will not affect the distinction requirements.

@hittesharma , thanks. The PR has been merged! It's fine to introduce what you have learned without too many details.You could also add ref links if you think readers could find lots of related content while you don't need to explain them in your tutorial.

**Comment by hittesharma** [comment]
[Azure.DevOps.Pipeline.and.More.pdf](https://github.com/KTH/devops-course/files/4496885/Azure.DevOps.Pipeline.and.More.pdf)

**Comment by gluckzhang** [comment]
> [Azure.DevOps.Pipeline.and.More.pdf](https://github.com/KTH/devops-course/files/4496885/Azure.DevOps.Pipeline.and.More.pdf)
> 
> FEEDBACK REQUESTED on ESSAY

Hi @hittesharma , it's fine for now. Don't forget to add this pdf to your task folder before the deadline.

**Comment by monperrus** [comment]
Dear Hitesh, Avijit, 

Thanks for the first version of the tutorial. Here is the feedback.

> Criterion: The TA can successful execute all the commands of the tutorial (mandatory)

No. The tutorial is based on heavy GUI usage, out of the scope of reproduction (they are not "commands")

> Criterion: The tutorial gives enough background 	

No: There is no background section, some definitions are given on the fly. Action: introduce a background section which defines the key terminology and concepts used in the tutorial

> Criterion: The tutorial is easy to follow

Yes: enough details are given, with good writing.

> Criterion: The tutorial is original, no such tutorial exists on the web:

No. Many similar tutorials exist, starting with the official Microsoft documentation 	

> Criterion: The tutorial contains fun facts or easter eggs

Partly. The tutorial contains boxes "Fun facts", which give trivia about the topic, it's not fun per se, but it's a good idea that makes reading pleasant. 

> Criterion: The tutorial is successful (attracts comments and success)

Not applicable, it's not published on a platform with outreach.

> Criterion: The tutorial is doable in the browser without a local environment (eg on katacoda.com) (optional)

No.

To pass, you must have at least 4 "yes". To achieve this, I would suggest 1) to add proper background 2) to elaborate on the fun facts 3) originality: to explain a rare feature from Azure DevOps which is little known and poorly documented in the official documentation. 

See also comments over email.

**Pull request merged**
