### PR TITLE
Course automation proposal : Automatic mail of confirmation for PR merge success

### PR DESCRIPTION
**Pull request by simonebonato**
# Assignment Proposal

## Title
Automatic email of PR merge success and calendar event.

## Names and KTH ID
  - Khalid El Yaacoub (khalidey@kth.se)
  - Simone Bonato (bonato@kth.se)

## Deadline

April 5th - Task 1

## Category

Course Automation

## Description

We designed a GitHub action that automatically generates an email confirmation that notifies the students with the details of their PR (title, description, deadline) and additional information (who and when accepted the PR), when it is merged in the main branch.

The github action does the following:

- On merge, parses the PR description and determine its details.
- Writes an email that contains a calendar event for the date of the deadline at 17pm if the deadline was written correctly in the body of the PR (it contains "task #"), otherwise it only includes the PR details and the info regarding who accepted the PR.
- Sends an email w/details to parsed addresses.

We thought it could be useful in order to give the students a confirmation that their request has been accepted and a further reminder about the deadline of their intended task.

### CODE REVIEW

**Comment by javierron** [comment]
Hello @simonebonato, thanks for the proposal. This action looks very useful.

I would like to know:
- Which are the group requirements that your tool checks?
- The PR is considered successful only if it is merged. Is the email sent after the merge?

**Comment by simonebonato** [comment]
Hi @javierron,
The action checks the group requirements that are stated in the GitHub page, namely "Group work is encouraged (max 2 persons) but you cannot be with the same persons for more than 2 projects. You can work alone for one or at most two projects".

And at the moment the email is sent whenever there is a PR and the requirements mentioned above are satisfied to notify the students that they are eligible to make the PR. But given your suggestion it could also be useful to send it anytime the PR is merged, but at that point the group requirements should have already been satisfied.

Essentially our aim was just to let the students know that the PR was sent successfully and they satisfy the group requirements.

We'll be waiting for further directions.

**Comment by javierron** [comment]
A task which checks these specific rules has already been proposed on #1650.

I would gladly accept a similar proposal which enforces another set of checks, but not these ones specifically.

**Comment by khalidey** [comment]
@javierron 
Since the group requirements has already been proposed, how about we instead send an automatic mail of confirmation of the PR (basically when the PR has been merged and accepted). This automatic mail would be sent only after the PR has been merged and provides details to the students regarding their PR (title, type, deadline etc...). 

We think this could be very useful for students.

**Comment by javierron** [comment]
> We think this could be very useful for students.

I agree, email integration with CI can be useful.

 Please update your proposal title and description accordingly. As I understand your action now would:
- On merge, parse a PR description and determine its details.
- Send an email w/details to parsed addresses.

I will accept this task if further integration between merge event and email is implemented. (e.g. mail includes calendar event? details about the PR merge itself?)

**Comment by khalidey** [comment]
@javierron 
We have updated our proposal title and description accordingly.

**Comment by javierron** [comment]
>We have updated our proposal title and description accordingly.

Thanks @khalidey. 

I wait until you address the last part of my previous comment before we merge.

**Comment by khalidey** [comment]
@javierron 
When you mention "further integration between merge event and email is implemented", do you mean that we should not only send a plain email to the students? Currently we send a body of text (with a subject) to the students which details their PR merge (Deadline, Category and Description). We considered adding a calendar event but the input made by students when they make a PR is arbitrary and has no certain structure and we already remind them of the deadline in the body text anyways.

Is there something else you want us to add?

**Comment by javierron** [comment]
> do you mean that we should not only send a plain email to the students?

@khalidey The email is a useful way to notify the students. I think we agree on that. However, with the current proposal, the content of the email would be the same that the student already wrote in the first place, which is not very informative. My point is that the email should contain information that is only available after the merge.

> We considered adding a calendar event but the input made by students when they make a PR is arbitrary

The deadlines are fixed, and part of the proposal template. Creating a calendar event is possible with this information.

Consider as well adding information about the PR merge event (Who merged your PR?, when?)

**Comment by khalidey** [comment]
@javierron 
That sounds good. 

We will add further integration between the merge event and email. This will include adding a calendar event for the deadline of the given task at 17h. We will also add additional information regarding the PR merge event such as who merged the PR and when they have merged the PR.

**Comment by simonebonato** [comment]
We also updated the title and description of the proposal accordingly.

**Pull request merged**
