### PR TITLE
Essay Proposal: Low-code Ops and the art of abstraction

### PR DESCRIPTION
**Pull request by hassbring**
# Essay Proposal: "Low-code Ops and the art of abstraction"

## Members
Isak Hassbring (isakha@kth.se)
Github: [hassbring](https://github.com/hassbring)

Gustaf Lidfeldt (lidfeldt@kth.se)
Github: [glidfeldt](https://github.com/glidfeldt)

## Topic
We would like to write an essay on the *no-code / low-code* abstraction practice and its rapid evolvement. We will critically review its emergence in devops and talk about about devops from the bigger perspective - abstraction. 

## Introduction

DevOps in general could be seen as a set of practices serving as abstraction layers that aims to let more people be more effective, by building an interface around difficulties - hence abstracting them away. The same goes for many other engineering fields, e.g. Computer Engineering is an abstraction on Electical engineering and programming languages are actually abstractions (nowdays multiple layers) on machine code. Among programmers, a one-liner is often considered superior compared to multiline programs (given equal task and performance). Why? Because we love the art of simplicity and abstraction.

In the no-code space, the computer program Excel is typically seen as the birth of the practice (in ~1985), as it lets "the average Joe" compute calculations without programming skills. Now, a lot has happened since then. Today, platforms such as Peltarion.ai even go beyond the once beloved one-liners and let creators (people building applications) set up, train, test and deploy cutting edge deep learning techniques without writing code. Bubble.io lets you write *interactive* front ends, also as a no-code practice. Shuttleops.io offers a no-code continuous delivery platform that literarly lets you *draw* your operations infrastructure / architecture and deploy.

We all know what the emergence of the no-code platform wordpress.org meant for web developers as it completely reshaped their industry.

So, what does this mean for the devloper teams as well as the operations? Is this the beginning of the end of devops as we know it?

We will explain *why* this matters for a devops engineer (or any engnineer in general!) and discuss the practical implications of low-code today and in the future.

### CODE REVIEW

**Comment by DSharifi** [comment]
I'd like to give feedback on this essay if the proposal is accepted 😄

**Comment by hassbring** [comment]
@cesarsotovalero @khaes-kth @Deee92 Can we start working? Really eager to get going as we must finish within 10 days 😊

**Comment by khesoem** [comment]
> Can we start working?

Yes you can. Good luck!

**Comment by johanmallobakken** [comment]
I would like to give feedback on this Essay! Created a new PR (#1264) for feedback now that @DSharifi has discontinued the course.

**Pull request merged**
