### PR TITLE
Open-source proposal: Wemake Python Styleguide

### PR DESCRIPTION
**Pull request by ruwaid4**
# Open-source proposal
## Members
Ruwaid Louis (ruwaid@kth.se)
GitHub: @ruwaid4

David Stevens (dstevens@kth.se)
Github: @stevensdavid

## Proposal
Create a new rule for Wemake Python Styleguide along with all of the required tests and get it approved by the maintainer.
GitHub Repo: https://github.com/wemake-services/wemake-python-styleguide

## Description
Wemake Python Styleguide strives to be the strictest linter ever. It has an active community in GitHub and is very popular. It is essentially a flake8 plugin making it very easy to use for anyone wanting to put themselves in agony.

### CODE REVIEW

**Comment by ruwaid4** [comment]
We were thinking either 
https://github.com/wemake-services/wemake-python-styleguide/issues/1241
or
https://github.com/wemake-services/wemake-python-styleguide/issues/1182

**Comment by gluckzhang** [comment]
Hi @ruwaid4 , the project has met our selection criteria and it's related to DevOps. I think both of the issues you mentioned are OK to be the task. But I would like to invite @monperrus and @bbaudry to review the PR.

**Comment by monperrus** [comment]
Thanks for the proposal. Linters are very important in a Devops pipeline.

What's the average amount of code for a new rule in wemake-python-styleguide?

What's your plan B if the rule is not merged in master?

**Comment by ruwaid4** [comment]
@monperrus I would say the average is about 200-300 lines including tests. But LOC is not a good measure for complexity in a project like this especially because of that you will spend more time fighting the worlds strictest linter than actually coding. 

I guess the PR we make on their repo should be sufficient to show the work we've done even if it isn't merged. We could also try another issue if we fail to complete one since there are plenty.

**Comment by monperrus** [comment]
I like the concept of making a PR on a repo with extremely tough linting. It's fun and you'll likely
learn a lot.

In case the PR is not merged, we'll need to have a proof that you worked hard and you'll write a 2-3
page document reflecting on the failure.

Challenge accepted!

**Comment by gluckzhang** [comment]
> I like the concept of making a PR on a repo with extremely tough linting. It's fun and you'll likely learn a lot. In case the PR is not merged, we'll need to have a proof that you worked hard and you'll write a 2-3 page document reflecting on the failure. Challenge accepted!

Thanks Martin! The PR has been merged :)

**Comment by ruwaid4** [comment]
We decided on issue: https://github.com/wemake-services/wemake-python-styleguide/issues/1239#event-3196692738

**Pull request merged**
