### PR TITLE
Presentation proposal, week4: Monitoring. tracing. observability in DevOps

### PR DESCRIPTION
**Pull request by hmellin97**
Paul Löwenström: paulher@kth.se
Henrik Mellin: hmellin@kth.se

Topic: Monitoring in DevOps

We would like to do a presentation on the monitoring phase in DevOps cycle

* what it is
* different ways of monitoring and their pros and cons.
* give an example using an existing service

### CODE REVIEW

**Comment by gluckzhang** [comment]
Hi @hmellin97 , thanks for the proposal. Definitely interesting and relevant. Note that there are overlaps among these three concepts, for example, monitoring and tracing could be different aspects of observability. Will you introduce the differences of them during your presentation?

**Comment by hmellin97** [comment]
Hi @gluckzhang, how about if we focus mainly on the _monitor_ part and discuss its uses and available services?

**Comment by gluckzhang** [comment]
Hi @hmellin97 , that sounds good. You could introduce different ways / levels of monitoring and their pros and cons instead. Could you update the `README`? Thanks :)

**Comment by hmellin97** [comment]
@gluckzhang done!

**Comment by gluckzhang** [comment]
@hmellin97 merged, thanks!

**Pull request merged**
