### PR TITLE
Updated references in my essay

### PR DESCRIPTION
**Pull request by keivanm**
I noticed that my references at the end of my essay were not clickable so I fixed it and that is the only thing I've added in the essay. The content is exactly the same as the essay I submitted yesterday.

### CODE REVIEW

**Comment by monperrus** [comment]
The diff also contains changes for the demo, please remove them from this PR.

**Comment by keivanm** [comment]
> The diff also contains changes for the demo, please remove them from this PR.

Sorry, I've tried but I can't get the commits from the demo to not show up.

**Comment by monperrus** [comment]
Please try harder. This level of Git/Github knowledge and skills is expected to achieved at this point in the course.

**Comment by keivanm** [comment]
The issue is now fixed and I'm closing this pr. Pr #913 is the new current one.

**Pull request closed without merging**
