### PR TITLE
Completed Demo: Using Terraform with GCP server for static IP webhook calls

### PR DESCRIPTION
**Pull request by akhilyerrapragadaa**
Updated Readme with link to URL.

### CODE REVIEW

**Comment by Mema5** [comment]
Hi! I am interested to give feedback to you :)

**Comment by jonasjohansson8908** [comment]
Hi I will give feedback on this one!

**Comment by johansettlin** [comment]
Hi i would like to give feedback!

**Comment by JoarEkelund** [comment]
I will give feedback

**Comment by akhilyerrapragadaa** [comment]
Thanks @Mema5, @jonasjohansson8908, @johansettlin. Please go ahead :)

**Comment by nagavem** [comment]
I would like to give feedback

**Comment by akhilyerrapragadaa** [comment]
Thank you @nagavem. Please go ahead :)

**Comment by nagavem** [comment]
Found the topic chosen to be very interesting and thought provoking.
The demo is crisp and concise in nature and has been made very informative by giving a background on introduction.
Overall a nice demo 😄

**Comment by Mema5** [comment]
You welcome @akhilyerrapragadaa . Here is my feedback:

# Feedback
Nice demo of something definitely not easy to do!

## Positive points
- :+1: everything is there, the demo is self-contained
- :+1: you did that alone: well done! 
- :+1: your mouse easy to follow and the progression of the demo is smooth
- :+1: the video actually triggered conversation in the comments in only 1 day!!
- :+1: good and accurate title

## Points to improve
- I had to pause the video all the time to be able to follow, consider:
   - having more concise subtitles
   - recording yourself reading the subtitles
- more straight-forward to do: you can improve the video description to make it more clear what you are solving and what is the targeted audience (people who know GCP, NAT, IP...)
- consider having a take home message at the end, it was required in the grading criteria for screencast I think :o

**Comment by akhilyerrapragadaa** [comment]
@nagavem  Thank you for the feedback. Glad you liked it :)

**Comment by johansettlin** [comment]
Nicely done demo on a topic that seems to be very technical and hard to do. Some things to consider is that you could explain more in depth of what you are actually doing (What is a GCP server, a bucket etc) for those who are not experts in the field unless you are targeting a specific audience. 

Also since the demo var very technical you could make the video a little bit longer just to make it easier to follow and read the notes.

**Comment by akhilyerrapragadaa** [comment]
@Mema5 Thank you for the feedback. Specifically, the points to improve section. Its always good to know the areas we can improve and make it better for viewers. Once again, really appreciate your feedback :)

**Comment by JoarEkelund** [comment]
Nice demo with an interesting topic.

The demo is on the shorter side and some extra time could be spent on giving a deeper explanation of the topic and technical aspects of the demo. Those slides that contain a lot of text could have been given som extra screen time so the viewer have enough time to read.

Overall a nice demo, good work! :)

**Comment by jonasjohansson8908** [comment]
Cool demo!
It seems like something that is quite hard to do and very DevOps. You show everything from start to finish and no steps are missed.
The font size of the terminal, web page, and documents were large enough and very readable.
I like that you have an introduction where you show the structure as a graph.

What I think could be improved:

The text doesn't always go nicely with the video, a lot happens at once. I had to pause to see both the text and follow what was happening.

It wasn't always explained what you were doing and why the different steps in the demo were needed.

2:15-2:40 could probably be fast-forwarded as it is only loading.

There is no take-home message at the end of the video.

Consider having an easter egg if you want to fill that criteria.

Good job!

**Comment by akhilyerrapragadaa** [comment]
@johansettlin Thank you for the feedback. Agreed, the demo was targeted for specific audience. Especially, towards terraform enthusiasts and google cloud platform (GCP) users. Also, to encourage the usage of webhookrelay. Since most of the viewers search for "Short and To Point" videos in youtube, I have decided to make it concise to point. However, as you suggested, since the topic is technical it can be extended further. Once again thank you for your valuable inputs :)

**Comment by akhilyerrapragadaa** [comment]
@JoarEkelund Thank you for your feedback. Happy that you find it interesting. Will make sure that the viewer is given enough time, will truncate and split the text. Once again, thank you for feedback :)

**Comment by akhilyerrapragadaa** [comment]
@jonasjohansson8908 Thank you for the feedback. Will look towards adding a take home message and refining the text. :)

**Pull request merged**
