### PR TITLE
Tutorial submission: Azure.DevOps.Pipeline.and.More

### PR DESCRIPTION
**Pull request by hittesharma**
As instructed in https://github.com/KTH/devops-course/pull/379 adding files.

### CODE REVIEW

**Comment by hittesharma** [comment]
@gluckzhang Please check now. 
Also, my essay had been merged but was outside the folder. So it would be good if you could maintain it in the folder structure of 'hiteshs/Essay'

**Comment by gluckzhang** [comment]
Hi @hittesharma , the file `presentationLink` has been deleted. However, `contributions/presentation/DevOps Pipeline in IT Industry.pdf` this file has not been fixed yet. It's still located in the root folder of the presentation instead of your personal task folder.

**Comment by hittesharma** [comment]
Thanks! 
I have removed it now.

**Comment by gluckzhang** [comment]
OK, merged, thanks @hittesharma !

**Pull request merged**
