### PR TITLE
Course Automation: Check Feedback Requirements (Final Submission) (Updated)

### PR DESCRIPTION
**Pull request by Grunler**
## Members

August Jönsson:
Github: Augustjon
KTH account: augustjo

Daniel Grünler:
Github: Grunler
KTH account: grunler

 ## Submission 
We have created a Github Action that can be used to automate some part of the evaluation of the feedback task. When people in the KTH course DevOps give feedback to their fellow students, that feedback has to pass certain requirements. We have focused on 2 of these requirements:

1. The feedback is substantiated meaning that the word count is at least 500 words, and if the word count is above 1000 then the feedback is considered remarkable. The Github Action uses input variables so that the limits can be modified in future course offerings as required.
2. The feedback should be submitted 4 days before the submission deadline of the task. As this deadline might also be subject to change in future course offerings we decided to let the course administration set the deadline for the feedback as an input to the Github Action.

## Functionality
The Github Action uses octokit to issue a get request for a README.md file in the specified path from the PR head. The action then calculates/estimates the number of words in the markdown file. The word count is compared to the requirements (pass and remarkable). The action also compares the time of the action trigger to the specified deadline to check if the submission is timely enough to pass. This information is then posted as an issue comment on the pull request.

### Not included
We have decided not to include feedback checks for the following: 
* remarkable submission time 
* quality of feedback
* pointers to additional material
* acting on feedback

These points all raised issues with ambiguity making them either very hard or subjective.

Instructions on how to use the action can be found in the README in our folder or [in our fork](https://github.com/Grunler/devops-course/blob/deployment/contributions/course-automation/augustjo-grunler/README.md).

## Assessment

This is our assessment of the grading criteria

| Criteria                                                                     | Yes                             | No | motivation                                                                                                          |
|------------------------------------------------------------------------------|---------------------------------|----|---------------------------------------------------------------------------------------------------------------------|
| The automation task produces a PR status or issue / PR comment               | yes                             |    | Our action creates a pr comment on the person giving feedback's pr                                                  |
| The automation task is reusable                                              | Yes (next year for this course) |    | Yes you should be able to reuse this action in later years, changing deadlines and different wordcount requirements |
| The task runs on a standard platform                                         | Yes (github action)             |    | yes it is a github action                                                                                           |
| The code for the task is available                                           | Yes                             |    | the code is avaliabe at the fork https://github.com/Grunler/devops-course                                           |
| The work is done before April 6, 2021 (in order to be useful for the course) | Yes (sort of)                   |    | it is submitted on 6 april                                                                                          |

### CODE REVIEW

**Comment by Grunler** [comment]
@cesarsotovalero we believe the automation task is ready for review

**Comment by Grunler** [comment]
After submitting this PR the grading criteria have been updated to include information that the action should be implemented in a standalone repo. As such we've created a separate repo: 
https://github.com/Augustjon/Feedbackcheck-action

We have also included tests to validate that our action works:
https://github.com/Grunler/devops-course/pull/23
https://github.com/Grunler/devops-course/pull/24

@cesarsotovalero would you like us to create a new PR where we remove the action code from the fork?

**Comment by SophieHYe** [comment]
Thanks for your PR. For the security consideration, we would like to ask you to remove all the code to your fork repo and give the repo link in the ReadMe is enough. Your PR only contains a few (one or two ) changed files (ReadMe and yml if needed). 
Could you please update your PR and we will come back to you. Thanks.

**Comment by SophieHYe** [comment]
Hi,

There are still many code included in your PR, could you remove all the code to your fork repo please? Thanks.

**Comment by Grunler** [comment]
@SophieHYe we removed the files and updated the README with a link to the action in the remote repo and marketplace

**Comment by SophieHYe** [comment]
Thanks. I am merging your work now.

**Pull request merged**
