### PR TITLE
Add feedback demo (#340)

### PR DESCRIPTION
**Pull request by Zodbigt**

### CODE REVIEW

**Comment by gluckzhang** [comment]
Hi @Zodbigt , the feedback support is for a completed task. If you have finished the first version of you demo, could you make a new PR as a submission? You could provide the materials on which you would like feedback there, instead of adding comments on the proposal PR.

That way is better because after receiving feedback on that PR, you could directly push a revised version before it is merged.

**Comment by Zodbigt** [comment]
Hi @gluckzhang! We are done with first version. But we don't understand what you mean by make a submission. Are we spose to add a submission folder in our demo folder? Our demo is a website that is hosted online. Should we just make the the sub folder "submission" and have i readme with some explanation and link to the website?

**Comment by stinalangstrom** [comment]
One other question as well, regarding the screencast. It says in the description about the task that it is optional, is it still so even though this corona-situation? We plan to make a simple one as a complement to our site, but it would be good to know if it is a requirement and how extensive it needs to be in that case. We believe that people get the most out of our demo by trying it themself, and thereby we want to focus more on the website than on the screencast.

As of right now, we do not have a screencast since we want to have feedback of our site and do changes to that before we conduct the final screencast, it this possible or do you require us to have a screencast before getting any feedback?

**Comment by gluckzhang** [comment]
> Are we spose to add a submission folder in our demo folder? Our demo is a website that is hosted online. Should we just make the the sub folder "submission" and have i readme with some explanation and link to the website?

Hi @Zodbigt , I mean you could simply make a PR to update `contributions/demo/tommysam-stinalan/README.md` and put the link there.

**Comment by gluckzhang** [comment]
> One other question as well, regarding the screencast. It says in the description about the task that it is optional, is it still so even though this corona-situation?

The grading criteria will be updated, there is a WIP PR here: #473 

> As of right now, we do not have a screencast since we want to have feedback of our site and do changes to that before we conduct the final screencast, it this possible or do you require us to have a screencast before getting any feedback?

No, it's not required to have a screencast since it's still `optional` in the current version.

**Comment by stinalangstrom** [comment]
Thank you for the answers! We have now made a new PR (#507) and requested feedback, you can close this PR if you want.

**Comment by gluckzhang** [comment]
Perfect. I will close this one and take care of the new one :)

**Pull request closed without merging**
