### PR TITLE
[Course Automation] Final Submission:  Generate Summary Readme on Category Folders

### PR DESCRIPTION
**Pull request by FelixFonteneau**
# [Course Automation] Final Submission: Generate Summary Readme on Category Folders

## Members

Félix Fonteneau (felixfon@kth.se)
GitHub: [FelixFonteneau](https://github.com/FelixFonteneau)

## Proposal

I would like to create an automation that  generate a summary readme for each category folder, based on the content of the contributions, and update when new project

For this, I will do a a Github action on pushes that:

- Check if a new contribution folder is pushed in one category folder or an update in these folders
- Retrieve the information of the contribution (e.g. the contributors, the status, a summary (if possible)... )
- Update the readme of the contribution directory (demo or essay)

## Goal

I plan to get the following of the criteria. 

|                                             | Yes | No | Remarkable |
|-------------------------------------------- | ----|----|-------------|
|The work is done before April 6, 2021 (in order to be useful for the course) |~~Yes~~ |	**No** |	n-a|
|The automation task produces a PR status or issue / PR comment	| **Yes**	|~~No~~	|~~Points to a generated page with valuable additional information~~|
|The automation task is reusable	|**Yes (next year for this course)**|	~~No~~	|In other courses than this one (if they have the same group formation structure)|
|The task runs on a standard platform	|**Yes (Github action)**	| ~~No~~ |	~~Other platforms (e.g. Moodle, Canvas)~~|
|The task is praised by the other students of this course|	**Yes**|	~~No~~|	n-a|
|The code for the task is available	|**Yes (public repo)**|	~~No~~	|**Well documented repo**|

## Submission

You can see the details of the doc, implementation and a demo are available in the dedicated repository [here](https://github.com/FelixFonteneau/readme-Generation-for-Devops-Course).

You can see the effect produced by the Action on my [fork](https://github.com/FelixFonteneau/devops-course/pulls), a PR is created with the modifications of the readmes.

### CODE REVIEW

**Comment by SophieHYe** [comment]
Hi,
Thanks for the excellent work. For the security consideration, we will kindly suggest you remove all the code outside your PR to your fork repo. Is it possible to remove the readme_generation.py to your fork repo?

**Comment by FelixFonteneau** [comment]
I fixed the yaml script by importing the code via a [released](https://github.com/marketplace/actions/readme-generation-for-contribution-category-folders) on the GitHub marketplace. Does this fit your exigences @SophieHYe? :)

**Comment by SophieHYe** [comment]
Thanks for your update. You PR looks great. My concern is about where will you put the generated ReadMe? 
From the demo you provided, it seems it's under the email1-email2 structure.  Will your generated ReadMe replaced the original ReadMe file submitted by students?

**Comment by FelixFonteneau** [comment]
No not at all, It analyses the existing readmes under the email1-email2 student's folders, then gets all the information it can. After retrieving, all the data is concatenated in form of a list in the category folder readme e.g. the readme of demo or presentation. The student's readme is never modified. 

Also, if there is already a text in the category readme, it will keep it and just update the generated list. 

You can see an example of commit that this course automation can provide on my [fork](https://github.com/FelixFonteneau/devops-course/pull/7/commits/c51dd0b3b1d49da57e5f9d2ad67ff5b1174c7f86).

I thought my [readme](https://github.com/FelixFonteneau/readme-Generation-for-Devops-Course) was clear enough, but feel free to tell me what is not clear so I can rewrite the parts. :)

**Comment by SophieHYe** [comment]
Thanks for your explanation.  I am merging your work now.

**Pull request merged**
