### PR TITLE
Tutorial submission: Implementing Azure DevOps

### PR DESCRIPTION
**Pull request by sujon2100**
-Changed Project contributor name
-Updated project tasks

### CODE REVIEW

**Comment by sujon2100** [comment]
Here is the wiki link of the tutorial https://dev.azure.com/KTHDevOpsCourseTutorial/DemoProjectFOrTutorial.

Please give me a feedback, if I need to add something.

**Comment by gluckzhang** [comment]
Hi @sujon2100 , I note that you updated the team information (only 1 member now). If this is correct, please also correct the folder name in this PR. Another suggestion is to add the tutorial link directly into your `README` file.

Regarding the concrete feedback on your work, you could follow the tips here to register a slot: https://github.com/KTH/devops-course/blob/master/contributions/feedback-planning.md

Thanks!

**Comment by sujon2100** [comment]
Hi,

I have changed the name of the file and added the final link of the tutorial here https://github.com/KTH/devops-course/compare/master...sujon2100:patch-6

However, I have created another pull request here https://github.com/sujon2100/devops-course/pull/1. should I keep it or delete it?

**Comment by gluckzhang** [comment]
The updated PR has been merged. Closed this one.

**Pull request closed without merging**
