### PR TITLE
Executable Tutorial: Building a CI/CD Pipeline for a small frontend in a Kubernetes Cluster

### PR DESCRIPTION
**Pull request by Internet-Person-IP**
## Members

Taqui - taqui@kth.se
GitHub: [Internet-Person-IP](https://github.com/Internet-Person-IP)

## Proposal
I want to create an Executable Tutorial for creating a CI/CD pipeline for a Kubernetes Cluster. The frontend will be super simple with a counter and click function.

The current structure of the tutorial:

- Creating the initial frontend, set up frontend with simple tests
- Creating a small cluster
- Containerizing the frontend
- Deploying the frontend to a small pod
- Creating the CI/CD pipeline
- Make changes to the frontend and actually push it to master
- Check that the CI/CD pipeline works correctly and then make sure that the deployed website works correctly

### CODE REVIEW

**Comment by khesoem** [comment]
Hi @Internet-Person-IP 

If I understand correctly, you basically want to show a tutorial on how Kubernetes works, right? If this is true, this PR cannot be accepted because it is too general and there are similar PRs. Like this one: https://github.com/KTH/devops-course/pull/737

If I am wrong, please let me know to reopen your PR.

**Comment by Internet-Person-IP** [comment]
@khaes-kth 

Hi again, thank you for telling me and linking a previous PR. My main concern was how CI/CD might work in a Kubernetes-based environment. However, there are some proposals like that as well for example https://github.com/KTH/devops-course/pull/844 and https://github.com/KTH/devops-course/pull/402.

A possible way to make mine more original would be to leverage terraform for creating this CI/CD pipeline with Kubernetes and Docker.

I hope it makes sense. If there are any other concerns let me know.

**Comment by khesoem** [comment]
Actually, there are also some tasks defined on "Terraform" as well. Make sure that you do not duplicate them before writing your proposal.

**Comment by Internet-Person-IP** [comment]
@khaes-kth So I looked around and I think there are some proposals on Terraform but most of them are Demo. I have not seen an executable tutorial using Terraform so I think that might be able to be called original enough? and especially since I hope to create an entire CI/CD pipeline using Terraform as well.

**Comment by khesoem** [comment]
If there is no tutorial on Terraform, your proposal will not be duplicate. You can go ahead with your idea and open a new PR.

**Pull request closed without merging**
