### PR TITLE
Demo Proposal: Infrastructure as Software with Pulumi

### PR DESCRIPTION
**Pull request by hassbring**
### Member

Name: Isak Hassbring (isakha@kth.se)
Github: [hassbring](https://github.com/hassbring)

### Motivation

Infrastructure as Code is great. There's just one problem - it's usually not code, but static files and domain-specific-languages that for large projects could be thousands and thousands of repetitive lines. E.g. Terraform requires HashiCorp Configuration Language (HCL) and Kubernetes YAML-files does not leverage neither the power of traditional programming languages, nor the wide-spread know-how already out there. 

Entering Pulumi! Pulumi is a cloud agnostic solution where you can use programming languages like Python, Go, and JavaScript to generate the static file infrastructure. You hence get access to familiar constructs like for loops, functions, and classes. This reduces boilerplate and enforce best practices. Instead of creating a new ecosystem of modules and sharing, Pulumi lets you leverage existing package management tools and techniques. Plus, you can automate and simplify stuff in a cool way. Infrastructure as **real** code - or software.

### Will be covered

* Pulumi intro:
  * what is it, why should I bother, !how can I use it
* How-to:
  * Setting up and deploying a simple web app using different IaS solutions cloud agnostic through Pulumi, such as AWS S3, Kubernetes cluster, etc.

### CODE REVIEW

**Comment by hassbring** [comment]
@khaes-kth Hi, thought I'd give you a ping due to a somewhat late proposal. Eager to get going :)

**Comment by khesoem** [comment]
Hi @hassbring ,

Good proposal. Thanks. You can start working on it.

I just do not know if you are still allowed to register a new proposal. Let us ask professors.

@monperrus : Are students allowed to register new proposals for demo or is it too late?

**Comment by hassbring** [comment]
@khaes-kth thanks! If it is to any help, all I could ever find regarding demo deadline is: 

**Google docs:** 
Q: When exactly is the deadline for demos? A: "The day before the demo day, Week 7."

**GitHub repo Readme:**
"The strict deadline for essays, tutorials, contributions to open-source, course automation is April 30, 23h59 Stockholm time; and "demo"; the strict deadline for repeated tasks (all) is May 31, 23h59 Stockholm time. 

(As this is written - demo is clearly outside of the 30/4 deadline)

Hence, according to the available resources, the deadline should be "day before demo day" && "May 31, 23h59 Stockholm time" which should mean that "day before demo day" applies.

**Comment by khesoem** [comment]
I also guess it should be OK. I just wonder if there was a strict deadline for _proposal_ submission.

**Comment by monperrus** [comment]
> @monperrus : Are students allowed to register new proposals for demo

Yes.

**Pull request merged**
