### PR TITLE
Demo: Continuous Integration for react application using circleCI 

### PR DESCRIPTION
**Pull request by MDRezaulHasan**
I am adding a new member to making group. Can you accept my pull request? Thanks

### CODE REVIEW

**Comment by SophieHYe** [comment]
Hi,
Could your update the existing folder name for the demo contribution or delete the old one, otherwise, you will work on two works.

**Comment by SophieHYe** [comment]
Hi @MDRezaulHasan,
Any update for the conflicting demo folder name? Thanks!

**Comment by MDRezaulHasan** [comment]
I will delete the demo folder and create a new folder and send a new pull
request today. Ok?

**Comment by SophieHYe** [comment]
No problem!

**Comment by hittesharma** [comment]
I will give feedback here

**Comment by SophieHYe** [comment]
Noticed you have sent new PRs, can we close this one?

**Pull request closed without merging**
