### PR TITLE
Open-source contribution submission

### PR DESCRIPTION
**Pull request by javierron**
New feature implementation in [ImgBot](https://github.com/dabutvin/Imgbot)

Sigrún Arna Sigurðardóttir (sasig@kth.se)
Javier Ron Arteaga (javierro@kth.se)

### CODE REVIEW

**Comment by monperrus** [comment]
@javierron @s1grun Good work, any news on the final merge?

**Comment by javierron** [comment]
@monperrus Not yet, the repo admin acknowledged our last message (~2 weeks ago), but has not posted anything since then. We are sure he will request some changes, and we will happily implement them, but for now we are stuck until he responds.

**Comment by monperrus** [comment]
@javierron after two week, a polite ping is in order.

**Comment by javierron** [comment]
@monperrus our last message was a polite ping, should we insist?

**Comment by s1grun** [comment]
@monperrus I left a new comment on the PR https://github.com/dabutvin/Imgbot/pull/635 hopefully he will get back to us.

**Pull request merged**
