### PR TITLE
[Final submission] Executable tutorial: Renovatebot

### PR DESCRIPTION
**Pull request by Sebberh**
Authors: 
Sebastian Fagerlind, sebene@kth.se
Kitty Thai, kittyt@kth.se

Our feedback and changes are listed in the comments below

### CODE REVIEW

**Comment by kittytinythai** [comment]
Hello @SophieHYe @cesarsotovalero @khaes-kth @Deee92! No one has signed up for giving feedback to our executable tutorial, could one of you maybe give us some feedback? 😊

**Comment by Deee92** [comment]
Hi @kittytinythai, I'll get back to you with feedback for your tutorial.

**Comment by Deee92** [comment]
### Feedback for Executable Tutorial: Set up Renovate with a NodeJS based Web Application

#### Step 1
Though the toy app is simple, some information about how it is organized, which dependencies it uses, and what it does, would be useful. Consider adding a README on the `GenericNode` repo, and provide a brief introduction to the app in Step 1.
**Note:** The tutorial was followed at https://github.com/Deee92/GenericNode

#### Step 6
Activation of Renovate also involves entering user details such as name and email, and then opens up a dashboard (which is later updated with a log of all the jobs as they are performed on the repo). It would be a good idea to also mention the use of the dashboard and possibly discuss one of the entries corresponding to the tasks performed in the tutorial.

#### Steps 9 and 11
Consider explaining briefly some of the settings in the default configurations in the Renovate configuration PR, as well as the corresponding option in `renovate.json`.

#### Step 12
Discuss in more detail why this is the best / ideal / most effective configuration for Renovate, and not the default configuration? 

#### Step 14
While following along with the tutorial, I got one PR to pin dependencies of `express` and `react` with the same versions as in the screenshot, but the update for `node` was `^16.0.0 -> 15.14.0`, and then got a separate PR to update `node` from `15.14.0 -> 16.0.0` (please refer to the closed PRs in the execution [here](https://github.com/Deee92/GenericNode/pulls?q=is%3Apr+is%3Aclosed)). Is this to be expected or was this caused by a deviation from the steps in the tutorial while following it?

#### Step 15
> Merge the pull request and check that all versions have been pinned.

Discuss what it means for a dependency to be pinned, why it is done, and include an illustration. One way could be by showing the diffs between the original `package.json` and the updated one after the Renovate PRs have been merged.

> Next, we'll break the config on purpose while setting up auto merge for minor updates.

Is this step a part of 15 or 16?

#### Step 16
Describe exactly what we are changing in the Renovate configuration, and why the config is now broken.

#### Step 17
Since I had forked the toy app, I did not have issues enabled on the fork, by default (see [this question](https://softwareengineering.stackexchange.com/questions/179468/forking-a-repo-on-github-but-allowing-new-issues-on-the-fork)). Perhaps this can be clarified in Step 2, like so:

> Fork the repository and enable issues on the fork

#### Step 18
Mention exactly what is being changed in `renovate.json` and why.

#### Step 21
What happens if one does not prefer auto-merge? Briefly discuss which options would be best suited for different use cases, and how the config may be changed.

#### Remarks
- The tutorial was easy to follow. With the exception of the issues highlighted above, all instructions were clear. However, details about why we are doing each step, which settings are being used in the configuration and why, and which other settings there are, would be helpful.
- The introduction can also include a brief discussion about how Renovate compares with similar tools. A takeaway at the end of the tutorial highlighting exactly what the user has learned from the tutorial would also be good.
- The tutorial also includes screenshots to showcase what the user can expect to see, which is appreciated, but the README is a little cluttered. Perhaps a horizontal rule can be used between the different steps, and level 3 or 4 headings can be used for each step. There are some typos that should be fixed.

**Comment by kittytinythai** [comment]
@Deee92 Thanks for the feedback! 🎉

**Comment by kittytinythai** [comment]
### The following changes have been made based on the received feedback
- [x] Add a brief description of the example project in step 1.
- [x] Add a README in the example project
- [x] Add short description about Renovate Dashboard, step 6
- [x] Add brief explanations of x, y and z in step 9
- [x] Add discussion in more detail why this configuration would be desired for Renovate instead of the default configuration, step 12
- [x] Add description of what "pin a dependency" means and an illustration (diff between original `package.json`), step 15
- [x] Move "Next, we'll break the config on purpose while setting up auto merge for minor updates." from step 15 to step 16
- [x] Add description on what have been changing in the Renovate configuration and why it is broken, step 16
- [x] Clarify step 2, add "Fork the repository and enable issues on the fork"
- [x] Add description of what have been changed, step 18
- [x] Step 21, add discussion of auto-merge enabled or disabled, pros and cons
- [x] Add summary in the end of the tutorial
- [x] Update the structure with additional subtitles
- [x] Add short comparison between Dependabot and Renovate in the introduction

**Pull request merged**
