### PR TITLE
Course automation: Submission

### PR DESCRIPTION
**Pull request by bubriks**
# Course automation: Verify pull request content changes

## Members

Ralfs Zangis (zangis@kth.se)
GitHub: https://github.com/bubriks

## Proposal
Ensuring that pull requests can be approved only if the formatting requirements are met. 

## Description
- Check changed .md file contents (contains: task name, members, and description)
- Verify that the member names (from README.md) are represented in the containing folder name
- Confirm that file structure follows the rules (no changes outside members folder in the selected category)
- Inform user if any checks have failed (for more details on what has failed check build)

### Overview:
Code testing the validity of markdown files and the change location is expected to be run on pull requests.
This solution should allow for relatively easy future updates requiring few modifications, as the most complex part is handled by the referenced GitHub action.

### Info about the solution:
To confirm that the file structure follows rules and all changes are within a specific folder a separate python file was created (This was done since this part of the task is unique for this specific problem) and it is called verify_location.py.

For file content validation a GitHub action was created [file content checker](https://github.com/marketplace/actions/file-content-checker). (More detailed description of it can be found following the provided link).

The second python file (verify_folder_names.py)  is used to ensure that the contents presented in the markdown file are represented in the folder names (for example last names of members and category titles).

### Getting started:
To get started a YML file is provided and it showcases how all of the aforementioned solutions can be used in tandem (this file is supposed to be placed inside the workflow folder and it assumes that the python files are located inside the tool folder). To modify the preferred file contents simply change the JSON used within the YML file. Remember that the JSON is composed of regex expressions by which file lines must abide by.

Example of deployed solution can be found in: https://github.com/bubriks/devops-course/tree/course-automation-deployed (changes done from submision pr can be seen here: https://github.com/bubriks/devops-course/pull/9)

And tests performed by forking the deployed solotion can be seen here: https://github.com/bubriks/devops-course/pull/12 (with each commit being a separate test, read comments for more info)

### CODE REVIEW

**Comment by bubriks** [comment]
This pull-request is expected to fail to build since I have changed files outside my folder.

**Comment by bubriks** [comment]
@khaes-kth I think that i am done with this task

**Comment by khesoem** [comment]
Hi @bubriks 

The TAs are going to have a discussion regarding grading automation tasks tomorrow. I'll check your submission afterwards.

**Comment by khesoem** [comment]
Hi @bubriks 

Good job generally.

We are making the grading criteria for course automation more clear. Please have a look at [this link](https://github.com/KTH/devops-course/blob/khaes-kth-course-automation-clarification/grading-criteria.md#course-automation). This clarification is not merged into the main branch yet, but as you see there, we have this requirement:

> You should demonstrate that your automation technique actually works and automatically produces some results. For example, you can fork the Devops-Course repo and activate the implemented Github Action on it and show how it works by making changes in your forked repo.

Please add a pointer to your test repository so that we can see how your Github Actions works in practice.

**Comment by bubriks** [comment]
@khaes-kth tests and example deployment are linked in the markdown file (I hope they are understandable and what was expected)

**Comment by khesoem** [comment]
I had a couple of questions:

1. If I understand correctly, your published Action performs only one of the three tasks that you have implemented. Why don't you combine all of them in the same Action?
2. If I understand correctly, a user of your Action should always provide a json to specify the structure. Why don't you use a default JSON to help lazy users?

**Comment by bubriks** [comment]
> I had a couple of questions:
> 
> 1. If I understand correctly, your published Action performs only one of the three tasks that you have implemented. Why don't you combine all of them in the same Action?
> 2. If I understand correctly, a user of your Action should always provide a json to specify the structure. Why don't you use a default JSON to help lazy users?

@khaes-kth Answer:
1. They were not combined into a single action in order for it to not become too niche. (right now action only verifies the file contents using the JSON input). Limiting action taking place outside folder and enforcing folder names could be considered 2 additional tasks. Therefore, this was done to allow for more use cases (although it is possible I am trying to do too much in this pull request and simple file content verification might be sufficient for this task).
2. The action requires the user to enter JSON in order for the file to be validated against it as default JSON would not provide any meaningful validation (especially since this action should be able to work for many file formats, not just .md)

**Comment by khesoem** [comment]
Good. So, the reason for both choices you made here is that you wanted your Action to be also useful for projects other than `devops-course`. Right?

**Comment by bubriks** [comment]
Yes, exactly

**Comment by khesoem** [comment]
Fine. Let me ask the teachers whether you should specialize the Action for our own repository or not. I'll come back to you soon.

**Comment by khesoem** [comment]
@bubriks
I asked the professors and they confirmed that we would prefer it if you designed "the Action such that it can be easily integrated into our repo just by adding it to the workflow `.yml` file". Do you want to change the structure of your submission or do you want me to merge (and later on grade) it in the current format?

**Comment by bubriks** [comment]
@khaes-kth Would it be ok to leave out the part of the task where I verify that the contents of the .md file are represented within the containing folder names (category-name/member-last-names)? So I would still enforce that changes are within a single folder following the expected file structure and that .md file is formatted correctly (For both of these having separate actions within the same yml).

**Comment by khesoem** [comment]
Can you explain why you prefer to leave that part out? Also, can you explain why you want to have separate Actions? Why not doing it all in the same Action?

**Comment by bubriks** [comment]
@khaes-kth I wanted to leave that part out since it is unique to this course and I didn't want to make 3 actions. As for making separate actions: I want them to be usable outside this course as well. If this change is not possible I can still make 3 actions, it is just that I would prefer them to be separate.

**Comment by khesoem** [comment]
> @khaes-kth I wanted to leave that part out since it is unique to this course and I didn't want to make 3 actions. As for making separate actions: I want them to be usable outside this course as well. If this change is not possible I can still make 3 actions, it is just that I would prefer them to be separate.

I understand. Since in your proposal you have offered all three features, I think you should include all of the. As for the separation of actions, I would say you should keep them in a single one because your Action is supposed to be primarily used for this course.

**Comment by bubriks** [comment]
@khaes-kth I did as you asked and made it into a single action. I hope this solution is understandable.

**Comment by monperrus** [comment]
@bubriks tip: don't push `__pycache__ ` in a repo and use a spellchecking editor (eg <s>saccesfull</s>) in your README

**Pull request merged**
