### PR TITLE
Demo: Designing integration tests with cypress

### PR DESCRIPTION
**Pull request by arxra**
Video on how to design integration tests to scale and how they are different from unit tests.
Examples using cypress to show the differences

### CODE REVIEW

**Comment by arxra** [comment]
Gah, the commits got all messed up :(

**Comment by arxra** [comment]
After reading through the requirements more carefully, I do not belive this would be a good demo video but might be well presented in another manner.

**Comment by arxra** [comment]
To clearify:
I would like to focus on cypress ability to act as a complete integration testing tool.
Using the cypress dashboard to show how tests run in parallel will be a good visualizer for everyone too see how important efficient tests are. There are also some common pitfalls while designing integration tests I would like to cover

**Review by cesarsotovalero — APPROVED** [review]

**Comment by cesarsotovalero** [comment]
> Gah, the commits got all messed up :(

No problem, I'll squash the commits :)

**Comment by cesarsotovalero** [comment]
hi @arxra, +1 on your PR. I'll merge. Good luck!

**Pull request merged**
