### PR TITLE
Executable Tutorial Submission: Building a CI/CD Pipeline for a small frontend in a Kubernetes Cluster using Terraform

### PR DESCRIPTION
**Pull request by Internet-Person-IP**
## Members

Taqui - taqui@kth.se
GitHub: [Internet-Person-IP](https://github.com/Internet-Person-IP)

Kun Wu - kunwu@kth.se 
Github: [Wkkkkk](https://github.com/Wkkkkk)

## Initial Proposal: 
[#1196](https://github.com/KTH/devops-course/pull/1196)

## Feedback
@thestar19 will provide some lovely feedback. Also, please do send us an email if you experience any problems. This tutorial has some pretty tedious setup processes. We went over the tutorial two or three times and everything seems correct.

# Submission

The final product can be found [here](https://www.katacoda.com/taqui/scenarios/code). There will be some wait time to get everything up and running.

## Grading Criteria

|                                             | Yes | No | Remarkable |
|-------------------------------------------- | ----|----|-------------|
|The TA can successful execute all the commands of the tutorial (mandatory) | Yes | No | In the browser 💥 |
|If local execution, runs on Linux | Yes | No | Easy to setup and run  |
|The tutorial gives enough background | Yes 💥| No | Comprehensive background |
|The tutorial is easy to follow  | Yes 💥| No | Well documented |
|The tutorial is original, no such tutorial exists on the web | Yes 💥 | No | The teaching team never heard about it |
|The tutorial contains [easter eggs](https://github.com/OrkoHunter/python-easter-eggs) | Yes | No | Subtle and fun 💥|
|The tutorial is successful (attracts comments and success) | Yes | No | Lively discussion |
|The language is correct | Yes | No | Interesting narrative  💥|

### CODE REVIEW

**Comment by khesoem** [comment]
Hi @Internet-Person-IP 

Please note that you should also remove your old folder.

**Comment by Internet-Person-IP** [comment]
@khaes-kth Hi, I am a little confused. When I look into the specific commit I only see the folder taqui-kunwu folder. Is there something that I am missing.?

**Comment by khesoem** [comment]
> @khaes-kth Hi, I am a little confused. When I look into the specific commit I only see the folder taqui-kunwu folder. Is there something that I am missing.?

You are right. Your current PR only adds a `taqui-kunwu` folder. But your previous PR had added a wrong folder (see [this](https://github.com/KTH/devops-course/tree/2021/contributions/executable-tutorial/taqui-kun)). Please remove that wrong folder and push it in this PR.

**Comment by Internet-Person-IP** [comment]
@khaes-kth So I initially pulled the 2021 branch. I merged it with my branch then fixed the merge conflicts and pushed it. Hopefully, I have done it correctly now. 

Best Regards,

Taqui

**Comment by khesoem** [comment]
Great! Now we wait until you receive your feedback and implement it. Then, we'll merge this submission PR.

**Comment by thestar19** [comment]
# Feedback on #1371
Members:
Alexander Kruger @thestar19 alekru@kth.se

[Feedback proposal #1225](https://github.com/KTH/devops-course/pull/1225)
[Feedback submission #1391](https://github.com/KTH/devops-course/pull/1391)
[submission](https://github.com/KTH/devops-course/pull/1371)
## Summary:
From an overall standpoint, the tutorial was interesting and well done. The only major problem was being forced to enter a creditcard number without context. In a world where scammers constantly try and steal your cookies, this part would be better with some reassurance from the tutorial. 
The readme from the folder seems underutilized. Information that was hard to include in the tutorial or a small easter egg could be placed there. Links to helpful pages or further information for those that want it could be placed here.
### Step 1
When opening the tutorial, the first part of the tutorial is really interesting and well written. The way the tutorial is structured makes it seem like an adventure and really contributes to the way it spins a tutorial into something more fun. If we are to really nitpick, it would be a good addition to mention what GCP stands for; assuming that the user knows at least something about GCP is reasonable but is the only complicated technology not mentioned.
### Step 2
Step 2 starts out with a problem. When registering an account for GCP, a credit card is required. For any previous Android user or Google Play developer, this step should not be a challenge but still represents a problem. Entering your credit card details, regardless of the reassuring logo of Google, still makes my internal alarms go off. The link presented in the tutorial with little to no background makes the alarms worse, especially because the website could be made to look like Google. Here it could be helpful to include more information about why google requires the credit card, how they are going to use it and ways to corroborate that the user is in fact going to right website. This verification could be in the way of recommending the user on what to google to get more information about the project or simply linking a guide about how to understand the SSL certificate.
### Step 3
Step 3 continues with presenting the adventure theme where the user moves through the tutorial like  a hero in a story. The tutorial assume familiarity with basic terminal tools such as simple file editors such as nano. The styling is excellent and provides a professional look. Unfortunately, the editing of files quickly becomes messy and complicated. An example of this can be seen when you need to change some parts of the variable.tf file. The instructions tell you to change the gcp_credentials which “is the directory of the file storage”. This could better explained by including a clear reference to the key obj created previously. The line “Change them to match your project, credentials, and service accounts.” makes this confusion worse by adding more unclear information to the mix. If it refers to other parts of the tutorial, a simple pointer such as mentioned above or simply asking the user to take note in a third party program such as Notepad++ of the paths needed later for example would go a long way to make this section more clear.
With that in mind, seeing your cluster running was fascinating at the very end. Including these kinds of pulls back to reality is great for making the user take a step back from the file system and recognize progress, even if it might seem like a minor step.
### Step 4
Moving from the complicated mess of editing the config files, step 4 is straightforward and interesting. A potential addition would be to explain the files deployment.yaml etc further by briefly walking through their structure and effect. Nothing in this world was as tempting as writing “kubectl apply -f your-specific-file”  when it said that I shouldn’t.
### Step 5
This part was interesting and the configuration file included great comments about it’s structure and effect. I also got stuck here for quite a while with the error 400 googleapi until the problem seemingly fixed itself. The small paragraph at the end was confusing: What does it mean to set the container to public? The google page included many warning and therefore made it harder to understand what the correct steps where. 
### Step 6
Having most of complicated stuff behind you, step 6 was really great moment. I really wish that some pictures were included, perhaps in a separate picture folder in the starting directory if images are hard to add to the left side tutorial part.  The ending on step 6 “If you copy that IP address you will be able to your counter application running” was a letdown as I did not at all understand what I was supposed to do.
### Step 7/8
Step 7 & 8 finished up a really interesting tutorial. I wish that the tutorial ended with potential other tutorials to follow or recommendations about where to go next. A link to an appropiate next step at https://www.katacoda.com/courses/kubernetes would be great or kubernetes own tutorial https://kubernetes.io/docs/tutorials/kubernetes-basics/.

**Comment by Internet-Person-IP** [comment]
@thestar19 Thank you for your feedback and progressively emailing us regarding issues around our tutorial. We have changed our tutorial to hopefully make the tutorial more clear. Here are the changes we made:


## Changes Implemented After Feedback

- Added what GCP stands for
- changed the project name from our to make it more clear that people should have their own unique project name
- Added a message regarding adding a credit card to the tutorial
- Added a Reason why google needs a credit card for using GCP
- Made the process more clear on Step 3 by adding more appropriate language and changing the naming of some variables to make it more clear
- Explained Each File in Step 4 in more detail
- Explained Why the Container Registry needed to be public
- Added a Picture in Step 6 to make it more clear where you will find your IP Address and I also mentioned here how you can find the easter egg

Thanks again for giving us your time.

**Comment by Internet-Person-IP** [comment]
@khaes-kth We have now changed the submission based on the feedback. So hopefully this will be our final submission. If the easter egg is unclear please let us know.

**Comment by khesoem** [comment]
Great, I'll merge this.

**Pull request merged**
