### PR TITLE
sscolari-morello week2 presentation proposal

### PR DESCRIPTION
**Pull request by stefanoscolapasta**
# Assignment Proposal

## Title

Automated Testing for videogames: SUPERNOVA and Agent-Based.

## Names and KTH ID

  - Stefano Scolari (sscolari@kth.se)
  - Gabriele Morello (morello@kth.se)

## Deadline

- Week 2

## Category

- Presentation

## Description

Analysis of the SUPERNOVA framework for automated test selection and defect prevention. 
Overview of agent-based testing and its relevance in the gaming industry. 
Proposed novel integration of agent-based testing with the existing SUPERNOVA framework.

**Relevance**

Testing in videogames has always been a notoriously hard task, due to the dimension of the software, it's dynamicity and non-deterministic nature.
The growing complexity of games has lead to a growing difficulty in organizing and structuring testing in an effective and non cost-prohibiting way.
SUPERNOVA proposes a solution to this problem through the use of Machine Learning. On the other side, QA testing can benefit from the use of agent-based systems whom are capable of mitigating the non-deterministic aspect in videogames, making it possible to automatically play and test the game searching for bugs.

### CODE REVIEW

**Comment by Deee92** [comment]
Hi @stefanoscolapasta, super interesting! Are you presenting an overview of [the research paper that proposed SUPERNOVA](https://arxiv.org/abs/2203.05566), or your own experiences using it?

**Comment by stefanoscolapasta** [comment]
> Hi @stefanoscolapasta, super interesting! Are you presenting an overview of [the research paper that proposed SUPERNOVA](https://arxiv.org/abs/2203.05566), or your own experiences using it?

We were thinking of giving an overview of SUPERNOVA and also explaining how agent-based testing could somehow complement it. Meaning that, we would also give an overview of the state-of-the-art for agent-based testing and propose how it could be integrated in the SUPERNOVA framework (from a high-level point of view). We have no personal experience in the use of none.

**Comment by Deee92** [comment]
I see. Can you clarify what is meant by agent-based testing? Is the agent a bot?

**Comment by stefanoscolapasta** [comment]
> I see. Can you clarify what is meant by agent-based testing? Is the agent a bot?

Yes, the papers we read use a set of different frameworks to achieve this. An example is Iv4xr, inspired by the BDI (Belief-Desire-Intent) agents. The agent is connected to the GUT (game under test) through its interface and programmed to achieve the wanted tasks and behaviours to carry out the testing objectives.

**Comment by Deee92** [comment]
Cool, sounds interesting.

**Pull request merged**
