### PR TITLE
Tutorial suggestion: Implementing Imgbot on OSS

### PR DESCRIPTION
**Pull request by louisezetterlund**

### CODE REVIEW

**Comment by louisezetterlund** [comment]
# Tutorial Proposal
 ## Members
 Louise Zetterlund (louiseze@kth.se)
 Johanna Iivanainen(jii@kth.se)

  ## Topic
 Implementing [Imgbot](https://imgbot.net/) on OSS 
  Our plan is to create a video-tutorial on how to use Imgbot and how to implement it on your Open Source Software.

 
  ## Tutorial
  We will show step-by-step how to implement it and how to use it.

**Comment by gluckzhang** [comment]
Hi @louisezetterlund , it seems that you are using the same branch to create PRs for tutorial and open-source contribution. Please use different branches so that they won't affect each other :)

**Comment by louisezetterlund** [comment]
Created new PR

**Comment by gluckzhang** [comment]
Hi @louisezetterlund , Imgbot is an interesting project, thanks for the PR! After taking a look at their webpage (https://github.com/marketplace/imgbot), I feel like **integrating** (not **implementing**) Imgbot into a project is sort of straightforward. Because it is a GitHub app that could be installed directly.

Maybe the tutorial could introduce how to set up a GitHub app or action, which helps to improve the DevOps flow. You could still use Imgbot as an example in the beginning. What do you think?

**Pull request closed without merging**
