### PR TITLE
Tutorial proposal: Github Apps and Actions

### PR DESCRIPTION
**Pull request by johannaii**
After discussing with @gluckzhang in the comments of our old PR #377 , we decide to change the topic of our tutorial. Here is our new tutorial proposal.

### CODE REVIEW

**Comment by cesarsotovalero** [comment]
I think that this tutorial topic is quite interesting. WDYT @gluckzhang

**Comment by gluckzhang** [comment]
Hi @cesarsotovalero , @johannaii , I think this is a good topic. GitHub apps and actions are becoming popular nowadays. It gives us many new ideas about CI/CD also. I propose to merge this PR :)

**Comment by monperrus** [comment]
FYI, "the Actions API is now generally available and out of Beta" https://developer.github.com/changes/2020-03-23-ActionsGA/

**Comment by louisezetterlund** [comment]
[This](https://github.com/johannalouise/repobepo) is where we are working on our tutorial. See the README.md.

**Pull request merged**
