### PR TITLE
Presentation Proposal, week5: DevSecOps in Kubernetes

### PR DESCRIPTION
**Pull request by emetha**
# Topic: DevSecOps in Kubernetes

## Members:
- Emelie Tham (etham@kth.se)
- Philip Wester (phwe@kth.se)

## Motivation
Both my partner and I are interested in learning more about Kubernetes as well as the security aspect of DevOps, so we put the two together as the subject of our presentation. We are a bit unsure whether or not this topic is too broad/general, so any feedback is appreciated!

## Description
Draft of Presentation Structure:
1. What is DevSecOps and Why is it important?
    - Case Study
2. DevSecOps in terms of Kubernetes
    - Security Challenges of Kubernetes
    - "Billion Laughs" vulnerability
    - How to strengthen Kubernetes Security
        - Reducing Kubernetes Attack Surface
        - Utilizing Kubernetes inbuilt security features
        - Using open source tools for Kubernetes Security
3. Conclusion/Summary

## References
References, if needed:

1. https://www.portshift.io/blog/what-kubernetes-does-for-security/

2. https://cloudblogs.microsoft.com/opensource/2019/07/22/devsecops-in-kubernetes/

3. https://medium.com/@nipunadilhara/how-kubernetes-advances-devsecops-117572983b5a

4. https://thenewstack.io/kubernetes-billion-laughs-vulnerability-is-no-laughing-matter/

5. https://www.sdxcentral.com/articles/news/kubernetes-latest-flaw-a-billion-laughs-not/2019/10/

### CODE REVIEW

**Comment by gluckzhang** [comment]
Hi @emetha , based on your presentation outline, I think the topic is concrete enough. Note that the billion laughs attack itself is a particular type of DoS attack. Maybe you need some explanations about how a vulnerability affects a DevOps workflow.

**Comment by gluckzhang** [comment]
The only concern from my side is the agenda. There are some pending PRs for doing a presentation in week 4. Considering the limited time slots, do you mind if I reschedule your presentation to week 5? If the pending PRs do not fix their minor issues in time, you could still do the presentation next week if you like.

**Comment by phwes** [comment]
Yes, you can reschedule our presentation to week 5.

**Comment by gluckzhang** [comment]
@phwes perfect, thanks :)

**Comment by gluckzhang** [comment]
Moved to week 5 and the PR has been merged.

**Pull request merged**
