### PR TITLE
Revise submission of executable tutorial: Automated email notification for IP address change in SSH server.

### PR DESCRIPTION
**Pull request by enniorampello**
# Revise: Automated email notification for IP change in SSH server

### CODE REVIEW

**Comment by enniorampello** [comment]
@khaes-kth this is the revise PR.

**Comment by khesoem** [comment]
@enniorampello. You should add the changelog to your readme. It should clarify what you have changed in your tutorial.

Also, please do not change the titles ('Assignment Proposal' -> 'Revised final submission') to make the bot pass.

**Comment by enniorampello** [comment]
> @enniorampello. You should add the changelog to your readme. It should clarify what you have changed in your tutorial.
> 
> Also, please do not change the titles ('Assignment Proposal' -> 'Revised final submission') to make the bot pass.

ok but how do I add the changelog? Can I just write a list of changes manually? Also, you can see them in the commits on the repo already.

**Comment by khesoem** [comment]
Yes, you should just write a list of changes manually.

**Comment by enniorampello** [comment]
OK. Changelog:
1. updated explanation on what to fill in the fields like `<any-email-address>`.
2. updated script to send email so that it executes correctly.
3. commented all the different parts of the final script so that its purpose is more clear.

**Comment by khesoem** [comment]
> OK. Changelog:
> 
>     1. updated explanation on what to fill in the fields like `<any-email-address>`.
> 
>     2. updated script to send email so that it executes correctly.
> 
>     3. commented all the different parts of the final script so that its purpose is more clear.

add this to your readme

**Pull request merged**
