### PR TITLE
Week 7 Presentation - Compliance as Code in DevOps: Automating GDPR Compliance

### PR DESCRIPTION
**Pull request by JadedTuna**
# Assignment Proposal

## Title

Compliance as Code in DevOps: Automating GDPR Compliance

## Names and KTH ID

- Wiktor Dobrosierdow (wiktord@kth.se)

## Deadline
- Week 7

## Category
- Presentation

## Description

This presentation will explore how Compliance as Code can be used to automate some GDPR compliance checks within DevOps workflows. It will discuss the concepts of Compliance as Code and show how it can be integrated into the infrastructure to speed up development.

**Relevance**

In DevOps, speed and automation are key, but compliance with regulations like GDPR can slow things down if handled manually. Therefore, Compliance as Code is an important topic for speeding up the development process without being bogged down by manual compliance checks.

### CODE REVIEW

**Comment by algomaster99** [comment]
Hey, please look for a partner if it is not too late. I will schedule you for tomorrow. The proposal looks good.

**Comment by algomaster99** [comment]
Let me know when you find a partner and then I will put on in the schedule for tomorrow.

**Comment by JadedTuna** [comment]
@algomaster99 no partner found yet, so I think I will be presenting it alone today.

**Comment by algomaster99** [comment]
Okay no problem. Scheduled for today 1.45 in lab.

**Comment by algomaster99** [comment]
Hey! Are you here in Orange lab?

**Pull request merged**
