### PR TITLE
eopru-dericsso: presentation proposal, week 5

### PR DESCRIPTION
**Pull request by einaroddurpall**
# Assignment Proposal

## Title

Package management for Kubernetes using Helm Charts

## Names and KTH ID

  - Einar Oddur Pall Runarsson (eopru@kth.se)
  - Daniel Ericsson (dericsso@kth.se)

## Deadline

- Week 4

## Category

- Presentation

## Description

Helm provides a simpler way to manage Kubernetes projects. The way to do so is creating so-called Helm Charts,
where each Chart is a collection of one or many individual Kubernets manifests. The charts can also have child charts
and other dependencies, and so using Helm means you as a user can install the whole project using a single command
instead of installing individual components and puzzling them together. This, along with many other features of Helm,
provides a helpful way of using Kubernetes to orchestrate containers.

**Relevance**

Helm is widely known as the package manager for Kubernetes, the container orchestration framework adapted by many huge 
companies such as Google and Spotify, and highly relevant in the topic of DevOps due to its ability to simplify application 
deployment, standardize deployments and provide effective configuration management.

### CODE REVIEW

**Comment by Deee92** [comment]
Hi @einaroddurpall! Your presentation on Helm seems better suited for week 4. Wdyt?

**Comment by Deee92** [comment]
Ping @einaroddurpall 🔔

**Comment by einaroddurpall** [comment]
Hi @Deee92, sorry for the late reply!
I agree that the presentation on Helm suits week 4 but if it is okay with you then week 5 would work much better for me and Daniel due to time concerns.

**Comment by Deee92** [comment]
Hi @einaroddurpall, that's unfortunately not possible. The presentations and demos presented during the lecture are required to align with the theme of the week.

**Comment by einaroddurpall** [comment]
Okay we understand, we thought Helm might pass under infrastructure as code, we will present in week 4 then @Deee92 :)

**Comment by Deee92** [comment]
Thanks @einaroddurpall. Can you update your README and PR description accordingly?

**Comment by einaroddurpall** [comment]
I have now updated the README and PR description, and moved the file to the correct folder, do you know why the pipeline fails @Deee92?

**Comment by Deee92** [comment]
@einaroddurpall, please fetch upstream. That might solve it.

**Comment by einaroddurpall** [comment]
It worked, thanks @Deee92 :)

**Pull request merged**
