### PR TITLE
Essay Submission: Containers: Is it worth banishing the Daemons and clearing the Roots

### PR DESCRIPTION
**Pull request by Volminger**

### CODE REVIEW

**Comment by gluckzhang** [comment]
Hi @Volminger , feedback-planning is provided for finished tasks. Have you finished the essay already? Before the deadline, you are still free to update the essay according to the feedback. But we don't give feedback on WIP versions.

**Comment by Callet91** [comment]
Hi @gluckzhang. The essay is almost complete and we are finishing up the essay today so it will be finished until the feedback date on Monday. If you want a PDF instead of a link we can upload this by Monday?

**Comment by gluckzhang** [comment]
Hi @Callet91 , both a PDF and a line are fine since you will finish the essay :)
Just ping me when you finish the work. I'll then merge this PR. Thanks.

**Comment by Volminger** [comment]
Hi again @gluckzhang they essay is now finished. We plan to publish they essay on Medium, we just want to receive your feedback before we publish it :)

Link to essay: https://docs.google.com/document/d/1vC35eVQpjxDziZEA4dsSM52kR4jhoZIIkLpDAeLvLyk/edit?usp=sharing

**Comment by gluckzhang** [comment]
@Volminger perfect. Your request has been registered. @bbaudry will give you feedback on the essay tomorrow :)

**Comment by bbaudry** [comment]
Feedback for #676

Thank you for this essay on a very technical aspect of containers. It is highly relevant to DevOps. The essay is well-structured and weel motivated. I have two main comments
- the main motivation to go daemonless is not precisely enunciated. It seems that security and safety are two essential characteristics of containers that can vary with a rootless solution. However, the main security features of Docker and Podman are not explicitly discussed. In particular, the impact of cgroup-v2 on security is not discussed. I suggest that you elaborate on the benefits of cgroup-v2 on security and safety and then discuss more precisely how this impacts the users of daemon-based vs. daemonless containers.
- there are a number of illustrations that do not support the technical discussion. I suggest to remove them, to keep a deep technical focus for your essay. Meanwhile, I encourage you to add some diagrams that support the discussion and comparison between the two versions of cgroup and between Docker and Podman.

See the annotated pdf sent by email for more detailed comments.

**Pull request merged**
