### PR TITLE
Presentation Kanban vs Scrum

### PR DESCRIPTION
**Pull request by evkade**

### CODE REVIEW

**Comment by Deee92** [comment]
Hi @evkade, looking forward to your presentation! A discussion about concrete examples of organisations where these methodologies are applied, and how they are useful, would be very cool.

**Comment by evkade** [comment]
Hi @Deee92 ! We were thinking about making the presentation in week 5 instead of week 4. Is it ok to change to do that? Then I will just make a new pull request changing the location of the folder with our readme.

**Comment by Deee92** [comment]
Hey @evkade, since week 5 is pretty open right now, go ahead!

**Comment by evkade** [comment]
Thank you! Making the new pull request now

**Pull request merged**
