### PR TITLE
Added screencast

### PR DESCRIPTION
**Pull request by Gabbi68**

### CODE REVIEW

**Comment by Volminger** [comment]
Hey,
I will give feedback to you :)

**Comment by xmas92** [comment]
I can give feedback.

**Comment by klaraesr** [comment]
I'll give feedback!

**Comment by eywoon** [comment]
I can give feedback

**Comment by christinasunnegardh** [comment]
I'd like to give feedback!

**Comment by Volminger** [comment]
You have chosen an interesting part of DevOps with Terraform. Here is my feedback on your demo :blush:

**Visual**: Enlarge the code in the editor in the beginning. It is possible to see what the text are, but it would be easier to read if it was a bit larger. You should also consider making the terminal text a big bigger.

**Timing**: The video is to long at 6:44min. It should be a maximum of 5min. This is mandatory requirement.. It does not add much value when clicking around and opening up different applications and web pages. This would give value if this was a tutorial, but since it is a demo it would be cleaner if you just cut to the different application windows. You should also consider speeding up the video when you are typing in things and speed up when Terraform is building or destroying.

**Technical**: To improve the technical part of the demo: Use Terraform outputs to display some information about what you just created. Consider using Terraform variables to input some information to Terraform and Azure. I also think that it is good practice to put your Terraform provider in a separate .tf file called provider.tf

**Motivation**: It is never stated why Terraform and your demo matters to DevOps. This needs to be clearly stated.

**Take-home message**: Add a concise take-home message at the end of your demo. This is mandatory requirement.

**GitHub repo**: I see in the YouTube video that you have a GitHub repo, but I cannot find it in the README. Consider adding a link to it so one can browse through your Terraform code.

**Subtitles**: I also could not find any subtitles on the YouTube video. This is mandatory requirement.

**Comment by christinasunnegardh** [comment]
Hi! Thank you for the demo, here comes my feedback!

- I think maybe you could get in trouble for that the demo is too long 😬 Maybe you can skip to explain some parts and then link to it externally instead to save some time? Also, in some parts of the screencast, not much is happening (for example 0:55-1:05). These could be cut out to save some time...
- It's a bit hard to read the text at the same time as looking at what you are doing. Consider maybe adding a voice over?
- I think it's great that you show the code for the infrastructure, but it's pretty small (too small to read without having full screen etc) and not explained :(
- The ending is a bit abrupt..

Overall, I really liked that the demo was so technical but I feel like many optimizations could be made to not make the viewer sit and "wait" for something to happen. Also, a voice over would be great.

**Comment by eywoon** [comment]
Feedback: Azure storage using Terraform

Positives:
- Really cool choice of topic and relevant
- Very technical

Improvements:
- Add some motivation in the beginning for why it matters to DevOps, along with a take-home message. Would help with context for those unfamiliar with the stack.
- Resolution is hard to read
- Maybe try to make it shorter, it exceeds the maximum limit

I’m sure you can shorten the demo by maybe filming it in a few parts. You have everything there, just needs some fine-tuning. I know making the videos is not easy :)

**Comment by klaraesr** [comment]
Thank you for your demo and for an interesting topic. Here are some points: 

- The demo is very straight at it, it would be good with some motivation and explanation of what will happen/what Terraform is
- The subtitles/text is a bit hard to read (words are cut sometimes), and since no one is speaking I think you could benefit from explaining more what it is you do. Right now there are only a couple words about what happens.
- You could clarify where you click and why. 
- At for example 3:45 there is a lot of just waiting, this could be sped up or removed to shorten the screencast (which is too long right now)
- I didn’t find an Easter egg, was there one?
- Add the link to the repo in the description
- Overall I would say to add more explanations, and a motivation in the beginning and take away at the end

**Comment by xmas92** [comment]
# Mandatory Criteria Check

- [ ] The screencast is 3-5 minutes
    * Unfortunately it is too long [**6:44**].  Fortunately there are many places where it is possible and even make scenes to cut it down.
    * Try and cutout the typos and mistakes ( like `az loign`)
    * Speedup dead-time. There are a lot of times where we are just waiting for some command to execute or the viewer is just waiting for the presenter to finish checking something. These can be speed up to be only as long as it takes to comfortably read the text caption.  
    * Overall try to cut / speedup any segment which has not caption or any visual user input from the presenter.
- [X] The screencast contains subtitles which are clear and in proper English
    * Sometimes there are a lot of things happening on screen (navigating around in the web interface, clicking buttons) without any accompanying explanation. These parts can be hard to understand without captions, either try to cut out / speedup unnecessary segments or add some more explanations. 
    * Sometimes there are weird word-breaks which makes it harder to read.
- [ ] The screencast contains a good and concise take-home message at the end
    * I think this is suppose to be it, the last two text prompts.
      >BY HAVING IT AS CODE WE CAN EASILY STORE IT IN GIT FOR VCS
      >THEN INFRASTRUCTURE CAN BE HANDLED LIKE ANY DEVELOPMENT
    * Maybe try to move this all into one conclusion sequence. Making the message self-contained also makes it more powerful. Right now the `IT` makes only understandable in the context of the screencast.

* The demonstration screencast is clearly motivated (why it matters for Devops?) 
     * While `Deploying azure storage using Terraform` definitely is a DevOps topic maybe some more time can be spent in the beginning to make this clear, especially to someone who knows about DevOps but not necessarily about `Azure Storage` or `Terraform`.  Pinpoint where these tools and services live in the overall DevOps ecosystem. 
* The demonstration screencast is difficult to do
    * The presenter makes everything look easy, but it is hard to gauge how difficult the demo would be to setup. Adding some more explanations of what is going on will probably help with the viewers understanding of the intricacies and difficulties involved. 
* The demonstration screencast is original 
    * There are a lot of hits when searching on Youtube and Google for this topic. Maybe again being a bit more explicit in explaining what is going on and adding some unique flair to it.
   * Other than that the screencast is a nice example of just how to deploy to Azure storage using Terraform.
* The demonstration screencast is sublime (eg visually appealing) 
    * I think cutting down the content will help with this. Also both code, website and terminal text size can be increased to make things more readable. When specific user actions are relevant you can try to bring attention to these by highlighting where the action takes place (or darkening everything else). 
* The demonstration screencast contains an easter egg
    * Not sure.
* An accompanying Github repository has been made (optional)
    *  Cannot find it. Making available may make it easier for some to follow along with the code.

**Pull request merged**
