### PR TITLE
[Final submission] Essay: SaaS, PaaS, IaaS? A taxonomy of cloud service models

### PR DESCRIPTION
**Pull request by andreaskth**
# Essay submission: SaaS, PaaS, IaaS? A taxonomy of cloud service models

## Members:

Andreas Kärrby (karrby@kth.se)
Github: [andreaskth](https://github.com/andreaskth)

Eleonora Borzi (borzi@kth.se)
Github: [EleonoraBorzis](https://github.com/EleonoraBorzis)

## Proposal/motivation

Original proposal PR is #1018

## Submission

The essay can be found under ‘contributions/essay/borzi-karrby/taxonomy-of-cloud-service-models.pdf’

Looking forward to feedback from @felix-seifert (#1056)!

## Grading criteria we are aiming for

|                                             | Yes | No | Remarkable |
|-------------------------------------------- | ----|----|-------------|
| format: The essay is in PDF | 🦋 Mandatory | - | - |
| title: The essay has a good title | Yes | No | Remarkable 🦋 |
| well-structured: The essay is well structured, the ideas are well presented | Yes 🦋 | No | Remarkable |
| introduction: The essay contains a good introduction | Yes 🦋 | No | Remarkable |
| conclusion: The essay contains a good conclusion | Yes 🦋 | No | Remarkable |
| self-contained: The essay is self-contained, one can understand it without reading something else (expected knowledge of the reader: a master student in computer science) | Yes | No | Remarkable 🦋 |
| innovative: The essay contains innovative ideas or material | Yes | No | Remarkable |
| figures: The essay contains good figures or listings | Yes | No | Remarkable |
| sound: The essay is sound, factual, and accurate | Yes 🦋 | No | Remarkable |
| references: The essay contains references, appropriate  in number and quality (10 good refs is a minimum) | Yes 🦋 | No | Remarkable |
| elegant: The essay presentation is elegant / visually appealing (eg LaTeX, InDesign) | Yes | No | Remarkable 🦋 |
| relevant: The essay addresses a topic that is relevant for DevOps | Yes 🦋 | No | Remarkable |

### CODE REVIEW

**Comment by felix-seifert** [comment]
And here comes the feedback for this essay.

It is helpful for many people that you shed some light on the area of cloud service terminology. Understanding the three cloud service models of infrastructure, platform and software as a service helps a lot to understand the offering of cloud service providers. The main aim of your essay seems to be to explain these three terms.  The National Institute of Standards and Technology (NIST) already provides a very condensed description of these terms for a more technical audience in _The NIST Definition of Cloud Computing: Recommendations of the National Institute of Standards and Technology._ You can consider whether you want to make reference to such a publication and elaborate on it for a technical audience or show some originality and try to bring these technical descriptions closer to a non-technical audience, i.e. you should define your target reader and write for them.

You should define the terms ‘cloud’, ‘cloud computing’ and ‘cloud service’. It might be useful to explain that computing in the cloud is just computing on someone else’s computer, which helps to show that the buzzword cloud computing is easily understandable. Such a definition of terms would fit perfectly under your subsection of _What is cloud?_.

To provide a better structure of your essay, you should divide the section _Background_ into two subsections: _History_ and _What is cloud?_.

I enjoy reading the history part in your _Background_ section. Before, I only knew bits and pieces of how modern cloud computing services occurred. Now, with the historical timeline, I better understand the initial ideas of why cloud computing was introduced and which issues it should help to tackle. However, some parts of this history section are colloquial and can also be more exact.

To avoid sounding too colloquial, you should adopt a more formal tone and decide on how you want to use the term ‘DevOps’. Consider defining the term in a single sentence such that the readers know what you are talking about and then stick to this definition. Also, describe how ‘DevOps’ relates to your cloud service models to justify the usage of this term.

My recommendation for being more exact is to sketch a timeline with the events and dates to check whether you have all the details correct. Afterwards, you rewrite the section in a chronological order with these details . Telling the history sequentially without any backwards time jumps helps with the readability. To make your timeline even clearer, you can create a figure to present the timeline graphically as well to the readers.

Even though the five essential characteristics of cloud computing are already defined by NIST, your explanations are easier to understand and less technical. Nevertheless, your translation into a less technical language can be improved to ensure accuracy, while keeping in mind the target audience
* _On-demand_ is misconstrued as constant availability. If a user does not request a functionality all the time, it will not be necessary that the service is available all the time. To fix your explanation, you can just say that the service should always be available when it is requested by the user.
* Under _Broad Network Access_, elaborate in a few words what a basic network access is. Consider to mention that it should be accessible from a consumer laptop or similar.
* For _Resource Pooling_, you mention a way of solving the pooling. You should try to be consistent and present a way of fulfilling the characteristic for either all characteristics or no characteristic.
* Your explanation of _Rapid Elasticity_ is nice as it mentions that the scaling should happen automatically. You can consider making it clearer that the scaling does not happen only automatically but also rapidly.
* The explanation of _Measure Service_ seems to summarise exactly what is needed. However, the formulation of the sentence seems to miss the proper description. The first part of the sentence that the service has to be quantifiable is appropriate but the second part should then mention that this results in showing the customer transparently what he/she is paying for.

Next, you mention which three service models you want to explain in the essay. Consider to add on the reason for your choice of these three models. For example, why do you not add any explanation of the service model Function as a Service or Container as a Service?

The structure of your explanation of Infrastructure as a Service (IaaS) is clear and succinct  and provides a good overview: what is IaaS, what are the advantages and disadvantages, when should it be used and who provides it. To ensure consistency, you can use this structure for the other service models. The vendor examples show that these service models are actually used. Mentioning other examples besides the three big vendors (Amazon, Google, Microsoft) would be good for showing a deeper understanding of the market. 

You mention the responsibilities of the provider and what the customer can do. Consider to make it slightly clearer and also mention what is included in the service that the customer pays for. Even though the hardware for IaaS runs only at the provider’s site, your description suggests that the provider can also install and maintain hardware at the customer’s site, which is not true. 

Infrastructure as Code does not seem to  belong to this section. Consider to make a subsection for it.

Your explanation of Platform as a Service (PaaS) starts slightly strange because you move on to application analytics quite quickly without explaining the exact service that the customer pays for. Try to have a similar structure as the explanation of IaaS and stick to this structure for the different service models.

At the beginning of the section about Software as a Service, it is possible to assume that the customers are interested to acquire the software and therefore, purchase a software copy and run it locally. Again, mention clearly what the customer pays for and what the service provides. Also, stick to your the aforementioned structure which was used for IaaS.

Even though IaaS can be more expensive than PaaS, this is definitely not true for all cases. Consider the different price drivers and you might then realise that a comparison would not be possible without the consideration of more details. When having a look at the prices, you should also think of the lock-in effect created by different providers.

Essays should generally be more formal and contractions with an apostrophe to leave out certain letters do not sit well in essays as they are considered to be informal. Examples are “it’s”, “I’m” and “we’re”. They should be replaced with “it is”, “I am” and “we are”.

When a term is abbreviated with an acronym which is not in the relevant language dictionary, its first occurrence gives the original term fully spelt out, followed by the acronym in parentheses to give the reader an explanation of what the acronym stands for. All subsequent occurrences of this term should then be replaced with the associated acronym to ensure consistency and avoid confusion. You should also avoid introducing an acronym without using it later on. Please check your terms and their acronyms like _Amazon Web Services (AWS)_ in sections 1 and 2 and _National Institute of Standards and Technologies (NIST)_.

Your references are helpful in explaining the cloud taxonomy. However, they are mainly blog posts and other internet pages; especially those of cloud service providers can be biased towards their own services. Even though many of the mentioned websites seem to be trustworthy sources and we were not specifically asked to produce a scientific essay, referencing some research papers increases the credibility and authenticity of your essay and diversifies your sources. I can recommend you the document with the previously mentioned and widely trusted definitions of cloud computing by NIST (it is not a research paper):

```
Mell, P., & Grance, T. (2011). The NIST Definition of Cloud Computing: Recommendations of the National Institute of Standards and Technology. Computer Security Division, Information Technology Laboratory, National Institute of Standards and Technology.
```

If you need to provide more content after condensing certain parts, you can deliberate on which information might be helpful for your target readers. Depending on your target group, it might be helpful to write about the advantages and disadvantages of each service model. Even though Grossman’s paper, _The Case for Cloud Computing_, is a little bit older, it gives you some simple ideas about the areas you have to consider. After identifying some challenges in these areas, you can have a look on how these challenges are tackled today.

```
R. L. Grossman (2009). The Case for Cloud Computing, IT Professional, 11(2), 23-27
```

My summarising recommendations would be to take the NIST definitions and try to formulate these definitions in an understandable way for the layperson. Try to write formal while addressing your target group and ensure consistency. Similar to defining and using variables in your code, you should always remember to define the technical terms you use.

I think that you can improve this essay and hope that it finds many readers who then get a better idea of the cloud terminology. This essay can therefore contribute to your strength of communicating technical content to non-technical customers.

Please always remember that feedback is like a serving tray: You can implement the parts that you find useful and leave the other parts on the tray.

**Comment by andreaskth** [comment]
Thanks @felix-seifert for quick and detailed feedback! Much appreciated.

We have now updated our essay based on many of the suggestions. Things we changed:
* Replaced contractions such as "it's" to make the text more formal
* Reworded some of the “NIST points” in 2.1 to make them consistent and clear
* Added informal definitions of ‘cloud’ and ‘cloud services’ under “What is cloud?”
* Clarified what customers are paying for in SaaS (and, by the same token, what providers are responsible for providing)
* In general made the three *aaS sections a bit more similar/cohesive
* Split the chapter "Background" into two sub-chapters (there was only one sub-chapter before)
* Changed the tone in the chapter “Background” to be more formal 
* Added a picture to show the timeline of cloud services
* Explained better how DevOps is related to cloud services
* Added reference to the NIST paper 

The essay is now ready for final assessment by “the course”/TAs. Was told to ping TAs after feedback-revision so am pinging @Deee92 since you were the one that merged the proposal :)

/Andreas and Eleonora

**Comment by felix-seifert** [comment]
Hi @EleonoraBorzis and @andreaskth, 

I know that the feedback was a little bit longer and difficult to work through. However, you improved your essay tremendously and I am sure that these changes paved the way for receiving a better grade.

Cheers,
Felix

**Comment by SophieHYe** [comment]
Thanks for the final essay submission. I am merging your PR.

**Pull request merged**
