### PR TITLE
Open-Source proposal

### PR DESCRIPTION
**Pull request by Spycsh**
# open-source: Bug fixing for the open-source project HTMLTestRunner

## Members

Sihan Chen: Email: sihanc@kth.se Github: [Spycsh](https://github.com/Spycsh)

Yuehao Sui: Email:  yuehao@kth.se Github: [amaothree](https://github.com/amaothree)

## Proposal

The open source project [HTMLTestRunner](https://github.com/SeldomQA/HTMLTestRunner) is used widely as a way to automatically generate elegant HTML testing report for Python unittest and send to mailboxes. It is used in several open-source projects such as [Seldom](https://pypi.org/project/seldom/).

Our contribution is aimed to address the following bugs:
1. expand the email support on email sending service with the functions in python smtplib (let it support Gmail, QQ, and 126, 163 mail etc.)
2. fix the bugs when scaling down web browser, the testing chart will overlap with the testing results by using responsive design
3. fix some typos and wrong references

### CODE REVIEW

**Comment by khesoem** [comment]
Hi @Spycsh 

Can you add the issue_ids related to the fixes you want to make?

**Comment by Spycsh** [comment]
Hi @khaes-kth 
No there are no issue ids related. I download the project and find the bugs myself.

**Comment by khesoem** [comment]
To make sure that your contribution will be accepted by the maintainers, it is much better if you create issues and get a positive reaction from maintainers before you start working on the them.

**Comment by Spycsh** [comment]
@khaes-kth I have already make the pull requests and two of them are merged about two or three days ago.

**Comment by Spycsh** [comment]
@khaes-kth Does this opern-source contribution must need an issue before contributing to it? Actually for this open-source project have a chat group to discuss the problems we met. I mean, this open-source project, HTMLTestRunner, is only a small component in a relatively large unit testing framework. Sometimes just pointing out the error in the chat group and then creating PR to modify it is more convenient. I can open the issues now about the above bugs in the proposal but I have already fixed them and the PR are merged about the day before yesterday. What do you think, do I need to create the issues? There is another small bug I found but not merged and not issued yet. So maybe I can create the issue now and create a PR to fix it. However I must say I do not know whether it derseves a "hard bug". It is simple but necessary. The previous bugs I find and fix in the proposal are relatively hard bugs (e.g. in the proposal, the first and the second one). Those are also necessary bug fixing.

**Comment by Spycsh** [comment]
This is one issue id of the above PRs
https://github.com/SeldomQA/HTMLTestRunner/issues/11

**Comment by khesoem** [comment]
Hi @Spycsh,

I noticed that your chosen repo does not have more than 100 stars, which means it does not meet [the requirements](https://github.com/KTH/devops-course/blob/2021/grading-criteria.md#open-source-contributions).

Unfortunately, we cannot accept this contribution.

**Pull request closed without merging**
