### PR TITLE
Demo Proposal: Demonstration of Deploying Multiple API Servers with Docker and AWS Lambda

### PR DESCRIPTION
**Pull request by EDChui**
# Assignment Proposal

## Title

Demonstration of Deploying Multiple API Servers with Docker and AWS Lambda

## Names and KTH ID

- Man Yin Edward CHUI (myechui@kth.se)

## Deadline

Task 2 (April 19)

## Category

Week 4: Containers & Serverless (April 12)

## Description

This demonstration would like to show: 

- How to dockerize multiple backend API servers (possibly written in different languages) under the same project at the same time.
- How to then deploy the docker to AWS lambda.

AWS Lambda is a serverless, event-driven service.
When a request is made to Lambda, it will invoke a function call to a function which correspond to an API call, then make the request accordingly.
In this demo, I would like to show how to deploy multiple backend API servers and demonstrate how they can possibly interact with each other (may be like a webhook) in the container.

### CODE REVIEW

**Comment by EDChui** [comment]
Hello, I want to know if it is possible to arrange my demo on 12 Apr? As I might not able to present it the week after (19 Apr).

**Comment by EDChui** [comment]
Made further description in `README.md`. Thank you.
@javierron

**Comment by javierron** [comment]
Thanks for the update. Please update the description in the PR text as well.

Just to make sure we are on the same page, you will present:
 1. How to create containers which contain functions that execute in AWS Lambda.
 2. How to upload these containers to AWS lambda.
 3. How to call these functions from clients.
 4. How the containers may interact with each other

**Comment by EDChui** [comment]
I have updated the PR text and I will present the item as you have mentioned.

**Comment by EDChui** [comment]
khgfjhjvy tfyby jkhvgfctdxerszmmmm

**Pull request merged**
