### PR TITLE
Initial demo proposal

### PR DESCRIPTION
**Pull request by PaulLowenstrom**
# Demo Proposal
## Members

Paul Löwenström (paulher@kth.se)
Oliver Lehtihet (oliverle@kth.se)

## Topic
Demo of deploying a CI/CD pipeline with gitlabs using docker, kubernetes and azure.

### CODE REVIEW

**Comment by SophieHYe** [comment]
Hello,
Your demo topic is indeed very relevant but a bit general.
Could you also please describe a bit more motivation for using azure and the original/difficulty of your demo?  Thanks.

**Comment by PaulLowenstrom** [comment]
We want to create a website for weather where we can use easily update, add and change information with the help of CD. We chose Azure as its one of the more popular programs when doing CD pipelines.

**Comment by lehtihet** [comment]
@SophieHYe

**Comment by lehtihet** [comment]
We also want to use azure to have 100% uptime. And it is easily compatible with kubernetes

**Comment by SophieHYe** [comment]
Hi,
It's great you have some concrete ideas about your demo. 
As quite many demos are showing deploying a CI/CD pipeline, our concern is about the novelty of your work.  Maybe you can explore some specific point in-depth in your demo.

**Comment by lehtihet** [comment]
We will focus our demo more on using azure to build on linux/windows/mac and make sure our program works on all of them.

**Comment by lehtihet** [comment]
@SophieHYe I have updated the readme

**Comment by Paul-Philip** [comment]
I would like to give feedback on this one :)

**Pull request merged**
