### PR TITLE
hhob: Feedback proposal

### PR DESCRIPTION
**Pull request by haraldhob**
# Assignment Proposal

## Title

Feedback on [Shifting Left in DevOps: Improving the Quality and Speed of Software Development](https://github.com/KTH/devops-course/pull/2204)

## Names and KTH ID

  - Harald Hobbelhagen (hhob@kth.se)

## Deadline

- Task 2

## Category

- Feedback

## Description

I would like to submit feedback for [this essay](https://github.com/KTH/devops-course/pull/2204)

### CODE REVIEW

**Comment by haraldhob** [comment]
Hey @khaes-kth, I just realised that the essay I am referring to has already been submitted thee days before I proposed the feedback. Should I still write the feedback as the essay and feedback was merged two days ago, so, from the grading criteria I would have time until tomorrow to finalise the feedback. Sorry for the inconvenience. BR

**Comment by khesoem** [comment]
@Deee92 @javierron Can you help me with this? Can the students submit the feedback more than 48 hours after the essay submission but before the chosen deadline? Also, can someone submit a feedback for a deadline different from the deadline of the essay?

**Comment by haraldhob** [comment]
Just to clarify: When I proposed the feedback the essay was apparently already submitted 3 days before. I can change my proposal, too, if that makes it easier.

**Comment by khesoem** [comment]
Hi @haraldhob 

I don't see any problem for submitting your feedback now. You will not get the timeliness score, however you can still pass if you get the score for other criteria. If you are present at the lecture, you can ask this in person as well. So, go ahead....

**Pull request merged**
