### PR TITLE
Completed Essay: Exploration of AWS services used throughout CI/CD

### PR DESCRIPTION
**Pull request by sujon2100**
We have completed the essay.  Here is the link PR: https://github.com/Nick-Steele/devops-course/tree/master/contributions/essay/nsteele-mhud

And here we have asked for the feedback:
https://github.com/KTH/devops-course/pull/644

### CODE REVIEW

**Comment by SophieHYe** [comment]
Hi,
Thanks for updating the essay. For sure, we will merge it. 
Please note that you commit also contain a contribution proposal for the COVID-19, which is not mature enough to be accepted.  How about remove them from this PR and create a new one for COVID-19? Thanks!

**Comment by sujon2100** [comment]
> Hi,
> Thanks for updating the essay. For sure, we will merge it.
> Please note that you commit also contain a contribution proposal for the COVID-19, which is not mature enough to be accepted. How about remove them from this PR and create a new one for COVID-19? Thanks!

Here is the latest situation of Covid19 PR taken from the message history https://github.com/KTH/devops-course/pull/633:
"
@gluckzhang commented 8 hours ago

@sujon2100 @Nick-Steele I'm fine with the idea. Please correct the folder name in order to get the PR merged: https://github.com/KTH/devops-course/tree/master/contributions/covid19#how-to-register-your-topic

@sujon2100 commented 5 minutes ago
Thank you @gluckzhang . I have changed the folder name, here you can see: https://github.com/KTH/devops-course/pull/633/files

@sujon2100 commented 4 minutes ago
Now could you register for the feedback? Here is the feedback pull request: #601
Thanks!
"
So, still do I need to create new PR for COVID19?

**Comment by gluckzhang** [comment]
@sujon2100 , a PR only contains relevant files to the subject. In another PR you propose to merge files about covid19, and that PR does not contain other files which is correct. Vice versa, in this PR you are going to submit the completed essay, then it should only contain the files about the updated essay. Besides, in the covid19 PR (which has been merged), the name of the task folder is `mhud-nsteele`, here it becomes `nsteele-mhud` which contains an very early version of the proposal. It should not be merged into the course repo anyway.

What we are going to check: in the list of changed files, there should only be **2** files:

- contributions/essay/nsteele-mhud/DD2482Essay.pdf
- contributions/essay/nsteele-mhud/README.md

What you could do to fix this:

- merge `KTH:master` to `Nick-Steele:master`
- delete the incorrect folder `nsteele-mhud`
- only update the files in `contributions/essay/nsteele-mhud`

What is a better practice: using different branches for PRs instead of using the master branch

**Comment by sujon2100** [comment]
> @sujon2100 , a PR only contains relevant files to the subject. In another PR you propose to merge files about covid19, and that PR does not contain other files which is correct. Vice versa, in this PR you are going to submit the completed essay, then it should only contain the files about the updated essay. Besides, in the covid19 PR (which has been merged), the name of the task folder is `mhud-nsteele`, here it becomes `nsteele-mhud` which contains an very early version of the proposal. It should not be merged into the course repo anyway.
> 
> What we are going to check: in the list of changed files, there should only be **2** files:
> 
> * contributions/essay/nsteele-mhud/DD2482Essay.pdf
> * contributions/essay/nsteele-mhud/README.md
> 
> What you could do to fix this:
> 
> * merge `KTH:master` to `Nick-Steele:master`
> * delete the incorrect folder `nsteele-mhud`
> * only update the files in `contributions/essay/nsteele-mhud`
> 
> What is a better practice: using different branches for PRs instead of using the master branch

Hi @gluckzhang ,

Thanks for your comments! We will keep in mind in the future. Just a question, do we need to recreate pull requests for the feedback for both Essay and COVID19, or the previously created pull requests are ok?

**Comment by gluckzhang** [comment]
@sujon2100 , the one for covid19 task has been merged, of course you don't need to create a new PR for that. But this one needs to be fixed: either you follow the tips to push updates to the current PR, or recreate one with only 2 files to be merged (`contributions/essay/nsteele-mhud/DD2482Essay.pdf` and `contributions/essay/nsteele-mhud/README.md`).

**Comment by sujon2100** [comment]
> Regarding feedback requests, the previous ones are OK, I will manually adjust the content.

Great! Thank you once again!

**Comment by gluckzhang** [comment]
> What we are going to check: in the list of changed files, there should only be **2** files:
> 
> * contributions/essay/nsteele-mhud/DD2482Essay.pdf
> * contributions/essay/nsteele-mhud/README.md

Any updates regarding this? @sujon2100 @Nick-Steele

**Comment by sujon2100** [comment]
Hi Long,

We have added one pdf that is the completed essay. And other one is readme
file. Can you explain what you want us to do? I'm not clear.

Best regards
Helal

**Comment by gluckzhang** [comment]
@sujon2100 , this PR should **only** contain **2** files. In the list of changed files, there are still 2 irrelevant files there, which should be removed. Especially `contributions/covid19/nsteele-mhud/README.md`.

**Comment by Nick-Steele** [comment]
@gluckzhang: Can you access it at the following link.  I cannot see any 2 irrelevant files. The 2 relevant files are available here. 
 https://github.com/Nick-Steele/devops-course/tree/master/contributions/essay/nsteele-mhud

ss

**Comment by Nick-Steele** [comment]
> @sujon2100 , this PR should **only** contain **2** files. In the list of changed files, there are still 2 irrelevant files there, which should be removed. Especially `contributions/covid19/nsteele-mhud/README.md`.

I cannot see any PR on this directory contributions/covid19/nsteele-mhud/README.md`.

**Comment by Nick-Steele** [comment]
Finished is here: devops-course/contributions/covid19/nsteele-mhud/README.md

**Comment by Nick-Steele** [comment]
I think it is resolved, I am unsure however, this is the message I am getting. Do I need to do anything else ? 

problem

**Comment by gluckzhang** [comment]
Well, in your screenshot there are still 4 files changed. But never mind, we will fix it manually. This PR has taken too much time.

**Pull request merged**
