### PR TITLE
Correct name of proposal folder

### PR DESCRIPTION
**Pull request by Neproxx**
Unfortunately, I forgot to rename the folder of my proposal README after having added someone to collaborate with. This pr changes the folder name from "marcelj" to "marcelj-khalidey". Please also create a group marcelj-khalidey in canvas after accepting the pr. The current group "marcelj" can however be used for my essay proposal that I will work on alone. Thanks.

### CODE REVIEW

**Comment by khesoem** [comment]
@vladomitrovic This PR is changing the folder name to add a student whose name was missing. Can we merge it?

**Comment by vladomit** [comment]
@khaes-kth I merged the PR

The best is to first delete the previous group or rename it manually on canvas before merging.

Because the for some reason [the changes](https://github.com/KTH/devops-course/pull/1728/files) of this PR are adding a new directory and not renaming it, even if this was the case in [the forked repo](https://github.com/Neproxx/devops-course/commit/a7fefb068e9a0cb740f9ea6b00ea3392a137d271)

Something to investigate....

**Comment by khesoem** [comment]
Thanks @vladomitrovic 

Do we have to take any other actions with respect to this specific PR and group?

**Comment by vladomit** [comment]
> Do we have to take any other actions with respect to this specific PR and group?

No, everything is sync now. 

I just opened an issue on kth/github-canvas-integration in order to have it somewhere for future improvements of the bot.

**Pull request merged**
