### PR TITLE
Executable tutorial proposal

### PR DESCRIPTION
**Pull request by phamelink**
# Assignment Proposal

## Title

Secure Linux webserver 

## Names and KTH ID
  - Philip Hamelink (ppjha@kth.se)
## Deadline

Task 3 May 3, 17h Stockholm time

## Category

Executable tutorial

## Description

Using Katacoda, I want to create a step-by-step guide on how to deploy a secure webserver on linux.
Starting from a default project that includes an API server and a React website, I want to show how you can secure the webserver 
by enabling basic ssh access as a non-root user, set up a firewall to only allow incoming https requests. I then want to show how you can
set up a reverse proxy with nginx to serve either API requests or the static website's files. 

I plan on doing a step by step demonstration, explaining every notion and showing the results to the user (for example when restricting ssh access
to only non-root users, show that access is denied by letting the user try anyway).

### CODE REVIEW

**Comment by luuuk** [comment]
Hey @phamelink - @fsegatz and I would love to give feedback on your tutorial if you're ok with that. LMK what you think, if you're ok with the plan I'll open a new PR!

**Comment by fsegatz** [comment]
Philip accepted our feedback offer. Please check and merge our PR (https://github.com/KTH/devops-course/pull/1823), when his proposal gets accepted.

**Comment by khesoem** [comment]
@phamelink , Can you please elaborate on the relation between your chosen topic and Devops?

**Comment by phamelink** [comment]
Hi @khaes-kth
I think my topic is especially relevant in DevSecOps, but also concerns deployment. 
When you deploy software, you often do this using a server. However, if this software is available through the network, then the whole server becomes exposed to the world. Enabling a firewall and setting up secure remote access are essential to making your server safer and a vital skill in DevOps security. Also, since I plan on deploying an API and a website, this step is the basis in setting up continuous deployment later on.

**Comment by khesoem** [comment]
Fair enough and good luck with the tutorial :) !

**Pull request merged**
