### PR TITLE
Demo complete

### PR DESCRIPTION
**Pull request by sashikanthr**
## Finished Demo - Test Amplification using DSpot

Demo is complete. The video can be found here: https://youtu.be/xGGGY6-xwJo

And, the github project is here: https://github.com/sashikanthr/DSpot-Demo

### CODE REVIEW

**Comment by Volminger** [comment]
Hey,
I will give feedback to you :)

**Comment by Marcus9512** [comment]
I will give feedback

**Comment by georgewbar** [comment]
I would like to give feedback

**Comment by javierron** [comment]
I will give feedback :)

**Comment by SoFoDa** [comment]
I will also give feedback

**Comment by rbratfors** [comment]
I would like to give feedback to this demo.

**Comment by rbratfors** [comment]
I thought it was a good and informative demo with an interesting topic. It was easy to follow and I'm sure that I could replicate it by just following the video and using the provided repo. The music was at a good level where it didn't disrupt the narration but still added some ambiance.

I think the subtitles could be improved by making each segment shorter, right now they sometimes take up almost 1/4 of the screen. This is easily fixed by just cutting it up into shorter bits so that it shows at most 2 lines at a time.

**Comment by georgewbar** [comment]
## Feedback overview
The demo is sublime and have very high quality. It is clearly motivated at the beginning why Test Amplification is relevant to DevOps. It is informative and instructive that you clarify the concept at the beginning of the demo. With a quick search on Youtube, I could not find a lot of videos that go through how to use Dspot for Test Amplification. The Github repo associated with the repo has good instructions on how to run the code. The demo is also in the 3-5 minutes range, which fulfills the requirement for time constraint. There are good subtitles (see below for feedback on an issue that could be fixed).

## Feedback using template
Using the template for `pass` criteria, in my opinion, the following criteria are fulfilled:
* The demonstration screencast is clearly motivated. Yes.
* The demonstration screencast is original. Yes.
* The demonstration screencast is sublime (eg visually appealing). Remarkable with some modifications (see comments below).
* An accompanying Github repository has been made (optional). Yes.

## Some issues that could be fixed
* Subtitles are a little bit long. You could separate the subtitles into- smaller lines at any one time. However, the script is very good.
* There is an implicit take-home message, which is stated as an introduction to the demo. However, a take-home message slide could be added at the end to summarize the key points. **The screencast contains a good and concise take-home message at the end** is a mandatory criterion.
* You could also add the credits for the music.

**Comment by Marcus9512** [comment]
Hello, here is some feedback!

First of all I have to say that your screencast looks nice and is very well edited. However, the subtitles are a bit long sometimes which make them hard to read and they are covering a large area of the screen. I think that just by splitting them in two and show them after each other would help a lot.

Your introduction is good, I like how you explain all the essential concepts in order for the viewer to understand what you will do. It´s also nice with a voice cover that makes it easier to follow.

However, one thing that wasn´t that clear is the take-home message (which is required in the grading criteria). It would be nice if you highlight what we should take with us from this video, because there was a lot of information presented. 

I liked that you added a QR-code in the end to your github repo.

Regards, Marcus

**Comment by SoFoDa** [comment]
Nice demo! You clearly state how DSpot relates to DevOps and the visuals really add to the explanation of the topic at hand. I agree that the subtitles can be smaller as they tend to obscure what is going on in the background. Furthermore, aspects such as branch and path coverage could be explained further when describing how the tests are initially lacking.

**Comment by javierron** [comment]
- Very good demo, really useful content.
- Very good explanation of test amplification
----
- Video does not mention how to trigger test amplification, it would be really helpful if it did.
- Subtitles could use better timing to avoid to much text being displayed at the same time.
- I would provide links to the tools and documentation used in the video description. Specifically DSpot.

**Comment by Volminger** [comment]
**Voice**: I am really not a fan of these generated voices since their speak is quite monotone and flat. I would suggest just having the music and text instead. But since it is not a grading requirement this is just my personal opinion. 

**Timing**: I like how you distribute your time with a short intro and then move over to actually showing your code and what Dspot can do.

**Visual**: The presentation is well put together and quite visual appealing in the explanation of Dspot. However it is hard to read all the text in the amplifier slide since the text is not sharp. But an overall well edited demo!

**Connection to DevOps**: It is clearly stated to why it matters to DevOps in the beginning

**Take-home message**: You have a nice take home message in the end, but maybe try to make it a bit clearer.

**Subtitles**: I also agree with the rest of the people that have already given you feedback. It would be nice if the subtitles was a bit smaller and more broken up. Since they now end up covering large part of the screen and code.

**Comment by sashikanthr** [comment]
@rbratfors @georgewbar @Marcus9512 @SoFoDa @javierron @Volminger 
Thank you one and all very much for taking the time and providing a detailed constructive feedback of the demo. I hope the demo helped you to gain some faimilarity with DSpot. I will definitely try to address all of your comments, the most prominent ones being the problem with subtitles and a clear take home message.  

I wish you good luck with the course and all future endeavours! :)

**Comment by dieflo4711** [comment]
It was a very informative screencast. The tools were well represented at the beginning of the video. It's clear how the demo is related to DevOps. The video is a little bit blurry sometimes and the subtitles sometimes cover a lot of screen space. These are details, but otherwise great job!

**Comment by sashikanthr** [comment]
@dieflo4711 Thank you for the feedback. I will be fixing the subitile part. :)

**Pull request merged**
