### PR TITLE
[Canvas API] Script to get missing grading

### PR DESCRIPTION
**Pull request by vladomit**
# Tools 

Regarding @monperrus 's email last week, here is the script to get missing grade for a given task and deadline/week.

## How it works

From the tools folder, :

`python missing-grade.py --task executable-tutorial --deadline 1 --token 8779~...`

for demo and presentation :

`python missing-grade.py --task presentation --week week2-testing-and-CI --token 88779~...`

`--week` and `--deadline` are optional, if you don't give them, you'll get all non graded groups for this task
`--token correspond to the canvas token`

### CODE REVIEW

**Comment by khesoem** [comment]
Thanks @vladomitrovic 
How about adding the description of this PR to a new readme file in the [tools folder](https://github.com/KTH/devops-course/tree/2022/tools)?

**Comment by vladomit** [comment]
> Thanks @vladomitrovic How about adding the description of this PR to a new readme file in the [tools folder](https://github.com/KTH/devops-course/tree/2022/tools)?

Done

**Review by khesoem — APPROVED** [review]
LGTM!

**Comment by khesoem** [comment]
Thanks @vladomitrovic

**Pull request merged**
