### PR TITLE
Final submission: Executable tutorial "Installing GitLab in your own infrastructure"

### PR DESCRIPTION
**Pull request by nalenz**
# Assignment Proposal

## Title

Installing GitLab in your own infrastructure

## Names and KTH ID

- Julian Nalenz (nalenz@kth.se)
- Elias Bonnici (bonnici@kth.se)

## Deadline

Task 2 (2022-04-19)

## Category

Executable tutorial

## Description

When companies grow, they often face the requirement of having full control over their Source Code Management tool, so it is not possible anymore to use github.com or gitlab.com. Instead, this service needs to be hosted in their own infrastructure, e.g. to enforce certain company policies regarding access control or to be able to determine the server location.

This executable tutorial should showcase how the platform GitLab can be installed in a newly set up Linode infrastructure. It will move through all the setup and configuration required for the GitLab instance to be fully usable and will give a quick overview of possible next steps and which additional features the paid version of GitLab offers.

[Link to Google Colab tutorial](https://colab.research.google.com/drive/1F1ypKVn8snnm294W2kgAmiILX0Pe1Vos?usp=sharing)

### CODE REVIEW

**Comment by monperrus** [comment]
@nalenz how to shut down the Linode resource to avoid any cost?

**Comment by sigalor** [comment]
@monperrus As long as a Linode VM has not been removed, it still costs something, no matter whether it has been shut down or is still running. We solved this my simply deleting the VM after we didn't need it anymore.

**Comment by nalenz** [comment]
@monperrus As long as a Linode VM has not been removed, it still costs something, no matter whether it has been shut down or is still running. We solved this my simply deleting the VM after we didn't need it anymore.

**Comment by monperrus** [comment]
ack, thanks.

**Pull request merged**
