### PR TITLE
Open source contribution submission

### PR DESCRIPTION
**Pull request by Autonymic**
# Assignment Proposal

## Title

Contributing to a python discord bot

## Names and KTH ID

- Tony Le (ttle@kth.se)

## Deadline

Deadline for task 5

## Category

Contribution to open-source

## Description

The discord bot is made for the Python Discord server. It is written in Python and makes use of Docker to run.
I'd like to contribute to this project as I think software bots are useful and I will learn how to set them up through this task.
This is related to DevOps as it falls under software bots.
The project should be fine to choose as it has more than 10 stars, more than 100 commits and a pretty active community on GitHub with the last merged pull request being merely 4 days ago.

I would like to work on two issues that are related:

https://github.com/python-discord/bot/issues/2171

https://github.com/python-discord/bot/issues/2170

The first is a bug that requires adjusting a command that should be able to take multiple users as arguments, but for now it only accepts one.
The second follows up on it by cleaning up the help text for the command, so it should be considered as adding to the documentation.
There is also a decent possibility of the contribution being merged as well.

**Submission**

The two issues have now been addressed.

Here is the PR for the bugfix:
https://github.com/python-discord/bot/pull/2178

This is the PR for the added/improved docs:
https://github.com/python-discord/bot/pull/2179

Hopefully they will also be merged soon.

### CODE REVIEW

**Comment by Deee92** [comment]
Hi @Autonymic, can you ping the developers on your two PRs, and ask for an update on when they can handle / merge them?
For you to pass this task, it is important that at least one of your PRs is merged, or there is an active conversation with the developers about your contribution.

**Comment by Autonymic** [comment]
image

Hi @Deee92, I did have a conversation with them as I was doing it, as shown in the image above. I will try to get in touch with them through Discord to see if my PRs can be merged or if there is a need to fix anything for that to happen.

I was hoping my contribution would cover fixing a bug and improving documentation though. Is that not the case?

**Comment by Autonymic** [comment]
Hi @Deee92 , one of the PRs have now been merged, and on the other there is a discussion on the details of the issue and fix. That should suffice for this task I suppose?

**Comment by Deee92** [comment]
Hi @Autonymic, thanks for the update.

**Pull request merged**
