### PR TITLE
Week 2 Presesntation: Slides

### PR DESCRIPTION
**Pull request by javierron**
Presentation slides link for our Docker & security presentation

### CODE REVIEW

**Comment by cesarsotovalero** [comment]
@javierron  your presentation is too large. 
You can assume that everyone knows how Docker works (or have only one slide at the beginning) and focus more on the security aspects.

**Comment by javierron** [comment]
Hello! The presentation will not take more than 9 minutes, most of the slides are just image ant text sequences.

 The first part should not take more than 1.5 minutes, and was added for context only.

**Comment by cesarsotovalero** [comment]
@javierron you don't any security tool or real example of vulnerability in depth. I think that your presentation will improve with less introduction and more focus on real examples.

**Comment by javierron** [comment]
OK, we will remove that part and add more focus on the real examples provided.

**Comment by javierron** [comment]
To clarify:

Many people in the course are giving feedback saying that they don't know much about DevOps, and that's why we added some strong context.

Also that the goal of the presentation is to give an overview on the _relation of docker security and DevOps_, and not to explain any tool or vulnerability in depth.

**Comment by cesarsotovalero** [comment]
Ok... good luck!

**Comment by javierron** [comment]
Thank you!

**Pull request merged**
