### PR TITLE
Updated essay based on feedback

### PR DESCRIPTION
**Pull request by MDRezaulHasan**

### CODE REVIEW

**Comment by MDRezaulHasan** [comment]
Hi @khaes-kth, we updated our essay based on feedback. Please check this PR and let us know.

**Comment by khesoem** [comment]
Hi,

Please mention your proposal and your previous submission.

**Comment by MDRezaulHasan** [comment]
Hi @khaes-kth, 
This is our previous Essay proposal #1079 
and previous submission Essay submission #1355
Feedback proposal #1087

**Comment by khesoem** [comment]
@MDRezaulHasan 

Thanks for the information. You should not submit a new PR, you have to update your old submission (#1355) which has not been merged yet. Update the pdf file in that PR and push it.

**Pull request closed without merging**
