### PR TITLE
Demo submission: CD of Node Express App on Google Cloud with designated release branch using Github actions

### PR DESCRIPTION
**Pull request by andnil5**
# Demo: CD of Node Express App on Google Cloud with designated release branch using GitHub actions

In this demo, we will demonstrate how to create a continuous deployment workflow using GitHub Actions that automate deployment of a simple Express server to Google App Engine (GAE), a fully managed, serverless platform for developing and hosting web applications at scale. We will go through the following:
1. How to create a project on Google Cloud
2. How to deploy the Express server to Google App Engine (GAE)
3. How to create a CD workflow to automate deployment using GitHub Actions

## Members

Kalle Pettersson (kalpet@kth.se)  
GitHub: [KallePettersson](https://github.com/KallePettersson)

Anders Nilsson (andnil5@kth.se)  
GitHub: [andnil5](https://github.com/andnil5)

## Screencast link
[YouTube link](https://www.youtube.com/watch?v=lY5Uj_VzClc).

## GitHub repository
[GitHub link](https://github.com/KallePettersson/Continous-Deployment-on-gCloud).

## Motivation

The motivation for why this demo matters to DevOps is twofold.
- It shows how to deploy an application on Google Cloud which increases productivity and flexibility, frees up developers by taking away the demands of managing infrastructure and provides automatic scaling.
- It demonstrates how to create a continuous deployment workflow using GitHub actions, which is one of the cornerstones of DevOps.

## Take home message

Make sure to **NOT** commit your `gcloud_secret.json` file to GitHub. This could give malicious actors remote access to your Google Cloud account.

## Grading - We strive to meet the following grading criteria

|                                             | Yes | No | Remarkable |
|-------------------------------------------- | ----|----|-------------|
|The demonstration is clearly motivated (why it matters for Devops?) | X |  | |
|The video is sublime (eg visually appealing) | X |  |  |
|There is a code repo to run the demo  | X |  | X |
|The video must contain subtitles which are clear and in proper English | X |  |  |
|The video includes a take-home message | X |  | X |

### CODE REVIEW

**Comment by Deee92** [comment]
Thanks @andnil5, merging!

**Comment by sfkwww** [comment]
The visuals were very nice and most of the steps were explained in a lot of detail. Some steps were explained in a bit too much detail though, such as how to log in to Google by pressing 'Allow'. There were also some sections where we need to copy commands and it isn't really highlighted in any way to make it easier to see. The GitHub link also doesn't work if the commands were posted there.

**Comment by Internet-Person-IP** [comment]
Really Nice Video but the quality makes it harder.


Pros:
1. Really Clear Instructions: The video has some solid instructions. This makes it easy to follow and to code along.
2. Top Tier Take Home Message: Good and informative take-home message that everyone should follow!
3. Presentation: The presentation was nice and clear

Improvements:
1. The video quality: I don't know if this is possible for you but I think that improving the video quality meaning resolution would be amazing. Some of the text in the YAML files can be quite unclear about what they are saying based on the resolution.
2. I think the motivation is great however I do believe that you need to include it in the video.

**Comment by IC-kth** [comment]
First of all, congratulations on your video. You approached a very interesting subject, and I enjoyed watching it. Bellow, I will add my main points:  

Strengths:
   - Very good that you added the logos of the used tools and languages as the caption of your video since many people look at the caption first and then read the title.
   - It's good that you state the prerequisites and explain the main files for the demo.
   - You have a very clear, logical, and structured flow in your demo, with detailed explanations for each step.

Potential Improvements:
   - I would suggest adding an opaque background for your explanation text since in various frames it's hard to read it because it overlaps the text displayed in the browser.
   - I  would suggest improving the image quality (the resolution) since it's not that clear (especially when using the terminal it is hard to see the text).
   - The link you provide to the GitHub repo is broken: ```https://github.com/KallePettersson/Continous-Deployment-on-gCloud```

**Comment by andrebrogard** [comment]
Good video!

## Strenghts
* Great clarifications of steps.
* Good background info!
* Clear actionable instructions

## To improve:
* Too fast, pauses necessary. Perhaps intended though.
* Difficult to read code/terminal text. 
* Low resolution on video (related to the above point also)

**Comment by vladomit** [comment]
**Strengths:**
Clear and easy to follow
Nice video editing
You show the prerequisites and important project files a the beginning 

**Improvement:**
Add a summary at the beginning
Don't have the subtitles in CAPITAL letters


But overall very good job guys !

**Comment by Adamih** [comment]
Things that are good: 
* Easy to follow
* It's nice that everything is shown in the process, especially logs, and that step in the process is included.
* A good demonstration of the finished result. 
* The text is very explaining and is a good complement to the demo code. 

Things that can be improved:
* Having a "why" is important. 
* Not having a voice-over was an intended decision I assume, but this means that the pacing of the video is much slower than it needs to be. Some say it's too fast, but pausing to write code should be the indeed way to consume video tutorials in my biased opinion. 

Good demo overall, very nice.

**Comment by andnil5** [comment]
Thank you all for the constructive feedback. We have updated the demo accordingly. You can find the updated demo [here](https://www.youtube.com/watch?v=xieUj9TSewA).

Associated PR: [#1515](https://github.com/KTH/devops-course/pull/1515)

**Pull request merged**
