### PR TITLE
docs: added presentation description

### PR DESCRIPTION
**Pull request by c-cret**
# Assignment Proposal

## Title

A/B Testing 

## Names and KTH ID
  - Mateo Florez (mateofc@kth.se)
  - Gabriel Acar (gacar@kth.se)

## Deadline

Task 1

## Category

Presentation

## Description

The Presentation will cover what A/B testing is in general and how it works, it will also cover why one should use A/B testing and how the A/B testing process looks like. We aim to hold the presentation on the 5th of april.

### CODE REVIEW

**Comment by c-cret** [comment]
@khaes-kth What does "Missing student registration :asim" mean?

**Comment by khesoem** [comment]
@c-cret This is a problem on our side. We are trying to fix it.

**Comment by khesoem** [comment]
BTW, @c-cret your readme is not put in the correct place. It should be inside a folder with the name same as your KTH IDs. Please have a look at other approved contributions.

**Comment by c-cret** [comment]
@khaes-kth All right, my bad, should look right now :)

**Comment by khesoem** [comment]
Hi @c-cret 

This is a relevant and interesting topic. However, other people have worked on it previous years: https://github.com/KTH/devops-course/pull/518. Your proposal should be novel.

PS: to fix the problem with the dd2482-bot, please pull the latest version from KTH/devops-course:2022 and make your changes on that version.

**Pull request closed without merging**
