### PR TITLE
Tutorial: Continuous benchmarking using Github Actions

### PR DESCRIPTION
**Pull request by jhammarstedt**

### CODE REVIEW

**Review by cesarsotovalero — APPROVED** [review]

**Comment by cesarsotovalero** [comment]
hi @jhammarstedt, your tutorial is relevant.
I'll merge your PR. Good luck!

**Comment by altaired** [comment]
Hi! I plan to give feedback on this tutorial, see PR #1188. @jhammarstedt please notify me when you're ready for feedback.

**Comment by jhammarstedt** [comment]
Hi @altaired !
Ok great, me or @carllei will get back to you when we're done! :)

**Comment by jhammarstedt** [comment]
@altaired 
Just wanted to give you an update that we're basically done with the code and are working on the katacoda now. We're estimating to have it done by the end of this week but I'll let you know on Friday either way.

**Comment by altaired** [comment]
@jhammarstedt any updates on your status?

**Comment by jhammarstedt** [comment]
@altaired 
Hi,
Yes meant to get back to you yesterday, but we've been working all week and had to make some finals adjustments. Aim to send it in tomorrow evening.

**Comment by altaired** [comment]
Great :)

**Pull request merged**
