### PR TITLE
Presentation Proposal: Continuous Experimentation

### PR DESCRIPTION
**Pull request by sashikanthr**
#  Continuous Experimentation

## Members:

- Sashikanth Raavikanti (sraa@kth.se)

- Nicholas Steele (nsteele@kth.se)

## Description:

Nick and I, Sashi, found the topic of continuous experimentation very interesting. As part of the presentation we would like to cover -

- Some background on Continuous Experimentation.
- Various experimentation practices such as Canary Releases, Dark Launches, etc.,
- Implementation techniques like Feature Toggles and Runtime Traffic Routing.
- Regression Driven and Business Driven experiments
- A real time use-case from Regression Driven experiments that covers one of the practices and techniques.

[Resource](http://eprints.cs.univie.ac.at/5953/1/paper-1.pdf)

### CODE REVIEW

**Comment by gluckzhang** [comment]
Hi @sashikanthr , note that there have been *7* presentations in `week4`, which is the maximum number. Do you mind moving your presentation to `week5` or `week6`?

**Comment by sashikanthr** [comment]
> Hi @sashikanthr , note that there have been _7_ presentations in `week4`, which is the maximum number. Do you mind moving your presentation to `week5` or `week6`?

Now moved the presentation to Week 5

**Comment by gluckzhang** [comment]
Thanks @sashikanthr , the PR has been merged.

**Comment by sashikanthr** [comment]
@gluckzhang Nick and I see that the topic has become very broad and we have chosen to entirely focus on Canary Releases as part of Continuous Experimentation. We will be providing information in detail along with 2 tools from IBM and Netflix can be used for Canary Testing / Canary Release practice. May I know if this is okay?

**Comment by gluckzhang** [comment]
Hi @sashikanthr , it's good to narrow down the scope and deeply discuss canary releases. So this is OK. Maybe it's better to update the title as well. You could submit a PR to update it :)

**Comment by sashikanthr** [comment]
Thank you @gluckzhang! I have now created a PR - https://github.com/KTH/devops-course/pull/574

**Pull request merged**
