### PR TITLE
Submission: Course Automation for Validation and Labeling

### PR DESCRIPTION
**Pull request by altaired**
This is my submission of the course automation proposed in PR #949. Information about the submission in detail can be found in the README.md file. 

This pull request does not enable the action, if that is desirable,  just tell me below and I'll fix it. Either way it should be very easy to enable and a suggested configuration file is included in this pull request (an issue number has to be set). The configuration file also makes it easy to reuse this action in other courses and future instances of this course. 

In order for the action to work, it is required to provide an API token as input to the action. More info about this can be found in the repoitory.

Repository: [https://github.com/altaired/devops-label](https://github.com/altaired/devops-label)

An example of the generated summary can be found among the issues in the repository above, it is issue 3 and can also be found by filtering on the label "generated". 

## Aiming for the following criterias

| | Yes | No | Remarkable
| -- | -- | -- | -- |
The work is done before April 6, 2021 (in order to be useful for the course) | ✓ Yes | No | n-a
The automation task produces a PR status or issue / PR comment | ✓ Yes | No | Points to a generated page with valuable additional information
The automation task is reusable | Yes (next year for this course) | No | ✓ In other courses than this one
The task runs on a standard platform | ✓ Yes (Github action) | No | Other platforms (e.g. Moodle, Canvas)
The task is praised by the other students of this course | (Hopefully) Yes | No | n-a
The code for the task is available | Yes (public repo) | No | ✓ Well documented repo

Signed-off-by: Simon Persson, siper@kth.se

### CODE REVIEW

**Comment by altaired** [comment]
As I've registered to give feedback on another task, I'm looking for someone to give feedback on this one if possible? @SophieHYe

**Comment by altaired** [comment]
@SophieHYe @khaes-kth @Deee92

**Comment by SophieHYe** [comment]
Hi,
Thanks for your cool submission. I will merge this version. 
Could you please also point out where the report/summary of your handled PR could be checked?

**Comment by altaired** [comment]
@SophieHYe Thank you for the response, I've updated the readme in the repository to mention where an example can be found. TL;DR the repository has the action enabled on itself, and issue #3 in that repo shows the summary.

**Comment by SophieHYe** [comment]
Thanks for the update. I am merging your PR now.

**Pull request merged**
