### PR TITLE
Essay

### PR DESCRIPTION
**Pull request by pontusnorman123**
# Assignment Proposal

## Title

_DevSecOps: Integrating Security into the DevOps process_

## Names and KTH ID

 ponorman@kth.se

## Deadline
- Task 2

## Category

- Essay.

## Description

_Security is an important part of DevOps and any computer system, so this essay wants to explain what types
of security meausures can be taken in DevOps and what challenges and advantages that may come with these
methods._

### CODE REVIEW

**Comment by Deee92** [comment]
Hi @pontusnorman123, we've had essay contributions on DevSecOps in the course before. Can you refine your proposal to focus more on specific tools / technologies within DevSecOps?

**Comment by pontusnorman123** [comment]
Ok I specified it to be more about the testing aspect of DevSecOps, is that specific enough or should I specify more?

**Comment by pontusnorman123** [comment]
# Assignment Proposal

## Title

_DevSecOps: Security testing in DevOps_

## Names and KTH ID

 ponorman@kth.se

## Deadline
- Task 2

## Category

- Essay.


## Description

_Security is an important part of DevOps and any computer system, so this essay wants to explain what kind
of testing can be done in DevOps and what challenges and advantages that may come with these
methods._

**Comment by Deee92** [comment]
Hi @pontusnorman123, the proposal can be refined further.

> _explain what kind of testing can be done in DevOps and what challenges and advantages that may come with these
methods._

Could you elaborate on the kinds of testing you are referring to?

**Pull request closed without merging**
