### PR TITLE
Demo: Using Cloud Functions in Firebase to create a serverless React app

### PR DESCRIPTION
**Pull request by m4reko**
# Demo: Using Cloud Functions in Firebase to create a serverless React app #

## Members ##
Markus Wesslén (mwesslen@kth.se) GitHub: [m4reko](https://github.com/m4reko)

Christian Stjernberg (cjgst@kth.se) GitHub: [christian-stj](https://github.com/christian-stj)

Lara Rostami (larasm@kth.se) GitHub: [LaraRos](https://github.com/LaraRos)

## Proposal ##
We propose a demonstration of how to create a simple React app using Firebase hosting and Cloud Functions to create app logic. The app will be hosted in a serverless manner.

### Tools ###
- React
- Firebase
  - Cloud Functions
  - Hosting

### CODE REVIEW

**Comment by SophieHYe** [comment]
Hi,
Please add more information about your tutorial proposal, so that we can assess if your PR is novel and original enough to be merged.


Specifically, please add preliminary plan of your demo, your motivation, and clarify the novelty/originality statement of your demo. Thanks!

**Comment by LaraRos** [comment]
## Motivation ##
Using Firebase can be difficult since it is a large platform wiht many services. We wish to make a video tutorial where we show how to do this in a short and simple manner, together with React.

## Novelty ## 
The material you can find online is quite complex and takes time to read. We wish to create a short video on the subject which will give you the basic tools in 3-4 minutes.

## Related to DevOps ## 
* The server will use cloud functions that are being run in Firebase as opposed to the server itself
* We will automatically deploy the main branch to Firebase

## Plan ##
* Create a working prototype in React with Firebase
* Create cloud function
* Automatically deploy from main branch to Firebase
* Create script for recording
* Record
* Post to GitHub

**Comment by LaraRos** [comment]
@SophieHYe

**Comment by christian-stj** [comment]
@monperrus We have one week with no feedback and would like to get started/ know what we need to do to improve the plan

**Comment by SophieHYe** [comment]
Thanks for the update. Your proposal looks great. I am merging it now.

**Pull request merged**
