### PR TITLE
Course Automation Proposal: Labelizing "feedbackable" merged PR contributions 

### PR DESCRIPTION
**Pull request by Hilaire-Bouaddi**
# GitHub action to show what is available for feedback 

## Member

Hilaire Bouaddi, bouaddi@kth.se, [https://github.com/Hilaire-Bouaddi]

## Rationale 

It takes some minutes to check if a contribution we are interested in will receive feedback or not. This can generate frustration.
The aim of the proposal is to automate the labelization of PR to mark the ones that can be feedbacked. 

## Proposal

I would like to try to create a GitHub Action. This action would:
- get the URL of every merged PR for contributions in either essay or executable tutorial. 
- for every URL 
  - if the URL is referenced in a contribution for feedback, put the label "feedbacked" to the PR, delete other labels "feedbackable" and "feedback claimed"
  - else if the URL is referenced in a feedback PR that waits to be merged, put the label "feedback claimed" to the PR, delete other labels "feedbackable" and "feedbacked"
  - else put the label "feedbackable" to the PR, delete other labels "feedback claimed" and "feedbacked"

### Legend 
* "feedbackable": nobody claimed the feedback for this task yet
* "feedback claimed": a PR is waiting to be merged for the feedback of this contribution
* "feedbacked": the feedback for this contribution has been claimed

### CODE REVIEW

**Comment by khesoem** [comment]
Hi @Hilaire-Bouaddi 

It is very useful contribution. Just one question: how is the action triggered?

**Comment by Hilaire-Bouaddi** [comment]
I have no experience with GitHub Action but I was hoping to trigger it when a PR is merged. Do you think it would be doable?

**Comment by khesoem** [comment]
> I was hoping to trigger it when a PR is merged. Do you think it would be doable?

Yes it is doable. But do you mean you want to check all the existing PRs and update their labels whenever there is a new pull request?

It seems it is also possible to run it preiodically: [https://jasonet.co/posts/scheduled-actions/](https://jasonet.co/posts/scheduled-actions/)

**Comment by Hilaire-Bouaddi** [comment]
But what would be the benefit of running it periodically? Since the execution depends only on the merged pull requests, why not only run it after every PR that is merged? If that is not clear, should we discuss this at the Lab session on Friday morning? Thank you very much for your feedback.

**Comment by khesoem** [comment]
> But what would be the benefit of running it periodically? Since the execution depends only on the merged pull requests, why not only run it after every PR that is merged? If that is not clear, should we discuss this at the Lab session on Friday morning? Thank you very much for your feedback.

You are right. Running it after a PR gets merged is enough. Note that you should check the all PRs and update their labels after a merge (if I understand your proposal correctly).

**Comment by khesoem** [comment]
Unfortunately, I cannot merge your proposal now because you have added new commits which add a workflow. Your proposal PR should only add a README file.

**Comment by khesoem** [comment]
Please create a new PR which only contains your proposal.

**Pull request closed without merging**
