### PR TITLE
Feedback submission on essay draft #1023

### PR DESCRIPTION
**Pull request by IfyUrama**

### CODE REVIEW

**Comment by khesoem** [comment]
Hi @IfyUrama 

Your submission should only change the `contributions/feedback` folder. This PR is also changing the `contributions/presentation` folder. Please fix it soon.

**Comment by IfyUrama** [comment]
@khaes-kth The submission is now on contributions/feedback/urama/README.md

**Comment by khesoem** [comment]
> @khaes-kth The submission is now on contributions/feedback/urama/README.md

I think your PR is removing the presentation README. Check your repo [here](https://github.com/IfyUrama/devops-course/tree/2021/contributions/presentation/week6/urama-yuxinm).

**Comment by IfyUrama** [comment]
Hi @khaes-th, 
 I don't think so. Our real presentation folder was made by my colleague. I tried to make the pull request, but had some issues, so my colleague did it. The presentation README you saw I deleted it the unused one I made.
Hope it's ok now?



Sent from Yahoo Mail on Android 
 
  On Tue, 4 May 2021 at 10:54, Khashayar ***@***.***> wrote:   



@khaes-kth The submission is now on contributions/feedback/urama/README.md


I think your PR is removing the presentation README. Check your repo here.

**Comment by khesoem** [comment]
[Here](https://github.com/KTH/devops-course/pull/1392/files) you can see the files your PR is changing. It is removing the already merged README of your presentation. [Here ](https://github.com/KTH/devops-course/tree/2021/contributions/presentation/week6/urama-yuxinm)is the the merged directory for your presentation. And [here ](https://github.com/IfyUrama/devops-course/tree/2021/contributions/presentation/week6/urama-yuxinm)is your directory.

You may need to `rebase` your branch to fix this issue.

**Comment by IfyUrama** [comment]
Hi @khaes-kth,

Should I close this pull request and make a new one to resubmit my feedback?

**Comment by khesoem** [comment]
@IfyUrama If you think that would solve the issue with your PR, you can to it.

**Comment by khesoem** [comment]
I just noticed you have created another PR with similar content (#1482). So I'm closing this one.

**Pull request closed without merging**
