### PR TITLE
Essay proposal

### PR DESCRIPTION
**Pull request by christian-stj**
Proposal for essay with outline added 

@khaes-kth I opened a new pull request as I could not update the one you closed

### CODE REVIEW

**Comment by khesoem** [comment]
Hi @christian-stj ,

Thanks for the update. I'm still concerned that your proposal is a bit too broad. Let us ask other TAs' opinion.

@Deee92 and @SophieHYe : What do you think about this essay proposal?

**Comment by christian-stj** [comment]
@Deee92 @SophieHYe

**Comment by Deee92** [comment]
Hi @christian-stj, I agree with @khaes-kth that the proposal might be too broad, but if you can ensure that you target very specific, technical aspects that make Git extremely relevant for DevOps, albeit potentially challenging for beginners, I think it would make for a meaningful contribution.

**Comment by christian-stj** [comment]
@Deee92 @khaes-kth  I can try to angle the essay to be more about the usage of version control and its gain to development productivity and how improving on Git can make for a more productive development process. Which will make the essay more related to DevOps.

**Comment by khesoem** [comment]
If I were you, I would change the topic and focus on a specific tool. "usage of version control" is too general and it is very hard to come up with an exciting essay on it.

**Comment by christian-stj** [comment]
I am planning on writing about Git so it is a very specific tool. I will discuss Git and also Git servers which are very relevant to DevOps and the DevOps process. There will be background presented so the user can understand the relevance to the DevOps field and get some understanding of Git and then the essay will be focused on user interaction and concepts of the Git architecture that make it hard for new users to understand. 

I think this topic definitely should be relevant enough to the course. I will make sure that the essay will not be too broad, it will focus on the Git tool, its architecture and usability.

**Comment by khesoem** [comment]
Fine.

Isn't your proposal very similar to this one? https://github.com/KTH/devops-course/pull/1092

**Comment by christian-stj** [comment]
It does have some similar content, mostly the part explaining the structure of Git. Perhaps I should give up on this topic since it has met a lot of resistance.....

**Comment by khesoem** [comment]
> Perhaps I should give up on this topic since it has met a lot of resistance.....

It's your call. I really do not want to resist too much, the sooner your PR is merged, the sooner I can proceed to assessing the next PR :-) However, we have to follow the rules of the course to the extent that we can.

**Comment by christian-stj** [comment]
I will do a presentation instead, @khaes-kth thanks for the quick feedback.

**Pull request closed without merging**
