### PR TITLE
Finished tutorial: Github Apps and Actions

### PR DESCRIPTION
**Pull request by louisezetterlund**

### CODE REVIEW

**Comment by bbaudry** [comment]
Feedback per #548

- 'Background'
  - the first sentences provide several statements about buzz words, agile, devops. For each statement, link to the source document(s) where you have read this
  - second paragraph is bit a confusing / redundant
  - what is a Doctrine container?

- 'How to install an GitHub App or Action'
  - I suggest to add an introduction for this section where
    - you announce that you will present three ways of installing an App
    - you motivate why you chose to explain these three ways
    - you discuss other possible ways, if they exist
  - prerequisites: it is ok to assume that the reader has a GitHub account and some GitHub repositories. However, some readers will not use slack and / or Discord. Can you explain the marketplace and webhook with no other prerequisite than a GitHub account.
  - 'webhook'
    - add a motivation to discuss webhooks here
    - what are examples of event / action that can trigger a webhook in github?
    - 'webhooks efficient both for the provider and the consumer.' What are provider and consumer here? What does efficient refer to?
    - why switch to a video tutorial for this last part of the tutorial? A tutorial about Github apps is good on a Github repo. I suggest to include this part with the rest of the tutorial
    - the video has no subtitle, sound or voice, which makes it difficult to follow.
  - how can an app be uninstalled?
- I suggest to add a conclusion section where
  - you summarize what you expect the reader should have learned
  - you provide further readings about why developers use actions, and share their experience about using different types of actions
- Minor comments
  - in table of contents, the link '2. How to ..' is broken
  - check for typos
  - formatting: to avoid keeping track of reference numbers, you can replace these numbers  [1] by a link on the corresponding word, e.g. [DevOps](https://en.wikipedia.org/wiki/DevOps). On a Github repo, it is fine if you don't have a numbered list of references at the end of the tutorial.

**Comment by louisezetterlund** [comment]
We are finished with this and ready for the final grade.

**Comment by gluckzhang** [comment]
> We are finished with this and ready for the final grade.

Hi @louisezetterlund , any updates to this PR? I'm considering to merge it.

**Comment by louisezetterlund** [comment]
Hi @gluckzhang, no updates, you can merge :) (The updates are in another repository that we already link to in the README in this PR)

**Comment by gluckzhang** [comment]
Perfect, thanks @louisezetterlund :)

**Pull request merged**
