### PR TITLE
Tutorial suggestion: Code Coverage

### PR DESCRIPTION
**Pull request by jonasjohansson8908**
### Group members:

Jonas Johansson, jonasjo5@kth.se

### Description

A step-by-step tutorial on how to setup and use a code coverage tool on your Github repository and integrate it with your CI solution. As an example I would suggest covering how to setup a Python or Java/maven project with Codecov or Coveralls. Each solution of course already have some documentation but I have yet to find a tutorial that is thorough and goes through all the steps mentioned below: 

Suggestions:

- A small introduction to code coverage.
- A comparison between existing solutions and a motivation of how the solution covered by the tutorial was chosen.
- Prepare the repository (if necessary).
- Setup the code coverage tool.
- Integrate the tool with your repository.
- Integrate the tool with a CI solution.
- A few examples on how to use the CC-tool.
- Hopefully I will find some easter eggs to cover when I dive into the topic.

### CODE REVIEW

**Comment by cesarsotovalero** [comment]
Hello @jonasjohansson8908, good topic. 
Please also add a comparison between the existing alternatives and explain your choice for the tutorial.
You can use https://github.com/hakimel/reveal.js for an in-browser version.
Good luck!

**Comment by jonasjohansson8908** [comment]
@cesarsotovalero 
Thank you for the suggestions!
How deep should the comparison be? Is it enough to cover why the solutions was or wasn't chosen, based on my perception when looking for alternatives?

**Comment by cesarsotovalero** [comment]
@jonasjohansson8908 Exactly. 
You just need to justify very well why you selected the Code Coverage tool that you will use (pros and cons), and give some insights about the alternatives (no need to be too explicit here). 
If you don't have any other question I'll merge.

**Comment by jonasjohansson8908** [comment]
@cesarsotovalero 
Thanks! You can merge now.

**Pull request merged**
