### PR TITLE
Presentation Proposal: Optimization Strategies for Test Suite Runtimes in Large Software Applications

### PR DESCRIPTION
**Pull request by luuuk**
# Assignment Proposal

## Title
Optimizing test runtime in large software applications

## Names and KTH ID
- Luke LeVasseur (lukel@kth.se)
- Nikolaos Smyrnioudis (nsmy@kth.se)

## Deadline
Task 1

## Category
Presentation

## Description

We intend to present various strategies which could be used to shorten test suite runtime in industry settings.
Often, tests suites on larger software applications can take upwards of 30 minutes to run in full. While the practice of
running all tests is a core principle of CI practice, it also hinders developer productivity.

Our presentation will discuss strategies DevOps practitioners can use to shorten test suite runtimes. Initial ideas
include parallelization of unit tests, CAREFUL parallelization of integration tests, increased resource allocation, only
running tests that cover modified code, and stochastically selecting unhelpful tests to skip over.

We are unaware of any existing tools that are designed to help with this problem and would love to learn more about them
as well if staff or other students have any suggestions!

### CODE REVIEW

**Comment by luuuk** [comment]
@khaes-kth Hi Khashayar - I was wondering if there are any additional steps Nikos and I need to take with this PR to get it approved by the staff? Thanks!

**Comment by luuuk** [comment]
I am also not sure why the `build` step is failing here (I've tried rerunning it by closing and reopening, but it doesn't want to pass)

**Comment by khesoem** [comment]
Hi @luuuk 

Thanks for submitting this proposal.

The first issue that I see is that you have not put your README file in the correct directory. You should put a presentation into the corresponding week folder here: https://github.com/KTH/devops-course/tree/2022/contributions/presentation

**Comment by khesoem** [comment]
Also, it seems there is a problem with GHActions today. We should wait for Github to solve it.

**Comment by luuuk** [comment]
> Hi @luuuk
> 
> Thanks for submitting this proposal.
> 
> The first issue that I see is that you have not put your README file in the correct directory. You should put a presentation into the corresponding week folder here: https://github.com/KTH/devops-course/tree/2022/contributions/presentation

I believe this is fixed now - let me know if the PR looks ok!

**Comment by vladomit** [comment]
@luuuk can you try to edit your README.md ? Just to ensure that the action is taking the last commit.

Anyways, I see that your README.md is not correctly formatted, It must follow the template, as you did in the first PR comment.

**Comment by khesoem** [comment]
Make sure you mention the problem in the company for motivation as well as tools that you can use for parallelization

**Pull request merged**
