### PR TITLE
Executable Tutorial Submission: API testing using RestSharp and Specflow in C# application.

### PR DESCRIPTION
**Pull request by gangwalmegha**

### CODE REVIEW

**Comment by gangwalmegha** [comment]
Hi @khaes-kth,
We need feedback on our executable tutorial, we don't have any feedback provider.

**Comment by khesoem** [comment]
Hi @gangwalmegha ,

@SophieHYe or Me will give you some feedback soon.

**Comment by khesoem** [comment]
> Hi @gangwalmegha ,
> 
> @SophieHYe or Me will give you some feedback soon.

For the record: Per our discussions, @Deee92 will give you feedback.

**Comment by Deee92** [comment]
### Feedback for " API testing using RestSharp and Specflow in C# application"

**Note:** Instructions to run the tutorial were not very clear, and the deadline is fast approaching. For this reason, the tutorial was not performed locally, and feedback is based on the post on Medium.

#### Remarks

- Include links wherever applicable (example, for RestSharp, NuGet) when introducing tools for the first time.
- Since the tutorial must be executed locally, include complete details about how each tool has to be installed and set up.
- It is a better idea to include scripts or code as text and not as an image/screenshot
- For the sample project, the README is unrelated to this tutorial and mentions the author "John Kocer".
- Talk more about writing tests with RestSharp, give more examples.
- Discuss the different kinds of assertions available. Does RestSharp allow detailed assertions on the `RestResponse`?
- Where is `UnitTest1.cs` in the linked GitHub repo?
- What are the steps for someone who does not use Visual Studio Code? Are there any command-line options to run these tests and the server?

**Comment by gangwalmegha** [comment]
Hi @Deee92 , @khaes-kth ,
We have updated the executable tutorial as per the feedback received:

We  tried to  answer  these remarks:
1. Include links wherever applicable (example, for RestSharp, NuGet) when introducing tools for the first time. 
- [done]
2. Since the tutorial must be executed locally, include complete details about how each tool has to be installed and set up.
-[done]
3. It is a better idea to include scripts or code as text and not as an image/screenshot
-[done]
4. For the sample project, the README is unrelated to this tutorial and mentions the author "John Kocer".
-[done]
5. Talk more about writing tests with RestSharp, give more examples.
- we tried.
6. Discuss the different kinds of assertions available. Does RestSharp allow detailed assertions on the RestResponse?
-[done]
Where is UnitTest1.cs in the linked GitHub repo?
-[It is present in the TodoSolution.sln file]
7. What are the steps for someone who does not use Visual Studio Code? Are there any command-line options to run these tests and the server? 
-[We tried to answer this question by using docker image.]

**Comment by khesoem** [comment]
Hi @gangwalmegha 

Your PR [is changing two files](https://github.com/KTH/devops-course/pull/1420/files), it should change one. Please fix this ASAP.

**Comment by gangwalmegha** [comment]
@khaes-kth , I have deleted my feedback file(readme.md), but now it shows some conflicts. Can you help me in this issue?

**Comment by gangwalmegha** [comment]
Hi @khaes-kth ,
I tried to solve the conflict , but I am not to succeed in it . Please guide me in this issue.

**Comment by khesoem** [comment]
Since your new PR is merged, I closed this one.

**Pull request closed without merging**
