### PR TITLE
demo proposal: CD implementation using Node Express and Google Cloud Services

### PR DESCRIPTION
**Pull request by bckfilip**
# Assignment Proposal

## Title

CD implementation of a React Native app using Google Cloud services

## Names and KTH ID
  - Filip Bäck (filbac@kth.se)
  - Isac Haglund (isacha@kth.se)

## Deadline

Task 1

## Category

Demo

## Description

CD implementation of a React Native app using Google Cloud services

### CODE REVIEW

**Comment by bckfilip** [comment]
tagging @khaes-kth as per request from PR #1596 #1631 

What does "Missing student registration :asim" mean?

**Comment by khesoem** [comment]
This comment is a problem on our side. A student who had not registered for the course yet, has had a merged PR and that is causing problems. We're working on it.

**Comment by khesoem** [comment]
Your proposal seems relevant and interesting.

Please make sure you have something new to say, compared to this PR: https://github.com/KTH/devops-course/pull/822

When the problem with the bot is solved, I'll merge this PR.

**Comment by khesoem** [comment]
@bckfilip 

Can you please pull the latest version from upstream (KTH-devops, 2022 branch)? I believe that will solve the problem with the bot.

**Comment by bckfilip** [comment]
@khaes-kth 

I have pulled the latest version and all checks pass! Thank you for the assistance.

**Pull request merged**
