### PR TITLE
Feedback complete on #1269

### PR DESCRIPTION
**Pull request by agnesforsberg**

### CODE REVIEW

**Comment by agnesforsberg** [comment]
Feedback for PR #1269 by @rymane and @agnesforsberg

**Comment by Deee92** [comment]
Hi @agnesforsberg, please resolve merge conflicts and let me know.

**Comment by agnesforsberg** [comment]
@Deee92 It's resolved now, sorry about that!

**Comment by SophieHYe** [comment]
Thanks for the feedback. I am merging your PR.

**Pull request merged**
