### PR TITLE
Open Source Contribution Proposal: better-npm-audit

### PR DESCRIPTION
**Pull request by bencivjan**
# Assignment Proposal

## Title

Contributing to [better-npm-audit](https://github.com/jeemok/better-npm-audit)

## Names and KTH ID
  - Ben Civjan (civjan@kth.se)
  - Diego Chahuan (docl@ug.kth.se)

## Deadline

Deadline task 5

## Category

Contribution to open-source

### Description

[better-npm-audit](https://github.com/jeemok/better-npm-audit) is a repository for creating a more informative npm-audit output. This relates to DevOps because it is an improvement on an existing package manager and is used to make software development more efficient to debug and automates common development tasks. It also relates to DevOps because it makes it easier to understand dependencies vulnerabilities and possible security failures.

We have addressed an issue that was raised and requested to be implemented by the author of the library. We will create a feature that splits the output of better-npm-audit into 2 tables, separated as developer dependencies and production dependencies. This will help developers prioritize which packages to fix, since a developer vulnerability is generally not as problematic.

The repository has 77 stars, 218 commits, and has an active community on GitHub since we recently had a conversation with the author.

### CODE REVIEW

**Comment by khesoem** [comment]
Interesting proposal.

Have you created an issue on that project?

**Comment by dchahuan** [comment]
Yes we worked on an open issue in the project. And ask the owner if help is still needed.

**Comment by khesoem** [comment]
Can you add a link to that issue?

**Comment by bencivjan** [comment]
[https://github.com/jeemok/better-npm-audit/issues/67](https://github.com/jeemok/better-npm-audit/issues/67) @khaes-kth

**Comment by khesoem** [comment]
Can you add it to the readme as well, please?

**Comment by bencivjan** [comment]
Just added it

**Pull request merged**
