### PR TITLE
Essay proposal: Types of deployments

### PR DESCRIPTION
**Pull request by bubriks**
# Essay proposal: Types of deployments

## Members

Ralfs Zangis (zangis@kth.se)
GitHub: [Ralfs](https://github.com/bubriks)

## Proposal

Document the reasons for using different forms of deployments (Rolling, blue/green and canary).

- Explain each form of deployment
- Give reasons for their usage
- Explain their drawbacks
- Examples from industry
- Final thoughs on the subject

### CODE REVIEW

**Comment by SunnyLight777** [comment]
a very interesting form of text structuring. this can be useful to many students, as well as many other helpful resources. One of my favorites is: https://writemyessays.me/advice-for-overcoming-procrastination/, it helps to improve the work. it can help a lot of people in editing their essays, which, by the way, will save a lot of time. This is very important for students as they need to be multitasking.

**Comment by bubriks** [comment]
> a very interesting form of text structuring. this can be useful to many students, as well as many other helpful resources. One of my favorites is: https://writemyessays.me/advice-for-overcoming-procrastination/, it helps to improve the work. it can help a lot of people in editing their essays, which, by the way, will save a lot of time. This is very important for students as they need to be multitasking.

**Comment by bubriks** [comment]
> a very interesting form of text structuring. this can be useful to many students, as well as many other helpful resources. One of my favorites is: https://writemyessays.me/advice-for-overcoming-procrastination/, it helps to improve the work. it can help a lot of people in editing their essays, which, by the way, will save a lot of time. This is very important for students as they need to be multitasking.

Thanks for the feedback

**Comment by khesoem** [comment]
@vladomitrovic will give feedback on this essay (see #1115).

**Pull request merged**
