### PR TITLE
Demo final

### PR DESCRIPTION
**Pull request by Mema5**
Hi, 
Here is our demo on terraform and cloud run. We hope you'll enjoy it :) 
Maël and Victor

### CODE REVIEW

**Comment by adbjo** [comment]
Hello, I will give feedback on this demo!

**Comment by Marcus9512** [comment]
Hello i would like to give feedback

**Comment by christinasunnegardh** [comment]
I'd like to give feedback :)

**Comment by Callet91** [comment]
I can give feedback as well

**Comment by zen93** [comment]
I would like to give feedback also

**Comment by Goradux** [comment]
I would like to give feedback!

**Comment by zen93** [comment]
Feedback: At 0:13 secs, the subtitles say posted instead of hosted.

**Comment by Goradux** [comment]
Feedback

Preface: I have no experience with terraform, but am familiar with google cloud.

Overall, a great demo. Good pace, good explanations, very visual and clear (even though you had subtitles, I did not even have to look at them once). The motivation for the demo is very clean and it is a great CI/CD tool to know. If I really had to nitpick, then the only thing I noticed was the audio volume difference at 4:20 and 4:35. Good job guys!

**Comment by adbjo** [comment]
Thanks for this great demo, nice work!
Feedback:
- The voice-over is great, very good pace and prononciation.
- The network diagram at the start/end + explanation makes the purpose very clear.
- The subtitles are wrong in many places, for example "in golang" is subtitled "angolang" at 0:35.
- Most of the Terraform file is already filled in, a quick explanation of what has been already set up could be added.

**Comment by christinasunnegardh** [comment]
Hi! Here is my feedback for this demo:

First of all, the demo feels like a real pro-demo that really belongs on YouTube :) I really like that the description is so well-documented as well - great job!

- Maybe it _could_ be nice to have some links to information about the concepts in the description (like Cloud Run, Terraform), if the viewer haven't heard about them before. (I don't know if this is necessary though, if you google for this demo you probably already know what they are - but worth thinking about maybe 🤔)
- The subtitles are sometimes a bit off, so I turned them off. However, for me it didn't matter as your English + the pace is so good.

I really like that the demo is so technical and that you explain everything so well. Awesome demo overall!

**Comment by Marcus9512** [comment]
Hello!

First of all, the demo looks really nice and explains all the relevant information in order for the viewer to understand the demo. I liked that you used youtube´s inbuilt function for subtitles, however, they were sometimes cut in the middle of a sentence which made it a bit harder to read. The first time you stopped the video in order to skip the building of the image, the video resumed in a sentence. This is just a minor problem, but it maybe is easy to fix.

In the last slide when you summarized the demo I think that it would help that you mention (or write) that this is your take-home message, just so that is clear when they are grading your demo.

I like that you have a GitHub repo to the demo, but I think that it needs a readme that explains how to use it, just to make it simpler if I would like to try some of the features. 
Again, nice demo!

Regards, Marcus

**Comment by Callet91** [comment]
# Feedback onTerraform demo: webapp in Google Cloud Run #801

|  | Yes | No | Remarkable |
| ------ | ------ | ------ | ------ |
| The demonstration screencast is clearly motivated (why it matters for Devops?)| Yes| | |
|The demonstration screencast is difficult to do| | | Remarkable |
|The demonstration screencast is original|Yes|||
|The demonstration screencast is sublime (eg visually appealing)| | | Remarkable |
|The demonstration screencast contains an easter egg| |No| |
|An accompanying Github repository has been made (optional)| Yes | | |

### Motivation:
**The demonstration screencast is clearly motivated (why it matters for Devops?)** 
The students states clearly how the demo relates to DevOps. 

**The demonstration screencast is difficult to do**
The demo utilizes many tools that relates to DevOps such as Terraform, GCP and Docker. Though the students makes it look easy, it is not something that anyone can pull off. 

**The demonstration screencast is original**
When searching for terraform, GCP and Docker on youtube, similar videos show up that sort of does the same thing as your demo, but not the exact combination so I would say that the demo is original. 

**The demonstration screencast is sublime (eg visually appealing)**
Easy to follow along. You take your time when explaining all the various steps you make. Like someone else said, like a pro code youtuber. 

**The demonstration screencast contains an easter egg**
I could not find any, but who am I to say that their is none. 

**An accompanying Github repository has been made (optional)**
It has, however, it is not that thorough. Remember, to get an "remarkable" on the demo you need a good repo. Update this so you can get that juzy remarkable.

**Bonus**
Great take home meassage. 

### Suggestions on changes/additions
- Add student name on title screen. I think it is redundant but Martin and Benoit said that it should be there
- Update repo with a more thorough readme.

**Comment by Mema5** [comment]
Waw, really, thank you all for your constructive feedbacks :) 
Thanks @Callet91 @Marcus9512 @christinasunnegardh @zen93 @Goradux @adbjo !!

**Comment by valsen** [comment]
Thanks for all your wonderful comments and feedback!

**Pull request merged**
