### PR TITLE
Feedback for essay "Putting the hours on fun, not manual labor: Incorporating DevOps in the Video Game Industry"(PR #1312)

### PR DESCRIPTION
**Pull request by callmeGoldenboy**
Updating the readme with the feedback. 
Feedback proposal was #983
Essay proposal was #970
Actual essay submission PR was #1312

### CODE REVIEW

**Comment by SophieHYe** [comment]
Hi, thanks for your PR. Please solve the conflict and add your name and KTH email in the ReadMe file, so that we can grade your task. Thanks.

**Comment by callmeGoldenboy** [comment]
> Hi, thanks for your PR. Please solve the conflict and add your name and KTH email in the ReadMe file, so that we can grade your task. Thanks.

Hi @SophieHYe , I'm not sure how to resolve the conflict since I do not have write access to the repo. Have never gotten this type of conflict on a forked repo. Could you elaborate more on what steps I need to take?

**Comment by callmeGoldenboy** [comment]
@SophieHYe  I have now solved the merge conflict

**Comment by SophieHYe** [comment]
Thanks! I am merging your PR now.

**Pull request merged**
