### PR TITLE
add tutorial proposal

### PR DESCRIPTION
**Pull request by georgewbar**
# Jenkins pipelines using Declarative pipelines and Jenkins user interface

## Contributors
George Rezkalla - rezkalla@kth.se @georgewbar

## Description

This tutorial will be about how to use Declarative pipelines and how to use Jenkins user interface to build a pipeline to compile a demo maven java app and run the unit tests whenever the code is pushed to a repo. The idea is to show two different ways of doing the same thing.

I will try using katacoda to make this tutorial. However, if there are some issues regarding using katacoda, i will demostrate how to install jenkins locally on a computer, and do the tutorial locally.

### CODE REVIEW

**Comment by SophieHYe** [comment]
Hi,
Will you be interested in expanding a bit of the topic to build a Jenkins pipeline in OpenShift or DigitalOcean?

**Comment by georgewbar** [comment]
* Could you elaborate more?
* Is it not just that DigitalOcean is only in the cloud?
* i tried googling openshift. It seems that it is not free.

**Comment by SophieHYe** [comment]
Hello,
Your PR will be merged. 
Using Openshift and DigitalOcean were just my suggestions to make the tutorial more complete. I was thinking if the Katacoda is not working, maybe you can try to use the Openshift (should be free) application image to construct a Jenkins Pipeline, or allow Jenkins to start slaves on DigitalOcean droplets. Jenkins provides some plugins for doing [this](https://jenkins.io/doc/pipeline/steps/openshift-pipeline/#openshift-pipeline-jenkins-plugin).

If you are interested in doing on Katacoda, please go ahead. Our concerns are about the original and difficulty of the tutorial. But it is hard to assess them at this point.  Maybe you will find some interesting and original stuff while you are doing this.  You can also make use of the feedback wanted as soon as you finish your tutorial.

**Comment by georgewbar** [comment]
@SophieHYe do you mean this openshift [https://www.openshift.com/products/online/ ](https://www.openshift.com/products/online/) ?

**Pull request merged**
