### PR TITLE
[Submission] Demo: Chaos testing in a deployed environment

### PR DESCRIPTION
**Pull request by nwessman**
# Demo submission: Chaos testing in a deployed environment

## Member 

Niklas Wessman (nwessman@kth.se)

Github: [nwessman](https://github.com/nwessman)

## Description

This demo aims to show how to use DevOps practice **Chaos engineering** to conduct **Chaos testing** in a deployed environment to test the robustness of the system. This demo will include the set up of a simple system and then go through the steps of setting up and conducting Chaos tests on the system while explaining the benefits of the practice. The tool used for the chaos testing will be **Chaos Toolkit**.

## Demo Video

[Chaos Engineering Demo using Chaos Toolkit](https://youtu.be/oAEgH2FEtwI)

## Demo code

[Chaos Engineering Demo](https://github.com/nwessman/Chaos-Engineering-Demo)

## Easter Egg

Switch to French subtitles for a fun time! :tada:

### CODE REVIEW

**Comment by nwessman** [comment]
Hi @khaes-kth, here is my Demo submission. You accepted my submission PR so I tag you here just in case you are in charge of it! :wave:

**Comment by bubriks** [comment]
## Pros
The demo is interesting, well made, and offers nice insight into the Chaos toolkit. Furthermore, the example was nice and easily understandable.

## Cons
Voice volume is inconsistent at times
It feels like a lot more could be said about this topic, however, with the time limitations in mind it is well structured.

**Comment by vickstrom** [comment]
Wow, I have never seen testing for microservice availability. This is great knowledge to have, which I will definitely take with me in the future. The structure of your video is good. Everything was nice and clear, and I understood everything. 

- I like how you explain the toolkits experiments in detail. However, From 1:20 to 2:00, I feel like there is a lot of information given at the same time. To help the audience to remember everything I would personally add definitions for example "steady state" and "probes". An alternative solution would also be to show the "steady-state" code while explaining what it is. I think either of them would be great!

- I like that you show the code. To visualize the servers, even more, providing an image with boxes representing the microservices and the communication between the user would help a lot! 

Haha, love the easter egg! Didn't know learning french was this fun :100:

**Comment by Agriad** [comment]
# Feedback
### author: arieltan@kth.se

## Positive
* Nice title screen  
I think it really fits well with the topic.

* GitHub repository  
It is a great idea that the code is shared so that people are able to test it themselves.


## Improvements
* Summary  
A summary or takeaway in the end would help tie up the video. If this is not possible perhaps it can be added in the description.

**Comment by hengque** [comment]
Interesting topic that I think many students don't come into much contact with during their courses.
+ Good pacing: not rushed and not too slow
+ Good video description
+ Overall it is clear what is being shown, what you are doing on a high level (even if details can't be explained due to the time limit)

- Audio is a bit inconsistent between different parts of the video. While it's never bad, it is quite noticeable and distracts a little
- Adding background music would be good to fill in the moments of silence in the pauses (for instance in the intro by the 5, 6 second mark; the silence is quite noticeable otherwise)

**Comment by oskstr** [comment]
### Feedback
Overall, a very interesting topic and a good demo. I have seen a lot of YouTube recommendations for talks on chaos engineering but I haven't look at any yet. 

Voice over (except some audio levels) are good. So are the subtitles. I wouldn't say it was the easiest to follow along, but I find it hard to pinpoint why. Perhaps using images/animations to show what you are trying to do in broad strokes would make it easier to understand.

The audio is a bit all over the place. Especially jumping from the intro to the code. I'm not an expert but perhaps normalizing the audio levels would fix that issue?

You say that the code can be found on your GitHub using the link in the description but that link doesn't work. Private repo?

**Comment by nwessman** [comment]
Thank you all for the very valuable feedback!

**Pull request merged**
