### PR TITLE
executable tutorial: proposal

### PR DESCRIPTION
**Pull request by hampfh**
# Assignment Proposal

## Title

Continuous delivery to GitHub container registry and containerization

## Names and KTH ID

- Hampus Hallkvist (hallkvi@kth.se)
- Melvin Jakobsson (melvinj@kth.se)

## Deadline

- Task 1

## Category

- Executable tutorial

## Description

This tutorial investigates how to use GitHub Actions to build a docker image and publish it into a GitHub container registry where it can then be downloaded onto servers and set into production. The tutorial will cover how to build the project as a docker image, how to setup the registry and how to deploy the image to the registry.
Elements of the tutorial:

- Containerization of an application
- Publishing the container to the GitHub registry: https://github.com/features/packages

**Relevance**
While cloud providers such as Google Cloud Platform, AWS, Azure etc provide great value, they come at a cost. Both in terms of the financials of running infrastructure on them but also in terms of security and privacy. Self-hosted continuous deployment is an option, but the setup can be complicated. The most important steps are the containerization of the application and integration of continuous delivery to a container registry, like the GitHub container registry.

### CODE REVIEW

**Comment by algomaster99** [comment]
Hey! Looks good to me. @javierron should the executable tutorial be also merged into this repository once I merge this PR?

**Comment by javierron** [comment]
@algomaster99 The deliverable for executable tutorial is a PR which modifies the README file by adding a link to the tutorial, and a link to the tutorial's repository. See https://github.com/KTH/devops-course/pull/2320/files

**Comment by algomaster99** [comment]
Merging!

**Comment by dvavd** [comment]
Hi, we have to give you feedback on this task and your deadline is today, which means our own deadline is within 48 hours. Unfortunately you did not reply to our emails and you have still not uploaded a link to your tutorial. Where can we find it?

cc: @algomaster99

**Comment by hampfh** [comment]
> Hi, we have to give you feedback on this task and your deadline is today, which means our own deadline is within 48 hours. Unfortunately you did not reply to our emails and you have still not uploaded a link to your tutorial. Where can we find it?
> 
> cc: @algomaster99

Hi, here's the submission: https://github.com/KTH/devops-course/pull/2575

**Comment by algomaster99** [comment]
@dvavd I guess it is resolved now? You have the task to give feedback to :D

**Comment by dvavd** [comment]
# Feedback

By David Streuli and Quang Minh Nguyen 

Your tutorial starts with a well-presented overview of what will be covered. The language is clear and concise. We found that an introduction of the problem that this tutorial solves was a bit lacking however and the assumed prerequisite knowledge could have been stated more clearly, as the reader may not be familiar with the topic. We think it wouldd have been valuable to include a short motivation why containerisation with Docker is useful.

We liked that you familiarised the user with the application and the setting before delving in to the technical aspects. You mentioned that the Dockerfile and the server directory are relevant. However, you did not mention that the Dockerfile was in the server directory, which was a bit confusing and initially led us to think that is missing. Also you could have included an appropriate title for this part. You introduced the popular command `ls`, which some readers may not be familiar with, which helps in following the tutorial. You then guide the user to open the file `index.mjs`, which is great to help the reader to understand the file structure and the content of the file. However, the lesser known commands like `cat`or `nano` to actually open the `index.mjs` file were missing and a clear explanation of the files' content would have been helpful.

The next step felt as one small step for mankind, but like a giant leap for a man. Seriously, the continuity from the previous step was a bit lacking and for a person unfamiliar with the topic it seemed unmotivated. Also, you mentioned that we can open the Dockerfile with the texteditor of choice, but we think this is actually not possible with Killercoda, bit we think you can set up an IDE in killercoda as an editor to help the user to edit files intuitively. This can be found in the killercoda setup.

The next part we really liked! You mentioned Docker Hub and linked it for further exploration and explained exactly why you chose the image in your specification. You gave guidelines and recommendations for good practice and the steps. In the following step, we felt a bit confused. You mention copying over things, but it was unclear where to we are copying these things and why this is necessary. Based on this description, we think it is not clear what to specify in a different environment with different dependencies. Subsequently, you make a good job explaining the purposes of CMD for specifying the command to run the application and EXPOSE to indicate the ports the container will use. This step was easy to follow, though we think it could benefit from briefly mentioning how to adjust the port if a different one is used. Adding a note about when EXPOSE is particularly helpful (e.g. when using Docker Compose) would also have added more depth to the explanation.

The last section for the build command was also clear, making sure that users understand the use of the `-t` flag for tagging and the `.` for specifying the Dockerfile path. The run command `docker run -p 127.0.0.1:80:80/tcp -t myapp` was also well explained. However, we think you could have added a bit more context about the -t flag in the docker run command. Also, simplifying the port mapping explanation and adding a note about troubleshooting common issues would have been more beginner-friendly. Initially the check failed for us; it could be that we executed the tutorial poorly, but it might also be that some steps were not described well enough.

Overall, your tutorial gave us a solid foundation for understanding Docker and containerisation, with clear language and well-structured technical instructions. We liked the explanations of key commands and the overall flow for creating and running a containerised application. With a few enhancements such as improving the introduction, enhancing the continuity between steps and providing more beginner-friendly explanations, we believe that you could make the tutorial even better. In any case we enjoyed executing it and are more knowledgable about Docker now. Thanks!

## Disclaimer
I/We certify that generative AI, incl. ChatGPT, has not been used to write this feedback. Using generative AI without permission is considered academic misconduct.

**Pull request merged**
