### PR TITLE
Final essay submission  - Putting the hours on fun, not manual labor: Incorporating DevOps in the Video Game Industry 

### PR DESCRIPTION
**Pull request by wska**
Essay submission follow-up on PR #970. Contains the PDF file and an update to the README to better reflect the outline of the essay. Will receive feedback from PR #983 before final submission.

### CODE REVIEW

**Comment by wska** [comment]
@callmeGoldenboy Hi! Ready for feedback.

**Comment by callmeGoldenboy** [comment]
@wska Alright I will review it and post the feedback within the upcoming 24h :)

**Comment by callmeGoldenboy** [comment]
## General thoughts
Well written essay. The video game industry is very big so it was interesting to read how they implement DevOps techniques to improve quality and reduce development time. As someone who likes to play video games, this gave me a good overview of the impact DevOps can have in game industry. 
## Strengths 
* The essay is self contained. It has all the information needed to understand what is presented
* Good use of figures to improve understanding as well as make the content more digestible 
* Visually appealing
* Good flow between the different sections. You start broad with DevOps in general, then proceed to describe how it is implemented in the video game industry and then give concrete examples.
* Good conclusion to the essay. You came back to the initial thought which was to save precious time from tidious work and put it where it matters. 
## Possible improvements
Here is a summery of the improvements that I think your work could benefit from.
* There are some grammatical errors/wrongly formulated sentences. You can find them under the "Syntactical errors" section. They are not many. Some are also mentioned directly in the relevant sections as improvement
* The introduction could use a little bit of improvement. Since it's the section that precedes everything, it is important that it is well written and attention grabbing. I have more specific examples in the Introduction section below.
* In the "Sample cases of DevOps adoption" section you have 1 or 2 paragraphs that are a bit long. Could be a good idea to split them up in smaller and more digestible chunks. Try to keep it between 3-10 lines.  
* It might be a good idea to not have anything other than the title and your names on the first page. I know it's a small essay but I think having a clean structure is still important.
* It might be a good idea to include an abstract. But seeing as the word count is already above 2000 as it is, you might need to remove certain parts in order to fit it in. 

### Syntactical errors
Here are some grammar errors that I spotted:

#### "DevOps in video game development"
* on the second last paragraph it should be "Video games as an entertainment, however,  ~~has~~ have a more ..." 
* Also in  the paragraph after that it should be "...terminated due **to** failing said core requirement"
* change "time on things which ~~one~~ are subjectively"


#### "Electronic Arts"
* Change "they had a dedicated developers that was charged with operating the build system" to something like "they had dedicated developers, charged with operating the build system".
* "would simply ~~to~~ fall to someone else"
* "previously were driven primarily ~~driven~~ by specific"
* " ...~~yet~~ all these mistakes were also". "Yet" should not be used there.


## Feedback for the different sections

## Introduction
This is the first section the reader stumbles upon so it dictates the interest the reader will have on the rest of the essay. Therefore, it is crucial to have a captivating introduction. This is the section that I feel needs the most improvement. Below are some of the changes that I think could improve the quality of the introduction.
#### Suggested improvements
* In the very first sentence you say "The video game entertainment industry has grown immensely and at the same time, it becomes increasingly more complex to create". I suggest adding something like "... and simultaneously it has become increasingly more complex to create high quality games". Ending it with "create" feels a bit off.
* "The cost of creating a game can now cost many millions" to something like "Creating games can now cost upwards of millions of dollars". Or even better if you have a clear tangible number on the upper bound of the cost ($250000 for a small indie game as per your source)
* "..and the importance of being first on the market is crucial" to something like "..and being first on the market is continuously  more decisive"

This are just suggestions I think you should consider. However, I do understand that the word count could be a limiting factor.


## Background
Very good background. It has all the relevant information and concrete examples of how DevOps has affected the video game development cycle. Background is supposed to be the backbone of the essay and give the reader all the relevant information to understand the rest. You did that well. This makes the essay self contained and all the important parts are presented.
### "DevOps"
I do not have anything to add here. I think it is well written and gives a good background to DevOps. It builds as the foundation to why DevOps could be a great tool to improve the video game development pipeline. 

### "DevOps in video game development"
You follow up the previous section about DevOps with this section which is specifically about DevOps in video game development which I think was well thought. You describe the differences between software development and video game development specifically and how the different aims they have also impacts the difficulty in setting up the processes. This gives the reader a better perspective and emphasizes the impact that DevOps could have on video game development, which is the core of your essay. 
## Sample cases of DeveOps adoption
This was the most interesting section as you gave concrete examples of the methodologies adopted in video game development. You also use figures to convey the impact adopting DevOps techniques has had on the company which further accentuates the importance of DevOps in this industry.
I like how you brought examples from two companies that are on different ends of the spectrum. On one hand you have EA which is huge billion-dollar company, and on the other hand you have Butterscotch Shenanigans which is a small team studio. It was a good idea to do that since it further shows that regardless of the size of the company, DevOps techniques can have a huge impact.

## Discussion & conclusion
Concise conclusion to the essay. I especially liked how in the introduction you mentioned how competitive the industry is and the here in the discussion you came back to it and emphasized how the time saved by DevOps techniques becomes invaluable. This further underlines the importance of DevOps and gives a nice full circle conclusion to your essay. Well done. 
#### Possible improvements
* By freeing up precious hours ~~by utilizing~~ through the utilization of modern DevOps methodologies

**Comment by wska** [comment]
Thanks for the feedback! We will make some adjustments according to your feedback and make another commit for the final submission.

**Comment by ChangGabriel** [comment]
Thanks for the feedback! We have now acted on the feedback we got from @callmeGoldenboy and have now commited the final essay submission. @Deee92

**Comment by ChangGabriel** [comment]
Here is a list of changes made after the feedback and we are ready grading:

# Changelog after Feedback
### General changes
- Fixed minor spelling errors and grammatical flaws
- Made the title page its own page
- Decided to not include an abstract due to the word limit
### Introduction
- Rephrased the sentence "The video game entertainment industry has grown immensely and at the same time, it becomes increasingly more complex to create"
- Rephrased some sentences to be more captivating
- Improved the section to be more captivating in general
### Sample cases of DevOps adoption
- Some paragraphs were too long. We split the paragraphs into smaller and more digestible chunks
### Discussion & conclusion
- Rephrased a sentence to be more concise and clear

**Comment by SophieHYe** [comment]
Thanks for your final submission. We will grade your work on this version. Thanks!

**Pull request merged**
