### PR TITLE
Essay Proposal: Comparing the three big cloud platforms

### PR DESCRIPTION
**Pull request by bckfilip**
# Assignment Proposal

## Title

IaaS: The Battle of the Clouds

## Names and KTH ID
  - Filip Bäck (filbac@kth.se)

## Deadline

Deadline 5

## Category

Essay

## Description

My proposal is to write an essay about the three big cloud platforms, namely AWS, Google Cloud, and Microsoft Azure. The essay will contain an introduction to cloud platforms, how each of the big three corporations work with their respective cloud platforms as well as a comparision between the three in regards to functionality among other things.

### CODE REVIEW

**Comment by khesoem** [comment]
@bckfilip Thanks for this relevant proposal. We have already had several similar proposals in this course, such as https://github.com/KTH/devops-course/pull/1079. So, I have to close this one.

**Comment by bckfilip** [comment]
@khaes-kth Hi and thanks for the feedback. Could I do an alternative angle on the same topic?
Such as:
1) the evolution of IaaS within DevOps?
2) the evolution of a certain cloud platform(AWS, GCP, MA, etc)?
3) The impact of IaaS on DevOps?
4) How the evolution of DevOps impacted the development of cloud platforms? 

Option 4) is my preferable choice. Let me know if this would be OK, thanks.

**Comment by khesoem** [comment]
@bckfilip Hi,

Sure! Option 4 works. Just make sure that you go into details as much as you can.

**Comment by bckfilip** [comment]
@khaes-kth thanks for the reply. I will! Uploading a new PR tomorrow morning.

**Pull request closed without merging**
