### PR TITLE
Week 4: Feedback Proposal

### PR DESCRIPTION
**Pull request by Pesteves2002**
# Assignment Proposal

## Title

Feedback on Presentation [Tensorboard: A suite of visualization tools to understand, debug, and optimize TensorFlow programs for ML experimentation](https://github.com/KTH/devops-course/pull/2442)

## Names and KTH ID

  - Diogo Melita (diogogm@kth.se)
  - Tomás Esteves (tmbpe@kth.se)

## Deadline
- Task 3

## Category
- Feedback

## Description
We want to provide feedback to Mateus and Marco's presentation on [Tensorboard: A suite of visualization tools to understand, debug, and optimize TensorFlow programs for ML experimentation](https://github.com/KTH/devops-course/pull/2442)

**Relevance**

Allow the presenters to receive some feedback before the presentation.

### CODE REVIEW

**Comment by MateusMarinheiro** [comment]
@Pesteves2002 @d-melita  Yes, I accept your feedback and am willing to address it

**Comment by javierron** [comment]
@Pesteves2002 Thanks for the proposal. Will you have time to provide the feedback before today's presentation? Or have you already done it?

@MateusMarinheiro

**Comment by d-melita** [comment]
@javierron Hi Javier! Yes we will have time. We have the feedback prepared and we already sent it to Mateus and Marco. It is now just a matter of making it "oficial". We can do this in 5 min as we just need to copy and paste on the PR of their presentation proposal.

**Comment by d-melita** [comment]
@javierron Hi again. We have just uploaded the [feedback](https://github.com/KTH/devops-course/pull/2442#issuecomment-2357898306) on their PR. We thought we needed to wait for this PR to be merged before providing the actual feedback. It’s done now. I’d like to mention again that Mateus and Marco were already aware of the feedback yesterday, as it was ready.

**Comment by javierron** [comment]
@Pesteves2002 Great! Please make another PR referencing the feedback to acknowledge the submission

**Pull request merged**
