### PR TITLE
Presentation : robot framework and end user test

### PR DESCRIPTION
**Pull request by paulinev-kth**
# Assignment Proposal
Robot framework and user test 

## Names and KTH ID

- Pauline Vaillant (paulinev@kth.se)
- Asim Jarrar (asim@kth.se)

## Deadline
Task 1

## Category
Presentation

## Description
Presentation of robot framework

### CODE REVIEW

**Comment by Deee92** [comment]
Hi @paulinev-kth, please update your README to add more details about the presentation, such as its description.
Also, please add your README to the correct folder - `contributions/presentation/week2-testing-and-CI/`

**Comment by paulinev-kth** [comment]
I think that Asim Jarrar doesn't have a canvas Id

**Comment by monperrus** [comment]
FYI, `*.robot` is a file type known by Github:
https://github.com/robotframework/robotframework/search?l=robotframework

An opportunity for an empirical study.

**Comment by monperrus** [comment]
@asja17 if you want to be graded, you must appear in Canvas. This depends on Ladok. What's the status of your Ladok registration?

**Comment by asja17** [comment]
Hi!

I have today become aware that something is wrong with my registration at this course.
So I will today write to the Student support and ask them to correct this misstake,
as I have been admitted to the course and also participated in lectures and labs.

BR
Asim Jarrar
________________________________________
Från: Martin Monperrus ***@***.***>
Skickat: den 1 april 2022 10:30
Till: KTH/devops-course
Kopia: Asim Jarrar; Mention
Ämne: Re: [KTH/devops-course] Presentation : robot framework and end user test (PR #1611)

@asja17<https://github.com/asja17> if you want to be graded, you must appear in Canvas. This depends on Ladok. What's the status of your Ladok registration?

**Comment by asja17** [comment]
Hi!

Now I am registered in Ladok as well.

BR
Asim Jarrar
________________________________________
Från: Martin Monperrus ***@***.***>
Skickat: den 1 april 2022 10:30
Till: KTH/devops-course
Kopia: Asim Jarrar; Mention
Ämne: Re: [KTH/devops-course] Presentation : robot framework and end user test (PR #1611)

@asja17<https://github.com/asja17> if you want to be graded, you must appear in Canvas. This depends on Ladok. What's the status of your Ladok registration?

**Pull request merged**
