### PR TITLE
Feedback proposal - Tutorial: Integrate DataDog in existing app

### PR DESCRIPTION
**Pull request by majate**
# Feedback - Tutorial: Integrate DataDog in existing app

## Members
* Sebastian Fagerlind - sebene@kth.se - @sebberh
* Maja Tennander - majate@kth.se - @majate

## Proposal
We want to give feedback to the tutorial "Integrate DataDog in existing app" (#972)

### CODE REVIEW

**Comment by khesoem** [comment]
@majate 
Note that the PR you are going to give feedback on is not a Demo, it is a executable tutorial.

**Comment by majate** [comment]
> @majate
> Note that the PR you are going to give feedback on is not a Demo, it is a executable tutorial.

Oh, I think my head was too occupied thinking of the video demo my partner and I are working on when I wrote this PR. 😄 We do know that it is a tutorial that we will give feedback to. I will update the header of the README for the final submission.

**Comment by khesoem** [comment]
> I will update the header of the README for the final submission.

Good, please remember to do so.

**Comment by evkade** [comment]
The tutorial is ready for review at https://www.katacoda.com/andreeva/scenarios/datadog-tutorial ! :)

**Pull request merged**
