### PR TITLE
Presentation submission : DevOps adoption in large Enterprise through Continuous Testing

### PR DESCRIPTION
**Pull request by Renugaa**

### CODE REVIEW

**Comment by Renugaa** [comment]
Hi Khaes.!

As per the feedback from the professor we have updated our kth id and presentation content. Could you please look after that and let us know if anything is needed.  Week 3 presentation #984.

// Renu and Megha

**Comment by Renugaa** [comment]
Hi, 

I mistakenly committed to the same branch as the presentation. Please ignore it. I will create a new pull request. 

Thanks,
Renu

**Comment by gangwalmegha** [comment]
Hello @SophieHYe,
We have created a new pull request, as we have updated the kth-id (from ved.megha to gangngwal@kth.se)and the content of the presentation. Our old PR is #984. Can you please check this new PR?

**Comment by gangwalmegha** [comment]
Hello @SophieHYe, @khaes-kth ,
We have created this new pull request as in my old merged PR #984, I didn't have a kth id. Now I have kth-id (ved.megha@gmail.com to gangwal@kth.se) that's why we created a new PR. Please can you look into this new PR and let us know if anything needed.

**Comment by gangwalmegha** [comment]
Hello @SophieHYe, @khaes-kth ,
We have created this new pull request as in my old merged PR #984, I didn't have a kth id. Now I have kth-id (ved.megha@gmail.com to gangwal@kth.se) that's why we created a new PR. Can you merge this PR  so that I will have a task assigned to gangwal@kth.se?

**Comment by gangwalmegha** [comment]
@khaes-kth ,
I did not have kth-id in my old PR #984. Now I have kth-id so I have created this new PR. Can you look into this PR and merge it so that I will have this presentation task assigned to my kth id(gangwal@kth.se).

**Comment by khesoem** [comment]
Hi @gangwalmegha ,

Two points:

First, you should not change [three files](https://github.com/KTH/devops-course/pull/984/files) as you are doing in this PR.
Second, instead of adding a new directory named `renanb-gangwal`, you should rename the old directory `renanb-ved.megh` to `renanb-gangwal`. We do not want to have two proposals for your group after merging this PR.

Easiest Solution: remove your forked repository. Fork deveops-course repository again. in the newly forked repo, rename the directory. Create a new pull request.

Please let me know if you need more help.

**Pull request closed without merging**
