### PR TITLE
Repeat Essay Submission: Ethics of Canary Testing

### PR DESCRIPTION
**Pull request by JustFredrik**
# Assignment Proposal

## Title

Re: Ethics of Canary Testing: Users as Guinea pigs

## Names and KTH ID

Fredrik Svanholm (svanhol@kth.se)

## Deadline

May 31

## Category

Essay

## Description

I intend to dive into the Ethics of partially rolling out new version of services to users both in order to validate performance but also to measure and compare user behavioural changes between versions. Discussing this aspect both in free and payed services.

### CODE REVIEW

**Comment by JustFredrik** [comment]
Here is a Changelog of my changes:

- Added references to many statements.
- Removed several statements where no supporting reference could be found.
- Specified statements that they were originating from me and my own thoughts when no supporting reference could be found but I still thought it was of value and a key part of the essay.
- Added old references to statements in the text where a reference supported the statement but it had no reference in the prior version.
- Removed duplicate/repeated (probably uncaught copy-paste error) sentence in 2. What is Canary testing
- Added commas in multiple longer sentences to improve flow.
- Split up some long sentences into two smaller sentences in multiple areas.
- Added two references to Feature flags in 2. What is Canary Testing.
- Added reference for Risk Analysis as good mitigation.
- Fixed broken reference.
- Rephrased sentences to read better.
- Changed capitalization of canary testing to be consistent across all mentions in the text. (previously it was written as Canary Testing, Canary testing or canary testing) 
- changed opt-in and opt-out to always be written with '-'. (previously was sometimes written as opt in and opt out or opt-in and opt-out)
- Changed effect to affect in some sentences.
- Many minor changes such as adding 'the' in front of 'users' or fixing small mistakes. 
- Fixed a sentence that ended abruptly in Potential Ethical Concerns.
- Added "hypothetically" to an example to indicate that it is just a made-up hypothetical scenario.
- Changed ethically bad to non-ethical in 6. Conclusion

**Comment by Deee92** [comment]
Hi @JustFredrik, please resolve the conflicts so that your PR can be merged.

**Comment by JustFredrik** [comment]
Hi @Deee92 I've fixed the conflict, the build error seems to have to do with updating Canvas grading which I don't think (?) I can resolve.

**Comment by Deee92** [comment]
Hi @JustFredrik, thanks! Can you also rename the file with the revised version (e.g., Revised_Ethics_Canary_Testing) so that it's easier for the grader to distinguish from the original one?

**Comment by JustFredrik** [comment]
Hi @Deee92 , both old and new version are now in the PR. Build still fails at Upade Grades in Canvas.

**Pull request merged**
