### PR TITLE
Presentation proposal for week 6: Docker and its implementation

### PR DESCRIPTION
**Pull request by jrutqvist**
In collaboration with @Pontus-Broberg

### CODE REVIEW

**Comment by gluckzhang** [comment]
Hi @jrutqvist @Pontus-Broberg , thanks for the PR. In order to avoid being general, I would suggest focusing on the third part in your outline: the implementation and Docker's differences from a VM. You could still introduce Docker and its usage in the beginning, which should not take too much time.

**Comment by jrutqvist** [comment]
Hi @gluckzhang!

Yes we could do that! Should we change the proposal to reflect that and resubmit the PR?

**Comment by gluckzhang** [comment]
> Hi @gluckzhang!
> 
> Yes we could do that! Should we change the proposal to reflect that and resubmit the PR?

That would be nice. Please directly update this PR instead of resubmitting one. Thanks :)

**Comment by gluckzhang** [comment]
Hi @jrutqvist , I find that there have been 6 presentations already in week5. Do you mind to reschedule your presentation to week6? Based on previous experience, doing 7 presentations per week is still a bit tense.

**Comment by jrutqvist** [comment]
That is fine with us, I'll change it when I update the pull request!

**Comment by jrutqvist** [comment]
@gluckzhang I have updated the PR with the requested changes! 😄

**Comment by gluckzhang** [comment]
Thanks @jrutqvist , the PR has been accepted!

**Pull request merged**
