### PR TITLE
Executable tutorial proposal: CI for Python with unittest using Github Actions

### PR DESCRIPTION
**Pull request by elmaxe**
# Executable Tutorial: CI for Python with unittest using Github Actions
## Members

Maja Tennander (majate@kth.se) [Github](https://github.com/majate)

Axel Elmarsson (axelelm@kth.se) [Github](https://github.com/elmaxe)

## Proposal:
This tutorial will show you how to set up CI for a Python project with unittest tests and linter using Github Actions.
The code base will be simple.
There will also be a section about why CI is good.
We plan writing it on medium.com

Our previous PR (#1214) was not approved, so we changed to Python and hope that it is okay.

### CODE REVIEW

**Comment by khesoem** [comment]
@elmaxe and @majate Good luck with the task.

I recommend you remove the "there will also be a section about why CI is good" part (or make it super short) and make the testing process a bit more complicated.

**Comment by majate** [comment]
> @elmaxe and @majate Good luck with the task.
> 
> I recommend you remove the "there will also be a section about why CI is good" part (or make it super short) and make the testing process a bit more complicated.

Thanks for the recommendation @khaes-kth! What do you mean by “make the testing process a bit more complicated”? That we should use more complicated features of the testing framework and explain how to do so, or something else?

**Comment by khesoem** [comment]
> What do you mean by “make the testing process a bit more complicated”? That we should use more complicated features of the testing framework and explain how to do so, or something else?

I did not have any specific change in mind. I just wanted to say that by removing (or shortening) the "CI is good" section, you will have more space to work on the testing process.

**Comment by Spycsh** [comment]
Hi @khaes-kth , I would like to give a feedback on #1230. My feedback PR id is #1256 .

**Pull request merged**
