### PR TITLE
Essay: A/B testing

### PR DESCRIPTION
**Pull request by cpiehl1**
### Members
Name: Carl Piehl

Mail: cpiehl@kth.se

Github: [cpiehl1](https://github.com/cpiehl1)

Name: Johan Henning

Mail: johennin@kth.se

Github: [johennin](https://github.com/johenninn)

### Proposal:

An essay about how A/B testing is performed by companies with large user bases. The following are some points we might touch on:

- Theoretical: What is A/B testing? Mostly on a conceptual level but might include some statistics if it's appropriate
- Technical: What tools are used in A/B testing and how are they orchestrated?
- Impact: What problems is A/B testing used for and what effect does it have?
- We might also explore some of the differences in the approaches used by different companies.

We will base our essay on the large number of articles, papers and blogs where companies describe how they perform A/B testing. Some examples below:

[Netflix](https://netflixtechblog.com/its-all-a-bout-testing-the-netflix-experimentation-platform-4e1ca458c15) \
[Spotify](https://engineering.atspotify.com/2020/10/29/spotifys-new-experimentation-platform-part-1/) \
[Airbnb](https://medium.com/airbnb-engineering/experiments-at-airbnb-e2db3abf39e7) \
[Facebook](http://sigops.org/s/conferences/sosp/2015/current/2015-Monterey/printable/008-tang.pdf)

### CODE REVIEW

**Comment by SophieHYe** [comment]
Hi,
Thanks for proposing A/B tests and indeed is very related to DevOps. Many students from past years have done this before.

Could you please also make a novelty/original statement about your essay?
How different is your essay compare to the past work on the A/B tests.
Would you narrow down your scope in A/B tests, which aspects will you focus on, the theory, the tools and the best practises? 

Thanks!

**Comment by SophieHYe** [comment]
Hi, 
Your essay and presentation proposal looks great to me. However, could you please make two separate PRs for this two tasks. This would be very helpful for us to track your tasks.  When you created two issue, you can assign me as the reviewer. Thanks!

**Comment by SophieHYe** [comment]
I have deleted the duplicated presentation proposal. Now the essay can be merged.

**Comment by iriediese** [comment]
Giving feedback for this, as per #1121

**Pull request merged**
