### PR TITLE
Essay: Comparison of Azure, AWS, and GCP based on DevOps

### PR DESCRIPTION
**Pull request by MDRezaulHasan**
I deleted the demo readme file. Now it has only one file which is an essay readme. Please let me know if I need any change.

### CODE REVIEW

**Comment by MDRezaulHasan** [comment]
@khaes-kth please check our PR and let us know if we need any changes. Thank you

**Comment by cesarsotovalero** [comment]
@MDRezaulHasan LGTM. I'll merge!

**Review by cesarsotovalero — APPROVED** [review]

**Comment by MDRezaulHasan** [comment]
Thank you

**Comment by khesoem** [comment]
Thanks @cesarsotovalero

**Comment by KallePettersson** [comment]
Hi, was told by a TA to mention that I will be giving you feedback on this assignment! Please ping me on GitHub whenever you guys are ready to receive feedback :) #1087

**Comment by MDRezaulHasan** [comment]
Ok, we will ping you

**Pull request merged**
