### PR TITLE
Updated demo length to be exactly 3 minutes

### PR DESCRIPTION
**Pull request by fwallb**
# How to get coverage reports for a GitHub repo

### Contributors:

Sara Damne - [damne@kth.se](damne@kth.se) - [@damnePers](https://github.com/damnePers)

Frida Wallberg- [fwallb@kth.se](fwallb@kth.se) - [@fwallb](https://github.com/fwallb)

## Motivation
Testing is important aspect in software development. In DevOps, it is important with continious integration and deployment. This ongoing, neverstoping process requires easy access to valuable information such as the percentage of covered code, and what part of the code that lacks tests. This is important in order to verify that the code does what it is supposed to do. By adding a badge displaying the percentage of covered code to the first page of the repo, it is easy for everyone to get access to that valuable information and act on it. Generating a more extensive report via Clover can show where tests are needed in a more detailed way. Clover reports can show parts of functions that needs tests, and what parts of the projects that are in most need of tests, and much more. The combination of the badge and the report is a good base for a project.

## Description
The demo shows 
- how to setup Maven and Travis for a basic Java project,
- how to set up a badge on the repo's first page with the help of CodeCov,
- how to generate a Clover report for the repo.

### Link to GitHub repo
[demo-badge-setup](https://github.com/damnePers/demo-coverage-setup/blob/main/README.md)

### Link to YouTube video
[How to add code coverage badge + report using codecov and clover](https://www.youtube.com/watch?v=i-0lTgYovg8&ab_channel=SaraDamne)

### CODE REVIEW

**Comment by elmaxe** [comment]
Good job! :)

Positive:
- Clear voice over
- Good intro
- Interesting and useful content

Improvements
- Perhaps linking to the repo in the description so you can take a look at how you set up the repo and code (and not having to manually navigate to the repo).
- When displaying commands to run you should perhaps add a background to make it much easier to read the command (I don't think white text with outline is enough)
- Perhaps you should think about showing what is only necessary. Is it necessary to show the whole screen when showing what code you should write in your file? Perhaps you could only show the code (zoom in) etc

**Comment by iriediese** [comment]
Nice demo. Good subtitles, voice-over and content. Easy to follow. 
I like that you show the steps, and the README.md in your repo is very welcome.
For an improvement, you could maybe write something in the description of your video (maybe link the repo, for example).

**Comment by MDRezaulHasan** [comment]
Great Work.

1. Voice cover is clear
2. Nice presentation
3. Clear code concept

Improvements:
Unable to read Build log which might be good for listener.

**Comment by mans-andersson** [comment]
# Demo day feedback
## Summarizing thoughts 
Overall it was difficult for me to find things that I think you should change
since the video is very good and gives a professional impression. Below 
follows some things I think could be improved.

## Add introduction?
I feel like it would be nice to get a brief introduction that quickly explains what 
code coverage means and why it is a good metric. 
This would make it clear why the topic is very relevant to 
DevOps. Although I do understand that it 
it may be difficult to fit into the video since 3 minutes is very short.

## Youtube description
There should be a description for the video on Youtube to make the video independent
of the course context. The code repo that is linked in the pull request contains 
very good, detailed instructions so adding a link to it would be great.

**Comment by kittytinythai** [comment]
## Feedback
Overall I think it was a very simple and yet informative video demo on how to set up Codecov for a project hosted on Github. I have listed the strengths and some suggestions for improvement below. Otherwise, good job 👍 
### Strengths
- Simple to follow
- The narrative was in a good pace and the instructions were clear
- Good summary in the ending
### Suggestions for improvement
- Change font color of the command in 1:55 and 2:03, it was a bit difficult to read the command in white
- Add link to your example repo in the video description

**Comment by felix-seifert** [comment]
# Feedback

From the video demos I watched till now, the content of your demo was the one which I could understand the easiest and immediately transfer it to my work. Voice, subtitles, pace, graphics, duration, they all are very nice.

However, I have some minor change requests. I did not try to investigate the whole test coverage topic but I am quite sure that you do not need Maven and/or Travis to use it. Maybe say that you chose Maven and Travis but also mention that these are not the only options. Furthermore, the title should show which technologies you used because test coverage is not only limited to Java.

Additionally, it is always nice to have a code repo where viewers can see which code you implemented. Maybe it exists. However, link it in your video description that people can easily find it.

**Pull request merged**
