### PR TITLE
Open source proposal: SaltStack Slack Bot

### PR DESCRIPTION
**Pull request by emetha**
# Open-Source Proposal

## Members
1. Emelie Tham (etham@kth.se)
2. Philip Wester (phwe@kth.se)

## Proposal
Creating a [SaltStack](https://github.com/saltstack/salt) Slack bot. 

## Description
SaltStack supports a SecOp orchestration of the DevOps toolchain by acting as a configuration manager as well as allow for remote execution. 

We want to create a Slack bot that will notify the user of the result of SaltStack's state runs. If time permits, perhaps allow sending commands from Slack as well. As of now, SaltStack has an API that allows for Slack integration, however, there seems to be no bots that make use of it. A slack bot would be preferable instead of directly calling the SaltStack API. This is because of two main reasons:
1. It is easier to communicate with a bot than with the API.
2. We can configure the presenting format from the bot to suit the user needs. (ie. include extra/less information, highlight important parts).

This implementation will be written in Python with the API of the open-source community Salt software.

Our motivation for this project is simply to learn more about the security aspects of DevOps by working with a SecOps tool like SaltStack. Seeing that Slack is a popular communication tool used for projects gave us our inspiration to create a Slack bot.

### CODE REVIEW

**Comment by SophieHYe** [comment]
Hi,
Thanks a lot for your PR, that's a very novel and interesting topic to explore SaltStack (SecOps).
Your idea seems meaningful and doable. But your description is very general, we cannot provide detailed comments based on that. 
Could also please add more information:
-Your motivation for implementing a bot
-The functional difference between using slack API  and the bot
-The major benefits of using a bot
-How does it related to the DevOps.

**Comment by emetha** [comment]
@SophieHYe Hi! We added some more information on our proposal (written in both the PR description and ReadMe). Hopefully, this answers your questions :)

**Comment by emetha** [comment]
Hi! My partner and I are wondering if we can start working on this PR, or if we need to extend more on our proposal? @SophieHYe  @cesarsotovalero

**Comment by cesarsotovalero** [comment]
Hi @emetha, thanks for the information added. I'll merge your PR. 
Good luck!

**Pull request merged**
