### PR TITLE
Demo Submission: Calico policies in Kubernetes

### PR DESCRIPTION
**Pull request by rbratfors**
This is our final submission for our demo.

### CODE REVIEW

**Comment by nour95** [comment]
Hi, Can I give you feedback?

**Comment by rbratfors** [comment]
Hi @nour95, go right ahead!

**Comment by adbjo** [comment]
Hello, interesting topic, I would like to give some feedback!

**Comment by veggiemonk** [comment]
I will give feedback

**Comment by Kappenn** [comment]
Thanks everyone! go ahead! @adbjo @veggiemonk @nour95 :)

**Comment by jrutqvist** [comment]
I will give feedback as well!

**Comment by sashikanthr** [comment]
I will give feedback to this demo.

**Comment by veggiemonk** [comment]
|                                             | Yes | No | Remarkable |
|-------------------------------------------- | ----|----|-------------|
|The demonstration screencast is clearly motivated (why it matters for Devops?) | **Yes** X | No | Remarkable |
|The demonstration screencast is difficult to do | **Yes** X | No | Remarkable |
|The demonstration screencast is original | **Yes** X | No | Remarkable |
|The demonstration screencast is sublime (eg visually appealing) | **Yes** X | No | Remarkable |
|The demonstration screencast contains an easter egg | **Yes** X | No | Remarkable |
|An accompanying Github repository has been made (optional) | **Yes** X | No | Remarkable |

Good demo.

## Good points

* The demo was clear
* The pace was good.
* The voice over is very good and speaken clearly.
* The UI of the web app shows what is happening :+1:
* The introduction says that it will demo the ease of use of Calico in a kubernetes cluster and that is exactly what it is

## To improve

* The explanation details were quite basic
* A demo that only show how easy it is to use something is good, could you show how hard it is to do the same thing without ?

Conclusion: :+1:

**Comment by nour95** [comment]
Hi, 
The demo is good. I also think that the topic you choose is important and clearly motivated in the readme file.

I have just found it difficult to understand the relationship between the visual representation  of pods shown in 0:45 ( and how it became updated later when you change the policy) and what you wrote in the terminal. 
However, after watching the video 3 times, I understand that the UI/visual representation is the pod the 4th pod that “is not shown” as you mention in 0:35 (I hope that I understand correctly).  
I think since, this pod is important, can you try to show it or something or maybe emphasise it little more?

**Comment by sashikanthr** [comment]
It was a nice presentation overall. I like how you visually reprsented the nodes FrontEnd, BackEnd and Client. The narration was good and I was able to follow the entire demo. Also, it is good to have a github link for reference to have a quick look sometime. Only point I have is the subtitles are missing in the video and the YouTube generated once aren't right throughout. If you can, then that would be a good addition I believe. :)

Great work!

**Comment by jrutqvist** [comment]
Really great that you show the graphics to describe what your changes are actually doing, this is so often lost in demonstrations and really makes it easier to grasp. The presentation way clear and clean over all, well done! A good addition would be a quick look in one of the YAML files to see how the policies are specified, but it is of course hard to fit this in the short time available.

**Comment by adbjo** [comment]
Good job on this demo guys, i like it!
Feedback:
- Great quality voice-over, pace is good, mic is good, and enunciation is good.
- Add subtitles since the speaker has an accent, non-swedish speakers may not hear some words, for example "files" is pronounced "fills" at 0:18.
- The accompanying Github repository is helpful.
- Funny easter egg.
- Explanations could be more detailed, explain what the commands are doing or explain more explicitly.

**Pull request merged**
