### PR TITLE
Essay: Gitlab CI vs Github Actions

### PR DESCRIPTION
**Pull request by nikolim**
Hand in of the essay: Continuous Integration Comparison: GitHub vs GitLab

### CODE REVIEW

**Comment by tobiasgg** [comment]
Hello! I find this topic interesting, could I provide feedback on this essay?

**Comment by nikolim** [comment]
Hey @tobiasgg sure, would be nice to get some feedback. But I am not sure since it's already merged?

**Comment by tobiasgg** [comment]
I asked the TA's and received the following answer:
'You can give feedback on a task that has already been finished. However, remember in that case if you submit it two days after that task is finished, you will not get the score for "timeliness".'
So I think its fine! :)

**Comment by tobiasgg** [comment]
# Feedback for essay "Gitlab CI vs GitHub actions"

This essay compares the Continuous Integration functionality of the two platforms GitHub and Gitlab. All in all this essay is well written, relevant and educational.
## High level strengths and weaknesses of the essay

### Strengths
* The language used in the essay is clear and concise.
* The two CI platforms are compared in many different relevant aspects.
* The essay compares the platforms not only theoretically but also practically using a case study.

### Weaknesses
* Parts of the comparison is at a somewhat high level and lacks a bit of a deeper discussion.
* The essay is a bit "diplomatic" at times, where no clear standpoint in favor of any of the two platforms is presented.
* There are multiple small language errors in the essay.


## Feedback per section

### 1. Introduction
The introduction is concise and gives a good overview of the topics the essay will discuss. The purpose of the essay is also clearly stated.

### 2. Background
The background gives a clear description of both GitHub and GitLab. A short summary of the histories of the companies is given which is nice as it is very relevant to their place in the CI-tool market today. However, the sentence-structure in section **2.1** is slightly "choppy". There are alot of short sentences which have a negative impact on the flow when reading. This is **not** a general theme in the essay, though.

### 3. Core components and concepts
This section contains a good explanation of pipelines and the hierarchy of pipelines, jobs and dependencies. In the part where caching is mentioned it could potentially be good to mention the purposes of caching in this setting, as it might not be completely obvious to the reader.

### 4. Comparison
This part is the core of the essay that contains a discussion on the differences between the two platforms in different aspects.

In section **4.1 Runners** the word "runners" is used but not defined. It might be expected from the reader to be familiar with this, but that was not the case for me. So an improvement here could be to briefly define the word to make it clearer to the reader. On the same theme, this section assumes previous knowledge of Docker and Containers. To make this section more complete it could have been good to explain these concepts. 

In section **4.2 Functionality** the author compares the functionality of the two platforms at a high level. In this section I would have liked a somewhat deeper discussion. There is also a broken LaTeX link as indicated by the `??` in the first sentence.

The section **4.3 Configuration** there is a deep discussion regarding the different configuration methods of the two platforms that takes into account things such as beginner friendliness, templates and GUI. This part is very good and nuanced.

The images of the GUI's of the two platforms (Figure 1 & Figure 2) are very nice, although it would be better if they appeared earlier in the essay. I know that image placement in LaTeX can be quite hard and it might be the case that the author wanted to place the figures "higher up" but that the rendering caused them to end up where they are. I recommend using the `[H]` flag in LaTeX to make sure that figures appear where they are placed in the text.

In general, I would have liked the author to include a short conclusion after each segment indicating which of the two platforms can be considered better in that specific aspect.  

### 5. Case study
I think it is great that the author compares the two platforms in a case study in addition to just comparing them theoretically. However, in sections **5.1** and **5.2** it would be nice if the author would include a short summary with the pros and cons of the experience using the specific platforms. 
### 6. Conclusion and reflection
The conclusions are clearly stated and show a nuanced picture of the learnings of this study. The author has also included a personal reflection which I think is very good.
## Structure
The essay is split up into many small parts, which keeps the reader's attention and makes the essay interesting and easy to read.

The sections and subsections are well defined and follow a red thread. There are also no "unnecessary" sections.

## Language
The language of the essay is adequate and the essay has a nice flow which makes it comfortable to read. The author manages to use professional language without making the essay dry or too formal.

However, I did notice a some language errors:
1. In the **introduction** the word "specific" is misspelled in the last sentence.
2. In section **2.1** the word "an" is missing in the sentence `"He started Gitlab as [an] open source project alone besides his job. "`
3. In section **2.1** the word "to" is missing in the sentence `"Gitlab is therefore often referred [to] as a leader in the CI/CD field."`
4. In section **2.2** there is a grammatical error in the first sentence where "created" is used instead of "create". 
5. In section **2.2** the word "led" is misspelled as "lead" in the sentence `"This lead to a significant decrease in their users, since many switched to the competitor Gitlab."`.
6. In section **2.2** there is a grammatical error in the sentence `"Nevertheless Github is by far the largest code hosting platform, with over 100 million repositories, 73 million users and employs current around 2500 people.
"`. Here "employs current around" should be changed to "currently employs around".
7. In section **2.2** the word "you" is missing from the sentence `"Github Actions allows [you] to run the code to automate development workflows."`.
8. In section **3** there the word "that" should be removed in the sentence `"Both platforms use some common concepts` ~~that~~ `to create a CI pipeline"`
9. In section **3** the word "secrets" is misspelled in the last sentence.
10. In section **4.1** the word "technologies" is misspelled as "technology's" in the last sentence.
11. In section **4.2** the word "of" is missing **and** the word "pipeline" should be in plural in the sentence `" Pipeline orchestration allows the creation [of] parent and child pipeline[s] which can then also be run concurrently."`.
12. In section **5.1** the words "the" and "image" are repeated in the sentence `"In the .gitlab-ci.yml we start by specifying` ~~the image~~ `the Docker image the pipeline should run in."`.
13. In section **5.1** the phrase "set up" is concatenated into one word, "setup", in the sentence `"Here we setup the Python environment by installing the required packages"`.
14. In section **5.1** the word "the" is missing from the sentence `"Afterwards we can define the test and [the] deploy job"`.
15. In section **5.1** the word "to" should be removed from the sentence `" Additionally we configure` ~~to~~` the deploy job to only run on the main branch."`.
16. In section **5.2** the word "pipelines" should be in possessive form, "pipelines'", in the following sentence`"Putting the file into this dedicated has the advantage that you can store several pipelines['] files in this folder, which are then automatically executed by Github."`.
17. In section **6** the word "little" should be removed in the sentence `"Gitlab offers slightly more functionality in the area of CI/CD than Github, gives slightly` ~~little~~ `more freedom in the configuration and might be the better choice if DevSecOps is important. "`


To avoid these kinds of errors in the future I recommend running the text through a spell and grammar checker. One very simple way is just to paste the entire essay into Google Docs, which has an excellent spell and grammar check feature. 

## Pointers to additional material

The following [article](https://www.lambdatest.com/blog/jenkins-vs-gitlab-ci-battle-of-ci-cd-tools/) discusses differences between Gitlab CI and Jenkins, which also is a very big platform in the scene. Furthermore, this [article](https://faun.pub/github-actions-vs-jenkins-which-should-you-use-d7ba6800e8bb) is similar, but instead compares GitHub vs Jenkins. It seems like a natural continuation of this study to also look at the other big actors in the CI-area. Therefore I would also like to point to the following [article](https://www.altexsoft.com/blog/engineering/cicd-tools-comparison/) which looks at some other CI-tools such as Jenkins, TeamCity, CircleCI and TravisCI and compares them in many relevant aspects.

**Pull request merged**
