### PR TITLE
Posted the video Link

### PR DESCRIPTION
**Pull request by nagavem**
Finished the demo video and posted the link.

### CODE REVIEW

**Comment by GiorgosTagkoulis** [comment]
Hi, I would like to give feedback.

**Comment by gynther-k** [comment]
I would like to give feedback on this demo.

**Comment by keivanm** [comment]
I'll give feedback on this demo

**Comment by cwinge** [comment]
I'll give feedbackto this demo :)

**Comment by Goradux** [comment]
I would like to give feedback!

**Comment by nagavem** [comment]
Thank you @GiorgosTagkoulis  @gynther-k  @keivanm 
Feel free to go ahead :)

**Comment by nagavem** [comment]
@cwinge  @Goradux  Thank you!!
Go ahead :)

**Comment by akhilyerrapragadaa** [comment]
I like to give feedback for this demo!

**Comment by nagavem** [comment]
@akhilyerrapragadaa  Sure go ahead :)

**Comment by Goradux** [comment]
Feedback:

Overall, displays a good use of a CI/CD tool, which is always nice to see in work. From some potential improvements, it would be nice to have some voice over the video with a bit more explanations. That could be quite helpful to those who do not have any prior understanding/experience of the systems in use here. Also, quite a bit of the screen time in the middle of the video is just background event without comments. Ideally, those could be either cut/sped up/have more subtitles. Otherwise, very nice music and quite enjoyable to watch! It was clear why this demo is useful, and it is very sublime.

**Comment by akhilyerrapragadaa** [comment]
Pristine demo presentation. Description per step was positioned well. Agreed to @Goradux regarding truncating the background event screen time. The end was very well presented. Serene music's a good thought and finally, it was well to the point.

**Comment by keivanm** [comment]
Nicely looking demo. I would've liked it to have a voice over though. Also more background info on the tools and how to set them up in the beginning. I want to know why I would want to use these tools :)

**Comment by gynther-k** [comment]
Feedback:

Very nice demo overall. Good choice of background music that makes the watcher in a happy mode. The content is understandable and the screencast is nice to watch. Possible improvements could be that it would maybe be good to lower the volume and speak about the actions sometimes.

**Comment by nagavem** [comment]
@Goradux Thank you for the feedback it is greatly appreciated!!
Coming to your points,yes voice over is something we have considered and maybe we will integrate it as you and @keivanm  have requested for it,we were just having some troubles keeping things in sync with voice and the subtitles(we also liked the background music we found way too much 😛 )

Also for comments regarding the screentime in the middle as the video this is something we will look into definitely.
Super glad to hear that you enjoyed watching it and found it useful 😄

**Comment by nagavem** [comment]
@akhilyerrapragadaa Thank you so much for the kind feedback we will definitely try to improve upon the point regarding the screen time.

**Comment by cwinge** [comment]
Feedback time :)

Overall the screencast was well done and quite interesting.

Something I think would improve it would be to include a short introduction in the beginning. Just some information saying what you are doing, why it is relevant to devops and what is used to accomplish the task. At the end, everything was clear as day, but it came gradually throughout. 

Just a minor detail, I feel like the background behind subtitles should be a 100% opacity, at least if the background is moving/different colors. e.g. 3:01, just to make it a bit less distracting.

Music should be credited.

-----

That was all for now :) gj!

**Comment by nagavem** [comment]
@keivanm thank you for the feedback!! Its a good point you bring up regarding why you would want to use these tools and to provide a brief intro to them,we will try to inculcate this into our update :)

**Comment by nagavem** [comment]
> Feedback:
> 
> Very nice demo overall. Good choice of background music that makes the watcher in a happy mode. The content is understandable and the screencast is nice to watch. Possible improvements could be that it would maybe be good to lower the volume and speak about the actions sometimes.

@gynther-k Glad to hear that you liked the background music and its nice to see its putting the viewer in the exact mood we had hoped to achieve. Thank you for the suggestions regarding sound quality and voice over we will definitely consider them in our edit for the final version 😃

**Comment by nagavem** [comment]
> Feedback time :)
> 
> Overall the screencast was well done and quite interesting.
> 
> Something I think would improve it would be to include a short introduction in the beginning. Just some information saying what you are doing, why it is relevant to devops and what is used to accomplish the task. At the end, everything was clear as day, but it came gradually throughout.
> 
> Just a minor detail, I feel like the background behind subtitles should be a 100% opacity, at least if the background is moving/different colors. e.g. 3:01, just to make it a bit less distracting.
> 
> Music should be credited.
> 
> That was all for now :) gj!

@cwinge Thank you so much for the kind feedback,glad to hear you liked it and found it interesting.  Thank you for listing out the areas of improvement we will definitely try to inculcate them in the final version. Also special thanks for bringing up the point about music used being credited,had totally forgotten that in the midst of submission will look into that immediately  :)

**Comment by GiorgosTagkoulis** [comment]
A really nice screen-cast for an interesting topic. The pace of the video is very good, the transition between the different screens (apps that you use) is smooth, and the background music adds a positive touch. Some comments for improvement are:

- It would be nice to give an overview at the beginning of the video of the steps that you are going to follow. Before you make the push and go to Azure I mean. So the viewer has a better understand of the process you follow.
- In some cases when the background is in black and white, it is a bit difficult to understand the subtitles without pausing the video. Maybe it's just me, I don't know. But I'd prefer a different style for the subtitles, with lower-case letters, and maybe bigger font. It's a matter of preference of course.

But overall, a nice demo!

**Comment by valsen** [comment]
I'd like to give some feedback too!

Nice job with this demo:) Very slick production, and I think you struck a really nice balance regarding the tempo of the screencast. My only critique would be that It would be nice if you had a short introduction (voice or on screen) so that the viewer gets a little better prepared for the actual demo and its purpose. You have a video description of course, but I think a short intro would add to otherwise very professional quality of your demo!

**Comment by nagavem** [comment]
> A really nice screen-cast for an interesting topic. The pace of the video is very good, the transition between the different screens (apps that you use) is smooth, and the background music adds a positive touch. Some comments for improvement are:
> 
> * It would be nice to give an overview at the beginning of the video of the steps that you are going to follow. Before you make the push and go to Azure I mean. So the viewer has a better understand of the process you follow.
> * In some cases when the background is in black and white, it is a bit difficult to understand the subtitles without pausing the video. Maybe it's just me, I don't know. But I'd prefer a different style for the subtitles, with lower-case letters, and maybe bigger font. It's a matter of preference of course.
> 
> But overall, a nice demo!

@GiorgosTagkoulis thank you so much for the feedback I am glad you liked our screen cast as a whole. Regarding the points for improvement the introductory overview is something most of you have requested us and as such we will look into it and do the best we can to fit something in the opening minute to better explain the flow.We will also look into the issue regarding subtitles,we too felt it might be an issue at certain points with regard to the opacity and will definitely look into this.

**Comment by nagavem** [comment]
> I'd like to give some feedback too!
> 
> Nice job with this demo:) Very slick production, and I think you struck a really nice balance regarding the tempo of the screencast. My only critique would be that It would be nice if you had a short introduction (voice or on screen) so that the viewer gets a little better prepared for the actual demo and its purpose. You have a video description of course, but I think a short intro would add to otherwise very professional quality of your demo!

@valsen thank you so much for the feedback and kind compliments we are very glad to hear that you liked our presentation. The introduction is something that we are definitely looking into.Thank you once again for calling it professional it is really motivating for us to hear the same about our work 😄

**Pull request merged**
