### PR TITLE
linusost-praneetk: Demo Proposal, Week 4

### PR DESCRIPTION
**Pull request by PraneetKala13**
# Assignment Proposal

## Title

DockerSlim: Make your container small and secure!

## Names and KTH ID

  - Linus Östlund (linusost@kth.se)
  - Praneet Kala (praneetk@kth.se)

## Deadline

- Week 4

## Category

- Demo

## Description

We will be showcasing how a container can be minified by a significant degree using DockerSlim. We will demonstrate 
how Docker and DockerSlim are used to minify or slimming an image so that the containerised image is ready for 
production, but in an optimised manner. We will show the difference in container image size and show that 
vulnerabilites have been reduced to make the image more secure.We will also demonstrate the easy of use of the 
Docker and Slim tools.

**Relevance**

DockerSlim is created by slim.ai, which has a GUI that we will showcase. It provides additional functionality like 
providing an SBOM, CVE scanning andadditional statisitics and insights. Everything is containerised these days and 
having "slim", optimised and secure containers are becoming more relevant. Before shipping to production, it is 
essential to secure your containers and this can be done by finding and reducing vulnerabilities in the software. 
Automating this process saves times and the slmi.ai GUI makes it easy to use. Gain insights into what’s actually 
in your containers with deep container analysis of layers, packages and metadata.

### CODE REVIEW

**Comment by Deee92** [comment]
Hi @PraneetKala13, please make your PR description consistent with the README of your proposal.
Also, update your proposal to resolve the following:
> (We are still discussing what to put into a 7 minute demo)

**Comment by PraneetKala13** [comment]
Hey @Deee92 . I have made the edits and resolved the comment in parenthesis. Let me know if anything else is unclear, thanks.

**Comment by Deee92** [comment]
Thanks @PraneetKala13, please also update the PR description to match the contents of the README.

**Comment by PraneetKala13** [comment]
Hi @Deee92. Please excuse my ignorance 🙈, but could you be more specific as to what needs to be updated. Is the description not thorough enough in the README or does the PR description need to change in the title of the PR?

**Comment by Deee92** [comment]
Hi @PraneetKala13, no stress! It's the markdown description for the PR (before our comments). I will update it for you.

**Comment by PraneetKala13** [comment]
Hey @Deee92. Ah, I understand now, thanks a lot. The first comment is meant to have the README text. We did try and change that when we created it but it was being weird. 

All good now, thanks again.

**Pull request merged**
