### PR TITLE
Executable tutorial proposal: Integrating docker in a Node.js app

### PR DESCRIPTION
**Pull request by bckfilip**
# Assignment Proposal

## Title

Dockerizing a Node.js application

## Names and KTH ID
  - Filip Bäck (filbac@kth.se)
  - Isac Haglund (isacha@kth.se)

## Deadline

Deadline 4

## Category

Executable tutorial

## Description

We would like to create a tutorial in Katacoda that shows how to create an Express server as well as to containerise with the help of Docker. The tutorial will explain basic concepts of building an Express server with Node.js with the required steps for it to work properly. Then, we will show how to deploy the application with Docker. The guide will contain an explanation of what Docker is and how it works, with explanations of how to configure a Dockerfile, explain what images and containers are, and the commands to demonstrate it. Additionally, we will address the most common commands used within Docker, such as run, build, ps, exec, etc,.

### CODE REVIEW

**Comment by javierron** [comment]
Hello @bckfilip thanks for the proposal. 

I don't quite understand the proposal description. Do you mean that you'd like to make a tutorial on "how to deploy a Node.js application in a Docker container"? If you do, that is relevant for the course.

However, building and deploying an app with Docker is is not a difficult enough contribution. I suggest that you either:
- Propose that the tutorial will give in-depth explanations of Docker deployment commands and Dockerfile instructions. 
- Find a specific feature of Docker, or a specific Docker-related tool, and explore it with some depth within your tutorial.

**Comment by bckfilip** [comment]
@javierron Hi and thanks for the feedback. We will extend our tutorial to give more in-depth explanations of commands/instructions.

**Comment by bckfilip** [comment]
@javierron Due to unforeseen circumstances(partner has fallen ill) we would like to extend the deadline to #4 instead. I hope that it is ok.

**Comment by javierron** [comment]
@bckfilip 
> Hi and thanks for the feedback. We will extend our tutorial to give more in-depth explanations of commands/instructions.

Sounds good, please update the description and mention which commands or instructions you will focus on.

> Due to unforeseen circumstances(partner has fallen ill) we would like to extend the deadline to https://github.com/KTH/devops-course/issues/4 instead. I hope that it is ok.

Since the PR has not been merged, this is ok.

**Comment by bckfilip** [comment]
@javierron 
Hello again. I have updated the description with additional information, which I hope will suffice.

**Comment by javierron** [comment]
Thanks! LGTM.

**Pull request merged**
