### PR TITLE
added link to repo used for the demo

### PR DESCRIPTION
**Pull request by ArnPellesGit**
Here's mine (Per Arn) and John Landeholt's (@landeholt) final PR for the demo we had today. This commit adds a link to the README, linking to the repo we used for the demo.

### CODE REVIEW

**Comment by ArnPellesGit** [comment]
> Readme is not correctly formatted Need exactly: ['Assignment Proposal', 'Title', 'Names and KTH ID', 'Deadline', 'Category', 'Description']
> 
> Got: ['Edited after demo on the 12/4-22:', 'Assignment Proposal', 'Title', 'Names and KTH ID', 'Deadline', 'Category', 'Description']

Figure we need to fix this @cesarsotovalero? I simply added a link to the repo we used for the demo, on top of the README.

**Comment by khesoem** [comment]
@ArnPellesGit Can you please fetch the upstream (KTH/devops-course:2022) to fix this?

**Comment by ArnPellesGit** [comment]
> @ArnPellesGit Can you please fetch the upstream (KTH/devops-course:2022) to fix this?

Yup. Will do sometime tomorrow :)

**Comment by ArnPellesGit** [comment]
Is this fine? @khaes-kth

**Pull request merged**
