### PR TITLE
jakobew-arenbro Essay proposal Task 3 - A/B testing

### PR DESCRIPTION
**Pull request by jakobewaldsson**
# Assignment Proposal

## Title

Challenges in Software A/B Testing

## Names and KTH ID

  - Jakob Ewaldsson (jakobew@kth.se)
  - Martin Arenbro (arenbro@kth.se)

## Deadline

- Task 3

## Category

- Essay

## Description

A/B testing is a common technique for evaluating the impact of changes made to software services such as websites and mobile applications. The basic principle is to randomly present users with one of two different versions (A and B) of the software, and comparing different user metrics between the different versions. This could for example be time spent in the application, number of interactions etc. Although the concept is simple, there are many practical challenges when performing A/B testing at scale. This essay will present and explain these challenges and possible solutions.

**Relevance**

An important part of the DevOps methodology is to acquire and evaluate user behavior and sentiment, however this can be a difficult task. A/B testing provides a framework for this evaluation and it is widely used in practice.

### CODE REVIEW

**Comment by khesoem** [comment]
@jakobewaldsson 
Please name more specific challenges that you have in mind. As this topic has been considered by other students before, we need to make sure you have something different in mind.

**Comment by jakobewaldsson** [comment]
@khaes-kth 
We are planing to write about issues with how to estimate long term effects of changes in A/B testing. Also how users interacting with each other can make it difficult to evaluate test results.

**Comment by khesoem** [comment]
Please also name a few specific techniques/tools/methodologies/algorithms that you are going to talk about

**Comment by jakobewaldsson** [comment]
We are going to talk about clustering as a solution to the users interacting with each other and modeling user learning as a solution to long term effects.

**Comment by khesoem** [comment]
Great! Try to be as specific as possible in your final essay.

**Comment by beatajoh** [comment]
@jakobewaldsson
Hello! Is it okay if me and @Emilcrafter give you feedback on this essay?

**Comment by jakobewaldsson** [comment]
@BeataJohansson absolutely

**Comment by beatajoh** [comment]
@jakobewaldsson Great, thanks!

**Pull request merged**
