### PR TITLE
Essay-mircoram

### PR DESCRIPTION
**Pull request by OmidMircoram**
# Assignment Proposal

## Title

How to secure your CI/CD Pipeline and why it's important. 

## Names and KTH ID

  - Omid Mircoram (mircoram@kth.se)

## Deadline

- Task 3: Monday, May 8 @ 17h Stockholm Time

## Category

- Essay

## Description

In this essay, I will discuss the what CI/CD pipeline breaches such as https://blog.gitguardian.com/codecov-supply-chain-breach/ is. I will focus on techniques such as mapping the attack vector(observing and monitoring), depency analysis, securing the pipeline with automated tools such as testing (unit, application etc), and credential management. To show an state of the art example, I will also have a section on machine learning integration. 

**Relevance**

With supply chain attacks becoming more popular, it's a good idea to have a good understanding of what supply chain security is and how devops can be used to make it more reciliant against attacks. It's also important for a devops engineer to be able to look at a CI/CD Pipeline and be able to pinpoint weaknesses.

[Essay submission available](https://github.com/OmidMircoram/devops-course/blob/essay/contributions/essay/mircoram/Essay-mircoram.pdf)

### CODE REVIEW

**Comment by SandZn** [comment]
Hi, thanks for the submission. Please resolve the conflicts.

**Comment by Taomyee** [comment]
# **Feedback**

I/We certify that generative AI, incl. ChatGPT, has not been used to write this feedback. Using generative AI without permission is considered academic misconduct.
## **1 High level**
### **1.1 Strengths**
- Clear structure: The paper is well-structured. It's easy for readers to follow.
- High relevance: The topic of the essay is highly relevant to the topic of DevOps.
- Inclusion of real-world example: The example of the CodeCov breach provides a practical perspective to the topic and illustrates the potential consequences of insecure pipeline. 
- Visual representation: The figures effectively help understand the essay.

### **1.2 Weaknesses**
- Unclear captions for figures: The captions for figures are confusing.
- No detailed explanation for figures: The essay only mentions what the figure are about, but lacks explanations to help understand the contents.
- Limited discussion of consequences of the exmaple: The essay uses the CodeCov incident as an example to illustrate the risks. But there's limited discussion about the impact of such breaches on organizations, customers, or stakeholders.
- Lack of a clear call to actioin: The conclusion only provides a general call but without specific suggestions

### **2 Feedback per section**

### **2.1 Introduction**
The introduction gives readers a clear overview of the topic and emphasizes the importance of securing these pipeliens. One suggestion is that you could add a brief explanation of CI/CD pipelines so that the readers unfamiliar with this concept can understand it.
### **2.2 CI/CD Pipeline Breach**
This section is quite clear and easy to understand. It relates the topic with 10 main risks published by Cider Security and focuses on the first, second, third and sixth risks, which are well-explained. The explanations are informative and highlight potential risks associated with each. In the subsection "Preventive Actions", practical measures are offered to counteract the vulnerabilities discussed before. Each preventive action is appropriately linked to the corresponding risks, providing a strucured approach to address the security risks.

### **2.3 The CodeCov Breach**
It's a good section to enable readers to realize the security issues of this topic from a real-world example. One suggestion is to make the caption of the figure about the timeline clear so that readers can know what the timeline is about directly.
### **2.4 Machine Learning in the Pipeline**
This section is a in-depth extension of the topic, introduing an interesting perspective on integrating machine learning in CI/CD pipelines. The explanation and advantages of MLOps in CI/CD pipelines are highly relevant to the topic and help readers obtain a wider insight to the topic. Similarly,  a more proper caption is needed for Figure 2.
### **2.5 Conclusion**
The conclusion effectively summarizes the key points throughout the essay and emphasizes the concerns to security of CI/CD pipelines. It reiterates what the role of a DevOps should be in this threats. One suggestion is that the conlusion now seems like a conclusion for each section discussed before. Including a more specific and actionable take-home could make the conclusion more informative for the readers.

## **3 Additional material**
Since it's a course related to DevOps, it will be a good choice to include a section that explores the DevOps tools for enhancing the security of CI/CD pipelines. [Here](https://about.gitlab.com/blog/2023/03/15/getting-started-with-gitlab-application-security/) is an example of GitLab's DevSecOps, which can perform secuity scans in CI/CD pipelines.

**Comment by OmidMircoram** [comment]
@Taomyee Thanks for the feedback! It is very constructive and unfortunatly most of them could have been solved/was included before I had to shorten it down to match the world limit. 

@SandZn I see that you're the assigned TA for this request. Am I supposed to change my essay and resubmit it before I can get a pass grade in canvas or should I wait for additional feedback from the TA's? Or maybe it is already passed? (I do not see a grade for "essay" in canvas) 

Thanks again for the feedback and thanks for the help

**Comment by SandZn** [comment]
Hi @OmidMircoram, you should wait for feedback in Canvas. We are in the process of grading the essays. The professor/TA who grades you will give you a "completed" or "repeated" answer.

**Pull request merged**
