### PR TITLE
Demo for feedback

### PR DESCRIPTION
**Pull request by eywoon**

### CODE REVIEW

**Comment by s1grun** [comment]
I want to give feedback to this demo.

**Comment by cwinge** [comment]
I'll give this demo some feedback :)

**Comment by klaraesr** [comment]
I want to give feedback to this!

**Comment by veggiemonk** [comment]
I will give feedback

**Comment by jzafar** [comment]
I would like to give feedback!

**Comment by stinalangstrom** [comment]
I would like to give feedback to this as well :)

**Comment by hittesharma** [comment]
I will give feedback.

**Comment by klaraesr** [comment]
Good job on the demo, Airflow seems interesting! I liked the motivation for Slack too. Here are some points I have feedback on:

-  Parts with only text could have bigger font and be written more formally
- Easter-egg is not really hidden
- Add to the description where your music comes from
- Introduce in the beginning what you will do in the demo, the steps you will take
- Why Airflow matters to DevOps could be further explained
- You could add some prerequisites, like where do I download airflow?
- What are you running your scheduler on? It would be nice with an example of what you can use Airflow on.
- At 0:46, I don’t understand the context. Where does this piece of code belong and why is it relevant?
- Explain where you are adding code and doing things, it helps to look at the repo but it’s hard to understand in the demo.
- Clarify where you are clicking in the demo, for example when creating the Slack connection

**Comment by s1grun** [comment]
Overall a very good demo, I really liked it and I haven't heard about Airflow before but cronjobs can be a big headache to maintain. 

I feel the demo is relevant to DevOps and is clearly motivated and the demonstration looks simple and very straight forward and has good visualization. 

Here's my feedback:
- Since I'm not familiar with Airflow I don't know what DAGs is so I had to google, maybe it would be nice to have a very short description for it.
- When you show how to add the Slack integration in Airflow maybe elaborate a bit what information is needed there. 
- When you show how yo set up a Slack app maybe have the subtitles colored (like the green color), it really blended in with the text on the website
- Regarding the subtitle, it would be nice to keep the same font size throughout the video if possible.
- On minute 3:02 in the text, I noticed one typo and possibly missing words:
  * typo: dependancies -> **dependencies**
  * ... **and** restart workflows 
  * ... you don't have **to** ...
- On minute 3:15 you're missing a comma at the beginning of the sentence:
  * So**,** when ...
- One of the criteria for the screencast is that it should be less than 3 minutes, you exceed over that time-limit.

But as I said I really liked the demo and the content is really good, I hope this feedback is helpful. :)

**Comment by JohanKJIP** [comment]
Interesting demo!

There are two main things I see that could be improved. Firstly, I think you could expand the introduction including why this matters to DevOps. 

Secondly, the subtitles are very inconsistent making them harder to read. I understand it is challenging when the colour of the background changes but I think it would be easier to read if they are similar in style throughout the whole video. 

Lastly, it would be interesting to know the capabilities of Airflow beyond this demo. For example, is it possible to use other services other than Slack for notifications?

**Comment by hittesharma** [comment]
A nice topic that I always wish to learn. You presented it well too. But I was expecting a bit more background on how you are able to get those visualisation mappings in Airflow GUI. Secondly, What technically you are supposed to do in detail for this demo should be informed in the introduction. Overall the viewer is able to grasp the basic idea.

**Comment by cwinge** [comment]
Feedback time :)

Overall I find that the content of the screencast was interesting and overall good. I think the general flow of the video is at a good pace and as a viewer it was not troublesome to grasp the information displayed.

I do however think the subtitles could be done better, mostly visually. The text is presented quite differently throughout the video. Text being over a cluttered background or several different colors can make it harder to read. Especially when not adding any stroke, or just a plain background. Examples at 0:57, 1:33

I feel like the zone captured by the recording software is a bit too zoomed in, this might be intentional though. Not really a required fix, but to me it just feels a bit weird being able to see half of a tab, or half of a message, etc. e.g. 1:49.

The music should be credited.

------

That was all for now :) gj!

**Comment by veggiemonk** [comment]
|                                             | Yes | No | Remarkable |
|-------------------------------------------- | ----|----|-------------|
|The demonstration screencast is clearly motivated (why it matters for Devops?) | **Yes** X | No | Remarkable |
|The demonstration screencast is difficult to do | Yes | No | **Remarkable** X |
|The demonstration screencast is original | **Yes** X | No | Remarkable |
|The demonstration screencast is sublime (eg visually appealing) | Yes | No | **Remarkable** X |
|The demonstration screencast contains an easter egg | **Yes** X | No | Remarkable |
|An accompanying Github repository has been made (optional) | **Yes** X | No | Remarkable |

Good demo.

I personally don't like music in demo video as it prevents me to focus on the demo, I would prefer a voice over but that's a personal taste and doesn't affect the grading.

## Good points

* very clear demo
* good pace
* the problem is explained well
* the solution is clear
* Writing a custom batch job for the demo

## To improve

*  I feel we are solving 2 problems here: running batch job and getting notified of the state of jobs. Maybe create 2 parts in the video ?
* A short description of DAG (directed acyclic graph) would have been nice
* I almost missed the slack notification, maybe doing something do bring the attention of the viewer to where the notification is on the screen?

Conclusion: remarkable

**Comment by jzafar** [comment]
Thanks for the Demo, I think the topic is very interesting. But you should add more info about your demo. Anyhow Changing audio with context is a good idea.
I found couple of things that can be improved 

- if you are using too much text then i think you should add some voice over as well because it's very hard to read without stopping the video.
- Subtitle speed is a little bit fast.
- Time 2:44 you are continuously pressing refresh button it seems you are expecting output but you are not getting that out put might be your code is broken somewhere. 
- Add slide for take home message.

**Comment by stinalangstrom** [comment]
Thank you for the demo and introducing me to airflow, it was very interesting. Here comes my feedback:

* Good motivation of why this matters, one can easily understand why this is interesting and relevant.
* When you press the refresh button it was a bit hard to understand what you expect to happen, you can be more clear on that.
* The pace is good, it was easy to follow along.
* It was easy to see what happened on the screen, the size of everything was very good.
* The subtitle format was a bit inconsistent, it would be nice to have almost the same throughout the whole video.

Over all, a very good and interesting demo. Well done!

**Comment by eywoon** [comment]
@jzafar 
Thank you so much for the feedback 😊
I will certainly add a voiceover. These subtitles seem to be causing a lot of issues and I will skip them in the revised version.

The refresh clicking is just to update the UI faster for the demo, it can be a bit slow without it. The tasks changing colours means they go from queued -> running -> success state.
The output will always happen in the background when each task is being executed. The tasks going green means that they ran with a success flag. 
Hopefully a voiceover will help explaining that as it's obviously not clear, but the outputs are essentially presented in the batch job, poking for files (kinda mocking how a ftp connection could be), merging the two files when they have been found (mocking file arrival, in the example they are always there) and then sending an alert to slack if the merging was successful. 

A task won't run until the task before it has succeeded so a job like this could get one file on Monday, the next one on Wednesday and finally then do the merger and alerting on the Wednesday. With alerting you wouldn't have to go and check the UI to see if the workflow has finished. 

Hopefully this helps, it's a very cool tool for exactly that kind of processing pipelines :)

**Comment by sonderangebot10** [comment]
Thank you for the Demo! Airflow seems very interesting. The feedback:
- Interesting and new topic
- Easy to follow along
- Sometimes feel like there's too much text and voice over could be added
- Not really sure what DAG (Directed acyclic graph) is, could have explained more.

Overall, really good demo! 👍

**Comment by eywoon** [comment]
@s1grun @sonderangebot10 @stinalangstrom @veggiemonk @cwinge @hittesharma @JohanKJIP @klaraesr 
Thank you so much for the feedback everyone. Much appreciated and very helpful. 😀🎉

The main points to address summarised were:
- Video quality: I have now added voiceover as was the plan originally, that removes the not so great looking subtitles. I also fixed the weird cropping of the screen.

- Motivation and relation to DevOps: Extended the problem description and how Airflow is used to solve a specific problem, namely, getting rid of overhead when it comes to workflow management.
- Technicality: I put more thorough details of how to set everything up in the repository.

- Added an explanation of what a DAG is, as it’s referenced a lot in the video

**Pull request merged**
