### PR TITLE
Presentation Proposal: Pulumi - what, why and how

### PR DESCRIPTION
**Pull request by zehaoj**
# Assignment Proposal

## Title

Pulumi - what, why and how

## Names and KTH ID
  - Zehao Jiang (zehaoj@kth.se)

## Deadline

week5 (Apr 19)

## Category

Presentation

## Description

I am planning to give a presentation on explaining what Pulumi is, what are its key features, why we want to use it and how. Then I would compare it to Terraform with aspects such as Language support, Infrastructure Reuse and Modularity, Validating, etc.

### CODE REVIEW

**Comment by zehaoj** [comment]
@cesarsotovalero Hi! Could you check this? It's pretty close to task2 deadline

**Comment by javierron** [comment]
Hello @zehaoj thanks for the proposal.

Demos and presentations must fit in the topic of the targeted week. I f you plan to present next week, you should change your topic to something related to Infrastructure as Code. 

Also, for demos and presentations we do not use the task deadlines (1-5), instead the deadline is on the day that you plan to present.

**Comment by zehaoj** [comment]
@javierron Hi! Thanks for the feedback, I totally forgot that...
I've changed my proposal to more IaC-related and would like to present it next week. Some feedback on this would be really helpful. Thanks!

**Comment by javierron** [comment]
@zehaoj Thanks!

This tools are both very relevant for this week's topic.

However, a comparison would be difficult to make without knowing what the purpose of the tools is, and what is the need behind them. I suggest that you focus on explaining Pulumi, it's main features and motivation, and then use that to make the comparison to Terraform.

**Comment by zehaoj** [comment]
@javierron Hi! Thanks for the feedback! I've modified it and hope it's okay now!

**Comment by javierron** [comment]
Looks great. Good luck!

**Pull request merged**
