### PR TITLE
yimingj: presentation proposal week 9

### PR DESCRIPTION
**Pull request by Taomyee**
# Assignment Proposal

## Title

Chaos engineeing: The history, principle and importance

## Names and KTH ID

  - Yiming Ju (yimingj@kth.se)

## Deadline

- Week 9

## Category

- Presentation

## Description

I'll cover the history, principle and importance of chaos engineering.

**Relevance**

Chaos engineering enables teams to test system resilience and identify weaknesses before the failure in real world scenarios. In this way, the engineers can take precautions in advance.

### CODE REVIEW

**Comment by javierron** [comment]
Hello @Taomyee, this topic is interesting. Can you elaborate with an example how they "pose a threat to the security and efficiency of DevOps processes"?

**Comment by Taomyee** [comment]
Hello @javierron, after reviewing the previous topic, I realized it may not be suitable for my presentation. I have decided to switch to this new topic.

**Comment by javierron** [comment]
Hello @Taomyee. Chaos engineering is a relevant topic. However, the title is too broad and suggests a non-technical presentation.
Given that the presentation should be done already on Monday, I suggest that you come to the lab today and discuss directly with the TA team to find an appropriate focus for this task.

**Comment by Deee92** [comment]
Hi @Taomyee, we discussed in the lab that you could present some "good" academic papers on chaos engineering. You can start with searching on scholar.google.com and dblp.org.
Recent papers published in ACM and IEEE journals and conferences would be good. The PhD thesis of @gluckzhang on chaos engineering could also be a good start: https://www.gluckzhang.com/ 😄  

Make sure to include the technical contributions of the papers you present, and summarize their key findings.

**Comment by Deee92** [comment]
Please make a new PR with your revised proposal, we are closing this one.

**Pull request closed without merging**
