### PR TITLE
Feedback proposal

### PR DESCRIPTION
**Pull request by Limph1**
# Assignment Proposal

## Title

Feedback on "Setting Up a Dashboard using Splunk"

## Names and KTH ID

- Arber Limani (arberl@kth.se)
- Jonas Liley (liley@kth.se)

## Deadline

- Task 3

## Category

- Feedback

## Description

We would like to give feedback for [this executable tutorial](https://github.com/KTH/devops-course/pull/2451).

### CODE REVIEW

**Comment by sofiabobadilla** [comment]
Hi @Limph1 ,
Please find someone to work on this feedback proposal.

**Comment by Limph1** [comment]
Found one!

**Comment by Limph1** [comment]
> Hi @Limph1 , Please find someone to work on this feedback proposal.

Found one!

**Comment by sofiabobadilla** [comment]
Wonderful!

Merging :)

**Pull request merged**
