### PR TITLE
Course Automation submission

### PR DESCRIPTION
**Pull request by LeeBadal**
This is a submission for #959 

The github action runs automatically if accepted into 2021, check the README for detailed information.

We are aiming for remarkable in the aspect of well-documented repo ( in this case the [README](https://github.com/johennin/devops-course/blob/kth_version/contributions/course-automation/badal-johennin/README.md) in our fork )

### CODE REVIEW

**Comment by johennin** [comment]
@cesarsotovalero our submission is ready for a review/merge!

**Comment by SophieHYe** [comment]
Hi,
Thanks for the excellent work. For the security consideration, we will kindly suggest you remove all the code outside your PR to your fork repo. 
A good ReadMe and info to point out to your fork repo is enough. Thanks!

**Comment by johennin** [comment]
Hello @SophieHYe, so do you want us to not merge the code but only the readme file and then link to the code in a fork so you know how to implement it in the future?

**Comment by SophieHYe** [comment]
Hi @johennin, yes, please move the code to the fork repo.

**Comment by LeeBadal** [comment]
@SophieHYe I have removed the code from the PR and placed them in a new branch. Updated the readme so that it directs to the a new branch in our fork.

**Comment by SophieHYe** [comment]
Thanks for your update. I am now merging your PR.

**Pull request merged**
