### PR TITLE
Week 7 

### PR DESCRIPTION
**Pull request by chrissap543**
# Assignment Proposal

## Title

ELK: A Cohesive Logging Toolchain

## Names and KTH ID

- Christopher Sapinski (sapinski@kth.se)
- Kankanit Suppataratarn (kankanit@kth.se)

## Deadline

- Week 7

## Category

- Scientific Paper

## Description

The paper "[Building a real-world logging infrastructure with Logstash, Elasticsearch and Kibana](https://hdms.bsz-bw.de/frontdoor/deliver/index/docId/5021/file/elk_paper_patrick_kleindienst.pdf)" writes about how a company was having difficulty merging log files between all of their micro-services. They rectified this problem using ELK. 

**Relevance**

This paper is relevant because it details step-by-step how to create your own logging infrastructure. ELK is a widely used open-source toolchain for merging logs into more human-readable formats.

### CODE REVIEW

**Comment by sofiabobadilla** [comment]
Hi @chrissap543 

I cannot find the venue of the paper. Even though it is interesting, it is not good for this task. 

@algomaster99  could you share your thoughts on this as well?

**Comment by algomaster99** [comment]
I agree with you, @sofiabobadilla ! The topic is more relevant for Infrastructure as code week. Moreover, the paper is more of a tutorial than a scientific paper. A scientific paper is supposed to tell a problem and probably a solution for it.

@chrissap543 sorry for being so late in responding. Would it be okay if you can present something else?

**Comment by chrissap543** [comment]
We understand; we have two backup papers we are interested in. We would like to do the first one more but if it isn't good, then we'll do the second. The first is [A Survey on Deploying Prometheus and Grafana for Application Monitoring](https://www.jetir.org/papers/JETIR2401076.pdf) and the second is [A Survey on Observability of Distributed Edge & Container-Based Microservices](https://ieeexplore.ieee.org/document/9837035). Would it be possible to present on Thursday instead of Wednesday so we have ample time to prepare?

**Comment by algomaster99** [comment]
@chrissap543 the second one is good. Yes, you can present on Thursday. Please submit a PR for that. I will close this.

**Pull request closed without merging**
