### PR TITLE
Reschedule the presentation to week3: Automation Testing

### PR DESCRIPTION
**Pull request by MDRezaulHasan**
In week3 I want to present a Test automation topic.

### CODE REVIEW

**Comment by gluckzhang** [comment]
Hi @MDRezaulHasan , as you are going to reschedule your presentation to week3, you should move `week2/mrhasa` to folder `week3` (`mv ...` then commit). In the current PR you created folder `mrhasa` in both `week2` and `week3`.

**Comment by gluckzhang** [comment]
Hi @MDRezaulHasan , you will give the presentation next. Please note that the current title (automation testing) is too general, you should focus on a concrete topic in automation testing. For example:

- automation testing -> too generic | an introduction to the most popular automation testing frameworks -> good
- unit testing -> too generic | unit testing on web applications -> good

Please update the `README` before next lecture, when you submit your slides :)

**Comment by MDRezaulHasan** [comment]
Hello Zhang, I updated the read me file with specific topics ´is that
automation testing using selenium framework.

**Comment by gluckzhang** [comment]
@MDRezaulHasan , thanks! In order to be merged into master, you should submit another PR. Preferably pulling the updates into your forked repo (or simply forking it again) -> creatig a specific branch -> add the updates and create a PR.

**Comment by MDRezaulHasan** [comment]
I am sorry I do not understand. Can you tell me in details?

**Comment by gluckzhang** [comment]
Hi @MDRezaulHasan , sorry because the PR has been merged, I missed the update notification.

I think the easies way to do that is: directly [modify your `README` on the webpage](https://github.com/KTH/devops-course/edit/master/contributions/presentation/week3/mrhasa-mjza/README.md) on this repo, and choose "Create a new branch for this commit and start a pull request." at the bottom of that page.

**Comment by MDRezaulHasan** [comment]
Ok, I will do it. Can you tell me how to present the presentation tomorrow
or just submit and create a new pull request. Thanks in advance and take
care

**Comment by gluckzhang** [comment]
@MDRezaulHasan you will present it tomorrow using zoom as usual. The streaming url of the lecture will be announced in advance here: https://github.com/KTH/devops-course/issues/316

**Comment by MDRezaulHasan** [comment]
Thanks

**Comment by MDRezaulHasan** [comment]
Hello Zhang,
I created a new branch in the presentation->week3->mrhasa-mjz folder and
update the readme file.

**Pull request merged**
