### PR TITLE
Feedback Proposal: Canary Deployment Past, Present and Potential Future

### PR DESCRIPTION
**Pull request by iabdelkareem**
# Assignment Proposal

## Title

Feedback on [Canary Deployment: Past, Present and Potential Future](https://github.com/KTH/devops-course/pull/2335)

## Names and KTH ID

  - Ibrahim Abdelkareem (iaiab@kth.se)

## Deadline

- Task 3

## Category

- Feedback

## Description
I'd like to submit feedback for [this essay](https://github.com/KTH/devops-course/pull/2335)

### CODE REVIEW

**Comment by javierron** [comment]
Hello @iabdelkareem, thanks for the proposal.

**Comment by bbaudry** [comment]
hi @iabdelkareem ,

Please submit the feedback as soon as possible.
The essay was submitted one week ago.

Thank you
Best
Benoit

**Comment by iabdelkareem** [comment]
Thank you @bbaudry and apologies for the delay. I'll submit it tomorrow by maximum.

**Comment by iabdelkareem** [comment]
Hi @bbaudry I submitted the feedback 2 days ago in the essay's PR.

**Pull request merged**
