### PR TITLE
Demo submission jadlers

### PR DESCRIPTION
**Pull request by jadlers**
I've added links to the demo on YouTube as well as a link to the project repository on GitHub.

> ## Screencast link
> 
> [https://youtu.be/yPdwBRndwPY](https://youtu.be/yPdwBRndwPY)
> 
> ## Project repository
> 
> The repository can be found [here](https://github.com/jadlers/bollsvenskan-api).

### CODE REVIEW

**Comment by georgewbar** [comment]
I would like to comment on this PR

**Comment by xmas92** [comment]
I can give feedback.

**Comment by Anthial** [comment]
I would like to give you feedback :)

**Comment by eywoon** [comment]
I would like to give feedback

**Comment by klaraesr** [comment]
I would like to give feedback as well!

**Comment by Callet91** [comment]
I would like to give feedback here to

**Comment by xmas92** [comment]
# Mandatory Criteria Check

- [X] The screencast is 3-5 minutes
- [X] The screencast contains subtitles which are clear and in proper English
    - Very good use of Youtube's CC.
- [X] The screencast contains a good and concise take-home message at the end
    - >Monitoring a service gives you great insight which can help both resolving issues and developing the next feature.
    - Nice and concise formulation. Maybe a bit general (but probably better for it), as the demo only shows how to use monitoring and does not necessarily show a scenario where it is useful. It is however discussed in the introduction. Also as the demo seems to be aimed at someone with at least basic knowledge about tools like `Docker`, `Node.js`, etc. one can also expect the viewer to have some idea of concrete problems that this type of monitoring can solve.

# Graded Criteria

* The demonstration screencast is clearly motivated (why it matters for Devops?) 
    * I really thing it is. The short introduction stating with
      > Making the monitoring available closes the gap between developers and operators, which is what DevOps stands for.

       and then continuing to show how it is implemented in code (Dev) and can be visualised and monitored (Ops).
* The demonstration screencast is difficult to do
    * This seems very relative with regards to the viewers own knowledge.
    * For someone who has used these kind of tools before it seems like a rather simple process to get it working (not necessarily to master it and get it right).
    * While for someone newly introduced to web development having to integrate multiple tools might be rather challenging to do.
    * I do not think anything needs to be changed with regards to the screencast.
* The demonstration screencast is original 
    * I do not have time to dig deep into this but both some Google and Youtube searches show multiple articles and videos covering `Monitoring with Prometheus and Grafana`, most do however seem to be tutorials or introductory material, not showing it in action.
    * You also have the live demo, (would've worked better for the original demo day). Maybe it would be possible to show in the screencast how you can use this Monitoring to identify an actual problem. (Might be hard, require a lot of work due to 5 min time limit). But showing it in **real** (but contrived) action would differentiate it from all other material.
* The demonstration screencast is sublime (eg visually appealing) 
     * Overall I think everything is clear.
     * I really like the flow-chart application used to show the overview. (What is that flow-chart app btw?)
     * The text (intro) and especially the code could use a bit larger font as it is a little too small to be conferable while viewing on my laptop.
* The demonstration screencast contains an easter egg
    * Not sure. This category seems pretty contrived overall.
* An accompanying Github repository has been made (optional)
    * Yes.
    * Maybe something about the monitoring can be added to the project readme. Or a link to a wiki page or something that explains how monitoring is used in the project.

**Comment by klaraesr** [comment]
Nice demo! The motivation for monitoring was good and I like the application, which gave a clear context to the demo.

- You could add some more information on Prometheus and Grafana and how they help monitoring.
- How do you add Grafana to your project and how do you create a dashboard? (In terms of steps taken in Grafana, how to write the queries was clear)
- Overall I think the demo mostly explains things that are already set up, and not so much the steps taken. But the explanations are good.
- The take home message could be elaborated, and also add something about the tools you use not just monitoring in general.
- I didn’t find an Easter egg, was there one?

**Comment by Anthial** [comment]
## Feedback 

Monitoring is clearly a relevant DevOps topic since it straight up is a part of the DevOps loop. The short motivational introduction is well-stylised (I reckon it looks really good), although much like the ending take-home message, no CC subtitles are available. This is something that I would assume could be a problem for some people, so adding CC to the introduction and ending is something that I would love to see. 

The screencast is both easy to understand and beautiful. The way the relevant aspects are moved through step-by-step, each part delivered in small enough chunks that before the next part is moved on to one has had time to process the first. The detail which is shown when using Grafana paired with the strong take-home message really emphasises the importance of utilising monitoring when working on projects.  

There is a repository and there is also a link to the Grafana dashboard that can be played around with which is nice to see the actual monitoring in real-time. I like it because it really helps if one would want to decide whether or not this way of doing monitoring would be useful for one’s own projects. 

Overall I think you’ve done a great job. I don’t really see anything that I think (other than what has already been stated) could be improved.  

I tried to find any easter egg but I couldn’t find any, so if you had one in there, you truly hid it well :)

**Comment by eywoon** [comment]
First of all I really like the demo, it’s clear and concise. Has good motivation for context and a take home message. It flows very smoothly and is at a good pace. The flow chart is really nice. 

It’s hard for me to tell if it will be difficult to do as I’m no familiar with the stack. But it looks fairly straight forward

Live demo is a cool addition. 

Good job

**Comment by georgewbar** [comment]
## Feedback overview
* The demo is sublime and have very high quality (see below for some issues that could be fixed). 
* It is clearly motivated at the beginning why Monitoring is relevant to DevOps.
* It was a very nice interaction in the part 0:18 to 1:19 that clarifies the different parts of the demo.
* The demo is also in the 3-5 minutes range, which fulfills the requirement for time constraint.
* There are good subtitles.
* There is a good take-home message at the end (see below for some modifications).
* It was very nice and very technical on how to embed monitoring tools in the code.

## Feedback using template
Using the template for `pass` criteria, in my opinion, the following criteria are fulfilled:
* The demonstration screencast is clearly motivated. Yes.
* The demonstration screencast is difficult to do. Yes.
* The demonstration screencast is sublime (eg visually appealing). Remarkable (with some modifications, see below).
* An accompanying Github repository has been made (optional). Yes (with some modifications, see below).

## Some issues that could be fixed
* The code in the demo is very small. Zooming in on the interesting parts could help clarify the interesting parts together with marking them as is already done in the demo.
* You could write the title "Take home-message" on the last slide to make it clearer. You could also summarize mention the tools as examples in the take-home message.
* It is a little bit ambiguous to me how to replicate the demo using the Github repo. Generic instructions are given to get the code up and running for replication. It could help with an example. It could also help to add the prerequisites of what is needed to be installed to get the code up and running.

**Comment by Callet91** [comment]
# Monitoring with Prometheus and Grafana #809

|  | Yes | No | Remarkable |
| ------ | ------ | ------ | ------ |
| The demonstration screencast is clearly motivated (why it matters for Devops?)| Yes| | |
|The demonstration screencast is difficult to do| | | Remarkable |
|The demonstration screencast is original|Yes|||
|The demonstration screencast is sublime (eg visually appealing)| | | Remarkable |
|The demonstration screencast contains an easter egg| |No| |
|An accompanying Github repository has been made (optional)| Yes | | |

### Motivation:
**The demonstration screencast is clearly motivated (why it matters for Devops?)** 
The student clearly motivates how the demo relates to DevOps in the opening of the screencast. 

**The demonstration screencast is difficult to do**
The demo does not combine a bunch of DevOps tools, but instead focuses on a deep dive into Prometheus on a real life scenario. 

**The demonstration screencast is original**
When searching for "Prometheus and Grafana" on Youtube, there seems to be many videos on how to set this up but I think this video contributes to the topic since it shows how to implement it on an existing project. 

**The demonstration screencast is sublime (eg visually appealing)**
Easy to follow along and it is great with the introduction that explains everything. 

**The demonstration screencast contains an easter egg**
I could not find any, but who am I to say that their is none. 

**An accompanying Github repository has been made (optional)**
It has, however, it is not that thorough. Update it to ensure you get an remarkable on the demo. 

### Suggestions on changes/additions
- Add a title slide with student name and the project name. I think it is redundant, Martin and Benoit said that it should be there.
- Update repo with a more thorough readme.

**Comment by jadlers** [comment]
@xmas92 @klaraesr @Anthial @eywoon @georgewbar @Callet91 

Thanks a lot for the feedback you provided! As mentioned on the lecture I've really gotten well written constructive feedback, thanks again and well done :clap: 

I'll take all of suggestions and comments into account. The main points you pointed out, which I am going to address, are:
1. **The small font.** Both in introduction/ending and when showing the editor.
2. **The `readme`** in the repository needs to be updated. The project has been moving forward quickly the past weeks and is in definite need of an update.
3. **Take-home message.** I'll look over to see if I can find ways to improve it.

As for the Easter egg I'm sorry you searched for it in vain, there was none. I'll see if I can add one in the revised version.

**Comment by jadlers** [comment]
> I really like the flow-chart application used to show the overview. (What is that flow-chart app btw?)

It's the website [excalidraw.com](https://excalidraw.com/). A tool I found recently and have been using extensively ever since.

**Comment by sonderangebot10** [comment]
Thank you for the Demo! The monitoring topic seems very insightful. The feedback:

- Interesting and easy to follow presentation
- The font is too small, but I can see that it has already been noticed
- Everything looked straightforward to replicate for myself

Overall, really good demo! 👍

**Pull request merged**
