### PR TITLE
Course Automation Proposal: Make Pull Request shell script

### PR DESCRIPTION
**Pull request by luuuk**
# Assignment Proposal

## Title

Add a shell script (`mpr`, for "make pull request") which when invoked from CLI creates a new PR for students to the
devops course repository. This script will live in a new directory (`/scripts`) in the root of the devops repo.

## Names and KTH ID
  - Luke LeVasseur (lukel@kth.se)

## Deadline

Task 2

## Category

Course Automation

## Description
`mpr` will simplify the PR creation flow for students. This shell script will incorporate pushing the most recent commit
to its remote branch in the forked repo copy, opening a new PR in the devops repo, and applying the template PR
Description.

Students will be able to run `mpr` from their command line, which will prompt them for a PR title. After they write the
title and hit enter, the script will run some git commands and open up the "create pull request" web UI with the
template for the title auto-filled based on the CLI input. Students will still need to update the description of the PR
with details from their readme, but this will simplify the PR creation process for students (
currently `local commit, remote push, edit PR through git web UI, input title and desc, create pr`, will
be `local commit, mpr, input desc, create pr`)

Additionally, I could see this automation contribution as a first step in a new class of shell scripts designed to
automate student workflows. For example, I regularly use a `rebase`
alias (`git stash && git checkout origin/master && git pull && git checkout - && git rebase origin/master && git stash pop`)
which could also be valuable to student workflows within the devops repo.

### CODE REVIEW

**Comment by khesoem** [comment]
@luuuk Thanks for this interesting proposal.

For course automation, we usually look for something that can be integrated into the Devops-course repo and used in next iterations of this course. This is usually done by implementing a workflow for the course repo. What you are suggesting could be a tool used by students to submit a pull request more easily. Please think of how this can be integrated into the course repo and resubmit your proposal (if you want) in a new PR.

**Comment by khesoem** [comment]
Actually, if you can make it a script that is a part of this repo, that can be seen as a course automation task. So, I'm reopening this PR. Just try to make it a bit more clear, how students will use it. For example, they can run the script with a couple of inputs (description and title could be among them) and you will create the PR.

**Comment by luuuk** [comment]
Thanks for the input Khashayar! Will clarify the points above in the readme and PR description and tag you once done.

**Comment by luuuk** [comment]
Hey @khaes-kth readme is updated - lmk if this looks good!

**Comment by khesoem** [comment]
Nice, looking forward to it.

**Pull request merged**
