### PR TITLE
Repetition of Covid19 Project: Help Fight COVID19

### PR DESCRIPTION
**Pull request by sujon2100**
Based on the feedback, the following changes have been made:

1. Marged the two repositories to keep only one that contains all the code.
2. Added the CI and test instructions.
3. Added the documentation PDF.
4. The current documentation on Azure has been revised to have a clear structure, fewer screenshots.
5. Added more metrics about the project: How many tests? What code coverage? How many Locs? How long is a build?
6. The CI instructions have been documented. 
7. The CI/CD section of the documentation has no screenshot but instead details the content of the configuration files that we have developed and justified this content,  the needs of our application.
8. We have added contribution on: the novel, helpful, attract support from other KTH students. 
9. There is no self-assessment in the readme.
10. Added motivation about how our contribution succeeds on these criteria.

### CODE REVIEW

**Comment by sujon2100** [comment]
Updated README

**Comment by sujon2100** [comment]
Updated readme and links

**Comment by sujon2100** [comment]
Added Azure DevOps link in readme

**Comment by sujon2100** [comment]
Updated PDF for the documentation

**Comment by monperrus** [comment]
Thanks for the revised version. We don't want the full project in the course repo, only a link to your repo in the README is necessary. Please update this PR accordingly.

**Comment by sujon2100** [comment]
> Thanks for the revised version. We don't want the full project in the course repo, only a link to your repo in the README is necessary. Please update this PR accordingly.
Do you want us to remove all the sources, files, images, and contents of the readme files from the pull request?

**Comment by sujon2100** [comment]
> Thanks for the revised version. We don't want the full project in the course repo, only a link to your repo in the README is necessary. Please update this PR accordingly.

Do you want us to remove all the sources, files, images, and contents of the readme files from the pull request?

**Pull request closed without merging**
