### PR TITLE
[Final submission]: (meta) course automation

### PR DESCRIPTION
**Pull request by landeholt**
# Assignment Submission

## Title

Automatic verification for mandatory parts of course-automation final

## Members

John Landeholt (johnlan@kth.se)
github: Landeholt

## Deadline

Deadline to complete task 1: April 5, 17h Stockholm time

## Category

Course Automation
## Proposal

In order to alleviate __redundant work__ for this course TAs I propose to automate verification of the following mandatory parts for ["course-automation"](https://github.com/KTH/devops-course/blob/2022/grading-criteria.md#course-automation):

-   timeliness: the automation is done before the __first task__ deadline (in order to be useful for the course)
        The first task deadline should be a set as a variable that can be changed for each year. If the final pull request to this repo is after __first task__, the pull request should become invalid.
-   repo: the code for the task is available in a public repo
        Check through the `readme.md` for a github-url and check whether the repo is public or not

The automation should perform the following :

-   Run for each new pull request that is the course automation task
-   Check if it is a final submission (i.e has a repo-link)
    - if final: check if it is before __first task__ deadline and if repo is __public__
    - if not final: check if it is before __first task__
-   Give feedback accordingly to the pull request

## Submission
-

### Link to action repo

https://github.com/landeholt/dd2482-course-automation

### Validation

- [Pull request #8](https://github.com/landeholt/dd2482-course-automation/pull/8)

## Testing

Please check through the test folder, or the readme solution.

I think I have fulfilled the following criterion: 

|                                             | Yes | No | 
|-------------------------------------------- | ----|----|
|timeliness: the automation is done before the first task deadline (in order to be useful for the course) | **Mandatory** | - |
|repo: the code for the task is available in a public repo  | **Mandatory**| - | 
|outcome: the automation task produces a PR status or an issue / PR comment | **Yes** | No |
|reuse: the automation task is reusable (next year for this course) | **Yes** | No | 
|platform: the task runs on a standard platform (eg Github action) | **Yes** | No | 
|doc: the repo is documented with a good readme | **Yes**  | No | 
|figure: the README is illustrated with at least an informative figure (eg a flowchart) | Yes | **No** | 
|availability: The action is available on a market place (Github Marketplace, Azure Marketplace, etc.) | **Yes** | No |

### CODE REVIEW

**Comment by landeholt** [comment]
> Readme is not correctly formatted Need exactly: ['Assignment Proposal', 'Title', 'Names and KTH ID', 'Deadline', 'Category', 'Description']
> 
> Got: ['Assignment Submission', 'Title', 'Members', 'Deadline', 'Category', 'Proposal', 'Submission', 'Link to action repo', 'Validation', 'Testing']

Can't find template for submission..

**Comment by khesoem** [comment]
Hi @landeholt ,

There are two issues with your submission that should be solved before we merge it.
First, it also changes your course automation readme. This may be fixed if you rebase your branch.
Second, your essay is too long. It should be between 2400 to 2600 words. Please reduce its size and check if it has a correct number of words. Look at this link to see how you can count the words: https://superuser.com/questions/221359/count-the-number-of-words-in-a-pdf-file

**Comment by landeholt** [comment]
> Hi @landeholt ,
> 
> There are two issues with your submission that should be solved before we merge it. First, it also changes your course automation readme. This may be fixed if you rebase your branch. Second, your essay is too long. It should be between 2400 to 2600 words. Please reduce its size and check if it has a correct number of words. Look at this link to see how you can count the words: https://superuser.com/questions/221359/count-the-number-of-words-in-a-pdf-file

Thanks for the update!

I've now followed your instructions and will be awaiting your assessment!

**Comment by khesoem** [comment]
@landeholt , This is a course automation task, isn't it? Why is it changing an essay readme? https://github.com/KTH/devops-course/pull/1660/files

**Comment by landeholt** [comment]
> @landeholt , This is a course automation task, isn't it? Why is it changing an essay readme? https://github.com/KTH/devops-course/pull/1660/files

@khaes-kth  because I unfortunately uploaded multiple solutions/proposals in the same branch, will that be a problem? All checks have been passed

**Comment by landeholt** [comment]
@khaes-kth - sorry for any inconveniences! I hope this PR is correct by now

**Comment by khesoem** [comment]
@landeholt It seems your PR is not adding the submission section to the readme anymore: https://github.com/KTH/devops-course/pull/1660/files

Please fix that.

**Comment by landeholt** [comment]
> Readme is not correctly formatted Need exactly: ['Assignment Proposal', 'Title', 'Names and KTH ID', 'Deadline', 'Category', 'Description']
> 
> Got: ['Assignment Proposal', 'Title', 'Names and KTH ID', 'Deadline', 'Category', 'Description', 'Submission', 'Link to action repo', 'Validation', 'Testing']

@khaes-kth  there you go. merge me.

**Pull request closed without merging**
