### PR TITLE
Updating demo

### PR DESCRIPTION
**Pull request by PaulLowenstrom**
Updating demo, Oliver is not in the assignment anymore

### CODE REVIEW

**Comment by PaulLowenstrom** [comment]
Improved synch and readme

**Comment by PaulLowenstrom** [comment]
Fix easter egg time

**Comment by PaulLowenstrom** [comment]
Made minor changes to take home message

**Comment by PaulLowenstrom** [comment]
Updating readme

**Comment by bbaudry** [comment]
ACK. Received repetition for demo

**Pull request merged**
