### PR TITLE
[Final submission] Executable tutorial : setting up splunk in a docker container

### PR DESCRIPTION
**Pull request by Augustjon**
### Members
Hugo Heyman (hheyman@kth.se) 
Github: hallon-heyman

August Jönsson, kth: augustjo@kth.se
Github: augustjon

We have created a tutorial on how to set up splunk in a docker container.  
The tutorial can be done here https://katacoda.com/hallon/scenarios/hallon123

And the repo can be seen here
https://github.com/hallon-heyman/katacoda-scenarios  
These are the grading criterias we feel we have reached, Checkmarks marks the remarkable requirements we feel we have achieved.

|                                             | Yes | No | Remarkable |
|-------------------------------------------- | ----|----|-------------|
|The TA can successful execute all the commands of the tutorial (mandatory) | Yes | No | :heavy_check_mark: In the browser |
|If local execution, runs on Linux | Yes | No | Easy to setup and run  |
|The tutorial gives enough background | Yes | No | :heavy_check_mark: Comprehensive background |
|The tutorial is easy to follow  | Yes | No |:heavy_check_mark:  Well documented | 
|The tutorial is original, no such tutorial exists on the web | Yes | No | :heavy_check_mark:The teaching team never heard about it | (There exists guides but we could not find an interactive tutorial)
|The tutorial contains [easter eggs](https://github.com/OrkoHunter/python-easter-eggs) | Yes | No | :heavy_check_mark: Subtle and fun |
|The tutorial is successful (attracts comments and success) | Yes | No | Lively discussion |
|The language is correct | Yes | No | :heavy_check_mark: Interesting narrative  |

I  @Augustjon need to receive feedback in order to pass the feedback task so if anyone could give feedback to this tutorial that would be greatly appriciated.

### CODE REVIEW

**Comment by Augustjon** [comment]
I'm  not sure if there is any student left who is willing to give feedback at this stage. Maybe one of the TA:s can give feedback? @Deee92 @cesarsotovalero @SophieHYe @khaes-kth

**Comment by Deee92** [comment]
Hi @Augustjon, sure. I'll get back to you with some feedback.

**Comment by Deee92** [comment]
### Feedback for "setting up splunk in a docker container"

#### Introduction
> Docker is perhaps the worlds leading devopstool. Splunk is a monitoring tool used by many companies in order to analyse data comming from various systems.

When introducing Docker for the first time, also mention that it is a containerization tool that allows applications to be packaged and deployed as images that can be run easily. When introducing Splunk, include a brief overview of what kind of data it monitors, from which kind of systems (databases, APIs, ...), and what can be done with this data.

>  many programmers will already be familiar with it

Perhaps developers is a better word

> If you are unfamiliar with the structure of virtualisation

Can be removed

#### Step 1
Some common docker commands that can be executed in the Katacoda terminal would be useful while introducing concepts such as images, containers, etc. Include some more information on Dockerfiles (it has instructions to build a Docker image).
 
> They are created in two different ways: from read only templates and docker files. 

What is meant here by read-only templates? A Docker image is built on top of another (base) image, which is specified in the Dockerfile for the image.

#### Step 2
Mention exactly what the `docker pull` command does here (pulls the image from Docker Hub, gets the latest version, and so on). For more interactivity, here you can also include a command to list docker images and verify that the Splunk image has now been pulled locally.
When introducing Splunk, start by discussing if Splunk enterprise is an open-source, freely available tool.

#### Step 3
Explain why there two `-p` flags in the `docker run` command. Also include `--name` in the explanation.

> and look for the status to be healthy, if it says health:starting you must wait until it only says "(healthy).

This took a few minutes for me, mention that it can take a few minutes for the status to be `healthy`

#### Steps 4 and 5
What is some other types of events in Splunk? Explain in more detail what HEC. The instructions here are somewhat easy to follow, but ensure that you also include why each step is being done, what each option means.
In step 5, `index=main` and `index=history` should have quotes around `main` and `history`. Fix any issues with the `earliest` queries as well, as I could not replicate them.

#### Remarks
- Add links wherever applicable (Splunk, Docker, VMWare, Docker Hub) when introducing them for the first time
- There are many typos ("devopstool", "comming", "presences", "empackage", "featre", "eterprise", "specifiys", "kanakoda", "uppload") and inconsistencies ("docker" and "Docker", "devops" and "DevOps", etc) that should be corrected
- Maybe it's just me, but I did not find the easter eggs. 🥚 😢

**Comment by Augustjon** [comment]
### The following changes has been made based on the feedback
Thank you for the feedback @Deee92, we have acted on the feedback now.
- [x] Fixed typos in the whole tutorial
- [x] Added better description when introducing the readers to Docker and Splunk 
- [x] Add hint about easter egg in final step
- [x] Added links wherever it was needed
- [x] Added clarification on search queries in step 5 and fixed issues with search
- [x] Added more information about splunk in both step 2 and 4
- [x] Added common docker commands and explanation of them in step 1
- [x] Added more description to the docker run command and added part about the container starting taking some time

**Pull request merged**
