### PR TITLE
[Submission]: Executable tutorial: MLOps - Automation of Model Evaluation #1019

### PR DESCRIPTION
**Pull request by vickstrom**
# Exectuable tutorial: MLOps - Automation of Model Evaluation

# Members

Eric Vickström (ericvi@kth.se)

Github: vickstrom

Oscar Almqvist (oscaralm@kth.se)

Github: oscaralmqvist

# Proposal
Before pushing changes to the model, it is important to evaluate the model against certain datasets. For a given pull-request, we aim to compare the current version performance versus the version on the master branch. Hopefully, commenting the results on the pull-request itself with relevant statistics (classification rate etc.). 

Our executable tutorial will contain the following:
1. Github Webhooks - Check if an pull-request has been made.
2. DIY Server - Create an environment that evaluates the model with the proposed changes given in the pull-request.
3. Use the Github API  to make a comment on the pull request with the established classification rate.

# Submission

Here is the tutorial in written form as stated in the contract. 

[Tutorial (Github)](https://github.com/vickstrom/automation-of-model-evaluation)

We decided to extend our submission, by making the written tutorial interactive, to make it easier for TAs to grade and the possiblity of getting distinction.  

[Tutorial (Katacoda)](https://www.katacoda.com/vickstrom/scenarios/automation-of-model-evaluation)

### CODE REVIEW

**Comment by vickstrom** [comment]
@khaes-kth @SophieHYe Hi! We're done with our submission, however, no one has signed up to give this submission feedback. We have already received and given for the essay, but we do not know if we need to get feedback for this task as well.

**Comment by khesoem** [comment]
Hi @vickstrom 

Yes, you need to get feedback for this (or an essay if you have).

Your tutorial seems to be too long. A tutorial is supposed to take 10-15 mins to complete, but I think yours will take longer. Is that right?

**Comment by vickstrom** [comment]
> Hi @vickstrom
> 
> Yes, you need to get feedback for this (or an essay if you have).
> 
> Your tutorial seems to be too long. A tutorial is supposed to take 10-15 mins to complete, but I think yours will take longer. Is that right?

Hi @khaes-kth ! So, if I understood it correctly, because we got feedback (see [here](https://github.com/KTH/devops-course/pull/1344)) for the essay we don't need feedback for this?

Regarding the time it takes to complete the tutorial: in katacoda we forgot to change the estimated time from setting up the tutorial. It currently says 60 min but in reality it should be around 15 min according to our tests (which of course is biased but we tried to take it slow). The only thing "a lot" of time is creating a repository (or just forking our code example) and registering a Github App. The rest is just inserting the functions we have defined and explained in the tutorial. Hope this clarifies things!

**Comment by khesoem** [comment]
> if I understood it correctly, because we got feedback (see [here](https://github.com/KTH/devops-course/pull/1344)) for the essay we don't need feedback for this?

Yes, you understood it correctly. And I'm very happy to hear you had already received a feedback for another task :)

> It currently says 60 min but in reality it should be around 15 min according to our tests 

Good. Then that should be fine.

**Pull request merged**
