### PR TITLE
Executable Tutorial Proposal

### PR DESCRIPTION
**Pull request by t-sorger**
# Assignment Proposal

## Title

Setting Up a Dashboard using Splunk

## Names and KTH ID

- Marco Campione (campione@kth.se)
- Tom Sorger (sorger@kth.se)

## Deadline

- Task 3

## Category

- Executable Tutorial

## Description

In this executable tutorial, we will guide the user through running Splunk. We will add a data source and create a dashboard to visualize data using the new Splunk Dashboard Studio. The data source will be set up to dynamically grow in size and change its data over time, showcasing Splunk's real-time capabilities. Finally, we will configure an alert to trigger when a specific data threshold is met.

**Relevance**

"Having good dashboards is essential in DevOps" (see [here](https://github.com/KTH/devops-course/issues/8#issuecomment-445817093)).

### CODE REVIEW

**Comment by Deee92** [comment]
Hi @t-sorger, have you decided the platform you will use for the tutorial?

**Comment by t-sorger** [comment]
Hi @Deee92, we planned on using  [KillerCoda](https://killercoda.com/) to spin up and host a Docker container, so we can do the whole tutorial in the web browser.

**Comment by t-sorger** [comment]
Also just to make sure, does "Task 3" as deadline refer to deadline 3 (Deadline 3 for async tasks: Oct 15 2024, 17h Stockholm time)?

**Comment by Deee92** [comment]
Yes, your tutorial is due October 15. You will open a new PR for the final submission, linking this proposal PR. Let me know if that sounds good, and I'll merge.

**Comment by t-sorger** [comment]
Thanks for the clarification. Sounds good to us, please merge😊

**Comment by Limph1** [comment]
I would like to give feedback on this, if possible.

**Pull request merged**
