### PR TITLE
Mircoram essay proposal

### PR DESCRIPTION
**Pull request by OmidMircoram**
# Assignment Proposal

## Title

How to secure your CI/CD Pipeline and why it's important. 

## Names and KTH ID

  - Omid Mircoram (mircoram@kth.se)

## Deadline

- Task 3: Monday, May 8 @ 17h Stockholm Time

## Category

- Essay

## Description

In this essay, I will discuss the what CI/CD pipeline breaches such as https://blog.gitguardian.com/codecov-supply-chain-breach/ is. I will focus on techniques such as mapping the attack vector(observing and monitoring), depency analysis, securing the pipeline with automated tools such as testing (unit, application etc), and credential management. To show an state of the art example, I will also have a section on machine learning integration. 

**Relevance**

With supply chain attacks becoming more popular, it's a good idea to have a good understanding of what supply chain security is and how devops can be used to make it more reciliant against attacks. It's also important for a devops engineer to be able to look at a CI/CD Pipeline and be able to pinpoint weaknesses.

### CODE REVIEW

**Comment by javierron** [comment]
Hello @OmidMircoram. Thanks for the proposal. Supply chain security is a very broad topic. You should pick a more specific scope. 

You mention "Examples of supply chain attacks. Both static analysis as well as dynamic analysis methods will be discussed". This is a good start. However, I suggest that you pick a specific kind of attack, and then discuss the tools/techniques/methods that help mitigate this attack. Also, remember that the essay has to discuss the topic in the context of DevOps.

**Comment by javierron** [comment]
@OmidMircoram  

Also, can you elaborate on what is Microram?

**Comment by OmidMircoram** [comment]
@javierron Hello! Thanks for the feedback. Is it enough to delimit the scope to CI/CD pipeline breaches? And then discuss what it is, methods/tools/techniques etc to mitigate and then examples of such attacks?

Also, not sure what "microram" is (probably some old hardware ram sticks had only microbytes) but "mircoram" which has a very similar spelling is my last name. :)

**Comment by javierron** [comment]
LGTM. Sorry for confusing your name!

**Pull request merged**
