### PR TITLE
Feedback Proposal

### PR DESCRIPTION
**Pull request by DavidCWQ**
# Assignment Proposal

## Title

Feedback on Demo [Infrastructure as Code Using Ansible Playbooks](https://github.com/KTH/devops-course/compare/contributions/demo/week7/arberl-sorger)

## Names and KTH ID

  - Wenqi Cao (wenqic@kth.se)
  - Katsutoshi Amano (amano@kth.se)

## Deadline

- Task 3

## Category

- Feedback

## Description

We would like to provide a feedback for [Infrastructure as Code Using Ansible Playbooks](https://github.com/KTH/devops-course/tree/2024/contributions/demo/week7/arberl-sorger)

The feedback will be posted as a comment under their PR.

### CODE REVIEW

**Comment by sofiabobadilla** [comment]
@DavidCWQ 
remember to send the feedback before they present.

**Comment by DavidCWQ** [comment]
The feedback has been posted under their PR before presentation. We've also sent it to them via Discord. :)
Is there anything else we should do?

**Comment by sofiabobadilla** [comment]
submit a pr, title Feedback Submission
Look at other closed PRs for inspiration

**Comment by DavidCWQ** [comment]
Thank you sofiabobadilla! We've submitted the Feedback Submission #2628.

**Pull request merged**
