### PR TITLE
Demo proposal - Continous development, delivery, and pipelines with CircleCI

### PR DESCRIPTION
**Pull request by jonasjohansson8908**
# Demo proposal

## Members

Jonas Johansson, jonasjo5@kth.se

Github id: jonasjohansson8908

Marcus Jonsson Ewerbring, marcusew@kth.se

Github id: Marcus9512

## Continous development, delivery, and pipelines with CircleCI

We want to demonstrate how to integrate and use continuous delivery and continuous deployment with CircleCI. 
We will provide a GitHub repository together with our screencast. The viewer can fork the repo and will be provided two branches, one with a complete implementation and one unfinished setup.

We will show how new features can be delivered into an existing app.
We will highlight some features that make CircleCI a strong competitor within continuous deployment and some features that facilitate the migration from Jenkins to CircleCI. 

Hopefully (if we manage to pull it off), we will show some examples of integration with Docker and Kubernetes.

### CODE REVIEW

**Comment by cesarsotovalero** [comment]
@jonasjohansson8908: Soy, your demo will provide an end-to-end demonstration on how to integrate CircleCI into a real project. Do not forget to refer to the features that makes CirceCI great in comparison with their many competitors in the market.

**Comment by jonasjohansson8908** [comment]
Yes, focusing on deployment and delivery. We added an extra line in the readme, addressing the features of CircleCI. Do you have any specific features in mind? Both me and Marcus are new to CircleCI and CD in general.

**Comment by cesarsotovalero** [comment]
@ jonasjohansson8908 You can refer to the steps and features that facilitate the migration from Jenkins to CircleCI. Also, showing some examples of integration with Docker and Kubernetes is a plus.

**Comment by jonasjohansson8908** [comment]
@cesarsotovalero 
Thank you for the suggestions! I added them to the readme and comment

**Pull request merged**
