### PR TITLE
hazara: Demo Proposal Week 5

### PR DESCRIPTION
**Pull request by omidhzr**
# Assignment Proposal

 ## Title

 Managing Terraform's state remotely using AWS 

 ## Names and KTH ID

 - Omid Hazara (hazara@kth.se)

 ## Deadline

 - Week 5

 ## Category

 - Demo

 ## Description

I will demo the interplay between AWS and Terraform, in the context of state management. This will showcase the power and ease of implementing infrastructure as code in a DevOps workflow. 

**Relevance**

Terraform is a widely-used infrastructure-as-code (IaC) tool that enables users to create, update, and destroy infrastructure resources efficiently. By leveraging Terraform with AWS, developers and operations teams can manage infrastructure consistently and transparently, making it an essential component of a modern DevOps workflow.

### CODE REVIEW

**Comment by omidhzr** [comment]
Feel free to suggest interesting ideas that can be incorporated in this demo. I am very flexible and like challenging tasks.

**Comment by javierron** [comment]
Hello @omidhzr 
Would you consider changing the focus of your demo to showing AWS CloudWatch's main features in week 6?
You can still do it in the context of a Terraform deployment.

**Comment by omidhzr** [comment]
Hello @javierron :)
Yeah, I think I would be able to do so. Is it possible to deliver a demo and presentation on the same day? Because I have planned an MLOps presentation with a partner in week 6.

**Comment by omidhzr** [comment]
In the event that there is an overlap and it's not feasible to have the presentation and demo on the same day (MLOps and Monitoring in this case), I can modify the content of my IaC presentation to focus more on IaC or demo features of Ansible or Pulumi. Please share your input on this matter as soon as possible, so I can make the necessary preparations. Thanks!

**Comment by javierron** [comment]
Hello @omidhzr, sorry for the delayed response.

You cannot do presentation and demo on the same day.

Your plan of focusing the presentation on IaC is good.

Please update the proposal and I will review it immediately.

**Comment by omidhzr** [comment]
Hello @javierron!
Thanks for your response. Some stuff that I find interesting to demo is provisioning and the use of remote backend for state management and alike. Let's see what I can bake in 6-7 minutes.

**Comment by javierron** [comment]
@omidhzr that sounds great.
Can you name a few AWS tools that you would be interacting with?

**Comment by omidhzr** [comment]
@javierron I think of EC2, S3, VPC, IAM etc. that are needed to build the state management backend, for example. You are welcome to suggest interesting ideas and tools as well :)

**Comment by javierron** [comment]
@omidhzr  A demo on remote state management sounds very interesting. It can be helpful to know: (1) the advantages of remote state management backend vs local, and (2) how to set it up in AWS.
What do you think?

**Comment by omidhzr** [comment]
@javierron Yeah, I cannot agree more. :)

**Comment by javierron** [comment]
@omidhzr Great, if you update the proposal, I'll merge it right away.
Looking forward to your demo.

**Comment by omidhzr** [comment]
@javierron Updated the PR. Thanks for the input and have a great weekend!

**Comment by javierron** [comment]
@omidhzr merged!

**Pull request merged**
