### PR TITLE
Essay proposal

### PR DESCRIPTION
**Pull request by gynther-k**
Kasper is doing a Tutorial on TeamCity #352 and have emailed and got approval for the subject not conflicting too much, just wanna double check with the TA that is inspecting this PR.

### CODE REVIEW

**Comment by cesarsotovalero** [comment]
@gynther-k the topic DevOps and CI/CD is too broad for an essay. You should consider focusing on a single technology or tool instead for the essay (e.g. Jenkins). Also, the topic is too close to the tutorial of Kasper Liu. So, I'll merge this PR when you make the changes.

**Comment by gluckzhang** [comment]
Hi @cesarsotovalero , @gynther-k and @Kappenn are in the same team for this essay proposal. I assume @gynther-k means they have discussed with us by email that it's fine to have an essay whose topic is CI/CD as well. This should be fine since CI/CD is quite a large field. As long as the detils are different, as @SophieHYe mentioned in the email.

But I agree with the suggestions. The description of the essay is a bit broad.

**Comment by gynther-k** [comment]
Are the changes in README.md OK?

**Comment by cesarsotovalero** [comment]
@gynther-k  changes are good. 
Good luck.

**Pull request merged**
