### PR TITLE
Essay submit

### PR DESCRIPTION
**Pull request by TAOFOR4**

### CODE REVIEW

**Comment by javierron** [comment]
Hello @TAOFOR4, thanks for the submission!
Is this a revision? The file already exists in the repository. If this is a revision, please add it as a new file.

**Comment by NilsLofberg** [comment]
Hi, this is a semi-revision, due to accidental misconduct in the original file, it is not meant as a proper revision as we have yet to receive feedback from the examiners on it, but rather to replace the first submissions entirely. this has all been discussed with the examiners

**Comment by javierron** [comment]
@TAOFOR4 @NilsLofberg  I see. You need to fix the merge conflict before this can be merged then.

**Comment by TAOFOR4** [comment]
> @TAOFOR4 @NilsLofberg I see. You need to fix the merge conflict before this can be merged then.

Thx! Already fixed it.

**Pull request merged**
