### PR TITLE
Video demo Final Submission With Feedback: How to leverage Docker and Kubernetes for creating a Microservice Web App

### PR DESCRIPTION
**Pull request by Internet-Person-IP**
## Members

Taqui - taqui@kth.se
GitHub: [Internet-Person-IP](https://github.com/Internet-Person-IP)

## Initial Proposal: 
[#1007](https://github.com/KTH/devops-course/pull/1007)

# Submission

The final product can be found [here](https://www.youtube.com/watch?v=kcBz4cNKqGo).

## Grading Criteria

|                                             | Yes | No | Remarkable |
|-------------------------------------------- | ----|----|-------------|
|The demonstration is clearly motivated (why it matters for Devops?) |  💍 Yes | No | Relates to a hard problem |
|The demonstration is difficult to do | 💍 Yes | No | Relies on a non trivial infrastructure |
|The demonstration is original |  💍 Yes | No | The are less than 10 demos on the topic on Internet |
|The video is sublime (eg visually appealing) | Yes | No | Excellent narrative |
|The video contains an [easter egg](https://github.com/OrkoHunter/python-easter-eggs) | Yes | No | 💍 Related to the demo |
|There is a code repo to run the demo  | Yes | No | Code repo with a solid readme |
|The video must contain subtitles which are clear and in proper English | Yes | No | Clearly understandable voice over |
|The video includes a take-home message | Yes | No | 💍 Actionable takeaway |

# Fixed Feedback

* Gone through each step of the tutorial in more detail.
* More Consistent Experience Mic Wise
* Added Github Link to the repository
* Fixed some Editing

### CODE REVIEW

**Comment by Internet-Person-IP** [comment]
@khaes-kth Here is my final version

**Comment by Deee92** [comment]
Hi @Internet-Person-IP, your updated README should be corrected before it can be merged.

**Comment by Internet-Person-IP** [comment]
@Deee92 My Apologizes, I did not realize that I forgot to push the latest version of my README.md

It should be correct now.

Best Regards,

Taqui

**Comment by Deee92** [comment]
Thanks, merging now!

**Pull request merged**
