### PR TITLE
Proposal: Feedback on essay "Feedback on essay "Securing the pipeline - Continuous penetration testing""

### PR DESCRIPTION
**Pull request by elibon99**
# Assignment Proposal

## Title

Feedback on essay "Securing the pipeline - Continuous penetration testing"

## Names and KTH ID

- Elias Bonnici (bonnici@kth.se)
- Per Arn (perarn@kth.se)

## Deadline

Task 4

## Category

Feedback

## Description

We would like to give feedback on the essay "Securing the pipeline - Continuous penetration testing"

**Link to submission PR**

[#1909](https://github.com/KTH/devops-course/pull/1909)

**Essay Author**
-  Valdimar Björnsson (valdimar@kth.se)

### CODE REVIEW

**Comment by ArnPellesGit** [comment]
> Missing student registration :arn
> 
> If not from your group, fetch the upstream.

Why did this happen.. I am indeed registered afaik :(

**Comment by khesoem** [comment]
You should fetch the latest version from the upstream (KTH/devops-course:2022) to fix this issue.

**Comment by elibon99** [comment]
> Reference i

I've fetched the upstream but it does not seem to work

**Comment by elibon99** [comment]
> Missing student registration :arn
> 
> If not from your group, fetch the upstream.

I've fetched the upstream and it says on my fork that I don't have any new commits to fetch from KTH/devops-course:2022.

**Comment by khesoem** [comment]
You should change the folder name to your KTH ID. Your folder name is `arn-bonnici`, but your KTH ID isn't `arn`, it's `perarn`.

**Comment by elibon99** [comment]
> You should change the folder name to your KTH ID. Your folder name is `arn-bonnici`, but your KTH ID isn't `arn`, it's `perarn`.

Ahh, got it! Thanks

**Pull request merged**
