### PR TITLE
Essay: DevOps in IoT: Solution or challenge for sustainable development?

### PR DESCRIPTION
**Pull request by charlottea98**
# Essay submission: DevOps in IoT: Solution or challenge for sustainable development?

## Members
Name: [Charlotte Andersson](https://github.com/charlottea98)
E-mail: charande@kth.se

Name: [Lazar Cerovic](https://github.com/lazarko) 
E-mail: lazarc@kth.se

## Initial proposal
Initial PR can be found here #988 

## Submission
Submission can be found in ‘contributions/essay/charande-lazarc/DevOpsinIoTSolutionorchallengeforsustainabledevelopment.pdf'

Looking forward to feedback from @jhammarstedt and @carllei (#1081 )

## Grading criteria we are aiming for
|                                             | Yes | No | Remarkable |
 |-------------------------------------------- | ----|----|-------------|
 | format: The essay is in PDF | 👍  Mandatory | - | - |
 | title: The essay has a good title | Yes | No | 👍  Remarkable |
 | well-structured: The essay is well structured, the ideas are well presented | 👍 Yes | No | Remarkable |
 | introduction: The essay contains a good introduction | 👍  Yes | No | Remarkable |
 | conclusion: The essay contains a good conclusion | 👍  Yes | No | Remarkable |
 | self-contained: The essay is self-contained, one can understand it without reading something else (expected knowledge of the reader: a master student in computer science) | 👍  Yes | No | Remarkable |
 | innovative: The essay contains innovative ideas or material | Yes | No | Remarkable |
 | figures: The essay contains good figures or listings | Yes | No | Remarkable |
 | sound: The essay is sound, factual, and accurate | 👍  Yes | No | Remarkable |
 | references: The essay contains references, appropriate in number and quality (10 good refs is a minimum) | Yes | No | 👍  Remarkable |
 | elegant: The essay presentation is elegant / visually appealing (eg LaTeX, InDesign) | Yes | No | 👍  Remarkable |
 | relevant: The essay addresses a topic that is relevant for DevOps | 👍 Yes | No | Remarkable |

### CODE REVIEW

**Comment by jhammarstedt** [comment]
Good job, will have a look and give you some feedback soon! 
Looking forward to read it!😊

**Comment by jhammarstedt** [comment]
Hi @charlottea98 @lazarko
Great job with the essay! 😊
We have submitted our feedback. See #1319

**Comment by charlottea98** [comment]
Thank you for the feedback! 😄

**Comment by jhammarstedt** [comment]
Was told that the feedback also should be a comment on your PR, so will add it here as well :)

## Feedback on essay

### Overall comment 

We have divided our feedback into several parts, first  we address the structure and sentences of each section. Then we go over the remaining general essay criterias and make comments.

There were some grammatical errors to fix and some long sentences that could be modified, you can see most of the ones we found in the attached pdf with annotations. We also added some suggestions for some sentences but it’s up to you if you want to use them or not. :)

One <ins>important note</ins>: Using one word counter your essay came out to be 2020 words and another one showed 2064 (we probably use a different one from you). A suggestion would be to run the pdf word counter mentioned in the lecture to make sure your pdf is almost exactly 2000 words to avoid getting a repeat since the criterias are strict.


### Feedback on each section

#### Title
Great title that in a clear and precise way gives the reader an idea of what the paper is about. First having this new technology "DevOps in IoT" and then asking a somewhat controversial question regarding its actual positive or negative net impact on sustainable development sets a good tone and gets the interest going.

#### 1.0 Introduction 
Section 1.0 does a good job of introducing the reader to the ideas of the paper. The sentence "This essay aims to give a well-founded and nuanced depiction..." clearly describes what we can expect of this read.

Suggested improvements:
- The last sentence is a little weak and could either be changed or another sentence could be added to transition us into the next part. Maybe just swapping the last sentence with the previous one would make a better case. 
- Avoid using technologies twice in last sentence as it comes of a little repetitive  
- SDG is an important part of your essay. It could be suitable to mention it in the introduction together with IoT and DevOps.

#### 1.1 Internet of Things
Intuitive and easy to follow explanation of IoT which citations (the first citation might want to be moved to the end of the sentence). But the paragraph is good and easy to follow. 

Suggested improvements:

“IoT” might be a little overused (understand it’s hard when you want to explain it, but mixing it up with some synonyms could just ease the flow)
Add/edit the last sentence to allow for a better transition to the next paragraph. 


#### 1.2 DevOps
The explanation of what DevOps is was very easy to follow. It had a nice flow with good references and most people with a computer science background should be able to understand. 

Suggested improvements:

You talk about IT operations( ITOps) and the conflict it has with DevOps. It isn’t evident how this is directly relevant for your topic. Maybe it is better to remove the sentence:  “As a result this causes a conflict of interest due to one group working towards pushing more changes, and then the other trying to maintain stability.” 
to make sure you are closer to the word limit.

#### 1.3 Sustainable development (SDG)
The SDG figure you included is very good. It was easy to get an overview and follow your referencing to the different goals.
The motivation for why the SDG is important is also very good.

Suggested improvements:

You just use the term SDG but never specify what the acronym means besides in your figure and the title. Since you included it in the title and mentioned it in all the other sections after it became clear but it was a little confusing at first. You should specify what the acronym means in the beginning of the section.

#### 2.1 Tiny ML & Cloud Computing
The explanation of what a Smart City is was very detailed and easy to follow.
Tiny ML and Cloud computing are both very relevant to this topic so it was nice that you provided a section for it. The information you discussed was overall very interesting!

Suggested improvements:

It is difficult to fully grasp Tiny ML. You mention its usefulness but never really define what it is. Maybe you should add another sentence with a proper definition.
You mention that decentralized cloud computing is safer than centralized. It is not evident why this is the case. A suggestion would be to give a reason for why this statement is true.
 Similar to the previous point, you state that smart home facilities have less power consumption. It is not completely evident from looking at your essay in isolation why this is the case.


#### 2.2 IoT’s impact on sustainability
Great first paragraph with good language and flow! 

The impact that IoT has on each of the sustainability goals was an excellent way to build this paragraph. You make many good points and the format made them easy to grasp.

Suggested improvements:

IT could be interesting if you mention specific IoT tools that are used for sustainable purposes. It could also be interesting with concrete examples of how IoT tools have already made a difference.
You probably missed to finish the last sentence as it just ends halfway (and no “.” which is why we assumed it was just an accident)

#### 3.0 Conclusion
The conclusion was very well written. It clearly states what the reader has learned from reading your essay and it gives a good overview of the topic. Good that you state the objective of the essay in the first sentence. 

Suggested improvements:

One of the final snetences on page 6 comes off a bit odd, needed to re-read it a couple of times. Maybe add another comma after "any piece of technology, remains to be..." or rewrite it a little. You could remove "arises" and just write:
* "Furthermore, the question whether the solution to some of the world's greatest issues can be solved by IoT, or any piece of technology, remains to be unanswered. "

The buildup is great but the last sentence could be rewritten a little to end on a more powerful note. A possible suggestion could be:
“While IoT in a DevOps culture could be impactful on a global scale, one could wonder whether or not this technology will live up to its potential.”
Or if you don't wanna change, at least add the comma after "saves the world," and avoid using technology twice. :) 


### Comments on remaining grading criterias 

#### Well-structured
The overall structure of the essay is good. Your ideas and thoughts are well presented and there is a red thread throughout the paper.

#### Self-contained
We were able to follow along the essay just fine with the provided background. You could almost have added a little more detail about the technical stuff since you’re writing for CS students. But no problems reading your paper so good job!

#### Innovative
No real innovative concepts were discussed (which you haven’t marked either) so no worries here.

#### Figures and Listings
Only one image (but this was not marked) so you didn’t aim to get it. Since images don’t use your word limit you could add some nice IoT illustration, maybe on the Tiny ML as we both felt like a little more detailed explanation of what it actually is would have been nice.

#### Sound
Yes, there are references and all the information provided is both fully motivated by facts and cited with sources when needed.

#### References
Good and a sufficient amount of references. Most of them are from conferences, journals or papers.

#### Elegant
Well structured and clean (looks like it was written in latex). Clear headers with consistent formatting that made it elegant and visually appealing. 
#### Relevant
We also think the topic is relevant as both IoT and DevOps are two separately important topics today, and discussing it from a sustainable perspective is certainly relevant given our current global crisis. Good job picking topic!

### Final Comments
Overall you guys did a great job of writing an interesting and appealing essay. The topic is highly relevant, both for the course and in general. Just let us know if you have any questions regarding the feedback.  We enjoyed reading it and are looking forward to the final draft! Good luck with the rest of the course!😊

**Comment by charlottea98** [comment]
## Changes from feedback
Overall, fixed the grammatical errors that were spotted. Thank you for the tip of using the word counter the course uses as we weren’t aware of it!
### Introduction: 

- Changed the last sentence to not sound repetitive
- Mention SDG

### Internet of Things

- Changed one “IoT” term to sound less repetitive 

### DevOps

- More concise and relevant to the essay description of DevOps

### SDG

- Changed the header to “Sustainable Development Goals (SDG)” 
- Hyperlink to figures

### Tiny ML

- Added a figure which illustrates the concept of Tiny ML
- Added sub-sentence: “since if one server gets taken out then the whole cloud fails.”

### IoT’s impact on sustainability

- Fixed the last sentence

### Conclusion

- Fix confusing sentence 
- Add reference to quote
- End on a more powerful note

**Comment by SophieHYe** [comment]
Hi,
Thanks for the update! For a better trace of the tasks, we recommend one PR per task. Could you please remove the changes related to presentation? I can also do that if you want. Thanks.

**Comment by charlottea98** [comment]
Unfortunately, I didn't create separate branches for the tasks so I'm unsure how to remove files in this PR without accidentally removing wanted files. So, if you could do it that would be great! Thanks :) @SophieHYe

**Comment by monperrus** [comment]
@charlottea98 understanding Git is mandatory in this course :) please try harder to get a correct rebase/merge cycle such that the diff in this PR only contains the essay change.

in the meantime, we're grading DevOpsinIoTSolutionorchallengeforsustainabledevelopment.pdf from commit  093e1ac

**Comment by charlottea98** [comment]
Fixed now! @SophieHYe

**Comment by SophieHYe** [comment]
Thanks for the update! I am merging your PR now.

**Pull request merged**
