### PR TITLE
Video Demo Submission: GitHub Integration with Jenkins

### PR DESCRIPTION
**Pull request by yuxinmmmm**

### CODE REVIEW

**Comment by yuxinmmmm** [comment]
# Video Demo Submission: GitHub Integration with Jenkins 
## Members
Ifeoma Urama (Urama@kth.se)
Yuxin Meng (yuxinm@kth.se)
## Outline
1. Introduction of Jenkins as DevOps tool.
2. Why use Jenkins with Github.
3. Demo on how to integrate git with Jenkins

## Proposal
Jenkins is an open automation tool, written in Java with plugins for continuous integration in DevOps. It is a tool used to build, test and deploy reliable software.

Follows #1038 

## Link of the video
[GitHub Integration with Jenkins](https://www.youtube.com/watch?v=EPi09oOpZg0)

**Comment by yuxinmmmm** [comment]
Hi, @SophieHYe .We are ready for the merging.

**Comment by SophieHYe** [comment]
## Good points
* The introduction is good.
* The steps are easy to follow.
* Perfect timing within 3 mins.


## To improve
* The pace is a bit too fast.
* The font size of the code/text could be larger. Text is hard to read and follow.
* If you need more time, maybe consider to remove the part to create Github repo. You can  assume the target audience already had this prerequisite knowledge. Also give a reference link to point the audience if they do not such knowledge.
* More explanation between steps and steps would be nice.

**Comment by 8ar10der** [comment]
## Feedback
Yuehao Sui


### Overall, this is a clear demo. And in 3mins.
* Two speakers with noticeably clear voices with the help of detailed subtitles, even an accent is not a problem.
* The content is very clear and the font is the perfect size.
* The steps are as well organised and easy to follow.
* The background is detailed and relevant to DevOps.

### Possible improvements
* The content is very basic, could some of the more difficult operations be put in place.
* Try to add some sound effects, otherwise the video seems too boring.

**Comment by gangwalmegha** [comment]
Overall nice demo! I specially liked the subtitle for the video. Instruction steps are easy to follow.
To improve: The speaker is speaking very fast.

**Comment by felix-seifert** [comment]
# Feedback

I heard of Jenkins and used it a little bit. However, I only used and operated it how I was told and I never made any changes to the existing Jenkins deployment. This video gave me a helpful introduction on how to use it for a very simple workflow. It definitely reduces the hurdle of adopting it on an own project. You detailed explanations of easy steps made it even simpler to follow.

These simple explanations of the Git workflow is, however, very time consuming and should be known to nearly everyone who watches the video. You should shorten your video by summarising your Git interactions. You can then use the gained time to focus on the Jenkins workflow. Additionally, you can slow down the artificially increased voice over because this sounds very robotic.

Your subtitles look very clear and readable. However, it is not possible to switch them off. Consider to use the own subtitles of Youtube to make it easier, for both you and the viewer.

**Comment by hassbring** [comment]
### Feedback

Good job overall! Visually appealing and easy to follow. Jenkins is relevant. 
Improvements could be to slow down the speed, which would lead to a too long video. But at the same time, a lot of the simple git usage could be cut away, since it is trivial for the audience. Then, the video would be more focused around the core content.

**Comment by annsudo** [comment]
Good tutorial, lots of work and time invested.

1) The content: clear, the topic will be useful for a broad amount of users 
2) The video is appealing. Colourful graphics, subtitles
3) Another strong part of the tutorial is that it helps you to follow the whole process: from creating the file to pushing it to Github to integrating with Jenkins.

Suggestions for improvement:
*  Speaking too fast (in my opinion subtitles compensate for that, youtube also gives the option for watching at 0.75 speed)

**Pull request merged**
