### PR TITLE
Demo: Docker monitoring using Datadog

### PR DESCRIPTION
**Pull request by mans-andersson**
# Video demo proposal: Docker monitoring using Datadog

## Members

Eric Vickström (ericvi@kth.se)
GitHub: [Eric](https://github.com/vickstrom)

Måns Andersson (manande@kth.se)
GitHub: [Måns](https://github.com/mansand1)

## Proposal
Demoing the process of setting up a monitoring service for Docker using
Datadog.

We will have some Docker containers running on a local machine and 
after the monitoring service has been set up we will show statistics
such as network usage, memory usage and CPU usage for the different 
containers.

### CODE REVIEW

**Comment by mans-andersson** [comment]
Based on feedback from @khaes-kth

**Comment by khesoem** [comment]
@mansand1 
Unfortunately, this is duplicate. Have a look at: https://github.com/KTH/devops-course/pull/809

**Comment by mans-andersson** [comment]
Hello @khaes-kth . Would it be ok if we did a demo using Datadog instead of Prometheus + Grafana?

We saw that one group is doing an executable tutorial with Datadog (https://github.com/KTH/devops-course/pull/972)
but we hope it would be ok since we are doing a demo with a different focus.

**Comment by khesoem** [comment]
@mansand1 
Yes that would be OK. Update the PR ASAP, otherwise someone else might pick this topic.

**Comment by mans-andersson** [comment]
@khaes-kth 
PR updated

**Pull request merged**
