### PR TITLE
Week 7 Presentation Proposal - Certificate Management in DevSecOps

### PR DESCRIPTION
**Pull request by aykhazanchi**
# Assignment Proposal

## Title

Certificate Management in DevSecOps

## Names and KTH ID

- Ayushman Khazanchi (ayushman@kth.se)
- Abdullah Abdullah (aabdull@kth.se)

## Deadline

Task 3

## Category

Presentation

## Description

We want to talk about cerificate management. In this we will try to cover the basics of TLS certificates and certificate chains. We will cover a little bit about Zero Trust Architecture and how certificates can help in zero trust architectture or even simple microservice architectures.

We will cover how it's done using Vault in a non-K8s environment and using Istio/Linkerd in a K8s environment.

### CODE REVIEW

**Comment by javierron** [comment]
@aykhazanchi Thanks for the proposal. The topic looks relevant and very technical. Looking forward to see the presentation.

**Comment by aykhazanchi** [comment]
@monperrus I see the schedule for week 7 looks pretty packed already but we would like to request that we can present this topic to the class instead of separately to the professors :)

**Comment by monperrus** [comment]
@aykhazanchi  Sure, we do prefer presentations to the full class. What about presenting on week 8 or week 9?

**Comment by aykhazanchi** [comment]
@monperrus We're good with presenting in Week 8!

**Pull request merged**
