### PR TITLE
[REPEAT] Essay: Cloud & Serverless: Game Changer?

### PR DESCRIPTION
**Pull request by Internet-Person-IP**
# Changes Asked and Made:

- Many sentences seem repetitive, and there are also repetitions within
sentences

I changed the structure of the essay to make it less repetitive and also change a lot of the sentences that seem repetitive.

- Some text is vague/unclear and should be rephrased (such as some
sentences in Section 5, or in the last paragraph of Section 6.2) 

I changed the text to make it more clear what I am trying to convey

- Some important technical facts are mentioned as advantages, and stated
directly but more explanation would be appreciated
   - Example: "Security is an aspect of serverless storage which makes
it incredibly interesting since it can offer powerful access management..."

I added another sentence explaining what the concept is how it helps with access control.

- Some issues with consistency should be fixed
   - Example: The introduction paragraph of Section 6 mentions
"Serverless Relational Databases", but subsection 6.2 mentions both
relational and non-relational databases

Changed the structure of the essay to make it more clear.

- Links to external tools should be included as a reference or a
footnote (Example: Aurora, DynamoDB, etc)

Fixed.

- Grammatical errors should be fixed, and language should be more formal
("To keep it simple" can be "Simply stated", avoid "You do XX" and use
"XX is done", etc)

I am not the best at formal writing but I read through it and fixed any ambiguity or informal language I could find.

   - Minor remark: citations should be placed before the period in a
sentence

I ignored this since from my understanding inside a period refers means that the reference only refers to the sentence, outside means it refers to an entire paragraph, which I tried to be consistent on, but perhaps I am wrong.

### Additional Change

Added some subsections to limitation since my word count got below 1900.

### CODE REVIEW

**Comment by Internet-Person-IP** [comment]
@khaes-kth Hi, my essay is fixed. I got some feedback from a friend and he helped me with some of the issues aswell. If there is anything else you want me to fix please let me know.

**Comment by khesoem** [comment]
Hi @Internet-Person-IP 

Thank you for submitting the new version. I can see that you have indeed improved the text. I skip the positive points about your essay and only mention what can be improved further.

1. There are still some grammatical issues. For example, paragraph 2 of section 2.2. There are also some typos, ex. paragraph 2 section 1.1. You can use a free grammar/spell checker online to check your text. That would help you not miss minor issues like these.
2. I do not quite understand what section 1.1 adds to the essay. If you want to introduce metrics based on which Severless enhances previous technology, you can introduce them at the beginning of Section 2.
3. I think section 2.2 can be moved/removed. It seems each subsection 2.2 is introducing a Serverless service. If yes, I do not understand how 2.2 fits there. Also, it is always a good practice to say what information later subsections will provide at the beginning of a Section. So, after the bullet points in Section 2 (Serverless), you can say "the next subsections will .....".
4. It would be interesting if you had some figures. With figures you may also pass another requirement. For example, a figure that shows an overview of Serverless workflow would be useful. By describing such a figure in the text, you will also extend the essay and pass the 1900 words threshold more easily.

PS: I think section 3 is much more clear than previous sections. Good job with that section.

I also found a similar essay (not a perfect one) from previous years [here](https://github.com/KTH/devops-course/blob/2021/attic/2020/contributions-2020/essay/dingli/essay.pdf). You can get some idea there.


Best,

**Comment by Internet-Person-IP** [comment]
Hi @khaes-kth, Thank you for your suggestion I did some changes and hopefully, they strengthen the essay:


- There are still some grammatical issues. For example, paragraph 2 of section 2.2. There are also some typos, ex. paragraph 2 section 1.1. You can use a free grammar/spell checker online to check your text. That would help you not miss minor issues like these.

I ran it through Grammarly to fix some of the issues that you mentioned.

- I do not quite understand what section 1.1 adds to the essay. If you want to introduce metrics based on which Serverless enhances previous technology, you can introduce them at the beginning of Section 2.

I think that understanding the metrics to define a good infrastructure can help to understand the strengths of serverless. I changed it so that it fit the section a bit more. I added a small introduction to explain the purpose of the entire section to make it more clear what I want to do.


- I think section 2.2 can be moved/removed. It seems each subsection 2.2 is introducing a Serverless service. If yes, I do not understand how 2.2 fits there. Also, it is always a good practice to say what information later subsections will provide at the beginning of a Section. So, after the bullet points in Section 2 (Serverless), you can say "the next subsections will .....".

So I wanted my essay to describe how Serverless could replace more traditional IT resources. I agree that the sectioning becomes unclear. I added a small introduction to the Serverless section to describe that I want to both introduce each service and how they can replace traditional IT resource.

- It would be interesting if you had some figures. With figures, you may also pass another requirement. For example, a figure that shows an overview of Serverless workflow would be useful. By describing such a figure in the text, you will also extend the essay and pass the 1900 words threshold more easily.

I added a small figure describe the Serverless Computing model in a bit more detail. I also added a small explanation as well.


I hope these changes are enough for me to pass the essay. If there are any other concerns please message me and I will fix them as soon as I can.

Best Regards,

Taqui

**Comment by khesoem** [comment]
Hi @Internet-Person-IP 

Thanks for updating the essay. The final grading will be done after the deadline.

Please remove ``contributions/essay/taqui/discord-0.0.15.deb'' so that we can merge this PR.

**Comment by Internet-Person-IP** [comment]
@khaes-kth thank you for your feedback. I think the discord file should be deleted.

**Pull request merged**
