### PR TITLE
Add initial demo proposal

### PR DESCRIPTION
**Pull request by JoarEkelund**
# Demo Proposal
 ## Members

 Joar Ekelund (joarek@kth.se)
 Johan Settlin (settlin@kth.se)

 ## Topic
 Demo on how to write a Jenkins pipeline for CI/CD

### CODE REVIEW

**Comment by SophieHYe** [comment]
Hello,
Your demo topic is indeed very relevant but a bit general.
Could you also please describe a bit more motivation for using azure and the original/difficulty of your demo? Thanks.

**Comment by johansettlin** [comment]
Our plan was to demo on how to write a scripted pipeline and runs on every commit or PR on GitHub using Jenkins. The Pipeline would do tasks such as compile code and run tests. We would do this on a maven project. Is this proposal good or do you have any suggestions? we feel a bit lost.

**Comment by SophieHYe** [comment]
Hi, 
Your demo plan is good. My major concern is about the originality of your demo as many tutorials and demos exist about how to use write a Jenkins pipeline to CI/CD the GitHub commits. We may expect a little bit more than Jenkins pipeline. Would you be interested in using docker pipeline, or integrate Jenkins with sonarQube or explore more about monitoring to collect and gather insights from traces and logs for your application?

Could you please also update your plan in your READMe file to describe your motivation, plan and your expected outcome of your demo. Thanks!

**Comment by johansettlin** [comment]
readme updated @SophieHYe

**Comment by SophieHYe** [comment]
Thanks for the update. The PR has been merged!

**Pull request merged**
