### PR TITLE
[Final submission] Essay (updated according to feedback)(4)

### PR DESCRIPTION
**Pull request by hassbring**
### Essay final submission, with updates following feedback
* Essay original proposal PR: #1205
* Essay draft submission PR: #1396 (i.e. the version that recieved feedback from @johanmallobakken)
* Feedback is to be found in the comments of PR #1396, as requested.

### Members

Name: Isak Hassbring (isakha@kth.se)
Github: [hassbring](https://github.com/hassbring)

Name: Gustaf Lidfeldt (lidfeldt@kth.se)
Github: [glidfeldt](https://github.com/glidfeldt)

#### Ps
After trying with exactly 2000, then 1740, then less than 1500, now we have just above 1000 words in LaTeX. 
Previous submissions that somehow fail the word count in a strange manner: #1458, #1460, #1461.

### CODE REVIEW

**Comment by khesoem** [comment]
Hi @hassbring 

Thanks for the submission. Did you change your essay based on the feedback? If yes, please provide a short list of changes in a README file in the same directory.

**Comment by hassbring** [comment]
> Hi @hassbring
> 
> Thanks for the submission. Did you change your essay based on the feedback? If yes, please provide a short list of changes in a README file in the same directory.

Hi @khaes-kth! Yes - changed the essay based on all actionable feedback given. Will update with a README.md file.

**Comment by khesoem** [comment]
Good. Please ping me when you are done with the update.

**Comment by hassbring** [comment]
@khaes-kth Done. Updated the README file in the same directory. Please let me know if there is anything else you'd like us to fix. I'll go ahead and paste the update below in this comment as well: 

## Changes following feedback
* Most feedback suggestions from [#1403] addressed. Some left out due to extensive restructure of the essay. Examples:
  * Sources: complete restructure, Harvard style, doubled amount
  * Images / figures: resized, labeled, captioned
  * Section "Practical examples": restructured
  * Deeper reflective linkage to devops

**Pull request merged**
