### PR TITLE
[Submission] Video demo: CD to AWS EC2 using Github Actions

### PR DESCRIPTION
**Pull request by kittytinythai**
# Video demo: Continuous Deployment to AWS EC2 using Github Actions
Proposal PR id #960 

## Members
Axel Elmarsson (axelelm@kth.se), @elmaxe

Kitty Thai (kittyt@kth.se), @kittytinythai

## Agenda
1. Introduction
2. Prerequisites
3. The CD pipeline
4. Set up EC2
5. Set up S3 Bucket
6. Create build script
7. CodeDeploy setup
8. Set up Github actions

## Youtube Link
[Video demo](https://www.youtube.com/watch?v=B04c0lbzMC4)
## Code Repository
[Demo repo](https://github.com/elmaxe/devops-demo-video)

Aiming for a "yes".

|                                             | Yes | No | Remarkable |
|-------------------------------------------- | ----|----|-------------|
|The demonstration is clearly motivated (why it matters for Devops?) | Yes | 🦆 No |  Relates to a hard problem |
|The demonstration is difficult to do | 🦆 Yes | No | Relies on a non trivial infrastructure |
|The demonstration is original | 🦆 Yes | No | The are less than 10 demos on the topic on Internet |
|The video is sublime (eg visually appealing) | 🦆 Yes | No | Excellent narrative |
|The video contains an [easter egg](https://github.com/OrkoHunter/python-easter-eggs) | 🦆 Yes (There's a frame with a link) |  No | Related to the demo |
|There is a code repo to run the demo  | 🦆 Yes | No | 🦆 Code repo with a solid readme |
|The video must contain subtitles which are clear and in proper English | 🦆 Yes | No | 🦆 Clearly understandable voice over |
|The video includes a take-home message | 🦆 Yes | No | Actionable takeaway |

### CODE REVIEW

**Comment by altaired** [comment]
# Overall

Overall the content is good and it is an interesting and very useful subject. Always wanted to learn  to deploy from scratch instead of relying on the tools doing it basically with no interaction at all for you. 

# Strengths
- You go through the whole process and don't skip any steps
- You have a github repository with all instructions which is amazing
- There are clear subtitles that follow the video properly

# Actionable points
- The video is fast, very fast. It is hard to get through it without either pausing from time to time or slowing down the speed. As there is a github repository, you don't need to type it the same time you do it, but in order for the video to show its full value it has to be a bit slower. 
- Would be nice with a bit larger font size in the editor and terminal. Since you use vscode I can recomend going into Zen mode and increasing the font size.
- The last seconds when you've deployed everything, why not show the deployed app instead of a black background.

**Comment by SophieHYe** [comment]
## Good points
* Perfect timing within 3 mins.
* Good to have zoom-in highlights.

## To improve
* The pace is a bit too fast. 
* The font size of the code/text could be larger. Steps are hard to read and follow.
* Would be good to add a motivation of using AWS EC2 and Github actions.
* If you need more time, you can assume the audience know the EC2 and S3 setting, and give external materials of these information to audience not familiar the prerequisite knowledge.

**Comment by LaraRos** [comment]
# Feedback demo day
* A great demo that showcases a very complex setup, I learned something new :)
## Things to work on
* Go through the CI pipeline more in detail, I feel like it’s way too quick
* The speaking speed is very fast, not sure if you can do anything about it though because we only get 3 min :(
* In general, the demo is very quick, I’m not sure how to reduce it but I feel like I need to pause
* I don’t get where the React comes in here, it wasn’t mentioned I think. You could probably remove it all together
* There is a tea kettle sound in the background sometimes, you could remove it to improve the sound quality
* Some background of the systems would be nice, but again you’re quite short on time :(

**Comment by 8ar10der** [comment]
## Feedback
Yuehao Sui

### Overall, Perfect!
* The speaker speaks with clear words and a good voice.
* The content is very clear and the font is the perfect size.
* The steps are as well organised and easy to follow.
* The background is detailed and relevant to DevOps.
* Enough detail and video in 3 minutes
* Nice BGM

### Possible improvements?
* I like your VSCode theme but it doesn't look too good in the video.
* It is better to zoom in on the parts related to the code.
* The sound becomes rather strange after accelerated processing, try to refine the content rather than accelerating the voice.

**Comment by christian-stj** [comment]
### Feedback

#### Strengths
- Lots of content, many services that cooperate
- Great editing and highlighting, easy to follow in the video

#### Improvements
- The video is very rushed, I suggest that you remove some specifics as the video needs more space to breathe. (Did you speed up narration?) I think the rushed feeling is increased when sentences are cut very tight. One sentence starts almost before the next has ended which feels very rushed and unnatural.
- I did not know anything about EC2 or S3 and I felt that a lot of words were being thrown at me with no explanation (IAM also has many occurrences). Now as others mentioned one might assume that the target audience for this video is people with knowledge on the topic but for me, I would like a short explanation. 

#### Summary
Overall a good demo with good editing and content. There is a lot of content and perhaps the scope of explaining the setup of such a pipeline is too much for a 3-minute demo. I would also personally see this demo more as something that explains the services rather than a step-by-step tutorial on how to set it up.

**Comment by andreaskth** [comment]
Overall a nice video! I especially like the background music! Adds a niceness to the video. Generally the video felt a bit rushed at times but I know this was due to the 3 minute limit and there was nothing you could do about that.

**Now for some specific comments as I watched the video:**

It could be nice to mention briefly what an EC2 instance is (and S3 bucket). However, given the time limit this may be hard to do. If you find yourselves in the lucky position of having to add more content (maybe if removing other content), you could consider this as something worth adding.

Nice graphic at 00:09!

At 00:30, the whole script is not visible. Maybe you could add it to the video description?

Around 00:55, very nice highlighting so the viewer can pay attention to what matters. 

At 1:15 you have 1 frame of something flashing by. Maybe that’s your easter egg? Either way it was a bit confusing, hehe.

1:40 you should probably pronounce it C L I and not ”cli”, I don’t think I’ve ever heard it pronounced that way.

At 2:03 it says ’coped’ in the subtitles while it should be ’copied’.

At 2:45 it was very good that you included the code in increments as they were being spoken. This helps the viewer to know which code corresponds to which ”quote” in the voice-over.

Good luck for the final hand-in on Friday!

**Comment by kittytinythai** [comment]
### Actions done based on feedback
- [x] Remove a few sentences (we tried to remove a few parts, but it felt like the instructions got unclear) to slow down the pace a bit. 
- [x] Zoom in the when viewing the editor and the terminal to make the scripts and commands more readable.
- [x] 00:30, the whole script were not visible, add the entire script on the frame
- [x] 1:15, update the easter egg.
- [x] 1:40, change the pronunciation of 'CLI'
- [x] 2:03 fix typo in the subtitles, from 'coped' to 'copied'.

**Comment by elmaxe** [comment]
New video: https://www.youtube.com/watch?v=-5ibP83GhK8
See #1506

**Pull request merged**
