### PR TITLE
Demo submission: Docker monitoring using Datadog

### PR DESCRIPTION
**Pull request by mans-andersson**
# Video demo proposal: Docker monitoring using Datadog

## Members

Eric Vickström (ericvi@kth.se)
GitHub: [Eric](https://github.com/vickstrom)

Måns Andersson (manande@kth.se)
GitHub: [Måns](https://github.com/mansand1)

## Proposal
Demoing the process of setting up a monitoring service for Docker using
Datadog.

We will have some Docker containers running on a local machine and 
after the monitoring service has been set up we will show statistics
such as network usage, memory usage and CPU usage for the different 
containers.

## Submission
In this demo we show how to integrate Datadog with Docker in order to monitor 
your containers. Examples of metrics are CPU usage and network usage.

## Video link
https://youtu.be/nr3X2ilHVGw

## Criteria
These are the criteria we believe that we have achieved.

| Criteria  | Yes  | No  | Remarkable  |
|---|---|---|---|
| The demonstration is clearly motivated (why it matters for Devops?)  | Yes. Explained in the video  |   |   |
| The video is sublime (eg visually appealing)  | Yes. Nice editing.  |   | Yes  |
| The video contains an easter egg  | Yes (dog gifs)  |   | Datadog = dog gifs  |
| The video must contain subtitles which are clear and in proper English  | Yes  |   | Yes, clear voiceover |
| The video includes a take-home message  | Yes. At the end of the video  |   |   |
|   |   |   |   |

### CODE REVIEW

**Comment by christian-stj** [comment]
Here's some feedback from me:

Overall strengths:
- Clear voiceover
- Great animations and editing
- Easy to follow steps (although I did not try it)

Improvements:
- The voice-over from Måns sounds a bit dull and slow, I think it needs more energy for a more capturing demo experience. 

I think it's a very good demo overall and re-recording some voiceovers would make a big difference.

**Comment by oscaralmqvist** [comment]
Overall, I liked the demo and I felt that it had a clear objective throughout the whole demo and it was easy to follow. I really appreciate the timestamps you've included in the description as they also show up in the player, very nice! It could be nice if you specified in the beginning that it will be about Docker specifically, and also perhaps talk/show more about the metrics one can see in the dashboard in the end.  Also, in my opinion, the music was a bit loud so perhaps lower it a tiny bit. Good job!🎉

**Comment by altaired** [comment]
# Overall
Great video with a great tempo. You make a great job showing how simple it is to get started. Definitely want to try out Datadog.

# Strengths

- Good video where you in a good tempo explain all the steps necessary.
- Bonus points for the nice memes 😎
- The subtitles are good and you speak clearly
- Especially nice that you've added timestamps in the video
- Nice with music too

# Actionable points

- As mentioned previously, some parts of the audio could be improved, sounds a bit muffled sometimes.
- Maybe shorten the intro or remove the signup part and spend more time showing the datadog dashboard

**Comment by cpiehl1** [comment]
Excellent demo! Main strength is that it is extremely well edited. Visually very nice, especially the docker setup part. The music is good. Timestamps are a nice addition. Voice-over also solid. I liked the take-home as well.

For a possible improvement, I agree with the above comment saying that the register account part feels useless, and more time should be spent on the dashboard.

**Comment by George-Bassilious** [comment]
Very well done demo! I really enjoyed watching and learning how to monitor docker containers using Datadog and here are some pointers I thought of while watching:

## Positives
* Amazing and nice graphics and editing of the video, was very interactive and easy to follow!
* Loved the background music which makes the demo more interesting to watch
* The description was very good with timestamps showing the different parts and that the video is split into different timestamps
* Very nice actionable information which makes the demo very easy to understand
* The memes and message was nice at the end

## Possible suggestions for improvement
* At 0:57 the subtitles covers the important part of the screen, dont know what the solution is because you used youtubes closed captions system, but just a headsup!
* You could add the github repo to the description if you had one, If not then you can disregard this comment
* Sometimes the background music was to loud, such as the "docker setup" portion of the video where the loud music took away focus from the voiceover
* The voiceover in the last part was a little low, did not really hear what was said and I feel the ending of the video should be more impactful to leave the viewer with a positive vibe after watching the video

**Comment by Chen-Zidi** [comment]
# Feedback

This is a super visually attractive video!:boom: It looks really professional. You use nice animation, attractive topic title and nice background music. The video also has nice and clear subtitles to navigate. Structure is also good with necessary background information. 

Here are possible improvements:

I personally feel the animation flash effect when you start talking about docker is a little bit distracting. The background music at the beginning could be more lower in volume. But current volume also works fine.

In all, excellent video demo, which both fits the course requirement well and is attractive on youtube.:thumbsup:

**Pull request merged**
