### PR TITLE
Open-source contribution proposal: Contribute to DevOps-exercises Repository

### PR DESCRIPTION
**Pull request by AbyelT**
# Assignment Proposal

## Title

Open-source contribution to the DevOps-exercises Repository

## Names and KTH ID

- Abyel Tesfay (abyel@kth.se)
- Valdimar Björnsson (valdimar@kth.se)

## Deadline

Task 5

## Category

Contribution to open-source

## Description

[DevOps-Exercises](https://github.com/bregman-arie/devops-exercises) is a github repository that contains questions and exercises on technical topics, from Software deveopment to DevOps. Contributing to this repository would benefit DevOps as it can help beginners who are starting to learn devops and experienced users. The project has an active community with 24.1k stars and over 500 commits.

The authors have expressed their wish for answers to questions related to Grafana, a observability and visualization tool. We wish to contribute by reading related documentation and finding answers to the questions, as well as formulating relevant questions. 

Issue can be found here: https://github.com/bregman-arie/devops-exercises/issues/4

### CODE REVIEW

**Comment by AbyelT** [comment]
Hello @javierron @khaes-kth is this acceptable as open source contribution? Thanks in advance!

**Comment by khesoem** [comment]
@monperrus @bbaudry : I have seen several proposals similar to this one. What do you think? Are they acceptable?

**Comment by AbyelT** [comment]
I have seen the similar contribution, would it still be alright if i contribute to the repo with different
documentation & answers?

**Comment by khesoem** [comment]
Hi @AbyelT 

Thanks for the proposal, which is totally relevant. Since we have already had several contributions to this project, we cannot accept this proposal.

**Pull request closed without merging**
