### PR TITLE
Feedback: proposal for essay #1167

### PR DESCRIPTION
**Pull request by kittytinythai**
# Feedback
Feedback on Essay: How to use Jira for agile project managment - PR ID: [#1167](https://github.com/KTH/devops-course/pull/1167)

## Members

Kitty Thai (kittyt@kth.se)
Github: [kittytinythai](https://github.com/kittytinythai)

Axel Elmarsson (axelelm@kth.se)
Github: [elmaxe](https://github.com/elmaxe)

## Proposal

We would like to give feedback on the essay *How to use Jira for agile project managment*, [#1167](https://github.com/KTH/devops-course/pull/1167).

### CODE REVIEW

**Comment by SophieHYe** [comment]
Hi,
Thanks for your feedback proposal. The #1080 is not merged yet. You have to wait for the PR merged and then we can merge your feedback proposal.

**Comment by kittytinythai** [comment]
Hello,
It seems like #1080 has been merged, will our PR also be merged soon?

**Comment by SophieHYe** [comment]
Hi, 
I am very sorry I cannot merge your PR now, as other TA has merged another feedback proposal for the same task. 
I understand you made your PR earlier and it's totally our fault.  Next time please make a comment on the target task to state that you will give a feedback for it, then other students and TAs will not miss your proposal.
Could you please make a feedback proposal for another essay or tutorial? I will first look at your new PR. Thanks and sorry!

**Comment by elmaxe** [comment]
How about making it a routine (for future) in the TA team to check the PR (#1080) and see who referenced it first, before accepting anything. Would be great

**Comment by kittytinythai** [comment]
@SophieHYe, I updated the feedback proposal in this PR. The new essay that we want to review is not merged yet, but I hope when it will then our proposal will be merged as well.

**Comment by SophieHYe** [comment]
Thanks for your update! I will keep an eye on their PR and yours.

**Comment by kittytinythai** [comment]
Hello @SophieHYe! It looks like the PR has been merged now 😊

**Comment by kittytinythai** [comment]
Hello @cesarsotovalero @Deee92 @khaes-kth! Could someone pls take a look at our PR and merge it? 😊

**Pull request merged**
