### PR TITLE
Task 3: Open Source Proposal (inigoaa+jmaragna)

### PR DESCRIPTION
**Pull request by jackma-00**
# Assignment Proposal

## Title

_--enable-feature: Consider removing no-default-scrape-port_

## Names and KTH ID

  - Jacopo Maragna (jmaragna@kth.se)
  - Íñigo Aréjula Aísa (inigoaa@kth.se)

## Deadline

- Task 3 

## Category

- open-source

## Description

Prometheus has different features available. However, some of them are not immediately available by default, but they can be enabled using flags. What the community is requesting is to enable some of these features by default. What we are proposing to do is to take this [issue](https://github.com/prometheus/prometheus/issues/13959) and resolve the problem.

Now, an outline of the various tasks we aim to solve:
1. Understand the project architecture and source code.
2. Set up the environment and run the project/tests.
3. Tackle the problem itself:
    - By default, we want the `no-default-scrape-port` feature to be enabled.
    - Add the possibility to disable it on demand.
    - Update the documentation.

**Relevance**

Prometheus is crucial in DevOps for its ability to monitor (Week 7) and analyze system performance in real-time. It helps teams collect metrics, set alerts, and automate responses, ensuring system reliability and quick incident resolution. This enhances the core DevOps practices of continuous integration, deployment, and collaboration.

### CODE REVIEW

**Comment by jackma-00** [comment]
@arejula27 and I are going to tackle this issue. 
We wondered whether saying "Task 3" clearly means we want to deliver on Deadline 3 (October 15th).

**Comment by algomaster99** [comment]
> We wondered whether saying "Task 3" clearly means we want to deliver on Deadline 3 (October 15th).

This has clarified it. Thank you!

I wonder when should we merge this PR. After the contribution in prometheus has been merged or before, @javierron ?

**Comment by arejula27** [comment]
Despite it not being merged yet, I guess it has been approved, so we can start working on it, right?

**Comment by algomaster99** [comment]
Hey! Please start working on it. I will wait for @javierron answer. 😅

**Comment by javierron** [comment]
@algomaster99 This PR is only for the proposal. When the group wants to submit the task, they should open another PR, which adds the links to the contributions to the README file.

**Pull request merged**
