### PR TITLE
Tutorial submission: Deploying NET Core 3.1 services to OpenShift

### PR DESCRIPTION
**Pull request by Goradux**
Would like some feedback on the tutorial. Thanks!

### CODE REVIEW

**Comment by gluckzhang** [comment]
Hi @Goradux , same as the previous PR, you need to register your feedback request according to this: https://github.com/KTH/devops-course/blob/master/contributions/feedback-planning.md

**Comment by bbaudry** [comment]
Feedback for #569

Thank you for the early completion of this tutorial. The topics discussed and illustrated here are clearly relevant for the DevOps course. The tutorial is well structured. My main feedback is to make the tutorial more self-contained and easier to follow for the reader.

- Introduction
  - add name of second author, Albert Asratyan
  - add brief introduction to Openshift, what it is and why it is an interesting technology
  - add brief introduction and motivation about .net core 3.1
  - NB: this point is too detailed and hard to understand that early in the tutorial
- Microservices
  - add pointers to external references for the reader who wants to know more about Microservices
  - "Because of this, microservices are an ideal solution for deployment to OpenShift." -> difficult to understand this statement for someone who does not know about OpenShift or about microservices. Add a little explanation.
- Setup
  - "To call the POST endpoint I suggest downloading Postman and sending a request:" Add simple instructions to install postman and to test the POST endpoint locally
- Create and setup Docker image
  - "Make sure you have Docker installed" Provide simple instructions / pointers to do this
  - add pointer to a basic tutorial about Docker
  - "try going to the root folder", provide some context and instructions so the reader does not have to 'try to go' there, but has exact instructions to do so
  - " Try typing into" -> same as above, the reader should not need to try, but should be able to follow instructions. Here, replace by "Paste .."
  - "publish the image to docker image" -> to Docker hub
  - "right click on the project and click publish" -> in which environment?
- "Running the docker image"
  - "One you have opened up the console ...". This is a long paragraph with instructions and no screenshot. Please, make sure that a reader can follow these instructions with no difficulty (menus are clearly visible, unambiguous, etc.)
  - in this section you give lots of instructions. Please, add some explanations about what is happening. For example,  what is a route for an endpoint?
  - "improve the API in a way that would use more resources and maybe do some workload testing" -> this is a very good suggestion. Can you add a richer version of the API in the Github repo, so the reader of the tutorial can try to run this improved API following the same instructions?
- Add a conclusion about you expect the reader to learn with this tutorial, the benefits of learning this and some pointers for further reading and learning on this topic

Typos
- it’s downsides -> its downsides
- One you have opened -> Once you have opened

**Comment by gluckzhang** [comment]
Hi @Goradux , any updates on this PR after the feedback? I'm considering to merge it today.

**Comment by Goradux** [comment]
Hi, @gluckzhang. We have updated the tutorial, but since we have published it on Medium, the changes are not visible here. Our group thinks it can be merged/closed.

**Comment by gluckzhang** [comment]
@Goradux I see. Then let's simply close this one. Thanks!

**Pull request closed without merging**
