### PR TITLE
Week 4: Scientific Paper Proposal (atheers-miladsf)

### PR DESCRIPTION
**Pull request by Atheer2104**
# Assignment Proposal

## Title

Quality Assurance in MLOps Setting: An Industrial Perspective

## Names and KTH ID

  - Atheer Salim (atheers@kth.se)
  - Milad Farahani (miladsf@kth.se)

## Deadline

- Week 4

## Category

- Scientific paper

## Description

We want to perform a presentation on the scientific paper [**Quality Assurance in MLOps Setting: An Industrial Perspective**](https://arxiv.org/abs/2211.12706)
This paper looks at the quality assurance (QA) of MLOps by taking an industrial perespective, it presents real-life examples but also talks about the challenges that arise
in industrial MLOps. 

**Relevance**

This paper is relevant to DevOps because it explores the field quality assurance in the MLOps setting but with focus on the industry. It's relevant since it's about MLOps but also 
that we get insight on how things actually are in the industry.

### CODE REVIEW

**Comment by Atheer2104** [comment]
@javierron Is there any reason for this proposal has not been yet merged in, it's also for this week

**Comment by javierron** [comment]
Hi @Atheer2104, I have asked for the opinion of the other TAs about the paper and the venue, since it's MLOps is not my expertise.

**Comment by javierron** [comment]
@Atheer2104 The paper you have selected has no citations, and the venue of publication is not well-known. Would you consider presenting one of the following papers, which are published in more established venues?
- A Joint Study of the Challenges, Opportunities, and Roadmap of MLOps and AIOps: A Systematic Survey (https://dl.acm.org/doi/full/10.1145/3625289)
- On the Understandability of MLOps System Architectures (https://ieeexplore.ieee.org/document/10440483/)

**Comment by Atheer2104** [comment]
@javierron I understand, we thought that if it was available on IEEE then that would be good enough, but can we present this paper instead [Quality Assurance in MLOps Setting: An Industrial Perspective](https://arxiv.org/abs/2211.12706) this was suggested by @bbaudry previously

**Comment by javierron** [comment]
@Atheer2104 Sounds good, please update the proposal, and I'll merge.

**Comment by Atheer2104** [comment]
@javierron we have updated the proposal now

**Comment by Atheer2104** [comment]
@javierron Ping!

**Comment by NoelMT** [comment]
# Feedback 
By Sam Khosravi (samkh@kth.se), Noel Tesfalidet (noelt@kth.se)
Number of Words: 1127

## Code of Conduct 
I/We certify that generative AI, incl. ChatGPT, has not been used to write this feedback. Using generative AI without permission is considered academic misconduct.

## High Level Overview

### Strengths
- The presentation gives a great overview of what the paper covers, questions that the paper answers and presents the results effectively.
- The MLOps software architecture was presented in a comprehensive manner and the visual pyramid click through both provided information as well as kept to the flow of speech, and was visually pleasing
- The illustrations/figures set in this presentation do a great job at keeping the listeners engaged, and makes it easier to follow.
- The proposed architecture part of the presentation was very well presented in form of speech and material
- Lastly, the presenters clearly put a lot of effort into training for this presentation and their speech is clear with great tempo and tone.
- Presentation looks good visually 
- Good switches between who speaks, which makes it much more engaging. It would be very hard to listen to one person speak for more than 30 seconds, and you do this switch well.

### Weaknesses
- Even though the proposed architecture was presented well, it could benefit from more interactive components. For example, you could have at appropriate moments of speech highlighted different parts of the architecture.
- In the part “Quality Assurance Challenges in Industry” you speak a lot during each bullet point. The speech is good, but you would benefit from either sub bullet points, or making each bullet point into its own slide where you add more visual components that help understanding what you talk about. Especially point 1 and 3 need this, but if you do it on one bullet point, it would be natural to do it on all of them.
- The presentation could have benefited from some visual component letting the viewer know where in the presentation structure we currently are. 
- When presenting the authors, it was very funny as you said “these are the authors” then the next second skipped over it. It would be funny to have but might not suite the vibe of this type of presentation.
- The introduction would need a click through for it to be smoother. Also, here there are too many figures which you click through too fast without giving any context about.
- The first slide could be skipped, and you could integrate it into just saying the name of the paper instead of having an introduction.
- Bring up more about what the related papers are about.


## Additional Material
We were interested in the testing of these machine learning models and how the different architectures are impacted. We found this paper [Test & Evaluation Best Practices for Machine Learning-Enabled Systems](https://arxiv.org/abs/2310.06800) that looked at existing testing techniques and how they can be adapted to ml model testing. This is a bit outside of the paper maybe but I still think it could be interesting to talk about things like how regression testing would work in the architectures proposed in the presented paper. This paper also touches little bit about the deployment problems and in the edge architecture it might also have similar problems.

## More Detailed Feedback 

### General
In general, we know that you did not have much time to prepare, as your previous paper was denied and you got a new one in short notice. Regardless of this, the amount of training you have done so far is impressive, and it flows on surprisingly well when considering the time frame you had to practice. We understand that the focus for you has not been on making visually appealing slides and transitions, but rather on material and memorizing the text. However, we would advise you to maybe focus on this more to complement your amazing speech and material. A wise man once said “Even the finest champagne tastes flat if served in a paper cup”😉 , so even if your speech is good, the presentation needs to be visually pleasing as well!

### Introduction
As previously said, you could both save time and have a smoother transition if you start by saying the name of the paper, instead of a short introduction to the area of research. This would make it so that you would not have to stress through the presentation of authors. Also, you decide to present the authors, you can either just present the main author or just skip over it. Also, the picture in the introduction showing the MLOps pipeline is clear, but as the introduction is relatively short, it would benefit by highlighting each part you are speaking about, otherwise it makes it harder for the audience to actually interpret the paper.

### Slides about MLOps Software architecture
Here the pyramid picture was super good! We really enjoyed seeing it build up, and it helped the flow of your presentation! The first picture was good as well on the first slide, but could use a tiny bit of explaining more, but this is not that important, just a little side note. I was also a little bit confused during the presentation since the illustration is just one big architecture or if it is three separate ones but this was cleared up after. Might be good to mention that these different configurations can work together if you find the time. Regardless this is a small thing and might just be us that are slow :)

### Slide about Quality Assurance Challenges in Industry
The material on these slides is very really good! However, this is the most lacking slide. You would benefit from many different things, which we understand you guys already most likely have thought of but have not had the time to implement yet. Firstly, the speech is too long for each bullet point. The material is good, but to be able to hang with the presentation we would have enjoyed either sub bullet points, or for you to turn each bullet point into its own slide. In this way, you could add more interactive components (which you could click through) which would aid your speech. Once again, points 1 and 3 were especially long, so these are the ones that need the actual fixing, but if you add something here it would be natural to do so on the other 3 bullet points.

### Slide about Proposed Architecture
This slide was amazing! Both the text and the material. Even though the entire presentation held a high level, this was the highlight! The only thing here would also be to add some interactive components on the figure of the proposed architecture to highlight each part you are speaking about!

### Slide about Critical Part
This was good and brought forward justified criticism about the shortcomings of the paper! We liked that you clicked through each point.

###  Slide about Take Home Message
The take home message was broad but still covered the area of the topic, as well as reflecting the seeming thoughts behind the authors of the paper. Good job!

**Pull request merged**
