### PR TITLE
final submission video demo

### PR DESCRIPTION
**Pull request by Internet-Person-IP**
## Members

Taqui - taqui@kth.se
GitHub: [Internet-Person-IP](https://github.com/Internet-Person-IP)

## Initial Proposal: 
[#1007](https://github.com/KTH/devops-course/pull/1007)

# Submission

The final product can be found [here](https://www.youtube.com/watch?v=jrQqf5s2XRk).

## Grading Criteria

|                                             | Yes | No | Remarkable |
|-------------------------------------------- | ----|----|-------------|
|The demonstration is clearly motivated (why it matters for Devops?) |  💍 Yes | No | Relates to a hard problem |
|The demonstration is difficult to do | 💍 Yes | No | Relies on a non trivial infrastructure |
|The demonstration is original |  💍 Yes | No | The are less than 10 demos on the topic on Internet |
|The video is sublime (eg visually appealing) | Yes | No | Excellent narrative |
|The video contains an [easter egg](https://github.com/OrkoHunter/python-easter-eggs) | Yes | No | 💍 Related to the demo |
|There is a code repo to run the demo  | Yes | No | Code repo with a solid readme |
|The video must contain subtitles which are clear and in proper English | Yes | No | Clearly understandable voice over |
|The video includes a take-home message | Yes | No | 💍 Actionable takeaway |

### CODE REVIEW

**Comment by Internet-Person-IP** [comment]
@khaes-kth I hope this is correct now. Thank you for your suggestion.

Best Regards,

Taqui

**Comment by Ackuq** [comment]
Very interesting demo! It was clear what was going on and easy to follow along. It is a lot of information being presented but I think you did a good job in picking out the important parts.

I would say that the video editing could be improved, for example between 1:18-1:30 where there’s a lot of non-needed space being occupied, which could probably be solved by some scaling and cropping.

I am also not too sold on the amount of slides that are present in the demo, I would much prefer if you actually explain the commands and the full flow while using them in the demonstration.

Furthermore, the description of the video needs more info, for example a link to the repository with your code and the services you used. If this is added, make a reference in the video and explain that “the full source code and configurations can be found in the GitHub repository in the description below”.

**Comment by Sebberh** [comment]
The image-quality was good, everything on the screen was readable and clear. However, you don't show how to actually set up what you are proposing. A large part of the instructions are just shown as slides with commands printed on them. This is in my opinion the most important thing to improve.

You also say that we will find information in the description, but it's empty.

It's positive that you have a voice-over but the audio-quality could be improved. It sounds like there are at least 3 different recordings, all of different volumes or in different rooms. Additionally, it sounds like you are screaming at the audience and that's pretty off-putting.


Nitpicks:
- You mention a "DQE-cluster" in the beginning but doesn't explain what it is.
- You say micro service in the slides through almost the entire presentation but switch to just service at the end, why?
- The sentence "A common practice is to leverage monolithic applications to build an entire application" sounds weird.

EDIT: Sorry if I have been too blunt, I currently have Covid-19 and feel pretty under the weather

**Comment by glidfeldt** [comment]
# Feedback
Good job! My feedback is divided into strengths, weaknesses, actionable feedback and grading.
## Strengths
* You had a good easter-egg!
* The introduction and take-home message was good and relevant to the subject.
* You demonstrate clearly what you do and the README.md helps if you want to do it yourself.

## Weaknesses
* Poor audio quality in the beginning (I especially had a hard time hearing your opening line). The audio quality improved after your introduction.
* You combined screen recording with slides for your tutorial. In would have preferred if you only showed how you do it in a terminal.

## Actionable feedback
* Consider improving your audio quality
* When screen recording, maximize your window so that empty space isn't seen.
* You should add a description to your GitHub repo if someone would like to try to do what you're doing on their own.

## Grading
I agree with the grading criteria aim that you state above

**Comment by MDRezaulHasan** [comment]
Good Work.

1. Informative idea and also practical aspects
2. Nice presentation
3. Clear concept 
Improvements:
1. Voice is a little bit louder which makes the speech unclear at some point.

**Pull request merged**
