### PR TITLE
[Submission] Tutorial: Serverless Applications on Heroku

### PR DESCRIPTION
**Pull request by Ackuq**
# Tutorial: Serverless Applications on Heroku

## Members

Axel Pettersson (axp@kth.se)
GitHub: [Ackuq](https://github.com/Ackuq)

Felix Seifert (fseifert@kth.se)
Github: [felix-seifert](https://github.com/felix-seifert)

## Description

Heroku is a webservice where users can run simple web applications for free for a limited number of hours per month. The obvious approach is to run serverless applications which are billed per second. However, Heroku does not offer the option to deploy serverless applications of-the-shelf.

We found a way on how to use Heroku's One-off Dynos, which are not addressable via HTTP requests, to process Functions-as-a-Service via providing arguments via environment variables. This approach is mentioned on the web only a single time. We want to create a tutorial on how to use Heroku to deploy a serverless application. This tutorial requires interaction with both Heroku and GitHub and goes through every major step in making it possible, as well as providing a frontend UI you can use to test your own serverless functions or even use to build your own frontend.

the tutorial is present both in the GitHub repository linked below and in generated tutorial website, created with GitHub pages. To accompany this tutorial, a Medium article was created to hopefully make the tutorial gain more public traction.

## Link to GitHub repository

https://github.com/felix-seifert/serverless-on-heroku

## Link to generated tutorial website

https://felix-seifert.github.io/serverless-on-heroku/

## Accompanying Medium article

https://axel-84042.medium.com/going-serverless-on-heroku-using-one-off-dynos-79b6fd85705a

## Easter egg hint

<details> 
  <summary>Click me for hint</summary>
  ⭐
</details>

### CODE REVIEW

**Comment by Ackuq** [comment]
Feedback to be published by @ChristopherGustafson #1100

**Comment by ChristopherGustafson** [comment]
Just created the PR for my feedback, see it here: #1217. Thanks for an awesome tutorial, it was very well done and I really enjoyed working through it. Well done guys! :)

**Comment by felix-seifert** [comment]
@ChristopherGustafson Feel free to leave a comment in the ['Issues' section](https://github.com/felix-seifert/serverless-on-heroku/issues/4). :)

**Comment by felix-seifert** [comment]
We implemented the feedback provided by @ChristopherGustafson in #1217. We created a [PR for the feedback implementation](https://github.com/felix-seifert/serverless-on-heroku/pull/6).

**Comment by felix-seifert** [comment]
@Deee92, according to the recent of @monperrus in the lecture, I want to check whether the changes after the feedback are registered. Do we have to change anything for the feedback implementation being recognised?

**Pull request merged**
