### PR TITLE
Essay submission: Investigation of Containerization Solutions (#1009) 

### PR DESCRIPTION
**Pull request by vickstrom**
This the submission following proposal #1009.

### CODE REVIEW

**Comment by vickstrom** [comment]
Ping @lazarko. Looking forward to the feedback!

**Comment by lazarko** [comment]
## Feedback on each part of the essay:
Submission: [#1344](https://github.com/KTH/devops-course/pull/1344)


Original authors: @vickstrom and @oscaralmqvist 
### Title
The title is good and representative of the essay. Names of the authors and date are fine as well. 
### 1. Introduction
The introduction gives a good problem formulation about the subject of 
containerization. The introduction states as well the goal of 
the essay clearly. Things that you may take into considerations are: 
* I did not fully understand to which sentence the citations belongs to. It can be
worth checking out [this](https://academia.stackexchange.com/questions/85477/where-should-citations-be-placed-relative-to-punctuation-e-g-full-stops-and-c) to exactly know where to position the citation. 
* Last sentence in the Introduction section contains two "and", which is something
that tends to be avoided.
### 2. Containers
This section explains what containers are and industry standards (OCI), including Docker and Podman. This is done professionally and there are no 
improvement suggestions other than what has already been stated in the previous section, that is the placement of citations. 

### 2.1 Relation to Virtualization
In this section containers are compared to virtual machines, and the difference between them is coherently presented. Once again, the positioning of the citations could be improved 
in order to make it clear to the reader which sentence it belongs to. I have also noticed sometimes the comma sign is overused. It is not something game-breaking, but it can be interesting to read more about it [here](https://www.scribendi.com/academy/articles/comma_rules_for_the_comma_obsessed.en.html). For
example "So, for a virtual machine, a complete installation ..." there are two commas close to each other. Once again this is an optional refactoring. 
### 2.2 Containers and DevOps
Good section about containers and devops; explaining the relation between the concepts. 
### 3.1 Open Container Initiative
This section gives an interesting insight on the OCI, by describing its principles and goal. 
### 3.2 Containerization Technologies
There are two sentences in the beginning of the first subsection paragraph: " Additionally, Docker is OCI compliant. Docker utilizes client-server
architecture." that are short (one is only 5 words). The sentences could be merged into one normal-sized sentence. Specify who do you mean with "you" (a bit informal): the reader, client, programmer? 


Overall I think that the description of the container technologies are well-founded and good. I like the comparison between Podman and Docker, including difference between them. 
### 4 Comparison
A good and deep evaluation of the container technologies in regard to security aspects. For the evaluation to be more nuanced maybe mention a couple more aspects that could be used to determine which technology is good or bad.
Other than you clearly state both positive and negative things about the container technologies. 
### 5 Conclusion
Well written conclusion, short and concise that describes the main takeaways from the essay. Good job!
### References
The references look good and there are more than 10 references, which is what the criteria ask for.  
## Overall impressions of the Essay
My overall of the essay is that it is well-written, structured and factual. The 
essay covers a topic that is definitely relevant to the DevOps subject. There is an introduction which states the aim and goal of the essay. Every concept, feature or technology brought 
up in the essay is carefully explained, with support of references. The essay presentation is elegant, and I am guessing that it is done with LaTeX which is good.

There are minor things that I have already suggested for improvement (citations, commas and some grammatical things), but it would 
also be good if a figure or listing would be added for the reader to get an overview of some subject. Adding figures does not directly add to the word count, but it can through referencing so be careful. The Best thing would be if you could maybe create your own figure (in Word or some other program). Another thing that could be added in the introduction is that you intend to evaluate 
the containerization solutions based on security aspects. Many things that are mentioned as suggestions for
improvement are just details, and some are even optional. 


Other than that I had a very positive experience with reading through the report. I learned more about container technologies, the container standards and difference between containers. Well done! :D

**Comment by oscaralmqvist** [comment]
Thanks for the feedback! These are the changes we've implemented:    
- Rewords the last sentence of the introduction (multiple `and`).
- Fixes references to correctly follow the IEEE citation style.
- Rewrites some commas in section _2.1 Relation to Virtualization_.
- Adds image to _2.1 Relation to Virtualization_
- Concatenates short sentences in _3.2.1 Docker_.
- Removes informal usage of `you` in _3.2.1 Docker_.
- Adds a one more aspect to _4 Comparison_.

**Comment by SophieHYe** [comment]
Thanks for the final essay submission. I am now merging your PR and we will grade your work based on the final version.

**Pull request merged**
