### PR TITLE
Demo PITest: Final submission

### PR DESCRIPTION
**Pull request by louisezetterlund**

### CODE REVIEW

**Comment by Zodbigt** [comment]
I will give feedback on this one

**Comment by jonasjohansson8908** [comment]
I will give feedback on this demo, PITest sounds interesting

**Comment by JohanKJIP** [comment]
I will give feed back on this one as well

**Comment by SoFoDa** [comment]
I will also give feedback

**Comment by sashikanthr** [comment]
I will give feedback

**Comment by jonasjohansson8908** [comment]
Overall a really good demo!

I liked that you had a voice-over, that really made it easier to follow the steps shown in the demo. You gave good explanations and I always felt like I understood what was happening.

There are some things that could be visually improved. E.g. the green screens at 0:08-0:09 and 0:45. I believe they can easily be cut in a video editor.

I found the bullet points in 0:12 to be a bit distracting. Especially since the second bullet point isn't presented until 0:47.

I especially liked the interactive parts, where you show your tests and how to install PIT. Also the improvement of a test

You also could consider adding an easter egg if you plan to fill that criteria.

Good job!

**Comment by johannaii** [comment]
@jonasjohansson8908 
Thank you so much for your feedback! 
We will definitely try to remove the green screens in the demo. We don't know why they ended up there (they are not visible in Adobe Premier Pro), but there should be someone else who had the same problem that could help us. 

P.s. We have an easter egg in the screencast ;-)

**Comment by sashikanthr** [comment]
I wanted to know about PIT, as the demo I worked on has PIT as a test selector. It was a nice presentation with a smooth narration. I liked the example of how mutation tests are different even if we have a 100% code coverage. That I think gave me a better understanding.

I see visually it is attractive as well. Just a very minor point. When you show that the mutant is killed the screen jumps to the Conclusion immediately. You can have may be hold like a 3-5 second window to show it clearly. 

Nice work!

**Comment by JohanKJIP** [comment]
Really good demo!

You introduce us to the demo and clearly explain what mutation testing is and why it is important, very good. A very small detail during the introduction is that the cursor is visible during the "What and why?" part. 

At 1:24 your test in `Testing isPositive` tests if 0 is a positive number. Later, when installing PIT this test is suddenly changed to testing if 1 is a positive number. This might be confusing when you later run PIT and change it back to what it was at 1:24. 

Good conclusion and take-home message.

**Comment by Zodbigt** [comment]
Thanks for the demo!
An obvious thing that I think you already know. But the video has some green screens at some parts of the video. If that could be fixed that would be awesome. 

You talk loud and clearly in the video so it's easy to follow.
Suggestion add some background music that fits the theme :) .

Good job with demo and the easter egg!

**Comment by SoFoDa** [comment]
Overall, really nice demo! You speak clearly with a nice tempo which makes it easy to follow. The installation process is explained very systematically and should, therefore, be easy to replicate. Also, the example is intuitive and shows the effectiveness of mutation testing. Could quickly mention in the beginning how the topic relates to DevOps if someone who is not as familiar with specifically DevOps would see the demo. You could, for instance, reference the image where you highlight the test phase of the DevOps cycle.

**Comment by pojans** [comment]
Cool demo! I think the demo is very clear and it was very easy to follow every step of the way. I also think it looked very nice from beginning to end. 

This is definitely related to the Dev in DevOps, however, to snag some extra bonus points, you should maybe say a few words in the beginning of the video about this (I am nitpicking). The thing you 

One thing you can change is: The green screen that pops up between the scenes should probably be removed.

I wish you the best of luck!

**Comment by johannaii** [comment]
@SoFoDa @Zodbigt @JohanKJIP @sashikanthr @pojans 

Thank you all for your feedback!
We will definitely fix some of your comments, and we appreciate that you have taken your time to find improvement areas for our screencast. 

If anyone one of you did not found our easter egg, but really want to know what it is, we can give you a hint :-)

**Comment by valsen** [comment]
I'd like to give some feedback here too:)

**Comment by valsen** [comment]
Great job with the demo! The slow pace made it easy to follow along with all the steps, and the introduction explaining what mutation testing is was concise and appropriate for the difficulty level you seemed to aim for in this demo. My only advice would be that you could dig a little deeper and perhaps show us something a little more advanced. But perhaps there is not much else to say about mutation testing? I don't know! But great job!

**Pull request merged**
