### PR TITLE
Course automation submission: Checking essay requirements

### PR DESCRIPTION
**Pull request by Atema**
# Course automation: Checking essay requirements

## Members

Martijn Atema (atema@kth.se)
GitHub: [Atema](https://github.com/Atema)

## Submission

With my submission, I aim for the following grading criteria. Further explaination is given in the sections below. The configuration (workflow) file required for this action is part of the same PR as this file.

|                                             | Yes | No | Remarkable  |
|-------------------------------------------- | ----|----|-------------|
|The work is done before April 6, 2021 (in order to be useful for the course) | Yes | No | n-a|
|The automation task produces a PR status or issue / PR comment | **🔥 Yes** | No | Points to a generated page with valuable additional information |
|The automation task is reusable | **🔥 Yes (next year for this course)** | No | **🔥 In other courses than this one** |
|The task runs on a standard platform | **🔥 Yes (Github action)** | No | Other platforms (e.g. Moodle, Canvas) |
|The task is praised by the other students of this course | 🙏 Yes | No | n-a |
|The code for the task is available | **🔥 Yes (public repo)** | No | **🔥 Well documented repo** |

## The action

I developed the action in JavaScript to run on the GitHub Actions platform; it is available in [Atema/pdf-essay-checker-action](https://github.com/Atema/pdf-essay-checker-action). Documentation is available in the repository's README, and includes all options that can be customised, together with a sample configuration that shows how to install the action in your own repository (using a workspace file). Because the action is customisable using input parameters, it is perfectly reusable in future iterations of this course, as well as other courses. It supports setting the minimum and maximum limits for the checks, and supports two ways of reporting the results (as the status of the action, and as a comment on the PR).

## Word count

[PDF.js](https://github.com/mozilla/pdf.js) is used to parse the text of the detected PDF files, after which [words-count](https://www.npmjs.com/package/words-count) is applied for accurate multi-language word counting. In general, the results of this method should be very similar to the counts generated by the recommended combination of `pdftotext` and `wc -w`, although there will probably be slight differences. For this reason, I have set the minimum and maximum count to 1800 and and 2200 respectively (2000 +- 10%). If wanted, these margins can easily be decreased by changing the configuration file.

## Plagiarism checking

A component that should have been part of this action, but is not, is plagiarism checking. It turned out to be impossible to include this service properly. Although there are several services available online, they are all closed and paid, and it is unclear how reliable they are. I'm aware that KTH has an agreement with [Ouriginal](https://www.ouriginal.com) (previously Urkund); however, they do not have an open API (it is only available to selected partners like Canvas).

### CODE REVIEW

**Comment by khesoem** [comment]
Hi @Atema 

Please remove the `.github/**/.yml` file from this PR. We will integrate your great contribution into the repo ourselves later.

**Comment by Atema** [comment]
@khaes-kth Done

**Comment by khesoem** [comment]
Hi @Atema 

Have you tested your Github Action? If yes, can you send a link to the test PR?

**Comment by Atema** [comment]
@khaes-kth I've tested in a separate (private & now deleted) repo. I'll create a test PR & send the link later tonight.

**Comment by Atema** [comment]
@khaes-kth Sorry, was working on another assignment yesterday and forgot. I created a PR in this repo: https://github.com/KTH/devops-course/pull/1488; the check itself works, but the comment function doesn't (it probably doesn't get the right permissions because it hasn't been merged yet). The PR in my own fork works completely: https://github.com/Atema/devops-course/pull/1.

**Comment by khesoem** [comment]
Great! Please create a new PR and change your readme and add a link to the test PR in your own fork.

**Pull request merged**
