### PR TITLE
Covid-19 proposal: Covid-19 Cases by Counties

### PR DESCRIPTION
**Pull request by perfah**
# Covid-19 Cases by Counties

## Members
Per Fahlander (perfah@kth.se)
Joar Ekelund (joarek@kth.se)

## Description
Write a webserver in Python that fetches and presents [official CSV-data from DGG (Myndigheten för digital förvaltning)](https://www.dataportal.se/sv/datasets/525_1424/antal-fall-av-covid-19-i-sverige-per-dag-och-region) on the number of COVID-19 cases per Swedish region/county. This data would be presented on a website with a graph plotting the development of newly confirmed cases in any region (with available statistics).

## Motivation
The official website from Folkhälsomyndigheten does not show newly confirmed cases per region/county in graph-form. It would be a nice addition to be able to see a plot on the development in specific regions since it is hard to see trends from data sheets.

## Ties to DevOps
We will use the following DevOps-related practices in the development of the script:
- GitHub for version control.
- Travis CI + PyTest (or similar) for unit and integration testing (including end-to-end testing by mocking a webserver and giving it http-requests)

### CODE REVIEW

**Comment by gluckzhang** [comment]
Hi @perfah , the idea sounds good. As you mentioned to apply CI, my question is:

- What form is your application? Is it a client-side python script, or a webserver implemented in python?
- What kind of tests will you have for your application?

Could you clarify this, thanks :) Note that only implementing a script that fetches and plots the data, may not be considered as sufficient. You could try adding some complex features, or enhancing the CI/CD pipeline for your project. Monitoring after development is also an idea to consider.

**Comment by perfah** [comment]
We are just now considering a webserver in Python, but have to admit that we are a bit unsure of what kind of tests would be appropriate in this case. Would testing HTTP-requests with the CI be considered sufficient? If not, what do you think would?

**Comment by gluckzhang** [comment]
Hi @perfah , that would be nice if you could have both unit tests and integration tests. For example, some methods could be directly tested with PyTest or similar tools. You could also setup the server and send HTTP requests to test it (feels like end-to-end tests).

**Comment by perfah** [comment]
@gluckzhang Hello again, we are happy to take on what you are suggesting! Tell us if there is anything else :)

**Comment by gluckzhang** [comment]
@perfah , perfect. Nothing else, but please update the `README` according to our discussions. Thanks :)

**Comment by perfah** [comment]
@gluckzhang I have now updated the proposal

**Comment by gluckzhang** [comment]
Thanks for the updates. The PR has been merged :)

**Pull request merged**
