### PR TITLE
Essay proposal: Comparison between continuous testing vs automation testing

### PR DESCRIPTION
**Pull request by MDRezaulHasan**
Hello, I want to write an essay based on continuous testing vs automation testing.

### CODE REVIEW

**Comment by MDRezaulHasan** [comment]
I am writing an essay based on testing in DevOps topic.  Can you marked my essay?

**Comment by MDRezaulHasan** [comment]
The motivation of this essay is to clear the concept of testing related to DevOps. Some differences in continuous testing and automation testing and make pure reliable concepts about the developing software in the IT industry.

**Comment by MDRezaulHasan** [comment]
Hello Zhang,
I am just updating my readme file with my motivation for the essay and
send it with a new pull request. And I will change my PR whole ppt file and
make a new ppt with the more technical concepts.

**Comment by gluckzhang** [comment]
@MDRezaulHasan you could submit a new PR, but if the topic is the same, it's even better to stay on this one since it's traceable.

I don't recommend a title like "Testing in DevOps" because the scope is too broad. It's good to be focused. As you mentioned, your motivation is to clarify concepts of testing, there are many concepts, what are the concrete ones you are going to explain? If you choose "continuous testing" and "automation testing", you could just use "continuous testing vs automation testing" or something similar as the title. Still, you need to distinguish from the existing articles which also discuss this.

**Comment by MDRezaulHasan** [comment]
Ok, I will make the title is a "comparison with continuous testing and
automation testing". For the PR I remain the same topic but I will change
the ppt.

**Comment by MDRezaulHasan** [comment]
I am updating the title as "Comparison between continuous testing vs automation testing".  Is it ok now?

**Comment by gluckzhang** [comment]
I will merge this PR, though it's still not perfect. Next time please submit one PR for one task update (you could create different branches for different PRs instead of putting everything in your master branch, if you want to submit several PRs at the same time).

**Pull request merged**
