### PR TITLE
Updating folder name

### PR DESCRIPTION
**Pull request by nagavem**
Folder name had my github account and now replaced with kth id

### CODE REVIEW

**Comment by SophieHYe** [comment]
Hi，
Could you please update the existing folder name: mjza-chikafa-nagavem, otherwise, there will be two folders. Thanks!

**Comment by nagavem** [comment]
@SophieHYe  I did not understand unfortunately,I have updated the existing folder name itself and raised this PR,have not created another folder.
Should i rename it on the git desktop client?

**Comment by gluckzhang** [comment]
@nagavem , if you take a look at your PR branch ([nagavem:patch-13](https://github.com/nagavem/devops-course/tree/patch-13)), you will see the previous folder still exists but you created another file with the name `mjza-chikafa-vemula`.

**Comment by nagavem** [comment]
@gluckzhang as my teammate has raised the initial pr I cannot modify the file from my side(permission is not available) ,I have notified him of the same but it might take time as he does not have access to a device currently.

**Comment by gluckzhang** [comment]
@nagavem , all right, I have corrected the folder's name. This PR is closed now :)

**Pull request closed without merging**
