### PR TITLE
Efranz-maxwik presentation week 8

### PR DESCRIPTION
**Pull request by Emilcrafter**
# Assignment Proposal

## Title

Next.js & Vercel vs. other providers - a conflict of interest 

## Names and KTH ID

  - Emil Franzell (efranz@kth.se)
  - Max Wiktorsson (maxwik@kth.se)

## Deadline

- Week 8

## Category

- Presentation

## Description

Vercel provides hosting and CI/CD for many different front-end frameworks. Most notably their own framework, Next.js. As Next.js has grown to become one of the world's most popular web frameworks, Vercel has also grown a lot as a company and is now one of the biggest CI/CD providers. Their serverless hosting option is a great option for quickly deploying your app to the web. Other providers such as Netlify and AWS Amplify also provide this service, but why should Vercel allow them to take market share. We believe there is a case for Vercel intentionally introducing breaking changes into Next.js (for serverless) to stay on top of the competition.

**Relevance**

As Vercel is one of the biggest CI/CD providers, we think that a discussion about this company is highly relevant for this week. We want to discuss the conflict of interest related to companies that both manage open source projects and provide CI/CD or other services related to these projects, where other companies may want to take market share by providing similar services.

### CODE REVIEW

**Comment by Deee92** [comment]
Hi @Emilcrafter, this presentation would be interesting and very relevant for week 8 when we talk about the cultural and legal aspects of DevOps. Wdyt?

**Comment by Emilcrafter** [comment]
Yes, I think that makes sense. Thank you!

**Comment by Deee92** [comment]
Good! Can you change your PR proposal accordingly, and also move the README to week 8?

**Comment by Deee92** [comment]
Hey again. Please move the README also to `contributions/week8/presentation/`.

**Pull request merged**
