### PR TITLE
Tutorial proposal: Apache on docker

### PR DESCRIPTION
**Pull request by phwes**

### CODE REVIEW

**Comment by gluckzhang** [comment]
Hi @phwes , thanks for the proposal. I'm afraid that only talking about deploying Apache server on Docker does not contain sufficient technical contribution. Maybe you could consider to add the following ideas:

- also introduce network communications among containers, because a web application usually connects to a database server, which could be dockerized as well
- introduce the differences between `volumes` and `bind mount`

What do you think?

**Comment by phwes** [comment]
@gluckzhang That sounds great!

I will do that as well then.

**Comment by gluckzhang** [comment]
@phwes , perfect. Please adjust the `README` according to our discussion. Then I will merge the PR :)

**Comment by phwes** [comment]
I have now updated the proposal.

**Comment by gluckzhang** [comment]
Thanks @phwes . The PR has been merged.

**Comment by phwes** [comment]
Great.
Thank you for your help!

**Pull request merged**
