### PR TITLE
Finished demo

### PR DESCRIPTION
**Pull request by MindaugasVarkalys**
Add screencast and repository of the finished demo

### CODE REVIEW

**Comment by johansettlin** [comment]
I would like to give feedback!

**Comment by JoarEkelund** [comment]
Would like to give feedback

**Comment by s1grun** [comment]
I would like to give feedback to this demo!

**Comment by SoFoDa** [comment]
I will also give feedback

**Comment by johansettlin** [comment]
The screencast clearly matters for DevOps (CD), you could go more in to depth in for example the kubernetes.yaml file and explain more about kubernetes for those who have not used kubernetes before. 

I really liked the fact that you have subtitles and talk in the screencast, this makes it easy to follow. And the Chuck Norris.

**Comment by JoarEkelund** [comment]
Nice demo. You speak clearly and it is easy to follow along. The Demonstration is clearly related to DevOps, it is visually appealing and contains an accompanying GitHub.

For someone with limited knowledge about Kubernetes and Rancher it would have been nice with some more background information in the beginning of the Demo.

Overall well done :)

**Comment by SoFoDa** [comment]
Nice demo! You speak with a nice tempo and the video is easy to follow in terms of the visuals. I agree that the topic is clearly connected to DevOps. This connection could be emphasized more in the beginning of the demo for someone who is not as familiar with DevOps.

**Comment by sujon2100** [comment]
I would like to give feedback!

**Comment by sujon2100** [comment]
Here is the feedback:
The screencast looks great. In general, it has a good explanation by the subtitles and with voice. Just as a general suggestion to improve the screencast is "Easter eggs" could be added as a hidden field so that the viewers can easily click and reveal that wherever they want. You could add fast-forward the video a little more and put more content in it. Otherwise, it's a great job. Wish you good luck!

**Comment by gluckzhang** [comment]
Hi, @nicolai-h is absent today, but he also gives his feedback on this demo. Here is what we received from him.

> The demo is about Rancher, which is a graphical tool that helps manage, scale and monitor multiple Kubernetes clusters. The demo had a good introduction, which presented the topic and gave enough information to be able to follow the rest of the demo. In some parts of the demo it seemed like the steps were not thought through beforehand and I think that might confuse some watchers. The files and code needed to set up Rancher pipeline was shown, which makes it easy to do it yourself after watching the demo. Overall it was easy to follow along with the demo and it gave a good introduction to Rancher.

**Comment by s1grun** [comment]
Very nice demo! The take-home message was clear, the sound was good and the speaker is talking very clear and in a good tempo.

It might be good to demonstrate how you connect the pipeline to your GitHub account, and I felt like one step/explanation was missing in regards to what Rancher does or is doing so it is triggered with the automatic CD pipeline.

**Comment by MindaugasVarkalys** [comment]
@johansettlin @JoarEkelund @SoFoDa @sujon2100 @nicolai-h @s1grun 
Thank you all for the feedback. It helped us a lot understand the downsides of our demo and improve it.

Based on what the majority of you told us, we added a short introduction in the beginning of the video and explained Kubernetes in more detail, so even the ones not familiar with Kubernetes can understand the demo.

#831

**Pull request merged**
