### PR TITLE
Essay: Comparison of Splunk and Nagios Devop monitoring tools and their use cases

### PR DESCRIPTION
**Pull request by carinawic**
# Essay Proposal: Comparison of Splunk and Nagios Devop monitoring tools and their use cases

## Members

[Carina Wickström](https://github.com/carinawic)  - carinawi@kth.se
[Ifeoma Urama](https://github.com/IfyUrama)  - urama@kth.se 

## Proposal
Motivation: There are many monitoring tools available today, which makes it hard for users to pick the one most suitable for them. Goal: We want to compare the two most common monitoring tools in order to make it easier to see their differences and use cases. We choose Splunk and Nagios because they are popular DevOps tools available.

- A comparison of Splunk and Nagios Devop monitoring tools and their use cases.

### CODE REVIEW

**Comment by carinawic** [comment]
This pr got a bit messy because I didn't branch properly... If this proposal gets accepted, I would like to make a new pk with the same content, and merge the new one instead of this, if that's ok

**Comment by SophieHYe** [comment]
Hi,
Your proposal is highly related to DevOps and very specific focus. I am merging your PR now and good luck to your work.

**Comment by SophieHYe** [comment]
Hi,
Your proposal is highly related to DevOps and very specific focus. I am merging your PR now and good luck to your work.

**Comment by Renstrom** [comment]
Hi, we would like to give feedback to your essay.

Pull request in reference #1178

**Comment by carinawic** [comment]
> Hi, we would like to give feedback to your essay.
> 
> Pull request in reference #1178

Hi,

Thank you, that's appreciated. We are still far from done with the essay. Would it be fine for you if we submit the essay for your reviewing around April 26:th?

**Comment by Renstrom** [comment]
Since the hard deadline is April 26:th for the feedback of a task submission, would it be possible to get it one or two days earlier? Mainly so we have the time to give good constructive criticism in time.

**Comment by carinawic** [comment]
Ah, yes of course. Then we will submit it towards the end of next week. :)

**Comment by carinawic** [comment]
I will submit the essay tomorrow (saturday) around noon. I hope that leaves enough time for the feedback. Thank you!

**Pull request merged**
