### PR TITLE
chore: Add the "Registered_KTH_IDs.txt" file

### PR DESCRIPTION
**Pull request by khesoem**
Hi @SophieHYe 

This PR adds a file containing all the registered KTH_IDs. Please let me know if you think something should be changed before merge.

### CODE REVIEW

**Comment by khesoem** [comment]
@SophieHYe Do you have any comments?

**Comment by khesoem** [comment]
@SophieHYe @Deee92 Can you merge this one?

**Comment by ysndr** [comment]
Hej
I'm not sure what this file is used for but I can't find my KTH id (`yannik`) upon this list although I am enrolled through ladok.

**Comment by khesoem** [comment]
Hi @ysndr ,

It is a file that some course automation tasks require. It is not a critical file. Can you create a PR and add your ID?

**Pull request merged**
