### PR TITLE
Final submission: Essay - The fundamentals of DevOps culture and how to transition to DevOps

### PR DESCRIPTION
**Pull request by lucianozapata**
# Finished Essay

## Title

The fundamentals of DevOps culture and how to transition to DevOps

## Names and KTH ID

- Luciano Zapata (zapata@kth.se)
- Isabel Redtzer (iredzer@kth.se)

## Deadline

Task 3

## Category

Essay

## Description

We plan to write an essay that embodies the core of DevOps culture and analyze how the transition to a DevOps culture is made. We plan to go into detail on what can improve as well as what challenges can arise. We are very interested in the human and psychological perspective of DevOps since we believe it’s necessary to get the full picture of what DevOps is.

Overall stucture of the final essay submission:
- Introduction to DevOps
- Background: What is DevOps culture? 
- Background: DevOps characteristics. 
- What does the transition to a DevOps culture look like?
- What challenges and benefits can arise?
- Reflection and conclusion

**Link to PDF**
[The fundamentals of DevOps culture and how to transition to DevOps](https://drive.google.com/file/d/1Q3Vr7hHNbZOldGn_eusqusVHuw8WI4S_/view?usp=sharing)

### CODE REVIEW

**Comment by lucianozapata** [comment]
Our PR for our final essay submission is now up! @isabelredtzer

**Comment by AbyelT** [comment]
Hello! @lucianozapata I am interested in giving feedback on your essay if possible.

**Comment by lucianozapata** [comment]
@javierron , We would like to know if we have finished this essay or if there is something left for us to do? 😊

**Comment by javierron** [comment]
Hello @lucianozapata, your submission is accepted. 
Grading is still pending, but you will be notified.

**Pull request merged**
