### PR TITLE
Week 7: Presentation proposal

### PR DESCRIPTION
**Pull request by Jonas-Liley**
# Assignment Proposal

## Title

Software licencing overview and compliance automation

## Names and KTH ID

- Jonas Liley (liley@kth.se)

## Deadline

- Week 7

## Category

- Presentation

## Description

In this presentation we will introduce the different licencing types and cover some of the most common licences including their implications. We will also propose (a) solution(s) to automate licence compliance checks using code/tools in a CI/CD pippeline.

**Relevance**

Licenses are an important topic for legal compliance and risk mitigation, especially if the produced software product is supposed to be re-licensed and sold. As one can see with the license change of elasticsearch from an open-source Apache 2.0 license to a more restrictive Server Side Public License (SSPL), software licensing can have a massive impact on companies and software products.

### CODE REVIEW

**Comment by Jonas-Liley** [comment]
Recreating the pull request because my partner dropped out: https://github.com/KTH/devops-course/pull/2591#issue-2564175646

**Comment by sofiabobadilla** [comment]
Merging, good luck :)

**Comment by algomaster99** [comment]
@Jonas-Liley could you please share the presentation with me? I really liked and I would like to reflect on the category of licenses slide that you have. My email: amansha@kth.se.

**Comment by Jonas-Liley** [comment]
@algomaster99 yes sure! I’ll send it later today

**Pull request merged**
