### PR TITLE
Executable-tutorial: Proposal change

### PR DESCRIPTION
**Pull request by sestys**
We are changing our proposal a bit to focus on two tools (ansible + K8s).

Also, we are looking for someone to give feedback on this tutorial.

### CODE REVIEW

**Comment by khesoem** [comment]
Hi,

What was your previous PR?

**Comment by fwallb** [comment]
Hi @khaes-kth,

The original proposal is #1102 and then adding team member in #1195

**Comment by Wizkas0** [comment]
I would like to give feedback on this tutorial, should I link to this or to the original?

**Comment by khesoem** [comment]
> I would like to give feedback on this tutorial, should I link to this or to the original?

It is safe to link both of them and also mention your feedback on both of them.

**Comment by Wizkas0** [comment]
I will give feedback for this task and my feedback PR id is #1317

**Comment by sestys** [comment]
Great, happy you picked our tutorial @Wizkas0 . We will let you know when the tutorial is up and running, we are currently aiming for Sunday.

**Comment by Wizkas0** [comment]
Thank you, sounds great!

**Pull request merged**
