### PR TITLE
Executable tutorial, Task 1: Final Submission

### PR DESCRIPTION
**Pull request by noizy-sthlm**
# Assignment Proposal

## Title

Multibranch pipelines with ArgoCD

## Names and KTH ID

  - Sam Maltin (smhanna@kth.se)
  - Amin Nouiser (anouiser@kth.se)

## Deadline

- Task 1

## Category

- Executable tutorial

## Description

The tutorial will demonstrate how to set up and manage a multibranch pipeline for Kubernetes clusters using ArgoCD. We'll guide readers through creating a development branch for testing a web application and a production branch for stable releases. ArgoCD will be integrated with Git to automate the deployment process, ensuring that each commit triggers an update.

**Relevance**

As automation is a core principle of DevOps, this tutorial is highly relevant to good DevOps practices.

Killercoda: https://killercoda.com/noizy-sthlm/scenario/killercoda
GitHub: https://github.com/noizy-sthlm/multibranch-k8s-cd-tutorial

### CODE REVIEW

**Comment by sofiabobadilla** [comment]
Thank you, we will look in it.
Merging now :)

**Comment by algomaster99** [comment]
Hi! I was looking at the assignment, but I am stuck at last step. I have pushed the docker images [here](https://hub.docker.com/r/algomaster99/dummy-webapp/tags) and my fork is [here](https://github.com/algomaster99/dummyWeb-ArgoCDk8s/). Upon pushing the docker image, I don't see the website being updated. Could you tell me why?

**Comment by noizy-sthlm** [comment]
> Hi! I was looking at the assignment, but I am stuck at last step. I have pushed the docker images [here](https://hub.docker.com/r/algomaster99/dummy-webapp/tags) and my fork is [here](https://github.com/algomaster99/dummyWeb-ArgoCDk8s/). Upon pushing the docker image, I don't see the website being updated. Could you tell me why?

Thank you for testing out the tutorial,

Your repository and Docker images looks good. As is noted in the tutorial, it takes a few minutes for any new image builds to be recognized and deployed after you have pushed them to Docker Hub. This as we are not using webhooks but letting Argo periodically poll Docker Hub and the git repo instead. Once the sync process is finished you should see that the "last sync" timestamp is reset:

image

However, it could also be that *image-updater* for some reason has problems writing back to the git repo. Make sure that the access token you generate for ArgoCD (in Step 4) includes read and write permissions.

If there were some problems during the write back process (or something else), you should be able to read it with `kubectl logs deployment/argocd-image-updater -n argocd`. If so, please dump it here and we'll take a look at it.

Since you already have your repository and images set up, you can start from **Step 3** when re-running the tutorial.

**Comment by algomaster99** [comment]
Hi! Not sure what was the problem, but I only deployed the production instance this time and upon docker push, the site updated in a minute. Hence, I am passing you. Good job!

**Pull request merged**
