### PR TITLE
Demo Submission: Continuous deployment on Google Play Store

### PR DESCRIPTION
**Pull request by vladomit**

### CODE REVIEW

**Comment by LaraRos** [comment]
# Feedback demo day
## Positives
* Good speaking speed
* Good editing and animations

## Work on
* I think the background music is too much
* The GitHub action part was very quick, I’d like more explaining and highlighting in this segment
* There is no general information segment, perhaps one could speak about Google Play Store and their services in general as an introduction
* You could reduce the current outline segment, and add more of the points above.
* The size of the text when you’re screen recording is quite small, you could make the text larger

**Comment by annsudo** [comment]
The tutorial is of high quality: 
1) The content: clear and easy to follow, the additional links and information are given to make sure all the viers are on the same page 
2) The video is appealing. Colourful graphics, clear voice over with just-right tempo and calm temper (not easy when you given 3 min)  
3) Structure: agenda, in the beginning, gives a clear picture of what to expect from the video

**Comment by oscaralmqvist** [comment]
It was nice that you showed the contents in the beginning, a small improvement here could be to list all the prerequisites in the slides as well. I think you should lower the volume in the very beginning as it was a bit loud compared to the rest. I'm not that experienced with working with the Google Play Store, but I felt that I didn't really follow all the different secrets/keys used and where you got them from. Overall, I enjoyed the pace and speed of this demo and the voiceover was clear. Great job! 🎉

**Comment by bubriks** [comment]
Great demo! I like that it is well structured and informative. However, maybe a bit more could be said about Google Play Store, but with limitations in mind, it is one of the best demos :)

**Comment by gangwalmegha** [comment]
Feedback on Demo:
Strength:
1. Speed: good
2. Good Animations
3. High Quality Video
Improve area:
1. Background music volume can be lower down.

**Comment by dmariel** [comment]
Well done! I think this demo is really well made and it gives the viewer a professional impression (visually appealing, good choice of background music, excellent structure and clear voice over while still following the time constraints). Furthermore, I like the separate section "Prerequisites" in which you refer to another video for information regarding how to recieve the key, since this enables you to focus on the main process in your video, while still providing your viewers with relevant information. The same applies to the conversion of keys to base64 format. 

A suggestion of improvement would be to include some background info on what GitHub Actions is and why you want to do this in Google Play Store (i.e. highlight the relevance for DevOps). Furthermore, you could perhaps divide the video into clickable sections on the YouTube timeline (i.e. I saw this in [this video](https://www.youtube.com/watch?v=GQ9qroAbqr4)). Moreover, the background music could perhaps be lowered a bit in the end of the video (in order to give the viewer the impression that the video is ending).

**Comment by vladomit** [comment]
Thanks for your feedback guys, we corrected our video and updated the link #1516

**Pull request merged**
