### PR TITLE
Presentation proposal: Presenting Dynatrace Container Monitoring

### PR DESCRIPTION
**Pull request by Hasan-Kalzi**
# Assignment Proposal

## Title

Container Monitoring: an overview of the monitoring system "Dynatrace" 

## Names and KTH ID

  - kalzi@kth.se 

## Deadline

Deadline task 4

## Category

Presentation

## Description

Dynatrace is one of the solutions to handle monitoring. Because DevOps is becoming more complex, we need an AI-powered, full stack and completely automated tool. Dynatrace is one of the powerful solutions that provide answers, not just data. I will attempt to explain the importance of monitoring in DevOps and present an overview of Dynatrace, show why 
it is a good tool to use and how to implement it in a project.

### CODE REVIEW

**Comment by khesoem** [comment]
@Hasan-Kalzi : have you already presented your work on week 9?

**Comment by Hasan-Kalzi** [comment]
No I didn't.

**Comment by khesoem** [comment]
Since we have finished the lectures, there is no more time for doing a presentation. I'll close this PR. Please let me know if I am missing something.

**Comment by Hasan-Kalzi** [comment]
@khaes-kth Okej I misunderstood the meaning of the deadline at 17 o'clock. can I do it under the re-making session?

**Comment by khesoem** [comment]
As far as I know, new proposals for presentations cannot be approved anymore.

**Pull request closed without merging**
