### PR TITLE
oliverle-nareaho Essay Proposal April 24

### PR DESCRIPTION
**Pull request by lehtihet**
# Assignment Proposal

## Title

Understanding Copilot X and it's potential for improved DevOps practices

## Names and KTH ID

  - Oliver Schwalbe Lehtihet (oliverle@kth.se)
  - Mathias Näreaho (nareaho@kth.se)

## Deadline

- Task 2 deadline (April 24, 17h)

## Category

- Essay

## Description

The latest version of GitHub Copilot is adopting OpenAI's new GPT-4 model, aswell as introducing chat and voice for Copilot. 
In addition, Copilot can now be used for pull requests, command line and documentation to answer questions. 

This essay aims to show these features and to talk about the potential, strengths and weaknesses of AI powered technology, and how it could be used to help developers write code based on the specifics of the operational environment.

As this version is not yet released to the public, the essay will have to use material that is available online.

**Relevance**

GitHub Copilot is commonly used for developing code, and according to GitHub themselves, 46% of code is written by Copilot. 

It could help developers understand what type of code to write to follow operational best practices, and how to utilize the available resources in the most optimal way.
Such an integral tool is very relevant to the themes of the course

### CODE REVIEW

**Comment by javierron** [comment]
This topic is very interesting, with a lot that can be discussed, so remember to ground it in the context of DevOps practices.

**Comment by LinusOstlund** [comment]
# ----------- Summary -----------
In “Understanding Copilot X and its potential for improved DevOps practices”, Lehtihet et. al. discuss how the future of DevOps might be improved be incorporating pair-programming with Copilot X. Following a brief background on pair-programming and AI, section three discuss strengths and weaknesses. However, it is not very clear how these strengths and weakness are relevant to the topic (Pair-programming and Copilot X).

# ----------- Overall evaluation -----------
The topic is great, and relevant for DevOps (and the future of coding monkeys 💻🐒). The introduction and background has a high standard, but there are some questions that should be adressed

I am not sure if the authors suggest Copilot X should replace the Navigator in pair-programming, or be used as a complement. The discussion in Section 3  bring up some relevant ideas (such as reducing time spent reading and writing documentation), but how is it feasible in the context of pair-programming and culture building? The arguments should be backed with references (see below for suggestions).

The paragraph on coding conventions should have a motivation on why it is relevant for pair-programming. I believe the authors could make a more elaborate list of challenges for Copilot X as a pair-progammer, with more focus on the essay topic (pair-programming and DevOps), rather than the technical aspect of Copilot X.

# ----------- Introduction -----------
**SCORE: 4 out of 5**
The topic is very interesting and relevant. LLM’s, and specifically GPT-4, is top of mind right now. Copilot X is the future. Pair-programming is well-defined, with risks and opportunities, and GPT-4 is adressed. The introduction is good. My questions are adressed in the "Evidence"-section.

# ----------- Background -----------
**SCORE: 4 out of 5**
This section is adequate. I have no feedback on the content. My questions are adressed in the "Evidence"-section.

# ----------- Evidence -----------
**SCORE: 2 out of 5**
There is not many peer-reviewed articles in the references, and the authors seem to rely on anecdotal arguments to support some of their claims. To make this feedback actionable, I will list some of my observations:
*  Section 1 Introduction, first line: “One of the fundamentals of DevOps is collaboration […]”. This is not backed with any references. Are you talking from your own experience, or is this something that is backed in the literature? A great starting point would be a systematic literature review such as [A qualitative study of DevOps usage in practice](https://onlinelibrary.wiley.com/doi/abs/10.1002/smr.1885) (just head to Google Scholar and query for “DevOps Literature Review”).
* Section 1 Introduction, middle of second paragraph: "A key goal in a DevOps environment is to bridge the gap between developers and IT operations". This should have a reference, or is it anecdotal? Also, is it bridging a cultural gap, a knowledge gap, or something else?
* Section 2.2 Relevance of pair programming in DevOps: “DevOps is the art of collaboration, agile development and automation”. It would be preferable if such claims were backed with references, or make it clear that it is anecdotal. Have a look at the previous literature review if you want a reference.
* Section 3.1 Strengths: this section is one of the main line of arguments, yet I can’t find a  single reference supporting your claims. “One of the most important tools of a developer is searching”. Out of personal experience I might agree with this, but it should be backed by research. In [Today Was a Good Day: The Daily Life of Software Developers](https://ieeexplore.ieee.org/abstract/document/8666786) the authors claim software-developers spend most of their time reading documentation (among other things!).
* Section 3.1 Strengths: What is “dynamic coding conventions tests”? Is that an academic term and something used in practice, if so, which tools are available? If not, I don’t really see the relevance. Following this line of argument, Figure 2 has an image text that left me confused, “… follow proper coding conventions” — proper according to whom? How is that relevant to pair-programming? Either make your current argument more concrete, or change focus; Copilot is a gold mine when it comes to automatic testing and such, perhaps that is something you could elaborate and how that would help pair-programming and enforce DevOps best-practices.
* Section 3.2 Challenges: it would be nice to see this section backed by references, too. I believe there are more challenges to “pair programming with AI” than the context of which it is operating in. What about [hallucinations](https://www.oecd-forum.org/posts/gpt4-the-hallucinations-continue) or [bugs introduced by programmers accepting prompts they don’t fully understand](https://www.deeplearning.ai/the-batch/copilot-ai-tool-may-cause-programmers-to-write-buggy-code/)? After all, it is just a LLM. What about the team-building and DevOps-cultural aspect of pair-programming? Would you consider removing one of the team members from the mix a challenge, or an opportunity?

# ----------- Presentation -----------
**SCORE: 3 out of 5**
Paragraphs are separated with both a new line, and an indentation. I’d recommend you to be consistent and pick one; either new line, or indentation (I tried to find a style guide to back this claim, but that proved to be hard). Some paragraphs and sections have more than one new line, which should be adressed by the authors. It would be nice to see some data visualisations (e.g, from the [GitHub blog](https://github.blog/2022-09-07-research-quantifying-github-copilots-impact-on-developer-productivity-and-happiness/)), or by other related work (e.g, how does a developers day look like?). To further improve readability, the authors could also adress [widows and orphans](https://fonts.google.com/knowledge/using_type/avoiding_widows_orphans) (paragraphs that appear by themself in a row of text).

[~770 words]

**Comment by LinusOstlund** [comment]
@javierron have I done everything correctly for a "Feedback"? Let me know otherwise.

Regards,
L

**Comment by javierron** [comment]
Hello @LinusOstlund! You also need to open a PR, adding a link to the comment in the README file.
Please also update the README to show that this task corresponds to the "Task 2" deadline.

**Comment by a-kbd** [comment]
# Feedback
”Understanding Copilot X and it’s potential for improved DevOps practices”
David Cederström
Arasp Keighobad
April 26, 2023
DD2482

We certify that generative AI, incl. ChatGPT, has not been used to write this feedback. Using
generative AI without permission is considered academic misconduct.


# High-level Strengths
- The essay chooses the very interesting topic of copilot/LLMs (and admittedly very hot right
now) and ties it to the course content as well as more traditional practices like pair programming
in a balanced and intriguing way.
- The essay makes some strong valid points about the strengths and weaknesses of both pair
programming as well as using new AI tools to aid for this.
- The essay is written in nice and easy to read language, keeping the reader engaged as well as
making the material easier to digest. Anything mentioned is explained and the text is fit for the
intended audience.

# High-level Weaknesses
- The challenges section really only provided one single challenge, whereas for example in the
section where you listed alternative models there were some problems and challenges that the
other models aimed to solve, e.g. not relying on licensed code etc.
- Weaknesses and potential problems with licensing, ethical issues etc should perhaps also be
explored. Have there been any cases where problems were caused by using the AI tool? i.e.
over-reliance on that the output is correct and it turning out to break in some unforeseen way.

# Specific Feedback
## Title and introduction

The title of the essay is good. You understand the core concept of the essay which also is reflected in
the essay itself. The quite heavy focus on pair programming is not really that clear from just reading
the title of the essay, although you rather quickly understand that the possible, practical implementations with Co-pilot X is done by pair programming so it is not really an issue.

The introduction does a good job of introducing the reader to the topic pair programming, AI’s
potential in improving this methodology and why this is important and relevant to DevOps. It sparks
the readers interest and the authors does a good job in describing what the potential problems are with
pair programming and what AI can potentially do in solving these issues, therefore also introducing a
potential solution to the problem which makes the reader want to keep on reading.

”Another problem is that the Navigator, who gives direction to the developer, would need to be
knowledgeable of the operations and infrastructure of the software environment, in order to best make
suggestions.” → This does not feel like a drawback of pair programming itself, perhaps the drawback
would then be that you need more people to do pair programming for the same amount of value compared to if they just worked separately (if one could show that the person would be more valuable not
being merely a navigator)

”In this thesis we will give a general description (...)” → Perhaps thesis is not the right word

# Background

It is appreciated by the readers that the authors have included a short introduction and overview of
the section. This makes it easier for the reader to understand and be prepared to what it can expect
in the form of content and context.

Since pair programming is an important concept within this topic, the authors did a good choice by providing the reader with some background information regarding the concept. A nice image was also added for additional, visual representation of what pair programming looks like and how it can
be implemented. The authors also motivates the relevance of pair programming in DevOps in a good
way, making the reader more convinced that the presented technologies and methodologies can be very
relevant as both a problem and solution within the field. It is also nice to get a background to what
GitHub Copilot X is and why it is connected to the concept of pair programming.

Although interesting, we are not sure that it is relevant or provides the reader with anything useful for this essay to list other AI code tools than Github Copilot X in a separate section.

”However Copilot is likely to remain the most widely used one, since it is integrated with the most
advanced large language model.” What models do the others use?

# Combining pair programming with AI

Interesting section where the more traditional practice of pair programming is compared to new more
high-tech tools that could potentially replace, or augment pair programming.

## Suggestions and comments
”and Copilot X would allow the used to have someone to collaborate with” used → user

”an experienced user of tools like Terraform or other DevOps toolkits can bring along Copilot for auto-completion and code suggestions” → why specifically Terraform? Is it extra suited for using alongside Copilot? You bring it up as an example suddenly and seemingly out of context.

”One of the most important tools of a developer is searching. Searching for code, libraries, tools
or any other part of the development process. After something suitable has been found, it then has to be shaped to fit the problem (or code) at hand, which can be time consuming and tedious” → Good point, that is a very compelling strength of using Copilot as a pair programmer

# Conclusion
Nice conclusion describing and weighing and rounding up the different strengths and challenges of the topic discussed. On the other hand the same feedback about not discussing the challenges enough applies here too. Perhaps the conclusion would have been more balanced if more challenges were explored.
## Corrections
”Because of it’s ability to understand” it’s → its
”As a result, if Copilot does shows promising results” either remove ”does” or shows → show (or remove "does")

# General comments
Tiny nitpick but usually, the word ”however” is idiomatically followed by a comma, you guys missed that at a couple of places.

# Pointers to additional material and related work

- Found this article that might be interesting for pondering about other challenges with this approach:
Why You Should Apply Caution When Using AI in Code Development https://www.spiceworks.com/tech/artific
intelligence/guest-article/why-you-should-apply-caution-when-using-ai-in-code-development/
- This post on Github’s own blog might be interesting: Responsible AI pair programming with
GitHub Copilot https://github.blog/2023-02-22-responsible-ai-pair-programming-with-github-copilot/

**Pull request merged**
