### PR TITLE
Proposal: Demo Terraform with Jetbrains' IDE

### PR DESCRIPTION
**Pull request by mindany2**
# Assignment Proposal  

## Title  

Demo Terraform with Jetbrains' IDE  

## Names and KTH ID   
  - Gatien Ducornaud (gatien@kth.se)
  - David Nadjar (ddnadjar@kth.se)  

## Deadline  

Task 2

## Category

Demo

## Description  

We plan on doing a demo for understanding what is Terraform and how to use it with Jetbrains' IDE (IntelliJ for our example).

### CODE REVIEW

**Comment by cesarsotovalero** [comment]
Hi @mindany2, 
Your demo proposal features very basic IDE functionalities for version control.
You should update your proposal to niche down some other IDE features more related to DevOps.
For example: 
- Dependency analysis with IntelliJ
- Docker integration
- Azure integration

I'll let this PR open until you revise it.

**Comment by mindany2** [comment]
Hello,

It's indeed basic IDE functionalities for version control. However, they are the must-have ones and we figured out some people don't know that.
Obviously if you prefer we can talk about your suggestions but we think it'll be more useful to cover basic and important to everyday life instead of talking about very precise features.

I let you decide given that and I'd update it if necessary.

**Comment by cesarsotovalero** [comment]
Hi @mindany2,
This course is for Master level students, so you can assume that your peers know the basics.
Please update the description with more advanced proposals.

**Comment by mindany2** [comment]
According to the last discussion we can suggest these features:
- Cherry-pick
- Amend any commit
- Squash commits
- Drop a commit
- Edit project history by performing interactive rebase﻿
- Pull requests on Github (with IJ)
- Differences between shelve/patches/stash

We think it will take more than 7 minutes so if you have any preferences on these features please tell us.
In case of you think it's not enough we run of ideas of which demo we can do for next week (given your examples were for last week), so if you have any, we'd be happy to hear them !
Thank you.

**Comment by cesarsotovalero** [comment]
Hi @mindany2, 
As per our discussion during today's lab: version control is part of the IaC workflow. 
I suggest you look at IntelliJ plugins such as https://plugins.jetbrains.com/plugin/7808-terraform-and-hcl, so that you can focus your demo on this topic.

**Comment by mindany2** [comment]
All done !
Can we do the demo in the first hour (as I can't attend the next ones) please ?

**Pull request merged**
