### PR TITLE
Presentation proposal week 9

### PR DESCRIPTION
**Pull request by NilsLofberg**
# Assignment Proposal

## Title

Injecting failures into a Kubernetes cluster with Chaos Mesh

## Names and KTH ID

- Nils Löfberg (nilslof@kth.se)

## Deadline

- Week 9

## Category

- Presentation

## Description

Chaos mesh is an open-source, cloud native, chaos engeneering platform that can be used for fault simulation in kubernetes clusters.
It has the capabilites to simulate or orchestrate different types of fault senarios such as node failiures, network failures and pos failiures.

I will present how this is done and the relevance and importance of such practices

**Relevance**

Ensuring the resiliance of a system is an important part of devops

PS. I know this is very late, I lost track of how many week were left

### CODE REVIEW

**Comment by SandZn** [comment]
Hi @NilsLofberg, thanks for the proposal. Your topic is relevant and indicates technical challenges. It could also be a cool topic for a demo.

A proposal pull request is submitted **after** you have an idea, **before** you finish the preparation.  In addition, we need time to review and give feedback.

Since today is the last chance to give a first presentation/demo, I suggest you attend today's lecture and explain your situation to the professors if needed. Hope you have your presentation prepared.

**Comment by SandZn** [comment]
The format of this pull request needs to be corrected. 

Please create a folder with your name and move this README file to the folder, then make a new pull request.

**Comment by NilsLofberg** [comment]
Hi,
Yes i have the presentation prepared and will attend the lecure. I am on my way in to campus now and will correct the format ASAP

**Comment by SandZn** [comment]
All right, I have fixed this. Good luck.

**Comment by NilsLofberg** [comment]
thank you

**Pull request merged**
