### PR TITLE
Essay Correction for the feedback: Exploration of AWS services used throughout CI/CD

### PR DESCRIPTION
**Pull request by sujon2100**
Added new pdf according to the feedback from @monperrus

### CODE REVIEW

**Comment by sujon2100** [comment]
Added new pdf

**Comment by sujon2100** [comment]
Added pdf link
added new pdf file

**Comment by SophieHYe** [comment]
Hi, please note that you have two files changed, one is the proposal for COVID19. 
If you want to update your proposal with details, I can merge both in this PR.

If you only want to update the PDF link, then you may have to remove the COVID19 proposal. 
Thanks!

**Comment by sujon2100** [comment]
@SophieHYe I have deleted the old proposal. Please only update the PDF link.

For Covid19, we have already updated correction of the feedback here https://github.com/KTH/devops-course/pull/633. DO WE NEED TO CREATE AGAIN A NEW PULL REQUEST FOR THE CORRECTED FEEDBACK? or the correction of the feedback I have written in the same page of the feedback, is enough? Please clear it. 

Thanks!

**Comment by SophieHYe** [comment]
Hi,
Thanks for your update!
Please also send another PR to add the revised report, source and website link in the readme for the final grading, so that we can grade your work based on that.  Thanks!

**Comment by sujon2100** [comment]
> final grading

@SophieHYe  Here is the PR for the final grading. Thanks!
https://github.com/KTH/devops-course/pull/701

**Pull request merged**
