### PR TITLE
Presentation proposal: Open source culture and conventions

### PR DESCRIPTION
**Pull request by nalenz**
# Assignment Proposal

## Title

Open source culture and conventions

## Names and KTH ID

- Julian Nalenz (nalenz@kth.se)

## Deadline

Task 4, to be presented at 2022-05-10 (Week 8: Cultural and legal aspects of DevOps)

## Category

Presentation

## Description

When first contributing to open source projects, many programmers find themselves confused about the conventions and expectations that other people in this space have. Over the years, many different standard practices revolving around open source projects for different programming languages have emerged.

This presentation will give an overview of various common conventions for open source projects of different sizes and how these conventions can aid in large-scale project management and maintaining. Some topics that will be discussed are:

- commit message format
- common issue and pull request labels
- changelog formatting
- choosing a suitable open source license
- which sections a good readme should contain and how it can make a project look more trustworthy and production-ready
- indicators to determine which open source project or library is the best long-term choice (e.g. that it has recent commits, a vibrant community, several responsible contributors, possibly backed by a company)

Various examples of well-known open source projects and how they apply these standards will be given.

### CODE REVIEW

**Comment by nalenz** [comment]
That is wrong, I did not register for this task yet.

**Comment by nalenz** [comment]
I'm also open for having someone else to do this presentation with! Could some TA or other administrator please add the "collaboration_wanted" label to this PR?

**Comment by khesoem** [comment]
@nalenz , which week do you intend to present this? Please mention this in your readme's deadline section.

Regarding the proposal, I should say it is relevant. However, if you focus on general points, it may be a bit old and unoriginal. I would suggest that you focus on the examples in your presentation to make it more exciting and original.

**Comment by nalenz** [comment]
@khaes-kth Of course, the presentation should actually focus mostly on examples, i.e. showcase existing projects and especially give the listeners concrete, actionable advice on how to improve their own open source work.

And thanks for the hint, I added the proposed presentation date!

**Pull request merged**
