### PR TITLE
Final Submission - Demo: Merging tool for Salesforce Deployments

### PR DESCRIPTION
**Pull request by oskstr**
## Members
- [Oskar Strömberg](https://github.com/oskstr) (oskstr@kth.se)
- [Sebastian Williams](https://github.com/sfkwww) (swill@kth.se)

## Proposal

We would like to demo an unreleased application CloudKit that we have worked with a few years ago. This app makes it much easier for Salesforce developers to deploy instances to production by providing the following features:
- Automatic dependency checking
- Automatically finds and displays merge conflicts between instances
- One click deployments

Salesforce is a CRM system that is used by many companies. However it is notorious for being bad at showing which dependencies are missing between instances and in general it can be hard to find which parts create conflicts. We believe this relates to DevOps since it automates certain parts of the process making it much easier to deploy from eg. Dev to Production.

### YouTube Link
[Video Demo](https://youtu.be/OBAVeo5005U)

### CODE REVIEW

**Comment by SophieHYe** [comment]
## Good points
* Good introduction and conclusion.
* The steps are easy to follow.
* Perfect timing within 3 mins.
* The voice is very good and clearly.

## To improve
* The font size of the code/text could be larger. Steps are hard to read and follow.
* A bit background of CRM or CloudKit. If If audience not familiar with these techniques, point them to the external reading material to gain some knowledge.

**Comment by iriediese** [comment]
Great demo. Clear voice, accurate subtitles, easy to follow and intuitive.
You could add more background information in the video description, since it's currently empty for you. Maybe add some references or pointers for people less familiar with the subject.

**Comment by carinawic** [comment]
Great video. It was easy to follow, with an especially clear introduction. Good audio and sound. I like the take-home message in particular which summarizes the point of the video. My suggestion is to speed up the video slightly because the audio was somewhat slow. In that way, you could fit more content into the 3 minute timeslot. Further, your video is only 2:50, which leaves additional time if you wish to describe some details further, or to implement the other feedback you have received.

**Comment by patricia-naccachian** [comment]
The outline of the demo is very well structured, and the steps shown are simple and easy to apply, and the audio was clear. However, more explanation on why it matters for DevOps and a little more background information would have made it better. Overall, the work is well done with minor fixes.

**Comment by sestys** [comment]
Good job! The demo has an easy-to-follow structure and a good take-home message. I would enjoy an introduction to both CRM system and Cloud talk to have a better understanding of when this problem with dependencies occurs. Otherwise, I liked the simple example to follow and then showing a more complex one at the end. Nice demo!

**Comment by IfyUrama** [comment]
**Overall:** Very clear explanation and voice over. Easy to follow.

**Strength:** The takeaway message is clear and precise and it summarizes the video. 

**Weakness:** The visual quality is a not so clear in some parts of the video.

**Pull request merged**
