### PR TITLE
Week 5: Presentation Proposal (jmaragna-jrybak)

### PR DESCRIPTION
**Pull request by jackma-00**
# Assignment Proposal

## Title

_AWS Cloud Development Kit - Define your cloud application resources using familiar programming languages_

## Names and KTH ID

  - Jacopo Maragna (jmaragna@kth.se)
  - Jakub Rybak (jrybak@kth.se)

## Deadline

- Week 5

## Category

- Presentation

## Description

We will demonstrate how the AWS Cloud Development Kit (AWS CDK) accelerates cloud development by enabling you to model your applications using familiar programming languages. Additionally, we will provide technical examples to help you get started and successfully implement these concepts.

**Relevance**

The topics covered are especially relevant to DevOps, as they enable managing infrastructure as code. This approach allows for version control and continuous deployment of changes to the target environment, leveraging AWS CloudFormation as the deployment engine.

### CODE REVIEW

**Comment by jackma-00** [comment]
Proposed by @laykos0 and I.

**Comment by algomaster99** [comment]
@jackma-00 I have not worked with AWS CDK, but I have a (probably dumb) question. How is this proposal different from https://github.com/KTH/devops-course/pull/2373? AWS CDK sounds like a suite of tools which also contains AWS Lambda function.

**Comment by jackma-00** [comment]
@algomaster99 thanks for the question. I'm also one of the proposers of #2373. Let me explain to you the differences. 

- In #2373 we use AWS CDK as a tool to support the deployment process to Lambda. As I explained to you that won't be the main focus, instead the CD process is what we will demonstrate.  
- Here the focus will be to give an introductory presentation about this IaC technology, explaining the way it works. highlighting the benefits and suggesting a way to get started.

**Comment by algomaster99** [comment]
Sounds good! Looks good to me :) Merging.

**Pull request merged**
