### PR TITLE
COVID-19: Updated contents

### PR DESCRIPTION
**Pull request by sujon2100**
### About this project
This project is developed for gathering information regarding COVID-19 to update the users. It is totally non-profit-oriented project which emphasis on novelty and helping the people by providing all related information about COVID-19. Both students and people from the community can support by using this web portal. This web app is integrated with the latest Microsoft cloud platform by using Azure DevOps and Azure WebServices. As a result, this app can ensure low cost and high efficiency.

**Contributors**
Helal Uddin (mhud@kth.se/sujon2100@hotmail.com) and Nick Steele (nsteele@kth.se/njws1@outlook.com)
Live Website link: https://kthcovid19webapp.azurewebsites.net/ (Service might be off due to fee subscription, contact if it is down)
[Wiki&DevOps Project / Help Fight COVID-19: Web App](https://dev.azure.com/KthProject2020/NewKthCovidProject)

**Table of contents**
1. Background
2. The Web Application
2.1 Functionality
2.1.1 COVID-19 Latest Update
2.1.2 Built-in DevOps Technology
2.1.3 Contribution to Novelty & Helping
2.1.4 Attract Support from other KTH students & Society
3. Criteria for this COVID19 project
4.References

**1. Background**
This project is developed for gathering information regarding COVID-19 to update the users. It is totally non-profit-oriented project which emphasis on novelty and helping the people by providing all related information about COVID-19. Both students and people from the community can support by using this web portal. This web app is integrated with the latest Microsoft cloud platform by using Azure DevOps and Azure WebServices. As a result, this app can ensure low cost and high efficiency.

**2. The Web Application**
ASP.NET  Core with C#, HTML, CSS, Boostrap has been used to develop the web app. For continuous delivery, deployment and code management, Azure DevOps has been used together with Azure web services. This ensures the seamless integration from the beginning/planning phase to the delivery phase.

**2.1 Functionality**
COVID-19 Latest Update
In this website, COVID-19 update regarding confirmed, recovered and death cases has been shown by using COVID-19 API. Global summary of COVID-19 can be shown in a nice frontend from https://news.google.com/covid19/map?hl=en-US&gl=US&ceid=US:en . Besides, a JSON format of data could be received from this API "https://corona.lmao.ninja/v2/all ". It is also possible to find all of the confirmed cases for a particular country like Sweden.

**2.1.1 Built-in DevOps Technology**
Azure DevOps for COVID-19 project: Azure DevOps project is created to use Team Foundation Services(TFS) and agile methodology to integrate and manage the development process from Visual Studio. Besides, Azure DevOps is used for Creating a DevOps project to write all of the features and tasks.

Azure DevOps Deployment pipeline: Automated build and release pipeline is used to host the Azure web services.

Azure Web Services: To able to consume web services, Azure app service plan has been created together with resource groups To run the local project to the cloud. Azure web services can only be used by using the Azure portal.

**2.1.2 Contribution to Novelty & Helping**
As COVID-19 is a global pandemic and people are dying every moment, an external donation option has been used to raise funds for the affected people. Moreover, to help the COVID-19 positive patients, a social group has been created to make a group fight against COVID-19. Moreover, others helping and supporting the research work or employees have been linked up on the webpage.

**2.1.3 Attract Support from other KTH students & Society**
Student Portal: In this section, KTH students can be able to get information regarding information and access in the canvas too. Because of the lockdown situation, Zoom has been linked up for the KTH students. For future students, information regarding courses and contact information has been provided in under each program section.

**2.1.4 Community Portal**
People from different communities can get help from the Community portal according to their municipality. There is an option for each section. In the first section, people can get their Emergency help by visiting the linked address. For the COVID-19 test kit or any medical assistance, "COVID-19? Support" can be referred to. If someone can learn more in the "COVID-19: Learn more" section about the symptoms of this disease and all related issues. "COVID-19 Update" section can give all current information regarding different cities and communities.

**3. Criteria for this COVID19 project**
This COVID-19 project is fulfilling the following criteria:
-The contribution is related to COVID-19
-The contribution is related to / built with DevOps technology
-The contribution is novel
-The contribution is helpful
-The contribution attracts support from other KTH students

**4. References**
[1]https://dev.azure.com/KthProject2020/NewKthCovidProject (Link to the complete Project)
[2] https://news.google.com/covid19/map?hl=en-US&gl=US&ceid=US:en 
[3] https://corona.lmao.ninja/v2/all 
[4] https://api.covid19api.com/country/sweden/status/confirmed 
[5] https://portal.azure.com/#home 
[6] https://visualstudio.microsoft.com/ 
[7] https://covid19responsefund.org/ 
[8] https://m.facebook.com/groups/815512272277849 
[9] https://www.canada.ca/en/public-health/services/publications/diseases-conditions/covid-19-information-essential-service-workers.html 
[10] https://www.canada.ca/en/public-health/services/publications/diseases-conditions/help-reduce-spread-covid-19.html 
[11] https://kth.instructure.com/courses/ 
[12] https://www.kth.se/en/om/kontakt 
[13] https://polisen.se/en/the-swedish-police/contacting-the-police/ 
[14] https://www.vardcentraler.sll.se/ 
[15] https://www.folkhalsomyndigheten.se/the-public-health-agency-of-sweden/communicable-disease-control/covid-19/about-the-disease/ 
[16] https://www.google.com/search?rlz=1C1CHBD_svSE814SE814&q=Coronavirus+Stats&stick=H4sIAAAAAAAAAONgFuLVT9c3NMwySk6OL8zJUULlPmL05hZ4-eOesJTTpDUnrzHacHEFZ-SXu-aVZJZUCulxsUFZKlyCUqg6NRik-LlQhXh2MXF7pCbmlGQElySWFC9iFXTOL8rPSyzLLCotVgCLAQCnsUMMkAAAAA&biw=1232&bih=740 
[17] https://intra.kth.se/en/campus/sakerhet/kris/corona/information-till-anstallda-med-anledning-av-coronaviruset-1.965906 
[18] https://intra.kth.se/en/campus/sakerhet/kris/corona/information-till-studenter-med-anledning-av-coronaviruset-1.965905 
[19] https://www.youtube.com/embed/k8vuUJ7hVLY 
[20] https://www.youtube.com/embed/JCw-B4Ig3DQ

### CODE REVIEW

**Comment by gluckzhang** [comment]
Hi @sujon2100 , thanks for the updates! The only updated file in this PR is `contributions/presentation/README.md`, which should not be the case. You need to put the PR's comment into your `README` file in the task folder.

**Comment by sujon2100** [comment]
> Hi @sujon2100 , thanks for the updates! The only updated file in this PR is `contributions/presentation/README.md`, which should not be the case. You need to put the PR's comment into your `README` file in the task folder.

You mean I have to create a new PR and then add the "README" file in it?

**Comment by sujon2100** [comment]
> Hi @sujon2100 , thanks for the updates! The only updated file in this PR is `contributions/presentation/README.md`, which should not be the case. You need to put the PR's comment into your `README` file in the task folder.
Hi @gluckzhang, I have added #633  PR and added readme.md file.

**Comment by monperrus** [comment]
> sujon2100 wants to merge 1 commit into master from monperrus-patch-1

Ill-formed PR, closing

**Pull request closed without merging**
