### PR TITLE
feat: demo proposal

### PR DESCRIPTION
**Pull request by iabdelkareem**
# Assignment Proposal

## Title

Chaos Engineering via Simmy in .NET

## Names and KTH ID

- Ibrahim Abdelkareem (iaiab@kth.se)

## Deadline

- Week 9

## Category

- Demo

## Description
Chaos Engineering tests system resiliency by intentionally introducing failures, helping to identify and address potential weaknesses before they cause real-world issues. 

Simmy is a chaos engineering library that can help developers injecting faults in their .NET applications. In this demo I'll use a simple distributed system of 2 web applications that communicate with each other and a MongoDB database. I'll then show you how to use the simmy library to inject faults such as slow responses from one of the web applications or crashing the database server to test how our application will react.

**Relevance**

Chaos Engineering is relevant to DevOps as it helps developers to detect system weaknesses and flaws in order to address them and increase the reliability and confidence in the system.

### CODE REVIEW

**Comment by javierron** [comment]
Hello @iabdelkareem, thanks for the proposal.
Can you elaborate on the topic, e.g. which tools you want to use? Any specific type of application? etc.

**Comment by iabdelkareem** [comment]
@javierron I'm planning build a simple distributed system on 2 web application that communicate with each other and a database. The applications will be built with C# and the database I'll use is MongoDb.

I'll use a library called [Simmy](https://github.com/Polly-Contrib/Simmy) to inject faults such as latency or database restarts in the application to test how it behaves and if the application is resilient enough to handle these cases.

**Comment by javierron** [comment]
Hello @iabdelkareem, that sound great. Please update the proposal with these details, and I will merge it. I suggest that you focus your demo on the Simmy library, which is novel in the course. Consider also updating the name of the proposal to focus on Simmy.

**Comment by iabdelkareem** [comment]
Thanks for the feedback @javierron done I've updated the proposal to focus on Simmy.

**Comment by iabdelkareem** [comment]
Thanks for the feedback @javierron done I've updated the proposal to focus on Simmy.

**Pull request merged**
