### PR TITLE
Executable tutorial proposal - software bots to generate github reports

### PR DESCRIPTION
**Pull request by PersonligaPersson**
# Assignment Proposal

## Title

Stakeholder management through GitHub report automation by utilizing software bots

## Names and KTH ID
- Per Arn (perarn@kth.se)
- Max Persson (maxper@kth.se)

## Deadline

Task 5 (2022-05-31)

## Category

Executable tutorial

## Description

In modern large scale software development projects stakeholder management is a vital aspect of the development process.
DevOps as a concept is something that may be utilized to benefit an organization in more ways than the purely technical.
We propose an executable tutorial where we show how to automate GitHub performance reports in a clean and graphical manner using Google Colab.

The output of this project is a Google Colab notebook that produces a formatted report ready for export to the appropriate stakeholders.
In our opinion, this fits under the category of "software bots" in the DevOps course.

### CODE REVIEW

**Comment by khesoem** [comment]
Good proposal. Try to introduce some more specific tools (not just Colab) as well.

**Comment by khesoem** [comment]
It seems that Per Arn has already proposed five tasks and this is the sixth one. Is this right? You cannot propose six tasks.

**Comment by PersonligaPersson** [comment]
@khaes-kth Would it be a problem to submit this as only one person?

**Comment by ArnPellesGit** [comment]
> It seems that Per Arn has already proposed five tasks and this is the sixth one. Is this right? You cannot propose six tasks.

Yeah I have indeed proposed six tasks now (including this one). I did not realize there was a cap on the amount of task proposals allowed. The reason being that I wanted to secure passing the course - if I were to fail one assignment (or more than one), then I'd compensate by doing more tasks.

**Comment by khesoem** [comment]
After double checking, I believe there is no rule prohibiting that. Go ahead!

**Comment by ArnPellesGit** [comment]
Cool, thank you :)

**Comment by monperrus** [comment]
@PersonligaPersson the deadline is approaching, please ping me when you submit the link to your tutorial in a new PR.

**Comment by PersonligaPersson** [comment]
Hi @monperrus. The final submission was made in PR #2034 . Please let me know if there are any issues.

**Pull request merged**
