### PR TITLE
amolt: Feedback for essay Task 1

### PR DESCRIPTION
**Pull request by Ana-Maria-O**
# Assignment Proposal

## Title

Feedback for Essay: DevSecOps: An Approach in Preventing and Responding to Worst-Case Cyberattacks like the SolarWinds Hack

## Names and KTH ID

  - Ana-Maria Olteniceanu (amolt@kth.se)

## Deadline

- Task 1

## Category

- Feedback

## Description

Original comment was made on the wrong PR: https://github.com/KTH/devops-course/pull/2107
Here is the correct PR with my comment on it: https://github.com/KTH/devops-course/pull/2159

### CODE REVIEW

**Comment by khesoem** [comment]
@Ana-Maria-O thanks for the proposal

when was the final essay submitted? Isn't it already more than 48 hours after the submission?

**Comment by Ana-Maria-O** [comment]
@khaes-kth The essay was submitted on the 11th of April, so it was less than 48 hours before my feedback. Despite that, we asked Musard in the last lecture and from what I can remember he said that the feedback had to be submitted 48 hours after the deadline, not after the essay submission.

**Comment by Ana-Maria-O** [comment]
Ah I double checked and it seems that I made the comment on the wrong pull request. I'll fix that in my PR

**Comment by khesoem** [comment]
@Ana-Maria-O OK, I'll merge this PR as the essay submission was merged 2 days ago

**Pull request merged**
