### PR TITLE
Finished: [Tutorial] An introduction to unit test, regression test and code coverage with IntelliJ 

### PR DESCRIPTION
**Pull request by Marcus9512**
# Tutorial
## Members
Marcus Jonsson Ewerbring (marcusew@kth.se)
Github username: Marcus9512

Diego Leon (dleon@kth.se)
Github username: dieflo4711

## Topic
An introduction on how to use unit testing, regression testing and code coverage with IntelliJ. 

Testing is an important software engineering practice and necessary to keep the state of quality of the software product or service under test. We will focus on Unit testing and regression testing. Code coverage provides critical information about where to focus testing, and is an important metric in Software testing.

We are planning to publish this on medium, katacoda or some forum that fits the tutorial.
## Preliminary structure

* Introduction
* Why should we test our program
    * What is unit-testing and why is it important
    * What is regression testing 
    * What is code coverage
    * Why we (the authors) think testing is important
* How to create a maven project in IntelliJ
* Applying unit testing to the project
    * Easy example
    * More advanced example
* Applying regression testing to the project
    * Easy example
    * More advanced example
* How to use code coverage with IntelliJ
    * Different tools for code coverage
* Summary

## Whats unique about this tutorial
The unique part of the tutorial is that it explains how you do unit tests, regression tests and code coverage in the same tutorial.
We also include our personal opinions regarding the areas and gives a easy and more advance example on how to implement these methods in IntelliJ.

## Finished tutorial
The tutorial can be found [here](https://medium.com/@marcus.jonssonewerbring/tutorial-an-introduction-to-unit-test-regression-test-and-code-coverage-with-intellij-b08be1268719)

### CODE REVIEW

**Comment by gluckzhang** [comment]
Hi @Marcus9512 , thanks for the submission!

**Comment by bbaudry** [comment]
Feedback per #543

Thank you for completing the tutorial early and for providing clear guidelines. You have decided to deliver a tutorial on unit testing and code coverage, which is very important for DevOps, but neither this topic or the technology (Junit, jacoco) is very original. Hence, you should target a tutorial that is very readable, informative and usable. The comments below are suggestions to improve these points.

Comments:
- general comment about the code examples: it is very good to have code snippets in the tutorial. However, you use screenshots, which are pretty small, while you could embedd the code snippets directly in the post. This would improve readability. For example see [this post](https://medium.com/@aryamurali/embed-code-in-medium-e95b839cfdda)
- Introduction: assuming IntelliJ and Windows is too much constraint for a beginner's tutorial about testing. Since you use Maven, JUnit and Jacoco to run the tests and get the coverage, I strongly suggest that you make  the tutorial independent of any IDE and OS. This would drastically increase its usability and relevance.
- 'Why should we test our program'
  - Warning: testing cannot 'ensure that the software is bug-free'
  - When you refer to spacecraft Mariner 1, please add a short background to explain the bug, what is Mariner 1 and to explain why you chose that specific example.
  - 'What is unit-testing': an example of method and unit test (taken from your github repo) would help
  - when you mention the benefits of unit testing, please add a reference about this statement
  - 'What is regression testing': an example would help, for example change the method used as example for 'what is unit testing' and discuss if the test passes or fails
  - 'Automated tests': typo: "the propose of automation"
  - 'What is code coverage':
    - warning when you state that 'High code coverage reduces the chance of the code containing bugs'; high code coverage with no assertions will leave most of the bugs.
    - it would be good to add an example of a code coverage report
- 'A guide to testing!'
  - as suggested above, I strongly encourage giving the tutorial instructions outside a specific IDE.
  - I like the idea of having different kinds of test (nominal case, corner case, random, etc.). I encourage you to find additional resources where the beginner reader can dig deeper in these different types of tests as well as different types of coverage (MC/DC, partition, etc.)
- Easter egg: where is the easter egg / fun part here ?
- 'Final words'
  - 'When you create tests you should thrive after 100% code coverage': no, this is not a good advice. For any realistic project, 100% code coverage is not the target, for many reasons including time to write and maintain the tests, time to run them, etc. Please, look at real-world, well tested Java projects and their code coverage as examples, e.g., from the Apache foundation.

**Comment by Marcus9512** [comment]
Hello!
Thanks for the great feedback @bbaudry, we will try to implement the most of it. However, in our initial pull request, we had specified that the tutorial would be in IntelliJ which we saw as the "unique/original part". That pull-request was accepted so we assumed that it was ok to have that as our main focus in this tutorial, see #475 . 

We are not sure if we have time to rewrite the tutorial to work outside IntelliJ before the deadline (have a demo and essay to write). We wonder if this tutorial can pass without removing the IntelliJ part (which is more or less the entire tutorial).

Again, thanks for the feedback.

**Comment by dieflo4711** [comment]
Hi,

Thanks for the feedback! For our easter egg, we present tools that can generate unit tests for you and show the reader how to use them. 

We would like to know if it's the presentation of our easter egg that is unclear, or if it's our easter egg that doesn't count as an easter egg.​

Best regards, Diego

**Comment by bbaudry** [comment]
Hi  

@dieflo4711, an easter egg should be hidden and fun, while the automatic generation of tests is not hidden in your tutorial and the fun part is not obvious. In software, an easter egg is typically revealed only when executing a specific function, as in the [man command](https://unix.stackexchange.com/questions/405783/why-does-man-print-gimme-gimme-gimme-at-0030)

@Marcus9512, if you stay within IntelliJ, it is important that the rest of the tutorial has no other prerequesite, and should include some original material, e.g. advanced code coverage features, pointers to more resources and other things suggested in the feedback

Best regards,
Benoit

**Comment by Marcus9512** [comment]
Hello @gluckzhang and @bbaudry !

We have now updated the tutorial with the feedback in mind. We did not submit a new PR because of the Medium link is still the same. Down below is a summary of what we did:

* Changed all code images to code snippets
* The tutorial should work on Windows, Linux, and Mac, however, we will still use IntelliJ because that is what the entire tutorial is about and we regard it as a unique attribute to our tutorial.
* Updated the section 'Why should we test our program' with more examples, added more information about Mariner 1, which we consider a fun fact. We fixed all the changes that were suggested by @bbaudry except adding an example from our repo regarding unit testing. We didn´t add it because we will cover that in 'A guide to testing!'
* In a guide to testing, we added more methods and additional reading regarding Unit-testing and code coverage. The sections ' Additional test methods' and 'Additional code coverage methods' were added.
* 'Easter egg', Because 'Automatic unit test generation' didn´t count as an easter egg we changed it to an extra part in our tutorial.
* We added 'Before you leave, some fun facts/easter eggs' Which tells about one removed easter egg in IntelliJ and an additional fun fact.
* The faulty statements in 'Final words' where fixed. 

Regards, Marcus and Diego

**Pull request merged**
