### PR TITLE
Open-source: contribution suggestion Travis

### PR DESCRIPTION
**Pull request by louisezetterlund**
# Tutorial Proposal
 ## Members
 Louise Zetterlund (louiseze@kth.se)
 Johanna Iivanainen(jii@kth.se)

   ## Topic
 Implementing Travis on an Neherlab 
 Neherlab has an open-source project working with COVID-19, where one of the issues is to use Travis or CircleCI for continuous integration. [See issue](https://github.com/neherlab/covid19_scenarios/issues/19)

   ## Solution
We would like to solve this issue for them.

### CODE REVIEW

**Comment by gluckzhang** [comment]
Hi @louisezetterlund , the proposal sounds quite meaningful, and relevant to DevOps. For PRs of open-source contribution, I would like to invite @monperrus and @bbaudry to take a look as well.

Thank you!

**Comment by johannaii** [comment]
@monperrus @bbaudry is it okay if we choose this issue for the open source contribution task?

**Comment by gluckzhang** [comment]
Hi @johannaii @louisezetterlund , FYI, in order to help mitigate the impact of COVID-19, we created a new category of task: [Software contributions to mitigate the impact of COVID-19](https://github.com/KTH/devops-course/tree/master/contributions/covid19)

I think your PR suits this new category well, could you update the folder path?

**Comment by louisezetterlund** [comment]
Hi @gluckzhang! It feels like the criteria are more difficult for the covid19 category than for the open-source. Is it okay if we keep it in open-source?

**Comment by gluckzhang** [comment]
> Hi @gluckzhang! It feels like the criteria are more difficult for the covid19 category than for the open-source. Is it okay if we keep it in open-source?

Hi @louisezetterlund , for me it's fine to keep it in the current category. Let's wait for @monperrus and @bbaudry 's opinions :)

**Comment by louisezetterlund** [comment]
Hi @gluckzhang 
Unfortunately, someone already started solving the linked issue, so we'll keep looking.

**Comment by gluckzhang** [comment]
Oh that's a pity. Thanks for the effort!

**Pull request closed without merging**
