### PR TITLE
Demo proposal

### PR DESCRIPTION
**Pull request by muhammad1928**
# Assignment Proposal

## Title

Disaster Recovery using Terraform

## Names and KTH ID

  - Linus Svensson (linussve@kth.se)
  - Muhammadsodiq Nematjanov (mnem@kth.se)

## Deadline

Week 5 

## Category

- Demo

## Description

This demo will demonstrate mainly how terraform can be used as a strong tool for disaster recovery and creating Virtual Machines on Google Cloud Services, as well as how to create an infrastructure as desired using terraform.

**Relevance**

By automating recovery processes, organizations can improve resilience, efficiency, reliability, compliance, and customer experience. This is essential in today's fast-paced, technology-driven world, where downtime can have severe

### CODE REVIEW

**Comment by muhammad1928** [comment]
update

**Comment by javierron** [comment]
@muhammad1928 the name of the file should not contain spaces

**Comment by javierron** [comment]
@muhammad1928 Also, please add the week to the pull request title

**Comment by muhammad1928** [comment]
is it enought if i delete the spaces?

added week on the title

**Pull request closed without merging**
