### PR TITLE
Executable tutorial proposal: setup systemd-nspawn container on linux

### PR DESCRIPTION
**Pull request by 8ar10der**
Member
Sui Yuehao yuehao@kth.se

### CODE REVIEW

**Comment by khesoem** [comment]
Hello,

Your chosen topic is relevant. However, if I understand correctly, your tutorial will be very short (probably with less than 10 commands). Won't it?

**Comment by 8ar10der** [comment]
> Hello,
> 
> Your chosen topic is relevant. However, if I understand correctly, your tutorial will be very short (probably with less than 10 commands). Won't it?

Not just create, I will introduct lots of configs, such as Resource control, Networking etc. It of course will more than 10 commands.

**Comment by khesoem** [comment]
> I will introduct lots of configs, such as Resource control, Networking etc

In that case, please be more specific in your proposal. Determine what you will exactly show.

**Comment by 8ar10der** [comment]
Ok, I will make a new PR later.

**Pull request closed without merging**
