### PR TITLE
Executable tutorial proposal: Installing GitLab in your own infrastructure

### PR DESCRIPTION
**Pull request by nalenz**
# Assignment Proposal

## Title

Installing GitLab in your own infrastructure

## Names and KTH ID

- Julian Nalenz (nalenz@kth.se)
- Elias Bonnici (bonnici@kth.se)

## Deadline

Task 2 (2022-04-19)

## Category

Executable tutorial

## Description

When companies grow, they often face the requirement of having full control over their Source Code Management tool, so it is not possible anymore to use github.com or gitlab.com. Instead, this service needs to be hosted in their own infrastructure, e.g. to enforce certain company policies regarding access control or to be able to determine the server location.

This executable tutorial should showcase how the platform GitLab can be installed in a newly set up AWS infrastructure. It will move through all the setup and configuration required for the GitLab instance to be fully usable and will give a quick overview of possible next steps and which additional features the paid version of GitLab offers.

### CODE REVIEW

**Comment by nalenz** [comment]
That is wrong, I did not register for this task yet.

**Comment by vladomit** [comment]
> That is wrong, I did not register for this task yet.

You should put your proposal in the correct task folder then. This one is in the demo folder.

**Comment by nalenz** [comment]
@vladomitrovic You're right, thanks for the hint! I fixed it now, please have a look at it again.

**Comment by javierron** [comment]
Hello @nalenz, as we discussed on the lab session, this proposal is very relevant for the course. Looking forward to see your work.

**Pull request merged**
