### PR TITLE
 Presentation Proposal: Cloud and the journey for a start-up to Fortune 500 (Follow up) 

### PR DESCRIPTION
**Pull request by MDRezaulHasan**
Hi @khaes-kth, @monperrus  said us to follow up with the previous presentation. We can focus in detail on load balancing and auto-scaling. So what we did, we make a new presentation that explains deep of auto-scaling and load balancing. If you want I can send you the email which marting send us.

### CODE REVIEW

**Comment by MDRezaulHasan** [comment]
@khaes-kth, Please let us know what we will do? We have our presentation tomorrow.

**Comment by khesoem** [comment]
Hi @MDRezaulHasan,

Since Martin proposed this topic, I think we can merge this PR.

Good luck,

**Comment by khesoem** [comment]
@MDRezaulHasan 

I just wanted to make sure you are aware that your PR has been merged. Did you noticed this?

**Comment by MDRezaulHasan** [comment]
Yes, thank you

**Pull request merged**
