### PR TITLE
Presentation proposal: containerized applications (group T1G27)

### PR DESCRIPTION
**Pull request by FelixEder**
### Presentation T1G27

Containerized applications.

Discuss: 
* What are containers?
* How do they work?
* What are they used for?
* Advantages/disadvantages
* Available tools and techonologies

**We want to present at the April 1st lecture.**

### CODE REVIEW

**Comment by SophieHYe** [comment]
Hi,
We are dropping the numbering of the groups, can I rename the folder name to felixed-erikjo9 according to the email address of you and your partner?

**Comment by FelixEder** [comment]
@SophieHYe sure!

**Comment by FelixEder** [comment]
@SophieHYe @monperrus @gluckzhang There seems to be an error here? We asked to present at april 1st (week 3) but we are placed in the week 2 folder? Could we please be moved to week 3 folder? :)

**Comment by gluckzhang** [comment]
Hi @FelixEder , indeed, it seems an mistake, sorry :)
Hi @SophieHYe , could you please review this PR again, together with #73 , thanks!

**Comment by gluckzhang** [comment]
@SophieHYe never mind, I just meged the #73 :)

**Pull request merged**
