### PR TITLE
feedback proposal Task 3 emilk2

### PR DESCRIPTION
**Pull request by saffronjam**
# Assignment Proposal

## Title

Feedback on "A fault injection platform for learning AIOps models"

## Names and KTH ID

Emil Karlsson (emilk2@kth.se)

## Deadline

Task 3

## Category

Feedback

## Description

I would like to submit feedback for [this essay](https://github.com/KTH/devops-course/pull/2165).

### CODE REVIEW

**Comment by khesoem** [comment]
Hi @saffronjam 

Thanks for the proposal! The feedback should be submitted at most two days after the deadline for essay submission. So, I'm closing this PR.

**Comment by saffronjam** [comment]
Hi!
Thanks for the reply. How would one go about this then?

Should I just look for an essay that is marked finished by you, and then immediately write feedback without 'proposing' it to you first?

**Comment by khesoem** [comment]
Hi

You can propose it when the essay is proposed (before it is submitted).

**Comment by saffronjam** [comment]
Ok! Thanks ☺️

**Pull request closed without merging**
