### PR TITLE
Presentation : DevOps adoption in large Enterprise through Continuous Testing

### PR DESCRIPTION
**Pull request by Renugaa**

### CODE REVIEW

**Comment by gangwalmegha** [comment]
Hello @khaes-kth,
Now we have created a new pull request as per your suggestion. Can you please merge this PR so I can have the task assigned to my kth id(gangwal@kth.se). Our old PR is #984

**Comment by khesoem** [comment]
Hi @gangwalmegha 

Good. Now you have removed feedback and essay proposals. Please also remove the `devops-course/contributions/presentation/week3/renanb-ved.megha/` directory. If I understand correctly, it was the old directory you used to put your presentation in. Right?

**Comment by Renugaa** [comment]
Hi Khaes,

We have deleted the above directory in our repo and created a new one as suggested - **https://github.com/Renugaa/devops-course/tree/Presentation/contributions/presentation/week3/renanb-gangwal** and created a new pull request #1285. Please delete the directory `devops-course/contributions/presentation/week3/renanb-ved.megha/` from your repo!

Thanks,
Renugaa

**Comment by Renugaa** [comment]
Hi @khaes-kth,

We have deleted the above directory and created a new pull request https://github.com/KTH/devops-course/pull/1300. Please review it!

Thanks,
Renugaa

**Comment by khesoem** [comment]
Hi @Renugaa 

I merged both #1300 and this PR. You could have removed that directory in this PR by pushing a new commit as well.

**Pull request merged**
