### PR TITLE
Feedback proposal: Gradle and Github actions Executable Tutorial

### PR DESCRIPTION
**Pull request by joakim-olsson**
# Assignment Proposal

## Title

Feedback on "Gradle and Github actions Executable Tutorial" [#1780]

## Names and KTH ID

- Joakim Olsson (joakiols@kth.se)

## Deadline

Task 4

## Category

Feedback

## Description

I would like to give feedback on the executable tutorial "Gradle and Github actions Executable Tutorial" by Filip Sannervik & Kunal Bhatnagar.

### CODE REVIEW

**Comment by monperrus** [comment]
@joakim-olsson where can we read your feedback? Thanks!

**Comment by joakim-olsson** [comment]
@monperrus 
Hi! I made this PR after realising that I already had a PR for creating a demo week 4, therefore I haven't finished this feedback task

**Comment by monperrus** [comment]
do you mean you drop this task?

**Comment by joakim-olsson** [comment]
@monperrus Yes since I was suppose to present this [Demo](https://github.com/KTH/devops-course/pull/1941) for week 4 so this was a duplicate week 4 task and I decided to not do any tasks for week 5.

**Pull request merged**
