### PR TITLE
Submission: feedback on essay

### PR DESCRIPTION
**Pull request by isacarvid**
Members: @isacarvid (isacarv@kth.se)
Feedback proposal can be found in KTH#1128
Feedback comment [here](https://github.com/KTH/devops-course/pull/1379#issuecomment-827652214)

 task |Yes | No | Remarkable
--|-- | -- | --
The feedback includes both strengths and weaknesses about the task | Yes | -|-
The feedback is provided 4 business days before the task deadline | Yes | -|-
All points are clearly actionable | Yes | -|-
The feedback is substantiated | Yes (at least 500 words) | -|-
The feedback contains pointers to additional material | Yes | -|-
The students act upon the feedback they receive |  **yes(I hope so)** |-|-

### CODE REVIEW

**Comment by khesoem** [comment]
hi @isacarvid 

Your feedback submission should only change the `contributions/feedback` folder. [This PR is also changing](https://github.com/KTH/devops-course/pull/1399/files) the `contributions/essay` directory. Please fix it ASAP.

**Comment by isacarvid** [comment]
Hi @khaes-kth!
I fixed the PR so that it only changes the feedback folder. Thanks for the heads up!

**Comment by khesoem** [comment]
> I fixed the PR so that it only changes the feedback folder

Great.

Please add a link to your feedback comment to your README.

**Comment by isacarvid** [comment]
> Please add a link to your feedback comment to your README.

thanks, @khaes-kth, It's done!

**Pull request merged**
