### PR TITLE
Added Final Essay submission: (Task 2), MLOps: The past, the present, the future

### PR DESCRIPTION
**Pull request by vishalned**
# Assignment Proposal

## Title

MLOPS: The past, The present and The Future

## Names and KTH ID

- Ennio Rampello (ennio@kth.se)
- Vishal Nedungadi (vishaln@kth.se)

## Deadline

Deadline for task 2

## Category

Essay

## Description

We all know about where MLOps is right now, with azure, aws, kubeflow and various services supporting mlops. But did you know that MLOps saw its origins in a research paper? With this essay, we are going to highlight how MLOps began, where it is now, and the future of MLOps.

### CODE REVIEW

**Comment by vishalned** [comment]
Hey @javierron , on latex it showed the word limit as ~2350, but here its showing something else. Kindly let us know if it is going to be a problem. Thanks in advance

**Comment by khesoem** [comment]
@vishalned , we count the words using this command. `sudo pdftotext "${added_file}" - | tr -d '.' | wc -w`

Please fix the word count and I'll merge this. Thanks

**Comment by vishalned** [comment]
Alright I will try, kindly give me some time and I will do it, I’m out of
Sweden, but will try to get a laptop as soon as possible

**Comment by khesoem** [comment]
Fine! Try to do it ASAP, as we are starting to grade this deadline submissions.

**Comment by vishalned** [comment]
Now the word count is correct.

**Pull request merged**
