### PR TITLE
Uploaded screen cast

### PR DESCRIPTION
**Pull request by MDRezaulHasan**
Please accept my request. I was upload screencast for demo.

### CODE REVIEW

**Comment by gluckzhang** [comment]
Hi @MDRezaulHasan , why a screencast is a `.exe` file instead of a link to the video you uploaded to Youtube?

**Comment by MDRezaulHasan** [comment]
Can i send a new pull request with youtube link?

**Comment by MDRezaulHasan** [comment]
I update my video. Can you give me some feedback

**Comment by gluckzhang** [comment]
I'll merge the PR. But I don't think it's possible to receive feedback before the final deadline. The feedback session for demos have passed.

**Comment by MDRezaulHasan** [comment]
Thanks

**Pull request merged**
