### PR TITLE
opers-jarns Presentation proposal, week 2

### PR DESCRIPTION
**Pull request by oscarzhpersson**
**The pull request must both contain a README.md and have description following this template:**

**The README.md file must be located in the directory**:

`contributions/<kth-id-1>-<kth-id-2>/<category>/[<week>/]README.md`

# Assignment Proposal

## Title

_The title of your proposal_

Jepsen - Why do we need a separate framework for testing distributed systems

## Names and KTH ID
  - Oscar Persson (opers@kth.se)
  - Jonathan Arns (jarns@kth.se)

## Deadline

_Selected deadline for the assignment_

- Week 2

## Category

_Category of your proposal_

Presentation

## Description

_Description of your proposal_

We would like to give a presentation about the testing framework Jepsen, a framework made for the testing of Distributed Systems. It is a framework that tests distributed systems, specifically, for resilience against partial failures. The presentation will delve into why such a tool is necessary, how it works, how it compares to more conventional testing frameworks (why they can not/should not be used for the same task), and a brief overview of how to use it.

The presentation will have a focus on why this type of tool is necessary and why it should not or can not be done with other tools.

### CODE REVIEW

**Comment by khesoem** [comment]
Hi @oscarzhpersson 

Thanks for submitting your proposal.

They proposal should follow the rules. It should only include a README file (you have added [five](https://github.com/KTH/devops-course/pull/2061/files)). It should put the README in a subdirectory of the target task (like `contributions/presentation/week2/opers-jarns/README.md`, not `contributions/opers-jarns/presentation/week2/README.md`). And the README file should not change the suggested headers or add unnecessary line breaks, etc. For example, you shouldn't add a `### Relevance` header. It should simply look like one of the READMEs from previous year such as this one: [https://github.com/KTH/devops-course/blob/2022/contributions/presentation/week2-testing-and-CI/svanhol-libl/README.md](https://github.com/KTH/devops-course/blob/2022/contributions/presentation/week2-testing-and-CI/svanhol-libl/README.md).

Please fix the PR so that it passes the check and TAs will assess it.

For your note: @Deee92 @javierron @SandZn

**Comment by oscarzhpersson** [comment]
@khaes-kth Hello!

We removed the accidentally pushed .DS_STORE files, and the relevancy header. I would like to add, though, that the relevancy header is part of the template that you provide.

Thank you, and we will now see if the TAs @Deee92 @javierron @SandZn accept it.

**Comment by khesoem** [comment]
@oscarzhpersson Thanks for fixing the issues! The template is also updated now.

**Comment by oscarzhpersson** [comment]
[DD2482 Week 2 - Presentation_ Jepsen.pptx](https://github.com/KTH/devops-course/files/11143039/DD2482.Week.2.-.Presentation_.Jepsen.pptx)

**Pull request merged**
