### PR TITLE
Submission of Course Automation

### PR DESCRIPTION
**Pull request by Spycsh**
We submitted in #1105, but there was a folder name conflict in the PR. Here we solved this conflict. 

This project creates GitHub action, which checks the validity of the links in the modified content for a pull request. If there are invalid links in the added content, the output of the GitHub action should be false, and the pull request will be **closed**. Meanwhile, the invalid links are **commented** in the closed pull request so contributers can be notified about the invalid links. This action should be triggered by pull_request_target event, which means it can serve as an early-check before manual merging. Notice that we only check the links which start with **http://** and **https://**

### CODE REVIEW

**Comment by Spycsh** [comment]
Hi, 

You can view our concrete implementation code and the usage of this automation tool with the link below:

[https://github.com/Chen-Zidi/check-modified-contents-link-validity-action](https://github.com/Chen-Zidi/check-modified-contents-link-validity-action)

This GitHub Action that we create can be used not only in devops course but also in other github projects and is simple to use. We also plan to publish this Action to Marketplace later. If you have any advice, please contact us, thank you very much!

**Comment by Chen-Zidi** [comment]
Published on market place https://github.com/marketplace/actions/check-links-in-the-modified-content-validity

**Comment by Chen-Zidi** [comment]
Hi! We have a demo at https://github.com/Chen-Zidi/devops-course. The action name is check-link-validity.

**Comment by Spycsh** [comment]
Hi @khaes-kth , we think all the work have been done based on your updated explanation of [grading](https://github.com/KTH/devops-course/blob/khaes-kth-course-automation-clarification/grading-criteria.md) for course automation, can you have a check on it?

- [x] publish on marketplace (yes)
- [x] demonstrate that this action actually work and yield useful results (yes because you can see the demo [here]( https://github.com/Chen-Zidi/devops-course), with the action name `check-link-validity`)
- [x] The action is created before April 6, 2021 (yes)
- [x] The automation task produces a PR status or issue / PR comment (remarkable because we will close the PR with a comment pointing out which the link is if there are invalid links in the PR)
- [x] The automation task is reusable (remarkable because it can be viewed on marketplace [here](https://github.com/marketplace/actions/check-links-in-the-modified-content-validity))
- [x] The task runs on a standard platform (yes)
- [x] The code for the task is available and well documented (remarkable)

**Comment by khesoem** [comment]
Hi @Spycsh 

I think your submission is ready to be reviewed/graded. Thanks for the submission.

**Pull request merged**
