### PR TITLE
Essay submission

### PR DESCRIPTION
**Pull request by ghost**
Version ready for feedback 
[Overleaf: BDD in DevOps](https://sv.overleaf.com/read/krsgwnmhcbnx)

### CODE REVIEW

**Comment by ghost** [comment]
@heeenkie the essay is ready for feedback!

**Comment by heeenkie** [comment]
Hi @anorangesky , I will try to get the feedback ready by the end of the day!

**Comment by heeenkie** [comment]
# Feedback #
I have divided the feedback according to the different headings to make it easier to read. I've also added plus and minus signs to easier follow the strengths and weaknesses.
 
 ### 1 Introduction ###
 &plus;  A good introduction that addresses the broader subject. Since my knowledge about BDD is zero, it was really good with a simple introduction like this.

 &minus; In the first sentences, you are stating a few claims about bad teamwork, e.g. "It is a me-first mentality, with a lack of trust and transparency. People’s unique strengths and weaknesses are not valued, the goal is not in focus, and conflicts exist.". I recommend you to change the opening to something like -"in teams with bad teamwork there could be ..." or find some references that support your claims because of teamwork.

 ### 2 Behavior-driven development ###
 &plus; This paragraph was really well written and informative. It was, despite the informative language, easy to follow and understand. 
 &plus; A relevant and nice looking illustration is always appreciated.
 
 &minus; The only thing to mention here is that you are pointing at the figure ?? instead of figure 1.

 ### 3 Getting up to speed with BDD ###
 &plus; A deeper dive into bdd. I liked this part as well since it was instructive in a way that caught my interest. 
 &plus; Here too, a relevant illustration that makes the whole paragraph easier to understand 
 
 &minus; I found two minor grammatical errors at the end of the paragraph: 
 - "... it is time to formulate how it can later automated".
  And it should be:
  - "... it is time to formulate how it can later be automated".


 - In the following sentence, the word "set" should be replaced with either "given" or "fixed"
 

 ### 4 Three Amigos ###
 &minus; change the sentence "The idea behind it is to make ..." to "The idea behind it, is to make ...".
 
 ### 5 The DevOps lifeloop ###
 &plus; Easy to understand the paragraph and also makes it easier to follow with the figures.
 &plus; I like how you build up the paragraph with the parallels devops-agile and bdd tdd.
 
 ### 6 BDD as DevOps practice ###
 &plus; This was an interesting paragraph with good concrete examples of BDD practices. It would also be interesting to expand this paragraph for a longer discussion about this. 
 
 ### 7 Tools and Frameworks ###
 &plusmn; Since my knowledge about BDD was limited I like how you presenting different tools for BDD and also gives references to these. I gained a lot from just be given these examples. Maybe it is a waste of space for this essay to give each and every tool its own paragraph. Consider removing this paragraph and introduce these tools shorter in the previous paragraph.
 
  ### 8 Conclusion ###
 &plus; Some ending sentences about bdd that sum it up well. Short, simple and straight forward.
 
 ### References ###
 I think the references are misused throughout the whole essay. In your defense, I think it's the tool that you have used in latex that messed some things up but I am going to point out the flaws anyway.
 
 &minus; A reference should not be placed after the paragraph to refer to the whole text. Instead, it should be placed in the sentence that you are talking about it.
 
 &minus; References should be in ascending order after their appearances in the essay.
 
 &minus; The references in the list, lack information such as author publication date, URL, etc.

**Comment by ghost** [comment]
Thank you for the feedback @heeenkie! 
I have now updated my essay accordingly. 

## Changelog 
General: I have shortened the essay and imported a package for latex which makes it work with the IEEE standards
### Intro
- Rephrased the section to be more concise (removed unnecessary wordings) and added a reference that strengthens the statement
### BDD 
- Fixed bug with referencing to figure in Latex
### Getting up to speed with BDD 
- Fixed the typos 
### three amigos 
- Moved this section to be a subsection of 'getting up to speed with BDD'
### Tools and frameworks 
- made this section as a subsection of 'BDD as a DevOps practice'
- Shortened the section about Gherkin since it was a bit out of scope 
### References
- Imported the IEEE package to Overleaf which solved the bug with the references

**Comment by monperrus** [comment]
@anorangesky please rebase, the diff should not show a change in `contributions/executable-tutorial`, it should only the PDF.

**Pull request closed without merging**
