### PR TITLE
The demo is now completed

### PR DESCRIPTION
**Pull request by felixlut**
The screencast can be found [here](https://www.youtube.com/watch?v=UXS62qZ-0F4), and the accompanying repository [here](https://github.com/jvikstrom/kth-devops-demo)

### CODE REVIEW

**Comment by Zodbigt** [comment]
I will give feedback on this one

**Comment by christinerosquist** [comment]
I can give you feedback on the demo! :)

**Comment by eywoon** [comment]
I will give feedback

**Comment by javierron** [comment]
I will give feedback :)

**Comment by veggiemonk** [comment]
I will give feedback

**Comment by Mema5** [comment]
I'll give feedback here as well :)

**Comment by Mema5** [comment]
# Feedback 
I really liked your demo and I learned a lot by watching the video!

## Positive points
- Love the music :+1: 
- Very nice github repo with good readme, good structure and everything that is necessary. +1 for the screencast steps!
- Good and clear progression in your demo: from unbalanced situation to well-balanced situation, that we can see in the graphs :+1: 
- Detailed and self-sufficient video description

## Points to improve
I think the biggest negative point is that there is too much text to read. It is almost impossible to follow the commands in the terminal + the text without pausing the video when you watch it. (one example: 4 lines of subtitles minute 4:35!). Consider: 
- having more concise subtitles, more like headers 
- recording yourselves reading the subtitles, so that we can concentrate on what happens in the screen

**Comment by veggiemonk** [comment]
|                                             | Yes | No | Remarkable |
|-------------------------------------------- | ----|----|-------------|
|The demonstration screencast is clearly motivated (why it matters for Devops?) | **Yes** X | No | Remarkable |
|The demonstration screencast is difficult to do | Yes | No | **Remarkable** X |
|The demonstration screencast is original | **Yes** X | No | Remarkable |
|The demonstration screencast is sublime (eg visually appealing) | Yes | **No** X | Remarkable |
|The demonstration screencast contains an easter egg | Yes | **No** X | Remarkable |
|An accompanying Github repository has been made (optional) | Yes | No | **Remarkable** X |

Great demo 👍 

At the beginning, there is a clear definition of the problem.

The presentation of the solution could use a bit more explaining about what is `linkerd` and why is this a the best tool for the job.

At the end, the solution clearly showed the problem was solved.

The music was annoying for me and the subtitle were a bit difficult to follow, 
but that is more of a personal taste.

I could not find the easter egg 🤷‍♂️ 

Conclusion: remarkable.

**Comment by Anthial** [comment]
@veggiemonk Our easter egg is well hidden,  but if you pay close attention to the graphs you might find something interesting. 🐊

**Comment by Anthial** [comment]
Also thank you @Mema5 and @veggiemonk for the feedback :)

**Comment by felixlut** [comment]
0.5 speed is your friend!

**Comment by javierron** [comment]
- Very useful content.
- The load balancing graphs could be better presented (axis names, reference values, etc)
----
- Video has a strange "jump" (0:27)
- Video recording quality could be improved
- The font used for subtitles felt strange and was hard to read for me

**Comment by eywoon** [comment]
Very detailed step-by-step introductions in the repo. 

The demo has a clear motivation for why we want to use this and was very informative and easy to follow for those unfamiliar with the problems.
The demo is very original and looks technologically difficult to do. It’s a nice video to watch, at a good pace.

Improvements:
- Sometime there is a bit too much text
- Explain what linkerd is

Overall, very cool content and relevant

**Comment by christinerosquist** [comment]
## Feedback

Great demo and really nice job with the repository (it describes everything very well). The steps are also well described. One comment is that you might consider zooming in more in the terminal and the screen, sometimes it could be hard to see everything on the screen since it was a bit zoomed out. At 3:19, the sentence is not finished and feels a bit “cut off”. I would suggest finishing the sentence in the same textbox so that we don’t have to wait until the next box in order to read the whole sentence. The easter-egg was hard to find, I think that it would be better if you hinted about it in the video somewhere. Good luck and once again, nice job! :)

**Comment by Zodbigt** [comment]
Thanks for the demo!

I love the music! Feels like I'm in the movie Interstellar or something and uncovering a mystery.

The subtitle for me at least goes by a little fast. But this could be my own personal preferences.

I know it's not a requirement, but a voice over would be really nice to have. 

A good and structured reademe me.
Also good that you linked everything in the description.
Great devops topic good job.

**Comment by Anthial** [comment]
@javierron @eywoon @christinerosquist @Zodbigt Thank you for your feedback! :D

**Comment by dieflo4711** [comment]
Liked it! The music was great as well and I learned a lot. It’s sometimes hard to read because of the different backgrounds. You could for example have a black background color for the text, and have white text. I think everything would look a bit more clean.

**Pull request merged**
