### PR TITLE
Course Automation Submission: GitHub action to show what is available for feedback 

### PR DESCRIPTION
**Pull request by Hilaire-Bouaddi**
# GitHub action to show what is available for feedback 

This submission corresponds to the following PR #1306. We now have a new member!

## Member 

Hilaire Bouaddi, bouaddi@kth.se [https://github.com/Hilaire-Bouaddi]

[NEW MEMBER] Kun Wu, kunwu@kth.se [https://github.com/Wkkkkk]

## Rationale 

It takes some minutes to check if a contribution we are interested in will receive feedback or not. This can generate frustration.
The aim of the proposal is to automate the labelization of PR to mark the ones that can be feedbacked. 

## The finished contribution 

This work resulted in a new workflow for the DevOps repository. This workflow named label.yml is in charge of labelling merged PRs.
This is the implemented behavior:
```
every time a push occures (including merge) to the 2021 branch / every time that a PR is created for the branch 2021:
    delete labels 'feedbacked', 'feedbacked claimed', 'feedbackable' from every PR
    add the label 'feedbacked' to all the valid PRs* that are referenced in a markdown file of the contributions/feedback folder
    add the label 'feedback claimed' to all the valid PRs* that are referenced in the body of open PRs
    add the label 'feedbackable' to all the other valid PRs*
```
*PRs that have the labels 'proposal' and either 'essay' or 'tutorial'.

Those are the following assumptions: 
* Every merged PR for a proposal of a contribution in an essay or an executable tutorial will get the labels 'proposal' and either 'essay' or 'tutorial'.
* Feedbacks have to mention both in their readme and in the body of the feedback PR the id of the PR of the contribution proposal that they want to feedback. 

Considering the number of students in the course, the script will make mistakes. Those mistakes will generally consist of setting the label to 'feedbackable' to merged PRs even if they will receive feedback because the feedback readme doesn't mention that PR. 

|                                             | Yes | No | Remarkable  |
|-------------------------------------------- | ----|----|-------------|
|The work is done before April 6, 2021 (in order to be useful for the course) | Yes | :white_check_mark: No | n-a|
|The automation task produces a PR status or issue / PR comment | :white_check_mark: Yes | No | Points to a generated page with valuable additional information |
|The automation task is reusable | :white_check_mark: Yes (next year for this course) | No | In other courses than this one |
|The task runs on a standard platform | :white_check_mark: Yes (Github action) | No | Other platforms (e.g. Moodle, Canvas) |
|The task is praised by the other students of this course | Yes | No | n-a |
|The code for the task is available | :white_check_mark: Yes (public repo) | No | Well documented repo |

### CODE REVIEW

**Comment by Hilaire-Bouaddi** [comment]
(the reason for the error in the workflows is precisely because this pull request has triggered the script that we want to integrate to the main branch (which is missing right now))

**Comment by khesoem** [comment]
Hi @Hilaire-Bouaddi 

Please read the [last version of grading criteria for course automation tasks](https://github.com/KTH/devops-course/blob/2021/grading-criteria.md#course-automation).

Please make the following changes as soon as possible:
1. remove the files you have added to `.github/workflow` directory.
2. upload your code into a separate repository.
3. show how your code works on a test repository (it can be a fork of `devops-course` repo).
4. add links to your code repo and test repo to your README.
5. remove the [old folder that only contains the name of one of your team members](https://github.com/KTH/devops-course/tree/2021/contributions/course-automation/bouaddi).

**Comment by Hilaire-Bouaddi** [comment]
Hello @khaes-kth , 

We tried to change the submission according to your comment. It should be done now. 

Hilaire

**Comment by khesoem** [comment]
> We tried to change the submission according to your comment. It should be done now.

Thanks. I do not see a link to your Github Action code. Can you add it to the README?

**Comment by Hilaire-Bouaddi** [comment]
Done!

**Pull request merged**
