### PR TITLE
Add initial demo proposal

### PR DESCRIPTION
**Pull request by JohanKJIP**
# Demo proposal

## Members

Johan von Hacht (johvh@kth.se)
David Johansson (davidjo2@kth.se)

## Topic

Demo of deploying a docker container to the cloud (e.g. Digitalocean).

### CODE REVIEW

**Comment by SophieHYe** [comment]
Thanks for the PR. The topic looks good.

**Comment by gluckzhang** [comment]
Agree with @SophieHYe , deploying containers to the cloud sounds a bit generic.
@JohanKJIP could you mention some details like the motivation / originality in this PR?

**Comment by JohanKJIP** [comment]
We chose the topic because we want to learn how to use and work with containers. Upon further research, it does seem quite simple and we therefore want to expand the demo to incorporate the whole CI/CD pipeline. This means we want to automatically deploy an application hosted in a repository to Digital Ocean with the help of e.g. Github actions.

Do we need to update the README file?

**Comment by SophieHYe** [comment]
Hello, 
Yes, please also update in ReadMe as well.
We may suggest also explore more aspects of the container and DigitOcean, such as comparing and presenting the development cost and performance.

**Comment by JohanKJIP** [comment]
@SophieHYe We have now added more details about our demo in the README.

**Comment by SophieHYe** [comment]
Thanks! I merged your PR.

**Comment by monperrus** [comment]
FYI, "the Actions API is now generally available and out of Beta" https://developer.github.com/changes/2020-03-23-ActionsGA/

**Pull request merged**
