### PR TITLE
Executable tutorial propsal: CI for Java Maven using Github Actions

### PR DESCRIPTION
**Pull request by elmaxe**
# Executable Tutorial: CI for Java Maven using Github Actions
## Members

Maja Tennander (majate@kth.se) [Github](https://github.com/majate)

Axel Elmarsson (axelelm@kth.se) [Github](https://github.com/elmaxe)

## Proposal:
This tutorial will show you how to setup CI for a Java Maven project with JUnit tests using Github Actions.
The Java code base will be simple, with just a few JUnit tests.
There will also be a section about why CI is good.
We will use medium.com

### CODE REVIEW

**Comment by thestar19** [comment]
I would like to give feedback on this. See  #1221

**Comment by khesoem** [comment]
Hi, this is relevant, but very similar to https://github.com/KTH/devops-course/pull/624. Proposals should not be duplicate.

**Comment by majate** [comment]
Ok, sorry, we only checked proposals from this year when we looked for duplicates.

**Comment by elmaxe** [comment]
Isn't it unreasonable to not allow "duplicates"/similar projects from previous years? We have to go through all previous years and check that no project is alike? It is already a tedious project to check that noone is doing the same thing this year.

Also, if no projects can be similar to previous years there will eventually be a shortage of things to write about (possibly nearly nothing to write about). What is the course's view on that?

I'm also pretty sure there are projects/demos that are similar to previous years' projects, but those are accepted. Why?

@khaes-kth

**Comment by khesoem** [comment]
Hi @elmaxe 

> Isn't it unreasonable to not allow "duplicates"/similar projects from previous years? We have to go through all previous years and check that no project is alike? It is already a tedious project to check that noone is doing the same thing this year.

I think there is no difference between checking this year's proposals and previous year's proposals. You can use the same search among the PRs for this.

> Also, if no projects can be similar to previous years there will eventually be a shortage of things to write about (possibly nearly nothing to write about). What is the course's view on that?

I personally agree to some extent with your argument. However, 1) this is the decision made by professors, 2) each year many new tools are introduced and they can be used by future students.

> I'm also pretty sure there are projects/demos that are similar to previous years' projects, but those are accepted. Why?

It can happen that TAs are unable to find similar tasks from previous year, but as students, you are supposed to check this yourselves. If some students do not do that, they are violating the rules.

**Pull request closed without merging**
