### PR TITLE
Essay for Grading: The Rust Build System

### PR DESCRIPTION
**Pull request by arxra**
## Contributors

- Aron Hansen Berggren
  Email: [aronber@kth.se](mailto:aronber@kth.se)
  Github: [arxra](https://github.com/arxra)
- Yannik Sander
  Email: [yannik@kth.se](mailto:yannik@kth.se)
  Github: [ysndr](https://github.com/ysndr)

## Initial proposal

Initial PR can be found here #1141

We are ready for feedback @Adamih :)
We are aiming to get a distinction, so please evaluate the essay to this standard.

### CODE REVIEW

**Comment by Adamih** [comment]
# Feedback for "The Rust Buildsystem"

As with any feedback, you may select what feedback to integrate into the text in order to reach remarkable, what can be fixed in an alternate way, and what can be discarded in its entirety.

First, will mention two points that apply to the document in its entirety. Then, I will mention section-specific feedback. Lastly, I will mention the most important/relevant things to fix (in my opinion) in order for you to reach a remarkable grade.

- **Grammar**: The title should be "_The Rust Build System_", (Maybe "_The Rust Build Pipeline_"?). "Buildsystem" is not a word.

- **Grammar**: I can recommend running the entire essay through a service like Grammarly to fix small errors like missing commas, punctuation, unnecessary words, general flow, etc. There are numerous punctuation errors so I did not note them down in the chapter-specific feedback.

- **Reference**: I'm not sure if it's okay to mix footnotes and references. This might not be proper, but I'm not sure.

## Section-specific feedback

### 1 Introduction

- **Comment**: It's nice that the goal of the Essay is spelled out very clearly.

  > We start off by explaining what we are looking at, before diving into the tools that ensure this project's integrity.

- **Grammar**: Grammar needs improving.

  > But how does DevOps Scale for projects as massive as rust an advanced programming language
  > which...

### 1.1 What is Rust

- **Comment**: I like this section. It's short and concise. It's perfect.

### 1.2 What is a "CI"

- **Comment**: I like that you brought up examples. Those examples carry this section at the moment.

- **Content**: Illustrations can be added here. CI is (most of the time) easier to illustrate than to explain concisely in my opinion and can be a great tool here.

### 2 The Rust Build CI

- **Comment**: I like that you clearly define the scope of this essay, and motivate why you scope your essay this way.

### 2.1 Rustbot

- **Comment**: It's not clear how this bot adds to the overall mission of the essay and it seems unimportant compared to bors.

- **Content**: The bot is called "Triagebot" according to your references. Please change the name to reflect this or acknowledge that the bot has a name in the Rust repository and another name for general use.

- **Content**: This bot does not seem to warrant its own section, but instead can be explained similarly to "rust-highfive" bot (but more in-depth).

### 2.2 Developing with bors

- **Comment**: I really love the structure here, and it illustrates a "mystery" of why bors is both unique and really advanced. You ask a great question at the end and it draws in the reader which is great.

### 2.2.1 The Pull Request

- **Comment**: Great illustration, and great explanation of what each bot's responsibility is! The "rust-highfive" bot explanation is short and concise.

- **Content**: It's not clear what "Mark the PR as rollup target" means, and it's not explained further in this section. Please add an explanation (max 1-2 sentences or just a small clarification).

  - Even though it's explained much later in the text, it leaves the reader hanging (and not in a good way). The minimal change that should be made is adding something in the spirit of: "What rollup is and what effects it has will be explained later when you know more about the rust build process/pipeline."

- **Content**: What is this quote referring to? If this is just rhetorical it should not be formatted as a quote in my opinion.

  > "What is tested, where, and how? After all, no traces of tests are present in the repository."

### 2.2.2. A bot's playground

- **Grammar**: This sentence probably needs to be rewritten

  > The whole CI runs on custom machines owned by the rust project, **such that resources are limited**.[8]

- **Reference**: Would love to see a reference for:

  > The extension of this is that it is not possible to run
  > more than eight auto builds per day and thus at most eight PRs are merged every day!

  I found the statement in [Another reference](https://forge.rust-lang.org/release/rollups.html). Here it says ~3.5hr (which multiplied by 8 is 28 hours of CI building per day).  
  A CI history entry probably works as a source if this one is outdated.

- **Comment**: I still really like that you ask questions that challenge the reader. It adds to the quality of the text and reading experience a lot.

- **Content**: Questions posed by/for the reader should probably not be formatted as quotes.

  > "Will all changes trigger a full build and test on 50+ platforms? Is that not kinda wasteful for simple changes such as correcting misspellings?"

  - **Grammar**: "kinda" (and similar filler words) should be removed.

### 2.2.3 Rollups

- **Comment**: I really like this introductory explanation of the central problem that rollups are trying to fix. This section in general is very good.

- **Content**: See my issues with "8 PR's per day" in 2.2.2.

### 2.3 The Green Master

- **Comment**: I'm not sure how to improve this segment. The quote seems out of place, but also I understand why it's there.

### 2.4 Action! Or lack there off

- **Comment**: This segment is pretty good, and I can see no apparent fault with it. I think there should be more focus on the benefits of custom tooling in this regard, and less focus on Github Action in general and its Lego-ness.

### 3 Wrap Up

- **Comment**: I really like this final segment. It's a good reminder.
- **Content**: Since the custom pipeline infrastructure was mentioned again here as an important part of the Rust build system, it should be explored or just talked about a bit more in the earlier segment.
- **Comment**: Nice final line. Yes, the Rust CI pipeline is somewhat extraordinary.

## Thoughts about meeting the grading criteria

- References: Most references seem to are from [forge.rust-lang.org](https://forge.rust-lang.org). It's a good source to reference, but I'm not sure if the variety of sources might become a problem.

- Title: Fix the grammar in the title.

- Innovative: I'm not sure what is considered innovative.

- Figures: Might need more illustrative figures for either in your introduction to CI or bots in action. CI can be a hard topic to explain.

- References: Again, I'm not sure if it's okay to mix footnotes and references. That is why I'm mentioning it here.

All other criteria I think are remarkable in quality. This is a fantastic essay and you both should be very proud.

**Comment by arxra** [comment]
Thanks a lot for the feedback, we'll incorporate it over today :)
See some great points in there, thanks for the thoroughness of it!

**Comment by arxra** [comment]
@cesarsotovalero we've incorperated the feedback and feel confident in our essay as a contribution. :)

**Comment by SophieHYe** [comment]
Thanks for the final essay. I am now merging your PR and we will grade your essay on the final version.

**Pull request merged**
