### PR TITLE
Presentation: Cloud and the journey for a start-up to Fortune 500

### PR DESCRIPTION
**Pull request by Internet-Person-IP**
## Members

Taqui - taqui@kth.se
GitHub: [Internet-Person-IP](https://github.com/Internet-Person-IP)

Carina - carinawi@kth.se
Github: [carinawic](https://github.com/carinawic)

Rezaul - mrhasa@kth.se 
Github: [MDRezaulHasan](https://github.com/MDRezaulHasan)

## Proposal

I want to create a presentation of the problems that occur when a small start-up might have to think about scaling their product for larger-scale usage. I want to pretend like I was the founder of Netflix (not set in stone) and talk about the decision I would make regarding the overall infrastructure of the application. I would discuss how to leverage the cloud to enable my little start-up to easily scale to the size of a Fortune 500 Company. Important will be to explain how each aspect relates to DevOps.

The topics that will be discussed in the presentation:

- Pretend like I am a startup wanting to create a great product
- Containerization
- Start talking about aspects of scaling
- Auto-scaling 
- Load Balancing
- Elasticity
- Disaster Recovery

### CODE REVIEW

**Comment by cesarsotovalero** [comment]
Hi @taqui Your presentation proposal is very in the scope of this DevOps course.
I can't wait to see it.
I'm merging your PR.

**Comment by Internet-Person-IP** [comment]
@cesarsotovalero just to be super clear currently I am only 1 person. The other Github account is my personal GitHub account. I will try and find someone who might be interested in this.

**Comment by monperrus** [comment]
thanks a lot @Internet-Person-IP for the presentation. We still have some free slots in week 2 (coming Tuesday), what about moving your presentation on week 2?

**Comment by Internet-Person-IP** [comment]
@monperrus Hello, thank you for asking us to present. Currently, we feel as we need more time to understand some of the cloud concepts in more detail and therefore we would prefer to present week 3.

**Comment by monperrus** [comment]
OK, that's fine. Thanks for your fast answer.

**Pull request merged**
