### PR TITLE
Tutorial proposal: Ansible for Jenkins and K8

### PR DESCRIPTION
**Pull request by sestys**
# Tutorial: *Configuration of CI/CD infrastructure with Ansible*

### Member
Matej Sestak (sestak@kth.se)
GitHub: [sestys](https://github.com/sestys)

### Proposal
The goal of this tutorial is to show how to set up Ansible to automate infrastructure for Jenkins, Docker, and Kubernetes for application deployment.
I have no prior experience with any of those tools and want to use this tutorial as a chance to dive into them.

The tutorial will be hosted on [Katacoda](https://www.katacoda.com).

### CODE REVIEW

**Review by cesarsotovalero — CHANGES_REQUESTED** [review]
Change the path of your `README.md`  to `contributions/executable-tutorial/sestak/README.md`

**Comment by sestys** [comment]
Moved, sorry about that.

**Review by cesarsotovalero — APPROVED** [review]

**Comment by cesarsotovalero** [comment]
LGTM. I'll merge!

**Comment by khesoem** [comment]
This proposal is modified in #1268

**Comment by Wizkas0** [comment]
I will give feedback for this task and my feedback PR id is https://github.com/KTH/devops-course/pull/1317

**Pull request merged**
