### PR TITLE
Revised submission for the grading: Demo

### PR DESCRIPTION
**Pull request by sujon2100**
-Updated link
-Updated content
-Updated Readme file

### CODE REVIEW

**Comment by SophieHYe** [comment]
Hi, there is a conflict. Please fix it and thanks!

**Comment by sujon2100** [comment]
> Hi, there is a conflict. Please fix it and thanks!

Hi, It's resolved now. Thanks!

**Comment by jvikstrom** [comment]
I'll give feedback here :)

**Comment by rbratfors** [comment]
Hello, I would like to give feedback to @sujon2100 and @adbjo.

**Comment by juliuscc** [comment]
I would like to give feedback

**Comment by adbjo** [comment]
Thank you @jvikstrom @rbratfors @juliuscc go ahead :)

**Comment by Kappenn** [comment]
I will give feedback

**Comment by rbratfors** [comment]
Overall I thought the demo was very clear and informative.

However, I feel like there's a lot of wasted space that could be cropped out. The screen resolution is way too wide and the download bar at the bottom serves little function.

Another improvement could be to add voice-over for increased accessibility and understanding. The demo is clear enough with just subtitles but voice-over just allows the viewer to focus more on the actual actions.

**Comment by jvikstrom** [comment]
First something completely unrelated to the demo, I really like the music: where did you find it?

One technique you can use to focus someones attention is to kind of dim the parts of the screen that are not useful at the moment (if you don't want to re-record the entire screencast). In the first minute it's kind of hard to know where to look so I feel like you could use this at some point(s) there.

At around 3:38 when the VM fails to deploy I'm not sure if it's supposed to be that way or not - it doesn't really feel like it fits in with the rest of the demo. I'd suggest just slicing that part out of the video. 

It'd be nice to have just a short sentence in the beginning what network peering is and why you want to use it. I mean I'm assuming you use it primarily for inter-Data-Center communication? But I have no idea where it's used.

The take-home message is a bit weird considering the subject, should probably tie it into actual network peering instead

Now don't get me wrong: I actually really like this demo, it's very dense and informative so it's nice you don't waste any time.

I really like how you integrated the subtitles, it looks absolutely great.

Finally, there are a couple of interesting papers on the virtual network in Azure:
[How they use FPGA to enforce SDN policies] (https://www.microsoft.com/en-us/research/uploads/prod/2018/03/Azure_SmartNIC_NSDI_2018.pdf)
[The actual switch platform](https://www.microsoft.com/en-us/research/wp-content/uploads/2017/03/vfp-nsdi-2017-final.pdf)

It's much more low-level and I'm in no way suggestion you use these as sources for the video, however they did some pretty cool things and might be worth a read anyways. So just thought I'd share them

**Comment by sujon2100** [comment]
> I'll give feedback here :)

Thanks!!

**Comment by sujon2100** [comment]
> Hello, I would like to give feedback to @sujon2100 and @adbjo.

Thanks!!

**Comment by Kappenn** [comment]
I think this demo is really clear and jumps stright at the point, good job!

As for my opinions of areas where you can improve:

First, although I'm not the targeted audience for this video, it would be nice with just a sentence or two to just explain roughly what you are doing.

Secondly, I think the pacing can be improved, sometime I just finished reading the subtitles, and don't have time to acctually see what happens on the screen. You could slow down some part of the video, alternatively a voice over would be a good complement for the video.

Finally, around 3:37 you get an error, I don't know if this is on purpose but it doesn't seem to fill any purpose. If that is the case, you can probably just remove it.

**Comment by sujon2100** [comment]
> I would like to give feedback

Thank you so much  @juliuscc !!

**Comment by sujon2100** [comment]
> I will give feedback

Thanks!!

**Comment by sujon2100** [comment]
> Overall I thought the demo was very clear and informative.
> 
> However, I feel like there's a lot of wasted space that could be cropped out. The screen resolution is way too wide and the download bar at the bottom serves little function.
> 
> Another improvement could be to add voice-over for increased accessibility and understanding. The demo is clear enough with just subtitles but voice-over just allows the viewer to focus more on the actual actions.

Thank you for your feedback!!

**Comment by sujon2100** [comment]
> First something completely unrelated to the demo, I really like the music: where did you find it?
> 
> One technique you can use to focus someones attention is to kind of dim the parts of the screen that are not useful at the moment (if you don't want to re-record the entire screencast). In the first minute it's kind of hard to know where to look so I feel like you could use this at some point(s) there.
> 
> At around 3:38 when the VM fails to deploy I'm not sure if it's supposed to be that way or not - it doesn't really feel like it fits in with the rest of the demo. I'd suggest just slicing that part out of the video.
> 
> It'd be nice to have just a short sentence in the beginning what network peering is and why you want to use it. I mean I'm assuming you use it primarily for inter-Data-Center communication? But I have no idea where it's used.
> 
> The take-home message is a bit weird considering the subject, should probably tie it into actual network peering instead
> 
> Now don't get me wrong: I actually really like this demo, it's very dense and informative so it's nice you don't waste any time.
> 
> I really like how you integrated the subtitles, it looks absolutely great.
> 
> Finally, there are a couple of interesting papers on the virtual network in Azure:
> [How they use FPGA to enforce SDN policies](https://www.microsoft.com/en-us/research/uploads/prod/2018/03/Azure_SmartNIC_NSDI_2018.pdf)
> [The actual switch platform](https://www.microsoft.com/en-us/research/wp-content/uploads/2017/03/vfp-nsdi-2017-final.pdf)
> 
> It's much more low-level and I'm in no way suggestion you use these as sources for the video, however they did some pretty cool things and might be worth a read anyways. So just thought I'd share them

Thanks for your feedback!

As you mentioned why we kept the VM error? The answer is as it could be encounter by others and they can see the solution that we have given there. It was nothing major error related to deployment, just a rule for naming length.

**Comment by sujon2100** [comment]
> I think this demo is really clear and jumps stright at the point, good job!
> 
> As for my opinions of areas where you can improve:
> 
> First, although I'm not the targeted audience for this video, it would be nice with just a sentence or two to just explain roughly what you are doing.
> 
> Secondly, I think the pacing can be improved, sometime I just finished reading the subtitles, and don't have time to acctually see what happens on the screen. You could slow down some part of the video, alternatively a voice over would be a good complement for the video.
> 
> Finally, around 3:37 you get an error, I don't know if this is on purpose but it doesn't seem to fill any purpose. If that is the case, you can probably just remove it.

Thank you for your appreciation!!

Here are some answers related to your questions:
In the second part of the comments, you talked about slow down the video. Actually creating and deploying Virtual network, peering and VM, it takes at least 30 to 40 minutes depending on Microsoft's global network traffic. To present it under 5 minutes a great challenge. But we tried our best to slice it down and made it in 5 minutes.

As you mentioned why we kept the VM error? The answer is as it could be encounter by others and they can see the solution that we have given there. It was nothing major error related to deployment, just a rule for naming length.

**Comment by nagavem** [comment]
Hi, a little late but I would like to give feedback

**Comment by juliuscc** [comment]
Firstly I did not understand what the demo was about. I think the demo could be vastly improved by a diagram of the architecture that you want to achieve. You could spend a couple of seconds discussing what you want to do, and the benefits of it. Something like this:

Untitled drawing

There was a lot of manual typing, and it would be interesting if the process was automated, and your demo showed how it is automated. Otherwise, you could demo the actual benefits of this by showing two applications that send secrets to each other. I don't think it is very interesting to show a lot of manual config, and I think the demo could be improved by showing something more novel or interesting.

**Comment by juliuscc** [comment]
I think the topic is very interesting and novel. I like that it is about Azure, instead of AWS or GCP. It is a very unique approach to discuss explicit secure channels between VMs.

**Comment by sujon2100** [comment]
> Firstly I did not understand what the demo was about. I think the demo could be vastly improved by a diagram of the architecture that you want to achieve. You could spend a couple of seconds discussing what you want to do, and the benefits of it. Something like this:
> 
> Untitled drawing
> 
> There was a lot of manual typing, and it would be interesting if the process was automated, and your demo showed how it is automated. Otherwise, you could demo the actual benefits of this by showing two applications that send secrets to each other. I don't think it is very interesting to show a lot of manual config, and I think the demo could be improved by showing something more novel or interesting.

@juliuscc Thanks a lot for your great feedback! If it's ok with you, can we use this diagram?:)

**Comment by sujon2100** [comment]
> I think the topic is very interesting and novel. I like that it is about Azure, instead of AWS or GCP. It is a very unique approach to discuss explicit secure channels between VMs.

@juliuscc Thanks a lot for your appreciation!

**Comment by juliuscc** [comment]
> @juliuscc Thanks a lot for your great feedback! If it's ok with you, can we use this diagram?:)

Sure :)

**Comment by sujon2100** [comment]
Thank you @rbratfors, @rbratfors, @jvikstrom, @Kappenn, @juliuscc for the great feedback. Based on the feedback, we have changed on the following changes:

- The infrastructure is created with Terraform instead of in the Azure Portal, showing how infrastructure deployment can be automated (more novel and interesting).
- Accompanying GitHub repository created for the Terraform code.
- Screen resolution fixed.
- Music credits embedded in the video end-screen.
- Failed VM creation removed.
- Introductory slide added with network diagram of the created infrastructure.
- Easter egg at 4:20


Latest screencast: https://youtu.be/WPZPVX2ptF0

**Comment by juliuscc** [comment]
The improvements are very significant! Cool video!

**Comment by sujon2100** [comment]
> The improvements are very significant! Cool video!

Thank you @juliuscc!

**Pull request merged**
