### PR TITLE
Finished demo: GitLab CI/CD pipeline (Building, Testing, deployment to Heroku)

### PR DESCRIPTION
**Pull request by christinasunnegardh**
Copy of addition to README:

## Demo for Demo Day

Here is the link to my demo for the demo day: https://www.youtube.com/watch?v=5IkDrgFSFw4&t=7s The accompanying GitLab repository: https://gitlab.com/christinasunnegardh/devops-gitlab-demo

### CODE REVIEW

**Comment by jonasjohansson8908** [comment]
I will give feedback on this demo

**Comment by Pontus-Broberg** [comment]
I would like to give feedback to this! :)

**Comment by MindaugasVarkalys** [comment]
I would like to give feedback to this

**Comment by Zodbigt** [comment]
I will give feedback on this one

**Comment by jonasjohansson8908** [comment]
This is a very good demo!
I liked that you had a voice-over. That really made it easier to follow the steps shown in the demo. The demo also looks nice, I can see that you've spent time on editing the video.

The demo is 1 second too long. I'd imagine that the time limit is strict, you should consider shortening the video to be sure.

I found the part with the transparent screen ~4:45 to be a bit confusing. It was a bit unclear where I should pay attention. To the text in front, the audio, or the webpage shown in the background.

The take-home message at the end is good but could be a bit more explicit to sum up the demo.

Also, you probably should write a readme for the repository.

Good job!

**Comment by Pontus-Broberg** [comment]
I love this demo!
It is very good, easy to follow and I as a viewer understood everything that you did.

It is really nice that you had a voice-over, especially for someone like me that can't read very fast. However, at 1:46 and 3:06 you add another textbox to the side that contains quite a lot of text. Reading this while listening to the voice-over is quite confusing and hard, and I myself had to pause the video to not miss anything. I understand you do not want to remove those boxes altogether, but maybe consider also reading those text boxes with the voice-over or make them smaller, so they seem a bit more non-important because right now, the big boxes with the big "i" symbol make it seem like it is something I don't want to miss.

Other than that, maybe find somewhere to shave off 1 second of the video? I know it is only one second but you never know how the TAs treat that hard limit of 3-5 minutes...

Overall, great video! Good job!

**Comment by Zodbigt** [comment]
Thanks for the demo!
I like the upbeat music in it. Makes me excited/ready to continue listening to it.
You talk loud and clearly. It is well edited. For example good transitions and zooming in when you show something.

The subtitle at one point is obscuring the blue note, so it is not possible to read. Around 4 min 18 seconds. It is possible to read by pausing the video at the right moment.

Super minor thing. The video link starts at 7 seconds. 

Good job.

**Comment by matsskoglund** [comment]
The demonstration is clearly motivated to show how to use Gitlab together with Heruku
I did not try the demo but, the screencast was very good
The demonstration was perhaps not original but was very good in showing the core concepts
The screencast was very sublime and very easy to follow, nothing unneccessary
The easter egg was there, even though having tests are perhaps not so much of an easter egg

I would say that the demonstration does not trigger a conversation but it is actually a good thing in this case. 
It was a very clear getting started guide and if you dont have any questions it fitted it purpose percetly.

A screencast was made and it was a must in this case since there were no other documentation.
The screencast was remarkable good as a getting started guide. We at Scania would very much like to have more people that can create such good getting started guides.

Small comments.
Avoid using "latest" for image versions since that can cause your CI/CD pipeline to fail in the future 
or bring in vulnarabilities if the images change. Better to specify a version and actively change the version.

Avoid leaving a CI/CD pipeline in a failed state. Always try to have green lights. 
Failed pipelines should trigger some action to fix the issue.

Very good!

**Comment by MindaugasVarkalys** [comment]
It's very nice and detailed demo. I really liked that you showed all the steps in detail and explained every line in your `gitlab-ci.yml`. The visuals were perfect and you clearly motivated why it matter for DevOps. Your speech was clear and easy to understand. It's nice that you added Github repository and other external links, so the viewer can read more about the technologies and services you use. I didn't notice any Easter eggs, but maybe I just missed it. One small thing I don't understand is why you have to install Ruby on Ruby Docker image, but overall it's really great demo. Good job!

**Comment by christinasunnegardh** [comment]
Hi everyone (@jonasjohansson8908, @Pontus-Broberg, @Zodbigt, @matsskoglund, @MindaugasVarkalys)!

Thank you so much for all the feedback - it was very useful!

**Based on your advice I have updated the following in the demo:**
- Added a description to the README at the accompanying GitLab repository
- Fixed minor issues with the subtitles
- Removed the "prerequisites" part in the screencase and updated the description with this information instead
- Removed the unnessecary action in the screencast where ruby is installed altought we are already on a Ruby Docker image.
- Added information about that you can specify a specific version of the image in docker
- Changed the easter egg completely
- Major changes to the end/take-away part in the screencast
    - Relate to DevOps again, what happens when the pipeline fails etc.
    - Hint about where to fid the easter egg
- Made updates to the description on Youtube.


Thank you once again, all the feedback was very appreciated!

**Pull request merged**
