### PR TITLE
CI tools in the context of business

### PR DESCRIPTION
**Pull request by isachaglund**
@khaes-kth Please check asap :)

### CODE REVIEW

**Comment by khesoem** [comment]
Can you send a link to your proposal here?

**Comment by khesoem** [comment]
I mean your proposal pull request

**Comment by isachaglund** [comment]
This is a screen shot of your approval. When you helped me on the lab session i believe we deleted my fork and therefore the PR? because i cant find it now.

**Comment by isachaglund** [comment]
its pr#2005

**Comment by khesoem** [comment]
Hi @isachaglund 

I just talked to Benoit. He told me that we can accept your task submission, even though you have officially submitted it after the deadline. However, you will not have a chance for repeat.

So, if you want to improve your essay before grading, please let me know here and apply your changes before May 31. If you want this version to be considered as the final one, please let me know.

**Comment by isachaglund** [comment]
Hi, 

I was obviously handing it in by email before deadline on may 23rd 15:11. Why would that take a way my chance for repeat? 

Regards,

Isac Haglund

**Comment by khesoem** [comment]
Hi,

You can discuss this with Benoit. But I'm sure if you try your best, you'll pass the task and a repeat won't even be needed.

Best,

**Comment by isachaglund** [comment]
Hi,

I have now made my final changes and uploaded the pdf to my forked repository. Once again i am having problems with merging with the main repository.

Here you can see it.
https://github.com/isachaglund/devops-course/tree/2022/contributions/essay/isacha

also the file here directly
***@***.***


How do I proceed?

Best regards,
Isac Haglund


On 24 May 2022, at 15:04, Khashayar Etemadi ***@***.******@***.***>> wrote:



Hi @isachaglund<https://github.com/isachaglund>

I just talked to Benoit. He told me that we can accept your task submission, even though you have officially submitted it after the deadline. However, you will not have a chance for repeat.

So, if you want to improve your essay before grading, please let me know here and apply your changes before May 31. If you want this version to be considered as the final one, please let me know.

**Comment by khesoem** [comment]
Hi @isachaglund 

Thanks for making the changes. What is your problem with creating a pull request?

An easy way to create a new PR: save your essay somewhere to make sure you do not lose it. Deleted your forked repository. Refork the devops repository. Clone your fork. Replace your old essay in the cloned repo with the new version. Update the readme and mention the changes. Create a PR. You should not face any issues if you follow these steps.

Please create the revision PR as soon as possible. We have to finish the grading soon.

Best,

**Comment by isachaglund** [comment]
hey! 

Thank you for your assistance. I have created a PR, however it fails on the wordcount it says? It shoudl not be a problem i have 2476 words in total. Is there an other issue? 



https://github.com/KTH/devops-course/pull/2054 <https://github.com/KTH/devops-course/pull/2054>


Regards, 

Isac

**Comment by khesoem** [comment]
Hey!

Sorry for the late reply. I just saw this.

Is your problem solved? If not, can you send a link to your PR?

**Pull request merged**
