### PR TITLE
Final Submission - Course Automation: Checking Open-Source Requirements

### PR DESCRIPTION
**Pull request by oskstr**
# Course Automation: Checking Open-Source Requirements

## Members
- [Oskar Strömberg](https://github.com/oskstr) (oskstr@kth.se)
- [Sebastian Williams](https://github.com/sfkwww) (swill@kth.se)

## Proposal

We would like to create a GitHub action that would automatically check the requirements for an open-souce contribution.

The action should check that repo has:
- More than 10 stars
- More than 100 commits
- An active community
  - open to interpretation
  - provide stats on what has happened the last year (comments, PRs, commits)

We believe that checking that a project is related to DevOps may be too difficult for the purposes of this project.

## Final Submission
We have created a GitHub action at: https://github.com/sfkwww/milkyway

The action can be used to find a link to an open-source GitHub repository in a body of text, like a pull request, and 
get the following stats:
 - stars
 - watchers
 - contributors
 - forks
 - commits
 - commits last year
 - open issues
 
 The action can test that those stats satisfy some minimum requirement, e.g. 10 stars and 100 commits.
 
 With this pull request we have added a file at `.github/workflows/open-source-requirement.yml` that 
 would run this action whenever a pull request to `2021` gets the label `contribution_to_opensource`.
 
 The minimum requirements currently in place are:
 - stars: 10
 - watchers: 10
 - contributors: 10
 - forks: 1
 - commits: 100
 - commits last year: 10
 - open issues: 10
 
 If needed they can be changed or removed. The default requirement is 0. 
 
 The current workflow also uses `github-script` to comment a table of stats on the pull request.

An example would be:

>  [ rust-lang/rust ]
>  -----------------------
>  | Stat  |  Number |  Pass | 
>  |---|---|---|
>  |Stars ⭐              | 53440             | ✔️   |
>  |Commits 📦            | 141152           | ✔️ |
>  |Commits Last Year ⏱️  | 14472 | ✔️ |
>  |Watchers 👀           | 1489          | ✔️ |
>  |Contributors 🧑🏻‍🤝‍🧑🏻       | 4135      | ✔️ |
>  |Forks 🍴               | 7696             | ✔️ |
>  |Open Issues 🟢        | 7056       | ✔️ |

### Update according to change in grading criteria
In a proposed update [#1209](https://github.com/KTH/devops-course/pull/1209) to the grading criteria for this task there are two additional requirements.

1. Implemented in stand-alone repository (already done, no issue here)
2. Demonstrate that automation technique actually works, for example in fork of [KTH/devops-course](https://github.com/KTH/devops-course) (we have tested but haven't provided a link)

Here is a link to the Pull Request where we did our testing: [sfkwww/milkyway#2](https://github.com/sfkwww/milkyway/pull/2).

Here is a link to the actions invoked during said testing: [sfkwww/milkyway/actions](https://github.com/sfkwww/milkyway/actions).

### CODE REVIEW

**Comment by oskstr** [comment]
@cesarsotovalero I don't know if you are the correct person to ping about this. We opened this pull request two weeks ago (a week before the deadline). You were the one who merged the proposal. Do we need to fix anything to get this merged?

**Comment by oskstr** [comment]
I noticed that there is an open PR to clarify grading for this task at #1209 from @khaes-kth . 

While we already have provided a link to our separate repo, we haven't provided a link to prove that it does what we say it does. Here is the link to the PR we did tests on https://github.com/sfkwww/milkyway/pull/2 .

Is that sufficient? Our action doesn't expect a certain file structure or anything, it just looks at the PR body iff it has the [contribution_to_opensource](https://github.com/KTH/devops-course/labels/contribution_to_opensource) label.

**Comment by khesoem** [comment]
> While we already have provided a link to our separate repo, we haven't provided a link to prove that it does what we say it does. Here is the link to the PR we did tests on [sfkwww/milkyway#2](https://github.com/sfkwww/milkyway/pull/2) .

Please add this information in your readme.

> Is that sufficient?
We will see when we grade your work. After a quick glance, I believe you have done a decent job.

**Comment by oskstr** [comment]
@khaes-kth , sure I could add that to the README. Will probably be in a couple of hours though, working on the demo atm.

What I meant by _"Is that sufficient?"_ was just referring to the link to our test PR and to point 2 in the proposed change to the grading criteria (showing that it works, for example with a fork of this repo). I understand that some course automations might refer to the folder structure of this repo and for those it would probably be good to test with a fork specifically.

**Comment by oskstr** [comment]
@khaes-kth , sorry about the long wait but I have now updated the README and PR comment according to your comment above.

**Comment by khesoem** [comment]
Hi @oskstr,

I accidentally merged your PR but it should not be merged yet. I reverted it. Please submit a new PR without adding the `.github/workflows/open-source-requirement.yml` file. We do not want to make changes in our workflow for now.

**Comment by oskstr** [comment]
Ok, @khaes-kth . I have opened a new PR #1299 with the additional commit of 7ec00f5 which removes that file. It was my understanding that this task was more urgent to be of any use during the course.

**Comment by khesoem** [comment]
> I have opened a new PR #1299 with the additional commit of [7ec00f5](https://github.com/KTH/devops-course/commit/7ec00f57c30e65c5e101ecdb10ee2be6dde594a3) which removes that file.

Awesome! I merged that one.

**Pull request merged**
