### PR TITLE
Feedback Proposal for Eassy #1165

### PR DESCRIPTION
**Pull request by Renugaa**

### CODE REVIEW

**Comment by Renugaa** [comment]
Hi,

Sorry. I have mistakenly merged both the branches in my repo and that's why we see all the previous commits on this PR. Please ignore them. 

Thanks,
Renu

**Comment by khesoem** [comment]
Hello @Renugaa 

I think `contributions/presentation/week3/renanb-gangwal/README.md` does not exist [in the repo](https://github.com/KTH/devops-course/tree/2021/contributions/presentation/week3). Please remove the `contributions/presentation/week3/renanb-gangwal/` folder and push your.

Also, note that #1165 has not be merged yet. You have to wait until it is merged and mention me again.

**Comment by Renugaa** [comment]
Hi Khaes,

It looks like the Essay #1165 is dropped. So, I will pick a new topic for my feedback.

Thanks,
Renu

**Comment by khesoem** [comment]
Fine. So, I'll close this PR and wait for your new proposal. Please let me know if you had a different plan in mind.

**Pull request closed without merging**
