### PR TITLE
Feedback proposal

### PR DESCRIPTION
**Pull request by kthfre**
# Assignment Proposal

## Title

Feedback for the executable tutorial "Infrastructure as Code with Pulumi".

## Names and KTH ID

- Fredrik Gölman (golman@kth.se)
- Chandni Narottambhai Rakhashiya (cnra@kth.se)

## Deadline

- Task 3

## Category

- Feedback

## Description

Feedback for [this executable tutorial](https://github.com/KTH/devops-course/tree/2024/contributions/executable-tutorial/mqnguyen) by mqnguyen@kth.se.

I've received approval from the author to leave feedback on this assignment. Am I making the correct assumption that the deadline for such feedback would be "Task 3" + 48h?

This feedback assignment has been [submitted](https://github.com/KTH/devops-course/pull/2540#issuecomment-2419590447).

### CODE REVIEW

**Comment by sofiabobadilla** [comment]
@kthfre 
"Task 3" + 48h" , yes :)

Still, please find a partner to deliver the feedback.

**Comment by kthfre** [comment]
@sofiabobadilla I've emailed all 3 recent students in the "looking for teammates" issue that are looking to do feedback, and will keep an eye on anyone else replying there. If I can't find anyone, will I have the go ahead to do it alone (the rules said you could do max 2 alone at the start of the course)?

**Comment by kthfre** [comment]
@sofiabobadilla Found a partner for this assignment, so I guess we are all set.

**Comment by kthfre** [comment]
@sofiabobadilla @algomaster99 This assignment has been submitted.

**Comment by algomaster99** [comment]
@kthfre great tutorial. I was not able to find the easter egg. I had a hunch that it would be after "Don't click me" button. But I am unable to connect now even after "restart session and run all".

It keeps throwing:
image

**Comment by kthfre** [comment]
@algomaster99 you may be on the right path, perhaps click it the odd more time. :) The server had crashed, I restarted it now. (we're in the wrong PR)

**Comment by algomaster99** [comment]
Sorry for the wrong PR. I managed to complete it now 😊

Guess I will have eggs :D


Regards,
Aman Sharma

PhD Student
KTH Royal Institute of Technology
School of Electrical Engineering and Computer Science (EECS)
Department of Theoretical Computer Science (TCS)
<http://www.kth.se><https://www.kth.se/profile/amansha><https://www.kth.se/profile/amansha>
<https://www.kth.se/profile/amansha>https://algomaster99.github.io/
________________________________

**Pull request merged**
