### PR TITLE
Essay : Role of DevOps in minimizing downtime on applications using Continuous deployment

### PR DESCRIPTION
**Pull request by Renugaa**

### CODE REVIEW

**Comment by SophieHYe** [comment]
Your proposal of the essay is good. However, I would like to ask you for the following changes:

(1) Please be noted that your folder name is not your kth email. Please update Renu-Yuxin ->    renanb-yuxinm.

(2) Also one PR per task. Please remove the changes on presentation in this PR.

Thanks.

**Comment by Renugaa** [comment]
Hi Sophie,

I made the changes as suggested. Please review it and let me know if it's as expected. 

Thanks!

**Comment by SophieHYe** [comment]
I have removed your existing duplicated presentation proposal. Now the essay proposal can be merged.

**Comment by oscaralmqvist** [comment]
I will give feedback for this task and my feedback PR id is #1151.

**Comment by oscaralmqvist** [comment]
Hey, did you manage to publish your essay? I couldn't figure out if it was on another branch or not published yet.  😀

**Comment by Renugaa** [comment]
Hej @oscaralmqvist,

We published our essay just now and it is ready for feedback, #1316 this is our PR. 

//Renu and Yuxin

**Comment by oscaralmqvist** [comment]
Great, I'll take a look 👍

**Pull request merged**
