### PR TITLE
Executable tutorial proposal

### PR DESCRIPTION
**Pull request by dannolaius**
# Assignment Proposal

## Title

Creating a Robust Gatsby Web Service with Automated Testing and Deployment on GitHub

## Names and KTH ID

  - Robin Eggestig (eggestig@kth.se)
  - Daniel Lai Wikström (daniellw@kth.se)

## Deadline

- Task 3

## Category
- Executable tutorial

## Description

This comprehensive hands-on tutorial provides detailed, step-by-step instructions for setting up a Gatsby application, integrating automated testing, and deploying it using GitHub Actions and GitHub Pages. Discover how to harness Gatsby’s powerful capabilities for fast data fetching and static site generation, leading to a fully functional web service hosted on GitHub Pages, complete with automated tests to ensure reliability and performance.

The tutorial also covers the integration of automated unit and integration tests, the configuration of CI/CD workflows using GitHub Actions, and managing version control with Git. We plan to use personal access token (PAT) with permissions for a new repository for full hands on learning. Designed for developers of all skill levels, this tutorial empowers participants to gain practical experience with Gatsby and modern deployment strategies.

**Relevance**
In today’s fast-paced software development landscape, the demand for efficient and reliable web applications is higher than ever. This tutorial is particularly relevant as it provides an executable format that helps developers learn about Gatsby and GitHub Actions while equipping them with essential skills for implementing automated testing and deployment.

As organizations increasingly adopt DevOps practices and agile methodologies, the ability to quickly create and deploy robust web services becomes essential. This practical resource effectively bridges the gap between theory and practice, empowering participants to adopt modern development practices in their own projects.

Our tutorial: https://killercoda.com/daniellw/scenario/gatsby-tutorial
Github for tutorial: https://github.com/dannolaius/coda-tutorial

### CODE REVIEW

**Comment by eggestig** [comment]
On further research, rendering a static page with github pages using remix is a bit counterproductive as it requires too many changes to be applicable for a non-static project. Especially considering remix's whole niece is server-side rendering and hydration. Instead we're opting for a framework that is static in nature, Gatsby.

**Comment by dannolaius** [comment]
We see the proposal still hasn't been looked at but we made a tutorial that i added to the README now.

**Comment by sofiabobadilla** [comment]
Hi @dannolaius ,
I'll merge the PR as proposal, please open a new one as submission!
Thanks

**Comment by dannolaius** [comment]
@sofiabobadilla Created a submission. Since this one already had the links in the README I just moved them around a bit, hope that's works! https://github.com/KTH/devops-course/pull/2680

**Pull request merged**
