### PR TITLE
Course automation proposal : Automatic weekly recap mail

### PR DESCRIPTION
**Pull request by paulinev-kth**
## Title

Automatic weekly recap mail
# Names and KTH ID
- Pauline Vaillant ([paulinev@kth.se](mailto:paulinev@kth.se))

# Deadline
Task 2
# Category
Course automation
# Description
I would create a github action that send a weekly mail that would send a mail with
- plan for the next week (arcticles to read according to the readme), when and where are the lectures
- task done, and next task deadline (for example if the student has done 0 task, it would be the deadline for task 1, if it has aldready done 1 task, it would be the date for deadline 2)

### CODE REVIEW

**Comment by paulinev-kth** [comment]
I have started to work on the task to be able to keep up with the deadlines
Would it be possible to have a feedback ?

**Comment by javierron** [comment]
Hello @paulinev-kth, thanks for the proposal. This seems indeed useful. 

I have just one question: How are you planning to find out if the student has done a task? (not only registered)

Otherwise the proposal makes a lot of sense, just make sure that you don't spam the kth emails while testing your action,

**Comment by paulinev-kth** [comment]
I'm planning to use Canvas API, I don't know how it works yet for the authentication 
Is there not a PR that add automatically the grades ?  I was planning to take inspiration from it

**Comment by javierron** [comment]
@paulinev-kth I see. However, since submissions are not done through Canvas, this information cannot be pulled from there.

I suggest that you focus on tracking proposals: e.g. what deadlines, task types, weekly topics for demo/presentation are still available for each student. There is also information in the repo about teammates, e.g. the "[teammate finder](https://github.com/KTH/devops-course/issues/1166)" issue.

Canvas integration sounds also really nice, but all information there is actually pulled from this repository. This means that any information that you could pull from Canvas, you could also pull from here.

**Comment by paulinev-kth** [comment]
@javierron 
Actually I am planning to find the number of task done by using the issue https://github.com/KTH/devops-course/issues/1607  (Statistics of Student Registrations). 
I will use github api to find issues with the name "Statistics of Student Registrations" inside the title and use the one with the correct year, and then I will analyze the text using the fact that it should be the same format every year. 
My current issue is more for students with no task yet I don't know how to find their canvas id

**Comment by javierron** [comment]
@paulinev-kth that is a great idea. 

> My current issue is more for students with no task yet I don't know how to find their canvas id

I see, there is no way to find students who have not submitted at least one task from the repo. I believe you could pull all kth ids from canvas API, then you would have to filter to only target students, I'm not sure if all this data is available to you as a student of the course. If this information is not available to you, you can ignore students that have not submitted at least one task.

**Comment by javierron** [comment]
@paulinev-kth Please update the readme file considering the discussion points, and I will merge it. Looking forward to see your work!

**Comment by paulinev-kth** [comment]
@javierron Once this branch is merged, is it okay for the deadline or do I have to finish my task by tuesay ?

**Comment by javierron** [comment]
@paulinev-kth Your proposal states that you target deadline for task 2, which is Tuesday April 19th at 17:00h. You are free to change the deadline to the one that suits you best. Remember that you can only present one task per deadline, except for demos and presentations which have their own deadlines on the day of the scheduled lecture.

**Comment by paulinev-kth** [comment]
I will finish it by Tuesday then

**Pull request merged**
