### PR TITLE
Course Automation: Checks Demo Link

### PR DESCRIPTION
**Pull request by heeenkie**
More information in the readme

### CODE REVIEW

**Comment by khesoem** [comment]
Hi,
I think your proposal is in the scope. However, I am not sure if it is complicated enough. Could you add some more features?

**Comment by cesarsotovalero** [comment]
@heeenkie Checking the validity of links was already proposed. So this PR is duplicated. See https://github.com/KTH/devops-course/blob/2021/contributions/course-automation/zidi-sihan/README.md

**Comment by khesoem** [comment]
@heeenkie Sorry, but the PR that @cesarsotovalero mentioned was merged. So, we have to close your PR and wait for your new proposal.

**Comment by heeenkie** [comment]
@cesarsotovalero @khaes-kth 
Hi, The merged PR was to check link validity in all PR, I wanted to check if a link existed for 'DEMO' PR och set the status of the PR depending on the existence of the link.

Is this still a rejection?

**Comment by cesarsotovalero** [comment]
> Is this still a rejection? 

Yes, it is almost the same action.

**Pull request closed without merging**
