### PR TITLE
Essay Submission: Testing Micro Services: Challenges, Types and NodeJS Solutions

### PR DESCRIPTION
**Pull request by Abdullah1428**
# Assignment Proposal

## Title

Testing Micro Services: Challenges, Types and NodeJS Solutions

## Names and KTH ID
  - Chrysoula Dikonimaki (cdik@kth.se)
  - Abdullah Abdullah (aabdull@kth.se)

## Deadline

Task 4

## Category

Essay

## Description

Testing of Microservices Architecture is one of the trending topic in DevOps and in this essay we want
to target the different types of testing that can be done within the microservices architecture, the challenges 
of implementing those tests and then also present some tools and frameworks that are the industry standard followed to
solve those challenges in related to NodeJS specifically.

(Edit: PDF for Essay is in the directory contributions/essay/cdik-aabdull)

### CODE REVIEW

**Comment by aykhazanchi** [comment]
Hi @Abdullah1428, is it okay if @Akseluhr and I give feedback on this essay? Thanks

**Comment by Abdullah1428** [comment]
Hi @aykhazanchi thank you for the request and yeah go ahead for the feedback, looking forward to it. May not have enough time to add the feedback due to other course works but will look into it.

**Comment by xrisaD** [comment]
Hi @javierron, I've noticed that while we have submitted the essay on time, the pr is still not merged

**Comment by xrisaD** [comment]
Hi @khaes-kth, why is the PR open? we submitted the essay on time

**Comment by khesoem** [comment]
Hi @xrisaD 
I thought I should give you a little more time to improve your work based on the feedback. I'm gonna merge it now.

**Comment by aykhazanchi** [comment]
## Feedback on Chrysoula Dikonimaki and Abdullah Abdullah’s essay: Testing Microservices, Challenges, Types and NodeJS Solutions

### Feedback by Aksel Uhr ([auhr@kth.se](mailto:auhr@kth.se)) and Ayushman Khazanchi ([ayushman@kth.se](mailto:ayushman@kth.se))

*Note*: we understand it may be hard to implement a lot of this as we tried to be quite detailed about it. Overall we find it a very well-written essay and we have tried to offer ways in which we feel it can be strengthened. 

### High-Level Strengths

1.	A lot of different micro service testing concepts. Perfect essay for a comprehensive overview. 
2.	Good and understandable explanations of those various concepts
3.	Many (scientific) references which indicate that you have done a good amount of research.
4.	Ambitious essay and very interesting and relevant (to DevOps and software engineering) topic.
5.	Problem is clearly stated, and overview is given for each field of interest
6.	Overall, a good structure
7.	The title encapsulates the entire essay in a good way.
8.	We learned a lot!

### High-Level Weaknesses

1.	Structure (especially headings / sections) could be done differently. Some content could have been better arranged for increased readability (details below)
2.	Consider the relevance / incorporation of section 4.1. Testing techniques. (details below)
3.	The flow of reading sometimes suffers a little bit due to the preceding section not being entirely related to the successor. Try to incorporate a read through of your text.
4.	Try to eliminate opinions / proverbs (e.g., “hand down”) and avoid the term “we” for a more academic finish.
5.	Some minor but frequent spelling errors in introduction. Proof-read the essay multiple times.

### Introduction

The introduction is well written. The authors start by describing and contextualizing SOA and micro services on a holistic level and proceed to narrow it down, leading the reader to the scope of the essay regarding testing microservices. We think this section could be improved by clearly stating the goal / purpose of the essay and any limitations, which is common in 3.4. academic papers and therefore a good practice for the master thesis. An example could be “The purpose of this paper is therefore to… and we will focus on the javascript library NodeJs.” Conclusively, it will be clearer for the reader what you are trying to achieve with the essay.

### Monolithic to Microservices

This section is interesting as it compares the traditional architecture with micro services. The advantages of microservices are clearly described and we feel like any MSc student in computer science would have no problem understanding it. Nice job. However, we feel like this section could be incorporated in section 3 for the sake of readability and better essay structure.

On its own, it does give a good overview of two major architecture patterns. Maybe it could be expanded upon in this section how these are beneficial in the case of microservices and how they pertain to testing in NodeJS specifically. Some more context could have been provided as to where the division of code rests in microservices. For example, how do microservices handle dependency on other services, etc. It can be argued that this is not within the scope of the essay but we feel a few points could have strengthened this section.


### Microservices Testing Challenges

We feel the introduction portion on the challenges of designing with microservices architecture could have been better suited to the previous architecture section. The “Pyramid to Honeycomb” section dives right into the two models of testing but does not explain what the tests themselves imply. For example, it is stated that “having many small unit tests for each service is not necessary and it restricts how the code changes” but it is not explained why this could not also be a drawback of larger, more connected tests like integration testing where even more code or functionality is interdependent and thus resistant to change. I think more emphasis here could be placed on the frameworks themselves with strong, hard examples of where they’re applied. 

Additionally, this section needs to focus a bit more on the challenges to testing microservices. You introduce one interesting solution but don’t state whether this is commonly practiced in the industry, which I think the reader would appreciate. Perhaps there are any paper or article that states whether Honeycomb is industry practice for testing micro services?

### Testing Techniques

Very interesting section on Test doubles, stubs, and mocks. More insight can be provided to strengthen this section in the form of what kind of mock data or mock APIs are created and whether these methods support different forms of data apart from just objects. 

Additionally, this section feels very short and disconnected from its preceding section. It is also a bit unclear to us what the difference is between Testing Techniques and Testing Types as to me they sound very similar and could be joined into the same sub-section. Section 4.1 is relevant to testing since it describes two testing techniques. It might be clearer if you could contextualize the techniques in their relevance to microservices. 

### Testing Types

Under Unit Testing it is not clear what sociable and solitary mean on a deeper level. Some more detail can be provided on what is meant by “domain logic” as described for sociable tests.
Very clear and well-described section on integration tests. The last paragraph especially makes it much clearer how integration tests are different from sociable tests. Well done.

Very well described section on Contract Testing. Compact and to the point while also being technical enough to explain the implementation details. Good job.

This has been our favourite section of the essay. You describe typical test practices and relate them to microservices, as well as argue why they are important. It is clearly written. Great job.

One way it can be strengthened is to connect these test types to the Testing Hierarchy described in the Challenges section as it provides some additional context to the information. For example, you could refer to this resource with some more relevant history and context to different types of testing: https://martinfowler.com/articles/2021-test-shapes.html

### Solutions for NodeJS Microservices Testing

The section does not provide an entire understanding of each framework, but we doubt that’s the purpose of the section. It gives a brief overview and for anyone interested you can read more about it on your own.

This section on its own is well written but deviates a bit from the flow of the essay. It is lacking a bit in context on why these libraries are specifically relevant to NodeJS. For example, are these libraries only for NodeJS or are there some features that they provide that can only be used in NodeJS? It is a bit unclear what’s specific about these tools in respect to NodeJS. Apart from that missing link the information about the tools itself is very well researched and shows clearly that authors have the knowledge. The tools are relevant and SOTA and it’s appreciated that some key features of each library are also mentioned. 

Overall, we think this section could have been combined with the Testing Types section to create better readability. This section references terms used in Testing Types quite a lot so it would go better if these sections were combined and then split within sub-headings where each tool could then be mentioned.

### Conclusion

The conclusion is good and wraps up the essay with a timely and relevant message regarding the rise of microservices-based architecture and therefore the importance of increased and better testing practices around it.

### Additional Resources
-	The Best Unit Testing Frameworks for NodeJS, https://blog.logrocket.com/the-best-unit-testing-frameworks-for-node-js/
-	Popular Testing Libraries, https://www.raftlabs.co/development/popular-testing-libraries
-	Shift-Right Testing, https://techbeacon.com/app-dev-testing/shift-right-test-microservices-wild-tame-devops
-	Efficiently Testing Pipelined Microservices, https://blog.shiftleft.io/efficiently-testing-pipelined-microservices-fa219b75e0a9
-	Testing Microservices: Examining the Tradeoffs of Twelve Techniques - Part 2, https://www.infoq.com/articles/twelve-testing-techniques-microservices-tradeoffs/

**Comment by Abdullah1428** [comment]
@aykhazanchi and @Akseluhr thank you for this detail feedback on our essay.

**Pull request merged**
