### PR TITLE
Essay: Comparison of Kubernetes and Nomad

### PR DESCRIPTION
**Pull request by dmariel**
# Essay: Comparison of Kubernetes and Nomad
 
## Members
- [Dina Lerjevik](https://github.com/dmariel) (lerjevik@kth.se)
- [Patricia Naccachian](https://github.com/patricia-naccachian) (nacca@kth.se)

## Proposal
We would like to write an essay in which we describe orchestration and compare two commonly used tools: Kubernetes and Nomad.
 
We aim to fulfill the following criteria:

* Format: The essay is in PDF
* Title: The essay has a good title
* Well-structured: The essay is well structured, the ideas are well presented
* Introduction: The essay contains a good introduction
* Conclusion: The essay contains a good conclusion
* Self-contained: The essay is self-contained, one can understand it without reading something else (expected knowledge of the reader: a master student in computer science)
* Figures: The essay contains good figures or listings
* Sound: The essay is sound, factual, and accurate 
* References: The essay contains references, appropriate  in number and quality (10 good refs is a minimum)
* Elegant: The essay presentation is elegant / visually appealing (eg LaTeX, InDesign)
* Relevant: The essay addresses a topic that is relevant for DevOps

We aim for pass with distinction.

### CODE REVIEW

**Review by cesarsotovalero — APPROVED** [review]

**Comment by cesarsotovalero** [comment]
@dmariel LGTM. Looking forward to reading your essay. Good luck!

**Comment by IfyUrama** [comment]
I will give feedback for this task and my feedback PR id is #1110.

**Comment by IfyUrama** [comment]
Hi,

I am waiting for your essay submission to give feedback.

**Comment by dmariel** [comment]
Hi! I'm sorry, we were not aware that giving feedback four business days before the final submission was part of the feedback criteria, since we are not doing the feedback task ourselves and the deadline for the essay is April 30. We are currently working on the essay, but could send you a draft this evening if you like? If so, please share a Google e-mail address with us, so that we can send you a link. Also, please note that this is not a finished version. We will then look at your feedback and see if we can implement your changes to our final version, which I believe is another criteria for the feedback task @IfyUrama

**Comment by IfyUrama** [comment]
Ok, my Google e-mail address is ifeomaurama0@gmail.com.

**Comment by IfyUrama** [comment]
Feedback submission on essay draft #1023.

@dmariel Here is feedback link: Feedback submission on essay draft #1023 #1392

**Comment by khaes-kth** [comment]
Fine. Actually, you were supposed to write the feedback in a PR comment, but I do not see a comment including the content of your feedback. As I understand, you have just referred to your feedback submission [here](https://github.com/KTH/devops-course/pull/1023#issuecomment-827695264). I cannot find the content of your feedback in the [referred PR](https://github.com/KTH/devops-course/pull/1392/files).

We want to make sure that the feedback receiver has read your feedback. Do you have some evidence for that?

**Comment by IfyUrama** [comment]
Hi @khaes-kth 

Ok. Initially, I added my feedback in the README file [Initially submission](https://github.com/KTH/devops-course/pull/1392/commits/025bf9ff1cd7541691d12673edff7240f56bdb27)  and in the goggle doc @dmariel sent me through gmail account. I later deleted it when i decided to make a new pull request for feedback submission.

**Comment by dmariel** [comment]
Hi! Can confirm that we have received the feedback @IfyUrama @khaes-kth

**Pull request merged**
