### PR TITLE
Demo: CI and CD pipeline using Azure DevOps

### PR DESCRIPTION
**Pull request by MDRezaulHasan**

### CODE REVIEW

**Comment by MDRezaulHasan** [comment]
Hi @khaes-kth, I added my demo video and create a new PR. Take a look at this video. Thanks

**Comment by khesoem** [comment]
Hi @MDRezaulHasan 

Thanks for the video. Your PR is [changing files that should not be changed](https://github.com/KTH/devops-course/pull/1480/files). Please fix it.

Do you have any specific question regarding your submission that need me to watch the video now? If not, we can merge the PR and later we will grade it.

**Comment by MDRezaulHasan** [comment]
@khaes-kth, I am trying to delete this file but I can not. Can you help me?

**Comment by khesoem** [comment]
The easiest solution: 1- copy your changed file somewhere in your PC to save it, 2- unfork, 3- fork again, 4- make the change again, create a new PR and ping me there, 5- close this PR.

**Pull request closed without merging**
