### PR TITLE
Essay submission: Introduction to Software-bots: Slackbots

### PR DESCRIPTION
**Pull request by shotaroi**
# Assignment Proposal

## Title

Introduction to Software-bots: Slackbots

## Names and KTH ID
  - Shotaro Ishii (shotaro@kth.se)

## Deadline

Task 4

## Category

Essay

## Description

In the essay, general introcution to software-bots and slackbots, as well as how Slackbots is used and benefitial
in devops are planned to be discussed.

### CODE REVIEW

**Comment by zehaoj** [comment]
Hi @shotaroi We think your essay is very interesting and would like to know if we could give feedback on this?

**Comment by shotaroi** [comment]
Hi @zehaoj. Thank you, yeah feel free to do that if you'd like

**Comment by javierron** [comment]
Thanks for the submission!

**Comment by zehaoj** [comment]
# Feedback for Essay on Introduction to Software-bots: Slackbots

This essay gives an overview introduction about software-bots and some of their related areas. On top of that, it mainly focused on a certain type of bot, Slackbots, which is based on a messaging app Slack. Overall speaking, this essay is both informative and easy to understand. Readers can quickly get the idea of what is slackbots and in what areas it is used. But in the meantime, we think there are some parts that can be improved. But in general, it is a good essay and we a log from it.

Here's our feedback on this essay:

## Strength
* The essay is well written
	* It has a good structure and is visually appealing, which makes it easier for readers to follow the author's idea.
* The essay is self-interpretative and the concepts are interpreted nicely. 
* The Introduction of the essay outlines the problem.
	* It brings out the problem this essay is trying to focus on, which makes it easier for readers to quickly know what this essay is mainly about.
* The Conclusion of the essay appropriately summarizes the whole essay and contains a concise take-home message.


## Weakness
* The essay could have more content about Slackbots.
	* We think since this essay is about Slackbots, it should take up most of the pages. However, though illustrated and discussed a little bit more in detail, it is still not enough. The topic of the essay might not be so clear and we think maybe having less content about general bots and more about Slackbots would be better. 
	* The article [Why developers are slacking off: Understanding how software teams use slack](https://dl.acm.org/doi/pdf/10.1145/2818052.2869117?casa_token=VIdCdtY1GDgAAAAA:RT6mfvNQ7C8jmdfIt0WG9zz3UBuMeI4-olJF5rnPaQq6L3K0PRIFhWhSJqF53qGuuVBbB2xUKeM4Kg) provides more detailed information about slackbots and it would be nice if the author could cite some.
* Some parts are not related to DevOps very closely. 
	* For example in section 4, it would be better if the author could clearly state the relationship between all these types of bots and DevOps and how they're used differently in the process.
* The essay is somewhat too general and is not very innovative. 
	* We suggest that the author can take a look at [The impact of anthropomorphic and functional chatbot design features in enterprise collaboration systems on user acceptance](https://www.researchgate.net/profile/Ivo-Benke/publication/330728789_The_Impact_of_Anthropomorphic_and_Functional_Chatbot_Design_Features_in_Enterprise_Collaboration_Systems_on_User_Acceptance/links/5c7323f0a6fdcc471599048b/The-Impact-of-Anthropomorphic-and-Functional-Chatbot-Design-Features-in-Enterprise-Collaboration-Systems-on-User-Acceptance.pdf)
* The essay could use more figures or listing.
	* To help readers better understand the importance of the usage of bots in DevOps. The listing in section 3.1 could also contain more information rather than just the name of the tools.
* Some terms are not explained.
	* After the listing of example of tools used in DevOps in section 3.1, it would be more helpful if the author could give a brife introduction on these tools, otherwise readers might be confused.
* The essay should cite more articles in a single section.
	* For example section 4.2 only cites one article, which might not be sufficient and convincing. Even worse, it could lead to potential plagarism.

**Pull request merged**
