### PR TITLE
Week 2: Presentation proposal (maxisr & jbiorck)

### PR DESCRIPTION
**Pull request by Blezie**
# Assignment Proposal

## Title

Mockito: What it is, how it works, and how it improves automated testing in Java

## Names and KTH ID

  - Johann Biörck (jbiorck@kth.se)
  - Max Israelsson (maxisr@kth.se)

## Deadline

- Week 2

## Category
  - Presentation

## Description

We want to talk about Mockito, a Java-based mocking framework, to enhance the testing automation process, specifically within the context of Continuous Integration (CI). Mockito allows developers to create mock objects for unit tests. It enables simulation of complex interactions without requiring actual dependencies.

**Relevance**

This proposal is relevant as it improves automated testing by using Mockito to simplify test development through mocking external dependencies.

### CODE REVIEW

**Comment by algomaster99** [comment]
Hi @Blezie ! Thanks for the proposal! A presentation of Mockito looks good. However, since it is a huge library, it would be nice to focus on only one feature. For example, this feature could be on of the latest features. You can look at their changelog to find such features.

**Comment by JohannBiorck** [comment]
> Hi @Blezie ! Thanks for the proposal! A presentation of Mockito looks good. However, since it is a huge library, it would be nice to focus on only one feature. For example, this feature could be on of the latest features. You can look at their changelog to find such features.

We plan to focus on the mock feature, by showing an example of how its done. Does that sound okay?

**Comment by algomaster99** [comment]
@JohannBiorck ! Do you have any specific APIs in mind? One of the major features you can present is [`DoNoMock`](https://github.com/mockito/mockito/releases/tag/v4.1.0) with some context of Mockito.

But maybe I am being too focussed. :sweat_smile: @Deee92 is an expert in testing and testing libraries. She can help use converge towards a topic. What do you think of the proposal and my suggestion, @Deee92 ?

**Comment by JohannBiorck** [comment]
> @JohannBiorck ! Do you have any specific APIs in mind? One of the major features you can present is [`DoNoMock`](https://github.com/mockito/mockito/releases/tag/v4.1.0) with some context of Mockito.
> 
> But maybe I am being too focussed. 😅 @Deee92 is an expert in testing and testing libraries. She can help use converge towards a topic. What do you think of the proposal and my suggestion, @Deee92 ?

I dont understand how explaining DoNoMock would be more interesting that what we intend to do, it seems very easy to use and its functionality is not hard to understand. Is it not focused enough to give context of Mockito then explain and show and example using Mocks?

**Comment by algomaster99** [comment]
>  how explaining DoNoMock would be more interesting that what we intend to do

Personally, mocking an object is binary. Either you put `@Mock` or you don't so why is there another annotation. Moreover, `@DoNotMock` has been introduced as a major feature.

> Is it not focused enough to give context of Mockito then explain and show and example using Mocks

It is sufficient to present it, but I want you to present more APIs in the library apart from just `@Mock`. And yes, if you don't like the feature I looked up, do not present it. But mockito is a huge library. I am sure you can find many interesting things about it.

**Comment by Deee92** [comment]
Hi @JohannBiorck and @Blezie, mocking is great. I agree with @algomaster99 though, presenting an overview of Mockito (as one would get from its docs) might not be enough.
How about presenting mocking in general - what problem it solves, why it is challenging, when should we not use it? You could then talk about mocking tools / libraries and techniques for different languages (e.g., the best libraries for Java, Python, etc), and different contexts (e.g., mocking APIs). Make sure to include examples (code listings), even better if you can find some from real projects such as on GitHub.
How does this sound?

**Comment by JohannBiorck** [comment]
> Hi @JohannBiorck and @Blezie, mocking is great. I agree with @algomaster99 though, presenting an overview of Mockito (as one would get from its docs) might not be enough. How about presenting mocking in general - what problem it solves, why it is challenging, when should we not use it? You could then talk about mocking tools / libraries and techniques for different languages (e.g., the best libraries for Java, Python, etc), and different contexts (e.g., mocking APIs). Make sure to include examples (code listings), even better if you can find some from real projects such as on GitHub. How does this sound?

This sounds good! Should we talk about multiple different tools and show multiple examples, or is it enough to talk about mocking in general and then go into specifics and show code examples from Mockito?

**Comment by Deee92** [comment]
You can motivate the need for mocking, and illustrate with good examples. I recommend presenting how mocking can be done for different use cases and with different tools.

**Comment by JohannBiorck** [comment]
> You can motivate the need for mocking, and illustrate with good examples. I recommend presenting how mocking can be done for different use cases and with different tools.

I like this idea I am just not sure if we have the time to go into any real depths if we are to bring up multiple examples and show off different tools. is that fine?

**Comment by algomaster99** [comment]
> > You can motivate the need for mocking, and illustrate with good examples. I recommend presenting how mocking can be done for different use cases and with different tools.
> 
> I like this idea I am just not sure if we have the time to go into any real depths if we are to bring up multiple examples and show off different tools. is that fine?

I think you do have time for multiple examples. You can write the outline (slide by slide) of the presentation that you are thinking which is exceeding time. I can help you shorten.

**Comment by JohannBiorck** [comment]
> > > You can motivate the need for mocking, and illustrate with good examples. I recommend presenting how mocking can be done for different use cases and with different tools.
> > 
> > 
> > I like this idea I am just not sure if we have the time to go into any real depths if we are to bring up multiple examples and show off different tools. is that fine?
> 
> I think you do have time for multiple examples. You can write the outline (slide by slide) of the presentation that you are thinking which is exceeding time. I can help you shorten.

okay we will give it a go then!

**Comment by JohannBiorck** [comment]
@algomaster99 
This is our current structure: Intro - Explain what mocking is and why it is useful -> Explain what Mockito is and then show an example of mocking in Mockito -> Then we talk about when not to use Mocking and show an example here as well ( Right now this is also using mockito but we can change it). -> Then we have a reflection about the pros and cons of mocking -> Then we talk a little bit about other languages and frameworks for mocking and finally we end with our take-home message.

Does this sound good?

**Comment by algomaster99** [comment]
@JohannBiorck ! Looks good to me. @Deee92 , what do you think?

> Then we talk about when not to use Mocking and show an example here as well

This is nice!

**Comment by Deee92** [comment]
Yes, sounds good. @algomaster99 we can merge this PR. Looking forward to the presentation!

**Pull request merged**
