### PR TITLE
Tutorial proposal: Automated monitoring/analytics with ELK Stack

### PR DESCRIPTION
**Pull request by andreaskth**
# Executable tutorial: Automated monitoring/analytics with ELK Stack

## Members

Andreas Kärrby (karrby@kth.se)  
Github: [andreaskth](https://github.com/andreaskth)

Henrik Kultala (kultala@kth.se)  
Github: [hengque](https://github.com/hengque)

## Proposal

We would like to create an executable tutorial on Katacoda that will showcase how to add support for monitoring/analytics in an application by using the ELK stack (Elasticsearch, Logstash, Kibana). We will create our own very basic application and extend it with monitoring/analytics.

As for the actual analytics to focus on, it remains to be determined when we've learned more about the capabilities of the ELK stack. Most likely we want to focus on generating and displaying data on how users interact with the application (which elements the user interacts with most, which views are most frequently visited, and how much time is spent in each view).

The relationship to DevOps is that monitoring is a big part of "Ops" and a lot can be gained by automating this as much as possible. Also [this](https://www.atlassian.com/devops/devops-tools/devops-monitoring?) reference contains good motivations for why/how this is related to DevOps.

### CODE REVIEW

**Comment by khesoem** [comment]
Hi,

This is a relevant and timely topic. However, there are many uncertainties in your proposal yet. Please make your final decisions and update the proposal accordingly.

**Comment by andreaskth** [comment]
Hi @khaes-kth, we've updated our proposal now after having made a few choices. What do you think, does this sound good?

**Comment by khesoem** [comment]
Hi,

As far as I see, you changed the title of this PR. Please change the title of your tutorial in the README file as well.

**Comment by andreaskth** [comment]
Right, thanks for the reminder! It should be good now, @khaes-kth

**Pull request merged**
