### PR TITLE
Week 5 demo proposal

### PR DESCRIPTION
**Pull request by leegrash**
# Assignment Proposal

## Title

Using Bicep to edit Azure resources as code

## Names and KTH ID

  - Gustaf Svensson (gussvens@kth.se)
  - Carl Lavö (lavo@kth.se)

## Deadline

- Week 5

## Category

- Demo

## Description

We want to demo how to setup Azure infrastructure resources using the Bicep language. The demo will show how to edit and setup a similar environment in a different Azure region. The demo will further compare the process of using Azure CLI and ARM templates to using Bicep to declaratively generate the resource templates.

**Relevance**
Microsoft Azure is the largest cloud computing provider however their DSL bicep for IAC on MS Azure is not as common as similar technologies such as Teraform or AWS cloud formation. The technologies differ in key aspects and we think it would be interesting to demo this technoloy to the rest of the course attendees.

### CODE REVIEW

**Comment by algomaster99** [comment]
Hi! Cool proposal! Never heard of bicep. Could you add a comparison with azure cli as well?

**Comment by leegrash** [comment]
Sure! We can compare it to azure cli!

**Comment by algomaster99** [comment]
Could you also edit the proposal?

**Comment by leegrash** [comment]
The proposal has been edited.

**Pull request merged**
