### PR TITLE
Revised Submission Essay: Exploring Linkerd as a Service Mesh Layer for Observability, Reliability, and Security

### PR DESCRIPTION
**Pull request by aykhazanchi**
# Assignment Proposal

## Title

Exploring Linkerd as a Service Mesh Layer for Observability, Reliability, and Security

## Names and KTH ID
  - Ayushman Khazanchi (ayushman@kth.se)

## Deadline

Task 4 (Repeated Task)

## Category

Essay

## Description

In this essay I would like to explore service mesh layers and how they fit into the Kubernetes architecture. I will begin by giving a brief overview of what is a service mesh, what they do, how they implement communication, observability, security, and reliability in their layers. I will explore a little bit about how Linkerd implements a service mesh and the Linkerd control and data plane. Then I will wrap up with some reflection on what are the advantages and disadvantages of using service mesh and Linkerd as one of the solutions.

**Revisions to original submission:**
- Rewrote multiple sections of the essay to connect the sections better
- Added Introduction section with clear problem statement and how service mesh helps solve the problem
- Explained briefly in Introduction the motivation for focusing on Linkerd as opposed to other options
- Mentioned alternatives to Linkerd with detailed benchmark comparison also provided later in the essay
- There was feedback regarding use of terms like Zero-Trust protection and Layer 7. I've provided some brief background on those whereever those terms were used, however I could not go into details there in order to be within the word limit.
- Layer 7 relevance to observability is also added now.
- Added some better sources including one more book that I read during the process.
- All references are now cited in the essay, including the academic references
- Essay was written in Latex and is justified. Section titles are numbered and sources are provided for each image as well.%

### CODE REVIEW

**Comment by monperrus** [comment]
@aykhazanchi here you remove a file but you don't provide a new essay. That's a serious issue. Please reach out to the TAs asap to explain and fix this.

**Comment by aykhazanchi** [comment]
@monperrus I was not aware both files were required to be there so I had replaced the old essay file with the revised one. But now I have added both the old file and the new one. Apologies but hope it's still allowed. cc: @Deee92 @khaes-kth

**Comment by aykhazanchi** [comment]
@Deee92 @khaes-kth the PR check is failing on some archive issue but I hope this can still be merged. I have added the original essay submission as well to the PR.

**Comment by monperrus** [comment]
ack @aykhazanchi

**Pull request merged**
