### PR TITLE
Tutorial submission: GitOps with K8s & Flux CD

### PR DESCRIPTION
**Pull request by s1grun**

### CODE REVIEW

**Comment by bbaudry** [comment]
Feedback per #573

Thank you for the early completion of this tutorial and for choosing an original and very relevant topic for the DevOps course. The tutorial is clear, well-structured and the sequence of commands to follow the tutorial is well documented. Below are some comments and suggestions to consolidate it.

- If there are two authors, explicitly mention the second author in the intro
- Access and sufficient privileges in Azure: clarify what privileges are sufficient and include instructions to set these privileges
- azure.microsoft.com: add the link
- Create the following variables: add a short description for each variable
- AKS: add a short description
- Fork GitHub repository
  - this section is about a Docker container and a Github repo. Please, clarify how these two artifacts relate to each other and what's the purpose of each one.
  - someone else’s simple Hello World: who is this someone else? are we authorized to use it? I strongly recommend that you create your own simple Github repo and images on Docker hub, which will be dedicated to the purpose of this tutorial
- Helm: add link to Helm
- fluxctl: add a link
- Add a conclusion where you reflect about the tutorial (what you expect the reader should have learned), about the different technologies that you have presented, about the general concept of Gitops

Typos
- one the same line
- control it easier
- SSH key give

**Comment by s1grun** [comment]
@bbaudry Thank you very much for the feedback!

**Comment by s1grun** [comment]
The tutorial has been updated after receiving the feedback above. https://medium.com/@sas_65289/gitops-with-kubernetes-flux-cd-ce4c8b4734f2

**Comment by gluckzhang** [comment]
Thanks for the updates. The PR has been merged!

**Pull request merged**
