### PR TITLE
REPEAT Essay: Putting the hours on fun, not manual labor: Incorporating DevOps in the Video Game Industry

### PR DESCRIPTION
**Pull request by ChangGabriel**
Here is the log of the changes @wska and I (@ChangGabriel) made after receiving feedback on the meeting and email.
Original PR: #1312 
Proposal PR: #970

# Changelog
> Sound: please improve the comparison of the previous and current deployment and QA pipelines of Butterscotch Shenanigans with and without DevOps practice (Figure 3 and Figure 4). This part is key for your essay, but not clear in the current version.

**Action:** We reformulated some sentences in section 3.2 in order to have space to add a new paragraph where we improve the comparison of the previous and current deployment and QA pipelines of Butterscotch Shenanigans with and without DevOps practice. This paragraph replaced the old last paragraph in section 3.2. It summarizes the differences before and after  Butterscotch Shenanigans adopted modern DevOps practices and presents the key takeaway from section 3.2.

>Figures: you gave Figure 1 and Figure 2, but these two figures are not referenced in the text. If you want to put a figure, you have to reference them in the text. If your figures are taken from somewhere else, please add a citation for the source of Figure 1 / 2.

**Action:** Figure 1 is now referenced in the text, tying it to the parts of the texts where it is relevant. Figures, unless a citation is included, were created by us using draw.io (https://app.diagrams.net/) (applies to figure 1). We considered your words in the meeting about figures being complementary to the text and decided to remove figure 2 since it merely acted as a visualization of the information that was already provided in the text, and not really adding any new or complementary information.

> Conclusion: what's the key difference with the mainstream DevOps practices? What's the performance/effectiveness/time-cost/fun improvement with DevOps practices? Please rewrite section 3.2 to give a comprehensive discussion.

**Action:** We followed your suggestion from our meeting and converted the "Discussion & Conclusion" into being only a Conclusion, and instead information leading up to said conclusion is left in the previous segments where we investigate the two companies in order to avoid having to disclose the same information twice. This was done both for structure but also to save on the word count. We also updated section 3.2 as part of the “sound” feedback. Additionally, we added a short segment in the conclusion about what we think are the key differences between the mainstream and game development DevOps practices, based on the material we investigated.

> Each concept and abbreviation should be introduced and defined before being used (Example: QA, CI/CD)

**Action:** All acronyms/abbreviations are now defined the first time they are mentioned, using the full word followed by the shortened name that will be used instead in the rest of the text (Quality Assurance(QA), etc.).

> Reference: the quality of reference could be improved by citing a research paper in addition to the tech posts from websites.

**Action:** This was skipped due to the references containing two instances of research citations ([2] and [6]) as discussed in our meeting about the essay.

> Citations should appear before the period at the end of the sentence (Example: . [9])

**Action:** All citations are now consistent and adhere to the principle of being at the end of the sentence and before the period.

### CODE REVIEW

**Comment by wska** [comment]
We did some additional tweaks in another commit. Final version is commit: 080f6a8ae571c790348127dd2534f3702a4b4151

**Comment by wska** [comment]
We conducted our modifications in accordance to the feedback over three commits. The latest and final version is commit: db9d49386bc7a91599d0418997e9c3f71d50d336

**Comment by wska** [comment]
@khaes-kth Hello. I noticed that this PR got labelled as a tutorial instead of an essay. 

As a side note, is there any preliminary time estimate for when we are supposed to get feedback on our repeats?

Thanks.

// William

**Comment by khesoem** [comment]
Thanks @wska for letting me know.

You will probably get your grades in Ladok this week.

**Comment by wska** [comment]
@khaes-kth Oh okay, thanks for letting me know. Do we get any actual feedback/confirmation on our submission via an email or so or only grades reported directly to ladok?

Many thanks.

**Comment by khesoem** [comment]
As far as I know, you will receive your grades on Ladok. If you want to get more feedback afterwards, you can contact us.

**Pull request merged**
