### PR TITLE
Week 7 Demo Proposal

### PR DESCRIPTION
**Pull request by RohiniBhardwaj**
# Assignment Proposal

## Title

Simplifying Kubernetes Policy Management Using Kyverno

## Names and KTH ID

  - Rohini Bhardwaj (rohinib@kth.se)

## Deadline

- Week 7

## Category

- Demo

## Description

I want to propose a demo to showcase how Kyverno simplifies and automates Kubernetes policy management. It will demonstrate Kyverno’s capabilities in enforcing security, ensuring compliance, and automating resource configurations through policies, making Kubernetes environments more secure, consistent, and manageable.

**Relevance**

Kyverno simplifies Kubernetes policy management, making it highly relevant for DevOps teams. It automates tasks like security enforcement, resource configuration, and compliance checks without the need for custom code. By using easy-to-write YAML policies, DevOps teams can ensure consistency across all environments, speeding up deployments while maintaining security.

### CODE REVIEW

**Comment by sofiabobadilla** [comment]
@RohiniBhardwaj 
Try changing the file name to README.md

**Comment by javierron** [comment]
@RohiniBhardwaj Hi, are you ready to present today?

**Comment by RohiniBhardwaj** [comment]
> @RohiniBhardwaj Hi, are you ready to present today?

@javierron 
Now, the PR is successfully created so can I do tommorow in lab?

**Comment by javierron** [comment]
@RohiniBhardwaj Ok, looks good.

**Pull request merged**
