### PR TITLE
Adding team member name to directory

### PR DESCRIPTION
**Pull request by hittesharma**

### CODE REVIEW

**Comment by hittesharma** [comment]
@SophieHYe kindly merge. It is just addition of team member name.

**Comment by SophieHYe** [comment]
Dear Hittesh, 
You may also remove the old folder of your name under essay,  so that you would be counted to work twice. Please kindly update them :)

**Comment by hittesharma** [comment]
Removing old directory for new 'hiteshs-chikafa'

**Comment by SophieHYe** [comment]
Hi Hittesh,
Please also remove this one: https://github.com/KTH/devops-course/tree/master/contributions/essay/hiteshs

**Comment by SophieHYe** [comment]
I have manually deleted this one:  contributions/essay/Essay proposal: IaC using Terraform 
and closing this PR.

**Pull request closed without merging**
