### PR TITLE
Tutorial proposal - Implementing Azure DevOps 

### PR DESCRIPTION
**Pull request by georgewbar**
### Contributors

* Helal Uddin - mhud@kth.se @sujon2100
* George Rezkalla - rezkalla@kth.se @georgewbar

### Description

VSTS is a team foundation server in a cloud. It's been around 13 years to help teams, managers, software developers to manage there developing efforts. It helps with source code, project plan, automated build, automated deploy, testing, bug tracking as well as to manage all kinds of developing stuff. With VSTS, it is possible to get all of these services but in a cloud. Because of that no need to worry about running or backing it up as Microsoft is dealing it on the behind in the cloud. It is possible to have the same features on the on-premise version of TFS. Azure DevOps Is the new version of VSTS. Same functionality but more features. As it has been observed that Microsoft has changed a lot from it's a website regarding visual studio team services name to Azure DevOps, all of the tools and extension in the Azure portal have been modified too. So in this tutorial, we will show:

* Which changes have been made regarding VSTS into Azure DevOps?
* How to use Azure DevOps to manage code
* How it is related to DevOps like automated releases, automated deployment
* How to use DevOps Artifacts
* How to use DevOps Test Plan

### CODE REVIEW

**Comment by georgewbar** [comment]
We will elaborate on this a little bit more on sunday.

**Comment by georgewbar** [comment]
@SophieHYe This PR and PR #448 are for the same team (our team). We created two PRs by mistake.

**Comment by SophieHYe** [comment]
Hi,
Thanks very much for letting me the update of PR #448 and your proposal description is excellent.
My major comments are as follows:
- Your proposal is original of comparing with VSTS，but the research questions you want to answer and discuss seem more like an essay rather than a tutorial. The comparison would be great for an essay.  For the tutorial, we may expect to see steps of how to set up the environment and execute the commands to do Azure deployment and release.
- The last four bullet points you listed for the tutorial seem a bit broad, I would recommend to maybe focus two of them. 
- Another comment maybe also think about the target users of your tutorial and the prerequisite of your tutorial.  Would you target to newbies or users with some experience?

I will merge your PR and look forward to your great tutorial!

**Comment by georgewbar** [comment]
* We will not do a full comparison. We will just state how things have changed with time in Microsoft DevOps.

## Clarification of the questions

* Which changes have been made regarding VSTS into Azure DevOps? (just a timeline of changes in Microsoft DevOps).
* How to use Azure DevOps create tasks and use VCS (how to use Boards and Git).
* How it do automated releases, automated deployment in Azure DevOps (how to use pipelines).
* How to use Test Plans (if we have time).
* How to use Artifacts (if we have time).

A demo .net core project will be used in the pipeline.

We are trying to give a holistic picture of the whole pipeline.

**Comment by SophieHYe** [comment]
Hi,
Greate! I see and I have merged your PR.

**Pull request merged**
