### PR TITLE
Finished demo: CI/CD pipeline with Travis and Google App Engine on a React aplication

### PR DESCRIPTION
**Pull request by christinerosquist**
COPY OF README: 

# Final Demo Submission
## Members
Christine Rosquist (rosquis@kth.se)
Klara Eserstam (klaraes@kth.se)
Pontus Broberg (pbroberg@kth.se)

## Topic
Demo of how to implement a CI/CD pipeline with Travis and Google App Engine on a React aplication. 

## Details
Continuous integration and continuous delivery are relevant parts of DevOps, and we would like to learn more about how to implement it. We will create a React application that is connected to GitHub, and demonstrate how Travis CI can deploy and run end-to-end tests with Google App Engine, triggered by a git push command. 

## Structure
- The agenda of the presentation 
- Demo on how to implement it 
- Take-home message

## Links

[Screencast](https://www.youtube.com/watch?v=DllEb7556YM&t=9s&fbclid=IwAR34kNENcsyL011gNgg2SeaRNbWfkVugDsHjcyukon3xUaprjVE1qB2nE8I)

[GitHub Repository](https://github.com/klaraesr/my-application-react)

[The deployed application with easter-egg](https://my-react-application-275913.ew.r.appspot.com/)

## Grading criterias that we aim to fulfill are: 

|                                             | Yes | No | Remarkable |
|-------------------------------------------- | ----|----|-------------|
|The demonstration screencast is clearly motivated (why it matters for Devops?) | **Yes** | No | **Remarkable** |
|The demonstration screencast is difficult to do | Yes | No | Remarkable |
|The demonstration screencast is original | **Yes** | No | Remarkable |
|The demonstration screencast is sublime (eg visually appealing) | **Yes** | No | **Remarkable** |
|The demonstration screencast contains an easter egg | **Yes** | No | **Remarkable** |
|An accompanying Github repository has been made (optional) | **Yes** | No | Remarkable |

Motivation for the criterias: 

**The demonstration screencast is clearly motivated:** Yes, Continuous Integration and Continuous Deployment are essential parts in DevOps. We clearly state why it is important and relevant in the demo in the take-home message. 

**The demonstration screencast is original:** Yes, we have seen variants of this demo but nothing that is completely similar to this. Also, the idea with the easter-egg is something we think is original.

**The demonstration screencast is sublime:** Yes, the demo is visually appealing. For example, we highlight different buttons when they are being pressed so that the user easier can follow the demo. Also, the screen is zoomed in and with subtitles describing the different steps, so that you can follow what is happening on the screen very well.  

**The demonstration screencast contains an easter egg:** Yes, we provide an easter-egg that is hidden in our application. The user must type the word "devops" in order to see the easter-egg, which is a bonus section where we describe how to also integrate code-coverage to the pipeline.  

**An accompanying Github repository has been made (optional):** Yes, the link is provided here in the README and also in the Youtube-video.

### CODE REVIEW

**Comment by jadlers** [comment]
I'd like to give feedback to this demo :relaxed:

**Comment by louisezetterlund** [comment]
I will give feedback to this one :)

**Comment by johannaii** [comment]
Me too!

**Comment by Kappenn** [comment]
I will give feedback

**Comment by jrutqvist** [comment]
I'll give feedback as well!

**Comment by MindaugasVarkalys** [comment]
I would like to give feedback

**Comment by sujon2100** [comment]
I would like to give feedback.

**Comment by sujon2100** [comment]
Here is the feedback:
The screencast looks great. In general, it has a good explanation by the subtitles and with the pointers on the screen. Just as a general suggestion to improve the screencast is instead of fixed, you could add a voice to explain it more efficiently. Besides, Easter eggs could be added as a hidden field so that the viewers can easily click and reveal that wherever they want. Otherwise, it's great job. Wish you good luck!

**Comment by louisezetterlund** [comment]
Thank you for your demo!

The demo was very easy to follow and I really liked how clear it was when you darkened the screen to show where to press. 

Suggestions for improvement:
It would be nice to have a voice-over. I had to pause the video whenever there was a new text because I thought it was hard to read and follow the cursor at the same time.

**Comment by johannaii** [comment]
Really good demo and screencast! Thank you for sharing it with us. 

I really like the structure of the screencast, and that you show the agenda for the screencast in the beginning. I also like the visual effects that you have added to the video. For instance, when you highlight which button you should press. The screencast is easy to follow, it is sublime, the subtiles are easy to read (because of the box and background color), and I like the topic that you have chosen. 

A big + for adding a good and useful tip as an award for finding the ”secret” keyword :D

**Comment by Kappenn** [comment]
Good job!

The Demo is really clear on what you do every step. I really like the highlights on every step, it made it really easy to follow and alwasy been in the known of what you are doing.

As for criticism, sometimes I can't read fast enough and also have a look at the screen. You could slow down some parts of the video (although the video is already 5 min) or add a voice over so it is easier to follow what happens on the screen.

**Comment by jrutqvist** [comment]
First of all: nice music, really got the vibe going in this demo! I appreciate that you really made the steps you've taken very clear and highlight all the button presses, it really showcases the whole process. A nice addition would be a quick illustration or diagram explaining how all the technologies link together so that you can map it all out in your head as well, though I understand time is in short supply so it might be hard to fit in.

**Comment by jadlers** [comment]
Over all the video is well made and I think it meets all mandatory requirements, good job! :clap:

- Good introduction which gives a clear overview to what will be shown.
- Nice highlighting of areas to help the viewer know what to look at.
- It's a bit unclear if you should do anything on TravisCI after you've approved it for all repositories [here](https://youtu.be/DllEb7556YM?t=56) (56s). Should you just make sure the repo is in the list?
- Minor clarification could be made [here](https://youtu.be/DllEb7556YM?t=142) (2m22s) where the text box says enable the "App Engine API" while you search for "App Engine Admin API".
- The descriptions given for each part is easily read and gives clear information.
- Nice easter egg! Great how it adds information as to how to proceed further with testing.
- The choice of music is good as well, not to distracting which is perfect.

**Comment by christinerosquist** [comment]
@jadlers @louisezetterlund @johannaii @jrutqvist @Kappenn @sujon2100 

Thank you all for the nice feedback! We will definitely add a voice-over to the demo since almost all of you suggested it. We will also take the other things you mentioned into consideration when improving the demo. Thank you so much! :)

**Comment by MindaugasVarkalys** [comment]
Nice demo! I liked that you included all the setup steps and not only showed how it works. The music is very nice, but I would personally prefer to hear your voice instead of reading. Besides that the subtitles change too fast and I had to constantly pause the video. For subtitles, I would recommend you using sans serif font instead of serif, because it easier reads on the display. But overall, the content of the demo is great. Good job!

**Comment by christinerosquist** [comment]
Thank you @MindaugasVarkalys for the feedback! We will take everything you wrote into consideration :)

**Pull request merged**
