### PR TITLE
Presentation: MLOPS - Current application and future possibilities

### PR DESCRIPTION
**Pull request by jhammarstedt**
Ideas for our presentation week 3

### CODE REVIEW

**Comment by cesarsotovalero** [comment]
Hi @jhammarstedt, your idea for the presentation is very relevant for this DevOps course.
Can you please give more details of the differences that you will discuss in your presentation?

**Comment by sestys** [comment]
The main difference is the introduction of data pipelines, model training and monitoring, and model deployment into the automation process. These changes make it more complex as multiple different actions (not just push of new code into repo) can trigger the integration/deployment. 
We also want to present current solutions used for MLops and where they are headed, as more Ops engineers will need to work with them if the Software 2.0 revolution will come.

**Comment by cesarsotovalero** [comment]
Hi @sestys,
Thank for the description. LGTM.
I'll merge your proposal.
Good luck!

**Comment by monperrus** [comment]
thanks a lot @jhammarstedt for the presentation. We still have some free slots in week 2 (coming Tuesday), what about moving your presentation on week 2?

**Comment by sestys** [comment]
sorry for getting back that late @monperrus, but we weren't able to finish the presentation on time to present it tomorrow.

**Comment by monperrus** [comment]
ack. no worries.

**Pull request merged**
