### PR TITLE
Final submission: Dockerizing Node.js application [Executable tutorial]

### PR DESCRIPTION
**Pull request by bckfilip**
# Assignment Proposal

## Title

Dockerizing a Node.js application

## Names and KTH ID
  - Filip Bäck (filbac@kth.se)
  - Isac Haglund (isacha@kth.se)

## Deadline

Deadline 4

## Category

Executable tutorial

## Description

Reference to original proposal #1759 

We would like to create a tutorial in Katacoda that shows how to create an Express server as well as to containerise with the help of Docker. The tutorial will explain basic concepts of building an Express server with Node.js with the required steps for it to work properly. Then, we will show how to deploy the application with Docker. The guide will contain an explanation of what Docker is and how it works, with explanations of how to configure a Dockerfile, explain what images and containers are, and the commands to demonstrate it. Additionally, we will address the most common commands used within Docker, such as run, build, ps, exec, etc,.

Link to Katacoda Scenario [Katacoda](https://www.katacoda.com/filipback/scenarios/dockerizing)
Link to GitHub repo [GitHub](https://github.com/bckfilip/katacoda-scenarios)

*hint: easter egg on last slide*

### CODE REVIEW

**Comment by bckfilip** [comment]
The katacoda will be updated with a flowchart as well to fulfil an additional requirement.

**Comment by bckfilip** [comment]
The flowchart has now been added.

**Comment by bckfilip** [comment]
I did notice that I had not updated my fork with the relevant update, only the comment in the PR. I hope that this is not an issue though, as it contains the same info as the comment.

**Comment by bckfilip** [comment]
# Assignment Proposal

## Title

IaaS: The Battle of the Clouds

## Names and KTH ID
  - Filip Bäck (filbac@kth.se)

## Deadline

Deadline 5

## Category

Essay

## Description

My proposal is to write an essay about the three big cloud platforms, namely AWS, Google Cloud, and Microsoft Azure. The essay will contain an introduction to cloud platforms, how each of the big three corporations work with their respective cloud platforms as well as a comparision between the three in regards to functionality among other things.

**Comment by javierron** [comment]
Hello @bckfilip, thanks for the submission.

Right now your PR contains a readme file that is not related to the submission (an essay proposal). In order to merge your submission you need to remove that file.

**Comment by bckfilip** [comment]
@javierron Hi and thanks for the feedback. I have removed the files unrelated to this submission. Hope everything is in order.

**Pull request merged**
