### PR TITLE
Final Submission - Gradle and Github actions Executable Tutorial (Original PR: #1693)

### PR DESCRIPTION
**Pull request by ZerooCoool**
# Assignment Proposal

## Title

Setting up continous testing and integration using gradle and github actions

## Names and KTH ID
  - Filip Sannervik (sannerv@kth.se)
  - Kunal Bhatnagar (kunalb@kth.se)

## Deadline

Task 1

## Category

Executable tutorial

## Description

We created an executable tutorial with Katacoda which teaches how to setup a Gradle project for build and test automation. It also teaches how to add unit and integration tests, and how to combine this with GitHub actions to create a CI/CD pipeline. It also explains the basics of how Maven can be combined with gradle to publish a Gradle artifact to a Maven repository.

It consists of the following parts:

* Introduction to Gradle
* Introduction to GitHub Actions
* Setting up a project with Gradle
* Adding unit and integration tests
* Setting up CI pipeline with GitHub actions
* Using Maven to publish a Gradle artifact

## Links

* [Link to Katacoda Tutorial](https://www.katacoda.com/filipsannervik/scenarios/ci-gradle-github)
* [Link to Katacoda Repo](https://github.com/ZerooCoool/katacoda-scenarios)

### CODE REVIEW

**Comment by ZerooCoool** [comment]
The original pull request is #1693, we had to make a new one since I thought it was a good idea to merge the latest version before I created the pull request. This resulted in many changed files so the assistant told me to fix it and create a new one, then mention the earlier pull request.

**Comment by khesoem** [comment]
@ZerooCoool Your PR should only update the README file and add the info related to final submission there. Can you fix it?

**Comment by ZerooCoool** [comment]
Fixed it

**Comment by khesoem** [comment]
Didn't you have your proposal merged before?

**Comment by ZerooCoool** [comment]
Yes the proposal was merged before we started the assignment. This is the final submission.

**Comment by khesoem** [comment]
Can you send a link to your proposal PR?

**Comment by ZerooCoool** [comment]
Yes here it is: https://github.com/KTH/devops-course/pull/1643

**Comment by khesoem** [comment]
It seems that PR was wrongly merged. You should put your readme inside a folder with your your names on it as you have done in this final submission PR. Can you please remove what you have written in the proposal PR and merge that info into this PR?

**Comment by ZerooCoool** [comment]
Do you want me to edit the closed proposal PR, edit the readme inside the folder to include the information of the proposal, and then merge that into this PR? So in the end this PR will just have one readme file containing the proposal? Where should the information related to the final submission be then?

**Comment by khesoem** [comment]
No. I want that this PR does two things:
1- removes your text from the README file that you updated in your proposal.
2- include all the information (proposal+final submission) in the README file you are creating in this PR. Your final version of this readme should look like this: https://github.com/KTH/devops-course/blob/2022/contributions/executable-tutorial/jedma-segatz/README.md

**Comment by ZerooCoool** [comment]
Ok sounds good, I fixed it now

**Comment by khesoem** [comment]
I just noticed you have picked deadline 1 for this task, which is April 5. But the PR was submitted on 12 days ago. Did you submit your task before the deadline?

**Comment by ZerooCoool** [comment]
Yes if you see my first comment and the title there is a link to an earlier PR which is the original. I was told to make some changes and make a new PR and mention the earlier one which was submitted before the deadline. You can also see that there is no changes to the submission except for the PR formality.

**Comment by khesoem** [comment]
Aha, great! We'll consider this submission.

**Comment by joakim-olsson** [comment]
Hi I'd like to do a feedback task on your tutorial

**Comment by ZerooCoool** [comment]
> Hi I'd like to do a feedback task on your tutorial

Okay, you are allowed to do so Joakim!

**Pull request merged**
