### PR TITLE
Week 6: Demo proposal

### PR DESCRIPTION
**Pull request by joseflindkvist**
# Assignment Proposal

## Title

Measuring frequency of deployments

## Names and KTH ID

- Tobias Ljunggren (tljun@kth.se)
- Josef Lindkvist (joslindk@kth.se)

## Deadline

- Week 6

## Category

- Demo

## Description

The organization DORA comes out with the state of DevOps every year. Additionally, they provide a standard set of DevOps metrics used for evaluating process performance and maturity. These metrics provide information about how quickly DevOps can respond to changes, the average time to deploy code, the frequency of iterations, and insight into failures.

This demo will demonstrate how to easily and automatically measure frequency of deployments. The demo will utilise GitHub actions webhooks and a serverless rest API (AWS lambda) connected to a database (MongoDB). The demo will mainly focus on the GitHub actions webhooks, how to parse the payloads, and which events can trigger. It will not be about setting up AWS lambda.  

_Relevance

Github actions are commonly used to have autonomy and create personalised workflows for the deployment processes. This demo can be used for any project regardless of if the application is hosted on vercel, heroku, AWS, etc.

https://www.atlassian.com/devops/frameworks/dora-metrics

### CODE REVIEW

**Comment by algomaster99** [comment]
Looks good to me! But it may collide with https://github.com/KTH/devops-course/pull/2376. @Deee92 , can we have two different tasks for the same topic?

EDIT: asking only one TA to delegate responsibility efficiently.

**Comment by Deee92** [comment]
Hi @algomaster99, this does overlap with #2376.
@joseflindkvist, I suggest making a new proposal with a different (preferably non-UI) testing framework.

**Comment by joseflindkvist** [comment]
Hi @algomaster99 & @Deee92, we have now updated our proposal. Please let us know what you think! We found a different subject we thought was interesting.

**Comment by algomaster99** [comment]
Hi! It does not seem relevant to the week 4 theme of AIOps. 

> how to easily and automatically measure frequency of deployments.

I do like the problem statement. Can you move this demo to week 3?

**Comment by tobiasljunggren97** [comment]
> Hi! It does not seem relevant to the week 4 theme of AIOps.
> 
> > how to easily and automatically measure frequency of deployments.
> 
> I do like the problem statement. Can you move this demo to week 3?

@algomaster99 I already have another PR out for a week 3 Scientific Article, are you allowed to do multiple things in the same week? You can see that one [here](https://github.com/KTH/devops-course/pull/2416). If you are allowed to do multiple presentations the same week I can do it, but from my understanding you are not allowed to?

**Comment by algomaster99** [comment]
@Deee92  I have a question. The proposal is good, but it is relevant to week 3. However, the are already presenting [another task](https://github.com/KTH/devops-course/pull/2416) in week 3. How should we accommodate this proposal?

**Comment by Deee92** [comment]
@tobiasljunggren97 @joseflindkvist if there is a possibility to make your task more IaC-centric, we could have it on Week 6.

**Comment by joseflindkvist** [comment]
> @tobiasljunggren97 @joseflindkvist if there is a possibility to make your task more IaC-centric, we could have it on Week 6.

Yea I guess we could spend more time talking about the serverless setup and make it more IaC-centric, though it wasn't our initial idea. Could we otherwise present it in week 7 that is a bit more open?

**Comment by Deee92** [comment]
Yes, that is an option, but Week 7 ideally should not overlap with topics from previous weeks. I would recommend demo-ing in Week 6, focusing more on IaC. Wdyt, @algomaster99?

**Comment by algomaster99** [comment]
@Deee92 do you mean demo-ing in week 6? If you mean week 6, I agree with you!

**Comment by joseflindkvist** [comment]
@Deee92 @algomaster99 Then we'll do this demo in week 6 instead. I've now changed the path + deadline of our proposal. Please let me know if you have any other comments.

**Comment by algomaster99** [comment]
This is good! Thank you!

**Comment by joseflindkvist** [comment]
Hello @Deee92 @algomaster99, I just wanted to make sure with you that we can still do this demo next week. Asking because you thought it would work if we focused a little bit on IaC, but realized that IaC was yesterday's theme. So it is off-brand for next weeks theme but it may be okay since you approved it?

**Comment by Deee92** [comment]
Oops, we were off by one week. This topic would indeed be out of place for the lecture of week 6. How about presenting in the lab of week 6, i.e. October 3? Wdyt, @algomaster99?

**Comment by algomaster99** [comment]
@Deee92 yeah, I agree that it is off-topic. But we merged it and it is on number 5 in the schedule. @joseflindkvist would it be okay if we shifted your demo to October 3 instead of October 2?

**Comment by joseflindkvist** [comment]
@algomaster99 @Deee92 Yes, of course, we can do it on the 3rd of October. Do you still want us to focus on IaC, or could we return to our original idea of being more CD-centered? We would prefer this :)

**Comment by algomaster99** [comment]
The proposal is more relevant to CD and it is merged so no point of suggesting any changes to it :) 
Deliver what you have plans for :100:

**Comment by joseflindkvist** [comment]
@algomaster99 Hi, do you have a time slot for us to present tomorrow at the lab session? :)

**Comment by algomaster99** [comment]
Hi @joseflindkvist ! 13.15 October 3 at the lab. Is it good for you?

cc @Deee92 @javierron @sofiabobadilla

**Comment by joseflindkvist** [comment]
Yes that works great! @algomaster99

**Comment by algomaster99** [comment]
Great. I have scheduled you.

**Pull request merged**
