### PR TITLE
Essay proposal IaC

### PR DESCRIPTION
**Pull request by psalqvist**
# Assignment Proposal

## Title

A comparitive study of IaC tools - Terraform, Pulumi, Google Cloud Deployment Manager and AWS CloudFormation

## Names and KTH ID

 - Philip Salqvist (phisal@kth.se)

## Deadline

Task 3

## Category

Essay

## Description

During the rise of IaC, a number of tools and platforms have been established. However, these tools are quite heterogeneous by differing in a number of important ways.
Investigating the main differences by a comparitive study of these tools could be of great benifit when making a long term choice in investing in a perticular IaC technology.
This study will do precisely that by investigating four different tools, which are divided into two open source and two closed source alternatives, namely Terraform and Pulumi
as well as Google Cloud Deployment Manager and AWS CloudFormation.

### CODE REVIEW

**Comment by psalqvist** [comment]
Could you please take a look at this proposal @Deee92?

**Comment by Deee92** [comment]
Hi @psalqvist, thanks for your proposal. We've had a very similar one this year (see #1817). Can you try modifying your proposal or making a new one?

**Comment by psalqvist** [comment]
Thank you for the feedback @Deee92. I have two proposals, and would like to run them by you quickly before putting one of them down officially in the README:

1.  Identify the main challenges practitioners face when developing IaC.
2. Identify the best practices used when developing IaC.

Both of these areas were recommended as potential research avenues under section 5.2 in this [systemic mapping of current IaC research](https://www.sciencedirect.com/science/article/pii/S0950584918302507?casa_token=5x8rrdMUxGQAAAAA:ugIlaBZNLzu3Y5NCnCmKGvifcWyIMsDqmSU3X9rt9o6BPQvtA1rlsfGHnCuZg7CEv_Yn7Lc4kA).

**Comment by psalqvist** [comment]
Please let me know whether any of these are ok or if perhaps both of them are!

**Comment by psalqvist** [comment]
Sorry to be a bit pushy, but it would be great if I could get started on the essay this afternoon. Are any of the two proposals ok from your point of view @Deee92?

**Comment by Deee92** [comment]
Hi @psalqvist, these ideas sound good. Perhaps you can address both in one essay. Make sure you include this reference as well!

**Comment by Deee92** [comment]
I'm closing this PR then. Looking forward to your new proposal!

**Pull request closed without merging**
