### PR TITLE
Tutorial Proposal: An investigation into Docker & Kubernetes.

### PR DESCRIPTION
**Pull request by Nick-Steele**
A practical investigation of Docker and Kubernetes with respect to development/testing environments.

sraa@kth.se 
nseele@kth.se 

Sashi and I want to focus and learn about containers and their management using Kubernetes. We think this is an important topic as containers can be used in almost all parts of the DevOps lifecycle from providing a configured environment for application developers, testers and operational developers to the deployment of an application. Hence, learning containerisation management/ provisioning is a vital skill for anyone wanting to get dirty with DevOps!

We want to portray their relation through a step by step tutorial:

Tutorial outline: 
•	Overview (What and why).
•	Set up a docker development or testing environment.
•	Provision, manage and scale using Kubernetes.
 
I myself for a long time had heard of Docker and Kubernetes but I did not know the differences and powerful outcomes these technologies can have within DevOps projects.
There are many tutorials on getting started with Docker and Kubernetes but ours will demonstrate their relations through a sequence of steps clearly outlining a fluid transition between the two tools, educating students on how they work with one another.

After the tutorial the student will:
•	Understand the difference between Docker/Kubernetes with a sound understanding of their relation. How to create Docker environments (example probably with some sort of skeleton app (the app here isn’t that important the focus is on configuring and using the services))
•	How to manage and provision Docker containers with Kubernetes.
 
A good issue/theme to stick with in relation to the course topics is scalability. (This issue will be highlighted in the Kubernetes component of the tutorial as one of the major benefits of Kubernetes is its ability to scale). 

This tutorial will get the student thinking small by setting up basic environments so that foundational knowledge is achieved.

 The tutorial will then scale their knowledge up with an example use case. This will take what the student has done and explain that basically the same thing is done within major tech companies to scale/ provision development/testing environments on a large level, hopefully, this will give the student a sense of satisfaction. Additionally, after this tutorial is complete, Sashi and I aim to integrate these technologies into our own/future software development projects.

### CODE REVIEW

**Comment by gluckzhang** [comment]
Hi @Nick-Steele , I think the proposal is well written, thank you! Before merging the PR, you only to remove unrelated files (`contributions/covid19/nsteele-mhud/README.md.txt` and `contributions/essay/NickSteele-HelalUddin/README.md.txt`).

If those two tasks have not been registered, you could submit them in separate PRs. Don't forget to change the extension name to `.md` from `.txt` :)

**Comment by gluckzhang** [comment]
Hi @Nick-Steele , thanks! Another issue mentioned by Benoit this morning: could you also add your names in the `README`, before the email addresses?

**Comment by Nick-Steele** [comment]
> Hi @Nick-Steele , thanks! Another issue mentioned by Benoit this morning: could you also add your names in the `README`, before the email addresses?

Sorry, I tuned in late, I have added our names to to readme

**Comment by gluckzhang** [comment]
Perfect, the PR has been merged. Thanks @Nick-Steele

**Pull request merged**
