### PR TITLE
Executable Tutorial Submission

### PR DESCRIPTION
**Pull request by FelixFonteneau**
# Using the Clojure library AWS-api to access AWS services  

## Members

Félix Fonteneau, felixfon@kth.se (github username: [FelixFonteneau](https://github.com/FelixFonteneau))

Hilaire Bouaddi, @Hilaire-Bouaddi bouaddi@kth.se (github username: [Hilaire-Bouaddi](https://github.com/Hilaire-Bouaddi))

## Proposal

The functional programming language Clojure allows easy execution of scripts with its built-in REPL. The library AWS-api makes it easy to use the AWS tools from Clojure. AWS APIs operations are described in data that can be used recursively, this makes AWS very well suited for a fundamentally functional programming language such as Clojure. Combined with Clojure, this library is a powerful alternative to AWS CLI and bash scripts to access AWS tools. In this executable tutorial, we would explain how to use the library to access AWS Services. 

## Submission

Here is our [submission](https://www.katacoda.com/felix-f/scenarios/clojure-aws-api) using Katacoda.

## Feedback

We would appreciate feedback on this executable tutorial. However, we did not found any team willing to do it, is it possible to provide one? Thanks in advance!

## Aimed grades

In this tutorial, we aimed for the following criteria:

|                                             | Yes | No | Remarkable |
|-------------------------------------------- | ----|----|-------------|
|The TA can successfully execute all the commands of the tutorial (mandatory) | ✅Yes | No | ✅In the browser |
|If local execution, runs on Linux | ✅Yes | No | ✅Easy to set up and run  |
|The tutorial gives enough background | ✅Yes | No | Comprehensive background |
|The tutorial is easy to follow  | ✅Yes | No | ✅Well documented |
|The tutorial is original, no such tutorial exists on the web | ✅Yes | No | ✅The teaching team never heard about it |
|The tutorial contains easter eggs | Yes | No | Subtle and fun |
|The tutorial is successful (attracts comments and success) | ✅Yes | No | Lively discussion |
|The language is correct | ✅Yes | No | Interesting narrative  |

### CODE REVIEW

**Comment by FelixFonteneau** [comment]
@khaes-kth @cesarsotovalero @Deee92 Is it possible to have a feedback/review please? :)

**Comment by khesoem** [comment]
Hi @FelixEder ,

I'll send you some feedback soon.

**Comment by FelixEder** [comment]
@khaes-kth Wrong Felix, I took this course two years ago :D 
@FelixFonteneau tagging you so you don't miss this comment :)

**Comment by khesoem** [comment]
:))

Thanks @FelixEder. Many people took this course and appear in GH suggestions.

**Comment by khesoem** [comment]
Here is my feedback:

Overall, very useful tutorial. Also, the scenario you have chosen is short but informative enough. The main problem is that some points are not explained enough.

# Step-by-Step

## Introduction

Please give a bit more information about the context. What is Clojure? How does it compare to similar tools? What is REPL? What is even AWS?

## Step 1

What is Leiningen? Why do we need it?

## Step 2

> Several dependencies are needed,

Please make it clear what kind of dependencies you are talking about. Dependencies for what exactly? For Clojure, Leiningen, aws-api? Make 

## Step 3

> We will use the IAM (Identity and Access Management) service

What is it? Why do we use it?

> You should be able to see user information in JSON.

Please explain what information this json includes. What are the keys and values?

## Step 4

> Usage

Please explain the commands one by one.

> we need to parse it with a slurp for instance

What is `slurp`?

> We can summarize all the previous code in our main function:

Please explain which part represents which step. It is kinda clear, but it is always better to be even more clear.

**Comment by FelixFonteneau** [comment]
Thanks for the feedback, it's true that we have provided information for people initiated to Clojure. We will update some context and information soon! :)

**Comment by FelixFonteneau** [comment]
@khaes-kth done! You can see the updated tutorial [here](https://www.katacoda.com/felix-f/scenarios/clojure-aws-api).

**Pull request merged**
