### PR TITLE
Feedback submission

### PR DESCRIPTION
**Pull request by IfyUrama**
New pull-request to resubmit feedback on essay draft #1023.

### CODE REVIEW

**Comment by khesoem** [comment]
@IfyUrama Please add a link to your feedback comment in the readme.

**Comment by IfyUrama** [comment]
Hi, @khaes-kth
I have added link to my feedback comment in the README.md file.

**Comment by khesoem** [comment]
Hi @IfyUrama 

Thanks for that. But actually what had in mind was link to where you have sent your feedback to the feedback receivers. Like [this one](https://github.com/KTH/devops-course/pull/1355#issuecomment-827839158).

**Comment by IfyUrama** [comment]
Hi @khaes-kth,

It was in the closed PR. Here is the  [Link ](https://github.com/KTH/devops-course/pull/1023)
Link to closed PR. [Closed PR](https://github.com/KTH/devops-course/pull/1392)

**Comment by khesoem** [comment]
Fine. Actually, you were supposed to write the feedback in a PR comment, but I do not see a comment including the content of your feedback. As I understand, you have just referred to your feedback submission here. I cannot find the content of your feedback in the referred PR.

We want to make sure that the feedback receiver has read your feedback. Do you have some evidence for that?

**Comment by khesoem** [comment]
I read your comment in #1023. Although it is not how you were supposed to send the feedback, it is fine. I merged this PR.

**Comment by IfyUrama** [comment]
Ok, thanks

**Pull request merged**
