### PR TITLE
Executable Tutorial: Building a CI/CD Pipeline for a small frontend in a Kubernetes Cluster using Terraform

### PR DESCRIPTION
**Pull request by Internet-Person-IP**
# Executable Tutorial: Building a CI/CD Pipeline for a small frontend in a Kubernetes Cluster using Terraform

## Members

Taqui - taqui@kth.se
GitHub: [Internet-Person-IP](https://github.com/Internet-Person-IP)

## Proposal
I want to create an Executable Tutorial for creating a CI/CD pipeline for a Kubernetes Cluster using Terraform. The frontend will be super simple with a counter and click function.

The current structure of the tutorial will be creating a terraform template that does this:

- Creating the initial frontend, set up frontend with simple tests
- Creating a small cluster
- Containerizing the frontend
- Deploying the frontend to a small pod
- Creating the CI/CD pipeline
- Make changes to the frontend and actually push it to master
- Check that the CI/CD pipeline works correctly and then make sure that the deployed website works correctly

### CODE REVIEW

**Comment by khesoem** [comment]
Hi @Internet-Person-IP,

Can you add some information about how you want to create your tutorial? Katacoda or ...?

**Comment by thestar19** [comment]
I would like to give feedback on this #1225.

**Comment by Internet-Person-IP** [comment]
@khaes-kth Hello, small update I added a member to this proposal and regarding how we want to create the tutorial, we are thinking about doing it in katacoda or as a medium article for creating this tutorial depending on which one fits our proposal the best.

**Comment by khesoem** [comment]
@Internet-Person-IP
Now that you have added a new member, you should change the folder name of your proposal as well.

**Comment by Internet-Person-IP** [comment]
@khaes-kth the folder name should be changed as well now.

**Comment by monperrus** [comment]
@kun please rename the folder with your KTH username which is "kunwu"

**Pull request merged**
