### PR TITLE
Final Submission Essay: Agile and Devops

### PR DESCRIPTION
**Pull request by Linnea55**
# Assignment Proposal

## Title

Working with DevOps and Agile together

## Names and KTH ID
  - Linnea Hagman (lhagm@kth.se)
 
## Deadline

Task 4

## Category

Essay

## Description

Planned headings (wording and order might change):

Introduction
What is Agile?
What is DevOps?
How do they complement each other (to get a better quality of service delivered)?
How can agile and devops be used successfully together?
What are the challenges of using Devops and agile together? 
Conclusion

### CODE REVIEW

**Comment by valdimarb13** [comment]
# Feedback on Working with Agile and DevOps together
This essay begins with an introduction to the concepts of Agile and DevOps and then provides a more thorough analysis on how these concepts are connected. Finally, the essay describes how these concepts can work in tandem and how DevOps can make up for the weaknesses of Agile.

## High level strengths and weaknesses
### Strengths
•	The overall structure of the essay is impeccable, if a question arises in one section it usually answered in the next as a result the progression between sections feels natural
•	The core concepts of the essay, Agile and DevOps are explained very concisely at the very beginning offering a strong foundation for the rest of the work
•	The citations are very thorough
### Weaknesses
•	Sometimes jargon is used that assumes the reader is familiar with Software Development methodologies
•	Occasional grammatical errors
## Additional comments
### 1.	Introduction
The introduction serves it purpose well offering an overview of what is to come. However, the main concepts addressed in the paper are introduced as “buzzwords”. 
“The glory days of the Waterfall methods are over and has been replaced with the buzzwords Agile and Devops”.
This immediately makes the reader doubt the validity and relevance of the methodologies before they are properly introduced. The essay goes on to contradict this initial assumption by thoroughly detailing the purpose of the methodologies and pointing out that they have in fact been in use for a long time.

###  2.	Background
This section offers some background information on DevOps and Agile. It is quite well written and succinct. Overall, this section is strong. Still, the introduction the paper mentions earlier software development models such as the Waterfall model. A short explanation of these models and their shortcomings might offer some insight into the inception of Agile methodologies.
###  3.	How do Agile and DevOps complement each other
After describing the general concepts this section explores how they relate to one another. The section is quite convincing that DevOps can indeed make up for some of the problems encountered in Agile. However, the concept of cross-functional teams is brought up as a central motivation for the unification of the methodologies. This could be expanded upon further and is a bit difficult to follow.
### 4.	How can Agile and DevOps be used successfully together 
This section explains the union of Agile and DevOps in more practical terms, in what forms it can be implemented and how it can work at various levels of automation. The idea that responsibility goes down and collaboration increases with automation is quite interesting. There are some strange word choices in this section such as “human skills”, one might wonder where the line between a human and non-human skill is drawn. Also, the concept of hard skills is partly explained as “performing well”, without context this is perhaps a bit too broad.
### 5.	What are the challenges of using DevOps and Agile together
This section explains that these concepts are evolving over time and cannot be viewed as a quick-fix to every organizational problem. The precise meaning of “recruitment gap” is a bit unclear, is it a gap in what is taught in schools and what is expected in professional environments or a problem of neglect in job advertisements?
### 6.	Discussion and Conclusion 
 This section nicely ties together the contents of the essay 

### Additional material
It’s interesting to look at some concrete examples of how organizations have implemented the Agile-DevOps approach and their experiences:
https://tdwi.org/articles/2021/01/15/biz-all-apply-devops-mindset-to-manage-people-data.aspx

https://www.sciencedirect.com/science/article/pii/S0164121219301517?casa_token=QnLZa7dnGPYAAAAA:zIY2tLei-6sFGwX9IoC1QLd0IasNsNAVGa5ObZDPaHRvRrTfKdV2T8lHPEU6wOsMh6zfIisdlgPz

**Comment by Linnea55** [comment]
Hi @valdimarb13 and the TAs @khaes-kth, @javierron , @cesarsotovalero, @Deee92,

thank you for the feedback, but it came a bit unexpected since I submitted my final submission of the essay yesterday evening. Therefore I'm unsure on how I should act upon the feedback.

**Comment by khesoem** [comment]
@Linnea55 : Since the final submission is not merged yet, you have time to improve your work based on this feedback. In fact, that's the point of sending the feedback as a comment to the submission PR.

**Comment by Linnea55** [comment]
@khaes-kth How much time do I have to improve my work?

**Comment by Linnea55** [comment]
Hi @khaes-kth,

an updated version of my essay based on the feedback is now available. My original essay, which was submitted before the deadline is still available.

**Comment by khesoem** [comment]
Great! Can you remove the old version (not-revised) version?

**Comment by khesoem** [comment]
The old version is not required.

**Comment by Linnea55** [comment]
@khaes-kth I have deleted the old version now.

**Pull request merged**
