### PR TITLE
Essay proposal: Future of Devops

### PR DESCRIPTION
**Pull request by mustafamusse**
# Assignment Proposal

## Title
The future of Devops

## Names and KTH ID
  - Mustafa Ali (Mustali@kth.se )
  - Noah Rahimzadagan (rahimz@kth.se)

## Deadline
Task 4

## Category
Essay

## Description
The idea of this essay is to explain the current status of the devops life cycle and explore inevitable or likely future changes to the Devops landscape. The DevOps approach is very effective in maintaining, deploying and servicing software. In the current day it has many advantages over the old school of software development. It is easy to oversee and maintain the code. But how will the landscape change in the future? 

The essay will explore how other, not yet implemented technologies could potentially be a part of the DevOps process in the future. The potential technologies that will be explored is automatic software repair in the CI stage, automatization of the CI/CD process with the help of AI among others.

### CODE REVIEW

**Comment by javierron** [comment]
@mustafamusse Thanks for the proposal!

**Comment by lnsandnkth** [comment]
Hej you two @noahra and @mustafamusse, could I review your essay as soon as it is done?

**Comment by noahra** [comment]
> Hej you two @noahra and @mustafamusse, could I review your essay as soon as it is done?

Yeah! I have already sent what we have written by e-mail! Hope you can provide some good feedback! :)

**Comment by lnsandnkth** [comment]
# Feedback
## High level
- **Strengths:**
  - You cover quite a range within DevOps, which I think is quite impressive for such a short essay
  - Precise descriptions of subtopics that give a good overview of the presented technologies (like 3.1, 4.1, 4.2)
  - Mentioning important areas in DevOps that you don't usually think of (like security)
- **Weaknesses:**
  - Some multi-clause sentences should be shortened for a better structure and to make the sentences easier to understand
  - You probably haven't spell checked your essay yet, I provided some corrections here
  - Some sentences are far too attention grabbing and should at least contain some scepticism about what they are describing
  - Weak or no introductions and transitions
  - You don't mention downsides of what you present, that may be though because of the limited size of the essay and the amount of topics you cover
  - The Introduction and the topic AIOps end abruptly (are you still working on them?)

## Things to improve on
- **Misspellings and commas:**
  - 1 Introduction: 
    - costumers &rarr; customers, 
    - developments a deployment &rarr; development, deployment
    - waterfall method &rarr; waterfall methodology (or waterfall model)
  - 2 Background:
    - engineers and making &rarr; engineers and makes
    - realises &rarr; realizes
    - av DevOps &rarr; of DevOps
    - tools and disciplines &rarr; tools, and disciplines
  - 3 Continuous Integration:
    - merged to &rarr; merged into
    - arised &rarr; arisen
  - 3.1 Automatic repair:
    - to identify resolve bugs &rarr; to identify and resolve bugs
    - which performs computational &rarr; which performs a computational
    - is to rollback &rarr; is to roll back
    - the bug arised &rarr; the bug arose
  - 3.2 Repairnator:
    - The third ~~and~~ and last
    - is to provid &rarr; is to provide
    - data for ~~future~~ future program
    - during five different occasions &rarr; on five different occasions
    - each others patch fixes. &rarr; each other's patch fixes.
  - 4 Code Reviews:
    - Code reviews enables the flow &rarr; Code reviews enable the flow
  - 4.1 AI Code Reviewers
    - It is no signifcant &rarr; It is no significant
    - a place in the ~~the~~ DevOps
    - By implemented an AI &rarr; By implementing an AI
  - 4.2 Codeguru
    - one can almost view ~~the~~ Codeguru
    - deployed in the continous integration of a work flow, and it &rarr; deployed in the continuous integration of a workflow, it
  - 4.3 Future of Code Reviews
    - reviews by AI agents has &rarr; reviews by AI agents have
    - For the future there may very well be more tools than the Codeguru &rarr; In the future, there may be more tools than Codeguru
  - 5 Security
    - attacks occuring &rarr; attacks occurring
    - deployment stage, which means, after &rarr; deployment stage, which means, that after
    - will perform test &rarr will perform tests
    - It is in fact a bottle neck, since &rarr; It is in fact a bottleneck since 
  - 5.1 DevSecOps
    - responsibilities for the developer &rarr; responsibilities to the developer

<br>

- **Rewrite sentences for more clarity or to remove mistakes:**
  - 1 Introduction: 
    - First sentence &rarr; "DevOps stands for development and operations and combines practices and tools that
      specialize in delivering applications and services to customers faster and more reliable than traditional
      software development tools."
    - Second sentence &rarr; "DevOps was first introduced as a concept back in 2007, when the
      separation between software development and IT operations raised inefficiencies."
  - 2 Background:
    - "Slowly but surely, DevOps was not just an idea anymore ~~but slowly~~, ..."
    - "~~DevOps has been around since 2007, and~~ When reading"
    - to system in a dedicated brought with it &rarr; to system in a dedicated ?way?, brought with it
    - 2nd to last sentence rewrite to "... that the Software Engineering landscape will change and especially DevOps will change even more."
  - 4 Code reviews:
    - "... many companies perform a code review."
    - "Code reviews enable the flow of knowledge ~~to pour~~ between ~~the metaphorical cups of the~~ different developers."
    - "Another issue one easily can deduce, that is due to code reviews is the fear of novice developers of trying something daring, and effectively become ridiculed by their peers or more experienced
      developers." I cannot figure out what you want to say with this. Do you mean that novice developers are afraid of their peers and an AI-code-reviewer is the solution? Definitely rewrite it.
    - less vulnerable to group think &rarr; less vulnerable to peer pressure
  - 5 Security
    - ~~Clearly,~~ many software engineering companies
    - "This effectively gives additional responsibilities to the developer, thus she needs to be more mindful of security when creating software."
  - 6 AIOps:
    - "To have an optimal user experience many teams often are focused on fixing issues related to the user
      experiences and emergencies rather than spending that time innovating and developing applications
      and services to costumers." That sentence is quite bloated, shorten it

<br><br>
- **Additional things to improve on**
  - 1 Introduction
    - The introduction ends abruptly and misses what DevOps' upside is, to eg. the waterfall model.
    - The introduction fails to inform the reader about what DevOps is and assumes that the reader already knows all about it.
    - The introduction should also be about what you are going to present in your essay, not just what DevOps is
  - 2 Background:
    - I am not quite sure about the first sentence, it seems a bit too enthusiastic and lets the reader assume that DevOps is a perfect methodology without any downsides.
  - 3 Continuous Integration:
    - There should be an introductory sentence that states that the subtopics are new state of the art technologies and not in the status quo of DevOps since 2007
    - Missing quote or evidence: "Sapienz has proved to be very effective."
    - You should reference figure 1 in one of your paragraphs, otherwise it just sits there with little purpose
    - You could provide a figure for the Repairnator workflow like you did for SapFix. Like this one https://www.researchgate.net/profile/Martin-Monperrus/publication/325728100/figure/fig1/AS:636870224519168@1528853102437/The-overview-workflow-of-the-Repairnator-program-repair-bot.png
    - Shouldn't Repairnator be a sub-paragraph of Automatic repair like 3.1.2?
    - "Astoundingly, the Repairnator has thus far fooled human developers on GitHub" how has it fooled human developers? State that they thought it was a human account.
  - 4 Code reviews:
    - "Code reviews enables the flow of knowledge to pour between the metaphorical cups of the different developers." This sentence seems a bit too sensational
    - "It is no signifcant scientific discovery that humans are error prone." Maybe find another way of saying this or scratch it.
  - 5 Security:
    - Rewrite the first sentence so that it mentions that also the DevOps chain is being targeted by cyber attacks.
  - 6 AIOps:
    - This paragraph also ends abruptly, how can AIOps automate fixing bugs and help communitcation between teams. Is there already a solution out there? And how does this topic differ from AI Code Reviewers or Automatic repair.

**Pull request merged**
