### PR TITLE
feat: essay 3 proposal 

### PR DESCRIPTION
**Pull request by iabdelkareem**
**The pull request must both contain a README.md and have description following this template:**

**The README.md file must be located in the directory**:

`contributions/iaiab/task-2/README.md`

# Assignment Proposal

## Title

History of Containers, Before Docker and After.

## Names and KTH ID

  - Ibrahim Abdelkareem (iaiab@kth.se)

## Deadline

- Task 3

## Category

- Essay

## Description

The idea of containers has been around for many years. However, it started becoming popular when Docker was founded and changed the landscape of software development & deployment. 

In this essay, I'll talk about the history of containers. First, I'll briefly explain how it all started with the idea of Virtualization at IBM in the 1960s, then in the 1970s when the concept of process isolation in Unix systems came to light up until the early 2000s when process containers (cgroups)  introduced by Google and how it helped them to manage their infrastructure. Then Linux Containers (LXC) in the late 2000s, which is considered the first most-complete implementation of container manager until Docker came and became a game-changer technology for DevOps and how they donated Containerd to the CloudNativeFoundation. Then I'll talk about container orchestration and the rise of Kubernetes.

In this history journey I'll explain how in every step these technologies helped DevOps to better manage their infrastructure and how it helped developers to deploy and manage their applications. I'll discuss also how application deployment is today with Kuberenetes and Cloud Native solutions.

**Relevance**

Relevant to containers.

### CODE REVIEW

**Comment by iabdelkareem** [comment]
@javierron  I pushed the essay in the same PR. Apologies for doing this after the deadline hope it can be accepted.

**Comment by javierron** [comment]
Hello @iabdelkareem. Thanks for the proposal, unfortunately we cannot accept it for two reasons:
1. You have already submitted an Essay task. Per the rules of the course, you are only allowed to do one task per category. Being "demo" and "presentation" mandatory.
1. The topic has been discussed in a similar essay before. See [this contribution](https://github.com/KTH/devops-course/blob/2022/contributions/essay/bonato/Docker%20containers%20from%201979%20till%20today.pdf).

**Comment by javierron** [comment]
@iabdelkareem To pass the course, you still need to propose and deliver both "demo" and "presentation" tasks. Since there is only one last chance to do so on week 9, I reccommend you to: (1) open the corresponding PR proposals, and (2) contact the professors asking for an exception to present both tasks on week 9.

**Comment by iabdelkareem** [comment]
@javierron thank you for the feedback. I submitted a proposal for [feedback task](https://github.com/KTH/devops-course/pull/2341) and will submit soon 2 other PRs for presentation and demo and contact the professor.

**Pull request closed without merging**
