### PR TITLE
[Submission] Demo: Automatically publishing tested Node.js packages on npm with Github Actions 

### PR DESCRIPTION
**Pull request by oscaralmqvist**
Submission for https://github.com/KTH/devops-course/pull/1152

### CODE REVIEW

**Comment by oscaralmqvist** [comment]
Ping @cesarsotovalero as you accepted my proposal 😀

**Comment by vickstrom** [comment]
I have always wondered how you published npm packages! And you even automated the process, great video! The content and the structure is great. I have a few suggestions that would make the video "flow" more. 

- There is a lot of movement in the your video, however the start and the end is two static images. For example at the end, show only one keypoint and transition the next one would make these sections feel more "alive".  

- I like the jump-cuts at the start, so less time is spent on clicking on links. However, I have never added a Action Secret and got a bit lost when you jump cutted to that section. I would recommend either showing the process of navigating to that page, or maybe provide an URL in the description.

Otherwise, this was a great video! Have a good one.

**Comment by MDRezaulHasan** [comment]
Great Work.

1. Voice cover is clear
2. Nice presentation
3. Clear code concept
4. Interesting and realistic idea for automated package
Improvements:
Avoid first moving. It will destruct the flow.

**Comment by evkade** [comment]
**Demo Feedback**

Overall really useful, interesting, clear and good demo! 

_Positive_ 

- The video is easy to follow and has a very interesting and relevant subject
- The instructions are clear
- The repo looks nice
- Nice that you explain what the code does as you write it
- Really nice takeaway slide! 

_Negative_
- The video is a little bit blurry for me at times (when you show the browser especially) 
- Sometimes it feels like the video is going a little bit fast 
- There is not so much motivation of how the subject is related to devops 
- Maybe the readme of the repo could have a little bit more information

**Comment by oskstr** [comment]
### Feedback

Really interesting demo. I like the topic. The voice over and subtitles were good. 

Sometimes the text is probably a bit too small. I mainly thinking of when you are showing GitHub and the terminal window. You could perhaps use the zoom functionality in the browser to have less whitespace and either use a larger font in your terminal or simply use the integrated terminal in VS Code (you can even default to WSL and open with a shortcut). 

I liked that the voice over sounded very calm and that you didn't rush through anything. That made it easy to follow. 👍

**Comment by kittytinythai** [comment]
## Feedback
A very interesting and informative demo! I've listed the strengths and a few suggestions for improvement below. Otherwise, good job 👍 
### Strengths 
- Informative introduction before starting the demo
- Clear instructions
- Narrative pace was good and makes it easy to follow
- Nice take-home message in the ending!
### Suggestions for improvement
- The video quality is a bit blurry when viewing Github pages, can this be fixed? Maybe zoom in a bit in the browser or change the Github to dark mode
- [personal opinion] I thought it was a bit distracting when the singer in the background music began to sing every now and then, maybe change to something that's just some melody?

**Comment by majate** [comment]
Great demo! The video content was easy to understand, the speed was good, the voice over was clear and the subtitles correct. In addition, the editing had high quality, and the background music and the included slides were small details that increased the overall feel. I don't really have any problems to pinpoint.

One thing that could increase the watching experience, would be to highlight relevant parts on the screen when there is something specific that we should look at. For instance at time stamp 2:37, you mention that we can see that the publish workflow is triggered and you show the GitHub Actions page. If you are unfamiliar with GitHub Actions, it can be hard to know where on the screen you should look to see that the workflow is indeed running. In that case, highlighting the specific workflow in the list (e.g. by drawing an arrow, drawing a square, or blurring everything else) would make it easier to follow along.

**Pull request merged**
