### PR TITLE
Essay Proposal: challanges and applications for MLOps

### PR DESCRIPTION
**Pull request by linus1996**
# Assignment Proposal
## Title
Challanges and applications of MLOps

## Names and KTH ID
Linus Below Blomkvist (libl@kth.se)

## Deadline
Task 4

## Category
Essay

## Description
The purpose of this essay is to present the challanges of MLOps and also  
the opportunities where MLOps can be applied and improv areas such as efficiency, and risk reduction
with the use of Machine Learning and AI

### CODE REVIEW

**Comment by khesoem** [comment]
This PR is changing two files (https://github.com/KTH/devops-course/pull/1936/files). It should only add your readme and not change anything else. You may need to rebase to fix the issue.

**Comment by linus1996** [comment]
@khaes-kth ok. Can I go ahead and start with the essay?

**Comment by linus1996** [comment]
@khaes-kth I think that is has been rebased now

**Comment by khesoem** [comment]
@linus1996 Your PR is still removing `contributions/essay/README.md` file. The easiest (but not best) way to fix it: you can remove your old fork, refork the repo, add your own readme, create a new PR, remove this old PR, and mention me in your new PR.

**Pull request merged**
