### PR TITLE
Executable Tutorial proposal: Integrate DataDog in existing app

### PR DESCRIPTION
**Pull request by evkade**

### CODE REVIEW

**Comment by khesoem** [comment]
Hi @evkade ,
As I understand, you have added two topics in this single PR. Can you please close this PR and create two separate PRs each including one single topic proposal?

**Comment by evkade** [comment]
Hi! Sorry I think the other file slipped through. Fixed it now!

**Review by khesoem — APPROVED** [review]
LGTM!

**Comment by majate** [comment]
@Sebberh and I will give feedback for this task and our feedback PR id is #1071

**Comment by evkade** [comment]
The tutorial is ready for review at https://www.katacoda.com/andreeva/scenarios/datadog-tutorial ! :)

**Pull request merged**
