### PR TITLE
submit essay

### PR DESCRIPTION
**Pull request by TAOFOR4**

### CODE REVIEW

**Comment by javierron** [comment]
Hello @TAOFOR4. thanks for the submission.

**Comment by AliAsbai** [comment]
# Feedback from  Ali Asbai (asbai@kth.se) and David Ljunggren (dljungg@kth.se)

_We certify that generative AI, incl. ChatGPT has not been used to write this essay. Using generative AI without permission is considered academic misconduct._

## 1    High-level Strengths

One primary strength of the essay is its structure with regard to sections and subsections. The choice of sections and subsections seems appropriate, and the subsections themselves are rich in information. We also appreciate the use of images in the theoretical sections.

The conclusion-chapter neatly summarizes the key takeaways from the essay.

## 2    High-level Weakness

The primary weakness of the work is the absence of references where it is appropriate (for details about this, read the next section of this document). Another big weakness is that the introduction fails to introduce the reader to what the essay aims to answer. As a reader, we expect to be introduced to some sort of problem or research question early on - it simply is never introduced in this essay.

Another main drawback of the essay is the lack of an abstract that summarizes the work.

The language in the essay could be looked over in certain parts. While we found the text readable and understandable as a whole, certain sentences could be improved in their accuracy and focus.

## 3    Feedback

_In this section, we plan to give more specific feedback._

As already mentioned, it would be more comprehensible if the introduction included some sort of problem statement or at least a purpose subsection. This would allow the reader to understand what he or she is about to read. The title itself is a bit of a pointer as to what the work will be about, but that is about it. 

When it comes to references, we would like to give some concrete examples. In chapter 2, only subsection 2 _Security challenges in CI/CD pipelines_ has references. We think it is suitable, whenever giving a theoretical background, to cite a credible source. To further specify this with an example, see the following paragraph's absence of references. The final citation is ours.

_The continuous integration/continuous delivery (CI/CD) pipeline is an agile
DevOps workflow based on the idea of a frequent and reliable software delivery process. In a CI/CD pipeline, there are four phases: Build, Test, Deliver, and Deploy, which are all deployed continuously in an endless loop. Different automated workflows can be integrated into different parts of the process, and different parts of the pipeline, which helps DevOps teams to quickly, continuously, and reliably deliver the software (Xiong and Löfberg)._

Section 4.1 introduces the general benefits of using HIDS in CI/CD pipelines. The section discusses the general benefits of three separate issues or arguments, as they were called in the essay. This section is highly informative, and as readers, we found it very interesting. But at the same time, we found the section a bit hard to follow at times since each argument contained a lot of branches that could alter or negate the benefits of using HIDS. We believe that a more easily understandable way of writing this section would add a short example scenario for each of the three arguments. This way, the benefits of using HIDS for the arguments would be easier to follow.

We also believe the conclusion of the essay could use a reflective part. Where the authors could reflect on the method of their work or parts of their work that exceeded their expectations.

**Comment by allandao** [comment]
# Feedback

Feedback for the Essay "How host-based intrusion detection systems can improve the security of CI/CD pipelines" by Löfberg and Xiong.
https://github.com/KTH/devops-course/tree/2023/contributions/essay/nilslof-taox

Feedback by Allan and Jun, @allandao and @Letuvertia respectively

I/We certify that generative AI, incl. ChatGPT, has not been used to write this feedback. Using generative AI without permission is considered academic misconduct.

Number of words: ~881

---

## Overview

We were interested in exploring and providing feedback on this particular essay in order to learn more about the specifics of the notion of host-based intrusion detection systems (HIDS), which is introduced in the essay. The issue at hand is highly relevant to DevOps and is a modern and again, relevant issue to pipelines across a diverse range of projects, teams, and organizations. With this in mind, the feedback presented will feature an exploration of the different sections of the paper, with thoughts on how it all comes together to introduce and promote technology that may be impactful to one's day-to-day work, but perhaps not something that a rather inexperienced developer knows of, emphasizing the essay's significance.

### High Level Feedback
Areas of Strengths:
- Interesting and relevant topic
- Well structured, with the introduction to CI/CD pipelines offering the baseline knowledge needed as well as definitions for key terms
- Example tool provided (actionable)
- Overall, a strong foundation

Areas of Improvement:
- Stronger citations, particularly in CI/CD section
- Increased integration of diagrams and/or listings could be beneficial
- Slight expansion of available examples of intrusion and vulnerabilities
- Links to particular subsection references would be helpful
- More resources always appreciated

### Additional Materials
Some interesting resources that complement the information found in the paper.
- A deeper dive into OSSEC https://www.sans.org/white-papers/39565/
- More information about intrusion https://www.sans.org/white-papers/343/

### Conclusion
The essay is well written to be self-contained and informative, and again, on an interesting and relevant topics. Key ideas related to improvement are generally more particular quality of life additions, such as more visuals to offer a better idea of what the suggested tools do and look like. On this previous point, we see a key aspect of the paper: actionable steps through two different pieces of software and a recognition that the software is only complementary to other security tooling, given the analysis from the challenges and limitations mentioned. As for the course rubric, it holds to many of the required points, although the essay could be more direct in terms of the language used to express points such as how recent (sota or state of the art) the issue and discussed software is. Overall, a fun and quite a comprehensive read!

---

## A Deeper Dive
Examining each section.

### 1 Introduction
A short and concise introduction gives a motivation of the essay. However, some keywords or short descriptions of the potential vulnerability and attacks can be mentioned to let readers know what exact problem is HIDS trying to solve.

We might to change "most significant companies" to "most significant projects," given how prevalent CI/CD pipelines are.

May be helpful to specify outside malicious actors

### 2 CI/CD Pipelines
Great section to self-containerize the essay, brief and clear. Re-emphasizing DevOps here may be helpful.
The security challenges can further distinguish the logical error and security error and why the CI/CD pipeline responsible for these errors. Finally, it is not clear that how the figure 2 and the statement "we are currently experiencing a global uptick in cyber attacks in general" are related to the error mentioned above.

The listing of three prevalent security issues is well-structured.
However it's not clear why these attacks are more likely to happen in the automated process of CI/CD but not the traditional development.
For example, the unverified malicious frameworks are also likely to be used when the developer manually builds the software.

It is especially important to offer source material for the CI/CD information, as well as the related diagram (similar to the chart provided with data up 2021, and it is a bit blurry).

### 3 Overview
Effective introduction to HIDS, but it would be helpful to re-emphasize the distinction between the two different forms of HIDS that have been in development and usage.

### 4 Benefits
This section discussed how HIDS can solve the 3 listed security issues in subsection 2.2. The introduction to OOSEC and Qualys is well referenced and provides details of the important features of the system. The authors also argue how these features solve the security issues.

Offering an example of why a HIDS make require significant ongoing work would be helpful.

"The third argument, outlined in subsection 2.2.3 entailed the fast-paced environ-
ment in which CI/CD pipelines live." This quote relates to the detail of adding links that was mentioned in the overview.

### 5 Limitations and Challenges
A fair section that promotes issues both related to team culture (towards the end) and technical issues.
The limitations mentioned here are important and concise. It's great that the authors further give the term NIDS for reader who are interested in network attacks, and it seems to be a great topic for future works.
Great paragraph!

### 6 Conclusion
"However, they [HIDS] are not an all-encompassing solution
and should be used in conjunction with other security measures to create a
multi-layered security to the CI/CD pipeline." It could be helpful to offer examples of other security measures to clearly indicate what HIDS is lacking. For example, if static analysis tools would be complementary.

Finally, expanded reflection regarding the authors own past experiences influencing why they chose this topic would be valuable motivation as another example of why HIDS is important and motivation for the essay. A interesting read, thanks.

**Comment by allandao** [comment]
Commenting on behalf of Jun, offering his insights:

## A Deeper Dive
Examining each section.

### 1 Introduction
A short and concise introduction gives a motivation of the essay. However, some keywords or short descriptions of the potential vulnerability and attacks can be mentioned to let readers know what exact problem is HIDS trying to solve.

### 2 CI/CD Pipelines
Great section to self-containerize the essay. The introduction to CI/CD is brief and clear. 
The securtiy challenges can further distinguish the logical error and security error and why is the CI/CD pipeline responsible for these errors.
It's not clear that how the figure 2 and the statement "we are currently experiencing a global uptick in cyber attacks in general" are related to the error mentioned above.

The listing of three prevalent security issues is well-structured.
However it's not clear why these attacks are more likely to happen in the automated process of CI/CD but not the traditional development.
For example, the unverified malicious frameworks are also likely to be used when the developer manually build the software.

### 3 Overview of Host-Based Intrusion Detection Systems
The section should be the main section but it's too brief and lack of technical details.
For example in the section 3.2.1, the elaboration of the most common intrusion events and their technical definitions are expected. It would also be appreciated if the author can give specific names of the most commonly used IDSs (preferably references and links) so that the readers who are interested in applying such system to their pipelines can have the resources to refer to.
In the section 3.2.2, the author compared the anomaly-based systems to the signatured-based one by pointing out the difference between machine learning techniques and ruled-based criteria.
However how machine learning is used here and why that makes it a better option for some situation is unclear.

### 4 Benefits of Using Host-Based Intrusion Detection Systems in CI/CD Pipelines
This section discussed how HIDS can solve the 3 listed security issues in subsection 2.2.
It's detailed and well written.
The introduction to OOSEC and Qualys is well referenced and provides details of the important features of the system. The authors also argue how these features solve the security issues.

### 5 Limitations and Challenges
The limitations mentioned here are important and concise. It's great that the authors further give the term NIDS for reader who are interested in network attacks, and it seems to be a great topic for future works. 
Great paragraph!

### 6 Conclusion
"However, they HIDS are not an all-encompassing solution
and should be used in conjunction with other security measures to create a multi-layered security to the CI/CD pipeline." It could be helpful to offer examples of other security measures to clearly indicate what HIDS is lacking.

**Comment by monperrus** [comment]
@allandao the task is meant to be teamwork, please merge your two separate feedbacks into a unique consolidated one. Thanks.

**Pull request merged**
