### PR TITLE
Submission of Demo: CI/CD Deployment using GitLab and AWS (#1022)

### PR DESCRIPTION
**Pull request by dmariel**
# Demo: CI/CD Deployment using GitLab and AWS

 ## Members
 - [Dina Lerjevik](https://github.com/dmariel) (lerjevik@kth.se)
 - [Carina Wickström](https://github.com/carinawic) (carinawi@kth.se)

## Submission

**The video is available [here](https://youtu.be/mGFS2zUL8mo).**

Description: Our video demo demonstrates how to create a CI/CD pipeline in GitLab for deploying a HTML-file to Amazon S3. Furthermore, we have chosen to include the creation of a custom GitLab Runner in our demo, which we believe distinguishes this video from other videos on the same topic.

Prerequisites: 
* GitLab account (https://about.gitlab.com)
* AWS account (https://aws.amazon.com/s3/) 

GitLab Documentation: https://about.gitlab.com/blog/2021/02/05/ci-deployment-and-environments/ 

YAML - Adapted from Documentation: https://gitlab.com/carinawi/gitlab-demo

## Grading criteria

We aim to fulfill the following criteria:

|                                             | Yes | No | Remarkable |
|-------------------------------------------- | ----|----|-------------|
|The demonstration is clearly motivated (why it matters for Devops?) | **Yes** | No | Relates to a hard problem |
|The demonstration is difficult to do | Yes | **No** | Relies on a non trivial infrastructure |
|The demonstration is original | Yes | **No** | The are less than 10 demos on the topic on Internet |
|The video is sublime (eg visually appealing) | **Yes** | No | **Excellent narrative** |
|The video contains an [easter egg](https://github.com/OrkoHunter/python-easter-eggs)* | **Yes** | No | **Related to the demo** |
|There is a code repo to run the demo  | **Yes** | No | Code repo with a solid readme |
|The video must contain subtitles which are clear and in proper English | **Yes** | No | **Clearly understandable voice over** |
|The video includes a take-home message | **Yes** | No | **Actionable takeaway** |

*Easter egg at 02:58 ([explanation](https://twitter.com/gitlab/status/1050008027649245184?s=20))

### CODE REVIEW

**Comment by khesoem** [comment]
Hi

Similar to your tutorial submission, this PR also has a merge conflict. Please fix it as soon as possible.

**Comment by dmariel** [comment]
@khaes-kth Hi! I believe it should be solved now

**Comment by Sebberh** [comment]
Very nice, +1 for hitting 3:00 exactly ;-) The vocal track was very clear and the image-quality was equally good. However, I did not understand exactly what S3 is and why it is used. This give context for what is shown but I understand if the time is too short for it to be added.
It's a nitpick but the video felt a little hectic, completely understandable with the time-limit though.

**Comment by Ackuq** [comment]
Very well done demo! It was very clear what was going on and easy to follow along. Good voice-over and editing.

I think it would be nice to add some comments about how this can later be used to serve this HTML file as a static website (and then maybe demo that as well, if it can be fit within the 3 min time limit). Maybe it is outside the scope of this demo and that is totally fine, but I think it would greater show the usability of using s3 and [does not need too much setup to do](https://docs.aws.amazon.com/AmazonS3/latest/userguide/WebsiteHosting.html).

**Comment by sfkwww** [comment]
Well made demo! The voice-over was very clear and the demo was fairly easy to follow. The visuals between each step were also nice and assisted with the overall presentation.
The video felt a little bit rushed but it didn't take away much from the demo.  I also noticed that I couldn't find a code repository for the demo, is that supposed to be included somewhere?

**Comment by damnePers** [comment]
# Feedback

Really good and clear demo. I'm impressed!

Good introduction explaining what is to come. This gives a good overview of what the demo is about with sufficient background and overall info. Maybe you could add that you have listed the different components used in the demo in your repo for more info.

The demo has a good step by step approach. This makes it very easy to follow along and the viewer can easily detect if they have missed something since you have a clear break for when you start doing something new. It also makes it very clear what it is you're doing throughout the demo. As a viewer you never lose track of what is going on. 

It would be nice to add an overview of all the steps in the beginning so the viewer knows what to expect. It could be nice to go over these at the end as well to get a quick recap of what the viewer has learned, but I understand that time is limited. At least you have this in your github repo which I would say is a good compromise. 

- Step 1: Good that you start from scratch.
- Step 2: Very clear and easy to see what you do all the time. Good that you explain the code in the .yml-file
- Step 3: This step is quite long, with many small, detailed things to do. Maybe it can be broken down further?
- Step 4: This step is clear and straightforward. Not much to say about it. 
- Step 5: This step seems quite complicated but you have really managed to make it clear.
- Step 6: Great that you end with how the pipeline works from start to finish and makes sure to show that it works!

The documentation and instructions in the readme are good as well. However, it would be nice if the instructions followed the steps of the demo, so that the viewer could easily find information of a step in case they didn’t quite understand it during the demo. 

The voice over is very fast, which is understandable given the strict time frame. Other than that, it is easy to understand and hear the voice over and the captions are correct as well. 

The graphics and video is also very clear and “good looking”.

**Comment by 8ar10der** [comment]
## Feedback
Yuehao Sui

### Overall, you are PRO!
* The speaker speaks at a good pace, with clear words and a good voice.
* The content is very clear and the font is the perfect size.
* The steps are as well organised and easy to follow.
* The background is detailed and relevant to DevOps.
* Enough detail and video in 3 minutes
* Nice BGM

### Possible improvements?
* It's a bit boring, could you try to add some elements that would grab the audience's attention, such as sound effects.

**Comment by yuxinmmmm** [comment]
# Feedback
## Overall
It is a really good and clear video demo.
## Good points
- The steps are very detailed.
- Perfectly on time.
- The voice is fast, but understandable with the subtitles.
- Actionable takeaway messages.
## Suggestions
- Since the voice has been fast, it will be better if there is no music to make me focus on the voice.

**Comment by carinawic** [comment]
Thank you all for your valuable feedback!

We intend to implement the following changes based on the feedback:

- Several people suggested that the purpose of S3 was not motivated, and what it can be used for futher. Therefore we will add a clickable link in the video called [”What is S3?”](https://docs.aws.amazon.com/AmazonS3/latest/userguide/Welcome.html) linking to the AWS S3 official documentation page.
- One feedback suggested that the repository link was not working, however we have checked this now and it seems to be working.
- The repo concerns the YAML coding part of the video, and therefore the repo is mentioned in that part of the video instead of the introduction.
- One suggestion mentioned that an overview was needed to show the steps of the video in advance. This will be done by including timestamps in the description as well as in the timeline of the youtube video.
-  Due to the time limitation we chose not to break down step 3 of the video. Instead we hope that the timestamps will prepare the viewer that this is a longer phase, and that the documentation will be enough to help the viewer.
- We did not understand the comment ”it would be nice if the instructions followed the steps of the demo”, perhaps @damnePers could kindly clarify this.
- For further clarification of the video content, we will add a README file in the gitlab repo.
- One suggestion mentioned that the music was redundant in the video. On the other hand, another suggestion mentioned that the video was slightly boring and that more sound effects should be added. Since these comments are contradictory, we decided to keep the music at a low volume.

**Pull request merged**
