### PR TITLE
Demo: Publishing a Java package to Maven Central using Github Actions

### PR DESCRIPTION
**Pull request by Ackuq**
# Video demo: Publishing a Java package to Maven Central using Github Actions

## Members

Axel Pettersson (axp@kth.se)
GitHub: [Ackuq](https://github.com/Ackuq)

Felix Seifert (fseifert@kth.se)
Github: [felix-seifert](https://github.com/felix-seifert)

## Proposal

In this demo we will show how to create a simple Java package and deploying it to Maven Central for distribution using Github Actions.

The action will:

-   run when commits are pushed to main branch
-   authenticate with Maven Central
-   use encrypted Github Secrets to securely handle authentication

### CODE REVIEW

**Comment by cesarsotovalero** [comment]
@Ackuq LGTM.
Go ahead!

**Review by cesarsotovalero — APPROVED** [review]

**Comment by fwallb** [comment]
Great demo, with useful content!

**Strengths**
- Good that you zoom in on the code when explaining.
- The way you insert code line by line is nice.
- The info button is a great feature.

**Weaknesses**
- The intro is short, maybe too short to understand, but the rest of the video made everything clearer. 
- The voiceover is a bit fast in some places, mostly at the start and end. I guess that the limited length made you focus on the actual content of the video.

**Comment by vladomit** [comment]
**Strengths:**
Interesting topic, really related to Devops
Focus on code


**Improvement:**
Give a clear summary at the beginning
Background music could make the video better




I know it's quite difficult to make these change now, especially to add the summary.
But overall very good job guys !

**Comment by johanmallobakken** [comment]
# Feedback

## Strengths

I like the topic, its interesting and has a lot of potential. 
The editing in general is done very well and the sped up code writing is cool.
You speak at a good pace.

## Improvements 
I would like to see a clearer structure on the video, its nice to know what will be covered and divide it into parts. 
I think a nice introduction with some graphics would make the video more appealing to watch.
When showing the action secrets for example it would be nice for a viewer to know where on Github this can be found.

In general not much to say! Great job :)

**Comment by andreaskth** [comment]
All in all an interesting video! As with everyone else, I know you were constrained by the 3 minute limit and that it will be hard to add anything to the video (without removing something else). My key advice would be to highlight important parts of the video (certain lines of code, etc), so the viewer knows what to look at, since the fast pace of the video (again, not your fault) can make it a bit disorienting otherwise.

**Watching the video and providing comments throughout:**

I like how you explain what Maven central is, in case the viewer is not familiar. Also good that you motivate why one wants to automate the process of publishing to this repository (as opposed to doing it manually). 

You could briefly mention that the pom.xml-file is the configuration file used to supply project information and configuration in Maven.

Awesome that you include reference links in the video description. 

Around 1:10, you could highlight the 6th and 13th lines, when mentioning these things in the voice-over.

Around 1:30, you should write ’setup-java’ in the white box, since this is what you have in the code and also what you say in the voice-over.

+1 for Sonic :)

Excellent that you also include the part where tests fail and how this stops the deployment.

At 2:30 it is not apparent where in the output to see that it has been successfully deployed. You highlight something with the cursor, but it's quite fast and disappears quickly.

At 2:39, the version number is increased from 1.0.1 in the beginning of the video to 1.0.14. Firstly, it’s not super-apparent (I didn’t catch it on my first watch-through), and also maybe it would be nice if it only went from 1.0.1 to 1.0.2. To fix this, you could open the HTML Inspector view in your browser and HTML-hack it to replace 1.0.14 with 1.0.2, and re-shoot that part of the video.

Good luck with the final submission!

**Comment by IC-kth** [comment]
First of all, congratulations on your video. You approached a very interesting subject, and I enjoyed watching it. Bellow, I will add my main points:

Strengths:
   - Very good that you give a short insight into what Maven Central is since viewers might not be familiar with it.
   - Creative adding the Sonic animation :) 
   - Very good that you pointed out important instructions/ things to look at with infoboxes.
   - Nice talk at the end of the video
   
Potential Improvements:
   - I suggest dividing your demo into clear work units, so it's more clear what step are you executing and what is its purpose.
   - Even if you provide the code and needed dependencies, the code writing speed is too high. I would suggest reducing it a bit. This is especially the case when you explain something and select the code/text: the selection is gone before you even get the chance to see it. 
   - At 1:57, you use GitHub Desktop client to push your commit, maybe it might be useful to say this since viewers might get confused (most being used to the terminal)

**Comment by Ackuq** [comment]
> Great demo, with useful content!
> 
> **Strengths**
> 
> * Good that you zoom in on the code when explaining.
> * The way you insert code line by line is nice.
> * The info button is a great feature.
> 
> **Weaknesses**
> 
> * The intro is short, maybe too short to understand, but the rest of the video made everything clearer.
> * The voiceover is a bit fast in some places, mostly at the start and end. I guess that the limited length made you focus on the actual content of the video.

Thank you Frida for the great feedback! Well, you kinda explained yourself why those weaknesses are there haha. For the intro part, I'll extend the description of the video a bit more rather than editing the content of the video, since that would take away parts of the actual content.

> Strengths:
> Interesting topic, really related to Devops
> Focus on code
> 
> Improvement:
> Give a clear summary at the beginning
> Background music could make the video better
> 
> I know it's quite difficult to make these change now, especially to add the summary.
> But overall very good job guys !

Thanks for the feedback Vlado! I'll extend the description of the video to include more descriptive content, as adding another part to the intro would reduce the actual important parts of the video.

> Strengths
> I like the topic, its interesting and has a lot of potential.
> The editing in general is done very well and the sped up code writing is cool.
> You speak at a good pace.
> 
> Improvements
> I would like to see a clearer structure on the video, its nice to know what will be covered and divide it into parts.
> I think a nice introduction with some graphics would make the video more appealing to watch.
> When showing the action secrets for example it would be nice for a viewer to know where on Github this can be found.

Thanks Johan for the feedback. As aforementioned, an outline would be good to have in the description, I'll add that! And yeah some more graphics could be a good addition to the video, I agree.

> All in all an interesting video! As with everyone else, I know you were constrained by the 3 minute limit and that it will be hard to add anything to the video (without removing something else). My key advice would be to highlight important parts of the video (certain lines of code, etc), so the viewer knows what to look at, since the fast pace of the video (again, not your fault) can make it a bit disorienting otherwise.
> 
> Watching the video and providing comments throughout:
> 
> I like how you explain what Maven central is, in case the viewer is not familiar. Also good that you motivate why one wants to automate the process of publishing to this repository (as opposed to doing it manually).
> 
> You could briefly mention that the pom.xml-file is the configuration file used to supply project information and configuration in Maven.
> 
> Awesome that you include reference links in the video description.
> 
> Around 1:10, you could highlight the 6th and 13th lines, when mentioning these things in the voice-over.
> 
> Around 1:30, you should write ’setup-java’ in the white box, since this is what you have in the code and also what you say in the voice-over.
> 
> +1 for Sonic :)
> 
> Excellent that you also include the part where tests fail and how this stops the deployment.
> 
> At 2:30 it is not apparent where in the output to see that it has been successfully deployed. You highlight something with the cursor, but it's quite fast and disappears quickly.
> 
> At 2:39, the version number is increased from 1.0.1 in the beginning of the video to 1.0.14. Firstly, it’s not super-apparent (I didn’t catch it on my first watch-through), and also maybe it would be nice if it only went from 1.0.1 to 1.0.2. To fix this, you could open the HTML Inspector view in your browser and HTML-hack it to replace 1.0.14 with 1.0.2, and re-shoot that part of the video.
> 
> Good luck with the final submission!

Thank you Andreas for the excellent feedback! And I know, it's a lot of stuff crammed into these 3 minutes. The pom.xml should be a prerequisite if working with a Maven project and explaining its general purpose is not really the scope of this video, I would argue. And regarding that bump to 1.0.14, well a lot of trial and error went into perfecting the workflow, so a lot of test releases was made haha. You can see that a lot of previous releases has been made beforehand when showcasing the GitHub releases, I wouldn't say that the actual release that is showcased is the important part here, rather the flow we hare demoing. However, good eye you got ;)

**Comment by Ackuq** [comment]
> First of all, congratulations on your video. You approached a very interesting subject, and I enjoyed watching it. Bellow, I will add my main points:
> 
> Strengths:
> 
> Very good that you give a short insight into what Maven Central is since viewers might not be familiar with it.
> Creative adding the Sonic animation :)
> Very good that you pointed out important instructions/ things to look at with infoboxes.
> Nice talk at the end of the video
> Potential Improvements:
> 
> I suggest dividing your demo into clear work units, so it's more clear what step are you executing and what is its purpose.
> Even if you provide the code and needed dependencies, the code writing speed is too high. I would suggest reducing it a bit. This is especially the case when you explain something and select the code/text: the selection is gone before you even get the chance to see it.
> At 1:57, you use GitHub Desktop client to push your commit, maybe it might be useful to say this since viewers might get confused (most being used to the terminal)

Thanks for the great feedback! I'll add an outline in the video description, thanks! And yes, the writing speed was adjusted to fit the length of the video, might be a bit fast at some parts. I wouldn't say that the actual Git client used is the important part here, if you use Sourcetree, CLI, GitHub Desktop is not important, when we say that we "push" it to the repository that should be clear what we mean.

**Comment by Deee92** [comment]
Hi @Ackuq, has your demo been updated with changes according to the discussions above?

**Comment by Ackuq** [comment]
> Hi @Ackuq, has your demo been updated with changes according to the discussions above?

Yes it has, altough I have not made a new upload of the video, I've updated the description of the video.

**Comment by Ackuq** [comment]
Also, some of the feedback I thought wasn't worth acting upon after some reflection, since it would result in important content of the video being cut out (due to the 3 min limit), decreasing the quality of the video overall.

**Pull request merged**
