### PR TITLE
Video demo:  How to leverage Docker and Kubernetes for creating a Microservice Web App

### PR DESCRIPTION
**Pull request by Internet-Person-IP**
## Members

Taqui - taqui@kth.se
GitHub: [Internet-Person-IP](https://github.com/Internet-Person-IP)

## Proposal
I want to create a video demo on how to leverage Kubernetes and Docker for a Microservice Infrastructure. My plan currently would be to use GKE and to create approx 4-6 containers.

Currently, I have no clear idea what kind of application I want to build but I want it to leverage the Microservice Architecture to the maximum.

The Services I am currently thinking about:

- 1 Frontend
- 1 Auth Service for Authentication
- 1 Service which has a small Node.js backend
- 1 Service with a C# backend
- 1 Container with a SQL DB
- 1 Container with a MongoDB instance

Possibly if I have time I would love to create a Terraform Template that automatically allocates these resources for me and possibly try and setup a CI/CD integration for my frontend(these will only happen if I have time)

### CODE REVIEW

**Comment by khesoem** [comment]
Hi @Internet-Person-IP 

Thanks for your proposal. I think there are already some similar proposal from previous years. See [this link](https://github.com/KTH/devops-course/pulls?q=is%3Apr+is%3Aclosed+GKE+). Moreover, I think it is always better to focus on a single tool, technology, feature, or ... in this course. I'm looking forward, for your new proposals...

**Comment by Internet-Person-IP** [comment]
@khaes-kth thank you for your feedback. Currently, the main thing I want to play with is microservices and kubernetes. I can minimize the proposal if that is what you are asking me. I looked at the link you sent but I do not see people building full scale Microservices using Kubernetes? am I missing something? The closest one I saw was this https://github.com/KTH/devops-course/pull/468 but it focused more on DevOpsifying scaling and provising using Kubernetes where as my focus would be more on the Microservices Side?

I wonder if it is possible to get some clarification on what I should be thinking about differently when it comes to creation of my proposal. 

Thank you for your time.

**Comment by khesoem** [comment]
@Internet-Person-IP : I thought you wanted to focus more on Kubernetes. Now I see your point. Just make your proposal more precise. What application do you want to create? Also, remove the "Possibly...". If you want to do it, then remove the "possibly" and just do it; otherwise, remove the whole thing, as your proposal is already heavy enough :)

**Comment by Internet-Person-IP** [comment]
@khaes-kth Thank you for your feedback. quite frankly I have no idea what kind of application I want to build. Possibly a chat application or possibly a bidding (like eBay or tradera) application or something along those lines. I am currently looking into it. For reducing the complexity I agree that possibly making the last part into an executable tutorial or possibly removing that would be more appropriate.

Thanks again for your advice. If there is anything else you are always welcome to @ me.

**Comment by khesoem** [comment]
Good. So please ping me here when you decided about your application so that I can merge your PR. I recommend you to do it as soon as possible.

**Comment by Internet-Person-IP** [comment]
@khaes-kth I think I will be building a small biding platform. Where you can create products and bid on those products as well. I have changed to proposal a bit to reflect the feedback you have given me.

**Comment by Internet-Person-IP** [comment]
# Video Demo: How to leverage Docker and Kubernetes for creating a Microservice Web App
## Members

Taqui - taqui@kth.se
GitHub: [Internet-Person-IP](https://github.com/Internet-Person-IP)

## Proposal
I want to create a video demo on how to leverage Kubernetes and Docker for a Microservice Infrastructure. My plan currently would be to use GKE and to create approx 4 containers.

I want to build a small bidding platform that shows how the different services are leveraged. In this platform, users will be able to create products and other users will be able to bid on them.

The Services I am currently thinking about:

- 1 Frontend
- 1 Auth Service for Authentication
- 1 Service which has a small Node.js backend
- 1 Service with a C# backend
- 1 Container with a MongoDB instance

**Comment by khesoem** [comment]
Good luck

**Comment by Internet-Person-IP** [comment]
@khaes-kth Hello, I know this is a little bit late but this week has been quite hectic for me. I recently got a call regarding a surgery I have been looking for quite some time. Because of this, I lost a couple of days that I would be working on my Video Demo and quite frankly I am approximately 30% of the way to completetion (I have been able to run the MongoDB instance and Node.js Auth Service). My question is if it for me to replace the C# backend with a Node.js backend? since this would reduce the load a bit for me since I am more familiar with Node.js. Also, I was wondering if it is possible to make a platform like blocket, instead of a bidding since I do have to worry about the underlying realtime activity of a bidding platform. I feel like I am asking for a lot but my circumstances have been quite hectic which is the only reason I ask.

**Comment by khesoem** [comment]
Hi @Internet-Person-IP 

I think you there is no problem to change a part of your implementation. As Martin said in answer to another student:

> [students] can change the implementation, the methodology, but not the general topic.

So, I think it should be fine to replace C# backend with a Node.js one.

**Pull request merged**
