### PR TITLE
Course automation: Automatic duplicate proposal detection

### PR DESCRIPTION
**Pull request by johennin**
# Automatic duplicate proposal detection
## Members
Lee Badal (badal@kth.se)

GitHub: [@LeeBadal](https://github.com/LeeBadal)

Johan Henning (johennin@kth.se)

GitHub [@johennin](https://github.com/johennin)

## Proposal
We plan to create a github action that validates that no previous/similar proposals have been made before.

To verify that the PR is a proposal we intend to test the folder structure or validate that a proposal label is assigned (if  https://github.com/KTH/devops-course/pull/949 is implemented)
We will then run a semantic analysis comparator to previous PR(Title and description) proposals and notify the user/TA's by writing a comment if they are above a certain threshold of similarity or if manual revision by a TA is required. (In this case the URLs to the similar PR will be provided)

## Proposed tools
 * Github Actions
 * [NLTK](https://www.nltk.org/)

### CODE REVIEW

**Review by cesarsotovalero — CHANGES_REQUESTED** [review]
@LeeBadal: is this your KTH account? If not, please change.

**Comment by LeeBadal** [comment]
@cesarsotovalero if you are wondering if this account is linked to my kth mail address, then yes.

**Comment by cesarsotovalero** [comment]
> @cesarsotovalero if you are wondering if this account is linked to my kth mail address, then yes.

No, I mean that you should use `badal` instead.

**Comment by LeeBadal** [comment]
> > @cesarsotovalero if you are wondering if this account is linked to my kth mail address, then yes.
> 
> No, I mean that you should use `badal` instead.

Sorry I'm not quite following, that is not possible because that username is already taken. Please clarify why/where this account is an issue and perhaps I will understand what you want me to change.

**Comment by cesarsotovalero** [comment]
> # Group Rules
> 
> - When you send a pull request for registration, please follow the name convention of using email addresses of two members to create the folder: email-email.

Your email is badal@kth.se, so the name of the folder in your pull request should be `contributions/course-automation/badal-johennin/README.md`

Is this clear to you now?

**Comment by johennin** [comment]
Hi, changes made, sorry about that!
@cesarsotovalero

**Review by cesarsotovalero — APPROVED** [review]

**Comment by cesarsotovalero** [comment]
LGTM now, I'll merge.

**Pull request merged**
