### PR TITLE
Essay submission: How AWS Encourages DevOps

### PR DESCRIPTION
**Pull request by Goradux**
We have finished the essay, but would still like to get some feedback from you before the final submission. Thanks.

### CODE REVIEW

**Comment by gluckzhang** [comment]
Hi @Goradux , in order to register a feedback request, you need to update `feedback-planning.md` here: https://github.com/KTH/devops-course/blob/master/contributions/feedback-planning.md

Please submit another PR to register a slot, thanks :)

**Comment by Goradux** [comment]
Hi,

I have updated the feedback-planning.md file, however, I guess that our fork is older than the file itself, so it shows that the whole file was created, even though we have changed only one line (adding us to the slot for the 20th of April, for both this PR and #569 as well).

**Comment by gluckzhang** [comment]
@Goradux , no worries, I will handle it this time. Usually it's recommended to do atomic PRs (one thing for one PR). You could also avoid such issues by doing so next time :)

**Comment by monperrus** [comment]
Feedback
--------

Overall, the essay is good, the structure makes sense, the writing is OK and we understand the goal of the essay.

Main comments:
- Title: it does not reflect the content, here is a suggestion for improvement "An analysis of AWS with respect to DevOps characteristics"
- Each subsection in Section 3 should clearly reference to one subsection of 2.4
- Add a recap table/figure showing the relations between Sec 3 and Sec 2.4

See also comments in PDF by email.

**Pull request merged**
