### PR TITLE
scientific paper proposal - week 6

### PR DESCRIPTION
**Pull request by florian-immig**
# Assignment Proposal

## Title

The Seven Sins: Security Smells in Infrastructure as Code Scripts

## Names and KTH ID

  - Peiyang Zheng (peiyang@kth.se)
  - Florian Jerome Immig (immig@kth.se)

## Deadline

- Week 6

## Category

- Scientific paper

## Description

We plan to present the paper titled "The Seven Sins: Security Smells in Infrastructure as Code Scripts", which provides an empirical study on security smells in infrastructure as code (IaC) scripts. The authors identify seven distinct security smells, such as hard-coded secrets and invalid IP address binding, which could lead to potential security breaches. They propose a static analysis tool, Security Linter for Infrastructure as Code scripts (SLIC), to detect these smells and highlight their prevalence and persistence in real-world IaC scripts.
Link: https://ieeexplore.ieee.org/document/8812041

**Relevance**

Understanding and mitigating security smells in IaC scripts is crucial for ensuring the security and robustness of automated infrastructure management in DevOps practices such as Infrastructure as Code.

### CODE REVIEW

**Comment by algomaster99** [comment]
Extremely relevant paper for us! Thanks!

**Comment by algomaster99** [comment]
There seems to be 2 files changes in the PR. One from last week and the one from this proposal. Could you please fix it?

**Comment by florian-immig** [comment]
Now only this week's file should be changed, so we are ready to merge.

**Comment by CoordinatesNotFound** [comment]
# Feedback

By Tianning Liang and Yinan Hu



## Code of Conduct



We certify that generative AI, incl. ChatGPT has not been used to write this feedback. Using generative AI without permission is considered academic misconduct.

## High-level strengths and Weaknesses:

### Strengths

- The structure of the presentation is very clear, first briefly introduces motivation, and then lists the seven security smells, the SLIC tool, and its evaluation result.
- There are architecture graphs and code snippets to help understanding.
- The result graph and description are clear and vivid.
- Limitations are being discussed.
- There are two more related papers being added as references.
- Good Take-home message

### Weakness

- Some page contains too many text, which may be difficult for people to get the key points, may need bolding.
- Extracting too many pictures or codes screenshot from the paper, can have better way to display them.
- Key findings just describe the data, without further reflection or summary
- May be better if potential solutions to the limitations are proposed

## Feedback per section

### Motivation

Motivation starts from a wide perspective, which is Infrastructure as Code, emphasizing the high relevance between this topic and our course. Then it enters security smells and highlights its three main bad effects. Finally, this section introduces the experiment this paper covers. All in all, the structure of this part is clear with four points.



### Security Smells

This part lists the seven security smells. Besides the simple description, there are sub-points to explain why this action is a security smell. They use point again to list. Although this way is not bad, there are too many words on this page without bolding, which makes it easy to distract.



### Security Linter for Infrastructure as Code Scripts (SLIC)

This part contains a vivid infrastructure graph to introduce what is SLIC. I appreciate the little design, which uses the same color as the corresponding module to describe it on the first page of this part. The graph is not difficult to understand with the addition of the text.

There are two more pages with code snippets, and specific rules to explain how the parser and rule engine operate. The information is brief and exact. But it’s obvious that they are screenshots from the original paper, I would doubt if there is a better way to put it in the slide. Extracting a lot of charts directly from a paper seems a bit lazy.



### Key Findings

This part uses a graph and also three short sentences to explain the key findings, which is detailed and vivid, achieving a balance. The key data of the research are demonstrated. However, these sentences seem to simply list the data, without further reflection or abstraction from the data. Also, the graph is a bit not clear.



### Limitations

This part discusses the limitations of the paper, which shows that you have not only read the good things but also reflected on the drawbacks on the paper. And the four points are concise, each stating a limitation from a different aspect, which is really good. It would be better if you could propose some possible solutions to the limitations.

### Take-Home message

The take-home message is really concise, accompanied by a vivid graph. And it well summarised the core of this presentation.

## Additional Material

I. K. Ratol and M. P. Robillard, “Detecting fragile comments,” in Proceedings of the 32Nd IEEE/ACM International Conference on Automated Software Engineering, ser. ASE 2017. Piscataway, NJ, USA: IEEE Press, 2017, pp. 112–122. [Online]. Available: http://dl.acm.org/citation.cfm?id=3155562.3155581

**Pull request merged**
