### PR TITLE
Presentation proposal: Monolithic vs Microservice Week 3

### PR DESCRIPTION
**Pull request by dieflo4711**
# Presentation Proposal
## Members
- Diego Leon (dleon@kth.se)
- George Rezkalla (rezkalla@kth.se)

## Topic
Monolithic vs Microservices

DevOps can extend its use of containerization to switch to a microservices architecture. Microservice based applications can be implemented for increased scalability and independence.

DevOps teams encapsulate pieces of functionality in microservices and build larger systems by composing the microservices like building blocks. These teams can also extend functionality by adding new microservices without affecting other parts of the application. DevOps practices, such as CI and CD, are used to drive microservice deployments.

## Details
- How do they work?
- What's the Difference (testing, deployment, scalability, etc)?
- Examples of implementation
- When should you use what?

### CODE REVIEW

**Comment by georgewbar** [comment]
github username: georgewbar
Name: George Rezkalla
kth mejl: rezkalla

**Comment by gluckzhang** [comment]
Hi @dieflo4711 , @georgewbar , there have been 7 presentations registered in week 3. Based on last week's experience, it might be too tense to have more than 7 presentations each week. Do you mind if reschedule your presentation to week 4?

Hi @SophieHYe , do you have any suggestions before merging this PR?

**Comment by georgewbar** [comment]
@gluckzhang actually my teammate for the old presentation `sevinc-rezkalla` dropped the course. Now, I am doing the presentation with @dieflo4711. So, feel free to remove the presentation `sevinc-rezkalla`

**Comment by gluckzhang** [comment]
> @gluckzhang actually my teammate for the old presentation `sevinc-rezkalla` will not continue the course. Now, I am doing the presentation with @dieflo4711. So, the presentation `sevinc-rezkalla` should be removed.

Hi @georgewbar , thanks for the info! I will confirm with that team and update the agenda. I think you will present in week3 then :)

**Comment by gluckzhang** [comment]
Regarding the proposal, I think the idea is very interesting and related. Could you add a short paragraph to introduce the background of this topic in `README.md`? You could mention something like: the motivation of choosing it, the relevance and timeliness for DevOps etc.

**Comment by dieflo4711** [comment]
Updated the readme file :)

**Comment by gluckzhang** [comment]
@dieflo4711 sounds great, the PR has been merged. Thanks!

**Pull request merged**
