### PR TITLE
essay proposal: Maven and its handling of build dependencies

### PR DESCRIPTION
**Pull request by AristotelisKotsias**
(Updated) The essay will give an insight into Maven as a DevOps tool. The main points that will be addressed in the essay are:

1. Introduction to Build Tools
2. Relation to DevOps
3. Definition of Build dependencies
4. Structure of the Maven Build dependencies
5. The Maven repository.
6. Concluding points

### CODE REVIEW

**Comment by AristotelisKotsias** [comment]
Hello @gluckzhang , thank you for your reply! I have updated our proposal to be more specific.

**Comment by gluckzhang** [comment]
> Hello @gluckzhang , thank you for your reply! I have updated our proposal to be more specific.

Thanks @AristotelisKotsias , since the essay will focus on dependencies, could you also update the title to something like "How Does Maven Handle Build Dependencies"?

@cesarsotovalero , what do you think about it? You are the expert of Maven dependency in our team :)

**Comment by AristotelisKotsias** [comment]
Hello, @gluckzhang i updated the title of the PR as well!

**Comment by AristotelisKotsias** [comment]
Hello @gluckzhang! What do you think of this proposal, can it get merged?

**Comment by gluckzhang** [comment]
> Hello @gluckzhang! What do you think of this proposal, can it get merged?

Hi @AristotelisKotsias , sorry about the late reply. Yes, I'm fine with the proposal and I will merge it now :)

**Pull request merged**
