### PR TITLE
Feedback proposal for essay #970

### PR DESCRIPTION
**Pull request by callmeGoldenboy**
# Feedback

## Member

Natan Teferi Asegehegn: ntas@kth.se

GitHub: https://github.com/callmeGoldenboy

## Proposal

I would like to give feedback on the essay written by Gabriel Chang and William Skagerström: the PR for the proposal is #970

### CODE REVIEW

**Comment by Deee92** [comment]
Hi @callmeGoldenboy, please link PR `#970` in your README as well.

**Comment by Deee92** [comment]
Also, leave a comment on https://github.com/KTH/devops-course/pull/970.

**Comment by callmeGoldenboy** [comment]
I have now changed the README and added the comment on #970

**Comment by Deee92** [comment]
Thanks, merging now. Good luck!

**Pull request merged**
