### PR TITLE
Essay: Devops techniques in video game development (working title)

### PR DESCRIPTION
**Pull request by wska**
Essay proposal

### CODE REVIEW

**Comment by cesarsotovalero** [comment]
Hi @wska, a good topic for an essay.
Looking forward to reading it!

**Review by cesarsotovalero — APPROVED** [review]
LGTM... do not forget to add pointers to specific DevOps tools, and also describe real-world practices adopted in the industry.

**Comment by callmeGoldenboy** [comment]
I would like to give feedback on this essay

**Comment by wska** [comment]
@callmeGoldenboy Hi! We already received one request to provide feedback on this essay. I do not know if multiple people are allowed to give feedback on the same project. You could perhaps ask one of the TAs about it?

**Comment by Deee92** [comment]
Hi @wska, do you mean PR #983? (The author of that PR is @callmeGoldenboy.)
If not, can you share the link to the PR with the feedback proposal for your essay?

**Comment by wska** [comment]
Hi! @Deee92.

My bad. Yes #983 is the one. It was the same person. I was contacted through email and did not know the github username of Nathan.

So all is well.

**Comment by Deee92** [comment]
Thanks for confirming, @wska.

**Pull request merged**
