### PR TITLE
Tutorial: Introduction of Pijul

### PR DESCRIPTION
**Pull request by ysndr**
We would like to introduce the VCS [Pijul](https://pijul.org/).
﻿
@dsharifi

### CODE REVIEW

**Comment by Grunler** [comment]
I would like to give feedback to this tutorial if it is accepted

**Comment by ysndr** [comment]
@cesarsotovalero are we good to go?

**Comment by ysndr** [comment]
@Grunler you should set up a pr once this is merged

**Comment by khesoem** [comment]
Hi @ysndr 

Good proposal. How do you want to create the tutorial? Katacoda or ...?

**Comment by ysndr** [comment]
Hej
Yes, as this does need access to some sort of linux environment I see katacoda or a similar service as the tool of choice.

**Comment by khesoem** [comment]
> Hej
> Yes, as this does need access to some sort of linux environment I see katacoda or a similar service as the tool of choice.

Can you add this information to your proposal?

**Comment by ysndr** [comment]
@khaes-kth I added a note to the proposal

**Pull request merged**
