### PR TITLE
Essay proposal: Solo programming vs Pair programming vs Mob programming in DevOps teams

### PR DESCRIPTION
**Pull request by mellonnen**
# Assignment Proposal

## Title

Solo programming vs Pair programming vs Mob programming in DevOps teams.

## Names and KTH ID

- Arvid Gotthard (gotthard@kth.se)

## Deadline

Task 4

## Category

Essay

## Description

My goal is to compare these three paradigms in producing software in the context of a DevOps team. I weigh the pros and cons for each approach based on a few criteria:

- Produced software quality.
- How does it work together with continuous delivery.
- Environment for learning.
- Development time and cost.
  - I plan to consider remote teams as well as regular teams

After an initial glance at the literature, I expect that pair and mob programming provide more pros than solo programming. However, I suspect that which paradigm is most successful is highly situational.

### CODE REVIEW

**Comment by pdchao23** [comment]
Hi can me and @bencivjan provide feedback on your essay?

**Comment by mellonnen** [comment]
Of course!

**Comment by pdchao23** [comment]
Perfect, if you can let us know when the essay is ready for feedback and give us access to the document that would be great!

**Comment by pdchao23** [comment]
Hi! Is your essay ready for feedback? We are looking to give feedback by the Task 4 deadline. If this isn’t possible please let us know, thanks!

**Comment by mellonnen** [comment]
Currently working on it 😅 It will be ready this afternoon/evening. Hopefully, that gives you guys enough time?

ping @pdchao23 so that you do not miss this!

**Comment by pdchao23** [comment]
Okay thanks @mellonnen! Please let us know once you are ready today and we can get started

**Comment by mellonnen** [comment]
@pdchao23  you can find the essay [here](https://github.com/mellonnen/devops-course/blob/persentation-proposal/contributions/essay/gotthard/Solo_vs_Pair_vs_Mob_programming.pdf).

Let me know if you need anything more, like confirming that I submitted the essay very close to the deadline. 😁

**Comment by pdchao23** [comment]
# Feedback (pdchao and civjan)
Thank you for this contribution to the DevOps course. Your essay detailing the different types of programming techniques was very insightful and relevant in the scope of DevOps. While it was a fantastic read, we do have some constructive feedback to make the essay even better. 
# High-level strengths
* A strong, concise introduction that tells the reader exactly what to expect when reading the article
* Clear organization between the discussion of each of the topics (Solo, Pair, and Mob)
* References many other works showing extensive research done on the topic
# High-level weaknesses
* Lack of anecdotal examples when analyzing and criticizing each programming technique
* Draws conclusions based off “studies” without providing necessary background
* The use of first person when comparing and discussing the techniques adds informality
# Specific feedback
## Introduction and Title:
The title and introduction are clear and concise detailing exactly what the essay will be discussing. It provides a clear relation between the programming techniques and the relevance to DevOps in the scope of the class.
## Solo Programming:
The reference to Fagan Inspections was very insightful. It provided great background on the origin of code reviews and drew our attention as readers. One confusing aspect of this for us was the allusion that code reviews are specific to solo programming. However, it is possible to use pair or mob programming and still have code reviews with a manager or other team members. In order to alleviate this confusion and make things more clear, we suggest adding a discussion of why code reviews in solo programming might be more necessary than the other strategies.
## Pair Programming:
We thought the description in this section was clear and taught us many new ideas, even with us having experience with pair programming. Our favorite part of this passage was the quote about strong pairing, which provided a solution to the ‘disconnected navigator’ drawback of peer programming. Everyone who has pair-programmed has likely experienced a ‘disconnected navigator’, which devolves the practice into simply solo programming with someone staring over your shoulder.
## Mob Programming:
The anecdote about Unruly was intriguing and very helpful for understanding mob programming in context. This made us wish for similar anecdotes in the other sections. In the introduction it could be beneficial to discuss the situations where mob programming would be better than the other strategies (i.e. an abnormally complex/important section of code). We weren’t sure where we would, so some examples of where it would be more useful would be helpful. Additionally, as readers we would love to hear a little bit about how Mob.sh works without having to do outside research. An additional sentence or two about the script would suffice.
## Discussion:
We think this is one of the most important parts that should really bring the essay together. At this point you have provided background on each topic and analyzed each technique individually, now the reader is looking for a holistic comparison of all three. 

You start by detailing your prior experience and express intrigue in both pair programming, mob programming but this throws off the objectiveness of the essay. Everything prior has been objective definitions and advantages and criticisms, so it is odd to all of a sudden change to first person and state your personal thoughts in the discussion. We would recommend omitting this first paragraph or changing it to be more objective to flow with the rest of the essay.

Additionally, you start by suggesting that there is really no definitive answer or conclusion to which technique is most effective. However, from the introduction and title it never really mentions this problem statement of trying to find which programming technique is the most effective. From our perspective the essay seemed more to just simply compare the three techniques and allow the reader to choose which programming technique suits their need the best. Providing certain situations where one programming technique would be more effective is a better way to approach this problem.

Lastly, you compare the techniques based on the speed of coding, coding quality, and cost of operation sparsely throughout the essay. We think this could potentially be a more definitive way to structure this last part to analyze the three programming techniques. It would also be interesting to see graphs or diagrams to help the reader visualize the difference.
## Additional Pointers:
* Comparison between effectiveness of solo, pair, and mob programming in a University setting
https://www.academia.edu/42508817/Solo_pair_or_Mob_programming_Which_should_be_used_in_university
* Study of software professionals effectiveness of solo vs pair programming
https://citeseerx.ist.psu.edu/viewdoc/download?doi=10.1.1.907.4935&rep=rep1&type=pdf
* Additional types of agile methodology
https://www.jigsawacademy.com/blogs/product-management/types-of-agile-methodology/
* Useful diagram describing pair programming
https://blog.teachcomputing.org/quick-read-pair-programming-supports-learners/

**Comment by mellonnen** [comment]
Thanks for the feedback!

**Pull request merged**
