### PR TITLE
Essay submission: "End-to-end testing: Useful practice or frustrating time sink?"

### PR DESCRIPTION
**Pull request by Grunler**
Collaborator: Lee Badal (@LeeBadal)

Proposal PR: #1369 

There is also a feedback proposal for this essay that is currently open, so we will mention it in case it gets accepted: #1413

### CODE REVIEW

**Comment by Renugaa** [comment]
HI, 

I would like to give feedback for the Essay.

//Renugaa

**Comment by Renugaa** [comment]
Hi,

My feedback proposal #1413 

Thanks 
Renugaa

**Comment by Grunler** [comment]
@Renugaa we're looking forward to your feedback!

**Comment by Renugaa** [comment]
Hi @Grunler,

I have provided my feedback and here it is #1459 

Thanks,
Renugaa

**Comment by bbaudry** [comment]
@Grunler, @LeeBadal thank you for contributing an essay!
@Renugaa  has prepared feedback about your essay: #1459
Please, act upon this feedback and prepare a revision of your essay, as well as a summary of the changes you made based on the feedback
Please submit by May 4, midnight Stockholm time
thanks!

**Comment by LeeBadal** [comment]
Based on the feedback we received we made minor changes:

* Renamed title to "Automated E2E.."
* Rephrased a sentence explaining that E2E tests, in general, refer to automated E2E tests.

### We took the following points into consideration but did not act upon them for the following reason:


**I felt it could have been more in depth in one of the particular areas of your choice instead of focussing everything on a high level.** 
Answer: This would require us to rewrite most of the essay, but in hindsight, it could have been a more interesting topic.

**Some more basic components of E2E testing could have also been mentioned in this topic instead of using the ones relevant to the example.** 
Answer: We did not find many other components that are used for automated E2E testing, but we also actively chose to mention they are frequently used and we were limited to the 2100 word count.
If we missed something major please provide a link and we could look into it. 

**You could have added some theories to prove it is also a successful solution in Manual environment.**
Answer: We agree with this but our focus was automated E2E tests as we otherwise have a risk of straying too far from the DevOps subject.


Thanks for the feedback @Renugaa !
@khaes-kth We are ready for a merge!

**Pull request merged**
