### PR TITLE
Essay submission: Comparison Study Between Popular Infrastructure as Code Tools

### PR DESCRIPTION
**Pull request by joakim-olsson**
# Assignment Proposal

## Title  

Comparison Study Between Popular Infrastructure as Code Tools

## Names and KTH ID   
  - Joakim Olsson (joakiols@kth.se)   
  - Mikael Jafari (mjafari@kth.se)  

## Deadline  

Task 2  

## Category

Essay

## Description  

A comparison study between some common Infrastructure as Code (IaC) tools. The tools that will be covered in the essay: Ansible, Terraform, Chef, and Salt.
How do they work, what are their differences, strength, and use cases? These are some of the things that will be discussed in this essay.

### CODE REVIEW

**Comment by joakim-olsson** [comment]
The excessive word count is caused by the code segments that we have used as figures in our report. The word count for our generated PDF according to Google Docs is 2443.

**Comment by khesoem** [comment]
Hi @joakim-olsson 

We count the words with the following commands ([link](https://github.com/KTH/devops-course/blob/2022/.github/workflows/essay-word-count.yml)):
`sudo pdftotext "${added_file}" - | tr -d '.' | wc -w`
`sudo pdftotext "${added_file}" - | wc -w`

Please make sure at least one of them returns a number in the target range.

**Comment by Deee92** [comment]
@joakim-olsson, you can also consider adding code listings as images.

**Comment by joakim-olsson** [comment]
Fixed @Deee92 @khaes-kth

**Pull request merged**
