### PR TITLE
Essay submission: Comparison of Splunk and Nagios Devop monitoring tools and their use cases

### PR DESCRIPTION
**Pull request by carinawic**
This is the submission following the proposal in PR #1021 
(Essay: Comparison of Splunk and Nagios Devop monitoring tools and their use cases)

We also look forward to feedback from @yuxinm and @renstr (#1178)

The pdf can also be quick accessed [here](https://github.com/carinawic/devops-course/blob/2021/contributions/essay/carinawi-urama/Essay_DevOps_final.pdf)

### CODE REVIEW

**Comment by yuxinmmmm** [comment]
# Feedback for essay "Comparison of Splunk and Nagios Devop monitoring tools and their use cases"

## Member
Yuxin Meng [@yuxinm](https://github.com/yuxinmmmm) email: yuxinm@kth.se

Anders Renström [@renstr](https://github.com/Renstrom) email: renstr@kth.se

## Pull-requests 
Essay proposal pull-request: [#1021](https://github.com/KTH/devops-course/pull/1021)

Essay submission pull-request: [#1338](https://github.com/KTH/devops-course/pull/1338)

## In General
The structure of the article is good, I can follow the structure of the article to read and understand the content of the article, and the abstract gave me a rough understanding of the text, to help me understand the main content of the article, which is very good. 
In addition, the content of the article is closely related to the title.

## Introduction
This part makes a good introduction to the topic, it briefly describes what continuous monitoring is and what the tools are generally used for. And also introduces the main content of each section of the article, which improves readability.
So I think this part is good and doesn’t need a lot of revision.

## Background
This section gives me a good idea of both of the tools mentioned in the title, both of their strengths and weaknesses, as well as where they are used. The content of this section is good, both tools have detailed background introduction. 
But I think this part is too much, from the length of this section will make me feel that the focus is on the introduction of the two rather than the comparison between them. And since there’s less about their use cases, I thought I’d cut the background on both tools and add more details of use cases. 
For example, in the section on Nagios use cases, there are detailed descriptions of the use cases, based on the references cited [16], and you can try to summarize them so that the reader can better understand what they are used for.

## Comparison
I think it makes sense to select three metrics for comparison, which are really elements to consider when choosing which monitoring tool to use.
But I think the comparison between the two tools is not just in terms of the metrics used to select the tool, but also in terms of their own characteristics. So I think you can also compare the differences from the monitoring features mentioned in the introduction to the monitoring tools in Section2.1 and the advantages and disadvantages of the two tools mentioned in Section2.2 and 2.4.

## Conclusion
The conclusion section summarizes the differences between the two by comparison. But there seems to be a lack of conclusions about use cases. This can be added after a description of the pros and cons of each tool. Splunk, for example, has advantages that make it a priority to use it in certain cases, and then you can talk about these use cases.

## References
As an essay, the number of references meets the requirements. References are presented well, clearly, and in the proper order. Both the reference in the article and the URL mentioned in the reference have clickable links, which I think is well done. Perhaps a little understated is the lack of references to academic journals or studies.

## Structure
I have some personal suggestions for the structure of the article. I think Section 2 is a bit long, and use cases about tools can not be part of the background section. Alternatively, you can merge the two sections (section 2.3 and Section 2.5) into a higher-level new section, such as Section 4, after section 3comparison.

In addition, if you want to modify the essay, you should pay attention to the word limit. I hope you can successfully complete the revision of the paper.

**Comment by yuxinmmmm** [comment]
> This is the submission following the proposal in PR #1021
> (Essay: Comparison of Splunk and Nagios Devop monitoring tools and their use cases)
> 
> We also look forward to feedback from @YuxinM and @renstr (#1178)
> 
> The pdf can also be quick accessed [here](https://github.com/carinawic/devops-course/blob/2021/contributions/essay/carinawi-urama/Comparison_Splunk_Nagios.pdf)

My Github account is  [@yuxinm](https://github.com/yuxinmmmm). Not the  [@YuxinM](https://github.com/YuxinM).

**Comment by Renstrom** [comment]
# Feedback
Hi @carinawic and @IfyUrama! 

Me and @yuxinmmmm have now constructed our feedback for your essays, which will be uploaded shortly. We decided early on to do the feedback separately in order to get different views of the paper.

**Comment by yuxinmmmm** [comment]
# Feedback for essay "Comparison of Splunk and Nagios Devop monitoring tools and their use cases"

## Feedback by Yuxin Meng
## Member
Yuxin Meng [@yuxinm](https://github.com/yuxinmmmm) email: yuxinm@kth.se

Anders Renström [@renstr](https://github.com/Renstrom) email: renstr@kth.se

## Pull-requests 
Essay proposal pull-request: [#1021](https://github.com/KTH/devops-course/pull/1021)

Essay submission pull-request: [#1338](https://github.com/KTH/devops-course/pull/1338)

## In General
The structure of the article is good, I can follow the structure of the article to read and understand the content of the article, and the abstract gave me a rough understanding of the text, to help me understand the main content of the article, which is very good. 
In addition, the content of the article is closely related to the title.

## Introduction
This part makes a good introduction to the topic, it briefly describes what continuous monitoring is and what the tools are generally used for. And also introduces the main content of each section of the article, which improves readability.
So I think this part is good and doesn’t need a lot of revision.

## Background
This section gives me a good idea of both of the tools mentioned in the title, both of their strengths and weaknesses, as well as where they are used. The content of this section is good, both tools have detailed background introduction. 
But I think this part is too much, from the length of this section will make me feel that the focus is on the introduction of the two rather than the comparison between them. And since there’s less about their use cases, I thought I’d cut the background on both tools and add more details of use cases. 
For example, in the section on Nagios use cases, there are detailed descriptions of the use cases, based on the references cited [16], and you can try to summarize them so that the reader can better understand what they are used for.

## Comparison
I think it makes sense to select three metrics for comparison, which are really elements to consider when choosing which monitoring tool to use.
But I think the comparison between the two tools is not just in terms of the metrics used to select the tool, but also in terms of their own characteristics. So I think you can also compare the differences from the monitoring features mentioned in the introduction to the monitoring tools in Section2.1 and the advantages and disadvantages of the two tools mentioned in Section2.2 and 2.4.

## Conclusion
The conclusion section summarizes the differences between the two by comparison. But there seems to be a lack of conclusions about use cases. This can be added after a description of the pros and cons of each tool. Splunk, for example, has advantages that make it a priority to use it in certain cases, and then you can talk about these use cases.

## References
As an essay, the number of references meets the requirements. References are presented well, clearly, and in the proper order. Both the reference in the article and the URL mentioned in the reference have clickable links, which I think is well done. Perhaps a little understated is the lack of references to academic journals or studies.

## Structure
I have some personal suggestions for the structure of the article. I think Section 2 is a bit long, and use cases about tools can not be part of the background section. Alternatively, you can merge the two sections (section 2.3 and Section 2.5) into a higher-level new section, such as Section 4, after section 3comparison.

In addition, if you want to modify the essay, you should pay attention to the word limit. I hope you can successfully complete the revision of the paper.

**Comment by Renstrom** [comment]
# Comparison of Splunk and Nagios DevOps Monitoring Tools and Their Use Cases
## Feedback by Anders Renström
## Member 
Anders Renström [@renstr](https://github.com/Renstrom) email: renstr@kth.se
Yuxin Meng [@yuxinm](https://github.com/yuxinmmmm) email yuxinm@kth.se
## Pull- Requests

Essay proposal pull-request: [#1021](https://github.com/KTH/devops-course/pull/1021)
Essay submission pull-request: [#1338](https://github.com/KTH/devops-course/pull/1338)
## Overall
Overall the essay is good, it has a clear red thread all throughout the paper with a self-containing structure. 
### Structure
The structure in the text was good, I liked that you provided almost the same amount of words for both monitoring tools and not prioritizing one monitoring tool over the other. It was also nice that the structure of the monitoring tool was the same (Introduction, product categories used,  Advantages/Disadvantages, and Use cases). This made it easier to compare the two later on.
### Linguistics
Overall, the linguistics of the text was good, it had a nice flow to it. Some minor inconsistencies with the capitalization of Splunk existed which is an easy fix.  
## Feedback for sections
### Abstract
The abstract has a nice summary of the whole essay which is what an abstract should do. However, due to the strict limit of the amounts of words in this essay. The words used here could maybe be used somewhere else to get more detail somewhere else of the paper. 
###Introduction (What they aim to achieve should be mentioned in conclusion as well)
I think the introduction is great, it introduces the importance of continuous monitoring tools and that there are many different ones to choose between. The sentence "what they aim to achieve", clearly showcases that there currently isn't a one fit all monitoring tool.

One minor improvement would be to further clarify the reasoning behind choosing to compare the two monitoring tools. As was said at the beginning of the introduction, there are a lot of different monitoring tools. So what made you choose these too especially? 
### Background 
Overall a good background, all subsections are fitting and interesting to read about. One thing that could be improved is to maybe shorten down the background for monitoring tools since the paper should focus a lot on comparing the two monitoring tools.
### Monitoring Tools
I do like the monitoring tools part, it is well written, detailed, and an interesting read. However, it feels that the importance of the monitoring tools takes too many places for the paper as I mentioned above. 
### Splunk monitoring tool
Aside from minor capitalization problems with the word "Splunk" in this section, the section is constructed really well and each part seems relevant to the essay.
### Some of the Splunk use cases 
The use cases section seems a bit unclear, especially compared to the Nagios use cases. In this one, you only list examples while the Nagios section uses clear use cases.
### Nagios monitoring tool
In the Nagios monitoring tool section, you mention that Nagios is free, however, there are actually some products such as the [Nagios-Xi](https://www.nagios.com/products/nagios-xi/), that starts around 1995 $/per user to use. Please consider adding some sort of detail regarding what costs and what doesn't with the Nagios product line.   
### Some of the Nagios use cases
See Splunk use cases
### Comparison
I really liked the comparison, dividing them to use cases, cost, and ease of use seemed clear after reading the background above. 
 - Use case: You mention that Splunk is the best monitoring tool for capturing and analyzing machine data, do you have any sources to back up this claim? Try to avoid using biased sentences.
 - Cost: In terms of cost, I believe more factors could be considered aside from Splunk's traffic cost. Due to the minimal customer support system, customizable and lacking in the user-friendly GUI that Nagios has. There are risks that this sort of monitoring tool costs a lot to upkeep compared to Splunk's monitoring system.  
- Ease of use: I wholeheartedly agree, that despite Splunk having a steep learning curve. With a highly customizable system like Nagios, more work is needed to be done. And if this work is documented thoroughly, it will be hard to maintain this code. Another thing the last sentence mentions that "Splunk is thereby easier to use thanks to its product support and documentation". I don't see this as one of the advantages mentioned above in the subsection "Splunk Monitoring Tool". Maybe include it to strengthen your claim 

### Conclusion
I'm not so sure about the conclusion, these systems do complement each other. But is it really worth it to combine the two tools? Or as you mentioned in "what they (the company) aim to achieve", do they want a highly customizable, free, and substantial user control monitoring tool like Nagios. Or do they want a Real-time performance, less hardware resource costly, real-time alert based for the desired search such as Splunk? I believe a more valid conclusion would be to say that it really based on what you as a customer need.
### References 
All references seem good, the only one that seems a bit unclear is the [ITCS465-Nagios](https://sites.google.com/site/itcs465nagios/protocols-supported) source. Maybe look at sources such as [Capterra](https://www.capterra.se/software/152751/nagios-core) and [TrustRadius](https://www.trustradius.com/products/nagios-core/reviews?qs=pros-and-cons) to see what the user have to say about it.

**Comment by carinawic** [comment]
# Response to feedback

Thank you @YuxinM and @renstr for your good feedback!
We took your feedback into consideration and made the following changes to our report accordingly:

### Abstract

> (...), due to the strict limit of the amounts of words in this essay. The words used here could maybe be used somewhere else to get more detail somewhere else of the paper. -- Anders Renström

We ended up shortening the abstract to get room for content elsewhere.

### Introduction
> One minor improvement would be to further clarify the reasoning behind choosing to compare the two monitoring tools. -- Anders Renström

We handled this by rephrazing one sentence, previously saying that we picked "two among many monitoring tools" into "This report aims to compare Nagios and Splunk, which are two popular tools for continuous monitoring." Shifting the emphasis on that we picked them because they were in particular popular. 

### Background

> One thing that could be improved is to maybe shorten down the background for monitoring tools since the paper should focus a lot on comparing the two monitoring tools. -- Anders Renström

> (...) But I think this part is too much, from the length of this section will make me feel that the focus is on the introduction of the two rather than the comparison between them. And since there’s less about their use cases, I thought I’d cut the background on both tools and add more details of use cases. -- Yuxin Meng

The background was accordingly shortened. Additionally, the "use case" sections was moved from the background to the comparison part of the essay, which further shortened the background chapter in accordance with feedback.

> For example, in the section on Nagios use cases, there are detailed descriptions of the use cases, based on the references cited [16], and you can try to summarize them so that the reader can better understand what they are used for. --  Yuxin Meng

When moving the "use case" parts, all left in the background was a summary of what they're used for - as mentioned in this feedback.

### Monitoring tools

> it feels that the importance of the monitoring tools takes too many places for the paper -- Anders Renström

Yes, this section was thereby shortened.

### Some of the Splunk use cases

>  The use cases section seems a bit unclear, especially compared to the Nagios use cases. -- Anders Renström

This was a good point! We thereafter changed and clarified these sections so that they ended up more alike and consistent with each other.

### Nagios monitoring tool
>  Please consider adding some sort of detail regarding what costs and what doesn't with the Nagios product line. -- Anders Renström

This was indeed slightly misleeding in the draft. We added a paragraph specifying the costs. 

### Comparison

> You mention that Splunk is the best monitoring tool for capturing and analyzing machine data, do you have any sources to back up this claim? --  Anders Renström

We could not find a source backing this up, so we changed this sentence entirely.

> Cost: In terms of cost, I believe more factors could be considered aside from Splunk's traffic cost. --  Anders Renström

There are indeed other cost factors one can consider. We did add the perspective of an increased maintainence cost using Nagios due to the lack of customer support.  

> "Splunk is thereby easier to use thanks to its product support and documentation". I don't see this as one of the advantages mentioned above in the subsection "Splunk Monitoring Tool". Maybe include it to strengthen your claim --  Anders Renström

We added this in the advantage list.

>  I think you can also compare the differences from the monitoring features mentioned in the introduction to the monitoring tools in Section2.1 and the advantages and disadvantages of the two tools mentioned in Section2.2 and 2.4. --  Yuxin Meng

We considered this, and much therefore we moved the "use case" sections to the comparison chapter, because indeed it is relevant to also compare the use cases, which result from the advantages/disadvantages (what the tools are good for).

### Conclusion

> I'm not so sure about the conclusion, (...)  I believe a more valid conclusion would be to say that it really based on what you as a customer need. --  Anders Renström

The conclusion was rephrazed a bit into focusing on that it depends on the use case. And additionally, it is also possible to combine the tools. 

> there seems to be a lack of conclusions about use cases.  -- Yuxin Meng

The final version includes a part of the comparison saying "use Nagios for this, and use Splunk for that", which we considered a conclusion about the use cases.

### References

> Perhaps a little understated is the lack of references to academic journals or studies. -- Yuxin Meng

> All references seem good, the only one that seems a bit unclear is the ITCS465-Nagios source. --  Anders Renström

The references were looked over. There aren't too many "academic journals or studies" to go on because it's a fairly new topic. 

### Linguistics

> Some minor inconsistencies with the capitalization of Splunk existed which is an easy fix. -- Anders Renström

Fixed! :)

### Structure

> I have some personal suggestions for the structure of the article. I think Section 2 is a bit long, and use cases about tools can not be part of the background section. Alternatively, you can merge the two sections (section 2.3 and Section 2.5) into a higher-level new section, such as Section 4, after section 3comparison. -- Yuxin Meng

We agreed with the problem, and the solution was almost implemented as you suggested, but instead of a completely new section they were moved to the upcoming section instead.

### My comments

We clearly did take your feedback into account, it was very good feedback from both of you. Thank you and good luck with the course!

**Comment by Renstrom** [comment]
Skimmed through it quickly, it looks a lot better now. 

Great job!

**Comment by SophieHYe** [comment]
Thanks for the final essay submission. I am now merging your PR and we will grade your work based on the final version.

**Pull request merged**
