### PR TITLE
Demo submission for kotsias-giorgost

### PR DESCRIPTION
**Pull request by AristotelisKotsias**
Link to screencast and GitHub repo have been added.

### CODE REVIEW

**Comment by AristotelisKotsias** [comment]
Please, the reviewers of the app don't make more than 3 searches each because the GitHub API that we use at the momemnt does not make authenticated requests and it only allows for only 60 requests per hour.

**Comment by keivanm** [comment]
I'll give feedback to this demo

**Comment by johansettlin** [comment]
I would like to give feedback!

**Comment by JoarEkelund** [comment]
I will give feedback

**Comment by Kappenn** [comment]
I will give feedback

**Comment by jzafar** [comment]
I would like to give feedback!

**Comment by olapiv** [comment]
I'll give feedback

**Comment by johansettlin** [comment]
Nice demo showing a great workflow. I would like to know more about how you set up and integrate Heroku and Travis (is there a plugin on Travis?).

The screencast was nicely done with both voice and subtitles. And at the beginning of the video a good overview was presented.

**Comment by keivanm** [comment]
Interesting and nicely made demo. Since there was almost a minute to spare I would've liked more background info on Heroku, specifically how it compares to other similar tools :)

**Comment by Paul-Philip** [comment]
I'd like to give feedback as well :)

**Comment by olapiv** [comment]
Altogether: Very nice.

I personally found this demo super helpful because I’ve actually heard of Travis and Heroku quite a few times, but I never really knew what they were about. Now I have an idea!

I found it came a bit out of the blue though when your Github was showing you that „all tests have passed“ with Travis CI. I wouldn’t necessarily know how to reproduce this. Same with Heroku - where did that come from? Basically some input on how to link the services together would be nice.

Also I didn’t really understand what the difference is between your review and your staging environment. Can you configure the builds to work differently there? It comes across to me as if you would actually only need one of the two.

**Comment by JoarEkelund** [comment]
Good demo. It gives a nice overview of the core functionality and the basic idea of Heroku.

However, it would have been nice to include some more background information about Heroku, what it is and its capabilities.

**Comment by Paul-Philip** [comment]
Hi,

Thanks for the demo, the content is relevant and the pace in the demo is great!
I like the introduction in the beginning, describing how the pipeline is setup.

The tools you used seemed really easy to use and I would like to test them.
Although, it would be great if you quickly showed the setup used for the Travis and Heroku.

**Comment by Kappenn** [comment]
Great Demo, the demo really showcased "CI/CD Pipeline with GitHub, Travis-CI and Heroku". 

The pacing is good, the content clear and easy to understand. It is easy to see why this is relevant to DevOps.

The only criticism I have is that it would be nice for me personally to get some more information of the setup, but that is coming from someone who has never worked with Heroku.

**Comment by jzafar** [comment]
Hi,
Thanks for your demo, very good demo and you have clearly showed what you are going to present. I like, you told what you are going to achieve in new feature and then after few click you showed you have deployed new feature.  

I would add you should show some screens of configurations or tool that you have used for CI/CD.

**Comment by AristotelisKotsias** [comment]
Thank you everyone for your constructive feedbacks!

@johansettlin 
Both Travis-CI and Heroku are connected to the GitHub repo of the application. Whenever a push or pull request is made then Travis-CI is triggered and the tests are run. Whenever a push to the master brach is made then the application is automatically deployed on Heroku. Moreover, on Heroku you can wait (or not) for the CI tests to pass before automatically deploying the app.

@olapiv 
The only difference is that in the review, before you merge a pull request you can have an idea of how the app will look like so the reviewer might ask for modifications. The staging environment though, is where all the changes for a certain period could end up (like in a scrum sprint). And in many real situations access to the staging environment might have many stakeholders (not essentially developers) so they can see if the like the new features before deploy them to the production.

**Comment by sonderangebot10** [comment]
Thank you for the Demo! Airflow seems very interesting. The feedback:
- Interesting and new topic
- First time I've heard about Travis and Heroku but it seems easy to follow along seeing your demo
- The demo shows and overall good workflow

Overall, really good demo! 👍

**Pull request merged**
