### PR TITLE
viktorme-dljungg: essay, april 10

### PR DESCRIPTION
**Pull request by VIGGEEN**
# Assignment Proposal

## Title

From Monolith to Microservices: Why It’s a Nuanced Decision.

## Names and KTH ID

- Viktor Meyer (viktorme@kth.se)
- David Ljunggren (dljungg@kth.se)

## Deadline

- April 10

## Category

- Essay

## Description

We introduce the concept of different architectural patterns in the context of the modern cloud. We briefly describe trade-offs associated with Monolith, Distributed Monolith and Microservice approaches. We examine the cost and challenges of migrating an existing monolith to a microservice architecture. We describe proven migration patterns that have been used for successful architecture migrations in the past. Finally, we discuss things that need to go into consideration when weighing the pros and cons of migrating from monolith to microservices.

**Relevance**

Microservices is a hot topic that many see as the "gold-standard" architectural pattern. We investigate this notion to see if this is always the case and whether the more traditional Monolith could remain viable. In particular, many projects start out as monoliths and then transition into microservices - researching how and when to successfully transition is extremely relevant from a professional standpoint.

### CODE REVIEW

**Comment by Deee92** [comment]
Hi @VIGGEEN, we've had a similar essay contribution in the course before. Please propose a new topic for your essay.

**Comment by dague1** [comment]
> Hi @VIGGEEN, we've had a similar essay contribution in the course before. Please propose a new topic for your essay.

Hi @Deee92,

If our essay aims to describe concrete challenges when transitioning from a monolithic architectural pattern into a microservices architectural pattern, would that be alright?

**Comment by Deee92** [comment]
Hi @VIGGEEN, thanks! This should be okay. Can you change the PR description and README accordingly?
In the essay, it would be a good idea to illustrate with concrete examples, wherever possible.

**Comment by VIGGEEN** [comment]
> Hi @VIGGEEN, thanks! This should be okay. Can you change the PR description and README accordingly? In the essay, it would be a good idea to illustrate with concrete examples, wherever possible.

@Deee92 Thanks for the feedback.

Please review the updated README.

**Pull request merged**
