### PR TITLE
Presentation Topic for week 3: Testing of CI pipeline

### PR DESCRIPTION
**Pull request by cevataykans**
We will look through the topic and pick up a detailed question/topic in CI/CD. Our current question is: how do you test the tester? Testing the CI pipeline.

Group Members:
* Cevat Aykan Sevinc sevinc@kth.se
* George Rezkalla rezkalla@kth.se

### CODE REVIEW

**Comment by SophieHYe** [comment]
Hello,
Could you please update this PR when you have a detailed topic description. Then we will discuss and merge your PR.

**Comment by cevataykans** [comment]
We have updated our presentation topic proposal as: Testing of CI pipeline.

We are interested in the testing of the CI pipeline because it is an interesting concept to test a pipeline that is intended to find bugs. The question is: *how do you test the tester?

**Comment by SophieHYe** [comment]
Greate.  I merged your PR.

**Comment by georgewbar** [comment]
Thanks!

**Comment by gluckzhang** [comment]
Hi @cevataykans , have you decided to quit the course, or withdrawing this task? If so, I would like to remove the folder `sevinc-rezkalla` as @georgewbar is proposing another PR now.

**Comment by cevataykans** [comment]
Hello @gluckzhang, yes I have quit the course.

**Comment by gluckzhang** [comment]
Got it, thanks for the response @cevataykans !

**Pull request merged**
