### PR TITLE
Setting Continuous Integration for Asp.Net Core project with Github Action

### PR DESCRIPTION
**Pull request by Sabrina459**
# Assignment Proposal

## Title

Setting Continuous Integration for Asp.Net Core project with Github Action

## Names and KTH ID
  - Sabrina Saiko

## Deadline

Task 1

## Category

Demo

## Description

Asp.Net Core is commonly used technology for building modern cloud based internet connected applications, such as web apps, IoT apps and mobile backends. The main thing in developing such types of software is reliability. So its testing should be as relevant as possible and protect application from fatal failures and chalange is in choosing the most accetable way.

In this demonstration, I show how Asp.Net Core based projects can be tested in real life and how to set up and run such tests with the respective frameworks.

### CODE REVIEW

**Comment by javierron** [comment]
Hello @Sabrina459, many thanks for your proposal. The task you describe is very relevant to this course.

#### Question
- This is related to testing and CI, do you plan on presenting on Week 2 (tomorrow)?

#### Actions
- Please specify in the description which tool(s) you will be using to test .net core projects.
- Please update the path of your readme file. It should be on `contributions/presentation/week2-testing-and-CI/<your-KTH-id>/README.md`
- Please update the headers of the readme file so that they match the ones predefined.

**Comment by Sabrina459** [comment]
> Hello @Sabrina459, many thanks for your proposal. The task you describe is very relevant to this course.
> 
> #### Question
> * This is related to testing and CI, do you plan on presenting on Week 2 (tomorrow)?
> 
> #### Actions
> * Please specify in the description which tool(s) you will be using to test .net core projects.
> * Please update the path of your readme file. It should be on `contributions/presentation/week2-testing-and-CI/<your-KTH-id>/README.md`
> * Please update the headers of the readme file so that they match the ones predefined.

Hello, I am happy to read it but it seems like I am not formally allowed to take part in this course. So someone, if they want, may choose this topic for their task.

**Comment by Sabrina459** [comment]
Hello, I am happy to read it but it seems like I am not formally allowed to
take part in this course. So someone, if they want, may choose this topic
for their task.


Best regards, Sabrina

пн, 28 мар. 2022 г., 17:21 Javier Ron Arteaga ***@***.***>:

**Comment by Deee92** [comment]
Hi @javierron, perhaps we should close this one.

**Pull request closed without merging**
