### PR TITLE
Essay submission for feedback: DevOps with Azure

### PR DESCRIPTION
**Pull request by johanmallobakken**
# This is a draft for feedback, not the final submission

## The original proposal
I want to write an essay on Azure DevOps Services. 

The essay will cover:
- Intro to DevOps
- What is Azure DevOps?
- In short the background/history 
- Why use Azure DevOps?
- How to use Azure DevOps?
- Services and tools and how they can be applied to the different phases in the application lifecycle.  (Boards, Pipelines, Repos, Artifacts, Testing)
- How Azure DevOps and it's services compare to other tools and services (e.g. Jenkins and Azure DevOps Pipelines, JIRA and Azure DevOps Boards, GitLab and Azure DevOps)
- Conclusion/Summary

## Members
Johan Mallo Bakken <johanmb@kth.se> [johanmb](https://github.com/johanmallobakken)

### CODE REVIEW

**Comment by johanmallobakken** [comment]
Hey @hassbring  , this is my first draft. Looking forward to your feedback :)

**Comment by hassbring** [comment]
# Feedback submission (Essay): DevOps with Azure #1404

This comment serves as Feedback on the Essay *draft* **DevOps with Azure [#1404](https://github.com/KTH/devops-course/pull/1404)**, written by Johan Mallo Bakken (johanmb@kth.se) [johanmallobakken](https://github.com/johanmallobakken). Essay *proposal* PR: Azure [#1057](https://github.com/KTH/devops-course/pull/1057).  The feedback is hereby provided within 24 hours after task submission. 

## Member / Feedback giver
Isak Hassbring (isakha@kth.se)
Github: [hassbring](https://github.com/hassbring)
Original Feedback Proposal PR: [#1154](https://github.com/KTH/devops-course/pull/1154).

## Foreword
The goal of this feedback is to help the reciever to reach as many *yes'* and *remarkables* as possible. Hence, the basis for the feedback is the grading table with its 12 points. The feedback will be provided in a clear and consise manner even though it might result in it being anticipated as a bit harsh. Please note that this is not in any way the will of the author 😊 .  The only aim, as mentioned above, is to respectfully help the reciever reach an as high grading as possible, within the scope of this task. 
Now - the actual feedback: 

## Strengths
First of all - very interesting essay overall with lots of potential! I learned a lot while reading it which was great fun, sience I've been looking forward getting to know Azure better. **Gold star** for great figures, such as:
* The visualization / table of Azure DevOps five main services is very clear and gives the reader a quick and solid understanding. Very good!
* Image on page 3 that links the devops cycle to Azure services is superb.

These add a lot of value to the essay as a whole. Remarkable figures in my opition! 

Moving on to what could easily be improved:

## Potential Improvements

As mentioned, the feedback will follow the structure of the [essay grading table](https://github.com/KTH/devops-course/blob/2021/grading-criteria.md#essays).

**Title:** The title "Azure devops" does the job. But however is a bit flat and could be improved. Add some color to it, and try to come up with a slightly more interesting title that catches the eye and interest of a potential reader.

**Well-structured:** The structure is ok, but could easily be improved by using a tree-like structure. A suggestion could be to make a section called "Introduction" that addresses the entire essay, then a "Background" and then put "DevOps", "Azure", "Azure history", "Why Azure" in it as subsections. Pro-tip here is to move over to LaTeX, it more or less serves as a gold standard for proper document structures. Lastly, I would personally love to see a table of contents. 

**Introduction:** The introduction should be rewritten and restructured. I think that the reader would like to start out with being told what Azure is, not devops. Start with something like: *"Azure DevOps is a set of cloud hosted DevOps services that work for any language targeting any platform. These set of DevOps services, aim to provide everything one needs to go from an idea to a working piece of software."* from the section **"What is Azure DevOps?"**. 

**Conclusion:** The conclusion is sound and factual, which is good. But it could be a bit more lively, perhaps. *One way* of improving it could be to raise some quesions before it, and try to answer them. 

**Self-contained:** Yes, generally. However when mentioning third party services or tools, ad a link or reference to them. 

**Innovative:** Yes, the figures are innovative in my opinion.

**Figures:** As mentioned above, great figures. Perhaps name them (Fig. 1,2,3...) and add a short image text.


**Sound:** The essay is somewhat sound, factual and accurate. Perhaps would be better to use LaTeX, and furthermore please try to formalize the language a bit if possible. Also, formal way of using acronyms is to introduce it right after the first time the phrase is introduced. E.g. instead of *Team Foundation Server... ...TLS...*, write *Team Foundation Server **(TLS)**... ...TLS*. This is the formal way.

**References:** The essay contains a proper amount of sources. Some better than others. However - if you move over to LaTeX you can use BibTeX reference formatting which makes it a lot easier to work with, both as a reader and a writer. Also, please use a standard such as Harvard or Oxford. 

**Elegant:** Although it is somewhat visually appealing as of today, it could be improved to a remarkable state by "migrating" to LaTeX.

**Relevant:** Yes - the essay definetly addresses a topic that is relevant for DevOps. 

**Other:**
Personally I think you could rename and reframe the competitor comparision to a "Critical reflection". Would be a good way of connecting better to the Conclusion. This seciton is already very interesting and could be focused on more. In combination - you could perhaps shorten the "how to use" section. Furthermore, to add more weight to the critical point of view, consider including a critical source such as e.g. [this very unhappy Azure user](https://sysadminadventures.com/2016/04/05/why-you-must-not-use-azure-if-you-want-to-keep-your-sanity/) or simliar. 

### Key actionable improvements
* Improve introduction *(see above for detail)*
* Improve conclusion *(see above for detail)*
* Migrate to Latex *(see above for detail)*
* Fix references *(see above for detail)*
* Shorten/change how to use section and use the space to focus on the Critical Reflection / Competitor section.
* Fix structure - use tree structure as described above
* Come up with a slightly more interesting title that catches the eye and interest of a potential reader.
* Grammar check the whole documents an extra time before handing in. Nothing big but some minor errors.

**Comment by johanmallobakken** [comment]
> # Feedback submission (Essay): DevOps with Azure #1404
> This comment serves as Feedback on the Essay _draft_ **DevOps with Azure [#1404](https://github.com/KTH/devops-course/pull/1404)**, written by Johan Mallo Bakken ([johanmb@kth.se](mailto:johanmb@kth.se)) [johanmallobakken](https://github.com/johanmallobakken). Essay _proposal_ PR: Azure [#1057](https://github.com/KTH/devops-course/pull/1057). The feedback is hereby provided within 24 hours after task submission.
> 
> ## Member / Feedback giver
> Isak Hassbring ([isakha@kth.se](mailto:isakha@kth.se))
> Github: [hassbring](https://github.com/hassbring)
> Original Feedback Proposal PR: [#1154](https://github.com/KTH/devops-course/pull/1154).
> 
> ## Foreword
> The goal of this feedback is to help the reciever to reach as many _yes'_ and _remarkables_ as possible. Hence, the basis for the feedback is the grading table with its 12 points. The feedback will be provided in a clear and consise manner even though it might result in it being anticipated as a bit harsh. Please note that this is not in any way the will of the author 😊 . The only aim, as mentioned above, is to respectfully help the reciever reach an as high grading as possible, within the scope of this task.
> Now - the actual feedback:
> 
> ## Strengths
> First of all - very interesting essay overall with lots of potential! I learned a lot while reading it which was great fun, sience I've been looking forward getting to know Azure better. **Gold star** for great figures, such as:
> 
> * The visualization / table of Azure DevOps five main services is very clear and gives the reader a quick and solid understanding. Very good!
> * Image on page 3 that links the devops cycle to Azure services is superb.
> 
> These add a lot of value to the essay as a whole. Remarkable figures in my opition!
> 
> Moving on to what could easily be improved:
> 
> ## Potential Improvements
> As mentioned, the feedback will follow the structure of the [essay grading table](https://github.com/KTH/devops-course/blob/2021/grading-criteria.md#essays).
> 
> **Title:** The title "Azure devops" does the job. But however is a bit flat and could be improved. Add some color to it, and try to come up with a slightly more interesting title that catches the eye and interest of a potential reader.
> 
> **Well-structured:** The structure is ok, but could easily be improved by using a tree-like structure. A suggestion could be to make a section called "Introduction" that addresses the entire essay, then a "Background" and then put "DevOps", "Azure", "Azure history", "Why Azure" in it as subsections. Pro-tip here is to move over to LaTeX, it more or less serves as a gold standard for proper document structures. Lastly, I would personally love to see a table of contents.
> 
> **Introduction:** The introduction should be rewritten and restructured. I think that the reader would like to start out with being told what Azure is, not devops. Start with something like: _"Azure DevOps is a set of cloud hosted DevOps services that work for any language targeting any platform. These set of DevOps services, aim to provide everything one needs to go from an idea to a working piece of software."_ from the section **"What is Azure DevOps?"**.
> 
> **Conclusion:** The conclusion is sound and factual, which is good. But it could be a bit more lively, perhaps. _One way_ of improving it could be to raise some quesions before it, and try to answer them.
> 
> **Self-contained:** Yes, generally. However when mentioning third party services or tools, ad a link or reference to them.
> 
> **Innovative:** Yes, the figures are innovative in my opinion.
> 
> **Figures:** As mentioned above, great figures. Perhaps name them (Fig. 1,2,3...) and add a short image text.
> 
> **Sound:** The essay is somewhat sound, factual and accurate. Perhaps would be better to use LaTeX, and furthermore please try to formalize the language a bit if possible. Also, formal way of using acronyms is to introduce it right after the first time the phrase is introduced. E.g. instead of _Team Foundation Server... ...TLS..._, write _Team Foundation Server **(TLS)**... ...TLS_. This is the formal way.
> 
> **References:** The essay contains a proper amount of sources. Some better than others. However - if you move over to LaTeX you can use BibTeX reference formatting which makes it a lot easier to work with, both as a reader and a writer. Also, please use a standard such as Harvard or Oxford.
> 
> **Elegant:** Although it is somewhat visually appealing as of today, it could be improved to a remarkable state by "migrating" to LaTeX.
> 
> **Relevant:** Yes - the essay definetly addresses a topic that is relevant for DevOps.
> 
> **Other:**
> Personally I think you could rename and reframe the competitor comparision to a "Critical reflection". Would be a good way of connecting better to the Conclusion. This seciton is already very interesting and could be focused on more. In combination - you could perhaps shorten the "how to use" section. Furthermore, to add more weight to the critical point of view, consider including a critical source such as e.g. [this very unhappy Azure user](https://sysadminadventures.com/2016/04/05/why-you-must-not-use-azure-if-you-want-to-keep-your-sanity/) or simliar.
> 
> ### Key actionable improvements
> * Improve introduction _(see above for detail)_
> * Improve conclusion _(see above for detail)_
> * Migrate to Latex _(see above for detail)_
> * Fix references _(see above for detail)_
> * Shorten/change how to use section and use the space to focus on the Critical Reflection / Competitor section.
> * Fix structure - use tree structure as described above
> * Come up with a slightly more interesting title that catches the eye and interest of a potential reader.
> * Grammar check the whole documents an extra time before handing in. Nothing big but some minor errors.

Thanks for great feedback! These changes have now been applied in my final submission on PR #1450 :)

**Comment by khesoem** [comment]
Since there is an updated version (#1450), I'll close this PR. @johanmallobakken Please let me know if you think we are missing something by closing this PR.

**Pull request closed without merging**
