### PR TITLE
Executable tutorial proposal

### PR DESCRIPTION
**Pull request by Alexanderliu2002**
# Assignment Proposal

## Title

Building and integrating a slack bot with GitHub actions using Node.js

## Names and KTH ID

  - Alexander Liu (aleliu@kth.se)
  - Gustaf Svensson (gussvens@kth.se)

## Deadline

- Task 3

## Category

- Executable tutorial

## Description

In our tutorial we will show how to set up a slack bot using node.js to monitor GitHub actions through notification in a slack channel. The bot will be able to parse github logs into readable slack messages in order to simplify continuous development and monitoring.

**Relevance**

Effective monitoring and automation is crucial to the DevOps life cycle. By integrating slack bot with GitHub actions developers can get real-time status updates on ongoing processes directly in their slack workspace. Additionally, developers can trigger pre-defined common events through slack increasing the efficiency of the entire process. The use of slack streamlines the continuous devlopment and monitoring process for developers and is a critical part in the DevOps cycle.

### CODE REVIEW

**Comment by algomaster99** [comment]
Hi!
Does it require opening a slack account? It would not fulfill "no-account" criteria of executable tutorial.

**Comment by Alexanderliu2002** [comment]
Changed PR to new proposal.

**Comment by algomaster99** [comment]
Discussed in person. Please edit the proposal.

**Comment by Alexanderliu2002** [comment]
Updated PR to also include parsing of logs from github into slack as discussed

**Comment by algomaster99** [comment]
Looks good! Merging :)

**Comment by leegrash** [comment]
@algomaster99 a quick question - we are currently working on ways to process and parse the logs of a github action and got an idea. It would be cool to use the GPT API to process the logs since it integrates "new" technologies and ways of working with software development. This does, however, pose a problem within the context of the Executable Tutorial - for this approach to be possible we would need a GPT api key which requires an account. What are your thoughts on the matter?

**Comment by algomaster99** [comment]
Hi @leegrash ! It should be okay I guess. In our research group, we have access to GPT so we should be able to use our own API key so please go for it.

@monperrus I will take this work on me. Will assign it to myself :)

**Pull request merged**
