### PR TITLE
Executable tutorial submission - Flox

### PR DESCRIPTION
**Pull request by bjornthiberg**
# Assignment Proposal

## Title

Creating and using Flox environment(s) in an existing project.

## Names and KTH ID

- Björn Thiberg (bthiberg@kth.se)
- Noak Jönsson (noakj@kth.se)

## Deadline

- Task 3

## Category

- Executable Tutorial

## Description

We had a visit during one of the lectures by a [Flox](https://flox.dev/docs/) developer. Exploring this cool piece of software, we found few if any tutorials on how to use it.

This tutorial goes through the main functionality of Flox. Specifically, how to create a Flox environment for an existing project, add dependencies and search for packages, and create a service. It also goes through how the Flox manifest file works.

[The tutorial can be found on KillerCoda here.](https://killercoda.com/bjornthiberg/scenario/flox)
[
The repository for the tutorial can be found here.](https://github.com/bjornthiberg/DD2482-executable-tutorial)

**Relevance**

Flox is relevant to DevOps since it allows the user to create and manageme reproducible, isolated, and portable development environments. This helps with solving the “works on my machine” DevOps problem across different testing, staging and dev environments. Flox provides a platform for managing dependencies, environments, and development tools in a containerized manner. These containerized environments can then be shared, submitted to version control, and be used as part of CI/CD pipelines.

### CODE REVIEW

**Comment by javierron** [comment]
@bjornthiberg Thanks for the proposal, I'll merge it, but note that it is not allowed to change the description of the task.
If the submission does not meet the original proposal, it will be graded as a repeat.

**Comment by bjornthiberg** [comment]
@javierron Hey! The two changes in the description where
1. To more thoroughly explain the contents.
2. To change this line, which specifically references what the tutorial _might_ include:

> "After that, we might include layering multiple environments, services, enviroonment variables, depending on what level of complexity the tutorial ends up having."

But the content, purpose and structure of the tutorial is exactly as we specified in the proposal, so there should be no issue :+1:

**Comment by algomaster99** [comment]
@bjornthiberg I am trying to run your tutorial.

I keep getting the following error after adding configuration for `vars` and `services.flask`. I tired to debug it on my own, but could not so please help here.
image

**Comment by nobnj** [comment]
@algomaster99 I have pushed an update with corrected instructions.

**Comment by algomaster99** [comment]
It is fixed now. Thanks!

**Pull request merged**
