### PR TITLE
feedback proposal for #965

### PR DESCRIPTION
**Pull request by Chen-Zidi**
# Feedback

## Members
Zidi Chen, zidi@kth.se, https://github.com/Chen-Zidi
Yuehao Sui, yuehao@kth.se, https://github.com/amaothree

## Proposal

We would like to do a feedback for Essay: Comparison of DevOps and SRE #965.

### CODE REVIEW

**Comment by SophieHYe** [comment]
Your feedback proposal is clear. Thanks!

**Comment by Chen-Zidi** [comment]
The file changes are for the proposals that have already accepted and merged. I would like to change the team members in those files. So should I maybe create a new pull request for that?

**Comment by SophieHYe** [comment]
Ok. I will merge your PR this time. Next time please create a separate PR for an update :) Thanks.

**Comment by SophieHYe** [comment]
@Chen-Zidi,
Please be noted that your did not remove your old tutorial folder in the PR and created a new one. 
https://github.com/KTH/devops-course/tree/2021/contributions/executable-tutorial 
You can only keep one folder with your id. Please make a new PR and fix this problem. Thanks!

**Comment by Chen-Zidi** [comment]
Ok. Thanks a lot.

**Pull request merged**
