### PR TITLE
Executable tutorial proposal: Using GitLab CI/CD to setup a Unity project with automated testing

### PR DESCRIPTION
**Pull request by ChangGabriel**
# Using GitLab CI/CD to setup a Unity project with automated testing
## Members
Gabriel Chang(gchang@kth.se)
GitHub: [ChangGabriel](https://github.com/ChangGabriel)

## Proposal
Automating your testing each time the code is integrated will allow you to find bugs as early as possible and fix them faster.

I plan to do a Katacoda tutorial going through how to set up a Unity project and use GitLab CI/CD for automated testing.
In the tutorial you will learn:

- Setup a Gitlab project repo
- Create a Unity project with tests that later will be run automatically
- How to setup Gitlab CI/CD and how to navigate it
- How to register your own machine as CI runner in your project
- How to connect Unity with Gitlab CI/CD so that it automatically runs the tests in the project on every push

### CODE REVIEW

**Review by cesarsotovalero — APPROVED** [review]

**Comment by cesarsotovalero** [comment]
Hi @ChangGabriel, your proposal LGTM. I'll merge, good luck!

**Comment by ghost** [comment]
Hi! I would like to give feedback on this tutorial

**Comment by ChangGabriel** [comment]
@cesarsotovalero Hi, I'm wondering if it is ok for me to change the tutorial to be run locally instead of Katacoda? 
Katacoda is unfortunately not suited for this tutorial.

**Comment by khesoem** [comment]
Hi @ChangGabriel 

To make any change in the proposal you should submit a new PR. You are allowed make the change you mentioned.

**Pull request merged**
