### PR TITLE
Tutorial proposal: Implementing Imgbot on OSS

### PR DESCRIPTION
**Pull request by louisezetterlund**
# Tutorial Proposal
 ## Members
 Louise Zetterlund (louiseze@kth.se)
 Johanna Iivanainen(jii@kth.se)

   ## Topic
 Implementing [Imgbot](https://imgbot.net/) on OSS 
  Our plan is to create a video-tutorial on how to use Imgbot and how to implement it on your Open Source Software.

   ## Tutorial
  We will show step-by-step how to implement it and how to use it.

### CODE REVIEW

**Comment by gluckzhang** [comment]
Hi @louisezetterlund , Imgbot is an interesting project, thanks for the PR! After taking a look at their webpage (https://github.com/marketplace/imgbot), I feel like **integrating** (not **implementing**) Imgbot into a project is sort of straightforward. Because it is a GitHub app that could be installed directly.

Maybe the tutorial could introduce how to set up a GitHub app or action, which helps to improve the DevOps flow. You could still use Imgbot as an example in the beginning. What do you think?

Regarding previous discussions: #345

**Comment by johannaii** [comment]
@gluckzhang Thank you for your comments! Is it okay if we make a more general tutorial on how to set up a Github app into you own project, and then use imgbot or another existing app as an example on how to do it? Or do you mean that we should build our own Github app or action to demonstrate it?

**Comment by gluckzhang** [comment]
> @gluckzhang Thank you for your comments! Is it okay if we make a more general tutorial on how to set up a Github app into you own project, and then use imgbot or another existing app as an example on how to do it? Or do you mean that we should build our own Github app or action to demonstrate it?

Hi @johannaii , I think both directions are fine since you will learn lots of stuff through this. If you would like to introduce GitHub app / action generally, you could focus more on the architecture and setup, then use Imgbot as an example. If you would like to make a tutorial about GitHub app development, then you may briefly introduce the concepts and show how to development a basic app.

The content of your tutorial should be rich enough anyway :) The former could introduce more features like github authentication, github app market, etc, while the latter could introduce development and deployment methods using basic features of github app.

**Comment by gluckzhang** [comment]
The new proposal has been merged. I will close this PR :)

**Pull request closed without merging**
