### PR TITLE
[Repeat] Essay : Role of DevOps in minimizing downtime on applications using continuous deployment

### PR DESCRIPTION
**Pull request by yuxinmmmm**

### CODE REVIEW

**Comment by khesoem** [comment]
Hi @yuxinmmmm 

You have provided [three PDF files](https://github.com/KTH/devops-course/pull/1556/files). Which one is the final one? Can you remove the extra 2?

**Comment by yuxinmmmm** [comment]
> Hi @yuxinmmmm
> 
> You have provided [three PDF files](https://github.com/KTH/devops-course/pull/1556/files). Which one is the final one? Can you remove the extra 2?

Hi, I deleted the extra two files. Do you still see three PDF files? I will try to fix it :)
And Repeat_Essay_Role of DevOps in minimizing downtime on application using continuous deployment (1).pdf is the right one.

**Comment by khesoem** [comment]
> > Hi @yuxinmmmm
> > You have provided [three PDF files](https://github.com/KTH/devops-course/pull/1556/files). Which one is the final one? Can you remove the extra 2?
> 
> Hi, I deleted the extra two files. Do you still see three PDF files? I will try to fix it :)
> And Repeat_Essay_Role of DevOps in minimizing downtime on application using continuous deployment (1).pdf is the right one.

I double checked your repo, I think it should be fine.

**Comment by yuxinmmmm** [comment]
> > > Hi @yuxinmmmm
> > > You have provided [three PDF files](https://github.com/KTH/devops-course/pull/1556/files). Which one is the final one? Can you remove the extra 2?
> > 
> > 
> > Hi, I deleted the extra two files. Do you still see three PDF files? I will try to fix it :)
> > And Repeat_Essay_Role of DevOps in minimizing downtime on application using continuous deployment (1).pdf is the right one.
> 
> I double checked your repo, I think it should be fine.

THANKS :)

**Pull request merged**
