### PR TITLE
dljungg-taox: Presentation proposal, week 3

### PR DESCRIPTION
**Pull request by TAOFOR4**
# Assignment Proposal

## Title

Ensuring Security in CI/CD Pipeline with SonarQube

## Names and KTH ID

  - David Ljunggren (dljungg@kth.se)
  - Tao Xiong (taox@kth.se)

## Deadline

-Week 3

## Category

- Presentation

## Description

We would like to address some key security risks in CI/CD pipelines, and how some of these risks can be mitigated using SonarQube Static Application Security Testing (SAST).

**Relevance**

Organizations are able to produce higher quality code more quickly by automating CI/CD throughout the development, testing, production, and monitoring stages of the software development lifecycle. Nowadays, many companies fully rely on their CI/CD pipelines in the delivery of their software. It is therefore essential that the pipeline remains secure.

### CODE REVIEW

**Comment by TAOFOR4** [comment]
> Missing student registration :David
> 
> If not from your group, fetch the upstream.

Hi, you mean David didn't register in the first lecture?

**Comment by javierron** [comment]
Hello @TAOFOR4,
Thanks for the proposal. Please fix the PR description to contain the same info as your README file.

Also, the topic you have chosen is very broad.
I suggest that you choose a smaller and better defined scope, so that you can make an in-depth study and presentation on the topic.

**Comment by TAOFOR4** [comment]
> 

Hi,
I have changed the PR description and do we need change the proposal into a smaller topic right now or we can do it later when working on the specific content?

**Comment by javierron** [comment]
@TAOFOR4 

You need to change the topic and scope of the proposal and motivate it before we merge this PR.

**Comment by TAOFOR4** [comment]
> @TAOFOR4
> 
> You need to change the topic and scope of the proposal and motivate it before we merge this PR.

**Comment by TAOFOR4** [comment]
> 

Hi,
We have changed our topic and scope into a smaller and specific one.

**Comment by javierron** [comment]
Hello, @TAOFOR4 
The topic you are proposing has been discussed previously in the course.
Also, after doing a Google search, I can see that there are many similar results.
We do not consider the proposal to be suitable for the course.

Consider changing it to something more technical: e.g. comparing some of the frameworks' specific advanced features.

**Comment by dague1** [comment]
Ill bump here! We want to start working on this if it's fine :)

**Comment by javierron** [comment]
Hello @dague1 @TAOFOR4 
This topic sounds interesting and very relevant. 
We've had presentations about SonarQube before, but not really focused on security. Try to cover the security issues and solutions related to CI/CD in depth during the presentation.

**Pull request merged**
