### PR TITLE
Presentation Proposal Week 4- DevOps in an Industry Implementation

### PR DESCRIPTION
**Pull request by hittesharma**
# Jenkins (Pipeline) in an Industry Implementation

Presentation by Hitesh Sharma (hiteshs@kth.se)

## Description:

(A) - Intro. on what is DevOps?
   As We know... 1 liner.

 - Different tools and technologies used in DevOps and discussion on them

 - Problem: What to learn?
   Solution: ...

(B) Technical discussion about Jenkins Pipeline
Content I will include as per your suggestions. I have to prepare it. It will not include docker to avoid any complexity but I will try to cover pipelines of Jenkins in depth.

(C) Conclusion and Questions

NOTE: I am targetting for distinction and will try to fulfill the majority of requirements. 
Items listed above is just proposal and may be added or deleted in the final version depending on their relevance.
All the discussions will be in line with my industry experience and on real-world facts.

### CODE REVIEW

**Comment by hittesharma** [comment]
@SophieHYe Kindly discuss or merge this pull request. Thanks!

**Comment by SophieHYe** [comment]
Hi,
The title of your presentation 'DevOps in an Industry Implementation' seems a bit general.
Your topic seems a bit broad as the first part focuses on different tools and technologies and the second part is about Jenkins Pipeline. Maybe you intended to provide the background of DevOps in the first part. Do you want to introduce and focus on the Jenkins Pipeline in your presentation?

**Comment by hittesharma** [comment]
Hi,

Here, I have seen sometimes students new in DevOps confuse about which technology to pick in DevOps and where to start. So I was targetting to help this out in my introduction. It might appear generic but it is the biggest problem for someone who is new in DevOps. Let me know if you want to avoid it.

I have noted down your inputs and updated the title, once I prepare my presentation fully by this weekend. I will share it with you for the second review as I don't want to loose distinction 🙂

**Comment by SophieHYe** [comment]
Hi @hittesharma,
Indeed your intention is excellent to give some background of DevOps. Please feel free to add them but try not to spend too much time only them. That's could be a good background and transition of introducing Jenkins pipeline which links the development and operation :) 

Great, you can share the slide with me if you want some feedback. Drop me an email to heye@kth.se. Now, I have merged your PR and we discuss it later!

**Pull request merged**
