### PR TITLE
Feedback proposal week 6: Security Linting in Python using Bandit

### PR DESCRIPTION
**Pull request by Alexanderliu2002**
# Assignment Proposal

Feedback on Executable tutorial: Security Linting in Python using Bandit

## Title

Feedback on executable tutorial: Security Linting in Python using Bandit

## Names and KTH ID

  - Alexander Liu (aleliu@kth.se)
  - Gustaf Svensson (gussvens@kth.se)

## Deadline

- Task 2

## Category

- Executable tutorial

## Description

Feedback on #2453 
Security Linting in Python using Bandit
https://github.com/KTH/devops-course/tree/2024/contributions/executable-tutorial/ieinberg-emilsjol

**Relevance**

Feedback and (code) review is important =)

### CODE REVIEW

**Comment by sofiabobadilla** [comment]
Hi @Alexanderliu2002 
Please find a partner for the task.

**Comment by leegrash** [comment]
I will do the feedback with Alexander :)

**Comment by sofiabobadilla** [comment]
@leegrash , @Alexanderliu2002  please update the folder, right now only has alexander username

**Comment by sofiabobadilla** [comment]
Great, :)
I'll merge now.

**Comment by arejula27** [comment]
We have to make the feedback for this tutorial, where is the link provided?

**Comment by Deee92** [comment]
Hi @Alexanderliu2002 and @leegrash, have you submitted this feedback yet? Please ping me when you do, thanks!

**Pull request merged**
