### PR TITLE
Essay : Role of DevOps in minimizing downtime on applications using continuous deployment

### PR DESCRIPTION
**Pull request by Renugaa**

### CODE REVIEW

**Comment by khesoem** [comment]
Seems that there is already a proposal for this essay: [https://github.com/KTH/devops-course/tree/2021/contributions/essay/renanb-yuxinm](https://github.com/KTH/devops-course/tree/2021/contributions/essay/renanb-yuxinm)

Why did you make this PR? Please add a description, the TAs do no necessarily remember previous discussions.

**Comment by Renugaa** [comment]
Hi @khaes-kth,

We have mistakenly merged all our branches before creating a pull request earlier. So, all our assignments ended up in the same pull request. We recently cleaned our repo by deleting the unwanted assignments from other branches and created separate branches for each assignment. And we created new pull requests for each assignment from different branches. 

Please consider the new ones and close the old PR #1080. 

Thanks,
Renugaa

**Comment by khesoem** [comment]
Hi @Renugaa 

The old PR #1080 is already merged and cannot be closed anymore. But as far as I understand, the content of that PR almost the same as this one. If this is right, we can close this PR safely and we will still have your essay proposal in `contributions/essay/renanb-yuxinm/README.md`. Is this OK?

**Comment by Renugaa** [comment]
Hi @khaes-kth,

Yes. You can close this PR! We will use the old PR #1080 to publish our Essay! 

Thanks,
Renugaa

**Pull request closed without merging**
