### PR TITLE
Executable tutorial: Travis CI React tests

### PR DESCRIPTION
**Pull request by George-Bassilious**

### CODE REVIEW

**Comment by SophieHYe** [comment]
Hi, 
Please add more information about your tutorial proposal, so that we can assess if your PR is novel and original enough to be merged.  

Specifically, please add preliminary plan for your thesis, your motivation, the novelty statement of your tutorial. Thanks!

**Comment by George-Bassilious** [comment]
We have added some more information now hopefully it is sufficient!

**Comment by George-Bassilious** [comment]
@SophieHYe We have updates now, is it better?

**Comment by SophieHYe** [comment]
Your PR looks good to me. I am merging it now. Thanks.

**Pull request merged**
