### PR TITLE
Final Submission: Essay - Transitioning from DevOps to DevSecOps

### PR DESCRIPTION
**Pull request by BrorSebastianSjovald**
# Assignment Proposal

## Title

Transitioning from DevOps to DevSecOps

## Names and KTH ID
  - Sebastian Sjövald (sjovald@kth.se)
  - Vilma Jalava (vilmaj@kth.se)

## Deadline

Deadline task 3

## Category

Essay

## Description

Subject: Transitioning from DevOps to DevSecOps 

Why: In our exploratory work, we found that the transtion from a DevOps environment to a DevSecOps one usually comes with a lot of new tools and techniques. We plan to explain normal tools and challenges found in DevSecOps in contrast to a normal DevOps one. These are tools such as SAST, DAST, IAST and RASP with challenges such as lack of expertise and transparency between security and devops.

Structure of final essay:
- Introduction
- Background
- The transition from DevOps to DevSecOps
- Conclusion

Link to PDF: 
[Transitioning from DevOps to DevSecOps](https://github.com/BrorSebastianSjovald/devops-course/blob/bbcec283ca780223829030995094569f0f57adcd/contributions/essay/sjovald-vilmaj/Transitioning_from_DevOps_to_DevSecOps.pdf)

### CODE REVIEW

**Comment by joloev** [comment]
Interesting topic @BrorSebastianSjovald! I would like to give feedback on your essay. Would it be okay for you?

**Comment by joloev** [comment]
# Feedback for Transitioning from DevOps to DevSecOps
_________________________________

The essay is highly relevant for DevOps as it discusses the differences between DevOps and DevSecOps, the challenges that arise when transitioning from DevOps and some important concepts and tools used in DevSecOps.

## High level strengths and weaknesses of the Essay

### Strengths

- The description of the differences between DevOps and DevSecOps is clear.
- Referencing is done neatly in each subsection discussing the different concepts in DevSecOps, and an appropriate amount of references is used.
- The essay is sound, factual and accurate. References are used well to support claims and make descriptions of concepts accurate. 
- The essay is definitely elegant and appealing. 

### Weaknesses

- The essay contains a small reflective part but which could be extended.
- The state of art in terms of what tools should be adopted is explained. However, the essay does not position where the research is at in terms of overall challenges. 
- The essay brings up the challenges such as lack of experienced personnel, research and tools. However, it does not really state the problem with it.

## Feedback on each section

### 1. Introduction
Great introduction to the topic of the essay which is fully in line with the title. The title could perhaps be adjusted to Challenges when transforming from DevOps to DevSecOps. However, even though one can guess, “a lack of experienced personnel, research and tools” are challenges it is not super clear this is a problem and what impacts it may have. 
 
### 2 Background
The background section is very strong. The descriptions of both DevOps in part 2.1 and DevSecOps in part 2.2 are clear and easy to understand. The differences between these two key concepts are clearly explained. 
3 The transition from DevOps to DevSecOps
It is a bit unclear whether this section belongs to the background, if it is some sort of result section or a discussion of the challenges faced. 

### 3.1 Challenges
This part is also well written. However, it feels rather similar to the information given in section 3. We interpret this section to inform what needs to be done in order to make a transition between DevOps and DevSecOps successful. Both sections discuss challenges even though this section makes it more clear that the things needed to be done are challenging. Section 3 and 3.1 could be unified under a section called Challenges. Our suggestion would be to rename part 3 to Challenges and rename subsection 3.1 to A big cultural change.

### 3.2 Adopting DevSecOps tools
This part also becomes a bit problematic. The reader has to guess if this is still one of the challenges, which is mentioned in the introduction. Other than that this part is very good. All subsections 3.2.1 Static Application Security Testing, 3.2.2 Dynamic Application Security Testing, 3.2.3 Interactive Application Security Testing and 3.2.4 Run-time Application Security Protection are well written. The descriptions of these concepts are easy to understand and the referencing in these parts follows a very coherent pattern that makes this part sound factual and accurate, as well as elegant and visually appealing. It would be fun to have some more information on the tools you mention but it may be beyond the scope of this essay.

### 4 Conclusion
The conclusion is also good as it wraps up what has been brought up earlier. There is one part of the conclusion showing some reflection which is nice for the reader. However, it would have been more appropriate to have a section only for a reflective discussion as it is rather limited. I believe this is the most interesting part of the essay where, based on the background you are able to reflect upon what will be the biggest challenges of the transition.

## Pointers to additional material
This systematic [review](https://www.researchgate.net/publication/354063693_Challenges_and_solutions_when_adopting_DevSecOps_A_systematic_review) would be a nice addition adding credibility to the concepts explained in the essay and give more substance to what, according to researchers, is worth focusing on in the transition to DevSecOps.

**Comment by BrorSebastianSjovald** [comment]
Hi @khaes-kth

I don't know how the feedback flow is supposed to work. I haven't visited this page in a long time (because work and other courses) and saw now that we received feedback. I thought we had to accept? 

I feel that it is unfair to the group that did the feedback cause their PR was accepted. But neither me or Vilma has the time to perform it right now

**Comment by khesoem** [comment]
@BrorSebastianSjovald : It is definitely encouraged that you act upon the feedback and improve your work based on it, however it is not necessary. No worries!

**Pull request merged**
