### PR TITLE
Submission Covid19: Help Fight Covid19 Social Web App

### PR DESCRIPTION
**Pull request by sujon2100**
Added folder and README.md file.

### CODE REVIEW

**Comment by gluckzhang** [comment]
Hi @sujon2100 , as a very basic rule in this course: every task should be registered via a PR first. Have you registered this task before, and got the proposal merged into the repo?

**Comment by sujon2100** [comment]
> Hi @sujon2100 , as a very basic rule in this course: every task should be registered via a PR first. Have you registered this task before, and got the proposal merged into the repo?
> 
> Or do you mean you are submitting a task proposal, instead of a final deliverable?
Hi @gluckzhang,

My group member has already created the project proposal before. Here is the link: https://github.com/Nick-Steele/devops-course/blob/master/contributions/covid19/nsteele-mhud/README.md.

So, I have created https://github.com/KTH/devops-course/pull/633 this because you have asked me to add comments in the readme file.

And finally, I have asked for feedback  here:https://github.com/KTH/devops-course/pull/601.

This project is already completed now we need feedback before final submission.

**Comment by Nick-Steele** [comment]
We already did this quite some some time ago our project was pushed to the covid-19 contributions in our folder.

**Comment by gluckzhang** [comment]
@sujon2100 @Nick-Steele , the proposal is located in your forked repo and is not proposed as a PR for a review. In the course repo, folder https://github.com/KTH/devops-course/tree/master/contributions/covid19, you will not find your registered task folder. By rule, only creating a proposal in your own forked repo, without submitting a proposal PR and getting it merged, is not considered as a valid task.

Anyway I'm checking the contents now to see if the project is qualified to be merged. Please pay attention to the task registeration rules. I think you have already done several PRs for your other tasks, correct?

**Comment by Nick-Steele** [comment]
Apologies, that was my mistake.

**Comment by gluckzhang** [comment]
@sujon2100 @Nick-Steele  I'm fine with the idea. Please correct the folder name in order to get the PR merged: https://github.com/KTH/devops-course/tree/master/contributions/covid19#how-to-register-your-topic

**Comment by sujon2100** [comment]
> @sujon2100 @Nick-Steele I'm fine with the idea. Please correct the folder name in order to get the PR merged: https://github.com/KTH/devops-course/tree/master/contributions/covid19#how-to-register-your-topic

Thank you @gluckzhang . I have changed the folder name, here you can see: https://github.com/KTH/devops-course/pull/633/files

**Comment by sujon2100** [comment]
Now could you register for the feedback? Here is the feedback pull request: #601
Thanks!

**Comment by gluckzhang** [comment]
Thanks for the update. Now the PR is merged.

**Comment by monperrus** [comment]
Feedback:

This is a first milestone.

Major points that are missing:
- link to a public repo with source code
- add a section "Background" in README that presents the used technologies
- presentation of the architecture of the app with a component diagram
- key metrics about the app (eg LOC)
- explanation of the testing setup used and coverage achieved
- explanation of the CI setup and detailed presentation of the pipelines
- explanation of the CD setup
- explanation of other DevOps aspects used
- novelty: explain what your application is unique and novel

Minor points:
- add fat captions to each figure to explain what they show and why they are interesting
- explain the dissemination plan: where did/will you advertise the website?
- don't copy the dev.azure.com README in this repo, it's not formatted correctly simply, add a link instead.

**Comment by sujon2100** [comment]
> Feedback:
> 
> This is a first milestone.
> 
> Major points that are missing:
> 
> * link to a public repo with source code
> * add a section "Background" in README that presents the used technologies
> * presentation of the architecture of the app with a component diagram
> * key metrics about the app (eg LOC)
> * explanation of the testing setup used and coverage achieved
> * explanation of the CI setup and detailed presentation of the pipelines
> * explanation of the CD setup
> * explanation of other DevOps aspects used
> * novelty: explain what your application is unique and novel
> 
> Minor points:
> 
> * add fat captions to each figure to explain what they show and why they are interesting
> * explain the dissemination plan: where did/will you advertise the website?
> * don't copy the dev.azure.com README in this repo, it's not formatted correctly simply, add a link instead.

Hi Martin,
Here is the completed feedback link for the COvid19 Project:
Final Report(Wiki): https://dev.azure.com/KthProject2020/NewKthCovidProject or https://dev.azure.com/KthProject2020/NewKthCovidProject/_wiki/wikis/NewKthCovidProject.wiki/2/Help-Fight-COVID-19-Web-App
Source: https://github.com/sujon2100/Covid19Source/tree/master/NewKthproject
ReadMe: contributions/covid19/nsteele-mhud/README.md
Website: https://kthcovid19webapp.azurewebsites.net/



> * List of correction
Major points that are missing:

(Done) link to a public repo with source code
(Done) add a section "Background" in README that presents the used technologies
(Done) presentation of the architecture of the app with a component diagram
(Done) key metrics about the app (eg LOC)
(Done) explanation of the testing setup used and coverage achieved
(Done) explanation of the CI setup and detailed presentation of the pipelines
(Done) explanation of the CD setup
(Done) explanation of other DevOps aspects used
(Done) novelty: explain what your application is unique and novel
Minor points:

(Done) add fat captions to each figure to explain what they show and why they are interesting
(Done) explain the dissemination plan: where did/will you advertise the website?
(Done) don't copy the dev.azure.com README in this repo, it's not formatted correctly simply, add a link instead.

Thanks!

Best regards
Helal

**Pull request merged**
