### PR TITLE
Executable tutorial task 3 proposal

### PR DESCRIPTION
**Pull request by muhammad1928**
executable tutorial

**The pull request must both contain a README.md and have description following this template:**

**The README.md file must be located in the directory**:

`contributions/executable-tutorial/week5/mnem/README.md`

# Assignment Proposal

## Title

Infrastructure as Code with Pulumi setup

## Names and KTH ID

 Muhammadsodiq Nematjanov (mnem@kth.se)

## Deadline

 task 3

## Category

Executable-tutorial

## Description

This tutorial offers a detailed, step-by-step guide on using Pulumi for Infrastructure as Code (IaC) to install, configure, and deploy an infrastructure that includes an NGINX web server and various services like NGINX and Redis, all within Docker containers. It walks through the process of defining and managing infrastructure resources using Pulumi, allowing users to provision and control their infrastructure in a declarative way. By following this guide, users will gain practical experience in utilizing Pulumi to apply DevOps principles in managing their infrastructure efficiently.

**Relevance**

This tutorial provides a concise guide on using Pulumi for Infrastructure as Code (IaC) to set up and deploy an NGINX web server and services like Redis in Docker containers. It covers the steps to define and manage infrastructure resources declaratively with Pulumi, giving users hands-on experience in applying DevOps practices to efficiently manage their infrastructure.

### CODE REVIEW

**Comment by muhammad1928** [comment]
hey, 
what should i do to fix this?

**Comment by sofiabobadilla** [comment]
Hi @muhammad1928 
Please find a partner for this task. (once you doo, change the folder name and the md file)
Regarding the ci error let me look at it in the meantime

**Comment by sofiabobadilla** [comment]
The ci problem is that you have nothing on the README.md file.
The same info you have in this content must be added on that file. See other merge PR for inspiration

**Comment by muhammad1928** [comment]
my partner is Quang M Nguyen. we are doing 2 separately executable projects. he said that u said it was okay to do it separately

**Review by muhammad1928 — COMMENTED** [review]
readme file is edited

**Comment by sofiabobadilla** [comment]
Hi @muhammad1928 ,
We only accept individual submission in very unique cases. 
Please search for a partner for this task.

**Comment by sofiabobadilla** [comment]
Regarding the ci, we are working to fix it. 
Once you add a partner on the file, the ci will run again and hopefully work this time.

**Comment by algomaster99** [comment]
@sofiabobadilla taking over this one.

@muhammad1928 your proposal looks extremely similar to https://github.com/KTH/devops-course/pull/2540. Even the description is similar. I suggest you to come up with something original.

**Comment by muhammad1928** [comment]
I have teamed up with another classmate instead of my previous one. which was doing #2540, thanks

**Comment by algomaster99** [comment]
> I have teamed up with another classmate instead of my previous one

That's okay, but I am asking you to choose another topic.

**Comment by muhammad1928** [comment]
oh okay, sorry this is the new PR #2582

**Pull request closed without merging**
