### PR TITLE
Feedback Proposal

### PR DESCRIPTION
**Pull request by arejula27**
# Assignment Proposal

## Title

Feedback for Executable Tutorial: Security Linting in Python using Bandit. 

## Names and KTH ID

  - Iñigo Aréjula Aísa (inigoaa@kth.se)
  - Lauren Llauradó (lllr@kth.se)

## Deadline

- Task 1

## Category

- Feedback

## Description

We will provide feedback on the executable tutorial "Security Linting in Python using Bandit"

Link https://github.com/KTH/devops-course/pull/2453

### CODE REVIEW

**Comment by sofiabobadilla** [comment]
Hi @arejula27 ,
Please link the PR of the executable tutorial  that you want to provide feedback.

**Comment by arejula27** [comment]
Done

**Comment by sofiabobadilla** [comment]
@arejula27 
I'll merge now :)

**Comment by arejula27** [comment]
The feedback should be written before the 3rd of October in their PR, right?

**Pull request merged**
