### PR TITLE
Presentation: Mobile backend as a Service in DevOps

### PR DESCRIPTION
**Pull request by LaraRos**

### CODE REVIEW

**Comment by khesoem** [comment]
Hi,

Please add your name, email, and github account to your readme.md file.

**Comment by LaraRos** [comment]
It was already there but I made it clearer @khaes-kth

**Comment by khesoem** [comment]
> It was already there but I made it clearer @khaes-kth

Good! I think I wasn't used to see the members' names at the end of the page. It seems you have also added a new member, which is fine.

Is the PR ready to be merged from your point of view?

**Comment by LaraRos** [comment]
Yes, seems fine! thanks! :) @khaes-kth

**Pull request merged**
