### PR TITLE
Feedback proposal to essay "From Chaos Monkey to Controlled Chaos - The History of Chaos Engineering"

### PR DESCRIPTION
**Pull request by ikhudur**
# Assignment Proposal

## Title

Feedback on essay `From Chaos Monkey to Controlled Chaos - The History of Chaos Engineering`

## Names and KTH ID

  - Ivan Khudur (ikhudur@kth.se)

## Deadline

Deadline 1 (2023-04-13 17.00)

## Category

- Feedback

## Description

I would like to submit feedback for this essay: https://github.com/KTH/devops-course/pull/2147

### CODE REVIEW

**Comment by khesoem** [comment]
Hi @ikhudur 

Your PR should add only one file, while it is adding two: https://github.com/KTH/devops-course/pull/2167/files

Please fix this. You may need to rebase to the upstream (KTH/devops-course) 2023 branch

**Comment by ikhudur** [comment]
@khaes-kth Ah, my apologise. Cant I just remove the erronous file?

**Comment by ikhudur** [comment]
Hello again @khaes-kth ,

Now I think I managed to remove the file, and all the remains is the correct feedback proposal file. Is that alright?

**Comment by khesoem** [comment]
you should add a README.md file not a README file. Can you fix this?

**Comment by ikhudur** [comment]
@khaes-kth I have updated the file to README.md

**Comment by ikhudur** [comment]
@khaes-kth And when I should do the final submission, do I use this PR, or do I create a new one?

**Comment by khesoem** [comment]
You should create a new PR for the final submission

**Pull request merged**
