### PR TITLE
Add initial essay proposal

### PR DESCRIPTION
**Pull request by ruwaid4**
# Essay Proposal
## Members
Ruwaid Louis (ruwaid@kth.se)
GitHub Username: ruwaid4

## Topic
The monitoring process:
* What tools are used
* What is monitored for different applications
* How the monitored data is used
* What some standard practices are

### CODE REVIEW

**Comment by gluckzhang** [comment]
Sounds nice, thanks @ruwaid123 !

**Comment by gluckzhang** [comment]
@ruwaid123 , to avoid the risk of being superficial or vague, you could think more about the scope and novelty even though the PR has been merged. For example, what are the 3 most related resources on the web and what are the novelty and differences of your own essay with respect to them?
We could have a meeting during lab sessions if you need more help :)

**Comment by ruwaid4** [comment]
There's nothing really groundbreaking happening in the field of monitoring right now, the chosen essay topic is more for me to get a better understanding of how the monitoring process works and not really to bring something new or extraordinary. It is to be a summary but still dive deeper than what most articles do. I could only find sources describing different parts of the monitoring process or summarizing the whole process very shallowly.

**Comment by ruwaid4** [comment]
@gluckzhang What about specifically looking into the monitoring process in the video game industry? Find out what kind of data is specific to video games and how it is used etc. Would that be a better scope? If so i will update the README.

**Comment by gluckzhang** [comment]
> @gluckzhang What about specifically looking into the monitoring process in the video game industry? Find out what kind of data is specific to video games and how it is used etc. Would that be a better scope? If so i will update the README.

Hi @ruwaid4 , I prefer this proposal because you will introduce the monitoring techniques generally first and then go deeper into a specific scenario. Let's update the README in this way. Please also add some key resources (e.g., 3 links) which you are going to read and cite. Thanks!

**Comment by ruwaid4** [comment]
@gluckzhang I have now updated the README, let me know if there is still something missing.

**Comment by gluckzhang** [comment]
Hi @ruwaid4 , thanks for the updates. This version is much better. Since this PR has been merged already, you could make another PR to update the existing `README` file :)

**Pull request merged**
