### PR TITLE
Final submission for open source contribution: Contributing to DevOps-exercises

### PR DESCRIPTION
**Pull request by Akseluhr**
# Assignment Proposal

## Title

Contributing to [devops-exercises](https://github.com/bregman-arie/devops-exercises)

## Names and KTH ID
  - Aksel Uhr (auhr@kth.se)
  - Abdullah Abdullah (aabdull@kth.se)

## Deadline

Task 3

## Category

Contribution to open-source

### Description

[devops-exercises](https://github.com/bregman-arie/devops-exercises) contains questions and exercises on various technical topics, related to DevOps.

We found that there were no questions about software supply chain and dependecny management, two highly relevant fields of DevSecOps. Therefore, we want to contribute with questions related to the mentioned fields. Our aim is to read research papers and documentation related to the topics and then formulate relevant questions and answers for this open source repo.

As of today, the repo has 22.5k stars, and is actively managed by more than 80 contributors. We have had initial discussions with the owner of the repo who are welcoming our idea.

Final Submission for open source contribution

Pull request can be found here: https://github.com/bregman-arie/devops-exercises/pull/229

All questions can be found here including answers:
https://docs.google.com/document/d/1j7vk94A7epkQvlB6b8qpqjcYIGSG0t9jsffEl8nQq-I/edit?usp=sharing

We opened a PR and had a nice discussion with the repo owner. On the first PR, we got some constructive feedback which we acted upon and modified our contribution accordingly. We hope that our contribution will be merged soon.

### CODE REVIEW

**Comment by javierron** [comment]
@Akseluhr Thanks for the submission!

To be able to merge, the merge conflict must be fixed first. Thanks!

**Comment by Akseluhr** [comment]
Should be fixed now @javierron have a nice weekend.

**Comment by Akseluhr** [comment]
Hi @javierron we're just wondering whether something is missing for the grade although it is merged here?

regards 
Aksel & Abdullah

**Comment by bbaudry** [comment]
@Akseluhr You have contributed interesting questions and have had a good conversation with the lead dev of the project. It is important that your PR is merged in order for you to pass the task. What is missing to get  https://github.com/bregman-arie/devops-exercises/pull/229 merged?

**Comment by Akseluhr** [comment]
Hi @bbaudry thanks for the comment. We have iteratively made changes w.r.t. the lead dev's feedback and our discussion. Last changes from our side was committed 4 days ago and it has not been reviewed yet. What has happened is that we kept getting new feedback iteratively for the answers and questions we wrote (that is - not all feedback at once, see the PR linked in the readme for clarification). So the reviewing process for merging has taken longer than expected. 

We hope that we will "pass" his checks with our most recent commit. Not sure when he has time though.

**Comment by Abdullah1428** [comment]
@bbaudry our PR is now merged after passing all the checks. hopefully it can be graded now. Thank you.

**Pull request merged**
