### PR TITLE
Presentation proposal: Devops and Security Week 4

### PR DESCRIPTION
**Pull request by eywoon**
Members:
Eyrún Þrastardóttir: eyrun@kth.se
Paul-Philip Mousulet: ppmo@kth.se

Topic: DevOps and security

We’ve been looking into the issue #18 (DevOps and Security)
and would like to do a presentation of one of the topics.
We’re still reading through the material posted in that issue and will define it further as soon as possible.

We're interested in why automated security is relevant to DevOps.

### CODE REVIEW

**Comment by gluckzhang** [comment]
Hi @eywoon , thanks for the WIP pull request. Looking forward to your updates :)

We will merge your PR after reviewing the concrete topic you choose. Please add a short statement (1-3 sentences) about the relevance and timeliness for DevOps and Security. Cheers.

**Comment by gluckzhang** [comment]
Hi @eywoon , any updates about this PR? Currently there have been 7 presentations for week3. Do you mind if we reschedule your proposal to week 4?

**Comment by eywoon** [comment]
Hi @gluckzhang, we're fine with it being moved one week :)

**Comment by gluckzhang** [comment]
> Hi @gluckzhang, we're fine with it being moved one week :)

Perfect, thanks! Since the PR still needs to be improved based on my previous comments, could you also update the folder when you add updates? Tack :)

**Comment by eywoon** [comment]
I put the proposal in the readme :)

**Comment by gluckzhang** [comment]
Perfect. The PR has been merged. Good luck!

**Pull request merged**
