### PR TITLE
feat: presentation proposal

### PR DESCRIPTION
**Pull request by iabdelkareem**
# Assignment Proposal

## Title

Serverless Workflow Orchestration with AWS Step Functions

## Names and KTH ID

- Ibrahim Abdelkareem (iaiab@kth.se)

## Deadline

- Week 9

## Category

- Presentation

## Description

Serverless technologies are great but often developers want to orchestrate multiple actions as part of a business process in response to certain event. Orchestrating actions within a distributed systems can be challenging for many reasons such as:

- Often there're many actions involved (e.g., calls to serverless function, transforming event data, making decisions, ...etc.)
- The need for visual feedback to know which steps where executed successfully and which are not.
- Execution of long running tasks in serverless distributed environment.

In this presentation I'll show you what's AWS Step Functions, why you may need it, and how it can help you to orchestrate your serverless workload.

**Relevance**

Serverless technologies are relevant to DevOps.

### CODE REVIEW

**Comment by javierron** [comment]
Hello @iabdelkareem. Thanks for the proposal. 
There has been a similar presentation before in the course (see https://github.com/KTH/devops-course/pull/987).
I suggest that you find a more specific topic about GitOps. It can be a specific practice or tool, and deliver a deep dive into that.

**Comment by iabdelkareem** [comment]
Thanks for your feedback @javierron I've updated the PR to a more specific topic in GitOps

**Comment by javierron** [comment]
Hello @iabdelkareem, on the presentation [I referenced before](https://github.com/KTH/devops-course/blob/2021/contributions/presentation/week4/cpiehl-charande/GitOps.pdf) Those exact same topics were already covered.

**Comment by iabdelkareem** [comment]
Hi @javierron thank you for the feedback. I changed the topic completely from GitOps as I wasn't sure if there's anything else to cover that hasn't been part of previous contributions.

**Comment by javierron** [comment]
Hello @iabdelkareem. This topic is much more focused, and has not been presented before. Good luck with the presentation and demo.

**Pull request merged**
