### PR TITLE
Essay Proposal, Task 2 - madao

### PR DESCRIPTION
**Pull request by allandao**
# Assignment Proposal

## Title

Recognizing and Addressing the Risk Behind Open Source Dependencies

## Names and KTH ID

  - Minh Allan Dao (madao@kth.se)

## Deadline

- Deadline 2: Monday, April 24 @ 17h Stockholm Time

## Category

- Essay

## Description

With events such as the panic ensuing from the Log4j vulnerability, the spotlight has continued to focus on on the usage and often the dependency on open source work. With many dependencies maintained by small teams stretched thin, estimates that security flaws often may take 4-6 months to address, and the continual release of new features to meet demand without the addressing of current flaws and tech debt, there are countless reasons why open source dependencies used either directly or integrated into other packages and modules used in enterprise code and beyond may be vulnerable.

Although more automation is increasingly available to identify static errors and offer upgrade recommendations, dynamic dynamic platforms such as Java can load new code at runtime, which is an alternative way for bad actors to still run their malicious code. This is of particular interest due to heightened complexity. Of course, strategies such as organizational policy and monitoring are helpful, but we may focus in particular on dynamic analysis through a safe environment called a sandbox.

**Relevance**

From a DevOps perspective, we should be motivated find a way to automate as much as we can when it comes to open source dependency management, so that we can minimize the vulnerabilities possible. It is important to both be aware of what is vulnerable and address, so tooling and a culture of (automatically) examining and documenting open source work used in projects and pipelines is key. 

For example, a DevOps teams may opt to configure their VMSS via an image derived from the Github Actions public repository, which can be updated by anyone, anytime. Now the team would need to monitor both the pipelines they have configured and the VMSS agents that act on those pipelines, creating multiple layers of dependencies present. A project may not use all of the packages that such public images (such as the ones via Github Actions) include, as they are naturally not tailored to a particular project. This introduces vulnerability in the sense that there are unused dependencies that may always potentially become a risk in the future. In turn, the tackling of bloat is a key measure in reducing dynamic risk, as there are less variables at play. 

Finally, all of these recommendations augment a clean and clear environment to do dynamic testing. A tool of particular interest is Veracode Dynamic Analysis, a Dynamic Application Security Testing (DAST) solution for web applications. In addition, Eclipse Steady can examine compiled Java code and report vulnerabilities by examining "fix-commits".

Overall, the tooling we planning to use and we approach all of this ties into the active culture of DevSecOps.

### CODE REVIEW

**Comment by khesoem** [comment]
@allandao Try to be more specific. Name a number of tools, technologies, methods that you want to write about. Are the examples you have provided in the relevance section the technologies you want to focus on?

**Comment by allandao** [comment]
> @allandao Try to be more specific. Name a number of tools, technologies, methods that you want to write about. Are the examples you have provided in the relevance section the technologies you want to focus on?

Thanks for the information @khaes-kth.
I wanted to clarify both to provide better feedback and understand the essay. As for the essay guidelines, what is an "informative listing"?

**Comment by allandao** [comment]
> @allandao Try to be more specific. Name a number of tools, technologies, methods that you want to write about. Are the examples you have provided in the relevance section the technologies you want to focus on?

Thanks for the information @khaes-kth.
I wanted to clarify both to provide better feedback and understand the essay. As for the essay guidelines, what is an "informative listing"?

**Comment by khesoem** [comment]
A listing is usually a piece of code/algorithm/pseudo code. To be informative, means it should be relevant to the paper and help the reader better understand your essay.

**Comment by khesoem** [comment]
> I wanted to clarify both to provide better feedback and understand the essay.
Do you mean that you have already changed the readme include the information that I asked for?

**Comment by allandao** [comment]
> > I wanted to clarify both to provide better feedback and understand the essay.
> > Do you mean that you have already changed the readme include the information that I asked for?

Appreciate the information about a listing. I was able to update the README with more specifics about dynamic analysis and specific tooling following further research, albeit with some delays - thanks for your understanding.

**Comment by khesoem** [comment]
Hi @allandao 

I think you have just updated the description of this PR. The README file doesn't seem to be changed. For example, it doesn't talk about Veracode. Please update it as well.

**Comment by allandao** [comment]
[INTEND-TO-REPEAT-May-31-madao-essay.pdf](https://github.com/KTH/devops-course/files/11311694/INTEND-TO-REPEAT-May-31-madao-essay.pdf)

**Comment by allandao** [comment]
Rather than submitting a merge request to submit a proper PDF, commenting here that I intend to resubmit for failed task deadline due to personal issues that appeared, barring timely completion.

**Comment by bbaudry** [comment]
hi @allandao 
I acknowledge your message and your intention to submit your essay as a repeat.
I mark this in canvas.
Please submit your final essay no later than May 22.
Best
Benoit

**Comment by bbaudry** [comment]
hi @allandao
Can you confirm that you will submit this essay no later than May 22?
Best,
Benoit

**Pull request merged**
