### PR TITLE
Finished essay

### PR DESCRIPTION
**Pull request by dieflo4711**

### CODE REVIEW

**Comment by gluckzhang** [comment]
Thanks @dieflo4711 , super effective. I'll merge the PR first, while we TAs will grade it later. Before the deadline, feel free to update the submission if you need. Cheers.

**Comment by gluckzhang** [comment]
Hi @dieflo4711 , by the way, students are given the opportunity to receive specific feedback on their work, before the deadline. You could do a PR according to https://github.com/KTH/devops-course/blob/master/contributions/feedback-planning.md :)

**Comment by monperrus** [comment]
Monday is holiday, I'll give the feedback it on Tuesday April 14.

**Comment by monperrus** [comment]
Good job for a first version of the essay.

Major comments:

* define the concepts before talking about the implementation, add a new section (Sec 2) about the common concepts between Docker Swarm and K8S
* introduce more structure with subsections
* the conclusion mixes a comparison and concluding remarks; a conclusion must not contain new content, add a new section "Comparison" before the conclusion to compare both platforms.

See also comments in the PDF sent over email.

**Pull request merged**
