### PR TITLE
Finished Demo: Continous deployment with CircleCI and Google Kubernetes Enginge

### PR DESCRIPTION
**Pull request by jonasjohansson8908**
# Demo: Continous deployment with CircleCI and Google Kubernetes Enginge

## Members

Jonas Johansson, jonasjo5@kth.se

Github id: jonasjohansson8908

Marcus Jonsson Ewerbring, marcusew@kth.se

Github id: Marcus9512

## Links

**Youtube video**
https://youtu.be/QlPTto0A19c

**GitHub repository**
https://github.com/jonasjohansson8908/cd-demo

## About

We demonstrate how to integrate and use continous deployment on a GitHub repository with CircleCI.
The service is run in docker and is hosted on Google Cloud Platform, using Google Kubernetes Engine.

We show how new features can be delivered into an existing, running app.

We have provided a GitHub template repository together with our screencast. The viewer can fork the repo and follow the steps shown in the video. The screencast has sound to facilitate viewing the code and terminal use in the video.

### CODE REVIEW

**Comment by gynther-k** [comment]
I would like to give feedback on this demo.

**Comment by zen93** [comment]
I would like to give feedback.

**Comment by Callet91** [comment]
I would like to give feedback to this one as well

**Comment by GiorgosTagkoulis** [comment]
Hi, I would like to give feedback.

**Comment by ashgreyship** [comment]
I will give you feedback on the demo! :)

**Comment by ashgreyship** [comment]
The demonstration is to use CircleCI and Kubernetes engine for achieving continuous deployment. It is related to DevOps. This demonstration requires users to know using CircleCI, Docker, and Kubernetes. Thus, it is difficult to do. Before the demo, the author should write the basic knowledge which is required to understand and replicate this demo. It might be better to mention more details about the files in the cd-demo repository.This demo may not be original as it is available on the official website of CircleCI. The video is available on YouTube so that the user can play it and replicate it later. The Easter egg is also interesting. At the end of the demo, it is recommended to talk more about the advantages and disadvantages of Kubernetes and CircleCI.

**Comment by gynther-k** [comment]
Feedback:

Overall one of the best demos I have watched today. Very good flow and perfect audio quality that makes it easy to follow for a new user. Easy to understand conclusions and no unnecessary talking. Possible improvements could be providing links for inexperienced user for information about setting up Google Cloud, Github, Docker etc.

**Comment by Callet91** [comment]
# Feedback on Continuous deployment with CircleCI and GCP #753

|  | Yes | No | Remarkable |
| ------ | ------ | ------ | ------ |
| The demonstration screencast is clearly motivated (why it matters for Devops?)| Yes| | |
|The demonstration screencast is difficult to do| | | Remarkable|
|The demonstration screencast is original|Yes|||
|The demonstration screencast is sublime (eg visually appealing)| | | Remarkable |
|The demonstration screencast contains an easter egg|Yes | | |
|An accompanying Github repository has been made (optional)| | | Remarkable|

### Motivation:
**The demonstration screencast is clearly motivated (why it matters for Devops?)** 
It is not explicitly motivated in the video, however, if you know what DevOps is you know that this demo is motivated. 

**The demonstration screencast is difficult to do**
The demo covers many aspects in DevOps such as CI/CD, GCP, Docker and kubernetes. Also, by having written a website as well increases the quality of the demo to resemble a real life implementation. AND, the template is great, thinking of using it in the Deep Learning course.

**The demonstration screencast is original**
If you search for CircleCI and GCP on youtube, the video does not show up (even if this is a bad metric on originality). There are many similar videos that illustrate how to set up a CI/CD pipeline with CirclCI and also many videos on how to deploy to GCP, but there is not any particular video showing the combo that is used in this video.
 The demonstration screencast is sublime (eg visually appealing)
Good sound quality, great video quality. Easy to follow along with the video. Good job!

**The demonstration screencast contains an easter egg**
It has, however, i didn't notice it, but that is the point with easter eggs, not everyone should notice it right.

**An accompanying Github repository has been made (optional)**
The repo is well structured and the readme looks professional. 

### Suggestions on changes/additions
- 0.29 Highlight/zoom in on "use this template".
- 3.13-3.20 it goes a little bit fast, maybe slow down and add highlights to make it easier to see what is going on.
- Yeah, the same goes for setting up the variables and rerun. You have 8 seconds to use so I know it can be hard 3.24-3.42.

**Comment by zen93** [comment]
Feedback: I'm nitpicking here but, the lack of mouse pointer makes us focus extra hard on which things are being clicked. Overall, the demo was great.

**Comment by GiorgosTagkoulis** [comment]
Thank you for a nice explanatory demo. I found the topic very interesting. Some comments are:
- it explains every step in the process. I feel like it is easy to reproduce it for another app by following the screen-cast
- The video technically was very good. Maybe a different style for the subtitles could make it even better, so it does not cover big part of the lower screen (not a problem though)

**Comment by jonasjohansson8908** [comment]
@ashgreyship

Thank you for the feedback!

We'd love to explain everything a bit more in-depth but found it hard to do so in order to meet the 5 minute requirement of the assignment. As you mention, there are quite a lot of information on CircleCI on how to make the configuration files, we therefore chose to focus on putting everything toghether. We might add links where the viewer can find more information about CircleCI, Docker and GKE. We do list them as prerequisites in the readme of the repository.
Thank you for the input :)

**Comment by jonasjohansson8908** [comment]
@gynther-k 

Thank you for the feedback and kind words!

Adding links is a really good idea! We might do that to the youtube-description and readme of the repository.

**Comment by jonasjohansson8908** [comment]
@Callet91 

Thank you for the very detailed and constructive feedback!

Actually, the reason for the video not being searchable is that we selected an option where it do not come up in searches. You have to have the link to find it.

Zooming on the "use this template" is a good idea, we will also look into if it is possible to extend the other parts you mentioned.

Thanks!

**Comment by jonasjohansson8908** [comment]
@zen93 

That is a good point. Actually, not having a mouse pointer is a trade-off that me and @Marcus9512 discussed when recording. As we have most scenes at double or triple speed, we found it hard to include the mouse pointer, while having it smooth and not distracting.

Thank you!

**Comment by jonasjohansson8908** [comment]
@GiorgosTagkoulis 

Thank you for the feedback!

We have experimented with the subtitles a lot and chose to have them quite big, but not in the way. The reason for this is so the user can have a smaller window with the video while following the steps shown. It is a good point though and we will look into having them smaller.

Thanks!

**Pull request merged**
